export const LESSONS = [
  {
    id: 't14-a',
    title: '四种收敛的严格定义与蕴含关系',
    subtitle: '从精确定义到反例——打字机序列、尖峰序列与收敛关系图',
    intro: [
      {
        title: '引入：为什么要精确区分四种收敛？',
        body: '第 9b 章引入了四种收敛的直觉，现在要精确化。动机：在 CLT 中 Zₙ →d N(0,1)，能否断言 Zₙ 逐点趋于某固定随机变量？答案是否，因为依分布是最弱的——它根本不要求 Xₙ 和 X 在同一概率空间上，更不要求轨道接近。在统计中，大数定律给出 σ̂ₙ →P σ，为什么这足以让我们用 σ̂ₙ 替换 CLT 中的 σ？答案是 Slutsky 定理。精确区分四种收敛，是读懂所有渐近统计结论的基础。',
        tip: '每种收敛模式回答不同的问题——精确化它们，才能知道一个定理的结论有多强、能怎么用。',
      },
      {
        title: '依概率收敛：精确定义与运算规则',
        body: '定义：Xₙ →P X，若对任意 ε>0，P(|Xₙ−X|>ε)→0（n→∞）。等价刻画：(1) P(|Xₙ−X|≤ε)→1；(2) 对任意 ε,δ>0，存在 N 使 n>N 时 P(|Xₙ−X|>ε)<δ。运算规则（命题）：若 Xₙ →P X，Yₙ →P Y，则：aXₙ+bYₙ →P aX+bY（线性）；XₙYₙ →P XY（乘积）；g 连续时 g(Xₙ) →P g(X)（CMT）；若 P(Y=0)=0，则 Xₙ/Yₙ →P X/Y（商）。重要警告：Xₙ →P 0 不能推出 E[Xₙ]→0（期望不能在极限号下移动，需要一致可积性）。',
        formula: 'X_n \\xrightarrow{P} X \\;\\Longleftrightarrow\\; \\lim_{n\\to\\infty} P\\!\\left(|X_n-X|>\\varepsilon\\right)=0 \\quad \\forall\\varepsilon>0',
        tip: '依概率收敛不保证期望收敛——这是最容易忽视的限制。反例：P(Xₙ=n)=1/n，Xₙ→P 0 但 E[Xₙ]=1。',
      },
      {
        title: '依分布收敛：Portmanteau 定理与等价刻画',
        body: '定义：Xₙ →d X，若在 F 的所有连续点 x 处，Fₙ(x)→F(x)（n→∞）。只在连续点要求：分布函数可能有跳跃（离散分布），跳跃点处即使整体收敛也可能 Fₙ(x) ≠ F(x)，故"连续点处收敛"是自然的选择。Portmanteau 定理（等价刻画）：①Fₙ(x)→F(x) 连续点；② 所有有界连续函数 f，E[f(Xₙ)]→E[f(X)]；③ 所有闭集 F，limsup P(Xₙ∈F)≤P(X∈F)；④ 所有开集 G，liminf P(Xₙ∈G)≥P(X∈G)；⑤ 对 P(X∈∂B)=0 的 Borel 集 B，P(Xₙ∈B)→P(X∈B)。Lévy 连续性定理：Xₙ →d X ⟺ 特征函数逐点收敛 φₙ(t)→φ(t)（且 φ 在 0 处连续）。',
        formula: 'X_n \\xrightarrow{d} X \\;\\Longleftrightarrow\\; F_n(x) \\to F(x) \\text{ 在 } F \\text{ 的所有连续点处}',
        tip: '依分布收敛不要求 Xₙ 和 X 在同一概率空间上——它只是"分布函数形状趋同"，与路径无关。',
      },
      {
        title: '几乎必然收敛：路径层面的定义与等价刻画',
        body: '定义：Xₙ →a.s. X，若 P(lim_{n→∞} Xₙ = X) = 1，等价于 P({ω: Xₙ(ω)→X(ω)}) = 1。用 limsup 改写：Xₙ →a.s. X ⟺ 对任意 ε>0，P(limsup_{n→∞}{|Xₙ−X|>ε})=0，即 P(∩_{N=1}^∞ ∪_{n=N}^∞{|Xₙ−X|>ε})=0。等价刻画（命题）：Xₙ →a.s. X ⟺ 对任意 ε>0，P(sup_{k≥n}|Xₖ−X|>ε)→0（n→∞）。对比依概率：依概率只要求第 n 个大错概率趋零，几乎必然要求"之后所有项都接近"的概率趋一。',
        formula: 'X_n \\xrightarrow{a.s.} X \\;\\Longleftrightarrow\\; P\\!\\left(\\sup_{k\\ge n}|X_k - X| > \\varepsilon\\right) \\to 0 \\quad \\forall\\varepsilon>0',
        tip: '几乎必然的等价刻画 P(sup_{k≥n}|Xₖ−X|>ε)→0 说明：不只是第 n 步，而是 n 之后的所有步都要接近——这比依概率（只管第 n 步）强得多。',
      },
      {
        title: 'L^p 收敛与均方收敛',
        body: '定义：Xₙ →L^p X，若 E[|Xₙ−X|^p]→0（p≥1）。均方收敛（p=2）：E[(Xₙ−X)²]→0，即 Var(Xₙ−X)+(E[Xₙ]−E[X])²→0。关系：L^p → L^q（p≥q，由 Jensen）；L^p → P（由马尔可夫：P(|Xₙ−X|>ε)≤E[|Xₙ−X|^p]/ε^p→0）。L^p 的好处：若 Xₙ →L^p X，则期望可以在极限号下移动——E[Xₙ]→E[X]（由 Hölder）。WLLN 的 L² 版本：E[(X̄ₙ−μ)²]=σ²/n→0，即 X̄ₙ →L² μ，比 WLLN（→P）更强一档。',
        formula: 'X_n \\xrightarrow{L^p} X \\;\\Rightarrow\\; X_n \\xrightarrow{L^q} X \\;(p\\ge q),\\quad X_n \\xrightarrow{L^p} X \\;\\Rightarrow\\; X_n \\xrightarrow{P} X',
        tip: 'L^p 收敛最大的优势：期望可以在极限号下移动（E[Xₙ]→E[X]），这是依概率收敛做不到的。',
      },
      {
        title: '蕴含关系总图与反例',
        body: '蕴含关系：a.s. ⟹ P ⟹ d；L^r ⟹ L^q（r≥q） ⟹ P ⟹ d。以下方向一般不成立（各有标准反例）：①P 不蕴含 a.s.：打字机序列（Xₙ =1_{[j/2^k,(j+1)/2^k]}，→P 0 但不 →a.s. 0）；② a.s. 不蕴含 L¹：尖峰序列（Xₙ = n·1_{[0,1/n]}，→a.s. 0 但 E[Xₙ]=1）；③ d 不蕴含 P：Xₙ ~ N(0,1) 独立（→d N(0,1) 但 P(|Xₙ−Z|>ε) 可能不趋零）；④ P 不蕴含 L^p：尖峰类型（P(Xₙ=n²)=1/n²，→P 0 但 E[Xₙ²]=n²）。特殊等价：Xₙ →d c（常数）⟺ Xₙ →P c——这是依分布升级为依概率的唯一一般情形。',
        tip: '打字机反例背熟：→P 但不 →a.s.。尖峰反例背熟：→a.s. 但不 →L¹。这两个是最重要的反例。',
      },
      {
        title: 'Borel-Cantelli 引理：从级数到 a.s. 收敛',
        body: 'Borel-Cantelli 第一引理：若 Σ P(Aₙ) < ∞，则 P(lim sup Aₙ) = 0（即无穷多个 Aₙ 同时发生的概率为零）。推论（a.s. 收敛的充分条件）：若对每个 ε>0，Σ P(|Xₙ−X|>ε) < ∞，则 Xₙ →a.s. X。第二引理：若 Aₙ 相互独立且 Σ P(Aₙ) = ∞，则 P(lim sup Aₙ) = 1（几乎必然发生无穷次）。应用：SLLN 的证明（四阶矩条件版）：E[X̄ₙ⁴] = O(1/n²)，Σ E[X̄ₙ⁴] < ∞，由 Borel-Cantelli 得 X̄ₙ →a.s. 0（均值零化后）。',
        formula: '\\sum_{n=1}^\\infty P(A_n) < \\infty \\;\\Rightarrow\\; P\\!\\left(\\limsup_{n\\to\\infty} A_n\\right) = 0',
        tip: 'Borel-Cantelli 判断 a.s. 收敛：把"坏事件概率的级数"求和，收敛则几乎必然只有有限次坏事件。',
      },
    ],
    questions: [
      {
        type: 'choice',
        prompt: '"打字机序列" Xₙ = 1_{[j/2^k,(j+1)/2^k]} 的哪个收敛结论正确？',
        options: [
          'Xₙ →a.s. 0 但不 →P 0',
          'Xₙ →P 0 但不 →a.s. 0',
          'Xₙ →L¹ 0 但不 →P 0',
          'Xₙ →d 0 但不 →P 0',
        ],
        answer: 1,
        explain: '打字机序列：每个区间长度趋于 0，故 P(Xₙ=1)→0，Xₙ →P 0。但对任意 ω∈[0,1]，ω 被无穷多区间覆盖，故 Xₙ(ω)=1 无穷次出现，Xₙ(ω) 不收敛到 0，即 Xₙ 不 →a.s. 0。这是"依概率不蕴含几乎必然"的经典反例。',
      },
      {
        type: 'judge',
        prompt: '若 Xₙ →a.s. X，则一定有 Xₙ →L¹ X，这个说法正确吗？',
        answer: false,
        explain: '错误。a.s. 不蕴含 L¹。反例：Xₙ = n·1_{[0,1/n]}（在[0,1]上，Lebesgue 测度）。对 ω>0，当 n>1/ω 时 Xₙ(ω)=0，故 Xₙ →a.s. 0。但 E[Xₙ] = n·(1/n) = 1 不趋于 0，故 Xₙ 不 →L¹ 0。需要一致可积性才能从 a.s. 升级到 L¹。',
      },
      {
        type: 'choice',
        prompt: '依分布收敛 Xₙ →d X 与依概率收敛 Xₙ →P X 等价的情形是：',
        options: [
          '当 X 服从正态分布时',
          '当 X 是常数时',
          '当 Xₙ 有界时',
          '当 Xₙ i.i.d. 时',
        ],
        answer: 1,
        explain: '定理：Xₙ →d c（常数）⟺ Xₙ →P c。当极限是常数时，依分布与依概率等价。这是唯一一般成立的等价情形。其他情况（X 非常数）一般有 P ⟹ d 但 d 不蕴含 P。',
      },
      {
        type: 'input',
        prompt: '设 P(Aₙ) = 1/n²。判断：P(lim sup Aₙ)（无穷多个 Aₙ 同时发生的概率）等于多少？',
        accept: ['0', '零'],
        explain: 'Σ P(Aₙ) = Σ 1/n² = π²/6 < ∞。由 Borel-Cantelli 第一引理，P(lim sup Aₙ) = 0，即以概率 1 只有有限个 Aₙ 发生（有限次之后 Aₙ 不再出现）。若 P(Aₙ) = 1/n，Σ 1/n = ∞，若还有独立性则 P(lim sup Aₙ) = 1（第二引理）。',
      },
      {
        type: 'judge',
        prompt: '依概率收敛 Xₙ →P X 蕴含存在子列 Xₙₖ →a.s. X，这个说法正确吗？',
        answer: true,
        explain: '正确，这是"子列原理"（Subsequence principle）。Xₙ →P X 等价于：对 Xₙ 的任意子列，都存在进一步的子列几乎必然收敛到 X。这是连接依概率和几乎必然的重要工具，也是"依概率收敛 ⟹ 依分布收敛"证明的关键一步（通过特征函数的逐子列论证）。',
      },
      {
        type: 'choice',
        prompt: 'Portmanteau 定理的等价刻画中，以下哪项不是 Xₙ →d X 的等价条件？',
        options: [
          '对所有有界连续函数 f，E[f(Xₙ)] → E[f(X)]',
          '对所有 Borel 集 B，P(Xₙ∈B) → P(X∈B)',
          '在 F 的所有连续点 x 处，Fₙ(x) → F(x)',
          '特征函数 φₙ(t) → φ(t) 逐点（且 φ 在 0 连续）',
        ],
        answer: 1,
        explain: '(B) 不正确。正确条件是对满足 P(X∈∂B)=0 的 Borel 集 B，P(Xₙ∈B)→P(X∈B)——要求 B 的边界有零概率。对所有 Borel 集成立是更强的要求，一般不成立（因为在跳跃点处 Fₙ 可能不收敛）。(A)(C)(D) 都是正确的等价刻画。',
      },
      {
        type: 'match',
        prompt: '将反例与其说明的"不蕴含"方向配对：',
        left: ['打字机序列（移动指示器）', '尖峰序列 n·1_{[0,1/n]}', 'P(Xₙ=n²)=1/n²，P(Xₙ=0)=1−1/n²', 'Xₙ~N(0,1) 独立'],
        right: [
          'd 不蕴含 P（极限非常数时）',
          'P 不蕴含 a.s.',
          'a.s. 不蕴含 L¹',
          'P 不蕴含 L²',
        ],
        answer: [1, 2, 3, 0],
        explain: '打字机：→P 0 但不 →a.s. 0（P 不蕴含 a.s.）；尖峰：→a.s. 0 但 E[Xₙ]=1 不趋零（a.s. 不蕴含 L¹）；P(Xₙ=n²)=1/n²：→P 0（坏事件概率趋零）但 E[Xₙ²]=n²→∞（不 →L²）；独立 N(0,1)：→d N(0,1) 但 P(|Xₙ−Z|>ε) 不趋零（d 不蕴含 P，极限非常数）。',
      },
      {
        type: 'judge',
        prompt: 'L^p 收敛（p≥q≥1 时 L^p ⟹ L^q）的理论依据是 Jensen 不等式，这个说法正确吗？',
        answer: true,
        explain: '正确。对凸函数 φ(x)=x^{q/p}（当 q<p 时 q/p<1 是凹函数，但对期望的方向是 ||X||_q ≤ ||X||_p），由 Hölder 不等式：E[|X|^q] = E[|X|^q·1] ≤ (E[|X|^p])^{q/p}·1^{p/(p-q)} = ||X||_p^q。故 ||Xₙ−X||_q ≤ ||Xₙ−X||_p → 0，L^p 收敛蕴含 L^q 收敛（p≥q）。',
      },
    ],
  },
  {
    id: 't14-b',
    title: 'Slutsky 定理、CMT 与 Delta 方法',
    subtitle: '收敛性的"传递工具"——统计渐近推断的核心引理',
    intro: [
      {
        title: 'Slutsky 定理：依分布 + 依概率 → 依分布',
        body: 'Slutsky 定理：若 Xₙ →d X，Yₙ →P c（常数），则 Xₙ+Yₙ →d X+c，Xₙ·Yₙ →d c·X。关键：Yₙ 必须依概率收敛到常数，不能是随机变量。若 Yₙ →d Y（非常数），结论依赖联合分布（仅知边际不够），一般不成立。典型用途：CLT 给出 √n(X̄ₙ−μ) →d N(0,σ²)；大数定律给出 σ̂ₙ →P σ（常数）；Slutsky 推出 √n(X̄ₙ−μ)/σ̂ₙ →d N(0,1)——这是 t 统计量渐近正态的标准证明，实践中用样本方差代替总体方差仍渐近正态。',
        formula: 'X_n \\xrightarrow{d} X,\\; Y_n \\xrightarrow{P} c \\;\\Rightarrow\\; X_n + Y_n \\xrightarrow{d} X+c,\\quad X_n Y_n \\xrightarrow{d} cX',
        tip: 'Slutsky 的关键限制：Yₙ 必须 →P 常数，不能是 →d 随机变量。混用这两种条件是常见错误。',
      },
      {
        title: 'Slutsky 定理应用：t 统计量渐近正态',
        body: '题目：Xᵢ iid，E[Xᵢ]=μ，Var(Xᵢ)=σ²<∞，σ 未知。设样本方差 σ̂ₙ² = (1/n)Σ(Xᵢ−X̄ₙ)²。证 Tₙ = √n(X̄ₙ−μ)/σ̂ₙ →d N(0,1)。思路：第一步（CLT）：√n(X̄ₙ−μ) →d N(0,σ²)，即分子 →d N(0,σ²)。第二步（WLLN+CMT）：σ̂ₙ² = (1/n)ΣXᵢ² − X̄ₙ² →P σ²（SLLN 两项）；由 CMT（g(x)=√x，x=σ²>0 处连续），σ̂ₙ →P σ，即 1/σ̂ₙ →P 1/σ。第三步（Slutsky）：Tₙ = √n(X̄ₙ−μ)·(1/σ̂ₙ) →d N(0,σ²)·(1/σ) = N(0,1)。',
        steps: [
          'CLT：√n(X̄ₙ−μ) →d N(0,σ²)（分子的渐近分布）',
          'WLLN+CMT：σ̂ₙ →P σ，故 1/σ̂ₙ →P 1/σ（分母依概率趋常数）',
          'Slutsky：乘积形式 →d N(0,σ²)·(1/σ) = N(0,1)',
        ],
        tip: '这是统计学中最重要的渐近结果之一：即使 σ 未知，用 σ̂ₙ 替代后 t 统计量仍渐近 N(0,1)，为大样本 z 检验提供依据。',
      },
      {
        title: '连续映射定理（CMT）：收敛穿越连续函数',
        body: 'CMT（定理）：若 Xₙ →d X，g 是连续函数（或在 X 几乎必然取值的点处连续，即 P(X∈Disc(g))=0），则 g(Xₙ) →d g(X)。对 →P 和 →a.s. 同样成立（证明更直接）。应用实例：(1) CLT 给 Zₙ →d N(0,1)，g(x)=x² 连续，故 Zₙ² →d χ²(1)。(2) 大数定律给 X̄ₙ →P μ，g(x)=e^x 连续，故 e^{X̄ₙ} →P e^μ。(3) 大数定律给 σ̂ₙ² →P σ²，g(x)=√x 在 x=σ²>0 连续，故 σ̂ₙ →P σ。使用 CMT 时注意：g 在极限取值点 X 必须连续，若 P(X=不连续点)>0 则 CMT 不成立（如 g(x)=1_{x>0} 在 0 点间断）。',
        formula: 'X_n \\xrightarrow{d/P/a.s.} X,\\; g \\text{ 连续} \\;\\Rightarrow\\; g(X_n) \\xrightarrow{d/P/a.s.} g(X)',
        tip: 'CMT 让收敛"穿越"连续函数不变——这是渐近统计中从已知收敛推出新收敛的核心工具。',
      },
      {
        title: 'Delta 方法：非线性变换的渐近分布',
        body: 'Delta 方法（定理）：若 √n(Xₙ−θ) →d N(0,σ²)，g 在 θ 处可微且 g\'(θ) ≠ 0，则 √n(g(Xₙ)−g(θ)) →d N(0, [g\'(θ)]²σ²)。证明思路：Taylor 展开 g(Xₙ) ≈ g(θ) + g\'(θ)(Xₙ−θ)，√n(g(Xₙ)−g(θ)) ≈ g\'(θ)·√n(Xₙ−θ) →d g\'(θ)·N(0,σ²) = N(0,[g\'(θ)]²σ²)，余项 o(|Xₙ−θ|)·√n →P 0（Slutsky 处理）。应用：CLT 给 √n(X̄ₙ−μ) →d N(0,σ²)，g(x)=e^x，g\'(μ)=e^μ，Delta 方法给 √n(e^{X̄ₙ}−e^μ) →d N(0, e^{2μ}σ²)。',
        formula: '\\sqrt{n}(X_n-\\theta)\\xrightarrow{d}\\mathcal{N}(0,\\sigma^2),\\;g\'(\\theta)\\ne 0 \\;\\Rightarrow\\; \\sqrt{n}(g(X_n)-g(\\theta))\\xrightarrow{d}\\mathcal{N}(0,[g\'(\\theta)]^2\\sigma^2)',
        tip: 'Delta 方法公式：直接在方差上乘 [g\'(θ)]²。g\'(θ) 是"放大倍率"——函数在 θ 处的斜率决定了渐近方差的大小。',
      },
      {
        title: 'Delta 方法：二阶情形（g\'(θ)=0 时）',
        body: '若 g\'(θ)=0，则一阶 Delta 方法给出零渐近分布，需要二阶展开。二阶 Delta 方法：若 √n(Xₙ−θ) →d N(0,σ²)，g\'(θ)=0，g 在 θ 处二阶可微，g\'\'(θ) ≠ 0，则 n(g(Xₙ)−g(θ)) →d (1/2)g\'\'(θ)·σ²·χ²(1)（因为 N(0,1)²  ~ χ²(1)）。直觉：当一阶项消失，主导项是二阶项，变换"慢了一拍"，需要 n 而非 √n 的标准化，极限分布变成 χ²(1) 形状而非正态。应用：若 X̄ₙ →P 0（μ=0），考虑 g(x)=x²，g\'(0)=0，g\'\'(0)=2，Delta 二阶给 n·X̄ₙ² →d σ²·χ²(1)。',
        formula: 'g\'(\\theta)=0,\\; g\'\'(\\theta)\\ne 0 \\;\\Rightarrow\\; n(g(X_n)-g(\\theta)) \\xrightarrow{d} \\frac{1}{2}g\'\'(\\theta)\\cdot\\sigma^2\\cdot\\chi^2(1)',
        tip: 'g\'(θ)=0 时标准化速率从 √n 变为 n，极限分布从正态变为 χ²(1)——这是统计推断中"退化"情形的典型处理。',
      },
      {
        title: 'Skorokhod 表示定理：把依分布"提升"到 a.s.',
        body: 'Skorokhod 表示定理：若 Xₙ →d X（取值于可分度量空间），则存在定义在同一概率空间上的随机变量 X̃ₙ 和 X̃，使得 X̃ₙ 与 Xₙ 同分布，X̃ 与 X 同分布，且 X̃ₙ →a.s. X̃。用途：在依分布层面做的运算，通过 Skorokhod 可以"搬"到 a.s. 层面计算（更方便），结论再翻译回分布层面。注意：搬运后只保证分布相同，不保证原概率空间结构不变，所以只能得分布层面的结论（不能得依概率或 a.s. 结论）。典型应用：CMT 的证明——借助 Skorokhod 将 →d 转化为 →a.s. 再通过普通连续函数极限性质得到结论。',
        formula: 'X_n \\xrightarrow{d} X \\;\\Rightarrow\\; \\exists\\; \\tilde{X}_n \\overset{d}{=} X_n,\\; \\tilde{X} \\overset{d}{=} X,\\; \\tilde{X}_n \\xrightarrow{a.s.} \\tilde{X}',
        tip: 'Skorokhod 是"把 →d 升级成 →a.s. 在新空间计算，再翻译回来"的技巧。结论只能是分布层面的，不是原空间的 a.s. 结论。',
      },
      {
        title: '易错点与条件反射训练',
        body: '① Slutsky 中 Yₙ 必须 →P 常数：若 Yₙ →d 非常数，结论依赖联合分布，不能直接套 Slutsky。② CMT 需要 g 在极限取值点处连续：g(x)=1/x 在 x=0 不连续，若 P(X=0)>0 则不能用 CMT。③ Delta 方法的方差公式：渐近方差 = [g\'(θ)]²σ²，不是 g\'(θ)·σ 或 g\'(θ)·σ²/n。④ 一阶 Delta 方法失效：g\'(θ)=0 时不能用一阶公式，需要二阶，且极限分布变为 χ²(1) 型，不再是正态。⑤ Skorokhod 搬运后的限制：在新空间有 →a.s.，但不能把这个 →a.s. 翻译回原空间，只能翻译成原空间的 →d 结论。',
        reveal: {
          q: 'Zₙ →d N(0,1)，g(x) = |x|。g(Zₙ) 收敛到什么分布？',
          a: 'g(x)=|x| 在 x=0 处连续（但不可微）。CMT 适用于连续函数，故 g(Zₙ)=|Zₙ| →d |Z|，其中 Z~N(0,1)，|Z| 服从半正态分布（折叠正态）。注意：CMT 要求 g 连续，不需要可微，所以 |x| 在 x=0 的不可微不影响结论。',
        },
      },
    ],
    questions: [
      {
        type: 'choice',
        prompt: 'Slutsky 定理的正确陈述是：',
        options: [
          'Xₙ →d X，Yₙ →d Y ⟹ Xₙ+Yₙ →d X+Y',
          'Xₙ →d X，Yₙ →P c（常数）⟹ XₙYₙ →d cX',
          'Xₙ →P X，Yₙ →d c ⟹ Xₙ+Yₙ →d X+c',
          'Xₙ →d X，Yₙ →d Y ⟹ XₙYₙ →d XY',
        ],
        answer: 1,
        explain: '(B) 正确。Slutsky 要求其中一个序列（Yₙ）依概率收敛到常数 c，然后可以推出乘积/和的依分布极限。(A)(D) 中 Yₙ →d Y（非常数），结论依赖联合分布，不能直接得出。(C) 混淆了 Xₙ 和 Yₙ 的角色。',
      },
      {
        type: 'input',
        prompt: 'CLT：√n(X̄ₙ−μ) →d N(0,σ²)。取 g(x)=x²，g\'(μ)=2μ，Delta 方法给出 √n(X̄ₙ²−μ²) →d N(0, ?)。设 μ≠0，问渐近方差填什么？（用 μ 和 σ 表示，如 4μ²σ²）',
        accept: ['4μ²σ²', '(2μ)²σ²', '4*μ²*σ²', '4μ^2σ^2'],
        explain: 'Delta 方法：渐近方差 = [g\'(μ)]²σ² = (2μ)²σ² = 4μ²σ²。即 √n(X̄ₙ²−μ²) →d N(0, 4μ²σ²)。当 μ=0 时 g\'(0)=0，一阶方法失效，需要二阶 Delta 方法，极限变为 χ²(1) 型。',
      },
      {
        type: 'judge',
        prompt: '连续映射定理（CMT）对依分布、依概率、几乎必然三种收敛都适用，这个说法正确吗？',
        answer: true,
        explain: '正确。若 g 在 X 几乎必然取值的点处连续，则 Xₙ →d X 蕴含 g(Xₙ) →d g(X)；Xₙ →P X 蕴含 g(Xₙ) →P g(X)；Xₙ →a.s. X 蕴含 g(Xₙ) →a.s. g(X)。三种收敛都保持连续变换——这使 CMT 成为通用工具。',
      },
      {
        type: 'choice',
        prompt: '若 g\'(θ)=0 而 g\'\'(θ)≠0，Delta 方法（二阶）给出：',
        options: [
          '√n(g(Xₙ)−g(θ)) →d N(0, g\'\'(θ)²σ²)',
          'n(g(Xₙ)−g(θ)) →d (1/2)g\'\'(θ)·σ²·χ²(1)',
          '√n(g(Xₙ)−g(θ)) →d 0',
          'g(Xₙ) →P g(θ)（无法得到渐近分布）',
        ],
        answer: 1,
        explain: '二阶 Delta 方法：g\'(θ)=0 时，一阶项消失，Taylor 展开主导项是 (1/2)g\'\'(θ)(Xₙ−θ)²。因 √n(Xₙ−θ) →d N(0,σ²)，故 n(Xₙ−θ)² →d σ²·Z²（Z~N(0,1)），Z² ~ χ²(1)。结论：n(g(Xₙ)−g(θ)) →d (1/2)g\'\'(θ)·σ²·χ²(1)。注意标准化速率变为 n（不是 √n），极限变为 χ²(1)。',
      },
      {
        type: 'judge',
        prompt: 'Slutsky 定理中，若 Yₙ →d N(0,1)（非常数），则 Xₙ+Yₙ →d X+N(0,1) 成立，这个说法正确吗？',
        answer: false,
        explain: '错误。Slutsky 要求 Yₙ →P 常数 c，才能得出 Xₙ+Yₙ →d X+c。若 Yₙ →d Y（Y 非常数），结论取决于 (Xₙ,Yₙ) 的联合分布，仅知道边际分布 Xₙ→X 和 Yₙ→Y 不够。反例：Xₙ=Z（固定 N(0,1)），Yₙ=−Z，则 Yₙ→d N(0,1) 但 Xₙ+Yₙ=0（常数），不是 N(0,1)+N(0,1) 的卷积。',
      },
      {
        type: 'match',
        prompt: '将工具与其对应的用途配对：',
        left: ['Slutsky 定理', 'Delta 方法', '连续映射定理（CMT）', 'Skorokhod 表示定理'],
        right: [
          '把依分布收敛"搬"到同一概率空间变成几乎必然收敛，方便计算后翻译回来',
          'g 连续时，收敛穿越 g 不改变收敛类型（d/P/a.s.）',
          'CLT + σ̂ₙ →P σ → t 统计量渐近正态 N(0,1)',
          '由 √n(Xₙ−θ) →d N(0,σ²) 推出 g(Xₙ) 的渐近方差为 [g\'(θ)]²σ²',
        ],
        answer: [2, 3, 1, 0],
        explain: 'Slutsky：合并 →d 和 →P 常数，推出乘/加积的渐近分布（t 统计量例子）；Delta 方法：非线性变换后的渐近方差乘 [g\'(θ)]²；CMT：连续函数穿越收敛；Skorokhod：把 →d 提升到新空间的 →a.s. 再翻译。',
      },
      {
        type: 'choice',
        prompt: '设 X̄ₙ →d N(μ, σ²/n)，用 Delta 方法求 log(X̄ₙ)（设 μ>0）的渐近分布，渐近方差是：',
        options: [
          '(1/μ)·σ²/n',
          '(1/μ)²·σ²',
          '(1/μ)·σ²',
          '(log μ)²·σ²/n',
        ],
        answer: 1,
        explain: '更准确地应写：√n(X̄ₙ−μ) →d N(0,σ²)，g(x)=log x，g\'(μ)=1/μ。Delta 方法：渐近方差 = [g\'(μ)]²σ² = (1/μ)²σ² = σ²/μ²。故 √n(log X̄ₙ − log μ) →d N(0, σ²/μ²)。注意这里的渐近方差是 σ²/μ²，不含 n（n 已经被 √n 标准化吸收）。',
      },
      {
        type: 'judge',
        prompt: '依分布收敛 Xₙ →d X 的证明中，一般优先用特征函数方法（Lévy 连续性定理），而不是直接验证分布函数逐点收敛，这个说法正确吗？',
        answer: true,
        explain: '正确。特征函数方法通常更方便：(1) 对独立随机变量，特征函数分解为乘积；(2) Taylor 展开特征函数比展开分布函数容易；(3) Lévy 连续性定理保证：特征函数逐点收敛（且极限在 0 处连续）即等价于依分布收敛。CLT 的证明就是先展开特征函数（Taylor 到二阶），证逐点收敛到 e^{−t²/2}，再引用 Lévy 定理。',
      },
    ],
  },
]
