export const LESSONS = [
  {
    id: 't18-a',
    title: '矩估计与最大似然估计（MLE）',
    subtitle: '从"用样本猜总体"到似然函数最大化——两大点估计方法的动机与推导',
    intro: [
      {
        title: '引入：用什么猜总体均值？',
        body: '设 $X_1,\\ldots,X_n$ 是来自总体的样本，总体均值 $\\mu$ 未知。最自然的猜测是样本均值 $\\bar{X}=\\frac{1}{n}\\sum X_i$。为什么？大数定律保证了 $\\bar{X}\\xrightarrow{P}\\mu$——样本量越大，样本均值越接近总体均值。这就是**矩估计法**的核心思想：用样本矩代替总体矩，"样本均值 $=$ 总体均值"建立方程，解出参数。但总体矩 $\\mu_k=E[X^k]$ 是参数 $\\theta$ 的函数，方程解出的 $\\hat{\\theta}$ 就是矩估计量。矩估计简单、通用，但不一定是"最好"的估计——它没有充分利用分布的具体形式。',
        tip: '矩估计不要求知道分布全貌，只要知道前若干阶矩即可，但也因此损失了分布的"形状信息"，统计效率通常不是最优的。',
      },
      {
        title: '矩估计法的一般步骤',
        body: '设总体分布含 $m$ 个未知参数 $\\theta_1,\\ldots,\\theta_m$。步骤一：计算前 $m$ 阶总体矩，写成参数的函数：$\\mu_k=E[X^k]=g_k(\\theta_1,\\ldots,\\theta_m)$，$k=1,\\ldots,m$。步骤二：令总体矩等于对应的样本矩：$g_k(\\theta_1,\\ldots,\\theta_m)=\\hat{\\mu}_k=\\frac{1}{n}\\sum_{i=1}^n X_i^k$。步骤三：解 $m$ 个方程组，得到 $\\hat{\\theta}_1,\\ldots,\\hat{\\theta}_m$ 即为矩估计量。常用结论：正态 $\\mathcal{N}(\\mu,\\sigma^2)$ 的矩估计为 $\\hat{\\mu}=\\bar{X}$，$\\hat{\\sigma}^2=\\frac{1}{n}\\sum(X_i-\\bar{X})^2$（分母为 $n$，有别于样本方差 $S^2$ 的分母 $n-1$）。指数分布 $\\mathrm{Exp}(\\lambda)$ 的矩估计：$E[X]=1/\\lambda=\\bar{X}$，故 $\\hat{\\lambda}=1/\\bar{X}$。',
        formula: 'E[X^k] = \\frac{1}{n}\\sum_{i=1}^n X_i^k,\\quad k=1,\\ldots,m',
        steps: [
          '步骤一：写出各阶总体矩 $\\mu_k=E[X^k]$（关于参数的表达式）',
          '步骤二：令 $\\mu_k=\\hat{\\mu}_k$（样本矩），建立方程组',
          '步骤三：解方程组，得矩估计量 $\\hat{\\theta}_1,\\ldots,\\hat{\\theta}_m$',
        ],
        tip: '矩估计的分母是 $n$（不是 $n-1$）。用 $k$ 阶矩估计 $m$ 个参数，通常取最低阶（$k=1,\\ldots,m$），但不同选择可能给出不同结果——矩估计不唯一。',
      },
      {
        title: 'MLE 的动机：什么参数最能解释这批数据？',
        body: '设观测值为 $x_1,\\ldots,x_n$，**似然函数**定义为在参数 $\\theta$ 下观测到这批数据的"可能性"：$L(\\theta)=\\prod_{i=1}^n f(x_i;\\theta)$。注意方向：数据固定，$\\theta$ 变化。MLE 的直觉："选择使当前观测数据最有可能出现的 $\\theta$"。数值例：抛硬币 3 次，观测到 $\\{1,1,0\\}$（正正反）。对于 $p=0.5$：$L=0.5^3=0.125$；对于 $p=0.7$：$L=0.7^2\\times0.3=0.147$；对于 $p=2/3$：$L=(2/3)^2\\times(1/3)=4/27\\approx0.148$。数据说 $p=2/3$ 最合理——这恰好是 $\\hat{p}_{MLE}=$ 正面比例 $=2/3$。',
        formula: 'L(\\theta) = \\prod_{i=1}^n f(x_i;\\theta),\\quad \\hat{\\theta}_{MLE} = \\arg\\max_{\\theta}\\,L(\\theta)',
        tip: '似然函数不是概率——$\\int L(\\theta)\\,d\\theta$ 一般不等于 1。它是固定数据条件下参数的函数，衡量"该参数下这批数据有多可能出现"。',
      },
      {
        title: 'MLE 求解：对数似然的 4 步流程',
        body: '由于乘积难求导，取对数转为求和：$\\ell(\\theta)=\\log L(\\theta)=\\sum_{i=1}^n\\log f(x_i;\\theta)$。$\\log$ 单调递增，最大化 $L$ 等价于最大化 $\\ell$。4 步流程——第 1 步：写对数似然 $\\ell(\\theta)=\\sum\\log f(x_i;\\theta)$；第 2 步：对每个参数偏导令零 $\\partial\\ell/\\partial\\theta_j=0$（似然方程）；第 3 步：解方程组，验证二阶导 $<0$（极大值）；第 4 步：检查特殊情形——若支撑依赖参数（如均匀分布），微分法失效，用代数分析法。经典例子：伯努利 $\\mathrm{Bernoulli}(p)$，$\\ell(p)=k\\log p+(n-k)\\log(1-p)$，求导令零得 $\\hat{p}_{MLE}=k/n=\\bar{X}$，与直觉完全吻合。',
        steps: [
          '第 1 步：写 $\\ell(\\theta)=\\sum\\log f(x_i;\\theta)$（乘积变求和）',
          '第 2 步：$\\partial\\ell/\\partial\\theta_j=0$（似然方程）',
          '第 3 步：解方程，验证 $\\partial^2\\ell/\\partial\\theta^2<0$',
          '第 4 步：检查是否边界取极值（支撑依赖参数 $\\Rightarrow$ 代数法）',
        ],
        tip: '对数似然把乘积变求和是最关键的一步——"加法比乘法好求导"是 MLE 计算便利性的根本原因。',
      },
      {
        title: '正态与泊松的 MLE 全推导',
        body: '正态 $\\mathcal{N}(\\mu,\\sigma^2)$（两参数均未知）：$\\ell(\\mu,\\sigma^2)=-\\frac{n}{2}\\log(2\\pi)-\\frac{n}{2}\\log\\sigma^2-\\frac{1}{2\\sigma^2}\\sum(x_i-\\mu)^2$。对 $\\mu$ 偏导令零：$\\sum(x_i-\\mu)=0 \\Rightarrow \\hat{\\mu}_{MLE}=\\bar{x}$。令 $v=\\sigma^2$，对 $v$ 偏导令零：$-n/(2v)+(1/2v^2)\\sum(x_i-\\bar{x})^2=0 \\Rightarrow \\hat{\\sigma}^2_{MLE}=\\frac{1}{n}\\sum(x_i-\\bar{x})^2$（分母 $n$，有偏！）。泊松 $\\mathrm{Pois}(\\lambda)$：$\\ell(\\lambda)=(\\sum x_i)\\log\\lambda-n\\lambda-\\sum\\log(x_i!)$，导数 $d\\ell/d\\lambda=(\\sum x_i)/\\lambda-n=0$，解得 $\\hat{\\lambda}_{MLE}=\\bar{x}$（与矩估计相同）。均匀 $U(0,\\theta)$：$\\ell(\\theta)=-n\\log\\theta$（对 $\\theta\\geq x_{(n)}$ 成立，否则 $L=0$），$-n\\log\\theta$ 单调递减，故 $\\hat{\\theta}_{MLE}=x_{(n)}=\\max(x_1,\\ldots,x_n)$（边界极值，不用微分法！）。',
        formula: '\\hat{\\mu}_{MLE}=\\bar{X},\\quad \\hat{\\sigma}^2_{MLE}=\\frac{1}{n}\\sum_{i=1}^n(X_i-\\bar{X})^2',
        tip: '均匀分布 $U(0,\\theta)$ 是"支撑依赖参数"的典型——MLE 在参数边界取得，绝不能对 $\\theta$ 求导令零。记住：$\\hat{\\theta}_{MLE}=X_{(n)}$。',
      },
      {
        title: 'MLE 的不变性原理',
        body: '定理（不变性）：若 $\\hat{\\theta}_{MLE}$ 是 $\\theta$ 的 MLE，则对任意函数 $g(\\theta)$，$g(\\hat{\\theta}_{MLE})$ 是 $g(\\theta)$ 的 MLE。不变性极为方便——无需重新推导，直接对估计量做变换。例一：已知 $\\hat{\\sigma}^2_{MLE}=\\frac{1}{n}\\sum(X_i-\\bar{X})^2$，则标准差的 MLE 为 $\\hat{\\sigma}_{MLE}=\\sqrt{\\hat{\\sigma}^2_{MLE}}$（直接开根号）。例二：泊松 $\\hat{\\lambda}_{MLE}=\\bar{X}$，零事件概率 $P(X=0)=e^{-\\lambda}$ 的 MLE 为 $e^{-\\bar{X}}$（直接代入）。对比矩估计：矩估计不具备不变性（$g(\\hat{\\theta}_{MoM})$ 一般不是 $g(\\theta)$ 的矩估计）。',
        reveal: {
          q: '设 $X_1,\\ldots,X_n\\overset{iid}{\\sim}\\mathrm{Exp}(\\lambda)$。(1) 求 $\\lambda$ 的 MLE；(2) 利用不变性，求平均寿命 $\\mu=1/\\lambda$ 的 MLE；(3) 矩估计是否与 MLE 相同？',
          a: '(1) $\\ell(\\lambda)=n\\log\\lambda-\\lambda\\sum x_i$，导数 $n/\\lambda-\\sum x_i=0$，$\\hat{\\lambda}_{MLE}=1/\\bar{X}$。(2) 不变性：$\\hat{\\mu}_{MLE}=1/\\hat{\\lambda}_{MLE}=\\bar{X}$（直接代入）。(3) 矩估计：$E[X]=1/\\lambda=\\bar{X}$，故 $\\hat{\\lambda}_{MoM}=1/\\bar{X}$——与 MLE 完全相同（指数分布的特殊"巧合"）。',
        },
      },
      {
        title: '易错点：MLE 的特殊情形与注意事项',
        body: '易错 1：均匀分布 $U(0,\\theta)$ 的 MLE 是 $X_{(n)}$，不是 $\\bar{X}$ 的某个倍数——支撑依赖参数时微分法完全失效，必须用代数分析（看 $L$ 的单调性）。易错 2：MLE 不一定无偏——$\\hat{\\sigma}^2_{MLE}=\\frac{1}{n}\\sum(X_i-\\bar{X})^2$ 的期望是 $\\frac{n-1}{n}\\sigma^2\\neq\\sigma^2$，系统性低估了方差。"MLE 很好"不等于"MLE 无偏"。易错 3：矩估计的分母是 $n$（不是 $n-1$），而无偏的样本方差 $S^2$ 分母是 $n-1$——两者不要混淆。易错 4：似然函数有多个解时，需逐一代入 $L(\\theta)$ 比较大小，取最大者为 MLE，不能只求一个根就停下。',
        tip: '口诀：正态方差的 MLE 分母是 $n$（有偏），样本方差 $S^2$ 分母是 $n-1$（无偏）。MLE 的两大优点：不变性 + 大样本渐近有效；两大缺点：小样本可能有偏 + 需要知道完整分布形式。',
      },
    ],
    questions: [
      {
        type: 'choice',
        prompt: '对泊松分布 $\\mathrm{Pois}(\\lambda)$，以下关于矩估计和 MLE 的说法正确的是：',
        options: [
          '矩估计 $\\hat{\\lambda}=\\bar{X}$，MLE 也是 $\\hat{\\lambda}=\\bar{X}$，两者完全相同',
          '矩估计 $\\hat{\\lambda}=\\bar{X}$，MLE 是 $\\hat{\\lambda}=\\sum X_i$，两者不同',
          '矩估计 $\\hat{\\lambda}=S^2$（样本方差），因为泊松分布方差等于均值',
          '矩估计用一阶矩，MLE 用二阶矩，两者结果不同',
        ],
        answer: 0,
        explain: '泊松分布 $E[X]=\\lambda$，矩估计令 $\\lambda=\\bar{X}$；对数似然 $\\ell(\\lambda)=\\sum x_i\\log\\lambda-n\\lambda-\\sum\\log(x_i!)$，导数 $(\\sum x_i)/\\lambda-n=0$ 解得 $\\hat{\\lambda}_{MLE}=\\bar{x}=\\bar{X}$。两者完全相同。（注：矩估计也可用 $E[X]=\\mathrm{Var}(X)=\\lambda$，即令 $S^2=\\bar{X}$，但这会引入方差信息，并不是标准矩估计做法。）',
      },
      {
        type: 'judge',
        prompt: '均匀分布 $U(0,\\theta)$ 的 MLE 为 $\\hat{\\theta}_{MLE}=X_{(n)}=\\max(X_1,\\ldots,X_n)$，求解时可以用"令 $d\\ell/d\\theta=0$"的微分法，这个说法正确吗？',
        answer: false,
        explain: '错误。$U(0,\\theta)$ 的支撑 $[0,\\theta]$ 依赖参数 $\\theta$，不满足 MLE 正则条件。$\\ell(\\theta)=-n\\log\\theta$ 关于 $\\theta$ 单调递减，极大值在约束边界 $\\theta=x_{(n)}$ 处取得，不能用微分法（导数 $-n/\\theta<0$ 恒负，令导数为零没有解）。必须用代数分析：$L(\\theta)=(1/\\theta)^n$ 对 $\\theta\\geq x_{(n)}$ 成立（否则为 0），在 $\\theta=x_{(n)}$ 时取最大值。',
      },
      {
        type: 'choice',
        prompt: '设 $X_1,\\ldots,X_n\\overset{iid}{\\sim}\\mathcal{N}(\\mu,\\sigma^2)$，两参数均未知。$\\mu$ 和 $\\sigma^2$ 的 MLE 分别是：',
        options: [
          '$\\hat{\\mu}=\\bar{X}$，$\\hat{\\sigma}^2=\\frac{1}{n-1}\\sum(X_i-\\bar{X})^2$（无偏样本方差）',
          '$\\hat{\\mu}=\\bar{X}$，$\\hat{\\sigma}^2=\\frac{1}{n}\\sum(X_i-\\bar{X})^2$（分母为 $n$）',
          '$\\hat{\\mu}=X_{(1)}$（最小值），$\\hat{\\sigma}^2=S^2$',
          '$\\hat{\\mu}=X_{(n)}$（最大值），$\\hat{\\sigma}^2=\\frac{1}{n}\\sum X_i^2$',
        ],
        answer: 1,
        explain: '正态对数似然对 $\\mu$ 偏导令零得 $\\hat{\\mu}_{MLE}=\\bar{X}$；令 $v=\\sigma^2$，对 $v$ 偏导令零得 $\\hat{\\sigma}^2_{MLE}=\\frac{1}{n}\\sum(X_i-\\bar{X})^2$（分母为 $n$，不是 $n-1$）。注意 $\\hat{\\sigma}^2_{MLE}$ 是有偏估计（$E[\\hat{\\sigma}^2_{MLE}]=\\frac{n-1}{n}\\sigma^2<\\sigma^2$），无偏修正是 $S^2=\\frac{1}{n-1}\\sum(X_i-\\bar{X})^2$。',
      },
      {
        type: 'input',
        prompt: '设 $X_1,\\ldots,X_n\\overset{iid}{\\sim}\\mathrm{Exp}(\\lambda)$，密度 $f(x;\\lambda)=\\lambda e^{-\\lambda x}$（$x>0$）。求 $\\lambda$ 的 MLE（用 $\\bar{X}$ 表示，如填"1/均值"）。',
        accept: ['1/均值', '1/X̄', '1/xbar', '\\hat{\\lambda}=1/\\bar{X}'],
        explain: '对数似然 $\\ell(\\lambda)=n\\log\\lambda-\\lambda\\sum x_i$，对 $\\lambda$ 求导：$d\\ell/d\\lambda=n/\\lambda-\\sum x_i=0$，解得 $\\hat{\\lambda}_{MLE}=n/\\sum x_i=1/\\bar{x}$。二阶导 $-n/\\lambda^2<0$，确认是极大值。MLE 为 $1/\\bar{X}$（样本均值的倒数）。',
      },
      {
        type: 'choice',
        prompt: '正态总体 $\\mathcal{N}(\\mu,\\sigma^2)$ 中，$\\mu$ 已知，$\\sigma^2$ 未知，$n$ 个 i.i.d. 样本。用矩估计法（令 $E[X^2]$ 等于样本二阶矩）得到 $\\sigma^2$ 的矩估计量为：',
        options: [
          '$\\hat{\\sigma}^2=\\frac{1}{n}\\sum(X_i-\\mu)^2$',
          '$\\hat{\\sigma}^2=\\frac{1}{n-1}\\sum(X_i-\\mu)^2$',
          '$\\hat{\\sigma}^2=\\frac{1}{n}\\sum X_i^2-\\mu^2$',
          '(A) 和 (C) 相同，均正确',
        ],
        answer: 3,
        explain: '$E[X^2]=\\sigma^2+\\mu^2$（$\\mu$ 已知），令 $\\sigma^2+\\mu^2=\\frac{1}{n}\\sum x_i^2$，解得 $\\hat{\\sigma}^2=\\frac{1}{n}\\sum x_i^2-\\mu^2$。同时 $\\frac{1}{n}\\sum(X_i-\\mu)^2=\\frac{1}{n}\\sum X_i^2-2\\mu\\bar{X}+\\mu^2$，当 $\\mu$ 已知时 $\\frac{1}{n}\\sum(X_i-\\mu)^2=\\frac{1}{n}\\sum X_i^2-\\mu^2$（展开后因 $E[X]=\\mu$ 化简），两者等价，选 (D)。',
      },
      {
        type: 'judge',
        prompt: 'MLE 的不变性：若 $\\hat{\\theta}_{MLE}$ 是 $\\theta$ 的 MLE，则 $g(\\hat{\\theta}_{MLE})$ 是 $g(\\theta)$ 的 MLE，这个性质对矩估计同样成立（即 $g(\\hat{\\theta}_{MoM})$ 也一定是 $g(\\theta)$ 的矩估计），这个说法正确吗？',
        answer: false,
        explain: '错误。不变性是 MLE 特有的性质，矩估计不具备。例：正态总体，$\\sigma^2$ 的矩估计是 $\\hat{\\sigma}^2=\\frac{1}{n}\\sum(X_i-\\bar{X})^2$，但 $\\sigma=\\sqrt{\\sigma^2}$ 的矩估计不是 $\\sqrt{\\hat{\\sigma}^2}$（矩估计要重新用标准差的矩方程推导）。MLE 不变性的本质是"最大化是变换不变的"——$\\arg\\max L(g^{-1}(\\phi))$ 关于 $\\phi$ 的解恰好是 $g(\\hat{\\theta}_{MLE})$。',
      },
      {
        type: 'match',
        prompt: '将分布与对应参数的 MLE 配对：',
        left: ['$\\mathrm{Pois}(\\lambda)$', '$\\mathcal{N}(\\mu,\\sigma^2)$（$\\sigma^2$ 已知，推断 $\\mu$）', '$U(0,\\theta)$', '$\\mathrm{Bernoulli}(p)$'],
        right: [
          '$\\hat{\\theta}=X_{(n)}$（样本最大值）',
          '$\\hat{p}=\\bar{X}$（成功频率）',
          '$\\hat{\\mu}=\\bar{X}$（样本均值）',
          '$\\hat{\\lambda}=\\bar{X}$（样本均值）',
        ],
        answer: [3, 2, 0, 1],
        explain: '泊松：$d\\ell/d\\lambda=(\\sum x_i)/\\lambda-n=0$，$\\hat{\\lambda}=\\bar{X}$；正态（$\\sigma^2$ 已知）：$d\\ell/d\\mu=\\sum(x_i-\\mu)/\\sigma^2=0$，$\\hat{\\mu}=\\bar{X}$；均匀：$L(\\theta)=(1/\\theta)^n$ 在 $\\theta\\geq x_{(n)}$ 时单调递减，$\\hat{\\theta}=X_{(n)}$；伯努利：$d\\ell/dp=k/p-(n-k)/(1-p)=0$，$\\hat{p}=k/n=\\bar{X}$（$k=\\sum x_i$）。',
      },
      {
        type: 'choice',
        prompt: '设 $X_1,\\ldots,X_n\\overset{iid}{\\sim}\\mathrm{Bernoulli}(p)$，观测到 $k$ 次成功。利用 MLE 不变性，估计 $p^2$（两次连续成功的概率）的 MLE 是：',
        options: [
          '$k^2/n^2$',
          '$(k/n)^2$',
          '$(k-1)k/[n(n-1)]$',
          '$\\bar{X}^2-S^2/n$',
        ],
        answer: 1,
        explain: '$\\hat{p}_{MLE}=k/n=\\bar{X}$（伯努利 MLE）。由 MLE 不变性，$p^2$ 的 MLE 为 $(\\hat{p}_{MLE})^2=(k/n)^2=(\\bar{X})^2$，直接代入即可，不需要重新推导。注意 $(k-1)k/[n(n-1)]$ 是 $p^2$ 的无偏估计（不是 MLE），MLE 要用不变性，不要混淆。',
      },
    ],
  },
  {
    id: 't18-b',
    title: '估计量的评价标准',
    subtitle: '无偏性、有效性（Cramér-Rao 下界）与一致性——三把尺子量好坏',
    intro: [
      {
        title: '引入：哪个估计量更好？',
        body: '矩估计和 MLE 都能给出 $\\theta$ 的估计，那哪个更好？问题本身需要"好"的标准。对同一参数 $\\sigma^2$：MLE 给出 $\\hat{\\sigma}^2_{MLE}=\\frac{1}{n}\\sum(X_i-\\bar{X})^2$（分母 $n$），样本方差 $S^2=\\frac{1}{n-1}\\sum(X_i-\\bar{X})^2$（分母 $n-1$）。直觉上 $S^2$ 无偏（$E[S^2]=\\sigma^2$），MLE 系统低估（$E[\\hat{\\sigma}^2_{MLE}]=\\frac{n-1}{n}\\sigma^2$）。但计算均方误差（MSE）后发现：$\\mathrm{MSE}(\\hat{\\sigma}^2_{MLE})<\\mathrm{MSE}(S^2)$（$n\\geq2$ 时）！所以没有绝对的"更好"——取决于评价标准。这道反直觉题揭示了点估计的核心张力：**无偏性 vs 有效性 vs MSE**。',
        tip: '估计量是随机变量（样本的函数），能谈论它的期望、方差、MSE。估计值是代入观测值后的确定数字，不再是随机变量。',
      },
      {
        title: '无偏性：期望指向真值',
        body: '定义：若 $E[\\hat{\\theta}]=\\theta$（对一切 $\\theta\\in\\Theta$），则称 $\\hat{\\theta}$ 为 $\\theta$ 的**无偏估计量**。偏差（bias）$=E[\\hat{\\theta}]-\\theta$。直觉：无偏估计量在大量重复实验中"平均上"指向真值，没有系统性偏差。重要结论：(1) 样本均值 $\\bar{X}$ 是总体均值 $\\mu$ 的无偏估计；(2) 样本方差 $S^2=\\frac{1}{n-1}\\sum(X_i-\\bar{X})^2$ 是 $\\sigma^2$ 的无偏估计（分母 $n-1$ 的原因：用 $\\bar{X}$ 代替未知 $\\mu$，引入一个约束，使自由度减少 1）；(3) $\\hat{\\sigma}^2_{MLE}=\\frac{1}{n}\\sum(X_i-\\bar{X})^2$ 是有偏的，$E[\\hat{\\sigma}^2_{MLE}]=\\frac{n-1}{n}\\sigma^2$；(4) 无偏性不具备变换不变性：$S$ 不是 $\\sigma$ 的无偏估计（$E[S]<\\sigma$）。',
        formula: 'E[\\hat{\\theta}]=\\theta,\\quad E[S^2]=\\sigma^2,\\quad E\\!\\left[\\frac{1}{n}\\sum(X_i-\\bar{X})^2\\right]=\\frac{n-1}{n}\\sigma^2',
        tip: '无偏性只关注期望，忽视方差。两个无偏估计量中，方差更小的通常更好。无偏性 $\\neq$ 最优。',
      },
      {
        title: 'Fisher 信息量与 Cramér-Rao 下界',
        body: '在所有无偏估计量中，方差能小到什么程度？**Fisher 信息量**给出了理论限制：$I(\\theta)=E\\!\\left[(\\frac{\\partial\\log f(X;\\theta)}{\\partial\\theta})^2\\right]=-E\\!\\left[\\frac{\\partial^2\\log f(X;\\theta)}{\\partial\\theta^2}\\right]$。$I(\\theta)$ 越大，参数越"可估"（数据关于 $\\theta$ 的信息越丰富）。**Cramér-Rao 下界定理**：对任意无偏估计量 $\\hat{\\theta}$，$\\mathrm{Var}(\\hat{\\theta})\\geq\\frac{1}{nI(\\theta)}$。若某无偏估计量 $\\hat{\\theta}^*$ 的方差恰好等于下界 $\\frac{1}{nI(\\theta)}$，则称 $\\hat{\\theta}^*$ 为**有效估计量**，也是 UMVUE（一致最小方差无偏估计量）。数值例：正态 $\\mathcal{N}(\\mu,\\sigma^2)$（$\\sigma^2$ 已知），$I(\\mu)=1/\\sigma^2$，CR 下界 $=\\sigma^2/n$，$\\mathrm{Var}(\\bar{X})=\\sigma^2/n$ 恰好等于下界——$\\bar{X}$ 是有效估计量。',
        formula: 'I(\\theta)=-E\\!\\left[\\frac{\\partial^2\\log f(X;\\theta)}{\\partial\\theta^2}\\right],\\quad \\mathrm{Var}(\\hat{\\theta})\\geq\\frac{1}{nI(\\theta)}',
        tip: 'Fisher 信息量的两个公式（一阶导的平方期望 $=$ 负的二阶导期望）是等价的，通常用二阶导那个更容易计算。',
      },
      {
        title: '均方误差（MSE）：偏差与方差的综合',
        body: '实践中，**均方误差**（MSE）综合考量偏差与方差：$\\mathrm{MSE}(\\hat{\\theta})=E[(\\hat{\\theta}-\\theta)^2]=\\mathrm{Var}(\\hat{\\theta})+[\\mathrm{Bias}(\\hat{\\theta})]^2$。偏差-方差分解：MSE $=$ 方差 $+$ 偏差的平方。有偏估计有时 MSE 反而更小（用偏差换方差）。典型例子：$S^2$（无偏）的 $\\mathrm{MSE}(S^2)=\\frac{2\\sigma^4}{n-1}$；$\\hat{\\sigma}^2_{MLE}$（有偏）的 $\\mathrm{MSE}(\\hat{\\sigma}^2_{MLE})=\\frac{(2n-1)\\sigma^4}{n^2}$。当 $n\\geq2$ 时 $\\frac{2n-1}{n^2}<\\frac{2}{n-1}$，所以 $\\mathrm{MSE}(\\hat{\\sigma}^2_{MLE})<\\mathrm{MSE}(S^2)$——有偏的 MLE 估计方差的 MSE 反而更小！',
        formula: '\\mathrm{MSE}(\\hat{\\theta})=\\mathrm{Var}(\\hat{\\theta})+[\\mathrm{Bias}(\\hat{\\theta})]^2',
        tip: '偏差-方差权衡（bias-variance tradeoff）是统计学和机器学习的核心主题。追求无偏有时以更大方差为代价，追求更小方差有时不得不接受系统偏差。',
      },
      {
        title: '一致性：大样本收敛',
        body: '无偏性和有效性是固定样本量 $n$ 的性质；**一致性**关注 $n\\to\\infty$ 时的行为。定义：若对任意 $\\varepsilon>0$，$\\lim_{n\\to\\infty}P(|\\hat{\\theta}_n-\\theta|>\\varepsilon)=0$，则称 $\\{\\hat{\\theta}_n\\}$ 为**弱一致估计量**，记 $\\hat{\\theta}_n\\xrightarrow{P}\\theta$。判断一致性的充分条件：$\\lim_{n\\to\\infty}E[\\hat{\\theta}_n]=\\theta$ 且 $\\lim_{n\\to\\infty}\\mathrm{Var}(\\hat{\\theta}_n)=0$（由 Chebyshev 不等式）。重要结论：$\\bar{X}_n\\xrightarrow{P}\\mu$（大数定律）；$S_n^2\\xrightarrow{P}\\sigma^2$；MLE 在正则条件下是一致估计量。关键区分：一致性 $\\not\\Rightarrow$ 无偏；无偏 $\\not\\Rightarrow$ 一致（方差不趋零时）。一致性是对估计量的最基本要求——不一致的估计量无论如何都不可接受。',
        formula: '\\lim_{n\\to\\infty}P(|\\hat{\\theta}_n-\\theta|>\\varepsilon)=0\\quad\\forall\\varepsilon>0\\;\\Longleftrightarrow\\;\\hat{\\theta}_n\\xrightarrow{P}\\theta',
        reveal: {
          q: '某估计量 $\\hat{\\theta}_n$ 满足 $E[\\hat{\\theta}_n]=\\theta+1/n$，$\\mathrm{Var}(\\hat{\\theta}_n)=1/n$。它是否无偏？是否一致？',
          a: '不无偏（偏差 $=1/n\\neq0$）。但当 $n\\to\\infty$：$E[\\hat{\\theta}_n]\\to\\theta$（期望趋于真值）且 $\\mathrm{Var}(\\hat{\\theta}_n)=1/n\\to0$，由 Chebyshev 不等式，$\\hat{\\theta}_n\\xrightarrow{P}\\theta$——是一致估计量。一致性不要求无偏，只要渐近趋于真值即可。',
        },
      },
      {
        title: '三大标准速查与条件反射',
        body: '三大评价标准汇总：无偏性——$E[\\hat{\\theta}]=\\theta$，期望无系统偏差，固定样本量下有意义；有效性——方差达到 CR 下界 $1/(nI(\\theta))$，在所有无偏估计中方差最小，仅针对无偏估计；一致性——$\\hat{\\theta}_n\\xrightarrow{P}\\theta$，大样本收敛，是最基本要求。条件反射：看到"求 MLE"$\\Rightarrow$ 写对数似然，4 步流程；看到"均匀分布 MLE"$\\Rightarrow$ 边界 $X_{(n)}$；看到"MLE 是否无偏"$\\Rightarrow$ 算 $E[\\hat{\\theta}_{MLE}]$（正态方差 MLE 有偏）；看到"Fisher 信息量"$\\Rightarrow$ 两个等价公式；看到"CR 下界"$\\Rightarrow$ $1/(nI(\\theta))$，达到下界 $=$ 有效 $=$ UMVUE（无偏类）。',
        tip: '实用法则：构造估计量 $\\to$ 检验无偏性 $\\to$ 检验一致性 $\\to$ 计算 MSE $\\to$ 比较效率。无偏性只是起点，不是终点。',
      },
    ],
    questions: [
      {
        type: 'judge',
        prompt: '样本方差 $S^2=\\frac{1}{n-1}\\sum(X_i-\\bar{X})^2$ 是总体方差 $\\sigma^2$ 的无偏估计，而 MLE 估计 $\\hat{\\sigma}^2_{MLE}=\\frac{1}{n}\\sum(X_i-\\bar{X})^2$ 也是 $\\sigma^2$ 的无偏估计，这个说法正确吗？',
        answer: false,
        explain: '错误。$S^2$（分母 $n-1$）是无偏估计，$E[S^2]=\\sigma^2$；但 $\\hat{\\sigma}^2_{MLE}$（分母 $n$）是有偏估计，$E[\\hat{\\sigma}^2_{MLE}]=\\frac{n-1}{n}\\sigma^2<\\sigma^2$（系统性低估）。偏差为 $-\\sigma^2/n$。两者都是 $\\sigma^2$ 的估计，但只有 $S^2$ 无偏。',
      },
      {
        type: 'choice',
        prompt: '以下关于 MSE 的说法，哪个是正确的？',
        options: [
          '无偏估计的 MSE 一定比有偏估计的 MSE 小',
          'MSE = 方差 + 偏差的平方，有偏估计的 MSE 有时比无偏估计更小',
          'MSE 只适用于评价有偏估计，无偏估计直接比方差即可',
          'MSE 和方差对无偏估计不同，因为无偏估计 MSE $=0$',
        ],
        answer: 1,
        explain: 'MSE $=\\mathrm{Var}(\\hat{\\theta})+[\\mathrm{Bias}(\\hat{\\theta})]^2$，对无偏估计 $\\mathrm{MSE}=\\mathrm{Var}$。有偏估计可以通过引入少量偏差来大幅降低方差，使 MSE 反而更小。典型例：正态方差的 MLE（有偏）的 MSE 小于 $S^2$（无偏）的 MSE（$n\\geq2$ 时）。',
      },
      {
        type: 'input',
        prompt: '设 $X_1,\\ldots,X_n\\overset{iid}{\\sim}\\mathcal{N}(\\mu,\\sigma^2)$，$\\sigma^2$ 已知，推断 $\\mu$。Fisher 信息量 $I(\\mu)=$ ？（用 $\\sigma^2$ 表达，如填"1/sigma²"）',
        accept: ['1/σ²', '1/sigma²', '1/sigma^2', '\\sigma^{-2}', '\\frac{1}{\\sigma^2}'],
        explain: '$\\log f(x;\\mu)=-\\frac{1}{2}\\log(2\\pi\\sigma^2)-\\frac{(x-\\mu)^2}{2\\sigma^2}$，$\\frac{\\partial\\log f}{\\partial\\mu}=\\frac{x-\\mu}{\\sigma^2}$，$\\frac{\\partial^2\\log f}{\\partial\\mu^2}=-\\frac{1}{\\sigma^2}$，$I(\\mu)=-E[-\\frac{1}{\\sigma^2}]=\\frac{1}{\\sigma^2}$。CR 下界 $=\\frac{1}{nI(\\mu)}=\\frac{\\sigma^2}{n}$，$\\mathrm{Var}(\\bar{X})=\\sigma^2/n$ 恰好等于下界，$\\bar{X}$ 是有效估计量（UMVUE）。',
      },
      {
        type: 'choice',
        prompt: '设 $X_1,\\ldots,X_n\\overset{iid}{\\sim}\\mathrm{Pois}(\\lambda)$，$\\hat{\\lambda}=\\bar{X}$，已知 $I(\\lambda)=1/\\lambda$。以下关于 $\\bar{X}$ 有效性的说法正确的是：',
        options: [
          '$\\mathrm{Var}(\\bar{X})=\\lambda/n$，CR 下界 $=\\lambda/n$，$\\bar{X}$ 是有效估计量',
          '$\\mathrm{Var}(\\bar{X})=\\lambda^2/n$，CR 下界 $=1/(n\\lambda)$，$\\bar{X}$ 不是有效估计量',
          '$\\bar{X}$ 无偏但不是有效估计量，因为泊松分布不满足 CR 定理的正则条件',
          '$\\bar{X}$ 的方差比 CR 下界大，说明存在更优的无偏估计',
        ],
        answer: 0,
        explain: '泊松分布 $\\mathrm{Var}(X)=\\lambda$，故 $\\mathrm{Var}(\\bar{X})=\\lambda/n$。CR 下界 $=\\frac{1}{nI(\\lambda)}=\\frac{1}{n\\cdot(1/\\lambda)}=\\lambda/n$。两者完全相等，故 $\\bar{X}$ 是 $\\lambda$ 的有效估计量（UMVUE）。',
      },
      {
        type: 'judge',
        prompt: '一致性意味着无偏性：若 $\\hat{\\theta}_n\\xrightarrow{P}\\theta$，则 $E[\\hat{\\theta}_n]=\\theta$，这个说法正确吗？',
        answer: false,
        explain: '错误。一致性与无偏性互不蕴含。可以构造有偏但一致的估计量：如 $\\hat{\\theta}_n=\\bar{X}+1/n$，有偏（偏差 $=1/n$）但一致（$\\bar{X}+1/n\\xrightarrow{P}\\mu$）。也可以有无偏但不一致的估计量（方差不趋零时）。典型有偏但一致的例子：$\\hat{\\sigma}^2_{MLE}=\\frac{1}{n}\\sum(X_i-\\bar{X})^2$，有偏（$E=\\frac{n-1}{n}\\sigma^2$），但一致（$n\\to\\infty$ 时偏差 $\\to0$，方差 $\\to0$）。',
      },
      {
        type: 'match',
        prompt: '将评价标准与对应的数学表达配对：',
        left: ['无偏性', '有效性', '一致性', 'MSE 分解'],
        right: [
          '$E[\\hat{\\theta}]=\\theta$（期望等于真值）',
          '$\\mathrm{MSE}=\\mathrm{Var}+\\mathrm{Bias}^2$（偏差-方差分解）',
          '$\\hat{\\theta}_n\\xrightarrow{P}\\theta$（依概率收敛）',
          '$\\mathrm{Var}(\\hat{\\theta})=\\frac{1}{nI(\\theta)}$（方差达到 CR 下界）',
        ],
        answer: [0, 3, 2, 1],
        explain: '无偏性：$E[\\hat{\\theta}]=\\theta$；有效性：方差恰好等于 CR 下界 $1/(nI(\\theta))$，是所有无偏估计中方差最小的；一致性：大样本下依概率收敛到真值；MSE 分解：MSE $=$ 方差 $+$ 偏差的平方（对有偏估计两项均非零）。',
      },
      {
        type: 'choice',
        prompt: '以下四个关于无偏性的说法，哪个正确？',
        options: [
          '无偏估计量的 MSE 一定小于有偏估计量的 MSE',
          '若 $\\hat{\\theta}$ 是 $\\theta$ 的无偏估计，则 $g(\\hat{\\theta})$ 一定是 $g(\\theta)$ 的无偏估计',
          '$S^2=\\frac{1}{n-1}\\sum(X_i-\\bar{X})^2$ 是 $\\sigma^2$ 的无偏估计，但 $S=\\sqrt{S^2}$ 不是 $\\sigma$ 的无偏估计',
          '无偏估计量的期望值等于参数真值，因此方差也等于零',
        ],
        answer: 2,
        explain: '$S^2$ 无偏（$E[S^2]=\\sigma^2$），但无偏性不具有变换不变性：由 Jensen 不等式，$E[\\sqrt{S^2}]=E[S]<\\sqrt{E[S^2]}=\\sigma$（因 $\\sqrt{\\cdot}$ 是凹函数），故 $S$ 低估 $\\sigma$，不是无偏估计。(A) 错（有偏 MSE 可以更小）；(B) 错（无偏性不保持函数变换）；(D) 错（无偏只约束期望，方差可以很大）。',
      },
      {
        type: 'judge',
        prompt: '$\\hat{\\sigma}^2_{MLE}=\\frac{1}{n}\\sum(X_i-\\bar{X})^2$（有偏）的均方误差（MSE）在 $n\\geq2$ 时比 $S^2=\\frac{1}{n-1}\\sum(X_i-\\bar{X})^2$（无偏）的 MSE 更小，这个说法正确吗？',
        answer: true,
        explain: '$\\mathrm{MSE}(S^2)=\\mathrm{Var}(S^2)=\\frac{2\\sigma^4}{n-1}$（无偏，MSE $=$ 方差）；$\\mathrm{MSE}(\\hat{\\sigma}^2_{MLE})=\\frac{(2n-1)\\sigma^4}{n^2}$（方差 $+$ 偏差的平方）。比较 $\\frac{2n-1}{n^2}$ 与 $\\frac{2}{n-1}$：前者 $\\times n^2(n-1)=(2n-1)(n-1)=2n^2-3n+1$；后者 $\\times n^2(n-1)=2n^2$。所以 $\\frac{2n-1}{n^2}<\\frac{2}{n-1}$（$n\\geq2$ 时 $2n^2-3n+1<2n^2$），有偏的 MLE 估计方差的 MSE 反而更小。',
      },
    ],
  },
  {
    id: 't18-c',
    title: 'MLE 的渐近性质与综合应用',
    subtitle: '渐近正态、渐近有效、Delta 方法——MLE 的大样本理论全景',
    intro: [
      {
        title: 'MLE 的渐近分布',
        body: '在正则条件下（似然光滑、支撑不依赖参数、参数在内部等），MLE 有优良的渐近性质。**渐近正态性定理**：设 $X_1,\\ldots,X_n\\overset{iid}{\\sim}f(x;\\theta_0)$，则 $\\sqrt{n}(\\hat{\\theta}_{MLE}-\\theta_0)\\xrightarrow{d}\\mathcal{N}(0,\\,1/I(\\theta_0))$。等价地，对充分大的 $n$：$\\hat{\\theta}_{MLE}\\approx\\mathcal{N}(\\theta_0,\\,\\frac{1}{nI(\\theta_0)})$。三层含义：(1) **一致性**：方差趋于 0，MLE 收敛到真值；(2) **渐近无偏**：期望趋于 $\\theta_0$；(3) **渐近有效**：渐近方差 $\\frac{1}{nI(\\theta_0)}$ 恰好等于 CR 下界——MLE 在大样本下达到理论极限，没有无偏估计能比它更精准（渐近意义）。',
        formula: '\\sqrt{n}(\\hat{\\theta}_{MLE}-\\theta_0)\\xrightarrow{d}\\mathcal{N}\\!\\left(0,\\;\\frac{1}{I(\\theta_0)}\\right)',
        tip: 'MLE 的渐近正态性是构造大样本置信区间的基础：$\\hat{\\theta}_{MLE}\\pm z_{\\alpha/2}/\\sqrt{nI(\\hat{\\theta}_{MLE})}$（用 $\\hat{\\theta}$ 估计 $I(\\theta_0)$）。',
      },
      {
        title: 'MLE 正则条件与特殊情形',
        body: 'MLE 渐近理论成立需要正则条件：(1) 模型可识别（不同参数给不同分布）；(2) 支撑不依赖参数（均匀分布 $U(0,\\theta)$ 违反此条件）；(3) 似然三阶可微；(4) 真实参数在内点（非边界）；(5) Fisher 信息量有限且正。当条件不满足时，MLE 仍可能存在但不一定渐近正态。典型例外——均匀分布 $U(0,\\theta)$：MLE $\\hat{\\theta}=X_{(n)}$，$E[X_{(n)}]=\\frac{n}{n+1}\\theta$（有偏），$n(\\theta-X_{(n)})\\xrightarrow{d}\\mathrm{Exp}(1/\\theta)$（指数分布，非正态！），收敛速度 $O(1/n)$（比正则情形的 $O(1/\\sqrt{n})$ 更快）。',
        tip: '口诀：支撑依赖参数 $\\Rightarrow$ MLE 在边界取得 $\\Rightarrow$ 渐近理论不适用 $\\Rightarrow$ 需单独分析（次序统计量的分布）。',
      },
      {
        title: 'Delta 方法：函数变换的渐近分布',
        body: '已知 $\\hat{\\theta}$ 的渐近分布，如何求 $g(\\hat{\\theta})$ 的渐近分布？**Delta 方法**：若 $\\sqrt{n}(\\hat{\\theta}_n-\\theta)\\xrightarrow{d}\\mathcal{N}(0,\\sigma^2)$，且 $g$ 在 $\\theta$ 处可微且 $g^{\\prime}(\\theta)\\neq0$，则 $\\sqrt{n}(g(\\hat{\\theta}_n)-g(\\theta))\\xrightarrow{d}\\mathcal{N}(0,\\,[g^{\\prime}(\\theta)]^2\\sigma^2)$。记忆：新方差 $=[g^{\\prime}(\\theta)]^2\\times$旧方差（一阶泰勒展开）。应用例：伯努利 $\\hat{p}_{MLE}=\\bar{X}$，$\\sqrt{n}(\\hat{p}-p)\\xrightarrow{d}\\mathcal{N}(0,p(1-p))$。求对数几率 $g(p)=\\log\\frac{p}{1-p}$ 的渐近分布：$g^{\\prime}(p)=\\frac{1}{p(1-p)}$，新方差 $=[\\frac{1}{p(1-p)}]^2\\cdot p(1-p)=\\frac{1}{p(1-p)}$。',
        formula: '\\sqrt{n}\\big(g(\\hat{\\theta}_n)-g(\\theta)\\big)\\xrightarrow{d}\\mathcal{N}\\!\\left(0,\\;[g^{\\prime}(\\theta)]^2\\sigma^2\\right)',
        steps: [
          '步骤一：写出 $\\hat{\\theta}$ 的渐近分布 $\\sqrt{n}(\\hat{\\theta}-\\theta)\\xrightarrow{d}\\mathcal{N}(0,\\sigma^2)$',
          '步骤二：计算 $g^{\\prime}(\\theta)$（在真实参数处求导）',
          '步骤三：$g(\\hat{\\theta})$ 的渐近方差 $=[g^{\\prime}(\\theta)]^2\\sigma^2/n$',
          '步骤四：用 $\\hat{\\theta}$ 代替未知 $\\theta$，得渐近置信区间',
        ],
        tip: 'Delta 方法是 MLE 不变性的"渐近版本"：不仅给出估计值，还给出估计的渐近方差（用于置信区间）。',
      },
      {
        title: '指数分布 MLE 有效性的完整验证',
        body: '设 $X_1,\\ldots,X_n\\overset{iid}{\\sim}\\mathrm{Exp}(\\lambda)$，$f(x;\\lambda)=\\lambda e^{-\\lambda x}$（$x>0$）。第一步，MLE：$\\hat{\\lambda}_{MLE}=1/\\bar{X}$（已推导）。第二步，Fisher 信息量：$\\log f=-\\log\\lambda+\\log\\lambda-\\lambda x=\\log\\lambda-\\lambda x$... 重新算：$\\partial^2\\log f/\\partial\\lambda^2=-1/\\lambda^2$，$I(\\lambda)=-E[-1/\\lambda^2]=1/\\lambda^2$。CR 下界 $=\\frac{1}{nI(\\lambda)}=\\frac{\\lambda^2}{n}$。第三步，Delta 方法验证：$g(\\bar{X})=1/\\bar{X}$，$g^{\\prime}(\\mu)=-1/\\mu^2$（$\\mu=1/\\lambda$），$\\mathrm{Var}(\\hat{\\lambda}_{MLE})\\approx[g^{\\prime}(\\mu)]^2\\cdot\\frac{\\mathrm{Var}(X)}{n}=\\frac{1}{\\ mu^4}\\cdot\\frac{1/\\lambda^2}{n}=\\frac{\\lambda^2}{n}$——渐近方差等于 CR 下界，$\\hat{\\lambda}_{MLE}$ 是渐近有效估计量。',
        formula: 'I(\\lambda)=\\frac{1}{\\lambda^2},\\quad \\operatorname{CR}\\text{ 下界}=\\frac{\\lambda^2}{n},\\quad \\operatorname{Var}_{\\text{渐近}}(\\hat{\\lambda}_{MLE})=\\frac{\\lambda^2}{n}',
        tip: 'Delta 方法验证有效性的套路：① 算 CR 下界 $1/(nI(\\theta))$；② 用 Delta 方法算 MLE 的渐近方差；③ 两者相等 $\\Rightarrow$ 渐近有效。',
      },
      {
        title: 'MLE vs 矩估计：综合对比',
        body: '两大方法对比表——矩估计：原理是样本矩代替总体矩，优点是简单、不需要完整分布，缺点是效率一般不最优、不唯一；MLE：原理是最大化似然函数，优点是渐近有效、不变性强、大样本理论完备，缺点是需要完整分布、计算有时复杂，特殊情形（支撑依赖参数）需单独处理。两者的关系：(1) 许多分布下矩估计 $=$ MLE（正态均值、指数分布、泊松分布）；(2) 正态方差是例外：矩估计和 MLE 都是 $\\frac{1}{n}\\sum(X_i-\\bar{X})^2$（分母 $n$），而无偏的 $S^2$ 分母是 $n-1$；(3) 大样本下 MLE 是渐近有效的，矩估计通常不是。',
        reveal: {
          q: '设 $X_1,\\ldots,X_n\\overset{iid}{\\sim}\\mathrm{Bernoulli}(p)$。(1) 求 $p$ 的 MLE；(2) $p(1-p)$（方差）的 MLE 是什么（用不变性）；(3) 验证 $\\bar{X}$ 是 $p$ 的有效估计量（计算 $I(p)$ 和 CR 下界）。',
          a: '(1) $\\hat{p}_{MLE}=\\bar{X}$（成功频率）。(2) 不变性：$\\widehat{p(1-p)}_{MLE}=\\bar{X}(1-\\bar{X})$。(3) $\\log f(x;p)=x\\log p+(1-x)\\log(1-p)$，$\\partial^2\\log f/\\partial p^2=-x/p^2-(1-x)/(1-p)^2$，$I(p)=-E[...]= E[X]/p^2+E[1-X]/(1-p)^2=1/p+1/(1-p)=1/[p(1-p)]$。CR 下界 $=\\frac{1}{nI(p)}=\\frac{p(1-p)}{n}$。$\\mathrm{Var}(\\bar{X})=p(1-p)/n$ 恰好等于 CR 下界，$\\bar{X}$ 是有效估计量。',
        },
      },
      {
        title: '综合易错点与条件反射',
        body: '综合易错点：① MLE 不一定无偏——正态方差 MLE 有偏，均匀 MLE 有偏，不要因为"MLE 很好"就断言无偏；② $\\hat{\\sigma}^2_{MLE}$ 与 $S^2$ 的混淆——分母分别为 $n$（MLE，有偏）和 $n-1$（样本方差，无偏），题目问"无偏估计"答 $S^2$；③ CR 下界达不到时——并非所有分布都存在有效估计量，下界不可达时 UMVUE 通过 Rao-Blackwell 定理构造；④ Delta 方法使用时机——已知 MLE 的渐近分布，求其函数变换的渐近方差，用 $[g^{\\prime}(\\theta)]^2\\times$ 原方差；⑤ 一致性的充分条件——期望趋于真值且方差趋于零（Chebyshev 不等式保证）。',
        tip: '速查口诀：无偏看期望，有效看 CR 下界，一致看方差趋零 $+$ 期望趋真值，MSE $=$ 方差 $+$ 偏差的平方。',
      },
    ],
    questions: [
      {
        type: 'choice',
        prompt: 'MLE 的渐近正态定理给出 $\\sqrt{n}(\\hat{\\theta}_{MLE}-\\theta_0)\\xrightarrow{d}\\mathcal{N}(0,1/I(\\theta_0))$。该定理包含的三层含义是：',
        options: [
          '一致性 + 渐近无偏 + 渐近有效（方差达 CR 下界）',
          '无偏性 + 有效性 + 一致性（三者等价于正则条件下）',
          '一致性 + 正态性 + 无偏性（MLE 在正则条件下均满足）',
          'MLE 在任何条件下都是有效估计量',
        ],
        answer: 0,
        explain: 'MLE 渐近正态定理的三层含义：(1) 一致性：方差 $1/(nI(\\theta_0))\\to0$，故 $\\hat{\\theta}_{MLE}\\xrightarrow{P}\\theta_0$；(2) 渐近无偏：均值趋于 $\\theta_0$；(3) 渐近有效：渐近方差 $1/(nI(\\theta_0))$ 恰好等于 CR 下界，MLE 是渐近有效估计量。注意这些是渐近性质，小样本下 MLE 可能有偏、方差大于 CR 下界。',
      },
      {
        type: 'judge',
        prompt: '均匀分布 $U(0,\\theta)$ 的 MLE $\\hat{\\theta}=X_{(n)}$ 不满足正则条件，因此它的收敛速度比正则情形更慢（$O(1/\\sqrt{n})$ vs 正则的 $O(1/n)$），这个说法正确吗？',
        answer: false,
        explain: '错误，方向相反。均匀分布 MLE $\\hat{\\theta}=X_{(n)}$ 的收敛速度比正则情形**更快**：$n(\\theta-X_{(n)})\\xrightarrow{d}\\mathrm{Exp}(1/\\theta)$，收敛速度是 $O(1/n)$；而正则 MLE 的收敛速度是 $O(1/\\sqrt{n})$（渐近正态的标准速度）。支撑依赖参数时，最大值统计量以更快的速度收敛，但极限分布是指数分布而非正态分布。',
      },
      {
        type: 'choice',
        prompt: '设 $X_1,\\ldots,X_n\\overset{iid}{\\sim}\\mathrm{Bernoulli}(p)$，$\\hat{p}=\\bar{X}$，$\\sqrt{n}(\\hat{p}-p)\\xrightarrow{d}\\mathcal{N}(0,p(1-p))$。用 Delta 方法求 $g(p)=p^2$ 的渐近方差（每个样本观测的渐近方差），下列哪个正确？',
        options: [
          '$4p^2(1-p)$',
          '$4p^2(1-p)/n$',
          '$2p(1-p)$',
          '$[g^{\\prime}(p)]^2\\cdot p(1-p)=4p^2(1-p)$（这是渐近方差，乘以 $n$ 是全体样本的方差）',
        ],
        answer: 3,
        explain: 'Delta 方法：$g(p)=p^2$，$g^{\\prime}(p)=2p$，$\\sqrt{n}(g(\\hat{p})-g(p))\\xrightarrow{d}\\mathcal{N}(0,[g^{\\prime}(p)]^2\\cdot p(1-p))=\\mathcal{N}(0,4p^2(1-p))$。这里 $4p^2(1-p)$ 是渐近方差（即 $n$ 倍的 $\\mathrm{Var}(g(\\hat{p}))$ 的渐近值），$\\mathrm{Var}(\\hat{p}^2)\\approx 4p^2(1-p)/n$。选 (D) 的表述更准确地说明了渐近方差的定义。',
      },
      {
        type: 'input',
        prompt: '设 $X_1,\\ldots,X_n\\overset{iid}{\\sim}\\mathrm{Pois}(\\lambda)$，$\\hat{\\lambda}_{MLE}=\\bar{X}$，$I(\\lambda)=1/\\lambda$。用 Delta 方法，$g(\\lambda)=\\sqrt{\\lambda}$ 的 MLE 的渐近方差（$n$ 倍的 $\\mathrm{Var}(\\sqrt{\\bar{X}})$ 的极限）是多少？（以 $\\lambda$ 表达，如填"λ/4 × 1/n"形式中的 λ/4 部分）',
        accept: ['1/4', '0.25', '\\frac{1}{4}'],
        explain: '$g(\\lambda)=\\sqrt{\\lambda}$，$g^{\\prime}(\\lambda)=1/(2\\sqrt{\\lambda})$。$\\sqrt{n}(\\hat{\\lambda}-\\lambda)\\xrightarrow{d}\\mathcal{N}(0,\\lambda)$（因为 $\\mathrm{Var}(\\bar{X})=\\lambda/n$，即渐近方差为 $\\lambda$）。Delta 方法：渐近方差 $=[g^{\\prime}(\\lambda)]^2\\cdot\\lambda=\\frac{1}{4\\lambda}\\cdot\\lambda=\\frac{1}{4}$。即 $\\sqrt{n}(\\sqrt{\\bar{X}}-\\sqrt{\\lambda})\\xrightarrow{d}\\mathcal{N}(0,1/4)$，$\\mathrm{Var}(\\sqrt{\\bar{X}})\\approx\\frac{1}{4n}$。',
      },
      {
        type: 'judge',
        prompt: 'MLE 的不变性与渐近有效性意味着：对任意函数 $g(\\theta)$，$g(\\hat{\\theta}_{MLE})$ 既是 $g(\\theta)$ 的 MLE，又是 $g(\\theta)$ 的渐近有效估计量，这个说法正确吗？',
        answer: true,
        explain: '正确。(1) 不变性：$g(\\hat{\\theta}_{MLE})$ 是 $g(\\theta)$ 的 MLE（由 MLE 不变性原理）；(2) 渐近有效：由 Delta 方法，$g(\\hat{\\theta}_{MLE})$ 的渐近方差为 $[g^{\\prime}(\\theta)]^2/(nI(\\theta))$，而 $g(\\theta)$ 的 Fisher 信息量为 $I(\\theta)/[g^{\\prime}(\\theta)]^2$（由参数变换公式），CR 下界 $=1/(n\\cdot I(\\theta)/[g^{\\prime}(\\theta)]^2)=[g^{\\prime}(\\theta)]^2/(nI(\\theta))$——两者相等，渐近有效。',
      },
      {
        type: 'match',
        prompt: '将 MLE 的渐近性质与对应描述配对：',
        left: ['渐近正态性', '渐近有效性', '不变性（渐近版）', '一致性（渐近版）'],
        right: [
          '渐近方差达到 CR 下界 $1/(nI(\\theta_0))$，大样本无偏估计中最优',
          '$\\hat{\\theta}_{MLE}\\xrightarrow{P}\\theta_0$（方差趋于 0）',
          '$g(\\hat{\\theta}_{MLE})$ 的渐近方差 $=[g^{\\prime}(\\theta)]^2/(nI(\\theta))$（Delta 方法）',
          '$\\sqrt{n}(\\hat{\\theta}_{MLE}-\\theta_0)\\xrightarrow{d}\\mathcal{N}(0,1/I(\\theta_0))$',
        ],
        answer: [3, 0, 2, 1],
        explain: '渐近正态性：MLE 标准化后收敛到标准正态；渐近有效性：渐近方差等于 CR 下界（所有渐近无偏估计中最优）；不变性渐近版：Delta 方法给出函数变换的渐近方差；一致性：方差趋零意味着 MLE 依概率收敛到真值。',
      },
      {
        type: 'choice',
        prompt: '以下关于 MLE 渐近理论的正则条件，哪个分布违反了该条件？',
        options: [
          '$\\mathcal{N}(\\mu,\\sigma^2)$（$\\mu$ 未知，$\\sigma^2$ 已知）',
          '$\\mathrm{Pois}(\\lambda)$（$\\lambda>0$ 未知）',
          '$U(0,\\theta)$（$\\theta>0$ 未知）',
          '$\\mathrm{Bernoulli}(p)$（$0<p<1$ 未知）',
        ],
        answer: 2,
        explain: '$U(0,\\theta)$ 的支撑 $[0,\\theta]$ 依赖参数 $\\theta$，违反正则条件"支撑不依赖参数"。因此均匀分布的 MLE $\\hat{\\theta}=X_{(n)}$ 不满足渐近正态性定理，其极限分布是指数分布（$n(\\theta-X_{(n)})\\xrightarrow{d}\\mathrm{Exp}(1/\\theta)$），不是正态。其余三个分布均满足正则条件。',
      },
      {
        type: 'choice',
        prompt: '在所有估计量（包括有偏的）中，MLE 的定位是：',
        options: [
          '任何样本量下均是方差最小的估计量（全局最优）',
          '在所有无偏估计量中方差最小（有效估计量）',
          '渐近有效：大样本时在所有渐近无偏估计量中渐近方差最小',
          'MLE 没有特殊的最优性，只是计算简便',
        ],
        answer: 2,
        explain: 'MLE 的最优性是渐近意义下的：大样本时，在满足正则条件的情况下，MLE 的渐近方差等于 CR 下界，是所有渐近无偏估计量中渐近方差最小的（渐近有效）。小样本时 MLE 不一定有偏，也不一定是有效估计量（例如正态方差 MLE 有偏）。(B) 说法错误——MLE 不一定是无偏估计，更不是所有无偏估计中方差最小的（小样本时）。',
      },
    ],
  },
]
