export const LESSONS = [
  {
    id: 't20-a',
    title: '贝叶斯学派基础与先验-后验框架',
    subtitle: '从"概率是频率"到"概率是信念"——贝叶斯三件套与先验选择',
    intro: [
      {
        title: '引入：抛硬币 10 次，频率派 vs 贝叶斯派',
        body: '一枚来源未知的硬币，抛 10 次得 7 次正面。**频率派直觉**：$\\hat{p}_{MLE}=7/10=0.7$，只凭数据，无任何前提。**贝叶斯派的反问**：如果我们相信这枚硬币"大概是公平的"，应该给出多大的估计？若先验取 $\\mathrm{Beta}(5,5)$（等效于"之前见过 5 次正面、5 次反面"），后验为 $\\mathrm{Beta}(12,8)$，后验均值 $=12/20=0.6$——比 0.7 更靠近 0.5。**为什么？** 先验在"挤压"数据的估计。10 次试验的信息不足以完全推翻先验。随着数据增多（100 次、1000 次），先验影响越来越弱，两派答案趋于一致。这就是**先验的力量**——在观测数据有限时，先验知识是无价的正则化工具。',
        tip: '先验的影响不是永久的——大样本时贝叶斯后验与 MLE 收敛一致（Bernstein-von Mises 定理）。先验在小样本时最重要，大样本时可以忽略。',
      },
      {
        title: '贝叶斯学派 vs 频率学派：根本区别',
        body: '两大学派对"概率"和"参数"的理解截然不同。频率学派：概率 $=$ 长期频率；参数 $\\theta$ 是**固定未知常数**；推断结果是点估计和置信区间；置信区间含义是"重复实验中 95% 覆盖真值"。贝叶斯学派：概率 $=$ **主观信念的度量**；参数 $\\theta$ 是**随机变量**，有概率分布；推断结果是后验分布 $\\pi(\\theta\\mid\\mathbf{x})$；可信区间直接说"$P(\\theta\\in[l,u]\\mid\\mathbf{x})=95\\%$"（直觉上更自然）。核心区别：频率派不允许给参数赋概率，贝叶斯派认为这是合理的主观度量。',
        tip: '贝叶斯与频率派的关键对比记忆：频率派——参数是常数，区间是随机的；贝叶斯——参数是随机的，给定数据后说"参数有 95% 概率在区间内"是合法的。',
      },
      {
        title: '贝叶斯三件套：先验、似然、后验',
        body: '贝叶斯推断的核心公式（贝叶斯定理的参数推断形式）：$\\pi(\\theta\\mid\\mathbf{x})=\\frac{p(\\mathbf{x}\\mid\\theta)\\pi(\\theta)}{p(\\mathbf{x})}\\propto p(\\mathbf{x}\\mid\\theta)\\cdot\\pi(\\theta)$，用文字：后验 $\\propto$ 似然 $\\times$ 先验。三个要素：(1) **先验** $\\pi(\\theta)$：观测数据之前对 $\\theta$ 的信念；(2) **似然** $p(\\mathbf{x}\\mid\\theta)$：给定 $\\theta$ 时数据的概率；(3) **后验** $\\pi(\\theta\\mid\\mathbf{x})$：观测数据后对 $\\theta$ 的更新信念。分母 $p(\\mathbf{x})=\\int p(\\mathbf{x}\\mid\\theta)\\pi(\\theta)d\\theta$ 是边际似然（归一化常数）——保证后验积分为 1，但计算困难，在共轭模型中可以省略（识别核函数后自动归一化）。',
        formula: '\\pi(\\theta\\mid\\mathbf{x})\\propto p(\\mathbf{x}\\mid\\theta)\\cdot\\pi(\\theta)',
        tip: '正比号的含义：后验密度函数与 $p(\\mathbf{x}\\mid\\theta)\\pi(\\theta)$ 成正比，归一化常数由"后验必须积分为 1"唯一确定。共轭情形下，识别核函数形状即可确定后验参数，无需手动积分。',
      },
      {
        title: '贝叶斯更新：序贯性与先验的选取',
        body: '贝叶斯推断是递推更新过程：当新数据到来，当前后验成为新的先验。$\\pi(\\theta)\\xrightarrow{\\text{观测}x_1}\\pi(\\theta\\mid x_1)\\xrightarrow{\\text{观测}x_2}\\pi(\\theta\\mid x_1,x_2)\\xrightarrow{\\cdots}\\pi(\\theta\\mid x_1,\\ldots,x_n)$。先验选取三类：(1) **无信息先验**：均匀先验 $\\pi(\\theta)\\propto1$ 或 Jeffreys 先验 $\\pi(\\theta)\\propto\\sqrt{I(\\theta)}$（参数变换不变性）；(2) **信息先验**：基于历史数据或专家经验；(3) **共轭先验**：先验与似然同族，后验形式相同，计算方便（下一节详细介绍）。先验选择原则：毫无先验知识 $\\to$ 均匀先验；追求计算便利 $\\to$ 共轭先验；有专家知识 $\\to$ 信息先验。先验影响随 $n\\to\\infty$ 消失——不要因选先验困难而放弃贝叶斯方法。',
        tip: 'Jeffreys 先验 $\\pi(\\theta)\\propto\\sqrt{I(\\theta)}$ 是"无信息先验"的理论最优选择，具有参数重参数化不变性（即换一种参数化方式不影响推断结论）。实践中常用均匀先验近似替代。',
      },
      {
        title: '完整示例：二项模型的 Beta 先验（Beta-Binomial 共轭）',
        body: '设定：$n$ 次独立伯努利试验，成功 $k$ 次，参数 $\\theta\\in(0,1)$。似然：$p(k\\mid\\theta)=\\binom{n}{k}\\theta^k(1-\\theta)^{n-k}\\propto\\theta^k(1-\\theta)^{n-k}$（省略与 $\\theta$ 无关的系数）。先验：$\\theta\\sim\\mathrm{Beta}(\\alpha,\\beta)$，即 $\\pi(\\theta)\\propto\\theta^{\\alpha-1}(1-\\theta)^{\\beta-1}$。后验（识别核函数）：$\\pi(\\theta\\mid k)\\propto\\theta^k(1-\\theta)^{n-k}\\cdot\\theta^{\\alpha-1}(1-\\theta)^{\\beta-1}=\\theta^{(k+\\alpha)-1}(1-\\theta)^{(n-k+\\beta)-1}$。识别出 Beta 分布的核函数：**后验** $\\theta\\mid k\\sim\\mathrm{Beta}(k+\\alpha,\\;n-k+\\beta)$。直觉：$\\alpha,\\beta$ 是"伪计数"——$\\alpha$ 是虚拟的历史成功次数，$\\beta$ 是历史失败次数，后验只需将实际成功次数 $k$ 加到 $\\alpha$，失败次数 $n-k$ 加到 $\\beta$。',
        formula: '\\theta\\mid k\\sim\\mathrm{Beta}(k+\\alpha,\\;n-k+\\beta)',
        reveal: {
          q: '某品牌手机次品率 $\\theta$ 未知，历史先验为 $\\theta\\sim\\mathrm{Beta}(3,27)$（等效于历史见过 3 件次品、27 件合格品）。今抽检 50 件，发现 2 件次品。写出后验分布，计算后验均值。',
          a: '后验：$\\theta\\mid k=2,n=50\\sim\\mathrm{Beta}(3+2,\\;27+48)=\\mathrm{Beta}(5,75)$。后验均值：$E[\\theta\\mid k]=(5)/(5+75)=5/80=0.0625$（6.25%）。对比 MLE：$\\hat{\\theta}_{MLE}=2/50=0.04$（4%），先验均值 $3/30=0.1$（10%）。后验均值 0.0625 是在 MLE（0.04）和先验均值（0.10）之间"折中"，先验起到正则化作用。',
        },
      },
      {
        title: '贝叶斯推断 5 步流程与易错点',
        body: '5 步流程：(1) 选先验 $\\pi(\\theta)$——共轭/无信息/信息先验；(2) 写似然 $p(\\mathbf{x}\\mid\\theta)$——只保留含 $\\theta$ 的因子；(3) 写后验 $\\pi(\\theta\\mid\\mathbf{x})\\propto$似然$\\times$先验——识别核函数，归一化；(4) 选估计量——后验均值/中位数/MAP；(5) 可信区间——等尾分位数或 HPD 区间。易错点：① 后验 $\\propto$ 似然 $\\times$ 先验，但必须归一化（积分为 1）；② MAP $\\neq$ 后验均值（偏斜分布时差异显著）；③ 可信区间 $P(\\theta\\in[l,u]\\mid\\mathbf{x})=95\\%$ vs 频率置信区间（两者语义不同，无信息先验下数值可相同）；④ 伪计数：Beta 先验 $\\mathrm{Beta}(\\alpha,\\beta)$ 中 $\\alpha$ 和 $\\beta$ 是伪计数，不是 $\\alpha-1$！',
        tip: '识别共轭先验的技巧：写出似然的核函数（含 $\\theta$ 的部分），找到与之配对形成 Beta / Gamma / 正态形状的先验——后验就是同族分布，参数直接相加更新。',
      },
    ],
    questions: [
      {
        type: 'choice',
        prompt: '以下关于贝叶斯学派与频率学派的对比，哪个说法是正确的？',
        options: [
          '频率学派认为参数是随机变量，贝叶斯学派认为参数是固定常数',
          '贝叶斯学派认为参数是随机变量，推断结果是后验分布 $\\pi(\\theta\\mid\\mathbf{x})$',
          '两者的置信区间含义相同，都是"参数以 $1-\\alpha$ 概率在区间内"',
          '贝叶斯方法需要大样本，频率学派可以用于小样本',
        ],
        answer: 1,
        explain: '贝叶斯学派：参数 $\\theta$ 是随机变量，通过先验分布 $\\pi(\\theta)$ 表达不确定性；观测数据后，推断结果是后验分布 $\\pi(\\theta\\mid\\mathbf{x})$，包含了关于 $\\theta$ 的全部信息。频率学派：参数是固定未知常数，不赋予概率分布；推断结果是点估计和置信区间（置信区间不是"参数在区间内的概率"）。贝叶斯方法在小样本时（有先验信息）反而更有优势。',
      },
      {
        type: 'judge',
        prompt: '贝叶斯公式 $\\pi(\\theta\\mid\\mathbf{x})\\propto p(\\mathbf{x}\\mid\\theta)\\pi(\\theta)$ 中，正比号说明后验只是"与右侧成比例"，不需要归一化，这个说法正确吗？',
        answer: false,
        explain: '错误。$\\pi(\\theta\\mid\\mathbf{x})$ 必须是合法的概率分布，积分为 1。正比号只是省略了归一化常数 $p(\\mathbf{x})=\\int p(\\mathbf{x}\\mid\\theta)\\pi(\\theta)d\\theta$——在共轭情形下，识别出核函数形状后可以直接写出归一化后的后验；非共轭情形下，必须数值计算或用 MCMC 处理归一化常数。忽略归一化会导致后验"积分不为 1"的错误。',
      },
      {
        type: 'choice',
        prompt: '$X_1,\\ldots,X_n\\overset{iid}{\\sim}\\mathrm{Bernoulli}(\\theta)$，先验 $\\theta\\sim\\mathrm{Beta}(\\alpha,\\beta)$，观测到 $k$ 次成功。后验分布是：',
        options: [
          '$\\mathrm{Beta}(\\alpha+k,\\beta+n-k)$',
          '$\\mathrm{Beta}(\\alpha+n,\\beta+k)$',
          '$\\mathrm{Beta}(k,n-k)$（与先验无关）',
          '$\\mathcal{N}(k/n,k(n-k)/n^3)$（CLT 近似）',
        ],
        answer: 0,
        explain: '后验核函数：$\\pi(\\theta\\mid k)\\propto\\theta^k(1-\\theta)^{n-k}\\cdot\\theta^{\\alpha-1}(1-\\theta)^{\\beta-1}=\\theta^{(k+\\alpha)-1}(1-\\theta)^{(n-k+\\beta)-1}$，识别为 $\\mathrm{Beta}(k+\\alpha,\\;n-k+\\beta)$。更新规则：成功次数 $k$ 加到 $\\alpha$，失败次数 $n-k$ 加到 $\\beta$。$\\mathrm{Beta}(k,n-k)$ 对应均匀先验 $\\alpha=\\beta=1$ 的特例（$\\mathrm{Beta}(k+1,n-k+1)$），不完全正确。',
      },
      {
        type: 'input',
        prompt: '某网站点击率 $\\theta$ 未知，展示 100 次点击 30 次。使用均匀先验 $\\mathrm{Beta}(1,1)$。后验均值（MMSE 估计）$=$ ？（分数形式，如 31/102）',
        accept: ['31/102', '31102', '0.304', '0.3039'],
        explain: '先验 $\\mathrm{Beta}(1,1)$（均匀先验），$n=100$，$k=30$。后验 $\\theta\\mid k\\sim\\mathrm{Beta}(1+30,\\;1+70)=\\mathrm{Beta}(31,71)$。后验均值（Beta 分布均值 $=\\alpha/(\\alpha+\\beta)$）：$E[\\theta\\mid k]=31/(31+71)=31/102\\approx0.304$。比 MLE $\\hat{p}=30/100=0.3$ 略高（均匀先验相当于加了 1 次成功和 1 次失败的"虚拟数据"，轻微向中心拉）。',
      },
      {
        type: 'judge',
        prompt: '贝叶斯推断的序贯更新性质：先处理 $x_1$ 得到后验，再将该后验作为先验处理 $x_2$，最终结果与一次性处理所有数据 $(x_1,x_2)$ 的后验**完全相同**，这个说法正确吗？',
        answer: true,
        explain: '正确。由贝叶斯公式的乘法性质，$\\pi(\\theta\\mid x_1,x_2)\\propto p(x_1,x_2\\mid\\theta)\\pi(\\theta)=p(x_1\\mid\\theta)p(x_2\\mid\\theta)\\pi(\\theta)$（i.i.d.）。序贯更新：先用 $x_1$ 得到 $\\pi(\\theta\\mid x_1)\\propto p(x_1\\mid\\theta)\\pi(\\theta)$，再用 $x_2$ 更新：$\\pi(\\theta\\mid x_1,x_2)\\propto p(x_2\\mid\\theta)\\cdot\\pi(\\theta\\mid x_1)\\propto p(x_2\\mid\\theta)p(x_1\\mid\\theta)\\pi(\\theta)$——与一次性计算完全等价。这是贝叶斯方法序贯数据处理的重要优势。',
      },
      {
        type: 'match',
        prompt: '将先验类型与对应描述配对：',
        left: ['均匀先验 $\\pi(\\theta)\\propto1$', 'Jeffreys 先验 $\\pi(\\theta)\\propto\\sqrt{I(\\theta)}$', '共轭先验', '信息先验'],
        right: [
          '先验族与后验族相同，参数更新规则简单（如 Beta-Bernoulli）',
          '无信息先验，参数变换不变性，$I(\\theta)$ 是 Fisher 信息量',
          '基于历史数据或专家经验，编码具体先验信念（如 $\\mathrm{Beta}(3,27)$）',
          '对参数完全无知时使用，在参数范围内各值等可能',
        ],
        answer: [3, 1, 0, 2],
        explain: '均匀先验：$\\pi(\\theta)=c$（常数），无信息，参数等可能；Jeffreys 先验：$\\pi(\\theta)\\propto\\sqrt{I(\\theta)}$，参数变换不变的无信息先验（均匀先验在重参数化后不再无信息，Jeffreys 先验解决了这个问题）；共轭先验：Beta-Bernoulli、Gamma-Poisson 等，后验与先验同族，计算方便；信息先验：编码已知信息，如历史次品率经验 $\\mathrm{Beta}(3,27)$。',
      },
      {
        type: 'choice',
        prompt: '贝叶斯可信区间（credible interval）$[l,u]$ 满足 $P(l\\leq\\theta\\leq u\\mid\\mathbf{x})=95\\%$，频率学派置信区间满足 $P_\\theta(L\\leq\\theta\\leq U)=95\\%$。两者的本质区别是：',
        options: [
          '计算方法不同，但含义相同（都是"95% 概率包含真值"）',
          '贝叶斯区间中 $\\theta$ 是随机变量，频率区间中区间端点是随机变量',
          '贝叶斯区间只适用于大样本，频率区间适用于小样本',
          '贝叶斯区间不需要先验，频率区间需要先验',
        ],
        answer: 1,
        explain: '本质区别在于"谁是随机的"。贝叶斯：$\\theta$ 是随机变量，$[l,u]$ 是计算出的固定区间，直接说"$\\theta$ 在该区间的概率是 95%"。频率学派：$\\theta$ 是固定常数，$[L,U]$ 是随机变量（随抽样变化），"95%" 指的是区间覆盖固定 $\\theta$ 的频率（重复实验的频率，不是单次实验的概率）。无信息先验下，两者数值可以相同，但含义截然不同。',
      },
      {
        type: 'judge',
        prompt: '均匀先验 $\\theta\\sim\\mathrm{Beta}(1,1)$ 下，Beta-Binomial 模型的后验均值（MMSE 估计）退化为 MLE $\\hat{p}=k/n$，这个说法正确吗？',
        answer: false,
        explain: '不完全正确。均匀先验 $\\mathrm{Beta}(1,1)$，后验为 $\\mathrm{Beta}(k+1,n-k+1)$，后验均值 $=(k+1)/(n+2)\\neq k/n$（MLE）。只有当 $n\\to\\infty$ 时，$(k+1)/(n+2)\\to k/n$（先验影响消失）。真正退化为 MLE 的是**无信息先验 $\\alpha=\\beta=0$（Haldane 先验）**，此时后验均值 $=k/n$——但这是一个不正则先验（积分发散）。均匀先验下后验均值略微偏离 MLE，更靠近 0.5（有正则化效果）。',
      },
    ],
  },
  {
    id: 't20-b',
    title: '共轭先验与贝叶斯点估计',
    subtitle: 'Beta-Binomial、Gamma-Poisson、正态-正态——三大共轭对的推导与 MAP 估计',
    intro: [
      {
        title: '共轭先验：让后验有解析解',
        body: '**定义**：若先验分布族 $\\mathcal{F}$ 满足：对任意 $\\pi(\\theta)\\in\\mathcal{F}$，后验 $\\pi(\\theta\\mid\\mathbf{x})$ 仍属于 $\\mathcal{F}$，则称 $\\mathcal{F}$ 为该似然的**共轭先验族**。共轭的好处：(1) 后验有解析表达式，无需数值积分；(2) 参数更新规则简单，直观的"计数"解释；(3) 适合序贯更新。三大共轭对速查：Beta-Binomial（成功概率）：后验还是 Beta，参数 $\\alpha\\to\\alpha+k$，$\\beta\\to\\beta+n-k$；Gamma-Poisson（速率参数）：后验还是 Gamma，$\\alpha\\to\\alpha+\\sum x_i$，$\\beta\\to\\beta+n$；正态-正态（均值，$\\sigma^2$ 已知）：后验还是正态，精度相加更新（见下文）。',
        tip: '共轭更新规则的记忆方法：Beta 先验的 $\\alpha,\\beta$ 是"虚拟的成功/失败计数"，实际数据直接加上去；Gamma 先验的 $\\alpha,\\beta$ 是"虚拟的事件总数/时间单位"，实际数据加上去。',
      },
      {
        title: 'Gamma-Poisson 共轭：速率参数的贝叶斯估计',
        body: '设 $X_1,\\ldots,X_n\\overset{iid}{\\sim}\\mathrm{Pois}(\\lambda)$，先验 $\\lambda\\sim\\mathrm{Gamma}(\\alpha,\\beta)$（$\\beta$ 为速率参数，均值 $=\\alpha/\\beta$）。似然核函数：$p(\\mathbf{x}\\mid\\lambda)\\propto\\lambda^{\\sum x_i}e^{-n\\lambda}$；先验核函数：$\\pi(\\lambda)\\propto\\lambda^{\\alpha-1}e^{-\\beta\\lambda}$。后验核函数：$\\pi(\\lambda\\mid\\mathbf{x})\\propto\\lambda^{(\\alpha+\\sum x_i)-1}e^{-(\\beta+n)\\lambda}$，识别为 $\\mathrm{Gamma}(\\alpha+\\sum x_i,\\;\\beta+n)$。直觉：$\\alpha$ 是历史观测到的事件总数，$\\beta$ 是历史观测的时间单位总数——实际数据直接累加。后验均值（MMSE 估计）$=\\frac{\\alpha+\\sum x_i}{\\beta+n}$（先验均值与 MLE 的加权平均）。',
        formula: '\\lambda\\mid\\mathbf{x}\\sim\\mathrm{Gamma}(\\alpha+\\textstyle\\sum x_i,\\;\\beta+n)',
        tip: 'Gamma 分布的众数（MAP 点估计）$=(\\alpha-1)/\\beta$（$\\alpha\\geq1$），而均值 $=\\alpha/\\beta$。后验 $\\mathrm{Gamma}(\\alpha+\\sum x_i,\\beta+n)$ 的众数 $=(\\alpha+\\sum x_i-1)/(\\beta+n)$，与后验均值不同（Gamma 分布右偏）。',
      },
      {
        title: '正态-正态共轭：均值的贝叶斯估计',
        body: '设 $X_1,\\ldots,X_n\\overset{iid}{\\sim}\\mathcal{N}(\\mu,\\sigma^2)$，$\\sigma^2$ 已知，先验 $\\mu\\sim\\mathcal{N}(\\mu_0,\\tau_0^2)$。后验仍是正态（正态-正态共轭），参数由**精度（方差倒数）加法则**更新：后验精度 $=$ 先验精度 $+$ 数据精度：$\\frac{1}{\\tau_n^2}=\\frac{1}{\\tau_0^2}+\\frac{n}{\\sigma^2}$。后验均值（精度加权平均）：$\\mu_n=\\tau_n^2\\left(\\frac{\\mu_0}{\\tau_0^2}+\\frac{n\\bar{x}}{\\sigma^2}\\right)=\\frac{\\frac{1}{\\tau_0^2}\\mu_0+\\frac{n}{\\sigma^2}\\bar{x}}{\\frac{1}{\\tau_0^2}+\\frac{n}{\\sigma^2}}$。后验 $\\mu\\mid\\mathbf{x}\\sim\\mathcal{N}(\\mu_n,\\tau_n^2)$。极端情形：$\\tau_0^2\\to\\infty$（先验极不确定）$\\Rightarrow\\mu_n\\to\\bar{x}$（退化为 MLE）；$n\\to\\infty$ $\\Rightarrow\\mu_n\\to\\bar{x}$（数据主导）；$n\\to0$ $\\Rightarrow\\mu_n\\to\\mu_0$（先验主导）。',
        formula: '\\frac{1}{\\tau_n^2}=\\frac{1}{\\tau_0^2}+\\frac{n}{\\sigma^2},\\quad \\mu_n=\\frac{\\frac{1}{\\tau_0^2}\\mu_0+\\frac{n}{\\sigma^2}\\bar{x}}{\\frac{1}{\\tau_0^2}+\\frac{n}{\\sigma^2}}',
        steps: [
          '步骤一：写先验精度 $1/\\tau_0^2$ 和数据精度 $n/\\sigma^2$',
          '步骤二：后验精度 $=$ 先验精度 $+$ 数据精度（精度相加）',
          '步骤三：后验均值 $=$ 精度加权平均（先验均值和样本均值的加权）',
          '步骤四：后验 $\\mu\\mid\\mathbf{x}\\sim\\mathcal{N}(\\mu_n,\\tau_n^2)$，直接读参数',
        ],
        tip: '精度 $=1/\\sigma^2$（方差的倒数），精度越大越确定。精度相加规则：先验和数据的"确定性信息量"可以叠加，后验比两者中任何一个都更确定（精度更大，方差更小）。',
      },
      {
        title: '三种贝叶斯点估计：损失函数决定选择',
        body: '后验分布包含全部信息，但若需要一个数字，需要从后验中提取。不同损失函数对应不同最优点估计：平方损失 $(\\hat{\\theta}-\\theta)^2$ $\\Rightarrow$ 后验均值 $E[\\theta\\mid\\mathbf{x}]$（MMSE 估计）；绝对值损失 $|\\hat{\\theta}-\\theta|$ $\\Rightarrow$ 后验中位数；0-1 损失 $\\mathbf{1}[\\hat{\\theta}\\neq\\theta]$ $\\Rightarrow$ 后验众数 $=$ MAP 估计。后验均值：Beta$(\\alpha,\\beta)$ 的均值 $=\\alpha/(\\alpha+\\beta)$；Gamma$(\\alpha,\\beta)$ 的均值 $=\\alpha/\\beta$；正态分布：均值 $=$ 均值。MAP：Beta$(\\alpha,\\beta)$ 的众数 $=(\\alpha-1)/(\\alpha+\\beta-2)$（$\\alpha,\\beta>1$）；Gamma$(\\alpha,\\beta)$ 的众数 $=(\\alpha-1)/\\beta$（$\\alpha\\geq1$）；正态：众数 $=$ 均值（对称分布均值 $=$ 中位数 $=$ 众数）。',
        formula: 'E[\\theta\\mid\\mathbf{x}]\\text{（平方损失）},\\quad \\arg\\max\\pi(\\theta\\mid\\mathbf{x})\\text{（0-1 损失，MAP）}',
        tip: '对称单峰分布（如正态后验）：后验均值 $=$ 中位数 $=$ 众数（MAP）。偏斜分布（Beta、Gamma 后验）：均值 $>$ 中位数 $>$ 众数（右偏时），三者显著不同，不能混用。',
      },
      {
        title: 'MAP 估计 = 带正则化的 MLE',
        body: 'MAP 估计：$\\hat{\\theta}_{MAP}=\\arg\\max_\\theta[\\log p(\\mathbf{x}\\mid\\theta)+\\log\\pi(\\theta)]$。当先验是**高斯先验** $\\theta_j\\overset{iid}{\\sim}\\mathcal{N}(0,\\sigma_0^2)$ 时，$\\log\\pi(\\theta)=-\\frac{1}{2\\sigma_0^2}\\|\\theta\\|_2^2+\\mathrm{const}$，MAP 等价于：$\\hat{\\theta}_{MAP}=\\arg\\min_\\theta[-\\ell(\\theta)+\\frac{\\lambda}{2}\\|\\theta\\|_2^2]$（$\\lambda=1/\\sigma_0^2$），即**带 L2 正则化（Ridge/权重衰减）的 MLE**。当先验是**拉普拉斯先验** $\\theta_j\\overset{iid}{\\sim}\\mathrm{Laplace}(0,b)$ 时，MAP 等价于：$\\arg\\min_\\theta[-\\ell(\\theta)+\\lambda\\|\\theta\\|_1]$（$\\lambda=1/b$），即**带 L1 正则化（LASSO）的 MLE**。深度学习中的权重衰减（weight decay）= 高斯先验 MAP 估计；稀疏正则化 = 拉普拉斯先验 MAP 估计。',
        formula: '\\text{高斯先验}\\;\\theta\\sim\\mathcal{N}(0,\\sigma_0^2)\\;\\Leftrightarrow\\;\\lambda\\|\\theta\\|_2^2\\text{（L2/Ridge）};\\quad \\text{拉普拉斯先验}\\;\\Leftrightarrow\\;\\lambda\\|\\theta\\|_1\\text{（L1/LASSO）}',
        reveal: {
          q: '设后验为 $\\theta\\mid\\mathbf{x}\\sim\\mathrm{Gamma}(3,1)$。分别计算：(1) 平方损失下的最优估计（后验均值）；(2) 0-1 损失下的最优估计（MAP，后验众数）；(3) 两者相同吗？为什么？',
          a: '(1) $\\mathrm{Gamma}(\\alpha,\\beta)$ 均值 $=\\alpha/\\beta=3/1=3.0$，平方损失最优估计 $=3.0$。(2) 众数（MAP）$=(\\alpha-1)/\\beta=(3-1)/1=2.0$，0-1 损失最优估计 $=2.0$。(3) 不同。$\\mathrm{Gamma}(3,1)$ 是右偏分布（均值 $>$ 中位数 $>$ 众数），均值 3.0 $>$ 众数 2.0，两者差距显著。偏斜后验中，不同损失函数导致不同最优估计，不能混用。',
        },
      },
      {
        title: '共轭先验完整速查表',
        body: '常见共轭先验对汇总（$n$ 个 i.i.d. 样本）：(1) 二项/伯努利 $\\mathrm{Bin}(n,\\theta)$，共轭先验 $\\mathrm{Beta}(\\alpha,\\beta)$，后验 $\\mathrm{Beta}(\\alpha+k,\\beta+n-k)$，后验均值 $(\\alpha+k)/(\\alpha+\\beta+n)$；(2) 泊松 $\\mathrm{Pois}(\\lambda)$，共轭先验 $\\mathrm{Gamma}(\\alpha,\\beta)$，后验 $\\mathrm{Gamma}(\\alpha+\\sum x_i,\\beta+n)$，后验均值 $(\\alpha+\\sum x_i)/(\\beta+n)$；(3) 指数 $\\mathrm{Exp}(\\lambda)$，共轭先验 $\\mathrm{Gamma}(\\alpha,\\beta)$，后验 $\\mathrm{Gamma}(\\alpha+n,\\beta+\\sum x_i)$；(4) 正态（$\\sigma^2$ 已知）$\\mathcal{N}(\\mu,\\sigma^2)$，共轭先验 $\\mathcal{N}(\\mu_0,\\tau_0^2)$，后验 $\\mathcal{N}(\\mu_n,\\tau_n^2)$（精度相加）；(5) 多项分布，共轭先验 $\\mathrm{Dirichlet}(\\boldsymbol{\\alpha})$，后验 $\\mathrm{Dirichlet}(\\boldsymbol{\\alpha}+\\mathbf{n})$。',
        tip: '指数分布的共轭是 Gamma，但更新规则与泊松不同：$\\alpha\\to\\alpha+n$（加样本个数），$\\beta\\to\\beta+\\sum x_i$（加观测总和）。原因：$\\mathrm{Exp}(\\lambda)$ 的充分统计量是 $(n,\\sum x_i)$，而泊松的充分统计量是 $(n,\\sum x_i)$ 但加法方向不同。',
      },
    ],
    questions: [
      {
        type: 'choice',
        prompt: '设 $X_1,\\ldots,X_n\\overset{iid}{\\sim}\\mathrm{Pois}(\\lambda)$，先验 $\\lambda\\sim\\mathrm{Gamma}(\\alpha,\\beta)$。后验分布是：',
        options: [
          '$\\mathrm{Gamma}(\\alpha+n,\\beta+\\sum x_i)$',
          '$\\mathrm{Gamma}(\\alpha+\\sum x_i,\\beta+n)$',
          '$\\mathrm{Gamma}(\\alpha+\\sum x_i,\\beta)$',
          '$\\mathrm{Gamma}(\\alpha,\\beta+n)$',
        ],
        answer: 1,
        explain: '泊松似然核函数：$p(\\mathbf{x}\\mid\\lambda)\\propto\\lambda^{\\sum x_i}e^{-n\\lambda}$；先验 $\\pi(\\lambda)\\propto\\lambda^{\\alpha-1}e^{-\\beta\\lambda}$；后验 $\\propto\\lambda^{(\\alpha+\\sum x_i)-1}e^{-(\\beta+n)\\lambda}$，识别为 $\\mathrm{Gamma}(\\alpha+\\sum x_i,\\beta+n)$。更新规则：$\\alpha\\to\\alpha+\\sum x_i$（加观测总事件数），$\\beta\\to\\beta+n$（加观测时间单位数）。后验均值 $=(\\alpha+\\sum x_i)/(\\beta+n)$。',
      },
      {
        type: 'judge',
        prompt: '正态-正态共轭模型（$\\sigma^2$ 已知，先验 $\\mu\\sim\\mathcal{N}(\\mu_0,\\tau_0^2)$）中，后验精度等于先验精度加数据精度 $n/\\sigma^2$，即精度相加；后验方差比先验方差更小，这个说法正确吗？',
        answer: true,
        explain: '正确。后验精度 $1/\\tau_n^2=1/\\tau_0^2+n/\\sigma^2>1/\\tau_0^2$（精度增加），故后验方差 $\\tau_n^2<\\tau_0^2$（方差减小）。直觉：数据提供了额外的信息（精度 $n/\\sigma^2$），叠加在先验信息上，使得后验对 $\\mu$ 的不确定性降低（方差减小）。每增加一个观测，精度增加 $1/\\sigma^2$，方差减小，后验分布越来越"尖锐"。',
      },
      {
        type: 'choice',
        prompt: '设后验分布为 $\\mathrm{Beta}(5,75)$。在绝对值损失 $|\\hat{\\theta}-\\theta|$ 下，最优贝叶斯估计是：',
        options: [
          '后验均值 $=5/(5+75)=0.0625$',
          '后验中位数（Beta$(5,75)$ 分布的 0.5 分位数，约 0.058）',
          '后验众数（MAP）$=(5-1)/(5+75-2)=4/78\\approx0.051$',
          '$\\hat{\\theta}_{MLE}=2/50=0.04$',
        ],
        answer: 1,
        explain: '绝对值损失 $|\\hat{\\theta}-\\theta|$ 下，最优贝叶斯估计是**后验中位数**（使后验绝对误差最小的点是中位数）。Beta$(5,75)$ 是右偏分布，中位数 $<$ 均值（中位数约 0.058，均值 $=0.0625$，MAP $=0.051$）。三者大小关系：MAP（众数）$<$ 中位数 $<$ 均值（均值），对应 0.051 $<$ 0.058 $<$ 0.0625。',
      },
      {
        type: 'input',
        prompt: '某仪器测物理量 $\\mu$（测量噪声 $\\sigma^2=4$ 已知），先验 $\\mu\\sim\\mathcal{N}(10,9)$（$\\mu_0=10$，$\\tau_0^2=9$），进行 $n=9$ 次测量，$\\bar{x}=12.5$。后验精度 $1/\\tau_n^2=1/\\tau_0^2+n/\\sigma^2=$ ？（分数形式，如85/36）',
        accept: ['85/36', '2.36', '2.361', '\\frac{85}{36}'],
        explain: '$1/\\tau_n^2=1/\\tau_0^2+n/\\sigma^2=1/9+9/4=4/36+81/36=85/36\\approx2.361$。故 $\\tau_n^2=36/85\\approx0.424$。后验均值 $\\mu_n=\\tau_n^2(\\mu_0/\\tau_0^2+n\\bar{x}/\\sigma^2)=(36/85)\\times(10/9+9\\times12.5/4)=(36/85)\\times(1.111+28.125)=(36/85)\\times29.236\\approx12.38$。后验 $\\mu\\mid\\mathbf{x}\\sim\\mathcal{N}(12.38,0.424)$。',
      },
      {
        type: 'choice',
        prompt: 'MAP 估计与 MLE 的关系是：',
        options: [
          'MAP 是 MLE 的特例（当先验为均匀先验时 MAP $=$ MLE）',
          'MLE 是 MAP 的特例（当似然很大时 MLE $=$ MAP）',
          'MAP 和 MLE 总是相等的（不变性原理）',
          'MAP 是 MLE 加上正则化项的最大化（高斯先验对应 L2 正则化）',
        ],
        answer: 0,
        explain: 'MAP $=\\arg\\max[\\log p(\\mathbf{x}\\mid\\theta)+\\log\\pi(\\theta)]$。当先验是均匀分布 $\\pi(\\theta)\\propto1$ 时，$\\log\\pi(\\theta)=\\mathrm{const}$，MAP 退化为 $\\arg\\max\\log p(\\mathbf{x}\\mid\\theta)=$ MLE。因此 MLE 是 MAP 在均匀先验下的特例（(A) 正确）。(D) 也部分正确（高斯先验 MAP 确实等价于 L2 正则化 MLE），但 (A) 更直接回答了 MAP 与 MLE 的关系。两者均正确时，按题意选最直接的 (A)。',
      },
      {
        type: 'match',
        prompt: '将先验分布与等价的正则化形式配对：',
        left: ['均匀先验 $\\pi(\\theta)\\propto1$', '高斯先验 $\\theta\\sim\\mathcal{N}(0,\\sigma_0^2)$', '拉普拉斯先验 $\\theta\\sim\\mathrm{Laplace}(0,b)$', '信息先验 $\\theta\\sim\\mathrm{Beta}(3,27)$'],
        right: [
          '无正则化（MLE）',
          '非标准正则化（含具体先验信念，无简单正则项对应）',
          'L2 正则化（Ridge/权重衰减），$\\lambda=1/\\sigma_0^2$',
          'L1 正则化（LASSO，稀疏解），$\\lambda=1/b$',
        ],
        answer: [0, 2, 3, 1],
        explain: '均匀先验 MAP $=$ MLE（无正则化）；高斯先验 MAP $=$ L2 正则化 MLE（权重衰减），正则化系数 $\\lambda=1/\\sigma_0^2$（先验方差越小，正则化越强）；拉普拉斯先验 MAP $=$ L1 正则化 MLE（LASSO，产生稀疏解），$\\lambda=1/b$；信息先验如 $\\mathrm{Beta}(3,27)$ 没有简单的正则化对应，它直接编码了具体的先验信念。',
      },
      {
        type: 'choice',
        prompt: '设 $X_1,\\ldots,X_n\\overset{iid}{\\sim}\\mathrm{Bernoulli}(\\theta)$，先验 $\\theta\\sim\\mathrm{Beta}(\\alpha,\\beta)$，后验均值（MMSE 估计）可写成 MLE 与先验均值的加权平均：',
        options: [
          '$\\hat{\\theta}_{MMSE}=\\frac{n}{n+\\alpha+\\beta}\\cdot\\frac{k}{n}+\\frac{\\alpha+\\beta}{n+\\alpha+\\beta}\\cdot\\frac{\\alpha}{\\alpha+\\beta}$',
          '$\\hat{\\theta}_{MMSE}=\\frac{k+\\alpha}{n}$（MLE 加先验计数）',
          '$\\hat{\\theta}_{MMSE}=\\frac{n\\bar{x}+\\alpha\\mu_0}{n+\\alpha}$（正态加权公式）',
          '$\\hat{\\theta}_{MMSE}=\\bar{x}$（与先验无关）',
        ],
        answer: 0,
        explain: '后验均值 $=(k+\\alpha)/(n+\\alpha+\\beta)$。分子分母同除 $n$：$=\\frac{k/n+\\alpha/n}{1+(\\alpha+\\beta)/n}$。整理为加权平均：$=\\frac{n}{n+\\alpha+\\beta}\\cdot\\frac{k}{n}+\\frac{\\alpha+\\beta}{n+\\alpha+\\beta}\\cdot\\frac{\\alpha}{\\alpha+\\beta}$，即 $=$ 数据权重 $\\times$ MLE $+$ 先验权重 $\\times$ 先验均值。数据越多（$n$ 增大），MLE 权重增大，先验权重减小；数据很少时（$n\\ll\\alpha+\\beta$），先验主导。',
      },
      {
        type: 'judge',
        prompt: '泊松-Gamma 共轭模型中，若先验 $\\lambda\\sim\\mathrm{Gamma}(\\alpha,\\beta)$，观测 $n$ 个样本均值为 $\\bar{x}$，则后验均值（MMSE 估计）是 $\\frac{\\alpha+n\\bar{x}}{\\beta+n}$，这个说法正确吗？',
        answer: true,
        explain: '正确。$\\sum x_i=n\\bar{x}$，后验 $\\lambda\\mid\\mathbf{x}\\sim\\mathrm{Gamma}(\\alpha+\\sum x_i,\\beta+n)=\\mathrm{Gamma}(\\alpha+n\\bar{x},\\beta+n)$，后验均值 $=(\\alpha+n\\bar{x})/(\\beta+n)$。整理为加权平均：$=\\frac{\\beta}{\\beta+n}\\cdot\\frac{\\alpha}{\\beta}+\\frac{n}{\\beta+n}\\cdot\\bar{x}$，即先验均值 $\\alpha/\\beta$ 和样本均值 $\\bar{x}$ 的加权平均，权重为先验"样本量" $\\beta$ 和实际样本量 $n$ 之比。',
      },
    ],
  },
  {
    id: 't20-c',
    title: '贝叶斯可信区间与大样本性质',
    subtitle: 'HPD 区间、Bernstein-von Mises 定理、变分推断与贝叶斯神经网络简介',
    intro: [
      {
        title: '贝叶斯可信区间：直觉上更自然的区间',
        body: '**贝叶斯可信区间**（credible interval）：区间 $[l,u]$ 满足 $P(l\\leq\\theta\\leq u\\mid\\mathbf{x})=1-\\alpha$，含义是"给定观测数据，参数 $\\theta$ 以 $1-\\alpha$ 的后验概率落在 $[l,u]$ 内"。这正是大多数人直觉上期望置信区间拥有的含义！对比频率置信区间：参数固定，区间随机，"95%"是区间覆盖固定参数的频率——不直观。最常用的**等尾可信区间**：取后验分布的 $\\alpha/2$ 和 $1-\\alpha/2$ 分位数：$[Q_{\\alpha/2}(\\theta\\mid\\mathbf{x}),\\;Q_{1-\\alpha/2}(\\theta\\mid\\mathbf{x})]$。数值例（正态后验）：$\\mu\\mid\\mathbf{x}\\sim\\mathcal{N}(\\mu_n,\\tau_n^2)$，95% 可信区间 $=[\\mu_n-1.96\\tau_n,\\;\\mu_n+1.96\\tau_n]$（形式上与频率置信区间相同，但含义不同）。',
        formula: 'P(l\\leq\\theta\\leq u\\mid\\mathbf{x})=1-\\alpha\\quad\\Leftrightarrow\\quad[l,u]\\text{ 是 }1-\\alpha\\text{ 可信区间}',
        tip: '无信息先验下，贝叶斯可信区间与频率置信区间**数值相同**（如正态均值）但**含义不同**。这是两个学派之所以既能和平共存、又在哲学上对立的原因。',
      },
      {
        title: 'HPD 区间：最短的可信区间',
        body: '**最高后验密度区间**（Highest Posterior Density, HPD）：在所有满足后验概率 $\\geq1-\\alpha$ 的区间中，HPD 区间是**最短的**。数学定义：$C_{HPD}=\\{\\theta:\\pi(\\theta\\mid\\mathbf{x})\\geq h\\}$，其中 $h$ 选取使得 $P(\\theta\\in C_{HPD}\\mid\\mathbf{x})=1-\\alpha$。HPD 区间的特点：(1) 对对称单峰分布（如正态后验），HPD 区间 $=$ 等尾可信区间；(2) 对偏斜分布（Beta、Gamma 后验），HPD 区间比等尾区间更短，但形状不对称；(3) 对多峰分布，HPD 区间可能是不连续的多个区间（每个区间对应一个峰）。HPD 区间是所有同覆盖率区间中最精确的，计算上通常需要数值方法（如 PyMC3 库）。',
        tip: '等尾区间：取分位数，计算简单；HPD 区间：最短区间，更精确但需数值方法。对称单峰后验（正态）两者相同，优先用等尾区间；偏斜后验用 HPD 更优。',
      },
      {
        title: '大样本性质：Bernstein-von Mises 定理',
        body: '**Bernstein-von Mises 定理**（B-vM 定理）：在正则条件下，当 $n\\to\\infty$ 时，无论先验如何（合理的正规先验），后验分布收敛到以 MLE 为均值、以 $1/(nI(\\theta_0))$ 为方差的正态分布：$\\pi(\\theta\\mid\\mathbf{x})\\to\\mathcal{N}(\\hat{\\theta}_{MLE},\\;[nI(\\hat{\\theta}_{MLE})]^{-1})$。含义：大样本时，数据"淹没"先验，贝叶斯和频率派结论一致。推论：大样本时，贝叶斯可信区间与频率置信区间数值相同（都是 $\\hat{\\theta}_{MLE}\\pm z_{\\alpha/2}/\\sqrt{nI(\\hat{\\theta}_{MLE})}$）。小样本时：先验起关键作用，贝叶斯和频率派可能给出很不同的结论；此时先验的选择至关重要。',
        formula: '\\pi(\\theta\\mid\\mathbf{x})\\xrightarrow{n\\to\\infty}\\mathcal{N}\\!\\left(\\hat{\\theta}_{MLE},\\;\\frac{1}{nI(\\hat{\\theta}_{MLE})}\\right)',
        tip: 'B-vM 定理是"频率-贝叶斯大和解"：大样本时两派数值趋同，哲学争论只在小样本时有实际意义。工程实践中，大样本用 MLE/置信区间（简单），小样本用贝叶斯/可信区间（需先验但更稳健）。',
      },
      {
        title: '当后验无解析解时：MCMC 与变分推断',
        body: '非共轭情形下，后验 $\\pi(\\theta\\mid\\mathbf{x})$ 无解析表达式，需近似方法。(1) **马尔可夫链蒙特卡洛（MCMC）**：通过构造以后验为平稳分布的马尔可夫链来采样。常用方法：Metropolis-Hastings（提议+接受/拒绝）、吉布斯采样（条件后验轮流采样）、Hamiltonian Monte Carlo（梯度驱动，Stan / PyMC 默认）。优点：样本渐近精确；缺点：计算慢，收敛性难以判断。(2) **变分推断（VI）**：用参数化分布 $q_\\phi(\\theta)$ 近似真实后验，最小化 KL 散度，等价于最大化证据下界（ELBO）：$\\text{ELBO}(\\phi)=E_{q_\\phi}[\\log p(\\mathbf{x}\\mid\\theta)]-D_{KL}(q_\\phi(\\theta)\\|\\pi(\\theta))$。优点：确定性优化，比 MCMC 快；缺点：近似精度依赖 $q$ 族的表达能力（均场近似可能低估后验方差）。VAE（变分自编码器）是变分推断在深度生成模型中的应用。',
        formula: '\\text{ELBO}(\\phi)=E_{q_\\phi}[\\log p(\\mathbf{x}\\mid\\theta)]-D_{KL}(q_\\phi(\\theta)\\,\\|\\,\\pi(\\theta))',
        tip: 'ELBO = "期望对数似然" $-$ "KL 散度"。最大化 ELBO 同时做两件事：(1) 让近似后验 $q$ 解释数据（最大化期望似然）；(2) 让 $q$ 接近先验 $\\pi$（最小化 KL 散度）。两者的平衡决定了后验的形状。',
      },
      {
        title: '可信区间与置信区间的完整对比',
        body: '频率置信区间 vs 贝叶斯可信区间——含义：置信区间"重复实验中 95% 覆盖固定 $\\theta$"，可信区间"给定数据，$\\theta$ 以 95% 后验概率在区间内"；参数性质：置信区间中 $\\theta$ 是固定常数，可信区间中 $\\theta$ 是随机变量；先验依赖：置信区间无先验，可信区间需先验；直觉性：置信区间反直觉，可信区间直觉友好；数值：无信息先验下（正态模型）两者数值相同。关键结论：可信区间的含义更直观，频率置信区间是"重复实验的保证"而非"当前结果的概率"。无信息先验下两者数值相同，但语义不同——不能互换陈述方式。',
        reveal: {
          q: 'Beta$(31,71)$ 后验（网站点击率，均匀先验 $+$ 100 次展示 30 次点击）。(1) 后验均值；(2) 95% 等尾可信区间（用分位数符号）；(3) "点击率以 95% 的概率落在该区间内"这句话正确吗？',
          a: '(1) 后验均值 $=31/(31+71)=31/102\\approx0.304$。(2) 95% 等尾可信区间 $=[Q_{0.025}(\\mathrm{Beta}(31,71)),\\;Q_{0.975}(\\mathrm{Beta}(31,71))]$，数值约 $[0.214,0.401]$。(3) 正确！贝叶斯可信区间允许说"参数以 95% 后验概率落在区间内"——因为在贝叶斯框架中参数 $\\theta$ 是随机变量，后验分布是给定数据后 $\\theta$ 的条件分布，$P(\\theta\\in[0.214,0.401]\\mid\\mathbf{x})=95\\%$ 是合法的概率陈述。这与频率置信区间的语义截然不同。',
        },
      },
      {
        title: '贝叶斯方法的适用场景与局限',
        body: '贝叶斯方法的优势：(1) 小样本时先验提供正则化，比 MLE 更稳健；(2) 可信区间语义直觉，结果易于解释；(3) 自然整合专家知识（通过先验）；(4) 序贯更新（在线学习）；(5) 不确定性量化（给出完整后验，不只是点估计）。贝叶斯方法的局限：(1) 先验选择的主观性（需做敏感性分析）；(2) 计算复杂（非共轭情形需 MCMC 或 VI）；(3) 非共轭模型的高维后验难以处理；(4) B-vM 定理在模型不正确时可能失效（先验和模型都错时后验不可靠）。现代实践：小样本 $+$ 先验信息丰富 $\\to$ 贝叶斯；大样本 $+$ 无强先验 $\\to$ 频率/MLE；深度学习 $\\to$ MAP（权重衰减）或贝叶斯神经网络（不确定性量化）。',
        tip: '先验敏感性分析是贝叶斯实践的必要步骤：用不同先验（弱先验、中等先验、强先验）重新计算后验，若结论稳健（不随先验变化），则结论可信；若结论敏感，说明数据不够充分，需更多数据或更严谨的先验选择。',
      },
    ],
    questions: [
      {
        type: 'choice',
        prompt: '以下关于贝叶斯可信区间的说法，哪个是正确的？',
        options: [
          '可信区间说"参数以 $1-\\alpha$ 概率落在区间内"，频率置信区间含义相同',
          '可信区间和置信区间的含义不同，但在无信息先验（正态模型）下数值相同',
          '可信区间只适用于小样本，大样本应用频率置信区间',
          '可信区间中"概率"是频率学派的概率，即"重复实验中的频率"',
        ],
        answer: 1,
        explain: '可信区间（贝叶斯）：$P(\\theta\\in[l,u]\\mid\\mathbf{x})=1-\\alpha$，参数是随机变量，直接说"后验概率"——含义直观。频率置信区间：$P_\\theta(L\\leq\\theta\\leq U)=1-\\alpha$，参数是常数，$1-\\alpha$ 是区间覆盖参数的频率——含义反直觉。无信息先验下（如正态均值），两者数值相同（都是 $\\bar{x}\\pm z_{\\alpha/2}\\sigma/\\sqrt{n}$），但含义截然不同，不能互换陈述。',
      },
      {
        type: 'judge',
        prompt: 'HPD 区间（最高后验密度区间）对对称单峰后验分布（如正态后验）与等尾可信区间完全相同，这个说法正确吗？',
        answer: true,
        explain: '正确。对对称单峰分布（如正态分布），分布的最高密度区域正好是围绕众数（均值）对称的区间，其中等尾区间（取 $\\alpha/2$ 和 $1-\\alpha/2$ 分位数）恰好也是最短区间（满足 HPD 定义）。两者完全重合。偏斜分布（Beta、Gamma）时，HPD 区间与等尾区间不同：HPD 更短（最优），但形状不对称，计算需数值方法。',
      },
      {
        type: 'choice',
        prompt: 'Bernstein-von Mises 定理说，大样本时后验分布收敛到以 $\\hat{\\theta}_{MLE}$ 为中心的正态。这意味着：',
        options: [
          '大样本时先验完全不重要，任何先验都给出相同结论',
          '大样本时贝叶斯可信区间和频率置信区间数值趋于相同',
          '贝叶斯方法只适用于小样本',
          '大样本时后验均值 $=$ MLE（精确相等，不是渐近）',
        ],
        answer: 1,
        explain: 'B-vM 定理的主要推论：大样本时，后验 $\\approx\\mathcal{N}(\\hat{\\theta}_{MLE},1/(nI(\\hat{\\theta}_{MLE})))$，贝叶斯 95% 可信区间趋近于 $\\hat{\\theta}_{MLE}\\pm1.96/\\sqrt{nI(\\hat{\\theta}_{MLE})}$，与频率 95% 置信区间数值相同。(A) 不完全准确——大样本时先验影响减弱但并非"完全不重要"（先验需合理，B-vM 定理有正则条件）；(D) 大样本时后验均值渐近趋于 MLE，不是精确相等。',
      },
      {
        type: 'input',
        prompt: '变分推断（Variational Inference）的目标是最大化 ELBO $=E_{q}[\\log p(\\mathbf{x}\\mid\\theta)]-D_{KL}(q(\\theta)\\|\\pi(\\theta))$。ELBO 中的 $D_{KL}$ 项（KL 散度）起什么作用？（填"正则化"或"归一化"）',
        accept: ['正则化', 'regularization', '正则'],
        explain: 'ELBO 中的 $D_{KL}(q\\|\\pi)$ 项起**正则化**作用：惩罚近似后验 $q$ 偏离先验 $\\pi$ 的程度。期望对数似然项鼓励 $q$ 解释数据（最大化），而 $D_{KL}$ 项阻止 $q$ 完全塌缩到数据（保持对先验的"尊重"）。两者的平衡决定了后验：数据项对应 MLE，$D_{KL}$ 项对应贝叶斯正则化（先验约束）。VAE 的重参数化技巧正是为了使 $D_{KL}$ 项可微，从而用梯度下降优化 ELBO。',
      },
      {
        type: 'choice',
        prompt: '以下哪种情形最适合使用贝叶斯方法（而非频率派 MLE）？',
        options: [
          '$n=10000$ 样本，无任何先验信息，估计总体均值',
          '$n=10$ 样本，有历史数据表明参数约在某范围内，估计次品率',
          '$n=1000$ 样本，总体分布正态，$\\sigma^2$ 已知，构造 $\\mu$ 的置信区间',
          '$n=500$ 样本，估计两组均值差，使用 $t$ 检验',
        ],
        answer: 1,
        explain: '贝叶斯方法最适合：小样本 $+$ 有先验信息。选项 (B)：$n=10$（小样本，MLE 不稳定），有历史数据（可以构造信息先验），贝叶斯通过先验正则化给出更合理的估计。大样本时（A、C、D），先验影响小，频率派方法（MLE、$t$ 检验）计算更简单、结果相近，无需引入先验的主观性。',
      },
      {
        type: 'match',
        prompt: '将贝叶斯方法的组成部分与对应描述配对：',
        left: ['后验均值（MMSE）', 'MAP 估计', 'HPD 区间', 'MCMC 采样'],
        right: [
          '非共轭后验无解析解时，构造马尔可夫链从后验中采样',
          '最小均方误差损失下的最优贝叶斯点估计',
          '最高后验密度区域，是所有同覆盖率区间中最短的',
          '后验众数，等价于正则化 MLE（高斯先验对应 L2）',
        ],
        answer: [1, 3, 2, 0],
        explain: '后验均值（MMSE）：$E[\\theta\\mid\\mathbf{x}]$，平方损失下最优，也称 MMSE 估计；MAP：后验众数 $\\arg\\max\\pi(\\theta\\mid\\mathbf{x})$，等价于高斯先验 MAP $=$ L2 正则化 MLE；HPD 区间：所有后验概率 $\\geq h$ 的 $\\theta$ 组成的集合，是最短的满足覆盖要求的区间；MCMC：马尔可夫链蒙特卡洛，非共轭后验的标准数值方法，通过随机游走从后验中采样。',
      },
      {
        type: 'judge',
        prompt: '贝叶斯可信区间和频率置信区间在任何情形下（包括小样本、非正态总体）数值都相同，只是含义不同，这个说法正确吗？',
        answer: false,
        explain: '错误。两者数值只在特定情形下相同（正态模型 $+$ 无信息先验）。一般情形下两者数值不同，甚至差异显著。例：二项比例的贝叶斯可信区间（Beta 后验分位数）和频率置信区间（Wald 区间）数值不同，小样本或极端比例时差异更大。正态均值的特殊性（自然共轭结构）使得无信息先验下两者数值恰好相同，这是"幸运的巧合"而非普遍规律。',
      },
      {
        type: 'choice',
        prompt: '变分推断的主要优势相比 MCMC 是：',
        options: [
          '变分推断给出精确的后验分布，MCMC 只是近似',
          '变分推断计算更快（确定性优化），MCMC 需要大量样本且收敛慢',
          '变分推断适用于任何先验，MCMC 只适用于共轭先验',
          '变分推断不需要先验分布，MCMC 需要先验',
        ],
        answer: 1,
        explain: '变分推断：将后验近似问题转化为**确定性优化**（最大化 ELBO），用梯度下降等优化方法，速度快（比 MCMC 快几个数量级）；MCMC：通过**随机采样**从后验中生成样本，渐近精确但收敛慢、需要大量样本。变分推断的代价是近似精度（取决于近似分布族的选择），通常低估后验方差（均场近似的常见缺陷）。两者都需要先验，两者都适用于非共轭模型。',
      },
    ],
  },
]
