export const LESSONS = [
  {
    id: 't24-a',
    title: '信息量、香农熵与联合/条件熵',
    subtitle: '为什么用 $-\\log p$ 度量信息、熵的直觉与计算、链式法则推导',
    intro: [
      {
        title: '引入：为什么越罕见的事件越有信息量？',
        body: '掷一枚均匀硬币，你得到了"正面"——这告诉你什么？答案是 1 比特的信息。而如果有人告诉你彩票号码（$p \\approx 10^{-7}$），你获得的信息量远大于此。香农把这一直觉精确化：事件 $A$ 的**自信息**（Self-Information）定义为 $I(A) = -\\log P(A)$。它满足三条公理：(1) 确定事件（$P(A)=1$）信息量为零；(2) 概率越小信息量越大；(3) 独立事件可加 $I(A \\cap B) = I(A)+I(B)$。在这三条约束下 $-\\log p$ 是唯一的选择。底数为 2 时单位是**比特**（bit），底数为 $e$ 时单位是**奈特**（nat，深度学习常用）。',
        tip: '独立可加性：$-\\log(p_1 p_2) = -\\log p_1 - \\log p_2$，这正是对数函数的核心性质，也是选 $\\log$ 而非其他单调函数的数学依据。',
      },
      {
        title: '香农熵：平均不确定性',
        body: '单个事件的信息量 $-\\log p(x)$ 是随机的。将它对随机变量 $X$ 取期望，就得到**香农熵**（Shannon Entropy）：$H(X) = \\mathbb{E}[-\\log p(X)] = -\\sum_x p(x)\\log p(x)$，表示对 $X$ 的**平均不确定性**。约定 $0\\log 0 = 0$（极限值）。直觉：熵越大，分布越"分散"，预测越难。均匀分布时熵最大（最不可预测），确定分布时熵最小（完全可预测）。以 $n$ 元均匀分布为例：$H(X) = -n \\cdot \\frac{1}{n}\\log\\frac{1}{n} = \\log n$。',
        formula: 'H(X) = -\\sum_{x} p(x)\\log p(x) = \\mathbb{E}[-\\log p(X)]',
        tip: '最大熵原理：对取 $n$ 个值的离散变量，$H(X) \\leq \\log n$，等号当且仅当 $X$ 服从均匀分布。直观证明：$D_{\\mathrm{KL}}(P \\| U) = \\log n - H(P) \\geq 0$，故 $H(P) \\leq \\log n$。',
      },
      {
        title: '伯努利分布的熵：双峰曲线',
        body: '设 $X \\sim \\text{Bernoulli}(p)$，$P(X=1)=p$，$P(X=0)=1-p$。代入定义：$H_b(p) = -p\\log p - (1-p)\\log(1-p)$，称为**二元熵函数**。具体计算三个关键点：$p=0$ 时 $H_b=0$（必然不发生）；$p=1$ 时 $H_b=0$（必然发生）；$p=0.5$ 时 $H_b = \\log 2$，取最大值（以 2 为底等于 1 比特，以 $e$ 为底约 $0.693$ 奈特）。这是"越均匀越不确定"的最简单体现：抛一枚公平硬币的结果最难预测。',
        formula: 'H_b(p) = -p\\log p - (1-p)\\log(1-p)',
        reveal: {
          q: '设 $X$ 的分布为 $p(1)=1/2,\\ p(2)=1/4,\\ p(3)=1/8,\\ p(4)=1/8$，用以 2 为底计算 $H(X)$。',
          a: '$H(X) = \\frac{1}{2}\\cdot 1 + \\frac{1}{4}\\cdot 2 + \\frac{1}{8}\\cdot 3 + \\frac{1}{8}\\cdot 3 = 0.5+0.5+0.375+0.375 = 1.75$ 比特。注意 $\\log_2 4 = 2 > 1.75$，因为分布不均匀，$p(1)=1/2$ 较集中，不确定性低于均匀分布。',
        },
      },
      {
        title: '联合熵与条件熵',
        body: '**联合熵** $H(X,Y) = -\\sum_{x,y} p(x,y)\\log p(x,y)$ 是二元系统 $(X,Y)$ 的总不确定性。**条件熵** $H(Y \\mid X)$ 是"已知 $X$ 后 $Y$ 的剩余不确定性"：$H(Y \\mid X) = \\sum_x p(x) H(Y \\mid X=x) = -\\sum_{x,y} p(x,y)\\log p(y \\mid x)$。两个关键不等式：(1) $H(Y \\mid X) \\leq H(Y)$——已知信息不增加不确定性（等号当 $X,Y$ 独立）；(2) $H(Y \\mid X) \\geq 0$（离散情形，非负）。直觉类比：知道今天有乌云，"明天下雨"的不确定性必然不大于完全不知情时。',
        formula: 'H(Y \\mid X) = -\\sum_{x,y} p(x,y)\\log p(y \\mid x) \\leq H(Y)',
        tip: '条件熵的平均性质：$H(Y \\mid X) = \\sum_x p(x) H(Y \\mid X=x)$ 是对每个 $x$ 条件下 $Y$ 的熵的**加权平均**，权重为 $p(x)$，而非对某一固定 $X=x$ 的熵。',
      },
      {
        title: '链式法则推导：从乘法公式到熵的分解',
        body: '**定理（熵的链式法则）**：$H(X,Y) = H(X) + H(Y \\mid X)$。推导：利用概率乘法公式 $p(x,y) = p(x)\\cdot p(y \\mid x)$，代入对数：$\\log p(x,y) = \\log p(x) + \\log p(y \\mid x)$，对联合分布取期望：$-\\mathbb{E}[\\log p(X,Y)] = -\\mathbb{E}[\\log p(X)] - \\mathbb{E}[\\log p(Y \\mid X)]$，左边是 $H(X,Y)$，右边分别是 $H(X)$ 和 $H(Y \\mid X)$，故等式成立。推广：多变量链式法则 $H(X_1,\\ldots,X_n) = \\sum_{i=1}^n H(X_i \\mid X_1,\\ldots,X_{i-1})$。',
        formula: 'H(X,Y) = H(X) + H(Y \\mid X) = H(Y) + H(X \\mid Y)',
        steps: [
          '写出联合分布的对数：$\\log p(x,y) = \\log p(x) + \\log p(y \\mid x)$',
          '两边乘以 $-p(x,y)$ 并对所有 $(x,y)$ 求和',
          '左边化为 $H(X,Y)$，右边第一项对 $y$ 求和得 $H(X)$，第二项为 $H(Y \\mid X)$',
        ],
      },
      {
        title: '易错点：微分熵可以为负；底数影响数值不影响结论',
        body: '**易错点 1**：连续型随机变量的**微分熵** $h(X) = -\\int f(x)\\log f(x)\\,dx$ 可以为负。例如 $X \\sim U(0, 0.1)$，密度 $f(x)=10$，$h(X) = -\\int_0^{0.1} 10 \\ln 10\\,dx = -\\ln 10 \\approx -2.3$ 奈特。原因：PDF 可超过 1，使 $-f\\log f$ 为负。**离散熵 $H(X) \\geq 0$ 恒成立**，两者不可混用。**易错点 2**：以 2 为底的比特和以 $e$ 为底的奈特差常数因子 $\\ln 2 \\approx 0.693$，比较不等式方向、等号条件时与底数无关，但数值不可混用。**易错点 3**：$H(Y \\mid X) \\leq H(Y)$ 成立，但条件互信息与无条件互信息的大小没有固定方向——知道第三变量可能使两个变量"更相关"（辛普森悖论类情形）。',
        tip: '记忆口诀：离散熵非负，条件减不确定性，均匀分布熵最大，确定分布熵为零。微分熵是例外，可为负，只能比差，不能比绝对值。',
      },
    ],
    questions: [
      {
        type: 'judge',
        prompt: '连续型随机变量的微分熵 $h(X)$ 一定满足 $h(X) \\geq 0$，这个说法正确吗？',
        answer: false,
        explain: '错误。连续型的微分熵可以为负，例如 $X \\sim U(0, 0.1)$，微分熵 $h(X) = \\ln 0.1 \\approx -2.3 < 0$。只有离散型香农熵 $H(X) \\geq 0$ 恒成立（因为 $-\\sum p \\log p \\geq 0$，所有项均非负）。微分熵依赖尺度，PDF 超过 1 时 $-f\\log f < 0$。',
      },
      {
        type: 'choice',
        prompt: '在以 2 为底的条件下，掷一枚均匀六面骰子出现某一面（概率 $1/6$）的自信息最接近哪个值（比特）？',
        options: ['1.0', '2.0', '2.58', '3.0'],
        answer: 2,
        explain: '$I = -\\log_2(1/6) = \\log_2 6 = \\log_2 2 + \\log_2 3 \\approx 1 + 1.585 = 2.585 \\approx 2.58$ 比特。概率 $1/6$ 比硬币的 $1/2$ 更小，信息量更大：$2.58 > 1$ 比特。',
      },
      {
        type: 'input',
        prompt: '设 $X$ 的分布为 $p(1)=1/2,\\ p(2)=1/4,\\ p(3)=1/8,\\ p(4)=1/8$，以 2 为底计算 $H(X)$（单位比特，保留两位小数）。',
        accept: ['1.75', '7/4'],
        explain: '$H(X) = -(\\frac{1}{2}\\log_2\\frac{1}{2} + \\frac{1}{4}\\log_2\\frac{1}{4} + \\frac{1}{8}\\log_2\\frac{1}{8} + \\frac{1}{8}\\log_2\\frac{1}{8}) = \\frac{1}{2}\\cdot1+\\frac{1}{4}\\cdot2+\\frac{1}{8}\\cdot3+\\frac{1}{8}\\cdot3 = 0.5+0.5+0.375+0.375 = 1.75$ 比特。',
      },
      {
        type: 'choice',
        prompt: '对取 $n$ 个值的离散随机变量 $X$，其香农熵 $H(X)$ 满足：',
        options: ['$H(X) \\leq \\log n$，当 $X$ 服从均匀分布时取等', '$H(X) \\geq \\log n$，当 $X$ 为确定量时取等', '$H(X) = \\log n$ 恒成立', '$H(X) \\leq 0$'],
        answer: 0,
        explain: '正确答案是 $H(X) \\leq \\log n$，等号当且仅当 $X$ 服从均匀分布。证明：$D_{\\mathrm{KL}}(P \\| U) = \\log n - H(P) \\geq 0$，故 $H(P) \\leq \\log n$。当 $X$ 为确定量时 $H(X) = 0$（最小，非最大）。',
      },
      {
        type: 'judge',
        prompt: '熵的链式法则 $H(X,Y) = H(X) + H(Y \\mid X)$ 中，当 $X,Y$ 独立时，$H(Y \\mid X) = H(Y)$，该结论正确吗？',
        answer: true,
        explain: '正确。当 $X,Y$ 独立时，$p(y \\mid x) = p(y)$，所以 $H(Y \\mid X) = -\\sum_{x,y} p(x,y)\\log p(y \\mid x) = -\\sum_{x,y} p(x)p(y)\\log p(y) = -\\sum_y p(y)\\log p(y) = H(Y)$。链式法则在此情形退化为 $H(X,Y) = H(X)+H(Y)$，正好反映独立变量的熵可加性。',
      },
      {
        type: 'match',
        prompt: '将左列的信息论量与右列的定义/性质正确配对：',
        left: ['自信息 $I(A)$', '香农熵 $H(X)$', '条件熵 $H(Y \\mid X)$', '联合熵 $H(X,Y)$'],
        right: [
          '已知 $X$ 后 $Y$ 的平均剩余不确定性，满足 $\\leq H(Y)$',
          '单个事件不确定性的度量，概率越小值越大',
          '$(X,Y)$ 整体系统的不确定性，满足 $\\geq \\max\\{H(X),H(Y)\\}$',
          '$X$ 平均不确定性，等于 $\\mathbb{E}[-\\log p(X)]$',
        ],
        explain: '自信息 $I(A) = -\\log P(A)$ 度量单个事件，概率越小值越大（配第2条）；香农熵是期望信息量（配第4条）；条件熵是已知 $X$ 后 $Y$ 的剩余不确定性（配第1条）；联合熵是整体不确定性（配第3条）。正确配对顺序：[1, 3, 0, 2]（从第0行开始索引）。',
      },
      {
        type: 'input',
        prompt: '均匀分布 $X$ 在 $\\{1,2,3,4,5,6,7,8\\}$ 上取值，以 2 为底计算 $H(X)$（单位比特，填整数）。',
        accept: ['3'],
        explain: '$H(X) = \\log_2 8 = 3$ 比特。均匀分布 $p(x)=1/8$，$H(X) = -8\\cdot\\frac{1}{8}\\log_2\\frac{1}{8} = \\log_2 8 = 3$。这也是对 8 个等可能结果编码所需的最优平均码长。',
      },
    ],
  },
  {
    id: 't24-b',
    title: '互信息、KL 散度与交叉熵',
    subtitle: '互信息的四种等价表达、KL 散度非对称性与非负性证明、交叉熵损失的理论基础',
    intro: [
      {
        title: '互信息：两个变量共享多少信息？',
        body: '**互信息**（Mutual Information）$I(X;Y)$ 度量"知道 $Y$ 后 $X$ 的不确定性减少了多少"。直观图像：用韦恩图，$H(X)$ 和 $H(Y)$ 各是一个圆，$H(X,Y)$ 是两圆的并集，$I(X;Y)$ 是两圆的交集（重叠部分），$H(X \\mid Y)$ 和 $H(Y \\mid X)$ 分别是两圆各自独有的部分。核心等式：$H(X,Y) = H(X \\mid Y) + I(X;Y) + H(Y \\mid X)$。互信息的两个核心性质：(1) **对称性** $I(X;Y) = I(Y;X)$；(2) **非负性** $I(X;Y) \\geq 0$，等号当且仅当 $X,Y$ 独立。',
        tip: '互信息 $I(X;Y) = 0$ 等价于 $X$ 与 $Y$ 独立，这为检验独立性提供了信息论视角。相关系数 $\\rho$ 只能检测线性相关，互信息能检测任意统计依赖。',
      },
      {
        title: '互信息的四种等价表达',
        body: '互信息有四种等价表达，每种揭示不同直觉：(1) $I(X;Y) = H(X) - H(X \\mid Y)$（知道 $Y$ 后 $X$ 减少的不确定性）；(2) $I(X;Y) = H(Y) - H(Y \\mid X)$（对称地，知道 $X$ 后 $Y$ 减少的不确定性）；(3) $I(X;Y) = H(X)+H(Y)-H(X,Y)$（两变量信息之和减去联合信息）；(4) $I(X;Y) = D_{\\mathrm{KL}}(p(x,y) \\| p(x)p(y))$（联合分布与独立时的差异）。推导 (1)：$I(X;Y) = \\sum_{x,y}p(x,y)\\log\\frac{p(x,y)}{p(x)p(y)} = \\sum_{x,y}p(x,y)\\log\\frac{p(x \\mid y)}{p(x)} = H(X) - H(X \\mid Y)$。',
        formula: 'I(X;Y) = H(X)-H(X \\mid Y) = H(Y)-H(Y \\mid X) = H(X)+H(Y)-H(X,Y)',
        steps: [
          '从定义 $I(X;Y) = \\sum_{x,y}p(x,y)\\log\\frac{p(x,y)}{p(x)p(y)}$ 出发',
          '拆分对数：$\\log p(x,y) - \\log p(x) - \\log p(y)$',
          '取期望：$-H(X,Y) + H(X) + H(Y) = I(X;Y)$，得到第 (3) 式',
          '对 (3) 式用链式法则 $H(X,Y) = H(X)+H(Y \\mid X)$，代入得 (2) 式',
        ],
      },
      {
        title: 'KL 散度：两个分布之间的差异',
        body: '**KL 散度**（Kullback-Leibler Divergence，相对熵）度量分布 $P$ 相对于 $Q$ 的差异：$D_{\\mathrm{KL}}(P \\| Q) = \\sum_x p(x)\\log\\frac{p(x)}{q(x)} = \\mathbb{E}_{x \\sim P}[\\log\\frac{p(x)}{q(x)}]$。两个核心性质：(1) **非负性** $D_{\\mathrm{KL}}(P \\| Q) \\geq 0$，等号当且仅当 $P=Q$；(2) **不对称性** $D_{\\mathrm{KL}}(P \\| Q) \\neq D_{\\mathrm{KL}}(Q \\| P)$，所以 KL 散度不是"距离"（不满足对称性和三角不等式）。约定：$q(x)=0$ 而 $p(x)>0$ 时该项为 $+\\infty$；$p(x)=0$ 时该项为 0。实践中若模型分布 $Q$ 在 $P$ 有支撑处赋零概率，KL 散度爆炸。',
        formula: 'D_{\\mathrm{KL}}(P \\| Q) = \\sum_x p(x)\\log\\frac{p(x)}{q(x)} \\geq 0',
        tip: 'KL 非对称的直觉：前向 KL $D_{\\mathrm{KL}}(P\\|Q)$ 要求 $Q$ 覆盖 $P$ 的所有支撑（否则无穷大），倾向于"均值寻求"；反向 KL $D_{\\mathrm{KL}}(Q\\|P)$ 允许 $Q$ 忽略 $P$ 的某些模式，倾向于"模式寻求"。变分推断中两种方向的选择有本质不同的后果。',
      },
      {
        title: 'KL 非负性的严格证明',
        body: '**定理（KL 非负性）**：$D_{\\mathrm{KL}}(P \\| Q) \\geq 0$，等号当且仅当 $P=Q$。**证明**（利用 $\\ln t \\leq t-1$，即 $-\\ln t \\geq 1-t$）：令 $t = q(x)/p(x)$，则 $-\\log\\frac{q(x)}{p(x)} \\geq 1 - \\frac{q(x)}{p(x)}$。两边乘以 $p(x)$ 并对所有 $x$ 求和：$D_{\\mathrm{KL}}(P \\| Q) = \\sum_x p(x)(-\\log\\frac{q(x)}{p(x)}) \\geq \\sum_x p(x)(1-\\frac{q(x)}{p(x)}) = 1-1=0$。等号成立要求 $q(x)/p(x) = 1$ 对所有 $p(x)>0$ 的 $x$ 成立，即 $P=Q$。这个证明本质上来自 **Jensen 不等式**：$-\\log$ 是严格凸函数，$D_{\\mathrm{KL}} = \\mathbb{E}[-\\log\\frac{q}{p}] \\geq -\\log\\mathbb{E}[\\frac{q}{p}] = -\\log 1 = 0$。',
        formula: 'D_{\\mathrm{KL}}(P \\| Q) \\geq \\sum_x p(x)\\left(1-\\frac{q(x)}{p(x)}\\right) = 1-\\sum_x q(x) = 0',
      },
      {
        title: '交叉熵：机器学习损失的信息论基础',
        body: '**交叉熵**（Cross-Entropy）定义为：$H(P,Q) = -\\sum_x p(x)\\log q(x)$，表示"用分布 $Q$ 的编码来压缩真实分布 $P$ 的数据的平均码长"。核心关系式：$H(P,Q) = H(P) + D_{\\mathrm{KL}}(P \\| Q)$。由 KL 非负性：$H(P,Q) \\geq H(P)$，等号当 $P=Q$。**机器学习的关键推论**：训练时 $P$（真实数据分布）固定，$H(P)$ 是常数，所以最小化交叉熵等价于最小化 KL 散度——这就是交叉熵损失的理论根源！分类任务中真实标签是 one-hot 分布，$H(P)=0$，故交叉熵直接等于 KL 散度，损失简化为 $-\\log \\hat{p}_k$（只需真实类别的预测概率）。',
        formula: 'H(P,Q) = H(P) + D_{\\mathrm{KL}}(P \\| Q) \\geq H(P)',
        reveal: {
          q: '为什么说"最小化交叉熵损失等价于最小化 KL 散度"？$H(P)$ 在训练中扮演什么角色？',
          a: '训练中真实分布 $P$（数据标签）固定，$H(P)$ 是关于 $P$ 的常数，对模型参数 $\\theta$ 的优化没有影响。所以 $\\min_\\theta H(P,Q_\\theta) = \\min_\\theta [H(P) + D_{\\mathrm{KL}}(P\\|Q_\\theta)] = \\min_\\theta D_{\\mathrm{KL}}(P\\|Q_\\theta)$。这意味着交叉熵损失就是在驱使模型分布 $Q_\\theta$ 接近真实分布 $P$。',
        },
      },
      {
        title: '互信息与 KL 散度的统一：数据处理不等式',
        body: '**互信息与 KL 的联系**：$I(X;Y) = D_{\\mathrm{KL}}(p(x,y) \\| p(x)p(y))$，即联合分布与"假设独立时"乘积分布之间的 KL 散度。由 KL 非负性直接给出 $I(X;Y) \\geq 0$，等号当 $X,Y$ 独立。**数据处理不等式（DPI）**：若 $X \\to Y \\to Z$ 构成马尔可夫链，则 $I(X;Z) \\leq I(X;Y)$。含义：对数据的任何处理（特征提取、压缩）不能增加关于原始量的互信息——信息只能丢失，不能凭空创造。深度学习启示：神经网络每一层对标签 $Y$ 的互信息 $I(h_i;Y)$ 不超过原始输入 $I(X;Y)$，为信息瓶颈理论提供基础。',
        formula: 'I(X;Y) = D_{\\mathrm{KL}}(p(x,y) \\| p(x)p(y)) \\geq 0',
        tip: '数据处理不等式说明：好的模型不是创造信息，而是高效提取和保留与任务相关的信息，同时压缩无关的冗余信息——这正是信息瓶颈理论的核心主张。',
      },
    ],
    questions: [
      {
        type: 'judge',
        prompt: 'KL 散度 $D_{\\mathrm{KL}}(P \\| Q)$ 满足对称性，即 $D_{\\mathrm{KL}}(P \\| Q) = D_{\\mathrm{KL}}(Q \\| P)$，这个说法正确吗？',
        answer: false,
        explain: '错误。KL 散度是不对称的，一般情况下 $D_{\\mathrm{KL}}(P \\| Q) \\neq D_{\\mathrm{KL}}(Q \\| P)$，因此它不是"距离"（度量）。特例：两个同方差正态分布（均值不同）时 $D_{\\mathrm{KL}}(P\\|Q) = D_{\\mathrm{KL}}(Q\\|P) = \\mu^2/2$，但这是特殊情形。前向 KL 和反向 KL 在变分推断中有本质不同的优化行为。',
      },
      {
        type: 'choice',
        prompt: '已知联合分布 $H(X,Y) = 1.811$ 比特，$H(X) = H(Y) = 1$ 比特，则互信息 $I(X;Y)$ 约为多少比特？',
        options: ['0.189', '2.811', '0.811', '1.0'],
        answer: 0,
        explain: '$I(X;Y) = H(X)+H(Y)-H(X,Y) = 1+1-1.811 = 0.189$ 比特。由 $I(X;Y) > 0$ 可知 $X,Y$ 不独立（若独立则 $I=0$）。也可用 $H(Y \\mid X) = H(X,Y)-H(X) = 0.811$ 比特，$I(X;Y) = H(Y)-H(Y \\mid X) = 1-0.811 = 0.189$ 比特，两种算法结果一致。',
      },
      {
        type: 'judge',
        prompt: '互信息 $I(X;Y)$ 一定满足 $I(X;Y) \\leq \\min\\{H(X), H(Y)\\}$，这个说法正确吗？',
        answer: true,
        explain: '正确。由 $I(X;Y) = H(X) - H(X \\mid Y)$ 以及 $H(X \\mid Y) \\geq 0$，得 $I(X;Y) \\leq H(X)$。同理 $I(X;Y) \\leq H(Y)$。因此 $I(X;Y) \\leq \\min\\{H(X),H(Y)\\}$。等号当 $Y$ 完全决定 $X$ 时（或反之），$H(X \\mid Y) = 0$，$I(X;Y) = H(X)$。',
      },
      {
        type: 'input',
        prompt: '设 $P$ 为均匀分布（4 个等可能结果），$U$ 也是均匀分布，计算 $D_{\\mathrm{KL}}(P \\| U)$（任意底数均可，填具体数值）。',
        accept: ['0', '0.0'],
        explain: '当 $P = U$ 时，$D_{\\mathrm{KL}}(P \\| U) = \\sum_x p(x)\\log\\frac{p(x)}{u(x)} = \\sum_x p(x)\\log 1 = 0$。KL 散度等于零当且仅当两个分布完全相同（$P = Q$ 几乎处处成立）。',
      },
      {
        type: 'choice',
        prompt: '在机器学习分类任务中，真实标签为 one-hot 分布 $P$（类别 $k$ 的概率为 1），模型预测概率为 $\\hat{p}$，则交叉熵损失 $H(P,\\hat{p})$ 等于：',
        options: ['$-\\log \\hat{p}_k$', '$-\\sum_j \\hat{p}_j \\log \\hat{p}_j$', '$\\log \\hat{p}_k$', '$H(P) + D_{\\mathrm{KL}}(\\hat{p} \\| P)$'],
        answer: 0,
        explain: '因为 $P$ 是 one-hot 分布，只有类别 $k$ 的概率为 1，其余为 0。代入定义：$H(P,\\hat{p}) = -\\sum_j p_j \\log \\hat{p}_j = -1 \\cdot \\log \\hat{p}_k = -\\log \\hat{p}_k$。这也说明：分类交叉熵损失只需关注真实类别 $k$ 的预测概率，其他类别的预测在此损失中不直接体现（但通过 softmax 归一化间接影响）。',
      },
      {
        type: 'match',
        prompt: '将左列量与右列说明正确配对：',
        left: ['$I(X;Y) = 0$', '$D_{\\mathrm{KL}}(P \\| Q) = 0$', '$H(P,Q) = H(P)$', '$H(Y \\mid X) = H(Y)$'],
        right: [
          '$X$ 与 $Y$ 统计独立',
          '$P$ 与 $Q$ 完全相同',
          '$X$ 与 $Y$ 独立（已知 $X$ 不减少 $Y$ 的不确定性）',
          '用最优编码 $Q=P$ 压缩 $P$，无损失',
        ],
        explain: '$I(X;Y)=0$ 等价于 $X,Y$ 独立（配第0条）；$D_{\\mathrm{KL}}=0$ 等价于 $P=Q$（配第1条）；$H(P,Q)=H(P)$ 说明 $D_{\\mathrm{KL}}(P\\|Q)=0$ 即 $Q=P$，用最优编码（配第3条）；$H(Y \\mid X) = H(Y)$ 说明 $X$ 与 $Y$ 独立，已知 $X$ 无法减少 $Y$ 的不确定性（配第2条）。正确配对：[0,1,3,2]。',
      },
      {
        type: 'judge',
        prompt: '数据处理不等式表明：若 $X \\to Y \\to Z$ 是马尔可夫链，则 $I(X;Z) \\leq I(X;Y)$，即对数据的处理不能增加互信息。这个说法正确吗？',
        answer: true,
        explain: '正确。数据处理不等式（DPI）是信息论的重要定理：马尔可夫链 $X \\to Y \\to Z$ 中，$Z$ 在给定 $Y$ 时与 $X$ 条件独立，因此 $I(X;Z) \\leq I(X;Y)$。直观理解：$Z$ 是从 $Y$ 进一步处理得到的，只能保留或丢失 $Y$ 中关于 $X$ 的信息，不能凭空创造。这为神经网络中"信息只能被提取/压缩，不能被创造"提供了理论保证。',
      },
    ],
  },
  {
    id: 't24-c',
    title: 'Jensen 不等式、信息论不等式与深度学习应用',
    subtitle: '凸性、Jensen 不等式推导 KL 非负、最大熵原理、VAE 的 ELBO 框架',
    intro: [
      {
        title: 'Jensen 不等式：凸函数的核心工具',
        body: '**Jensen 不等式**：若 $f$ 是凸函数（二阶导数 $\\geq 0$），则 $f(\\mathbb{E}[X]) \\leq \\mathbb{E}[f(X)]$；若 $f$ 是凹函数，不等号反向。严格凸函数等号成立当且仅当 $X$ 为常数。核心例子：$-\\log x$ 是严格凸函数（$\\frac{d^2}{dx^2}(-\\log x) = 1/x^2 > 0$）。这导出 KL 非负：$D_{\\mathrm{KL}}(P \\| Q) = \\mathbb{E}_P[-\\log \\frac{q(X)}{p(X)}] \\geq -\\log \\mathbb{E}_P[\\frac{q(X)}{p(X)}] = -\\log 1 = 0$（其中 $\\mathbb{E}_P[q(X)/p(X)] = \\sum_x p(x) \\cdot q(x)/p(x) = \\sum_x q(x) = 1$）。Jensen 不等式是信息论、统计物理、最优化的共同基石。',
        formula: 'f(\\mathbb{E}[X]) \\leq \\mathbb{E}[f(X)] \\quad (f\\text{ 凸})',
        tip: '记忆法：凸函数的图像"向上弯"，均值的函数值"低于"函数值的均值。$\\log$ 是凹函数，所以 $\\log(\\mathbb{E}[X]) \\geq \\mathbb{E}[\\log X]$（对数均值不等式）。',
      },
      {
        title: '最大熵原理：为什么高斯分布如此普遍',
        body: '**最大熵原理**给出了约束条件下最"无信息"（不确定性最大）的分布形式。三个经典结论：(1) 无约束离散情形：$n$ 个值的变量中，均匀分布熵最大 $H = \\log n$；(2) 均值约束 $\\mathbb{E}[X] = \\mu$，$X \\geq 0$：最大熵分布是**指数分布** $\\text{Exp}(1/\\mu)$；(3) 均值和方差约束 $\\mathbb{E}[X]=\\mu$，$\\text{Var}(X)=\\sigma^2$：最大熵分布是**正态分布** $\\mathcal{N}(\\mu,\\sigma^2)$。这解释了为什么正态分布在自然界和机器学习中如此普遍——在给定均值和方差的约束下，它是"最大不确定性"的分布，意味着没有额外假设。',
        formula: 'H(P) \\leq \\log n \\quad(\\text{离散}),\\qquad h(X) \\leq \\tfrac{1}{2}\\ln(2\\pi e\\sigma^2)',
        tip: '最大熵的贝叶斯解读：若只知道均值和方差，用正态分布作为先验是最"客观"的选择（不额外引入未知约束以外的信息）。这是贝叶斯推断中选择先验的重要原则。',
      },
      {
        title: '交叉熵损失与 VAE 的 ELBO：信息论统一视角',
        body: '**交叉熵损失（分类）**：最小化 $H(P,\\hat{p}) = -\\sum_k p_k \\log \\hat{p}_k$，等价于最小化 $D_{\\mathrm{KL}}(P \\| \\hat{p})$（$H(P)$ 固定）。**VAE 的 ELBO** 用信息论语言写成：$\\mathcal{L}_{\\mathrm{ELBO}} = \\mathbb{E}_{q_\\phi}[\\log p_\\theta(\\mathbf{x} \\mid \\mathbf{z})] - D_{\\mathrm{KL}}(q_\\phi(\\mathbf{z} \\mid \\mathbf{x}) \\| p(\\mathbf{z}))$，其中第一项是重建损失（解码器品质），第二项是正则化（近似后验接近先验）。Jensen 不等式保证 $\\log p(\\mathbf{x}) \\geq \\mathcal{L}_{\\mathrm{ELBO}}$（$\\log$ 是凹函数，$\\log\\mathbb{E} \\geq \\mathbb{E}[\\log]$），所以 ELBO 是对数似然的**可优化下界**。三大信息论工具（KL 散度、交叉熵、Jensen 不等式）在此统一。',
        formula: '\\log p(\\mathbf{x}) \\geq \\mathbb{E}_{q_\\phi}[\\log p_\\theta(\\mathbf{x}\\mid\\mathbf{z})] - D_{\\mathrm{KL}}(q_\\phi(\\mathbf{z}\\mid\\mathbf{x})\\|p(\\mathbf{z})) = \\mathcal{L}_{\\mathrm{ELBO}}',
        steps: [
          '引入辅助分布 $q_\\phi(\\mathbf{z}\\mid\\mathbf{x})$，将 $\\log p(\\mathbf{x})$ 乘以 $q_\\phi/q_\\phi$，化为期望形式',
          '对 $\\log$ 应用 Jensen 不等式（$\\log$ 是凹函数，$\\log\\mathbb{E} \\geq \\mathbb{E}[\\log]$）',
          '展开对数比值，分离重建项和 KL 正则化项',
        ],
      },
      {
        title: '熵的次可加性与条件独立性',
        body: '**次可加性定理**：$H(X_1,\\ldots,X_n) \\leq \\sum_{i=1}^n H(X_i)$，等号当且仅当 $X_1,\\ldots,X_n$ 相互独立。证明：由链式法则 $H(X_1,\\ldots,X_n) = \\sum_i H(X_i \\mid X_1,\\ldots,X_{i-1}) \\leq \\sum_i H(X_i)$（每一步用条件不增熵）。物理含义：多个变量联合的不确定性不超过各自不确定性之和——相关性"共享"了信息，减少了总不确定性。**条件独立检验**：$X \\perp Y \\mid Z$ 等价于 $I(X;Y\\mid Z) = 0$（条件互信息为零），等价于 $H(X,Y \\mid Z) = H(X \\mid Z) + H(Y \\mid Z)$（给定 $Z$ 后条件熵可加）。',
        formula: 'H(X_1,\\ldots,X_n) \\leq \\sum_{i=1}^n H(X_i)',
      },
      {
        title: '易错点汇总：信息论高频错误',
        body: '**错误 1**：$H(P,Q) = H(Q,P)$——交叉熵**不对称**！$H(P,Q) = -\\sum p\\log q$，$H(Q,P) = -\\sum q\\log p$，一般不等。而熵 $H(P) = H(P,P)$ 是对称的特例。**错误 2**：$I(X;Y\\mid Z)$ 可以大于或小于 $I(X;Y)$——条件互信息的"大小比较"没有固定方向。虽然 $I(X;Y\\mid Z) \\geq 0$ 始终成立，但 $I(X;Y\\mid Z)$ 与 $I(X;Y)$ 的大小依赖具体分布（辛普森悖论类情形可让条件互信息大于无条件互信息）。**错误 3**：VAE 的 ELBO 等号成立条件是 $q_\\phi(\\mathbf{z}\\mid\\mathbf{x}) = p(\\mathbf{z}\\mid\\mathbf{x})$，即近似后验等于真实后验；**错误 4**：混淆 $\\log_2$（比特）和 $\\ln$（奈特）单位，做题时必须统一底数。',
        tip: '信息论五大口诀：(1) KL 非负不对称；(2) 交叉熵 $=$ 熵 $+$ KL；(3) 互信息 $=$ 熵差 $=$ KL（联合 vs 乘积）；(4) 条件减不确定，次可加；(5) Jensen 给下界，$\\log$ 凹给 ELBO。',
      },
      {
        title: 'Fano 不等式与信道容量简介',
        body: '**Fano 不等式** 给出分类错误率的信息论下界：设 $\\hat{X} = g(Y)$ 是基于观测 $Y$ 对 $X$ 的估计，错误概率 $P_e = P(\\hat{X} \\neq X)$，则 $H(X \\mid Y) \\leq H_b(P_e) + P_e \\log(|\\mathcal{X}|-1)$。含义：条件熵越高，分类越难，错误率越高——提供了贝叶斯最优分类器错误率的理论下界。**信道容量** $C = \\max_{p(x)} I(X;Y)$，是信道在最优输入分布下能可靠传输的最大信息率。香农信道编码定理：只要传输速率 $R < C$，存在编码方案使错误概率任意小。这些结论（Fano 不等式、信道容量定理）是香农信息论的核心，也是现代通信系统的理论基础。',
        formula: 'C = \\max_{p(x)} I(X;Y)',
        reveal: {
          q: '若二元对称信道（每个比特以概率 $\\epsilon$ 翻转）的噪声概率 $\\epsilon = 0$ 时，信道容量 $C$ 是多少比特？',
          a: '$\\epsilon=0$ 时信道无噪声，$C = 1 - H_b(0) = 1 - 0 = 1$ 比特（以 2 为底），表示每个符号可靠地传递 1 比特。当 $\\epsilon=0.5$ 时 $C = 0$（纯噪声，完全无信息传递）。',
        },
      },
    ],
    questions: [
      {
        type: 'choice',
        prompt: 'Jensen 不等式 $f(\\mathbb{E}[X]) \\leq \\mathbb{E}[f(X)]$ 中，$f$ 需满足什么条件？',
        options: ['$f$ 是凸函数', '$f$ 是凹函数', '$f$ 是单调函数', '$f$ 是线性函数'],
        answer: 0,
        explain: 'Jensen 不等式：$f$ 是凸函数时 $f(\\mathbb{E}[X]) \\leq \\mathbb{E}[f(X)]$。$f$ 是凹函数时不等号方向反转：$f(\\mathbb{E}[X]) \\geq \\mathbb{E}[f(X)]$。$-\\log$ 是凸函数，用于推导 KL 非负；$\\log$ 是凹函数，用于推导 ELBO 下界（$\\log \\mathbb{E} \\geq \\mathbb{E}[\\log]$）。',
      },
      {
        type: 'judge',
        prompt: '在给定均值和方差 $\\sigma^2$ 的约束下，正态分布 $\\mathcal{N}(\\mu,\\sigma^2)$ 的微分熵最大，这体现了最大熵原理，说法正确吗？',
        answer: true,
        explain: '正确。最大熵原理：在均值 $\\mathbb{E}[X]=\\mu$ 和方差 $\\text{Var}(X)=\\sigma^2$ 两个约束下，微分熵最大的分布是正态分布 $\\mathcal{N}(\\mu,\\sigma^2)$，最大微分熵为 $h = \\frac{1}{2}\\ln(2\\pi e\\sigma^2)$。这解释了正态分布的普遍性：它是在已知均值和方差条件下最"无假设"的分布选择。',
      },
      {
        type: 'choice',
        prompt: 'VAE 的 ELBO 中 $D_{\\mathrm{KL}}(q_\\phi(\\mathbf{z}\\mid\\mathbf{x}) \\| p(\\mathbf{z}))$ 这一项的作用是？',
        options: [
          '正则化项，驱使近似后验接近先验，防止潜在空间过度分散',
          '重建损失，衡量解码器重建质量',
          '最大化对数似然的下界',
          '衡量真实后验与近似后验的差异（这项无法计算）',
        ],
        answer: 0,
        explain: 'ELBO $= \\mathbb{E}[\\log p_\\theta(\\mathbf{x}\\mid\\mathbf{z})] - D_{\\mathrm{KL}}(q_\\phi(\\mathbf{z}\\mid\\mathbf{x})\\|p(\\mathbf{z}))$。第一项是重建损失，第二项 KL 是正则化项，惩罚近似后验偏离先验 $p(\\mathbf{z})=\\mathcal{N}(0,I)$，防止编码器将不同输入映射到完全不重叠的潜在区域。ELBO 整体是对数似然的下界，最大化 ELBO 即最大化对数似然的可优化近似。',
      },
      {
        type: 'input',
        prompt: '设 $X_1, X_2$ 独立，$H(X_1) = 2$ 比特，$H(X_2) = 3$ 比特，则 $H(X_1, X_2)$ 等于多少比特？',
        accept: ['5', '5.0'],
        explain: '当 $X_1, X_2$ 独立时，联合熵等于边缘熵之和：$H(X_1,X_2) = H(X_1)+H(X_2) = 2+3 = 5$ 比特。这是次可加性取等号的条件（独立）。若存在相关性，则 $H(X_1,X_2) < H(X_1)+H(X_2) = 5$。',
      },
      {
        type: 'judge',
        prompt: '条件互信息 $I(X;Y \\mid Z)$ 可以大于无条件互信息 $I(X;Y)$，因为条件可能"揭示"更多依赖关系（如碰撞结构激活）。这个说法正确吗？',
        answer: true,
        explain: '正确。$I(X;Y \\mid Z) \\geq 0$ 始终成立，但 $I(X;Y \\mid Z)$ 与 $I(X;Y)$ 大小没有固定方向：(1) 若 $Z$ 是 $X$ 和 $Y$ 的公共因（分叉），条件 $Z$ 后 $X,Y$ 变得独立，$I(X;Y\\mid Z) < I(X;Y)$；(2) 若 $Z$ 是 $X,Y$ 的共同效应（碰撞），观测 $Z$ 后 $X,Y$ 变得相关，$I(X;Y\\mid Z) > I(X;Y)$。碰撞结构是最反直觉的例子（解释消去效应）。',
      },
      {
        type: 'match',
        prompt: '将下列深度学习概念与其信息论对应正确配对：',
        left: ['分类交叉熵损失', 'VAE 的重建项', 'VAE 的 KL 正则项', '数据处理不等式对神经网络的启示'],
        right: [
          '衡量解码器输出与输入的重建质量：$\\mathbb{E}[\\log p_\\theta(\\mathbf{x}\\mid\\mathbf{z})]$',
          '最小化 $D_{\\mathrm{KL}}(P\\|Q_\\theta)$，驱使预测分布接近真实分布',
          '驱使近似后验 $q_\\phi$ 接近先验 $p(\\mathbf{z})$，防止过拟合',
          '每层不能比原始输入含有更多关于标签的互信息',
        ],
        explain: '分类交叉熵 $H(P,Q_\\theta) = H(P)+D_{\\mathrm{KL}}(P\\|Q_\\theta)$，最小化等于最小化 KL（配第1条）；VAE 重建项（配第0条）；VAE KL 正则（配第2条）；DPI 对深度学习的启示（配第3条）。正确顺序：[1,0,2,3]。',
      },
      {
        type: 'choice',
        prompt: '关于 Fano 不等式 $H(X \\mid Y) \\leq H_b(P_e) + P_e \\log(|\\mathcal{X}|-1)$，下列说法正确的是：',
        options: [
          '条件熵越高，分类错误率的下界越高，分类越难',
          '条件熵越高，分类错误率越低，因为不确定性大',
          '该不等式给出错误率的上界',
          '$P_e = 0$ 时等式自动成立',
        ],
        answer: 0,
        explain: 'Fano 不等式 $H(X\\mid Y) \\leq H_b(P_e)+P_e\\log(|\\mathcal{X}|-1)$ 给出错误率 $P_e$ 的**下界**（由条件熵导出）：条件熵 $H(X\\mid Y)$ 越大，表示观测 $Y$ 对 $X$ 的信息越少，右侧也需越大，即 $P_e$ 越大。所以条件熵越高，分类越困难，最优分类器错误率越高。这提供了理论上任何分类方法的性能极限。',
      },
    ],
  },
]
