export const LESSONS = [
  {
    id: 't26-a',
    title: '贝叶斯网络：DAG 因子分解与 d-分离',
    subtitle: '从参数爆炸到线性压缩、三种连接结构、d-分离三规则、解释消去效应',
    intro: [
      {
        title: '引入：参数爆炸与图结构的魔法',
        body: '设医学诊断系统包含 $n=30$ 个二值症状变量 $X_1,\\ldots,X_{30}$（发热、咳嗽、胸痛……）。完整描述联合分布需要 $2^{30} - 1 \\approx 10^9$ 个独立参数——超过 10 亿，完全无法存储和学习。若引入贝叶斯网络，每个节点最多有 3 个父节点，每张条件概率表至多需要 $2^3 = 8$ 个参数，30 个节点总共只需 $30 \\times 8 = 240$ 个参数。**从 10 亿降到 240，不是近似，而是精确分解**——依靠图结构编码的**条件独立性假设**。这是概率图模型的核心魔法：图结构 $=$ 条件独立性假设 $=$ 参数量从指数级降到线性级。',
        tip: '贝叶斯网络的两个核心要素：(1) 图结构（DAG）编码哪些变量之间有依赖；(2) 条件概率表（CPT）量化每个变量在给定父节点时的分布。图结构决定参数量，CPT 决定具体分布。',
      },
      {
        title: 'DAG 因子分解：联合分布的精确表达',
        body: '**贝叶斯网络**是一个有向无环图（DAG），每个节点 $X_i$ 对应一个随机变量，有向边 $X_j \\to X_i$ 表示 $X_j$ 是 $X_i$ 的"父节点"。**联合分布的因子分解**：$P(X_1,\\ldots,X_n) = \\prod_{i=1}^n P(X_i \\mid \\text{Pa}(X_i))$，其中 $\\text{Pa}(X_i)$ 是 $X_i$ 的父节点集合（若无父节点则为先验 $P(X_i)$）。例：学生模型，节点为课程难度 $D$、学生智力 $I$、成绩 $G$、推荐信 $L$、SAT 分数 $S$，图结构 $D \\to G \\leftarrow I \\to S$，$G \\to L$，联合分布为 $P(D,I,G,L,S) = P(D) \\cdot P(I) \\cdot P(G \\mid D,I) \\cdot P(L \\mid G) \\cdot P(S \\mid I)$。',
        formula: 'P(X_1,\\ldots,X_n) = \\prod_{i=1}^n P(X_i \\mid \\text{Pa}(X_i))',
        steps: [
          '画出 DAG，确定每个节点的父节点集合 $\\text{Pa}(X_i)$',
          '对每个节点写出条件概率因子 $P(X_i \\mid \\text{Pa}(X_i))$',
          '将所有因子相乘得到联合分布',
          '统计参数量：$\\sum_i (|\\text{Pa}(X_i)| \\text{ 个父节点} \\Rightarrow 2^{|\\text{Pa}(X_i)|}$ 个参数）',
        ],
      },
      {
        title: '三种基本连接结构',
        body: '理解贝叶斯网络中信息"流动"的规律，关键是三种基本连接模式：(1) **链式结构** $X \\to Y \\to Z$：给定 $Y$ 后，$X$ 与 $Z$ 条件独立，$Y$ "中断"了 $X$ 到 $Z$ 的信息传递；(2) **分叉结构** $X \\leftarrow Y \\to Z$：$Y$ 是公共原因，给定 $Y$ 后 $X,Z$ 条件独立（观测公因"解释"了两者的相关性）；(3) **碰撞结构** $X \\to Y \\leftarrow Z$：未观测 $Y$ 时 $X,Z$ 独立，观测 $Y$（或其后代）后 $X,Z$ 变得**相关**（"解释消去"效应）。碰撞结构的行为与链/分叉完全相反，是最容易记错的地方。口诀：链/分叉——观测中间节点则阻断；碰撞——观测中间节点则畅通。',
        tip: '解释消去（explaining away）的直觉：草坪是湿的（观测了碰撞结果）。下雨和洒水器都是可能的原因，但如果你知道了洒水器确实开着，那么下雨的可能性就降低了——两个原因"互相解释/竞争"，产生了负相关。',
      },
      {
        title: 'd-分离：条件独立性的通用判定算法',
        body: '**d-分离**（directional separation）判断给定观测集合 $\\mathbf{Z}$ 时，两个节点 $X,Y$ 是否条件独立。**路径被阻断的充分条件**（路径上某中间节点 $m$）：(1) 链式 $\\cdots \\to m \\to \\cdots$ 或分叉 $\\cdots \\leftarrow m \\to \\cdots$：$m \\in \\mathbf{Z}$ 时路径**阻断**；(2) 碰撞 $\\cdots \\to m \\leftarrow \\cdots$：$m \\notin \\mathbf{Z}$ 且 $m$ 的后代 $\\notin \\mathbf{Z}$ 时路径**阻断**。若所有连接 $X,Y$ 的路径均被阻断，则 $X$ 与 $Y$ 被 $\\mathbf{Z}$ d-分离，意味着 $X \\perp Y \\mid \\mathbf{Z}$（在满足该图结构的所有分布中成立）。',
        formula: '\\text{链/分叉：}m \\in \\mathbf{Z} \\Rightarrow \\text{阻断}\\qquad \\text{碰撞：}m,\\text{后代} \\notin \\mathbf{Z} \\Rightarrow \\text{阻断}',
        steps: [
          '枚举所有连接 $X$ 与 $Y$ 的无向路径',
          '对每条路径，逐个中间节点判断是否阻断',
          '若某节点满足阻断条件，该路径被阻断',
          '所有路径均阻断 → $X \\perp Y \\mid \\mathbf{Z}$ 成立；否则不成立',
        ],
      },
      {
        title: 'd-分离完整例题：季节-雨-洒水器-湿草',
        body: '**DAG**：$S \\to R$，$S \\to C$，$R \\to W$，$C \\to W$（$S$=季节，$R$=下雨，$C$=洒水器，$W$=湿草）。问：$R \\perp C \\mid W$ 是否成立？**路径枚举**：路径 1：$R \\leftarrow S \\to C$；路径 2：$R \\to W \\leftarrow C$。**路径 1**：$S$ 是分叉节点，$S \\notin \\mathbf{Z} = \\{W\\}$，路径**畅通**。**路径 2**：$W$ 是碰撞节点，$W \\in \\mathbf{Z}$，路径**畅通**（观测碰撞节点，解释消去激活）。两条路径均畅通，$R \\perp C \\mid W$ **不成立**——观测到草湿，使得下雨和洒水器产生相关性（两者互相"竞争"解释湿草）。',
        reveal: {
          q: '接上题，判断 $R \\perp C \\mid S$（观测季节，不观测草湿）是否成立。',
          a: '路径 1：$R \\leftarrow S \\to C$，$S$ 是分叉节点，$S \\in \\{S\\}$，路径**阻断**。路径 2：$R \\to W \\leftarrow C$，$W$ 是碰撞节点，$W \\notin \\{S\\}$ 且 $W$ 的后代 $\\notin \\{S\\}$，路径**阻断**。所有路径阻断，$R \\perp C \\mid S$ **成立**——已知季节后，下雨和洒水器独立。',
        },
      },
      {
        title: '易错点：d-分离碰撞方向与道德化代价',
        body: '**易错点 1（最高频）**：碰撞节点的阻断方向与链/分叉完全相反——未观测碰撞节点才阻断，观测后反而畅通。记忆法："雨水-草湿-洒水器"：未知草湿时雨水和洒水器独立；得知草湿后两者产生关联（都在"争夺"解释权）。**易错点 2**：条件独立性 $X \\perp Y \\mid Z$ 只在满足图结构的所有分布中成立，不保证对所有分布成立——图模型的条件独立性是该模型类的**结构性假设**，而非通用数学定理。**易错点 3（道德化损失）**：将 DAG 转为 MRF 时需"道德化"（连接共同父节点），会引入原 DAG 中不存在的边，损失某些条件独立性。道德图编码的独立性集合是原 DAG 的**子集**，不能再转回 DAG。',
        tip: '快速记忆 d-分离三规则的表格：链（$\\to m \\to$）——在Z中阻断，不在Z中畅通；分叉（$\\leftarrow m \\to$）——在Z中阻断，不在Z中畅通；碰撞（$\\to m \\leftarrow$）——在Z中畅通（及后代），不在Z中阻断。',
      },
    ],
    questions: [
      {
        type: 'judge',
        prompt: '在碰撞结构 $X \\to Y \\leftarrow Z$ 中，当观测集 $\\mathbf{Z} = \\emptyset$（未观测任何变量）时，$X$ 与 $Z$ 独立。这个说法正确吗？',
        answer: true,
        explain: '正确。碰撞结构中，当碰撞节点 $Y$ 未被观测（且其后代也未被观测）时，该路径被阻断，$X$ 与 $Z$ 独立。注意：这与链/分叉结构相反——链/分叉中，中间节点未观测时路径是畅通的。碰撞结构的"未观测则阻断"是 d-分离中最反直觉的规则。',
      },
      {
        type: 'choice',
        prompt: '给定 DAG：$A \\to B$，$A \\to C$，$B \\to D$，$C \\to D$。下列哪个条件独立性由 d-分离成立？',
        options: [
          '$B \\perp C \\mid A$（分叉结构，$A$ 被观测）',
          '$B \\perp C$（未观测任何变量）',
          '$A \\perp D$（未观测任何变量）',
          '$B \\perp C \\mid D$（碰撞节点 $D$ 被观测）',
        ],
        answer: 0,
        explain: '路径 $B \\leftarrow A \\to C$：$A$ 是分叉节点，$A \\in \\{A\\}$，路径阻断，$B \\perp C \\mid A$ **成立**。选项 (1)：未观测 $A$ 时路径 $B \\leftarrow A \\to C$ 畅通，$B$ 与 $C$ 不独立。选项 (2)：路径 $A \\to B \\to D$ 和 $A \\to C \\to D$，$A$ 和 $D$ 之间有畅通路径，不独立。选项 (3)：$D$ 是碰撞节点，$D \\in \\{D\\}$，路径 $B \\to D \\leftarrow C$ 畅通，加上 $B \\leftarrow A \\to C$ 也畅通，$B$ 与 $C$ 不独立。',
      },
      {
        type: 'input',
        prompt: '贝叶斯网络有 4 个二值变量 $A,B,C,D$，结构为 $A \\to B$，$A \\to C$，$B \\to D$，$C \\to D$。以因子分解计算参数数量（每个 CPT 只算独立参数，即减 1）：$P(A)$ 贡献 1 个，$P(B\\mid A)$ 贡献 2 个，$P(C\\mid A)$ 贡献 2 个，$P(D\\mid B,C)$ 贡献 4 个，总共多少个？',
        accept: ['9'],
        explain: '$P(A)$：1 个（$P(A=1)$，$P(A=0)=1-P(A=1)$）；$P(B\\mid A)$：$A$ 取 0 或 1 各一个参数，共 2 个；$P(C\\mid A)$：同理 2 个；$P(D\\mid B,C)$：$B,C$ 各取 0/1，共 4 种父节点组合，每种 1 个参数，共 4 个。总计 $1+2+2+4=9$ 个参数。无结构时需 $2^4-1=15$ 个，节省了 6 个。',
      },
      {
        type: 'judge',
        prompt: '在 DAG 中，若 $X$ 与 $Y$ 被 $\\mathbf{Z}$ d-分离，则在所有满足该图结构的概率分布中，$X \\perp Y \\mid \\mathbf{Z}$ 均成立。这个说法正确吗？',
        answer: true,
        explain: '正确。这是 d-分离的马尔可夫性质定理：若图 $G$ 中 $X$ 与 $Y$ 被 $\\mathbf{Z}$ d-分离，则在所有满足图 $G$ 因子分解的分布中，$X \\perp Y \\mid \\mathbf{Z}$ 成立。注意：反过来不一定——某些分布可能有额外的独立性（图未编码的），但 d-分离给出的是从图结构可保证的最小独立性集合。',
      },
      {
        type: 'match',
        prompt: '将三种基本连接结构与其 d-分离行为正确配对：',
        left: ['链式 $X \\to Y \\to Z$', '分叉 $X \\leftarrow Y \\to Z$', '碰撞 $X \\to Y \\leftarrow Z$（未观测 $Y$）', '碰撞 $X \\to Y \\leftarrow Z$（已观测 $Y$）'],
        right: [
          '路径畅通，$X$ 与 $Z$ 不独立（解释消去激活）',
          '路径阻断，$X$ 与 $Z$ 独立（碰撞节点天然阻断）',
          '观测 $Y$ 则路径阻断，$X \\perp Z \\mid Y$',
          '观测 $Y$ 则路径阻断，$X \\perp Z \\mid Y$',
        ],
        explain: '链式：观测 $Y$ 阻断，未观测时畅通；分叉：同链式，观测公因 $Y$ 后 $X,Z$ 独立；碰撞未观测：路径阻断，独立；碰撞已观测：路径畅通，不独立（解释消去）。注意链和分叉的阻断条件相同（均为观测中间节点），碰撞方向相反（不观测才阻断）。正确配对：链[2]，分叉[2]，碰撞未观测[1]，碰撞已观测[0]。',
      },
      {
        type: 'choice',
        prompt: '以下关于贝叶斯网络（DAG）和马尔可夫随机场（MRF）的说法，哪个是正确的？',
        options: [
          'DAG 转化为 MRF（道德化）可能会损失某些条件独立性',
          'MRF 的表达能力严格强于 DAG',
          'DAG 和 MRF 可以精确表示完全相同的独立性集合',
          'MRF 可以无损地转换回 DAG',
        ],
        answer: 0,
        explain: '正确答案是 (0)。道德化（将 DAG 转为 MRF）需要连接共同父节点（"婚姻化"），可能引入原 DAG 中不存在的边，从而失去某些条件独立性——道德图编码的独立性集合是原 DAG 的子集。两者表达能力不可比（各有优势），不能随意互换，且 MRF 无法无损转回 DAG。',
      },
      {
        type: 'judge',
        prompt: '在 DAG 中，"解释消去"（explaining away）效应指的是：在碰撞结构中，观测到共同效应 $Y$ 后，两个原因 $X$ 和 $Z$ 变得相关（一个原因的存在降低另一个原因的概率）。这个说法正确吗？',
        answer: true,
        explain: '正确。碰撞结构 $X \\to Y \\leftarrow Z$：未观测 $Y$ 时 $X,Z$ 独立；观测 $Y$ 后路径被激活，$X,Z$ 产生（负）相关。例如：草地湿了（$Y$=1），可能因为下雨（$X$）或洒水器（$Z$）。观测到草湿后，若进一步知道洒水器开着（$Z$=1），则"下雨"的概率降低——洒水器的出现"解释"了草湿，降低了对其他原因的需求。',
      },
    ],
  },
  {
    id: 't26-b',
    title: '马尔可夫随机场与 EM 算法',
    subtitle: '势函数与配分函数、Gibbs 分布、EM 算法单调性推导、GMM 软分配',
    intro: [
      {
        title: 'MRF：势函数与配分函数',
        body: '**马尔可夫随机场（MRF）**使用无向图表示变量间的对称依赖。**局部马尔可夫性质**：给定邻居节点集合 $\\mathcal{N}(X_i)$，$X_i$ 与所有非邻居条件独立。**Hammersley-Clifford 定理**：满足局部马尔可夫性质的正分布，可以表示为极大团（全连接子集）上势函数的乘积：$P(\\mathbf{X}) = \\frac{1}{Z}\\prod_{c \\in \\mathcal{C}} \\psi_c(\\mathbf{X}_c)$，其中 $\\psi_c > 0$ 是势函数，$Z = \\sum_{\\mathbf{X}}\\prod_c\\psi_c(\\mathbf{X}_c)$ 是**配分函数**。**Gibbs 分布**的能量函数形式：$P(\\mathbf{X}) = \\frac{1}{Z}\\exp(-E(\\mathbf{X}))$，$E(\\mathbf{X}) = \\sum_c E_c(\\mathbf{X}_c)$。$Z$ 是 MRF 推断的核心难点——精确计算需对所有状态求和，指数级复杂度，通常需要近似方法。',
        formula: 'P(\\mathbf{X}) = \\frac{1}{Z}\\prod_{c \\in \\mathcal{C}}\\psi_c(\\mathbf{X}_c),\\quad Z = \\sum_{\\mathbf{X}}\\prod_c\\psi_c(\\mathbf{X}_c)',
        tip: 'MRF 与 DAG 的关键区别：DAG 的联合分布自动归一化（条件概率乘积），无需配分函数；MRF 的势函数乘积不是概率，必须除以配分函数才能归一化。配分函数的难以计算是 MRF 最大的挑战。',
      },
      {
        title: 'MRF vs DAG：表达能力与互换代价',
        body: '**DAG 转 MRF（道德化）**：(1) 为每个节点的所有父节点两两相连（"婚姻化"）；(2) 将所有有向边替换为无向边。代价：可能引入原 DAG 中不存在的边，损失某些条件独立性——道德图编码的独立性集合是原 DAG 的**子集**。**两类图的各自优势**：DAG 适合有方向因果关系（因果推断、生成模型）；MRF 适合对称依赖（图像分割中的像素邻居、社交网络）。**表达能力的不完全性**：存在某些分布，既不能用 DAG 精确编码也不能用 MRF 精确编码；DAG 可编码某些 MRF 无法精确表示的独立性（反之亦然），两者表达能力不可比。**条件随机场（CRF）**：MRF 的判别式变体，直接建模 $P(\\mathbf{Y}\\mid\\mathbf{X})$，无需建模输入分布，适合序列标注。',
        formula: 'P(\\mathbf{Y} \\mid \\mathbf{X}) = \\frac{1}{Z(\\mathbf{X})}\\exp\\left(\\sum_c \\psi_c(\\mathbf{Y}_c, \\mathbf{X})\\right)',
        tip: 'CRF 与 MRF 的关键区别：MRF 建模联合分布 $P(\\mathbf{X})$，配分函数 $Z$ 是全局常数；CRF 建模条件分布 $P(\\mathbf{Y}\\mid\\mathbf{X})$，配分函数 $Z(\\mathbf{X})$ 依赖于观测，更容易训练（无需建模观测分布的复杂结构）。',
      },
      {
        title: 'EM 算法：隐变量模型的最大化下界',
        body: '**问题设定**：观测数据 $\\mathbf{x}$，隐变量 $\\mathbf{z}$，参数 $\\theta$，边缘似然 $\\log P(\\mathbf{x}\\mid\\theta) = \\log\\int P(\\mathbf{x},\\mathbf{z}\\mid\\theta)\\,d\\mathbf{z}$（积分无解析解）。**EM 的关键思想**：引入任意分布 $q(\\mathbf{z})$，利用 Jensen 不等式推导下界 $\\mathcal{L}(q,\\theta)$：$\\log P(\\mathbf{x}\\mid\\theta) \\geq \\mathcal{L}(q,\\theta) = \\mathbb{E}_{q}[\\log P(\\mathbf{x},\\mathbf{z}\\mid\\theta)] + H[q]$。等号成立当 $q(\\mathbf{z}) = P(\\mathbf{z}\\mid\\mathbf{x},\\theta)$（间隙 $= D_{\\mathrm{KL}}(q \\| P(\\mathbf{z}\\mid\\mathbf{x},\\theta)) = 0$）。**两步迭代**：E步令 $q^{(t+1)} = P(\\mathbf{z}\\mid\\mathbf{x},\\theta^{(t)})$（使下界变紧）；M步 $\\theta^{(t+1)} = \\arg\\max_\\theta \\mathcal{L}(q^{(t+1)},\\theta)$（提升下界）。',
        formula: '\\log P(\\mathbf{x}\\mid\\theta) = \\mathcal{L}(q,\\theta) + D_{\\mathrm{KL}}(q(\\mathbf{z})\\|P(\\mathbf{z}\\mid\\mathbf{x},\\theta)) \\geq \\mathcal{L}(q,\\theta)',
        steps: [
          '引入任意分布 $q(\\mathbf{z})$，将积分改写为 $q(\\mathbf{z}) \\cdot P(\\mathbf{x},\\mathbf{z})/q(\\mathbf{z})$ 的期望',
          '对 $\\log$ 应用 Jensen 不等式（$\\log$ 是凹函数），得到 ELBO 下界 $\\mathcal{L}(q,\\theta)$',
          'E步：令 $q = P(\\mathbf{z}\\mid\\mathbf{x},\\theta^{(t)})$，消除间隙，使下界等于对数似然',
          'M步：固定 $q$，最大化 $\\mathcal{L}(q,\\theta)$，等价于最大化完全数据期望对数似然',
        ],
      },
      {
        title: 'EM 单调性证明',
        body: '**定理**：EM 算法保证对数似然单调不减：$\\log P(\\mathbf{x}\\mid\\theta^{(t+1)}) \\geq \\log P(\\mathbf{x}\\mid\\theta^{(t)})$。**证明**：(1) E步结束后，$q^{(t)} = P(\\mathbf{z}\\mid\\mathbf{x},\\theta^{(t)})$，此时 $\\mathcal{L}(q^{(t)},\\theta^{(t)}) = \\log P(\\mathbf{x}\\mid\\theta^{(t)})$（间隙为零）；(2) M步：$\\theta^{(t+1)} = \\arg\\max_\\theta \\mathcal{L}(q^{(t)},\\theta)$，故 $\\mathcal{L}(q^{(t)},\\theta^{(t+1)}) \\geq \\mathcal{L}(q^{(t)},\\theta^{(t)}) = \\log P(\\mathbf{x}\\mid\\theta^{(t)})$；(3) 对任意 $q$，$\\log P(\\mathbf{x}\\mid\\theta^{(t+1)}) \\geq \\mathcal{L}(q^{(t)},\\theta^{(t+1)})$（Jensen）。联结三个不等式得证。**注意**：EM 只保证单调性，不保证收敛到全局最优（GMM 对初始化敏感，多次随机重启是标准实践）。',
        formula: '\\log P(\\mathbf{x}\\mid\\theta^{(t+1)}) \\geq \\mathcal{L}(q^{(t)},\\theta^{(t+1)}) \\geq \\mathcal{L}(q^{(t)},\\theta^{(t)}) = \\log P(\\mathbf{x}\\mid\\theta^{(t)})',
        tip: 'EM 算法的几何理解：E步让下界曲线 $\\mathcal{L}(q,\\theta)$ 在当前点"贴合"对数似然曲线（消除间隙）；M步沿贴合的下界曲线往更高的方向走。每一轮 EM 等于在下界曲线上进行一步提升，保证整体不下降。',
      },
      {
        title: 'GMM 的 EM 算法：软分配与加权更新',
        body: '**高斯混合模型（GMM）**：$P(\\mathbf{x}\\mid\\theta) = \\sum_{k=1}^K \\pi_k \\mathcal{N}(\\mathbf{x}\\mid\\boldsymbol{\\mu}_k,\\boldsymbol{\\Sigma}_k)$，隐变量 $z_i \\in \\{1,\\ldots,K\\}$ 表示数据点 $i$ 属于哪个分量。**E步（计算"责任" $r_{ik}$）**：$r_{ik} = P(z_i=k\\mid\\mathbf{x}_i,\\theta^{(t)}) = \\frac{\\pi_k^{(t)}\\mathcal{N}(\\mathbf{x}_i\\mid\\boldsymbol{\\mu}_k^{(t)},\\boldsymbol{\\Sigma}_k^{(t)})}{\\sum_j\\pi_j^{(t)}\\mathcal{N}(\\mathbf{x}_i\\mid\\boldsymbol{\\mu}_j^{(t)},\\boldsymbol{\\Sigma}_j^{(t)})}$（每个点对每个分量的软归属权重）。**M步（用加权样本更新参数）**：令 $N_k = \\sum_i r_{ik}$，$\\boldsymbol{\\mu}_k^{(t+1)} = \\frac{\\sum_i r_{ik}\\mathbf{x}_i}{N_k}$，$\\pi_k^{(t+1)} = N_k/N$。与 K-means 的区别：K-means 是"硬分配"（每点只属于一个簇），GMM 是"软分配"（每点以不同权重属于所有分量）。',
        formula: 'r_{ik} = \\frac{\\pi_k^{(t)}\\mathcal{N}(\\mathbf{x}_i\\mid\\boldsymbol{\\mu}_k^{(t)},\\boldsymbol{\\Sigma}_k^{(t)})}{\\sum_j\\pi_j^{(t)}\\mathcal{N}(\\mathbf{x}_i\\mid\\boldsymbol{\\mu}_j^{(t)},\\boldsymbol{\\Sigma}_j^{(t)})}',
        reveal: {
          q: '若所有数据点对所有分量的责任均匀（$r_{ik} = 1/K$ 对所有 $i,k$），M步后各分量均值 $\\boldsymbol{\\mu}_k^{(t+1)}$ 等于什么？这说明 GMM 的什么问题？',
          a: '$N_k = N/K$，$\\boldsymbol{\\mu}_k^{(t+1)} = \\frac{\\sum_i (1/K) \\mathbf{x}_i}{N/K} = \\frac{1}{N}\\sum_i \\mathbf{x}_i$（全局样本均值）。所有分量均值相等，这是退化解——模型无法分辨各分量。说明 GMM 对初始化极为敏感，需要用 K-means++ 使分量均值相互分离，避免初始退化。',
        },
      },
      {
        title: '变量消元与信念传播简介',
        body: '**变量消元（Variable Elimination）**：对未观测变量逐步积分/求和，核心是"分配律"减少重复计算。例如链 $A \\to B \\to C$，计算 $P(A \\mid C=c)$ 时，先算 $\\tau(B) = P(C=c \\mid B)$，再算 $\\sum_B P(B \\mid A)\\tau(B)$，避免对 $B$ 重复计算。**信念传播（Sum-Product）**：在因子图（变量节点与因子节点的二部图）上，变量节点 $x$ 和因子节点 $f$ 交替传递消息，等价于并行变量消元。树形因子图上精确收敛，复杂度 $O(nk^2)$（$n$ 为节点数，$k$ 为状态数）；有环图上"循环信念传播"是近似推断。**树宽（treewidth）**：变量消元复杂度为 $O(k^{w+1})$，$w$ 是树宽。树形图 $w=1$，一般图树宽可达 $\\Theta(n)$（NP-hard 计算），意味着精确推断指数级困难。',
        tip: '信念传播与神经网络的联系：图神经网络（GNN）的消息传递机制可以看作广义的信念传播——节点聚合邻居消息更新自身表示，与 Sum-Product 算法的结构完全对应。',
      },
    ],
    questions: [
      {
        type: 'judge',
        prompt: '马尔可夫随机场（MRF）的配分函数 $Z = \\sum_{\\mathbf{X}}\\prod_c\\psi_c(\\mathbf{X}_c)$ 在精确计算时复杂度是指数级的，这是 MRF 推断困难的根本原因。这个说法正确吗？',
        answer: true,
        explain: '正确。离散变量 MRF 的配分函数 $Z = \\sum_{\\mathbf{X}}\\prod_c\\psi_c(\\mathbf{X}_c)$ 需要对所有可能的变量赋值求和。若有 $n$ 个二值变量，则有 $2^n$ 个状态，精确计算 $Z$ 是 $O(2^n)$ 的指数级操作。这就是为什么 MRF 的精确推断通常不可行，需要使用 MCMC、变分推断等近似方法（或利用树形结构精确求解，复杂度 $O(nk^2)$）。',
      },
      {
        type: 'choice',
        prompt: 'EM 算法的 E 步（期望步）的作用是：',
        options: [
          '计算在当前参数 $\\theta^{(t)}$ 下隐变量的后验分布 $q(\\mathbf{z}) = P(\\mathbf{z}\\mid\\mathbf{x},\\theta^{(t)})$，使 ELBO 与对数似然相等',
          '最大化完全数据对数似然 $\\mathbb{E}_q[\\log P(\\mathbf{x},\\mathbf{z}\\mid\\theta)]$',
          '直接最大化边缘似然 $\\log P(\\mathbf{x}\\mid\\theta)$',
          '更新参数 $\\theta$，使 ELBO 提升',
        ],
        answer: 0,
        explain: 'E步的作用是：在当前参数 $\\theta^{(t)}$ 下计算隐变量的后验分布 $q^{(t+1)}(\\mathbf{z}) = P(\\mathbf{z}\\mid\\mathbf{x},\\theta^{(t)})$，这使得 $D_{\\mathrm{KL}}(q \\| P(\\mathbf{z}\\mid\\mathbf{x},\\theta^{(t)})) = 0$，间隙消除，ELBO 等于对数似然。M步才是最大化 $\\theta$。两步交替进行，保证对数似然单调不减。',
      },
      {
        type: 'judge',
        prompt: 'EM 算法保证对数似然 $\\log P(\\mathbf{x}\\mid\\theta)$ 在每次迭代后严格增大，因此必然收敛到全局最优。这个说法正确吗？',
        answer: false,
        explain: '错误。EM 算法保证的是**单调不减**（$\\geq$），而非严格增大——当 $\\theta^{(t)}$ 已在局部极值时，M步后 $\\theta^{(t+1)} = \\theta^{(t)}$，对数似然不变而非增大。更重要的是，EM 不保证收敛到**全局**最优——它可能收敛到局部极值或鞍点，对初始化敏感（GMM 的多个局部极值是典型例子）。实践中需要多次随机重启并取最优结果。',
      },
      {
        type: 'input',
        prompt: '一个 GMM 有 $K=3$ 个分量，$N=100$ 个数据点。E步计算责任后，$N_1 = \\sum_i r_{i1} = 40$，$N_2 = \\sum_i r_{i2} = 35$，$N_3 = \\sum_i r_{i3} = 25$。M步后 $\\pi_1^{(t+1)}$ 等于多少？',
        accept: ['0.4', '0.40'],
        explain: 'M步中混合系数更新为 $\\pi_k^{(t+1)} = N_k/N$。$\\pi_1^{(t+1)} = N_1/N = 40/100 = 0.4$。同理 $\\pi_2 = 0.35$，$\\pi_3 = 0.25$。三者之和 $= 0.4+0.35+0.25 = 1$，满足概率之和为 1 的约束。',
      },
      {
        type: 'choice',
        prompt: 'GMM 的 EM 算法与 K-means 算法的本质区别是什么？',
        options: [
          'GMM 是软分配（每点以概率权重归属所有分量），K-means 是硬分配（每点唯一归属最近中心）',
          'GMM 不需要指定分量数 $K$，K-means 需要',
          'K-means 比 GMM 更准确，因为它使用精确分配',
          'GMM 只适用于一维数据，K-means 适用于任意维度',
        ],
        answer: 0,
        explain: 'GMM（EM）中每个数据点以"责任"权重 $r_{ik}$ 软性地归属于每个分量（0 到 1 之间，和为 1），均值更新是加权平均。K-means 是 GMM 的硬分配极限（等方差，$\\sigma \\to 0$）——每点硬性归属距离最近的中心（责任为 0 或 1），均值更新是简单平均。两者都需要指定 $K$，都能处理高维数据。GMM 更灵活（可以不等方差），但计算代价更高。',
      },
      {
        type: 'match',
        prompt: '将下列推断/学习方法与其适用场景配对：',
        left: ['信念传播（Sum-Product）', '变分推断（均场近似）', 'EM 算法', 'Loopy Belief Propagation'],
        right: [
          '树形因子图上的精确推断，复杂度 $O(nk^2)$',
          '有环因子图的近似推断，不保证收敛',
          '含隐变量模型的参数估计，保证对数似然单调',
          '将后验推断转化为 ELBO 最大化问题，速度快但有近似误差',
        ],
        explain: '信念传播：树形图精确（配第0条）；变分推断：ELBO 最大化（配第3条）；EM 算法：隐变量模型参数估计（配第2条）；Loopy BP：有环图近似（配第1条）。正确顺序：[0,3,2,1]。',
      },
      {
        type: 'judge',
        prompt: '条件随机场（CRF）与马尔可夫随机场（MRF）的主要区别在于：CRF 直接建模条件分布 $P(\\mathbf{Y}\\mid\\mathbf{X})$，无需建模输入 $\\mathbf{X}$ 的分布，因此更适合序列标注等判别式任务。这个说法正确吗？',
        answer: true,
        explain: '正确。MRF 建模联合分布 $P(\\mathbf{X},\\mathbf{Y})$（或 $P(\\mathbf{X})$），需要对输入分布建模（生成式）；CRF 直接建模条件分布 $P(\\mathbf{Y}\\mid\\mathbf{X})$（判别式），配分函数 $Z(\\mathbf{X})$ 依赖观测，无需建模输入复杂分布。在序列标注（命名实体识别、词性标注）中，CRF 无需建模复杂的观测（如文字特征）分布，更加实用。线性链 CRF + BiLSTM 是 NLP 序列标注的经典基线。',
      },
    ],
  },
  {
    id: 't26-c',
    title: '变分推断、ELBO 与 VAE',
    subtitle: 'ELBO 分解、均场近似、重参数化技巧、VAE 的编码器-解码器框架',
    intro: [
      {
        title: '后验推断的困难：为什么需要变分推断？',
        body: '贝叶斯推断的核心任务：计算后验 $P(\\mathbf{z}\\mid\\mathbf{x}) = P(\\mathbf{x}\\mid\\mathbf{z})P(\\mathbf{z})/P(\\mathbf{x})$。难点在分母 $P(\\mathbf{x}) = \\int P(\\mathbf{x}\\mid\\mathbf{z})P(\\mathbf{z})\\,d\\mathbf{z}$——复杂模型中这个积分无法解析计算。两大近似推断方法：(1) **MCMC**：构造平稳分布为目标后验的马尔可夫链采样，渐近精确但计算慢；(2) **变分推断（VI）**：在某个"简单"分布族 $\\mathcal{Q}$ 中寻找最接近真实后验的 $q^*(\\mathbf{z})$，将推断问题转化为**优化问题**，速度快但有近似误差。MCMC 是"精确采样"，VI 是"近似优化"——两者在不同场景各有优劣。',
        tip: 'MCMC vs 变分推断的选择原则：精度要求高、计算时间充足、参数维度中等 → MCMC；需要快速推断、参数维度极高、可以接受近似 → 变分推断。深度生成模型（VAE）选择变分推断，因为需要与神经网络联合优化（梯度下降）。',
      },
      {
        title: 'ELBO 推导：KL 散度与对数似然',
        body: '**变分推断的目标**：最小化 $D_{\\mathrm{KL}}(q_\\phi(\\mathbf{z}) \\| P(\\mathbf{z}\\mid\\mathbf{x}))$。展开 KL 散度：$D_{\\mathrm{KL}}(q_\\phi \\| P(\\mathbf{z}\\mid\\mathbf{x})) = \\mathbb{E}_{q_\\phi}[\\log q_\\phi(\\mathbf{z})] - \\mathbb{E}_{q_\\phi}[\\log P(\\mathbf{x},\\mathbf{z})] + \\log P(\\mathbf{x})$。由于 $\\log P(\\mathbf{x})$ 是常数（与 $q_\\phi$ 无关），最小化 KL 等价于**最大化 ELBO**：$\\mathcal{L}(\\phi) = \\mathbb{E}_{q_\\phi}[\\log P(\\mathbf{x},\\mathbf{z})] - \\mathbb{E}_{q_\\phi}[\\log q_\\phi(\\mathbf{z})]$。关键恒等式：$\\log P(\\mathbf{x}) = \\mathcal{L}(\\phi) + D_{\\mathrm{KL}}(q_\\phi \\| P(\\mathbf{z}\\mid\\mathbf{x})) \\geq \\mathcal{L}(\\phi)$，ELBO 是对数似然的下界。最大化 ELBO 同时：(1) 最小化 $D_{\\mathrm{KL}}(q_\\phi \\| P(\\mathbf{z}\\mid\\mathbf{x}))$（推断目标）；(2) 近似最大化 $\\log P(\\mathbf{x})$（学习目标）。',
        formula: '\\log P(\\mathbf{x}) = \\underbrace{\\mathbb{E}_{q_\\phi}[\\log P(\\mathbf{x}\\mid\\mathbf{z})] - D_{\\mathrm{KL}}(q_\\phi(\\mathbf{z})\\|P(\\mathbf{z}))}_{\\mathcal{L}(\\phi) = \\text{ELBO}} + D_{\\mathrm{KL}}(q_\\phi(\\mathbf{z})\\|P(\\mathbf{z}\\mid\\mathbf{x}))',
        steps: [
          '目标：$\\min_q D_{\\mathrm{KL}}(q \\| P(\\mathbf{z}\\mid\\mathbf{x}))$，但后验难以计算',
          '展开 KL 散度，分离 $\\log P(\\mathbf{x})$（常数）和 ELBO',
          '等价地最大化 ELBO：$\\mathcal{L}(\\phi) = \\mathbb{E}_{q_\\phi}[\\log P(\\mathbf{x}\\mid\\mathbf{z})] - D_{\\mathrm{KL}}(q_\\phi \\| P(\\mathbf{z}))$',
          'ELBO $\\leq \\log P(\\mathbf{x})$，等号当 $q_\\phi = P(\\mathbf{z}\\mid\\mathbf{x})$（真实后验）',
        ],
      },
      {
        title: '均场近似：因子分解近似后验',
        body: '**均场变分推断**假设近似后验在各维度上完全分解：$q_\\phi(\\mathbf{z}) = \\prod_j q_j(z_j)$（忽略各维度之间的相关性）。在此假设下，可以推导出每个因子的最优形式（坐标上升，CAVI 算法）：$q_j^*(z_j) \\propto \\exp(\\mathbb{E}_{q_{-j}}[\\log P(\\mathbf{x},\\mathbf{z})])$，其中 $\\mathbb{E}_{q_{-j}}$ 表示对除 $z_j$ 外所有变量取期望。算法：交替更新每个因子 $q_j$ 直到 ELBO 收敛。**均场的局限**：因子分解假设低估后验方差（忽略维度间相关性），这是变分推断的"内在代价"。均场是结构性近似，MCMC 只有统计误差（随样本量减小）。',
        formula: 'q_j^*(z_j) \\propto \\exp\\left(\\mathbb{E}_{q_{-j}}[\\log P(\\mathbf{x},\\mathbf{z})]\\right)',
        tip: '均场的直觉来自统计物理：粒子 $j$ 感受到的是其他粒子的"平均场"（均场），而非实际的局部相互作用。这个近似在物理学中被广泛使用，对应变分推断中忽略变量间相关性的假设。',
      },
      {
        title: 'VAE：变分推断与深度神经网络的结合',
        body: '**变分自编码器（VAE）**用神经网络参数化变分族：编码器 $q_\\phi(\\mathbf{z}\\mid\\mathbf{x}) = \\mathcal{N}(\\mathbf{z}\\mid\\boldsymbol{\\mu}_\\phi(\\mathbf{x}), \\text{diag}(\\boldsymbol{\\sigma}^2_\\phi(\\mathbf{x})))$（学习输入 $\\mathbf{x}$ 到隐变量分布的映射）；解码器 $P_\\theta(\\mathbf{x}\\mid\\mathbf{z})$（从隐变量生成数据）。训练目标：最大化 ELBO $= \\mathbb{E}_{q_\\phi}[\\log P_\\theta(\\mathbf{x}\\mid\\mathbf{z})] - D_{\\mathrm{KL}}(q_\\phi(\\mathbf{z}\\mid\\mathbf{x}) \\| P(\\mathbf{z}))$。KL 项（正则化）：对角高斯情形有解析解，$D_{\\mathrm{KL}}(\\mathcal{N}(\\boldsymbol{\\mu},\\boldsymbol{\\sigma}^2 I) \\| \\mathcal{N}(0,I)) = -\\frac{1}{2}\\sum_j(1+\\log\\sigma_j^2-\\mu_j^2-\\sigma_j^2)$。',
        formula: '\\mathcal{L}_{\\mathrm{VAE}} = \\mathbb{E}_{q_\\phi}[\\log P_\\theta(\\mathbf{x}\\mid\\mathbf{z})] - D_{\\mathrm{KL}}(q_\\phi(\\mathbf{z}\\mid\\mathbf{x})\\|P(\\mathbf{z}))',
        reveal: {
          q: 'VAE 训练中，当 KL 项 $D_{\\mathrm{KL}}(q_\\phi(\\mathbf{z}\\mid\\mathbf{x}) \\| P(\\mathbf{z})) \\to 0$ 时，意味着什么？这被称为什么现象？',
          a: 'KL $\\to 0$ 意味着近似后验 $q_\\phi(\\mathbf{z}\\mid\\mathbf{x}) \\to P(\\mathbf{z}) = \\mathcal{N}(0,I)$，编码器不再将输入 $\\mathbf{x}$ 的有效信息编入隐变量，解码器完全忽略 $\\mathbf{z}$（退化为普通自回归模型）。这称为 **KL 坍塌（KL collapse）**。缓解方法：KL 退火（训练初期给 KL 项小权重）、$\\beta$-VAE（$\\beta>1$），或自由比特约束。',
        },
      },
      {
        title: '重参数化技巧：使梯度穿过采样操作',
        body: '**问题**：ELBO 中重建项 $\\mathbb{E}_{q_\\phi(\\mathbf{z}\\mid\\mathbf{x})}[\\log P_\\theta(\\mathbf{x}\\mid\\mathbf{z})]$ 对 $\\phi$ 的梯度无法直接通过采样计算——采样操作不可微，梯度无法穿过随机节点。**重参数化技巧**：将 $\\mathbf{z} = \\boldsymbol{\\mu}_\\phi(\\mathbf{x}) + \\boldsymbol{\\sigma}_\\phi(\\mathbf{x}) \\odot \\boldsymbol{\\epsilon}$，$\\boldsymbol{\\epsilon} \\sim \\mathcal{N}(0,I)$，将随机性从参数中分离出来。现在 $\\mathbf{z}$ 对 $\\phi$ 可微（$\\partial\\mathbf{z}/\\partial\\phi$ 存在），标准反向传播可以计算梯度。这是 VAE 可以端到端用梯度下降训练的关键。类似技巧适用于其他参数族（Gumbel-Softmax 用于离散变量等）。',
        formula: '\\mathbf{z} = \\boldsymbol{\\mu}_\\phi(\\mathbf{x}) + \\boldsymbol{\\sigma}_\\phi(\\mathbf{x}) \\odot \\boldsymbol{\\epsilon},\\quad \\boldsymbol{\\epsilon} \\sim \\mathcal{N}(\\mathbf{0}, \\mathbf{I})',
        tip: '重参数化的本质：把采样变成"确定性函数 + 固定分布的噪声"的形式，将随机性"外推"到一个与参数无关的噪声源，从而使整个计算图可微。这是深度生成模型的核心技术之一。',
      },
      {
        title: '易错点：ELBO 的等号条件、KL 方向、均场的代价',
        body: '**易错点 1**：ELBO 的等号 $\\log P(\\mathbf{x}) = \\mathcal{L}(\\phi)$ 成立当且仅当 $q_\\phi(\\mathbf{z}) = P(\\mathbf{z}\\mid\\mathbf{x})$（近似后验等于真实后验），此时 $D_{\\mathrm{KL}} = 0$。VAE 中编码器永远只是近似，故 ELBO 是严格下界（存在间隙）。**易错点 2**：变分推断最小化的是 $D_{\\mathrm{KL}}(q \\| P(\\mathbf{z}\\mid\\mathbf{x}))$（反向 KL），而非 $D_{\\mathrm{KL}}(P(\\mathbf{z}\\mid\\mathbf{x}) \\| q)$（前向 KL）。反向 KL 倾向于"模式寻求"——$q$ 聚焦于后验的某个峰，可能忽略多峰后验的其他模式。**易错点 3**：均场近似低估后验方差，因为它假设各维度独立，无法捕捉后验的相关结构。如果任务对后验方差的准确性有要求（如不确定性估计），需要更复杂的变分族（如 normalizing flows）或改用 MCMC。',
        tip: '总结三条信息流：(1) 输入 $\\mathbf{x}$ → 编码器 $q_\\phi$ → 隐变量 $\\mathbf{z}$（推断方向，学习后验）；(2) 隐变量 $\\mathbf{z}$ → 解码器 $P_\\theta$ → 重建 $\\hat{\\mathbf{x}}$（生成方向，学习似然）；(3) 先验 $P(\\mathbf{z})$ 约束隐变量空间（正则化方向，KL 项）。三条流平衡才是好的 VAE。',
      },
    ],
    questions: [
      {
        type: 'judge',
        prompt: '在变分推断中，最大化 ELBO $\\mathcal{L}(\\phi)$ 等价于最小化 $D_{\\mathrm{KL}}(q_\\phi(\\mathbf{z}) \\| P(\\mathbf{z}\\mid\\mathbf{x}))$，因为 $\\log P(\\mathbf{x})$ 是与 $\\phi$ 无关的常数。这个说法正确吗？',
        answer: true,
        explain: '正确。由恒等式 $\\log P(\\mathbf{x}) = \\mathcal{L}(\\phi) + D_{\\mathrm{KL}}(q_\\phi \\| P(\\mathbf{z}\\mid\\mathbf{x}))$，由于 $\\log P(\\mathbf{x})$ 对参数 $\\phi$ 是常数，$\\max_\\phi \\mathcal{L}(\\phi) \\Leftrightarrow \\min_\\phi D_{\\mathrm{KL}}(q_\\phi \\| P(\\mathbf{z}\\mid\\mathbf{x}))$。这正是变分推断的核心思路：将难以直接优化的 KL 散度，转化为可以优化的 ELBO（不涉及难以计算的真实后验）。',
      },
      {
        type: 'choice',
        prompt: 'VAE 的 ELBO 可以分解为 $\\mathcal{L} = \\mathbb{E}_{q_\\phi}[\\log P_\\theta(\\mathbf{x}\\mid\\mathbf{z})] - D_{\\mathrm{KL}}(q_\\phi(\\mathbf{z}\\mid\\mathbf{x}) \\| P(\\mathbf{z}))$，其中两项分别代表：',
        options: [
          '重建质量（解码器好坏）和正则化（近似后验接近先验）',
          '先验分布的熵和对数似然',
          '编码器的准确性和解码器的准确性',
          'KL 散度和交叉熵',
        ],
        answer: 0,
        explain: '第一项 $\\mathbb{E}_{q_\\phi}[\\log P_\\theta(\\mathbf{x}\\mid\\mathbf{z})]$ 是重建项——衡量解码器将隐变量 $\\mathbf{z}$ 重建为输入 $\\mathbf{x}$ 的质量，越大越好；第二项 $D_{\\mathrm{KL}}(q_\\phi(\\mathbf{z}\\mid\\mathbf{x}) \\| P(\\mathbf{z}))$ 是正则化项——惩罚近似后验偏离先验 $P(\\mathbf{z})=\\mathcal{N}(0,I)$，越小越好。两项相互制衡：重建项鼓励编码器将不同输入编码到不同的隐变量区域，KL 项鼓励所有编码集中到先验。',
      },
      {
        type: 'judge',
        prompt: '重参数化技巧（Reparameterization Trick）将 $\\mathbf{z} = \\boldsymbol{\\mu} + \\boldsymbol{\\sigma} \\odot \\boldsymbol{\\epsilon}$，$\\boldsymbol{\\epsilon} \\sim \\mathcal{N}(0,I)$，使得梯度可以通过采样操作反向传播到编码器参数 $\\phi$。这个说法正确吗？',
        answer: true,
        explain: '正确。原始采样 $\\mathbf{z} \\sim q_\\phi(\\mathbf{z}\\mid\\mathbf{x}) = \\mathcal{N}(\\boldsymbol{\\mu}_\\phi, \\boldsymbol{\\sigma}^2_\\phi I)$ 是不可微操作，梯度无法穿过随机节点。重参数化后，$\\mathbf{z} = \\boldsymbol{\\mu}_\\phi + \\boldsymbol{\\sigma}_\\phi \\odot \\boldsymbol{\\epsilon}$ 是 $\\phi$ 的确定性可微函数（$\\boldsymbol{\\epsilon}$ 的随机性与 $\\phi$ 无关），$\\partial\\mathbf{z}/\\partial\\phi$ 存在，标准反向传播可以计算 $\\nabla_\\phi \\mathcal{L}$。',
      },
      {
        type: 'input',
        prompt: '对角高斯近似后验 $q_\\phi(z) = \\mathcal{N}(z\\mid\\mu, \\sigma^2)$，先验 $P(z) = \\mathcal{N}(0,1)$，$\\mu=0$，$\\sigma^2=1$ 时，$D_{\\mathrm{KL}}(q_\\phi \\| P)$ 等于多少？',
        accept: ['0', '0.0'],
        explain: '当 $q_\\phi = P$（$\\mu=0$，$\\sigma^2=1$）时，$D_{\\mathrm{KL}}(q_\\phi \\| P) = 0$（相同分布的 KL 散度为零）。代入解析公式：$D_{\\mathrm{KL}} = -\\frac{1}{2}(1+\\log\\sigma^2 - \\mu^2 - \\sigma^2) = -\\frac{1}{2}(1+0-0-1) = 0$。这也是 VAE 训练的"最优正则化状态"——若达到此状态则 KL 项贡献为零（KL 坍塌的边界条件）。',
      },
      {
        type: 'choice',
        prompt: '均场变分推断假设 $q_\\phi(\\mathbf{z}) = \\prod_j q_j(z_j)$，这个假设的代价是什么？',
        options: [
          '低估后验方差，忽略各维度之间的相关结构',
          '高估后验方差，使推断过于保守',
          '使优化问题变成非凸的，难以求解',
          '要求隐变量必须服从正态分布',
        ],
        answer: 0,
        explain: '均场假设各维度独立，但真实后验通常在各维度间存在相关性。由于强制因子分解，均场近似无法捕捉后验的协方差结构，导致**低估后验方差**（近似后验比真实后验更"尖锐"、更集中）。这是变分推断相对于 MCMC 的固有局限。更复杂的变分族（如 normalizing flows、full-covariance Gaussian）可以缓解，但计算代价更高。',
      },
      {
        type: 'match',
        prompt: '将 VAE 的各组件与其对应的概率图模型概念配对：',
        left: ['编码器网络 $q_\\phi(\\mathbf{z}\\mid\\mathbf{x})$', '解码器网络 $P_\\theta(\\mathbf{x}\\mid\\mathbf{z})$', '先验 $P(\\mathbf{z}) = \\mathcal{N}(0,I)$', 'ELBO 中的 KL 项'],
        right: [
          '隐变量的先验分布，约束隐变量空间形状',
          '变分推断中的近似后验分布（变分族中的最优选择）',
          '似然函数，描述从隐变量到观测的生成过程',
          '正则化项，驱使近似后验接近先验，防止 KL 坍塌',
        ],
        explain: '编码器 $q_\\phi(\\mathbf{z}\\mid\\mathbf{x})$ 是变分推断中的近似后验（配第1条）；解码器 $P_\\theta(\\mathbf{x}\\mid\\mathbf{z})$ 是似然函数（配第2条）；先验 $P(\\mathbf{z})$ 约束隐变量空间（配第0条）；KL 项是正则化（配第3条）。正确顺序：[1,2,0,3]。',
      },
      {
        type: 'choice',
        prompt: 'HMM（隐马尔可夫模型）前向算法计算 $P(\\mathbf{x})$ 的时间复杂度为多少？（序列长度 $T$，隐状态数 $K$）',
        options: ['$O(TK^2)$', '$O(K^T)$', '$O(T^2 K)$', '$O(TK)$'],
        answer: 0,
        explain: '暴力枚举 HMM 所有路径需要 $O(K^T)$（指数级）。前向算法利用动态规划：定义 $\\alpha_t(k) = P(x_1,\\ldots,x_t, z_t=k)$，递推 $\\alpha_{t+1}(k\') = P(x_{t+1}\\mid z_{t+1}=k\')\\sum_k\\alpha_t(k)P(z_{t+1}=k\'\\mid z_t=k)$。每步需要对 $K$ 个当前状态和 $K$ 个前状态计算转移，共 $T$ 步，总复杂度 $O(TK^2)$。这比暴力法减少了指数量级，是动态规划的典型应用。',
      },
    ],
  },
]
