export const LESSONS = [
  {
    id: 't4-a',
    title: '随机变量与概率质量函数',
    subtitle: '把随机试验的结果"数值化"，PMF 描述完整分布',
    intro: [
      {
        title: '为什么要引入随机变量？',
        body: '古典概型直接对"事件"计算概率，但很多问题需要对结果做数学运算：掷两枚骰子，我们想研究"点数之和"；射击比赛，我们想研究"命中环数"。\n\n如果还是用事件的语言，每次都要重新描述样本空间，极不方便。\n\n**随机变量**的本质：一个从样本空间 $\\Omega$ 到实数 $\\mathbb{R}$ 的函数 $X: \\Omega \\to \\mathbb{R}$，把每个随机结果"翻译"成一个数，让我们可以用代数工具来研究随机性。',
        tip: '随机变量不是"变量"，而是一个函数。"随机"来自 $\\Omega$，"变量"是函数的值。',
      },
      {
        title: 'PMF——离散随机变量的完整描述',
        body: '当随机变量 $X$ 的可能取值是有限个或可数无穷个时，称 $X$ 为**离散随机变量**。\n\n描述它的工具叫**概率质量函数**（PMF），定义为：每个取值 $x$ 对应的概率 $p(x) = P(X = x)$。\n\nPMF 必须满足两个性质，缺一不可：\n1. **非负性**：$p(x) \\geq 0$ 对所有 $x$ 成立\n2. **归一化**：$\\sum_i p(x_i) = 1$（所有可能值的概率加起来恰好等于 1）',
        formula: 'p(x_i) \\geq 0, \\quad \\sum_{i} p(x_i) = 1',
        tip: '拿到任何 PMF，第一步永远是验证归一化。若含未知参数，先用 $\\sum p_i = 1$ 解出参数。',
      },
      {
        title: '含参数 PMF 的归一化——例题精讲',
        body: '设离散随机变量 $X$ 的 PMF 为 $p(k) = c \\cdot k$，$k = 1, 2, 3, 4$，其他取值概率为 0。\n\n**第一步**：写出所有取值的概率之和，令其等于 1：',
        formula: '\\sum_{k=1}^{4} c \\cdot k = c(1+2+3+4) = 10c = 1 \\implies c = \\frac{1}{10}',
        steps: [
          '列出 PMF 表：$p(1)=0.1,\\ p(2)=0.2,\\ p(3)=0.3,\\ p(4)=0.4$',
          '验证：$0.1+0.2+0.3+0.4 = 1$ ✓',
          '此后所有期望、方差计算都用这张表',
        ],
        tip: '含参数时，归一化方程有且只有一个唯一解（若参数让某个 $p < 0$，说明参数无效）。',
      },
      {
        title: 'CDF——累积分布函数（阶梯函数）',
        body: '**累积分布函数**（CDF）定义为：$F(x) = P(X \\leq x) = \\sum_{x_i \\leq x} p(x_i)$\n\n对于离散随机变量，CDF 是一个**阶梯函数**：\n- 在每个取值 $x_i$ 处，$F$ 突然跳跃，跳跃高度恰好等于 PMF 值 $p(x_i)$\n- 在两个取值之间，$F$ 保持不变（水平线段）\n- $F$ 是**右连续**的：$F(x_k)$ 取的是右极限的值\n\n**注意区分**：离散型中，$P(X < k) = F(k^-) \\neq F(k) = P(X \\leq k)$，差值就是 $p(k)$。',
        formula: 'F(x) = P(X \\leq x) = \\sum_{x_i \\leq x} p(x_i)',
        steps: [
          '例：$p(1)=0.2,\\ p(2)=0.3,\\ p(3)=0.3,\\ p(4)=0.2$',
          '$F(1)=0.2,\\ F(2)=0.5,\\ F(3)=0.8,\\ F(4)=1.0$',
          '$P(2 \\leq X \\leq 3) = F(3) - F(1) = 0.8 - 0.2 = 0.6$（注意：左端含等号，要用 $F(3)-F(1)$）',
        ],
        tip: '区间概率公式：$P(a < X \\leq b) = F(b) - F(a)$。若左端含等号，用 $F(b) - F(a^-)$。',
      },
      {
        title: '常见离散分布速查（伯努利 / 二项 / 几何 / 泊松）',
        body: '四大离散分布几乎覆盖了所有离散概率建模场景：\n\n**伯努利** $B(p)$：只有 0/1 两个取值，成功概率 $p$。\n**二项** $B(n,p)$：$n$ 次独立伯努利试验的成功次数 $k$，$p(k) = \\binom{n}{k}p^k(1-p)^{n-k}$。\n**几何** $G(p)$：首次成功所需的试验次数 $k$，$p(k) = (1-p)^{k-1}p$，$k=1,2,\\ldots$\n**泊松** $\\mathrm{Poi}(\\lambda)$：单位时间/空间内事件发生次数 $k$，$p(k) = e^{-\\lambda}\\lambda^k/k!$，$k=0,1,2,\\ldots$',
        formula: 'p_{\\text{Poi}}(k) = \\frac{e^{-\\lambda}\\lambda^k}{k!}, \\quad k = 0, 1, 2, \\ldots',
        tip: '泊松分布适用于"稀少事件"：$n$ 大、$p$ 小、$\\lambda = np$ 适中（$n \\geq 20, p \\leq 0.05$）时，$B(n,p) \\approx \\mathrm{Poi}(\\lambda)$。',
      },
      {
        title: '易错点与思考路标',
        body: '**易错点 1**：PMF 归一化不验证就直接用，导致后续计算全错。\n\n**易错点 2**：CDF 在离散情形中，$P(X < k) \\neq F(k)$，要用 $F(k-1)$（当取值均为整数时）或 $F(k^-)$。\n\n**易错点 3**：泊松近似的条件——$p$ 接近 1 时不能用泊松（此时用正态近似）。\n\n**易错点 4**：几何分布的"首次成功"从 $k=1$ 开始计数，有的教材从 $k=0$ 计数（失败次数），使用前确认定义。',
        reveal: {
          q: '设 $p(k) = c\\cdot(1/2)^k$，$k = 1, 2, 3, \\ldots$，求归一化常数 $c$。',
          a: '$\\sum_{k=1}^{\\infty}(1/2)^k = 1/2 \\div (1-1/2) = 1$，故 $c = 1$。这正是参数 $p=1/2$ 的几何分布（$p(k) = (1/2)^k = (1-1/2)^{k-1}\\cdot(1/2)$）。',
        },
      },
    ],
    questions: [
      {
        type: 'judge',
        prompt: '对于任意离散随机变量 $X$，其 PMF 满足：$\\sum_i p(x_i) = 1$ 且 $p(x_i) \\geq 0$。这两个条件合称归一化与非负性，缺少其中任何一个，$p$ 都不能作为合法 PMF。',
        answer: true,
        explain: '正确。PMF 的两个必要且充分条件是非负性（$p(x) \\geq 0$）和归一化（$\\sum p(x_i) = 1$）。只有同时满足这两个条件，才是合法 PMF。',
      },
      {
        type: 'choice',
        prompt: '设 $X$ 的 PMF 为 $p(k) = c \\cdot k$，$k = 1, 2, 3, 4$（其他取值概率为 0）。求常数 $c$。',
        options: ['$c = 1/4$', '$c = 1/10$', '$c = 1/6$', '$c = 1/5$'],
        answer: 1,
        explain: '$\\sum_{k=1}^{4} ck = c(1+2+3+4) = 10c = 1$，故 $c = 1/10$。验证：$p(1)=0.1, p(2)=0.2, p(3)=0.3, p(4)=0.4$，之和为 $1$ ✓。',
      },
      {
        type: 'input',
        prompt: '掷一枚均匀骰子，$X$ 为点数。求 $P(2 \\leq X \\leq 4)$（写分数或小数）。',
        accept: ['1/2', '0.5', '3/6'],
        explain: '$P(2 \\leq X \\leq 4) = p(2)+p(3)+p(4) = 3 \\times 1/6 = 1/2$。也可用 CDF：$F(4) - F(1) = 4/6 - 1/6 = 1/2$。',
      },
      {
        type: 'choice',
        prompt: '设 $X$ 的 PMF 为 $p(1)=0.2, p(2)=0.5, p(3)=0.3$。CDF 在 $x=2$ 处的值 $F(2)$ 等于多少？',
        options: ['$0.2$', '$0.5$', '$0.7$', '$1.0$'],
        answer: 2,
        explain: '$F(2) = P(X \\leq 2) = p(1) + p(2) = 0.2 + 0.5 = 0.7$。CDF 是累积求和，到 $x=2$ 为止所有取值的概率之和。',
      },
      {
        type: 'judge',
        prompt: '对于离散随机变量，$P(X < 3) = F(3)$（其中 $F$ 为 CDF）。',
        answer: false,
        explain: '错误。$F(3) = P(X \\leq 3)$，包含了 $X=3$ 的概率；而 $P(X < 3) = F(3) - p(3) = F(2)$（当取值为整数时）。离散情形中"$<$"与"$\\leq$"不等价，差值为 $p(3)$。',
      },
      {
        type: 'match',
        prompt: '将各分布与其标志性特征匹配。',
        left: ['伯努利 $B(p)$', '二项 $B(n,p)$', '几何 $G(p)$', '泊松 $\\mathrm{Poi}(\\lambda)$'],
        right: [
          '首次成功所需试验次数，具有无记忆性',
          '只有 0/1 两个取值，单次试验结果',
          '$n$ 次独立试验的成功总次数',
          '单位时间内稀少事件的发生次数，$E=\\mathrm{Var}=\\lambda$',
        ],
        explain: '伯努利↔只有0/1两个取值；二项↔$n$次独立试验成功次数；几何↔首次成功所需次数（无记忆性）；泊松↔稀少事件计数（$E=\\mathrm{Var}=\\lambda$）。',
      },
      {
        type: 'input',
        prompt: '某产品次品率为 0.1，抽取 10 件，$X \\sim B(10, 0.1)$。$E[X]$ 等于多少？',
        accept: ['1', '1.0'],
        explain: '二项分布期望公式 $E[X] = np = 10 \\times 0.1 = 1$。',
      },
      {
        type: 'choice',
        prompt: '某银行每小时平均来 6 位顾客，$X \\sim \\mathrm{Poi}(6)$。以下哪项正确？',
        options: [
          '$E[X] = 6,\\ \\mathrm{Var}(X) = 36$',
          '$E[X] = 6,\\ \\mathrm{Var}(X) = 6$',
          '$E[X] = 36,\\ \\mathrm{Var}(X) = 6$',
          '$E[X] = \\sqrt{6},\\ \\mathrm{Var}(X) = 6$',
        ],
        answer: 1,
        explain: '泊松分布的期望和方差都等于参数 $\\lambda$：$E[X] = \\mathrm{Var}(X) = \\lambda = 6$。这是泊松分布的特征性质，也是判断是否适合用泊松分布的依据之一。',
      },
    ],
  },
  {
    id: 't4-b',
    title: '期望与方差——离散随机变量的数字特征',
    subtitle: '加权平均是期望，离散程度是方差',
    intro: [
      {
        title: '为什么要定义期望？',
        body: '随机变量每次取值不固定，但我们想用一个数来代表它的"典型水平"。\n\n**圣彼得堡悖论**：掷硬币，首次正面时游戏结束，第 $k$ 次首次正面则获得 $2^k$ 元。理论期望是 $\\sum_{k=1}^{\\infty} 2^k \\cdot (1/2)^k = \\sum_{k=1}^{\\infty} 1 = +\\infty$——期望无穷大！但没有人愿意花超过几十元参与。\n\n这说明：期望是"长期平均"，但若无穷级数发散，期望就不存在。大多数常见分布的期望是有限且有意义的。',
        tip: '期望的几何意义：把概率当"重量"，期望是杠杆上的平衡点。',
      },
      {
        title: '期望的定义与计算',
        body: '离散随机变量 $X$ 的**期望**（均值）定义为各取值与对应概率的加权和：\n\n推导思路：$n$ 次独立重复试验中，$X$ 取值 $x_i$ 大约出现 $n \\cdot p(x_i)$ 次，总和约为 $\\sum_i x_i \\cdot n p(x_i)$，除以 $n$ 得平均值 $\\sum_i x_i p(x_i)$——这就是期望的来源。',
        formula: '\\mathrm{E}[X] = \\sum_{i} x_i \\cdot p(x_i)',
        steps: [
          '例：骰子 $X$ 取 $1,2,3,4,5,6$，各概率 $1/6$',
          '$\\mathrm{E}[X] = (1+2+3+4+5+6)/6 = 21/6 = 3.5$',
          '例：$p(1)=0.1, p(2)=0.2, p(3)=0.3, p(4)=0.4$',
          '$\\mathrm{E}[X] = 1\\times0.1 + 2\\times0.2 + 3\\times0.3 + 4\\times0.4 = 0.1+0.4+0.9+1.6 = 3.0$',
        ],
        tip: '期望的线性性：$\\mathrm{E}[aX+b] = a\\mathrm{E}[X]+b$；$\\mathrm{E}[X+Y] = \\mathrm{E}[X]+\\mathrm{E}[Y]$（无论独立与否）。',
      },
      {
        title: 'LOTUS——函数的期望',
        body: '若要计算 $Y = g(X)$ 的期望，**不需要先求 $Y$ 的分布**，直接用 LOTUS（无意识统计学家定理）：\n\n$\\mathrm{E}[g(X)] = \\sum_i g(x_i) \\cdot p(x_i)$\n\n**经典错误**：$\\mathrm{E}[X^2] \\neq (\\mathrm{E}[X])^2$（除非 $X$ 退化为常数）。两者之差恰好是方差：$\\mathrm{Var}(X) = \\mathrm{E}[X^2] - (\\mathrm{E}[X])^2 \\geq 0$。\n\n例：骰子 $\\mathrm{E}[X^2] = (1+4+9+16+25+36)/6 = 91/6 \\approx 15.17$，而 $(\\mathrm{E}[X])^2 = 3.5^2 = 12.25$，差值就是方差 $35/12 \\approx 2.92$。',
        formula: '\\mathrm{E}[g(X)] = \\sum_{i} g(x_i) \\cdot p(x_i)',
        tip: '只有 $g$ 是线性函数时，$\\mathrm{E}[g(X)] = g(\\mathrm{E}[X])$ 才成立（Jensen 不等式取等条件）。',
      },
      {
        title: '方差的定义与计算公式',
        body: '**方差**度量随机变量偏离均值的程度，定义为"偏差平方的期望"：\n\n$\\mathrm{Var}(X) = \\mathrm{E}[(X-\\mu)^2]$，其中 $\\mu = \\mathrm{E}[X]$\n\n**实用计算公式**（优先使用）：$\\mathrm{Var}(X) = \\mathrm{E}[X^2] - (\\mathrm{E}[X])^2$\n\n**推导**：$\\mathrm{Var}(X) = \\mathrm{E}[X^2 - 2\\mu X + \\mu^2] = \\mathrm{E}[X^2] - 2\\mu\\cdot\\mathrm{E}[X] + \\mu^2 = \\mathrm{E}[X^2] - \\mu^2$\n\n若计算结果为负数，一定有计算错误（方差非负）。',
        formula: '\\mathrm{Var}(X) = \\mathrm{E}[X^2] - (\\mathrm{E}[X])^2',
        steps: [
          '第1步：算 $\\mathrm{E}[X] = \\sum x_i p_i$',
          '第2步：算 $\\mathrm{E}[X^2] = \\sum x_i^2 p_i$（注意是 $x^2$ 乘概率，不是 $x$ 平方后乘）',
          '第3步：$\\mathrm{Var}(X) = \\mathrm{E}[X^2] - (\\mathrm{E}[X])^2$',
          '第4步：标准差 $\\sigma = \\sqrt{\\mathrm{Var}(X)}$（与 $X$ 同量纲）',
        ],
      },
      {
        title: '方差的性质——线性变换规则',
        body: '设 $a, b$ 为常数：\n\n1. $\\mathrm{Var}(a) = 0$（常数无随机性）\n2. $\\mathrm{Var}(aX + b) = a^2 \\mathrm{Var}(X)$（平移 $b$ 不改变离散程度，系数 $a$ 要平方！）\n3. $\\mathrm{Var}(X + Y) = \\mathrm{Var}(X) + \\mathrm{Var}(Y)$（仅当 $X, Y$ 独立时成立）\n\n**易错**：$\\mathrm{Var}(aX+b) = a^2\\mathrm{Var}(X)$，不是 $(a+b)^2\\mathrm{Var}(X)$，也不是 $a^2\\mathrm{Var}(X)+b$——$b$ 是平移，绝对不影响方差。',
        formula: '\\mathrm{Var}(aX + b) = a^2 \\mathrm{Var}(X)',
        tip: '记忆口诀：期望看系数和平移（都参与），方差看系数平方（平移消失）。',
      },
      {
        title: '四大分布的期望与方差速记',
        body: '记住这张表，考试中遇到这些分布可以直接写结果：\n\n- **伯努利** $B(p)$：$\\mathrm{E}[X]=p$，$\\mathrm{Var}(X)=p(1-p)$\n- **二项** $B(n,p)$：$\\mathrm{E}[X]=np$，$\\mathrm{Var}(X)=np(1-p)$\n- **几何** $G(p)$（首次成功）：$\\mathrm{E}[X]=1/p$，$\\mathrm{Var}(X)=(1-p)/p^2$\n- **泊松** $\\mathrm{Poi}(\\lambda)$：$\\mathrm{E}[X]=\\lambda$，$\\mathrm{Var}(X)=\\lambda$\n\n**推导记忆法**：二项 = $n$ 个独立伯努利之和，期望和方差都乘以 $n$；泊松是大量独立稀少事件之和，期望=方差是其唯一特征（用于验证是否适合泊松模型）。',
        reveal: {
          q: '$X \\sim \\mathrm{Poi}(3)$，求 $\\mathrm{E}[X^2]$（不用直接求和）。',
          a: '$\\mathrm{E}[X^2] = \\mathrm{Var}(X) + (\\mathrm{E}[X])^2 = 3 + 9 = 12$。公式 $\\mathrm{Var}(X)=\\mathrm{E}[X^2]-(\\mathrm{E}[X])^2$ 反过来用，可快速求 $E[X^2]$。',
        },
      },
      {
        title: '综合例题：PMF 归一化 + 期望 + 方差一气呵成',
        body: '**题目**：$X$ 的 PMF 为 $p(k) = k/10$，$k=1,2,3,4$。求 $\\mathrm{E}[X]$、$\\mathrm{Var}(X)$、$P(X \\geq 3)$。\n\n**解题过程**：',
        steps: [
          '验证归一化：$\\sum_{k=1}^{4} k/10 = (1+2+3+4)/10 = 1$ ✓',
          '$\\mathrm{E}[X] = 1\\cdot0.1 + 2\\cdot0.2 + 3\\cdot0.3 + 4\\cdot0.4 = 0.1+0.4+0.9+1.6 = 3.0$',
          '$\\mathrm{E}[X^2] = 1\\cdot0.1 + 4\\cdot0.2 + 9\\cdot0.3 + 16\\cdot0.4 = 0.1+0.8+2.7+6.4 = 10.0$',
          '$\\mathrm{Var}(X) = 10 - 9 = 1$，标准差 $\\sigma = 1$',
          '$P(X \\geq 3) = p(3)+p(4) = 0.3+0.4 = 0.7$',
        ],
        tip: '列表计算是最不易出错的方法：一列 $x_i$，一列 $p_i$，一列 $x_i p_i$，一列 $x_i^2 p_i$，逐行填写再求和。',
      },
    ],
    questions: [
      {
        type: 'choice',
        prompt: '设 $X$ 的 PMF 为 $p(0)=0.5, p(1)=0.3, p(2)=0.2$。$\\mathrm{E}[X]$ 等于多少？',
        options: ['$0.5$', '$0.7$', '$1.0$', '$0.9$'],
        answer: 1,
        explain: '$\\mathrm{E}[X] = 0\\times0.5 + 1\\times0.3 + 2\\times0.2 = 0 + 0.3 + 0.4 = 0.7$。注意 $x=0$ 那项贡献为 0（乘以 0 了），但不能漏掉它。',
      },
      {
        type: 'input',
        prompt: '设 $X \\sim B(8, 0.25)$，求 $\\mathrm{Var}(X)$（写精确值）。',
        accept: ['1.5', '3/2'],
        explain: '$\\mathrm{Var}(X) = np(1-p) = 8 \\times 0.25 \\times 0.75 = 1.5$。二项分布方差公式 $np(1-p)$ 要会直接套用。',
      },
      {
        type: 'judge',
        prompt: '对任意随机变量 $X$ 和常数 $b$，有 $\\mathrm{Var}(X + b) = \\mathrm{Var}(X) + b$。',
        answer: false,
        explain: '错误。$\\mathrm{Var}(X+b) = \\mathrm{Var}(X)$，平移常数 $b$ 不改变方差（方差度量的是离散程度，而非绝对位置）。正确公式是 $\\mathrm{Var}(aX+b) = a^2\\mathrm{Var}(X)$，$b$ 完全消失。',
      },
      {
        type: 'choice',
        prompt: '设 $\\mathrm{E}[X] = 2$，$\\mathrm{E}[X^2] = 8$，则 $\\mathrm{Var}(X)$ 等于：',
        options: ['$6$', '$4$', '$2$', '$12$'],
        answer: 1,
        explain: '$\\mathrm{Var}(X) = \\mathrm{E}[X^2] - (\\mathrm{E}[X])^2 = 8 - 4 = 4$。公式 $\\mathrm{Var}(X) = \\mathrm{E}[X^2] - (\\mathrm{E}[X])^2$ 是计算方差的首选公式。',
      },
      {
        type: 'input',
        prompt: '$X \\sim \\mathrm{Poi}(5)$，利用泊松分布性质（不直接展开求和），求 $\\mathrm{E}[X^2]$。',
        accept: ['30'],
        explain: '$\\mathrm{E}[X^2] = \\mathrm{Var}(X) + (\\mathrm{E}[X])^2$。泊松分布 $\\mathrm{Var}(X) = \\lambda = 5$，$\\mathrm{E}[X] = 5$，故 $\\mathrm{E}[X^2] = 5 + 25 = 30$。',
      },
      {
        type: 'match',
        prompt: '将期望/方差的性质与正确公式匹配。',
        left: ['$\\mathrm{E}[aX+b]$', '$\\mathrm{Var}(aX+b)$', '$\\mathrm{E}[X+Y]$', '$\\mathrm{Var}(X+Y)$（$X,Y$ 独立）'],
        right: [
          '$\\mathrm{Var}(X) + \\mathrm{Var}(Y)$',
          '$a\\mathrm{E}[X] + b$',
          '$\\mathrm{E}[X] + \\mathrm{E}[Y]$',
          '$a^2\\mathrm{Var}(X)$',
        ],
        explain: '期望线性：$\\mathrm{E}[aX+b]=a\\mathrm{E}[X]+b$；方差线性变换：$\\mathrm{Var}(aX+b)=a^2\\mathrm{Var}(X)$；期望可加性无条件：$\\mathrm{E}[X+Y]=\\mathrm{E}[X]+\\mathrm{E}[Y]$；方差独立时可加：$\\mathrm{Var}(X+Y)=\\mathrm{Var}(X)+\\mathrm{Var}(Y)$。',
      },
      {
        type: 'choice',
        prompt: '设 $X \\sim G(1/3)$（几何分布，首次成功的试验次数），则 $\\mathrm{E}[X]$ 等于：',
        options: ['$1/3$', '$2/3$', '$3$', '$9$'],
        answer: 2,
        explain: '几何分布（首次成功）的期望为 $\\mathrm{E}[X] = 1/p = 1/(1/3) = 3$。直觉：平均每 3 次试验才首次成功一次，所以期望试验次数是 3。',
      },
      {
        type: 'judge',
        prompt: '若 $\\mathrm{E}[X] = 3$ 且 $g(x) = x^2$，则 $\\mathrm{E}[g(X)] = g(\\mathrm{E}[X]) = 9$。',
        answer: false,
        explain: '错误。一般情况下 $\\mathrm{E}[g(X)] \\neq g(\\mathrm{E}[X])$（Jensen 不等式）。$\\mathrm{E}[X^2] = \\mathrm{Var}(X) + (\\mathrm{E}[X])^2 = \\mathrm{Var}(X) + 9 \\geq 9$，等号成立当且仅当 $\\mathrm{Var}(X)=0$（即 $X$ 退化为常数）。',
      },
    ],
  },
  {
    id: 't4-c',
    title: '矩母函数与无记忆性',
    subtitle: 'MGF 是求矩的"生成器"，几何分布独有无记忆性',
    intro: [
      {
        title: '矩母函数的动机：一个函数包含所有矩',
        body: '期望是"一阶矩"，$\\mathrm{E}[X^2]$ 是"二阶矩"……如果有一个函数能同时生成所有矩，就不用逐个计算了。\n\n**矩母函数**（MGF）就是这样的工具：$M_X(t) = \\mathrm{E}[e^{tX}]$\n\n**为什么能生成矩？** 把 $e^{tX}$ 展开为幂级数：$e^{tX} = \\sum_{n=0}^{\\infty} \\frac{(tX)^n}{n!}$，求期望后得 $M_X(t) = \\sum_{n=0}^{\\infty} \\frac{\\mathrm{E}[X^n]}{n!} t^n$。对 $t$ 求 $n$ 次导再令 $t=0$，恰好取出第 $n$ 阶矩 $\\mathrm{E}[X^n]$。',
        formula: 'M_X(t) = \\mathrm{E}[e^{tX}] = \\sum_i e^{tx_i} p(x_i), \\quad M_X^{(n)}(0) = \\mathrm{E}[X^n]',
        tip: 'MGF 名称来源："母函数"（generating function）的意思是"通过求导来生成"各阶矩，$t$ 只是辅助变量，最终令 $t=0$ 取出所需的矩。',
      },
      {
        title: '伯努利分布的 MGF——验证公式',
        body: '设 $X \\sim B(p)$（伯努利），$X$ 只取 0 或 1：\n\n$M_X(t) = e^{t \\cdot 0}(1-p) + e^{t \\cdot 1} p = (1-p) + pe^t$\n\n验证：\n- 一阶导：$M_X\'(t) = pe^t$，令 $t=0$：$M_X\'(0) = p = \\mathrm{E}[X]$ ✓\n- 二阶导：$M_X\'\'(t) = pe^t$，令 $t=0$：$M_X\'\'(0) = p = \\mathrm{E}[X^2]$\n- 方差验证：$\\mathrm{Var}(X) = p - p^2 = p(1-p)$ ✓',
        formula: 'M_X(t) = (1-p) + pe^t',
        steps: [
          '离散 MGF 就是 PMF 的加权指数和',
          '对 $t$ 求导相当于对每项 $e^{tx_i}$ 乘以 $x_i$，再求和',
          '令 $t=0$：$e^{0 \\cdot x_i} = 1$，正好剩下 $\\sum x_i p(x_i) = \\mathrm{E}[X]$',
        ],
      },
      {
        title: '泊松分布的 MGF',
        body: '$X \\sim \\mathrm{Poi}(\\lambda)$，$p(k) = e^{-\\lambda}\\lambda^k/k!$：\n\n$M_X(t) = \\sum_{k=0}^{\\infty} e^{tk} \\frac{e^{-\\lambda}\\lambda^k}{k!} = e^{-\\lambda} \\sum_{k=0}^{\\infty} \\frac{(\\lambda e^t)^k}{k!} = e^{-\\lambda} \\cdot e^{\\lambda e^t} = e^{\\lambda(e^t-1)}$\n\n验证：$M_X\'(t) = \\lambda e^t \\cdot e^{\\lambda(e^t-1)}$，令 $t=0$：$M_X\'(0) = \\lambda = \\mathrm{E}[X]$ ✓\n\n**独立变量之和**：若 $X \\sim \\mathrm{Poi}(\\lambda_1)$ 与 $Y \\sim \\mathrm{Poi}(\\lambda_2)$ 独立，则 $M_{X+Y}(t) = e^{\\lambda_1(e^t-1)} \\cdot e^{\\lambda_2(e^t-1)} = e^{(\\lambda_1+\\lambda_2)(e^t-1)}$，即 $X+Y \\sim \\mathrm{Poi}(\\lambda_1+\\lambda_2)$。',
        formula: 'M_X(t) = e^{\\lambda(e^t-1)}',
        tip: 'MGF 的核心性质：独立变量之和的 MGF = 各 MGF 之积。利用这一点，可快速判断独立泊松之和仍是泊松，独立正态之和仍是正态（下一章）。',
      },
      {
        title: '几何分布的无记忆性',
        body: '几何分布 $G(p)$（$P(X=k) = (1-p)^{k-1}p$，$k=1,2,\\ldots$）有一个特殊性质：**无记忆性**。\n\n$P(X > m+n \\mid X > m) = P(X > n)$\n\n**直觉**：已经连续失败了 $m$ 次，但未来的"等待"和从头开始是一样的——过去的失败不影响未来。\n\n**证明**：$P(X > k) = (1-p)^k$（尾概率）。\n\n$P(X > m+n \\mid X > m) = \\frac{P(X > m+n)}{P(X > m)} = \\frac{(1-p)^{m+n}}{(1-p)^m} = (1-p)^n = P(X > n)$ ✓',
        formula: 'P(X > m+n \\mid X > m) = P(X > n)',
        steps: [
          '关键公式：几何分布的尾概率 $P(X > k) = (1-p)^k$',
          '条件概率 = 联合概率 / 条件概率',
          '$(1-p)^{m+n} / (1-p)^m = (1-p)^n$，指数相减',
          '结果与 $m$ 无关——无记忆性得证',
        ],
        tip: '无记忆性是几何分布在离散分布中的唯一特征（指数分布是连续版本的无记忆分布）。',
      },
      {
        title: 'MGF 的三大核心性质',
        body: '1. **唯一性**：若两个随机变量在某开区间 $(-h,h)$ 上有相同的 MGF，则它们同分布。这意味着 MGF 完全决定了分布。\n\n2. **独立变量之积**：若 $X, Y$ 独立，则 $M_{X+Y}(t) = M_X(t) \\cdot M_Y(t)$（和的 MGF = MGF 之积）。\n\n3. **线性变换**：$M_{aX+b}(t) = e^{bt} M_X(at)$。\n\n**特征函数补充**：当 MGF 不存在时（如柯西分布），用特征函数 $\\varphi_X(t) = \\mathrm{E}[e^{itX}]$（虚指数），对任何分布都存在，在极限定理中更基础。',
        formula: 'M_{X+Y}(t) = M_X(t) \\cdot M_Y(t) \\quad (X,Y \\text{ 独立})',
        tip: '记忆：MGF 把"独立之和"变成"乘法"，极大简化了独立变量和分布的推导。',
      },
      {
        title: '易错点汇总与思考路标',
        body: '**MGF 相关易错点**：\n1. MGF 要求 $\\mathrm{E}[e^{tX}]$ 在包含 0 的某区间内有限——不是所有分布都有 MGF（如柯西）。\n2. $M_X\'(0) = \\mathrm{E}[X]$，$M_X\'\'(0) = \\mathrm{E}[X^2]$，注意是令 $t=0$ 后的值。\n3. 独立变量和的 MGF 是"乘积"，不是"和"。\n\n**无记忆性易错点**：\n- 无记忆性是"已知 $X > m$，则 $X-m$ 的分布与 $X$ 相同"——等待的剩余时间分布不变。\n- 只有几何分布（离散）和指数分布（连续）具有无记忆性。',
        reveal: {
          q: '若 $X \\sim \\mathrm{Poi}(2)$ 与 $Y \\sim \\mathrm{Poi}(3)$ 独立，$Z = X+Y$ 服从什么分布？',
          a: '$Z \\sim \\mathrm{Poi}(2+3) = \\mathrm{Poi}(5)$。利用 MGF：$M_Z(t) = e^{2(e^t-1)} \\cdot e^{3(e^t-1)} = e^{5(e^t-1)}$，这是 $\\mathrm{Poi}(5)$ 的 MGF。',
        },
      },
    ],
    questions: [
      {
        type: 'choice',
        prompt: '设 $M_X(t) = \\mathrm{E}[e^{tX}]$ 为随机变量 $X$ 的矩母函数，则 $\\mathrm{E}[X^2]$ 等于：',
        options: ['$M_X(2)$', '$M_X\'(0)$', '$M_X\'\'(0)$', '$M_X(0)$'],
        answer: 2,
        explain: '$M_X^{(n)}(0) = \\mathrm{E}[X^n]$，故 $\\mathrm{E}[X^2] = M_X\'\'(0)$（MGF 对 $t$ 求二阶导，再令 $t=0$）。$M_X(0) = \\mathrm{E}[e^0] = 1$（恒为 1）；$M_X\'(0) = \\mathrm{E}[X]$（一阶矩）。',
      },
      {
        type: 'judge',
        prompt: '若 $X \\sim \\mathrm{Poi}(3)$ 与 $Y \\sim \\mathrm{Poi}(4)$ 独立，则 $X+Y \\sim \\mathrm{Poi}(7)$。',
        answer: true,
        explain: '正确。独立泊松变量之和仍是泊松，参数相加：$\\mathrm{Poi}(\\lambda_1) + \\mathrm{Poi}(\\lambda_2) = \\mathrm{Poi}(\\lambda_1+\\lambda_2)$。这可由 MGF 性质严格证明：$M_{X+Y}(t) = e^{3(e^t-1)} \\cdot e^{4(e^t-1)} = e^{7(e^t-1)}$。',
      },
      {
        type: 'choice',
        prompt: '设 $X \\sim G(1/4)$（几何分布，首次成功的试验次数）。已知前 5 次都失败，则第 6 次及以后首次成功的概率 $P(X > 5+3 \\mid X > 5)$ 等于：',
        options: ['$(3/4)^8$', '$(3/4)^3$', '$(3/4)^5$', '$(3/4)^8 / (3/4)^5$'],
        answer: 1,
        explain: '由无记忆性：$P(X > 5+3 \\mid X > 5) = P(X > 3) = (1-1/4)^3 = (3/4)^3$。无记忆性的意思是"已知前 5 次失败，剩余的等待分布与从头开始一样"，所以直接算 $P(X > 3)$。',
      },
      {
        type: 'input',
        prompt: '设 $X \\sim B(p)$（伯努利），其 MGF 为 $M_X(t) = (1-p)+pe^t$。利用 MGF 求 $\\mathrm{E}[X]$（令 $t=0$ 后一阶导的值），写出结果（用 $p$ 表示）。',
        accept: ['p'],
        explain: '$M_X\'(t) = pe^t$，令 $t=0$：$M_X\'(0) = pe^0 = p$。故 $\\mathrm{E}[X] = p$，与伯努利分布的期望一致 ✓。',
      },
      {
        type: 'match',
        prompt: '将各分布与其 MGF 匹配。',
        left: ['伯努利 $B(p)$', '泊松 $\\mathrm{Poi}(\\lambda)$', '常数 $X=c$（退化分布）'],
        right: [
          '$e^{\\lambda(e^t-1)}$',
          '$e^{ct}$',
          '$(1-p)+pe^t$',
        ],
        explain: '伯努利 MGF：$e^{t\\cdot0}(1-p)+e^{t\\cdot1}p=(1-p)+pe^t$；泊松 MGF：$e^{\\lambda(e^t-1)}$；退化常数 $X=c$ 的 MGF：$\\mathrm{E}[e^{tX}]=e^{tc}$。',
      },
      {
        type: 'judge',
        prompt: '无记忆性（Memoryless Property）在离散分布中是几何分布独有的性质——没有其他离散分布具有无记忆性。',
        answer: true,
        explain: '正确。在离散分布中，几何分布是唯一具有无记忆性的分布；在连续分布中，指数分布是唯一具有无记忆性的分布。这一性质可以反过来用：若一个离散分布具有无记忆性，则它一定是几何分布。',
      },
      {
        type: 'choice',
        prompt: '$X$ 的 MGF 为 $M_X(t)$，$Y = 2X+3$，则 $M_Y(t)$ 等于：',
        options: [
          '$2M_X(t)+3$',
          '$e^{3t}M_X(2t)$',
          '$M_X(2t+3)$',
          '$e^{2t}M_X(3t)$',
        ],
        answer: 1,
        explain: '线性变换的 MGF 公式：$M_{aX+b}(t) = e^{bt}M_X(at)$。这里 $a=2, b=3$，故 $M_Y(t) = e^{3t}M_X(2t)$。推导：$M_Y(t) = \\mathrm{E}[e^{t(2X+3)}] = e^{3t}\\mathrm{E}[e^{2tX}] = e^{3t}M_X(2t)$。',
      },
      {
        type: 'input',
        prompt: '设 $X \\sim \\mathrm{Poi}(\\lambda)$，已知 $\\mathrm{E}[X] = \\mathrm{Var}(X) = \\lambda$。若 $\\mathrm{E}[X^2] = 20$ 且 $\\mathrm{E}[X] = 4$，则 $\\lambda$ 等于多少？',
        accept: ['4'],
        explain: '$\\mathrm{Var}(X) = \\mathrm{E}[X^2] - (\\mathrm{E}[X])^2 = 20 - 16 = 4$。对泊松分布，$\\mathrm{Var}(X) = \\lambda$，故 $\\lambda = 4$，与 $\\mathrm{E}[X] = 4$ 一致 ✓。',
      },
    ],
  },
]
