export const LESSONS = [
  {
    id: 't5-a',
    title: 'PDF 与 CDF——连续随机变量的描述工具',
    subtitle: '面积即概率，单点概率为零',
    intro: [
      {
        title: '从离散到连续：一个反直觉的转变',
        body: '离散随机变量用 PMF 给每个取值赋予概率，但连续随机变量的取值无穷不可数——若每个点都有正概率，总概率之和就会超过 1，产生矛盾。\n\n**解决方案**：放弃"单点概率"，改用"密度"。概率不在点上，而在区间的"面积"里。\n\n**反直觉事实**：$X \\sim U(0,1)$（均匀分布），则 $P(X = 0.5) = 0$。但 $0.5$ 仍然是可能取到的值！"概率为零"不等于"不可能"——这是连续型概率论最重要的观念转变。',
        tip: '概率 = 密度曲线下的面积，不是高度。$f(x)$ 可以大于 1，只要曲线下总面积仍等于 1。',
      },
      {
        title: 'PDF 的定义与性质',
        body: '连续随机变量 $X$ 的**概率密度函数**（PDF）$f(x)$ 的定义：任意区间 $[a,b]$ 上的概率等于 $f$ 在该区间上的积分。\n\n**两个必要条件**（同 PMF 的连续版本）：\n1. 非负性：$f(x) \\geq 0$ 对所有 $x$ 成立\n2. 归一化：$\\int_{-\\infty}^{+\\infty} f(x)\\,dx = 1$\n\n**关键注意**：$f(x)$ 本身不是概率，可以大于 1（如 $U(0, 0.5)$ 时 $f=2$）。概率是面积：$P(a \\leq X \\leq b) = \\int_a^b f(x)\\,dx$。',
        formula: 'P(a \\leq X \\leq b) = \\int_a^b f(x)\\,dx, \\quad f(x) \\geq 0, \\quad \\int_{-\\infty}^{+\\infty} f(x)\\,dx = 1',
        tip: '含参数时，用归一化 $\\int f(x)\\,dx = 1$ 解出参数——与离散型 $\\sum p_i = 1$ 完全类比。',
      },
      {
        title: '含参数 PDF 的归一化——例题精讲',
        body: '设 $f(x) = cx^2$（$0 \\leq x \\leq 2$，其他为 0）。\n\n**第一步**：用归一化求 $c$：',
        formula: '\\int_0^2 c x^2\\,dx = c \\cdot \\frac{x^3}{3}\\Big|_0^2 = \\frac{8c}{3} = 1 \\implies c = \\frac{3}{8}',
        steps: [
          '验证：$f(x) = \\frac{3}{8}x^2 \\geq 0$ ✓；$\\int_0^2 \\frac{3}{8}x^2\\,dx = 1$ ✓',
          '$P(1 < X < 1.5) = \\int_1^{1.5} \\frac{3}{8}x^2\\,dx = \\frac{3}{8} \\cdot \\frac{x^3}{3}\\Big|_1^{1.5} = \\frac{1}{8}(3.375 - 1) = \\frac{19}{64} \\approx 0.297$',
          '$E[X] = \\int_0^2 x \\cdot \\frac{3}{8}x^2\\,dx = \\frac{3}{8}\\int_0^2 x^3\\,dx = \\frac{3}{8} \\cdot 4 = \\frac{3}{2}$',
        ],
        tip: '分段 PDF 积分时，注意每段的积分范围；跨段时分段相加，不要一股脑积分到全区间。',
      },
      {
        title: 'CDF——连续型与离散型的重大差异',
        body: '连续随机变量的 CDF：$F(x) = P(X \\leq x) = \\int_{-\\infty}^x f(t)\\,dt$\n\n**连续型 CDF 的三大性质**：\n1. 单调不减\n2. **连续**（不再是阶梯函数！）\n3. $F(-\\infty) = 0$，$F(+\\infty) = 1$\n\n**PDF 与 CDF 的互推关系**（微积分基本定理）：$f(x) = F\'(x)$\n\n**单点概率为零的直接推论**：$P(a < X < b) = P(a \\leq X < b) = P(a < X \\leq b) = P(a \\leq X \\leq b) = F(b) - F(a)$——连续型中端点是否含入无关紧要。',
        formula: 'F(x) = \\int_{-\\infty}^x f(t)\\,dt, \\quad f(x) = F\'(x)',
        steps: [
          '例：$f(x) = 1$（$0 \\leq x \\leq 1$），则 $F(x) = x$（$0 \\leq x \\leq 1$），$F(0^-)=0$，$F(1^+)=1$',
          '验证 $f = F\'$：$(x)\' = 1 = f(x)$ ✓',
          '指数分布 $f(x) = \\lambda e^{-\\lambda x}$，$F(x) = 1 - e^{-\\lambda x}$（$x \\geq 0$）',
        ],
      },
      {
        title: '三大常见连续分布',
        body: '**均匀分布** $U(a,b)$：$f(x) = \\frac{1}{b-a}$（$a \\leq x \\leq b$）。等可能取每一点——最简单的连续分布，用于建模"完全随机"的情形。\n\n**指数分布** $\\mathrm{Exp}(\\lambda)$：$f(x) = \\lambda e^{-\\lambda x}$（$x \\geq 0$）。建模"等待时间"，具有无记忆性（连续版本）。\n\n**正态分布** $N(\\mu, \\sigma^2)$：$f(x) = \\frac{1}{\\sqrt{2\\pi}\\sigma}\\exp\\left(-\\frac{(x-\\mu)^2}{2\\sigma^2}\\right)$。自然界中最普遍的分布，由中心极限定理支撑。',
        formula: 'f_{N}(x) = \\frac{1}{\\sqrt{2\\pi}\\sigma}\\exp\\left(-\\frac{(x-\\mu)^2}{2\\sigma^2}\\right)',
        tip: '标准正态 $Z \\sim N(0,1)$：$P(-1 < Z < 1) \\approx 68.3\\%$，$P(-2 < Z < 2) \\approx 95.4\\%$，$P(-3 < Z < 3) \\approx 99.7\\%$（$1\\sigma / 2\\sigma / 3\\sigma$ 经验法则）。',
      },
      {
        title: '易错点与思考路标',
        body: '**易错点 1**：$f(x) > 1$ 不是错误——$f$ 是密度，不是概率；$f(x) \\cdot \\Delta x \\approx P(x < X < x+\\Delta x)$ 才是概率（小面积）。\n\n**易错点 2**：连续型单点概率为零，但不能说"不可能发生"——$P(X = x) = 0$ 只代表该点没有"质量"。\n\n**易错点 3**：柯西分布 $f(x) = \\frac{1}{\\pi(1+x^2)}$ 是合法 PDF（非负且积分为 1），但 $\\mathrm{E}[X]$ 不存在（积分发散）——期望存在要求 $\\int |x| f(x)\\,dx < \\infty$。',
        reveal: {
          q: '$f(x) = kx$（$0 < x < 4$），求 $k$ 和 $E[X]$。',
          a: '$\\int_0^4 kx\\,dx = k \\cdot 8 = 1$，故 $k = 1/8$。$E[X] = \\int_0^4 x \\cdot \\frac{x}{8}\\,dx = \\frac{1}{8}\\cdot\\frac{x^3}{3}\\Big|_0^4 = \\frac{64}{24} = \\frac{8}{3}$。',
        },
      },
    ],
    questions: [
      {
        type: 'judge',
        prompt: '连续随机变量 $X$ 在某点处的密度值 $f(x_0)$ 可以大于 1，这是完全合法的。',
        answer: true,
        explain: '正确。$f(x)$ 是概率密度（单位：$1/\\text{单位}$），不是概率本身。例如 $X \\sim U(0, 0.5)$ 时 $f(x) = 2 > 1$，但 $\\int_0^{0.5} 2\\,dx = 1$ 仍满足归一化。概率是面积，不是高度。',
      },
      {
        type: 'choice',
        prompt: '设 $f(x) = cx^2$（$0 \\leq x \\leq 3$，其他为 0）。求常数 $c$。',
        options: ['$c = 1/3$', '$c = 1/9$', '$c = 3$', '$c = 1/27$'],
        answer: 1,
        explain: '$\\int_0^3 cx^2\\,dx = c \\cdot \\frac{27}{3} = 9c = 1$，故 $c = 1/9$。验证：$\\int_0^3 \\frac{x^2}{9}\\,dx = \\frac{1}{9} \\cdot 9 = 1$ ✓。',
      },
      {
        type: 'input',
        prompt: '$X \\sim U(0,1)$，求 $P(X = 0.3) + P(0.2 < X < 0.5)$（写小数）。',
        accept: ['0.3', '0.30'],
        explain: '$P(X = 0.3) = 0$（连续型单点概率为零），$P(0.2 < X < 0.5) = \\int_{0.2}^{0.5} 1\\,dx = 0.3$。两者之和 $= 0 + 0.3 = 0.3$。',
      },
      {
        type: 'choice',
        prompt: '连续随机变量的 CDF $F(x)$ 和离散随机变量的 CDF 相比，以下哪项是连续型 CDF 独有的性质？',
        options: [
          '单调不减',
          '$F(-\\infty)=0$，$F(+\\infty)=1$',
          'CDF 是连续函数（无跳跃点）',
          '$F(x)$ 与 PMF/PDF 可以互推',
        ],
        answer: 2,
        explain: '连续随机变量的 CDF 是连续函数（无跳跃）。离散型 CDF 是阶梯函数，在每个取值点处有跳跃，跳跃高度等于 PMF 值。其他三项（单调不减、边界条件、与密度互推）对离散和连续都成立。',
      },
      {
        type: 'input',
        prompt: '指数分布 $X \\sim \\mathrm{Exp}(3)$ 的 CDF 为 $F(x) = 1 - e^{-3x}$（$x \\geq 0$）。求 $P(X > 1)$（保留到小数点后 3 位）。',
        accept: ['0.050', '0.05'],
        explain: '$P(X > 1) = 1 - F(1) = e^{-3} \\approx 0.050$。也可以直接用"生存函数"：$P(X > t) = e^{-\\lambda t}$，这里 $\\lambda=3, t=1$，得 $e^{-3} \\approx 0.050$。',
      },
      {
        type: 'match',
        prompt: '将各连续分布与其 PDF 匹配。',
        left: ['均匀分布 $U(0,1)$', '指数分布 $\\mathrm{Exp}(\\lambda)$', '标准正态 $N(0,1)$'],
        right: [
          '$\\frac{1}{\\sqrt{2\\pi}}e^{-x^2/2}$（全实数轴）',
          '$\\lambda e^{-\\lambda x}$（$x \\geq 0$）',
          '$1$（$0 \\leq x \\leq 1$）',
        ],
        explain: '均匀分布：密度恒为 $1/(b-a) = 1$；指数分布：$\\lambda e^{-\\lambda x}$（$x \\geq 0$）；标准正态：钟形 $\\frac{1}{\\sqrt{2\\pi}}e^{-x^2/2}$，定义在全实数轴上。',
      },
      {
        type: 'judge',
        prompt: '若 $F(x)$ 是连续随机变量 $X$ 的 CDF，则在 $F$ 可导处，$f(x) = F\'(x)$，即 PDF 是 CDF 的导数。',
        answer: true,
        explain: '正确。由微积分基本定理：$F(x) = \\int_{-\\infty}^x f(t)\\,dt$，两边对 $x$ 求导得 $F\'(x) = f(x)$（在 $f$ 连续处）。这是连续型 PDF 与 CDF 的核心互推关系。',
      },
      {
        type: 'choice',
        prompt: '$X \\sim N(60, 100)$（$\\mu=60, \\sigma=10$）。$P(50 \\leq X \\leq 70)$ 用标准正态 $\\Phi$ 表示为：',
        options: [
          '$\\Phi(7) - \\Phi(5)$',
          '$2\\Phi(1) - 1$',
          '$\\Phi(70) - \\Phi(50)$',
          '$1 - 2\\Phi(1)$',
        ],
        answer: 1,
        explain: '标准化：$Z = (X-60)/10$。$P(50 \\leq X \\leq 70) = P(-1 \\leq Z \\leq 1) = \\Phi(1) - \\Phi(-1) = \\Phi(1) - (1-\\Phi(1)) = 2\\Phi(1) - 1 \\approx 0.683$（$\\pm 1\\sigma$ 经验法则）。',
      },
    ],
  },
  {
    id: 't5-b',
    title: '期望、方差与随机变量的函数',
    subtitle: '积分求期望，Jacobian 做变换',
    intro: [
      {
        title: '连续型期望——从求和到积分',
        body: '离散型期望是"加权求和"$\\mathrm{E}[X] = \\sum x_i p(x_i)$，连续型中把求和换成积分：\n\n**直觉**：把 $[a,b]$ 分成 $n$ 等份，每份宽 $\\Delta x$，中点 $x_i$ 处"概率质量"约为 $f(x_i)\\Delta x$，期望约为 $\\sum x_i f(x_i)\\Delta x$，令 $n \\to \\infty$ 得积分。\n\n**均匀分布验证**：$X \\sim U(a,b)$，$\\mathrm{E}[X] = \\int_a^b x \\cdot \\frac{1}{b-a}\\,dx = \\frac{a+b}{2}$——区间的中点，符合"均匀"的直觉。',
        formula: '\\mathrm{E}[X] = \\int_{-\\infty}^{+\\infty} x \\cdot f(x)\\,dx',
        tip: '期望存在的前提：$\\int_{-\\infty}^{+\\infty} |x| f(x)\\,dx < \\infty$（绝对可积）。柯西分布虽是合法 PDF，但期望不存在。',
      },
      {
        title: '三大分布的期望与方差',
        body: '**均匀分布** $U(a,b)$：\n- $\\mathrm{E}[X] = \\dfrac{a+b}{2}$（区间中点）\n- $\\mathrm{Var}(X) = \\dfrac{(b-a)^2}{12}$（只与区间长度有关）\n\n**指数分布** $\\mathrm{Exp}(\\lambda)$：\n- $\\mathrm{E}[X] = \\dfrac{1}{\\lambda}$（平均等待时间 = 速率的倒数）\n- $\\mathrm{Var}(X) = \\dfrac{1}{\\lambda^2}$（标准差等于期望！）\n\n**正态分布** $N(\\mu,\\sigma^2)$：\n- $\\mathrm{E}[X] = \\mu$，$\\mathrm{Var}(X) = \\sigma^2$（参数直接就是期望和方差）',
        formula: '\\mathrm{E}[\\mathrm{Exp}(\\lambda)] = \\frac{1}{\\lambda}, \\quad \\mathrm{Var}[\\mathrm{Exp}(\\lambda)] = \\frac{1}{\\lambda^2}',
        steps: [
          '指数分布推导 $\\mathrm{E}[X]$（分部积分）：$\\int_0^{\\infty} x \\cdot \\lambda e^{-\\lambda x}\\,dx$',
          '令 $u=x, dv = \\lambda e^{-\\lambda x}dx$：$= [-xe^{-\\lambda x}]_0^{\\infty} + \\int_0^{\\infty} e^{-\\lambda x}\\,dx$',
          '$= 0 + \\left[-\\frac{1}{\\lambda}e^{-\\lambda x}\\right]_0^{\\infty} = \\frac{1}{\\lambda}$',
        ],
        tip: '记忆技巧：指数分布 $\\mathrm{E}=1/\\lambda$，$\\sigma=1/\\lambda$，即"均值=标准差"——这是指数分布的独特特征（变异系数恒为 1）。',
      },
      {
        title: 'LOTUS 与方差公式',
        body: '与离散型完全类比：\n\n**LOTUS（函数的期望）**：$\\mathrm{E}[g(X)] = \\int_{-\\infty}^{+\\infty} g(x) f(x)\\,dx$，不需要先求 $g(X)$ 的 PDF。\n\n**方差公式**：$\\mathrm{Var}(X) = \\mathrm{E}[X^2] - (\\mathrm{E}[X])^2$\n\n**均匀分布验证**：$X \\sim U(0,1)$，$\\mathrm{E}[X^2] = \\int_0^1 x^2\\,dx = 1/3$，$\\mathrm{Var}(X) = 1/3 - (1/2)^2 = 1/12$——与公式 $(b-a)^2/12 = 1/12$ 一致 ✓',
        formula: '\\mathrm{Var}(X) = \\mathrm{E}[X^2] - (\\mathrm{E}[X])^2 = \\int_{-\\infty}^{+\\infty} x^2 f(x)\\,dx - \\left(\\int_{-\\infty}^{+\\infty} x f(x)\\,dx\\right)^2',
        tip: '标准化变换：若 $X \\sim N(\\mu,\\sigma^2)$，令 $Z = (X-\\mu)/\\sigma$，则 $Z \\sim N(0,1)$。用线性性质：$\\mathrm{E}[Z]=0$，$\\mathrm{Var}(Z)=1$。',
      },
      {
        title: '随机变量的函数变换——CDF 法（万能）',
        body: '**问题**：已知 $X$ 的 PDF，求 $Y = g(X)$ 的 PDF。\n\n**CDF 法（三步）**：\n1. 确定 $Y$ 的取值范围\n2. 求 $F_Y(y) = P(Y \\leq y) = P(g(X) \\leq y)$，化为 $X$ 的不等式后用 $F_X$ 表示\n3. 对 $y$ 求导：$f_Y(y) = F_Y\'(y)$\n\n**例**：$X \\sim U(0,1)$，$Y = X^2$。\n- $Y$ 的范围：$y \\in [0,1]$\n- $F_Y(y) = P(X^2 \\leq y) = P(X \\leq \\sqrt{y}) = \\sqrt{y}$（因 $X \\in [0,1]$）\n- $f_Y(y) = F_Y\'(y) = \\frac{1}{2\\sqrt{y}}$（$y \\in (0,1]$）',
        formula: 'f_Y(y) = F_Y\'(y), \\quad F_Y(y) = P(g(X) \\leq y)',
        steps: [
          '注意：$y = 0^+$ 时 $f_Y \\to +\\infty$——PDF 可以无界，只要积分仍为 1',
          '验证：$\\int_0^1 \\frac{1}{2\\sqrt{y}}\\,dy = [\\sqrt{y}]_0^1 = 1$ ✓',
        ],
        tip: 'CDF 法是最安全的方法，适用于任何 $g$（单调、非单调均可）。只有 $g$ 严格单调时才能用简洁的 Jacobian 公式。',
      },
      {
        title: '单调变换的 Jacobian 公式',
        body: '当 $g(x)$ 严格单调可微时，有更简洁的**换元公式**（类比积分换元）：\n\n反函数 $x = g^{-1}(y)$，则：\n\n$f_Y(y) = f_X(g^{-1}(y)) \\cdot \\left|\\frac{dg^{-1}}{dy}\\right|$\n\n**直觉**：变量变换时，"概率质量"不变，但区间长度变了（Jacobian 补偿这个伸缩）。\n\n**例**：$X \\sim \\mathrm{Exp}(\\lambda)$，$Y = \\sqrt{X}$（单调增）。$g^{-1}(y) = y^2$，$|(g^{-1})\'(y)| = 2y$。\n$f_Y(y) = \\lambda e^{-\\lambda y^2} \\cdot 2y = 2\\lambda y e^{-\\lambda y^2}$（$y > 0$）——这是瑞利分布。',
        formula: 'f_Y(y) = f_X(g^{-1}(y)) \\cdot \\left|\\frac{dg^{-1}(y)}{dy}\\right|',
        tip: '非单调情形（如 $Y = X^2$ 且 $X$ 可正可负）：对每个 $y$ 的所有反根 $x_k$ 分别套公式，再相加。',
      },
      {
        title: '指数分布的无记忆性（连续版本）',
        body: '指数分布的最重要特性：$P(X > s+t \\mid X > s) = P(X > t)$\n\n**证明**：\n$P(X > s+t \\mid X > s) = \\frac{P(X > s+t)}{P(X > s)} = \\frac{e^{-\\lambda(s+t)}}{e^{-\\lambda s}} = e^{-\\lambda t} = P(X > t)$ ✓\n\n**直觉**：设 $X$ 为设备寿命。已知设备已正常运行了 $s$ 小时，此后剩余寿命的分布与全新设备一样——没有"老化效应"。\n\n无记忆性是指数分布在连续分布中的唯一特征（离散版本是几何分布）。',
        formula: 'P(X > s+t \\mid X > s) = P(X > t), \\quad X \\sim \\mathrm{Exp}(\\lambda)',
        reveal: {
          q: '$X \\sim \\mathrm{Exp}(2)$，已知 $X > 1$，求 $P(X > 1.5 \\mid X > 1)$。',
          a: '由无记忆性：$P(X > 1.5 \\mid X > 1) = P(X > 0.5) = e^{-2 \\times 0.5} = e^{-1} \\approx 0.368$。注意差值 $1.5 - 1 = 0.5$，等于新的等待时间。',
        },
      },
    ],
    questions: [
      {
        type: 'choice',
        prompt: '$X \\sim U(2, 8)$，则 $\\mathrm{E}[X]$ 和 $\\mathrm{Var}(X)$ 分别等于：',
        options: [
          '$E = 5,\\ \\mathrm{Var} = 3$',
          '$E = 5,\\ \\mathrm{Var} = 36/12 = 3$',
          '$E = 5,\\ \\mathrm{Var} = 36$',
          '$E = 4,\\ \\mathrm{Var} = 3$',
        ],
        answer: 0,
        explain: '$\\mathrm{E}[X] = (2+8)/2 = 5$；$\\mathrm{Var}(X) = (8-2)^2/12 = 36/12 = 3$。选项 A 和 B 数值相同，选 A 表达更简洁。均匀分布记住两个公式：期望=中点，方差=$(b-a)^2/12$。',
      },
      {
        type: 'input',
        prompt: '$X \\sim \\mathrm{Exp}(4)$，求 $\\mathrm{E}[X]$（写分数或小数）。',
        accept: ['0.25', '1/4'],
        explain: '指数分布期望公式：$\\mathrm{E}[X] = 1/\\lambda = 1/4 = 0.25$。速率 $\\lambda=4$ 意味着平均每 $0.25$ 单位时间发生一次。',
      },
      {
        type: 'judge',
        prompt: '$X \\sim \\mathrm{Exp}(\\lambda)$ 的标准差等于其期望（即变异系数 $\\mathrm{CV} = \\sigma/\\mu = 1$）。',
        answer: true,
        explain: '$\\mathrm{E}[X] = 1/\\lambda$，$\\mathrm{Var}(X) = 1/\\lambda^2$，$\\sigma = 1/\\lambda$。因此 $\\sigma = \\mathrm{E}[X] = 1/\\lambda$，变异系数 $\\mathrm{CV} = \\sigma/\\mu = 1$——这是指数分布的特征性质。',
      },
      {
        type: 'choice',
        prompt: '$X \\sim U(0,1)$，令 $Y = -\\ln X$。$Y$ 服从什么分布？',
        options: [
          '$Y \\sim U(0,1)$',
          '$Y \\sim \\mathrm{Exp}(1)$',
          '$Y \\sim N(0,1)$',
          '$Y \\sim U(0,\\infty)$',
        ],
        answer: 1,
        explain: 'CDF 法：$F_Y(y) = P(-\\ln X \\leq y) = P(X \\geq e^{-y}) = 1 - e^{-y}$（$y \\geq 0$），这正是 $\\mathrm{Exp}(1)$ 的 CDF。因此 $Y \\sim \\mathrm{Exp}(1)$。这是逆变换采样的经典例子。',
      },
      {
        type: 'input',
        prompt: '$X \\sim U(0,1)$，$Y = X^2$，则 $f_Y(y) = $ ？（填写公式中的分子，即 $f_Y(y) = 1/($ \_\_ $)$，$y \\in (0,1]$）',
        accept: ['2√y', '2\\sqrt{y}', '2sqrt(y)'],
        explain: 'CDF 法：$F_Y(y) = \\sqrt{y}$，$f_Y(y) = F_Y\'(y) = \\frac{1}{2\\sqrt{y}}$，即分母为 $2\\sqrt{y}$。注意 $f_Y \\to \\infty$ 当 $y \\to 0^+$，但 $\\int_0^1 \\frac{1}{2\\sqrt{y}}\\,dy = 1$ ✓。',
      },
      {
        type: 'match',
        prompt: '将各分布与其期望 $\\mathrm{E}[X]$ 匹配。',
        left: ['$U(2, 6)$', '$\\mathrm{Exp}(0.5)$', '$N(3, 4)$'],
        right: ['$3$（正态分布参数直接给出均值）', '$4$（区间中点）', '$2$（$1/\\lambda$）'],
        explain: '$U(2,6)$：$\\mathrm{E}=(2+6)/2=4$；$\\mathrm{Exp}(0.5)$：$\\mathrm{E}=1/0.5=2$；$N(3,4)$（参数为 $\\mu=3, \\sigma^2=4$）：$\\mathrm{E}=3$。',
      },
      {
        type: 'judge',
        prompt: '已知 $X \\sim \\mathrm{Exp}(1)$，设备已运行了 3 小时。由无记忆性，未来再运行 2 小时不坏的概率等于全新设备运行 2 小时不坏的概率，即 $P(X > 2) = e^{-2}$。',
        answer: true,
        explain: '正确。无记忆性：$P(X > 3+2 \\mid X > 3) = P(X > 2) = e^{-1 \\times 2} = e^{-2}$。已经使用了 3 小时这一事实对未来寿命没有影响，剩余寿命仍服从 $\\mathrm{Exp}(1)$。',
      },
      {
        type: 'choice',
        prompt: '$X \\sim \\mathrm{Exp}(\\lambda)$，$Y = 2X+3$，则 $\\mathrm{Var}(Y)$ 等于：',
        options: ['$\\frac{4}{\\lambda^2}$', '$\\frac{2}{\\lambda^2}$', '$\\frac{4}{\\lambda^2} + 3$', '$\\frac{1}{\\lambda^2}$'],
        answer: 0,
        explain: '$\\mathrm{Var}(aX+b) = a^2 \\mathrm{Var}(X)$。这里 $a=2, b=3$，$\\mathrm{Var}(X)=1/\\lambda^2$，故 $\\mathrm{Var}(Y) = 4/\\lambda^2$。注意平移 $b=3$ 不影响方差。',
      },
    ],
  },
  {
    id: 't5-c',
    title: '标准正态与分位数',
    subtitle: '标准化是桥梁，$\\Phi$ 表查概率',
    intro: [
      {
        title: '正态分布：自然界最普遍的分布',
        body: '正态分布 $N(\\mu, \\sigma^2)$ 的 PDF：$f(x) = \\frac{1}{\\sqrt{2\\pi}\\sigma}\\exp\\left(-\\frac{(x-\\mu)^2}{2\\sigma^2}\\right)$\n\n**为什么正态分布如此普遍？** 中心极限定理（第 10 章）：$n$ 个独立同分布随机变量之和，无论原分布如何，当 $n \\to \\infty$ 时近似正态分布。\n\n**三参数直觉**：\n- $\\mu$ 控制分布的中心（左右平移）\n- $\\sigma$ 控制分布的宽窄（胖瘦）\n- $\\sigma$ 越大，分布越"分散"（峰值越低）',
        formula: 'f(x) = \\frac{1}{\\sqrt{2\\pi}\\sigma}\\exp\\left(-\\frac{(x-\\mu)^2}{2\\sigma^2}\\right)',
        tip: '正态分布关于 $x = \\mu$ 对称，期望=中位数=众数=$\\mu$，这三者相等是正态分布（以及所有对称单峰分布）的特征。',
      },
      {
        title: '标准正态与标准化',
        body: '**标准正态** $Z \\sim N(0,1)$：$\\mu=0, \\sigma=1$，PDF 为 $\\phi(z) = \\frac{1}{\\sqrt{2\\pi}}e^{-z^2/2}$，CDF 记为 $\\Phi(z)$。\n\n所有正态概率都可以转化为标准正态查表（或计算）：\n\n若 $X \\sim N(\\mu, \\sigma^2)$，令 $Z = \\frac{X - \\mu}{\\sigma}$，则 $Z \\sim N(0,1)$。\n\n**标准化的用途**：把任意正态 $X$ 的概率计算转化为查 $\\Phi$ 表：\n$P(a \\leq X \\leq b) = P\\left(\\frac{a-\\mu}{\\sigma} \\leq Z \\leq \\frac{b-\\mu}{\\sigma}\\right) = \\Phi\\left(\\frac{b-\\mu}{\\sigma}\\right) - \\Phi\\left(\\frac{a-\\mu}{\\sigma}\\right)$',
        formula: 'Z = \\frac{X - \\mu}{\\sigma} \\sim N(0,1)',
        steps: [
          '例：$X \\sim N(60, 100)$（$\\mu=60, \\sigma=10$）',
          '$P(50 \\leq X \\leq 70) = P(-1 \\leq Z \\leq 1) = 2\\Phi(1) - 1 \\approx 0.683$',
          '$P(X > 80) = P(Z > 2) = 1 - \\Phi(2) \\approx 0.023$',
        ],
        tip: '$\\Phi(-z) = 1 - \\Phi(z)$（对称性）。查表时若 $z < 0$，用 $1 - \\Phi(|z|)$。',
      },
      {
        title: '三个经验法则（$1\\sigma / 2\\sigma / 3\\sigma$ 规则）',
        body: '正态分布有三个极其重要的概率值，工程和数据科学中必记：\n\n$P(\\mu - \\sigma < X < \\mu + \\sigma) = P(-1 < Z < 1) = 2\\Phi(1) - 1 \\approx 68.3\\%$\n\n$P(\\mu - 2\\sigma < X < \\mu + 2\\sigma) = P(-2 < Z < 2) = 2\\Phi(2) - 1 \\approx 95.4\\%$\n\n$P(\\mu - 3\\sigma < X < \\mu + 3\\sigma) = P(-3 < Z < 3) = 2\\Phi(3) - 1 \\approx 99.7\\%$\n\n**应用**：质量控制中，产品参数落在 $\\mu \\pm 3\\sigma$ 之外的概率约 0.3%（"六西格玛"要求落在 $\\pm 6\\sigma$ 外概率极微）。',
        formula: 'P(|X - \\mu| < k\\sigma) = P(|Z| < k) = 2\\Phi(k) - 1',
        tip: '记忆口诀：$1\\sigma \\approx 68\\%$，$2\\sigma \\approx 95\\%$，$3\\sigma \\approx 99.7\\%$。考试中常考"落在均值 $\\pm k$ 个标准差内"的概率。',
      },
      {
        title: '分位数——逆问题',
        body: '"已知概率，求分位点"是正态分布的**逆问题**，用 $\\Phi$ 的反函数 $\\Phi^{-1}$（或 $z_\\alpha$ 记号）。\n\n**定义**：$p$ 分位数 $x_p$ 满足 $F(x_p) = p$，即 $P(X \\leq x_p) = p$。\n\n**常用分位数**（标准正态）：\n- $z_{0.025} = -1.96$（双尾 5% 检验用）\n- $z_{0.05} = -1.645$（单尾 5% 检验用）\n- $z_{0.975} = 1.96$（95% 置信区间用）\n\n一般正态分位数：$x_p = \\mu + \\sigma \\cdot \\Phi^{-1}(p)$（标准化的逆操作）。',
        formula: 'x_p = \\mu + \\sigma \\cdot \\Phi^{-1}(p)',
        steps: [
          '例：$X \\sim N(60, 100)$，求 $P(X \\leq x_{0.9}) = 0.9$ 的 $x_{0.9}$',
          '标准化：$P(Z \\leq (x_{0.9}-60)/10) = 0.9$，故 $(x_{0.9}-60)/10 = \\Phi^{-1}(0.9) \\approx 1.282$',
          '$x_{0.9} = 60 + 10 \\times 1.282 = 72.82$',
        ],
        tip: '偏度（$\\gamma_1$）和峰度（$\\gamma_2$）是衡量分布"形状"的更高阶描述：$\\gamma_1=0$ 表示对称，$\\gamma_2=0$ 表示正态峰度（超额峰度为 0）。',
      },
      {
        title: '正态分布的 MGF 与独立正态之和',
        body: '$N(\\mu, \\sigma^2)$ 的 MGF：$M_X(t) = e^{\\mu t + \\sigma^2 t^2/2}$\n\n**独立正态之和仍是正态**：若 $X_i \\sim N(\\mu_i, \\sigma_i^2)$ 相互独立，则：\n$\\sum_{i=1}^n a_i X_i \\sim N\\left(\\sum a_i \\mu_i,\\ \\sum a_i^2 \\sigma_i^2\\right)$\n\n这由 MGF 乘积法则直接得到：$M_{a_1X_1+a_2X_2}(t) = M_{X_1}(a_1 t) \\cdot M_{X_2}(a_2 t) = e^{(a_1\\mu_1+a_2\\mu_2)t + (a_1^2\\sigma_1^2+a_2^2\\sigma_2^2)t^2/2}$\n\n**深度学习联系**：回归模型假设 $y = f_\\theta(x) + \\varepsilon$，$\\varepsilon \\sim N(0, \\sigma^2)$，最大化似然等价于最小化 MSE（均方误差）。',
        formula: 'M_X(t) = e^{\\mu t + \\sigma^2 t^2/2}, \\quad X \\sim N(\\mu, \\sigma^2)',
        reveal: {
          q: '$X \\sim N(2, 9)$（$\\mu=2, \\sigma^2=9$），$Y = 3X - 1$，$Y$ 服从什么分布？',
          a: '$\\mathrm{E}[Y] = 3\\times2 - 1 = 5$，$\\mathrm{Var}(Y) = 3^2 \\times 9 = 81$，故 $Y \\sim N(5, 81)$（$\\sigma_Y = 9$）。正态分布经线性变换仍是正态分布。',
        },
      },
      {
        title: '概率积分变换——均匀分布的核心地位',
        body: '**定理**（概率积分变换）：若 $X$ 是连续随机变量，CDF 为 $F$，则 $U = F(X) \\sim U(0,1)$。\n\n**证明**：$P(U \\leq u) = P(F(X) \\leq u) = P(X \\leq F^{-1}(u)) = F(F^{-1}(u)) = u$，这正是 $U(0,1)$ 的 CDF ✓\n\n**逆变换采样应用**：若想从分布 $F$ 采样，只需先生成 $U \\sim U(0,1)$（计算机容易实现），再令 $X = F^{-1}(U)$，则 $X \\sim F$。\n\n例：指数分布采样——令 $U \\sim U(0,1)$，$X = -\\frac{1}{\\lambda}\\ln(1-U) \\sim \\mathrm{Exp}(\\lambda)$（因为 $F^{-1}(u) = -\\ln(1-u)/\\lambda$）。',
        formula: 'F(X) \\sim U(0,1) \\quad \\Leftrightarrow \\quad X = F^{-1}(U),\\ U \\sim U(0,1)',
        tip: '概率积分变换是连接所有连续分布的桥梁：任何连续分布都可以通过均匀分布生成，体现了均匀分布的基础地位。',
      },
    ],
    questions: [
      {
        type: 'choice',
        prompt: '$X \\sim N(50, 25)$（$\\mu=50, \\sigma=5$）。$P(X > 60)$ 用 $\\Phi$ 表示为：',
        options: [
          '$\\Phi(2)$',
          '$1 - \\Phi(2)$',
          '$\\Phi(-2)$',
          '$2 - \\Phi(2)$',
        ],
        answer: 1,
        explain: '标准化：$P(X > 60) = P(Z > (60-50)/5) = P(Z > 2) = 1 - P(Z \\leq 2) = 1 - \\Phi(2) \\approx 0.023$。注意 $\\Phi(-2) = 1-\\Phi(2)$（对称性），所以选项 A 和 C 数值等价，但选 B（$1-\\Phi(2)$）表达最清晰。',
      },
      {
        type: 'judge',
        prompt: '正态分布 $N(\\mu, \\sigma^2)$ 中，约 95.4% 的数据落在 $[\\mu-2\\sigma, \\mu+2\\sigma]$ 内。',
        answer: true,
        explain: '正确。$P(|X-\\mu| < 2\\sigma) = P(-2 < Z < 2) = 2\\Phi(2)-1 \\approx 0.954$。这是"$2\\sigma$ 经验法则"，工程统计和数据科学中极常用。',
      },
      {
        type: 'input',
        prompt: '$X \\sim N(100, 16)$（$\\mu=100, \\sigma=4$）。若 $P(X \\leq x_0) = 0.5$，则 $x_0$ 等于多少？',
        accept: ['100'],
        explain: '$P(X \\leq x_0) = 0.5$ 要求 $x_0$ 是中位数。正态分布的中位数等于均值 $\\mu = 100$（正态分布关于 $\\mu$ 对称）。',
      },
      {
        type: 'choice',
        prompt: '若 $X \\sim N(\\mu, \\sigma^2)$，$Y = 2X - 3$，则 $Y$ 服从什么分布？',
        options: [
          '$N(2\\mu-3, 4\\sigma^2)$',
          '$N(2\\mu-3, 2\\sigma^2)$',
          '$N(2\\mu, \\sigma^2)$',
          '$N(2\\mu-3, \\sigma^2)$',
        ],
        answer: 0,
        explain: '正态分布的线性变换仍是正态：$\\mathrm{E}[Y] = 2\\mu-3$，$\\mathrm{Var}(Y) = 4\\sigma^2$。故 $Y \\sim N(2\\mu-3, 4\\sigma^2)$。注意方差变为 $a^2\\sigma^2 = 4\\sigma^2$，系数 $a=2$ 要平方。',
      },
      {
        type: 'match',
        prompt: '将正态分布的分位数与对应的尾概率匹配（设 $Z \\sim N(0,1)$）。',
        left: ['$\\Phi(1.96) \\approx 0.975$', '$P(Z > 1.645) \\approx 0.05$', '$P(-1 < Z < 1) \\approx 0.683$'],
        right: [
          '$1\\sigma$ 经验法则：均值附近 68.3%',
          '单尾 5% 显著性水平的临界值',
          '95% 置信区间常用的 $z$ 值',
        ],
        explain: '$\\Phi(1.96)=0.975$：双尾 95% 区间用 $\\pm 1.96$（置信区间）；$P(Z>1.645)=0.05$：单尾 5% 检验临界值；$P(-1<Z<1)=0.683$：$1\\sigma$ 经验法则。',
      },
      {
        type: 'judge',
        prompt: '若 $U \\sim U(0,1)$，令 $X = -\\ln(1-U)$，则 $X \\sim \\mathrm{Exp}(1)$。',
        answer: true,
        explain: '正确。这是逆变换采样：$\\mathrm{Exp}(1)$ 的 CDF 为 $F(x) = 1-e^{-x}$，反函数 $F^{-1}(u) = -\\ln(1-u)$。令 $X = F^{-1}(U)$，则 $P(X \\leq x) = P(U \\leq 1-e^{-x}) = 1-e^{-x}$，正是 $\\mathrm{Exp}(1)$ 的 CDF ✓。',
      },
      {
        type: 'input',
        prompt: '$X \\sim N(60, 100)$（$\\mu=60, \\sigma=10$），回归模型的 MSE 损失为 $\\mathrm{Var}(X) = $ ？',
        accept: ['100'],
        explain: '$N(60, 100)$ 中，第二个参数是方差 $\\sigma^2 = 100$。深度学习中，若目标变量服从 $N(\\mu, \\sigma^2)$，MSE 损失对应噪声方差 $\\sigma^2$，即 $\\mathrm{Var}(X) = 100$，对应噪声标准差 $\\sigma=10$。',
      },
      {
        type: 'choice',
        prompt: '以下哪项关于正态分布的叙述是错误的？',
        options: [
          '正态分布关于均值 $\\mu$ 完全对称',
          '正态分布的 PDF $f(x)$ 在 $x = \\mu$ 处取最大值',
          '两个独立正态分布之差仍是正态分布',
          '正态分布的 MGF 在所有 $t$ 处都存在，且 MGF 不存在有限值',
        ],
        answer: 3,
        explain: '选项 D 错误。$N(\\mu, \\sigma^2)$ 的 MGF 为 $M_X(t) = e^{\\mu t + \\sigma^2 t^2/2}$，对所有实数 $t$ 都存在且有限（是 $t$ 的有限实值函数）。选项 A、B、C 均正确（差 = 加权和，系数为 $\\pm1$，仍是正态）。',
      },
    ],
  },
]
