export const LESSONS = [
  {
    id: 't6-a',
    title: '联合分布与边缘分布',
    subtitle: '联合是全貌，边缘是投影，积分掉另一个变量',
    intro: [
      {
        title: '为什么要研究多维随机变量？',
        body: '一维随机变量只能描述单个量的随机性，但现实中的量往往成对甚至成组出现：身高与体重、图像的亮度与对比度、两只股票的收益。\n\n这些变量之间存在关联，必须用**联合分布**来完整描述，否则丢失了变量间相关性的全部信息。\n\n辛普森悖论警示：只看边缘分布（单个变量），可能得到与联合分布完全相反的结论。两个医院分组比较，每组都是 A 更好，合计却是 B 更好——这是因为"病情严重程度"这个第三变量同时影响了医院选择和治愈率，光看合计数掩盖了关键信息。',
        tip: '联合分布包含两个变量的全部信息；边缘分布是联合分布的"投影"，丢失了变量间的依赖信息。从边缘分布无法反推联合分布（独立时除外）。',
      },
      {
        title: '联合 PMF——离散情形',
        body: '二维离散随机变量 $(X, Y)$ 的**联合概率质量函数**（Joint PMF）：$p(x_i, y_j) = P(X = x_i, Y = y_j)$\n\n**两个必要条件**：\n1. 非负性：$p(x_i, y_j) \\geq 0$\n2. 归一化：$\\sum_i \\sum_j p(x_i, y_j) = 1$\n\n**边缘 PMF**（"积分掉另一个变量"的离散版本）：\n- $p_X(x_i) = \\sum_j p(x_i, y_j)$（对 $Y$ 所有取值求和）\n- $p_Y(y_j) = \\sum_i p(x_i, y_j)$（对 $X$ 所有取值求和）\n\n联合分布表中，每行之和 = 该行 $X$ 值的边缘概率；每列之和 = 该列 $Y$ 值的边缘概率。',
        formula: 'p_X(x_i) = \\sum_j p(x_i, y_j), \\quad p_Y(y_j) = \\sum_i p(x_i, y_j)',
        tip: '联合分布表的"行和"给 $X$ 的边缘，"列和"给 $Y$ 的边缘——就像行列汇总一样直观。',
      },
      {
        title: '联合 PDF——连续情形',
        body: '二维连续随机变量 $(X, Y)$ 的**联合概率密度函数**（Joint PDF）$f(x,y)$ 满足：\n$P((X,Y) \\in D) = \\iint_D f(x,y)\\,dx\\,dy$\n\n**归一化**：$\\int_{-\\infty}^{+\\infty}\\int_{-\\infty}^{+\\infty} f(x,y)\\,dx\\,dy = 1$\n\n**边缘 PDF**（积分掉另一个变量）：\n- $f_X(x) = \\int_{-\\infty}^{+\\infty} f(x,y)\\,dy$\n- $f_Y(y) = \\int_{-\\infty}^{+\\infty} f(x,y)\\,dx$\n\n**关键陷阱**：积分限由 $f(x,y)$ 的定义域决定，不一定是 $(-\\infty, +\\infty)$！三角形定义域 $\\{0 \\leq x \\leq y \\leq 1\\}$ 中，固定 $x$ 时 $y$ 从 $x$ 到 $1$；固定 $y$ 时 $x$ 从 $0$ 到 $y$。',
        formula: 'f_X(x) = \\int_{-\\infty}^{+\\infty} f(x,y)\\,dy, \\quad f_Y(y) = \\int_{-\\infty}^{+\\infty} f(x,y)\\,dx',
        steps: [
          '**先画出定义域**，固定某个变量画一条竖线（或横线），读出另一变量的积分范围',
          '例：$f(x,y) = 6x$，$0 \\leq x \\leq y \\leq 1$',
          '固定 $x$（竖线），$y$ 从 $x$ 到 $1$：$f_X(x) = \\int_x^1 6x\\,dy = 6x(1-x)$',
          '固定 $y$（横线），$x$ 从 $0$ 到 $y$：$f_Y(y) = \\int_0^y 6x\\,dx = 3y^2$',
        ],
        tip: '每次做边缘分布，先画定义域图，否则积分限极易出错。',
      },
      {
        title: '独立性的判断',
        body: '$X$ 和 $Y$ **相互独立**当且仅当：联合分布等于边缘分布的乘积，**且定义域为矩形**。\n\n- 离散型：$p(x_i, y_j) = p_X(x_i) \\cdot p_Y(y_j)$ 对所有 $i, j$ 成立\n- 连续型：$f(x,y) = f_X(x) \\cdot f_Y(y)$ 对几乎所有 $(x,y)$ 成立\n\n**三角形/非矩形定义域直接判不独立**：若 $X$ 的取值范围依赖于 $Y$ 的取值（或反之），则一定不独立，不必进一步验证。\n\n**例**：$f(x,y) = 2e^{-(2x+y)}$（$x \\geq 0, y \\geq 0$），则 $f_X(x) = 2e^{-2x}$，$f_Y(y) = e^{-y}$，$f_X(x) \\cdot f_Y(y) = 2e^{-2x} \\cdot e^{-y} = f(x,y)$，且定义域 $[0,\\infty) \\times [0,\\infty)$ 是矩形，故 $X, Y$ **独立**。',
        formula: 'f(x,y) = f_X(x) \\cdot f_Y(y) \\text{ 对所有 } (x,y)\\text{ 成立，且定义域为矩形} \\Leftrightarrow X,Y \\text{ 独立}',
        tip: '验证独立性：先看定义域（矩形 ✓ / 三角形 ✗），再验证乘积分解。两个条件缺一不可。',
      },
      {
        title: '归一化求常数——含参数联合 PDF',
        body: '设 $f(x,y) = c \\cdot e^{-(2x+y)}$，$x \\geq 0, y \\geq 0$，求常数 $c$。\n\n用归一化条件：$\\iint f\\,dx\\,dy = 1$',
        formula: 'c \\int_0^{\\infty} e^{-2x}\\,dx \\cdot \\int_0^{\\infty} e^{-y}\\,dy = c \\cdot \\frac{1}{2} \\cdot 1 = \\frac{c}{2} = 1 \\implies c = 2',
        steps: [
          '定义域 $x \\geq 0, y \\geq 0$ 是矩形，可以分拆为 $x, y$ 各自的积分乘积',
          '$\\int_0^{\\infty} e^{-2x}\\,dx = 1/2$，$\\int_0^{\\infty} e^{-y}\\,dy = 1$',
          '$c \\cdot (1/2) \\cdot 1 = 1 \\Rightarrow c = 2$',
          '验证：$f(x,y) = 2e^{-(2x+y)} = 2e^{-2x} \\cdot e^{-y} = f_X(x) \\cdot f_Y(y)$，且定义域矩形，故 $X,Y$ 独立 ✓',
        ],
        tip: '当联合 PDF 在矩形定义域上可写成 $g(x) \\cdot h(y)$ 的乘积形式，则归一化可以分拆：$c_g \\cdot c_h = 1$，极大简化计算。',
      },
      {
        title: '易错点与思考路标',
        body: '**易错点 1**：积分限错误——非矩形定义域求边缘时，要用图形确定积分范围，不要一律积到 $\\infty$。\n\n**易错点 2**：定义域不是矩形，就算联合 PDF 能写成 $g(x)h(y)$ 形式，$X,Y$ 也不独立——独立的充要条件要求定义域是矩形。\n\n**易错点 3**：从边缘分布无法确定联合分布（除非已知独立）。两个相同的边缘分布可以对应无穷多种联合分布。',
        reveal: {
          q: '$f(x,y) = 6x$（$0 \\leq x \\leq y \\leq 1$）。判断 $X, Y$ 是否独立，并说明理由。',
          a: '不独立。理由一：定义域 $\\{0 \\leq x \\leq y \\leq 1\\}$ 是三角形（非矩形），直接判不独立。理由二：$f_X(x) = 6x(1-x)$，$f_Y(y) = 3y^2$，$f_X(x) \\cdot f_Y(y) = 18x(1-x)y^2 \\neq 6x = f(x,y)$。',
        },
      },
    ],
    questions: [
      {
        type: 'judge',
        prompt: '若联合 PDF $f(x,y)$ 的定义域是三角形区域（如 $0 \\leq x \\leq y \\leq 1$），则 $X$ 与 $Y$ 一定不独立，无需进一步验证乘积分解。',
        answer: true,
        explain: '正确。独立性要求 $X$ 的取值范围与 $Y$ 的取值无关（以及反之）。三角形定义域中，$X$ 的上界依赖于 $Y$（$x \\leq y$），说明 $X$ 和 $Y$ 的取值相互制约，故一定不独立。',
      },
      {
        type: 'choice',
        prompt: '设 $f(x,y) = c e^{-3x-2y}$，$x \\geq 0, y \\geq 0$。求常数 $c$。',
        options: ['$c = 2$', '$c = 5$', '$c = 6$', '$c = 1/6$'],
        answer: 2,
        explain: '$\\iint c e^{-3x-2y}\\,dx\\,dy = c \\cdot \\frac{1}{3} \\cdot \\frac{1}{2} = \\frac{c}{6} = 1$，故 $c = 6$。定义域矩形，积分可分拆：$\\int_0^\\infty e^{-3x}\\,dx = 1/3$，$\\int_0^\\infty e^{-2y}\\,dy = 1/2$。',
      },
      {
        type: 'input',
        prompt: '设联合 PMF 表为 $p(0,0)=0.1, p(0,1)=0.3, p(1,0)=0.2, p(1,1)=0.4$。求 $P(X=1)$（写小数）。',
        accept: ['0.6'],
        explain: '$P(X=1) = p_X(1) = p(1,0) + p(1,1) = 0.2 + 0.4 = 0.6$。边缘 PMF = 对另一变量所有取值求和（即对该行/列求和）。',
      },
      {
        type: 'choice',
        prompt: '设 $f(x,y) = 6x$（$0 \\leq x \\leq y \\leq 1$），求 $f_X(x)$（$0 \\leq x \\leq 1$）。',
        options: [
          '$6x$',
          '$6x(1-x)$',
          '$3x^2$',
          '$3(1-x^2)$',
        ],
        answer: 1,
        explain: '固定 $x$，$y$ 从 $x$ 到 $1$：$f_X(x) = \\int_x^1 6x\\,dy = 6x \\cdot (1-x) = 6x(1-x)$。注意积分下限是 $x$（不是 $0$），因为定义域要求 $y \\geq x$。',
      },
      {
        type: 'judge',
        prompt: '已知 $X$ 的边缘分布为 $\\mathrm{Exp}(2)$，$Y$ 的边缘分布为 $\\mathrm{Exp}(1)$，则联合分布是 $f(x,y) = 2e^{-2x} \\cdot e^{-y}$。',
        answer: false,
        explain: '错误。从边缘分布无法唯一确定联合分布——给定相同的边缘分布，可以有无穷多种联合分布（不同的依赖结构）。只有在 $X, Y$ 独立的前提下，才有 $f(x,y) = f_X(x) \\cdot f_Y(y)$。',
      },
      {
        type: 'match',
        prompt: '将边缘分布的计算方法与对应的操作匹配。',
        left: ['求 $f_X(x)$（连续型）', '求 $p_X(x_i)$（离散型）', '求 $f_Y(y)$（连续型）'],
        right: [
          '对 $x$ 所有取值求和：$\\sum_i p(x_i, y_j)$',
          '对 $y$ 积分：$\\int f(x,y)\\,dy$',
          '对 $x$ 积分：$\\int f(x,y)\\,dx$',
        ],
        explain: '$f_X(x)$：对 $y$ 积分（积分掉 $y$）；$p_X(x_i)$：对 $j$ 求和（求和掉 $y$ 的下标）；$f_Y(y)$：对 $x$ 积分（积分掉 $x$）。口诀：要求谁的边缘，就把另一个变量"消除"。',
      },
      {
        type: 'choice',
        prompt: '设 $f(x,y)$ 的定义域为矩形 $[0,1] \\times [0,1]$，且 $f(x,y) = f_X(x) \\cdot f_Y(y)$ 对所有 $(x,y) \\in [0,1]^2$ 成立。以下哪项正确？',
        options: [
          '$X$ 与 $Y$ 一定独立',
          '$X$ 与 $Y$ 一定不独立',
          '无法判断，还需要更多条件',
          '只有当 $f_X$ 和 $f_Y$ 都是均匀分布时才独立',
        ],
        answer: 0,
        explain: '定义域是矩形，且联合 PDF 等于边缘 PDF 的乘积——这两个条件同时满足，则 $X$ 与 $Y$ 独立。这正是独立性的定义（充要条件）。',
      },
      {
        type: 'input',
        prompt: '设 $f(x,y) = 2e^{-(2x+y)}$（$x \\geq 0, y \\geq 0$）。$X$ 的边缘分布是什么？（填写分布名称和参数，如"Exp(2)"）',
        accept: ['Exp(2)', 'Exp（2）', '指数分布(2)', '指数(2)'],
        explain: '$f_X(x) = \\int_0^\\infty 2e^{-(2x+y)}\\,dy = 2e^{-2x} \\int_0^\\infty e^{-y}\\,dy = 2e^{-2x}$（$x \\geq 0$），这正是 $\\mathrm{Exp}(2)$ 的 PDF。',
      },
    ],
  },
  {
    id: 't6-b',
    title: '条件分布与条件期望',
    subtitle: '条件是"切片"，全期望是迭代平均',
    intro: [
      {
        title: '条件分布——从全局到局部',
        body: '"已知 $Y = y$，$X$ 的分布是什么？"——这就是**条件分布**。\n\n条件分布是贝叶斯推断、因果推理的核心工具，也是深度学习中序列生成、自回归模型的概率论基础。\n\n**几何直觉**：联合 PDF 是三维空间中的曲面。条件 PDF $f(x|y_0)$ 是在 $y = y_0$ 这个平面上"切"一刀，得到的截面曲线，再归一化到面积为 1。\n\n边缘 PDF $f_X(x)$ 则是把整个曲面沿 $y$ 轴方向"压扁"（投影），即积分。',
        tip: '条件 = 切片（归一化）；边缘 = 投影（积分）。这两种操作互补，共同还原联合分布的完整信息。',
      },
      {
        title: '条件 PMF 与条件 PDF 的计算',
        body: '**离散型条件 PMF**：\n$P(X = x_i \\mid Y = y_j) = \\dfrac{p(x_i, y_j)}{p_Y(y_j)}$（要求 $p_Y(y_j) > 0$）\n\n**连续型条件 PDF**：\n$f_{X \\mid Y}(x \\mid y) = \\dfrac{f(x,y)}{f_Y(y)}$（要求 $f_Y(y) > 0$）\n\n**必须验证**：$\\int_{-\\infty}^{+\\infty} f_{X|Y}(x|y)\\,dx = 1$（算完后验证归一化，能快速发现积分限错误）。\n\n**例**：$f(x,y) = 6x$（$0 \\leq x \\leq y \\leq 1$），$f_Y(y) = 3y^2$：\n$f(x|y) = 6x / 3y^2 = 2x/y^2$（$0 \\leq x \\leq y$）\n验证：$\\int_0^y 2x/y^2\\,dx = 1/y^2 \\cdot y^2 = 1$ ✓',
        formula: 'f_{X|Y}(x \\mid y) = \\frac{f(x,y)}{f_Y(y)}, \\quad \\int f_{X|Y}(x|y)\\,dx = 1',
        steps: [
          '第 1 步：求 $f_Y(y)$（积分掉 $x$）',
          '第 2 步：写条件 PDF：$f(x|y) = f(x,y)/f_Y(y)$',
          '第 3 步：验证 $\\int f(x|y)\\,dx = 1$（积分范围是 $x$ 在给定 $y$ 时的可取范围）',
        ],
        tip: '若 $X, Y$ 独立，则条件 PDF = 边缘 PDF（条件不改变分布），即 $f(x|y) = f_X(x)$。',
      },
      {
        title: '条件期望 $E[X|Y=y]$',
        body: '条件期望是在已知 $Y = y$ 的情况下，$X$ 的期望：\n\n连续型：$E[X|Y=y] = \\int x \\cdot f_{X|Y}(x|y)\\,dx$\n\n**关键特性**：$E[X|Y=y]$ 是 $y$ 的函数，不是一个数字！把 $y$ 当变量，$E[X|Y]$ 本身就是 $Y$ 的函数，因此也是一个随机变量。\n\n**例**：$f(x|y) = 2x/y^2$（$0 \\leq x \\leq y$）：\n$E[X|Y=y] = \\int_0^y x \\cdot \\frac{2x}{y^2}\\,dx = \\frac{2}{y^2} \\cdot \\frac{y^3}{3} = \\frac{2y}{3}$\n\n这是 $y$ 的线性函数——给定 $Y = y$，$X$ 的平均值是 $y$ 的 2/3。',
        formula: 'E[X|Y=y] = \\int_{-\\infty}^{+\\infty} x \\cdot f_{X|Y}(x|y)\\,dx',
        tip: '条件期望 $E[X|Y=y]$ 随 $y$ 变化——对不同的 $y$ 值，$X$ 的"平均水平"不同。这是回归函数的概率论本质。',
      },
      {
        title: '全期望公式（迭代期望）',
        body: '全期望公式是概率论中最重要的计算工具之一：\n\n$E[X] = E[E[X|Y]]$\n\n展开为：\n连续型：$E[X] = \\int E[X|Y=y] \\cdot f_Y(y)\\,dy$\n离散型：$E[X] = \\sum_j E[X|Y=y_j] \\cdot P(Y=y_j)$\n\n**直觉**：对每个 $Y=y$ 的"层"算 $X$ 的条件期望，再按 $Y$ 的概率对这些层加权平均，得到 $E[X]$。\n\n**例（工厂）**：两条生产线，选第一条（概率 0.6）合格率 80%，选第二条（0.4）合格率 90%。整体合格率 $= 0.8 \\times 0.6 + 0.9 \\times 0.4 = 0.84$——这正是全期望公式！',
        formula: 'E[X] = E[E[X|Y]] = \\int E[X|Y=y] \\cdot f_Y(y)\\,dy',
        steps: [
          '验证例题：$E[X|Y=y] = 2y/3$，$f_Y(y) = 3y^2$（$0 \\leq y \\leq 1$）',
          '$E[X] = \\int_0^1 \\frac{2y}{3} \\cdot 3y^2\\,dy = \\int_0^1 2y^3\\,dy = \\frac{y^4}{2}\\Big|_0^1 = \\frac{1}{2}$',
          '直接用 $f_X(x) = 6x(1-x)$ 验证：$E[X] = \\int_0^1 x \\cdot 6x(1-x)\\,dx = \\frac{1}{2}$ ✓',
        ],
        tip: '全期望公式用途：当直接求 $E[X]$ 困难，但 $E[X|Y=y]$ 好算时，先算条件期望，再用全期望公式。',
      },
      {
        title: '全方差公式',
        body: '**全方差公式**（Law of Total Variance）：$\\mathrm{Var}(X) = E[\\mathrm{Var}(X|Y)] + \\mathrm{Var}(E[X|Y])$\n\n**直觉**：总方差 = **组内方差的期望** + **组间方差**。\n- 第一项：每个"层"（给定 $Y$）内部的方差，取期望\n- 第二项：各层均值之间的波动\n\n**例（保险）**：低风险客户（占 70%）年均索赔 200 元，方差 1000；高风险客户（30%）均 800 元，方差 5000。\n组内方差期望 $= 0.7 \\times 1000 + 0.3 \\times 5000 = 2200$\n整体均值 $= 0.7 \\times 200 + 0.3 \\times 800 = 380$\n组间方差 $= 0.7(200-380)^2 + 0.3(800-380)^2 = 75600$\n总方差 $= 2200 + 75600 = 77800$',
        formula: '\\mathrm{Var}(X) = E[\\mathrm{Var}(X|Y)] + \\mathrm{Var}(E[X|Y])',
        reveal: {
          q: '一枚硬币正面概率 $p$ 未知，$p \\sim U(0,1)$（先验）。在给定 $p$ 时，掷 $n=10$ 次成功次数 $X|p \\sim B(10,p)$。求 $E[X]$。',
          a: '由全期望公式：$E[X] = E[E[X|p]] = E[10p] = 10 E[p] = 10 \\times 1/2 = 5$。条件期望 $E[X|p] = 10p$，再对先验分布 $p \\sim U(0,1)$ 取期望。',
        },
      },
      {
        title: '贝叶斯定理的密度形式',
        body: '贝叶斯定理在连续情形的密度版本：\n$f_{Y|X}(y|x) = \\dfrac{f_{X|Y}(x|y) \\cdot f_Y(y)}{f_X(x)}$\n\n即：后验 $\\propto$ 似然 × 先验\n\n**连接深度学习**：变分自编码器（VAE）的目标是学习 $p(\\mathbf{z}|\\mathbf{x})$（给定数据的潜变量后验），但直接计算 $p(\\mathbf{x}|\\mathbf{z}) \\cdot p(\\mathbf{z}) / p(\\mathbf{x})$ 中的 $p(\\mathbf{x})$ 很难算，所以 VAE 用变分推断近似后验——这是贝叶斯密度形式在深度学习中的直接应用。',
        formula: 'f_{Y|X}(y|x) = \\frac{f_{X|Y}(x|y) \\cdot f_Y(y)}{f_X(x)}',
        tip: '后验 $\\propto$ 似然 $\\times$ 先验——贝叶斯推断的核心口诀。$f_X(x)$ 是归一化常数（"证据"），常常不需要显式计算。',
      },
    ],
    questions: [
      {
        type: 'choice',
        prompt: '设 $f(x,y) = 6x$（$0 \\leq x \\leq y \\leq 1$），$f_Y(y) = 3y^2$。条件 PDF $f(x|y)$ 等于：',
        options: [
          '$\\dfrac{2x}{y^2}$（$0 \\leq x \\leq y$）',
          '$2xy$（$0 \\leq x \\leq y$）',
          '$\\dfrac{6x}{y}$（$0 \\leq x \\leq y$）',
          '$2x$（$0 \\leq x \\leq 1$）',
        ],
        answer: 0,
        explain: '$f(x|y) = f(x,y)/f_Y(y) = 6x/(3y^2) = 2x/y^2$（$0 \\leq x \\leq y$）。验证：$\\int_0^y 2x/y^2\\,dx = [x^2/y^2]_0^y = 1$ ✓。注意条件 PDF 的积分范围是 $0$ 到 $y$（不是 $0$ 到 $1$）。',
      },
      {
        type: 'input',
        prompt: '设 $f(x|y) = 2x/y^2$（$0 \\leq x \\leq y$）。求 $E[X|Y=y]$（用 $y$ 表示）。',
        accept: ['2y/3', '(2/3)y', '2y／3'],
        explain: '$E[X|Y=y] = \\int_0^y x \\cdot \\frac{2x}{y^2}\\,dx = \\frac{2}{y^2} \\int_0^y x^2\\,dx = \\frac{2}{y^2} \\cdot \\frac{y^3}{3} = \\frac{2y}{3}$。条件期望是 $y$ 的函数，随 $y$ 增大而增大——当 $Y$ 更大时，$X$ 的平均值也更大（因为定义域是 $x \\leq y$）。',
      },
      {
        type: 'judge',
        prompt: '若 $X$ 和 $Y$ 独立，则对任意 $y$，条件期望 $E[X|Y=y] = E[X]$（条件不改变期望）。',
        answer: true,
        explain: '正确。若 $X, Y$ 独立，则 $f(x|y) = f_X(x)$（条件 PDF = 边缘 PDF），因此 $E[X|Y=y] = \\int x f_X(x)\\,dx = E[X]$，与 $y$ 无关。独立性的本质就是"已知 $Y$ 不改变 $X$ 的分布"。',
      },
      {
        type: 'choice',
        prompt: '某保险公司有低风险客户（概率 0.7，条件期望索赔 200）和高风险客户（概率 0.3，条件期望索赔 800）。全期望公式给出整体期望索赔额等于：',
        options: ['$\\frac{200+800}{2} = 500$', '$0.7 \\times 200 + 0.3 \\times 800 = 380$', '$0.7 \\times 800 + 0.3 \\times 200 = 620$', '$200 \\times 800 = 160000$'],
        answer: 1,
        explain: '全期望公式：$E[X] = \\sum_j E[X|Y=y_j] P(Y=y_j) = 200 \\times 0.7 + 800 \\times 0.3 = 140 + 240 = 380$。不能简单取算术平均（那是假设两类客户等概率的情况）。',
      },
      {
        type: 'match',
        prompt: '将各概念与其正确定义匹配。',
        left: ['条件 PDF $f(x|y)$', '全期望公式', '条件期望 $E[X|Y]$', '全方差公式'],
        right: [
          '$\\mathrm{Var}(X) = E[\\mathrm{Var}(X|Y)] + \\mathrm{Var}(E[X|Y])$',
          '$E[X] = E[E[X|Y]]$（迭代期望）',
          '$f(x,y)/f_Y(y)$（联合除以边缘）',
          '$Y$ 的函数，是随机变量',
        ],
        explain: '条件 PDF = 联合/边缘；条件期望 $E[X|Y]$ 是 $Y$ 的函数（随机变量）；全期望公式 $E[X]=E[E[X|Y]]$；全方差公式将总方差分解为组内+组间。',
      },
      {
        type: 'judge',
        prompt: '条件期望 $E[X|Y=y]$ 对固定的 $y$ 值来说是一个确定的数；但 $E[X|Y]$（不固定 $y$）是一个随机变量。',
        answer: true,
        explain: '正确。对固定的 $y$，$E[X|Y=y] = \\int x f(x|y)\\,dx$ 是一个确定的数值（关于 $y$ 的函数的值）。但当 $y$ 本身是随机变量 $Y$ 时，$E[X|Y]$ 就成了 $Y$ 的函数，因而是一个随机变量。全期望公式 $E[X] = E[E[X|Y]]$ 对这个随机变量再取期望，才得到 $E[X]$。',
      },
      {
        type: 'input',
        prompt: '条件 PDF $f(x|y) = 2x/y^2$（$0 \\leq x \\leq y$），验证它是合法 PDF：$\\int_0^y f(x|y)\\,dx = $ ？',
        accept: ['1'],
        explain: '$\\int_0^y \\frac{2x}{y^2}\\,dx = \\frac{2}{y^2} \\cdot \\frac{x^2}{2}\\Big|_0^y = \\frac{2}{y^2} \\cdot \\frac{y^2}{2} = 1$ ✓。条件 PDF 必须对 $x$ 的合法范围积分等于 1（归一化），这是验证计算是否正确的标准检验步骤。',
      },
      {
        type: 'choice',
        prompt: '下列关于全方差公式 $\\mathrm{Var}(X) = E[\\mathrm{Var}(X|Y)] + \\mathrm{Var}(E[X|Y])$ 的叙述，哪项正确？',
        options: [
          '第一项 $E[\\mathrm{Var}(X|Y)]$ 是"组间方差"',
          '第二项 $\\mathrm{Var}(E[X|Y])$ 是"组内方差期望"',
          '第一项是"组内方差期望"，第二项是"组间方差"',
          '两项都是"组间方差"，总和等于总方差',
        ],
        answer: 2,
        explain: '第一项 $E[\\mathrm{Var}(X|Y)]$：先算每个 $Y=y$ 层内 $X$ 的方差，再取期望——这是"组内方差的期望"。第二项 $\\mathrm{Var}(E[X|Y])$：各层的条件均值 $E[X|Y=y]$ 之间的波动——这是"组间方差"。总方差 = 组内方差期望 + 组间方差。',
      },
    ],
  },
  {
    id: 't6-c',
    title: '协方差、相关系数与协方差矩阵',
    subtitle: '协方差度量线性联动，相关系数消除量纲',
    intro: [
      {
        title: '为什么需要协方差？',
        body: '期望和方差描述单个随机变量的"位置"和"离散程度"，但无法刻画两个变量之间的**线性关联**。\n\n**直觉**：股票 A 和股票 B 同涨同跌（正相关），还是一涨一跌（负相关），还是毫无关系（不相关）？这个信息在期望和方差中完全缺失。\n\n**协方差**就是量化这种线性关联的工具：\n- $\\mathrm{Cov}(X,Y) > 0$：$X$ 大时 $Y$ 趋向大，正相关\n- $\\mathrm{Cov}(X,Y) < 0$：$X$ 大时 $Y$ 趋向小，负相关\n- $\\mathrm{Cov}(X,Y) = 0$：线性不相关（注意：不等于独立！）',
        tip: '协方差的符号说明线性关联的方向；大小说明线性关联的强度（但受量纲影响，不能跨场景比较）。',
      },
      {
        title: '协方差的定义与计算公式',
        body: '**定义**：$\\mathrm{Cov}(X,Y) = E[(X-\\mu_X)(Y-\\mu_Y)]$\n\n**实用计算公式**（优先使用）：$\\mathrm{Cov}(X,Y) = E[XY] - E[X] \\cdot E[Y]$\n\n**推导**：$E[(X-\\mu_X)(Y-\\mu_Y)] = E[XY] - \\mu_X E[Y] - \\mu_Y E[X] + \\mu_X\\mu_Y = E[XY] - \\mu_X\\mu_Y$\n\n**计算步骤**：\n1. 求 $E[X]$ 和 $E[Y]$（边缘分布或线性性质）\n2. 求 $E[XY]$（LOTUS：$\\iint xy \\cdot f(x,y)\\,dx\\,dy$，若独立则 $= E[X]E[Y]$）\n3. $\\mathrm{Cov}(X,Y) = E[XY] - E[X]E[Y]$',
        formula: '\\mathrm{Cov}(X,Y) = E[XY] - E[X] \\cdot E[Y]',
        steps: [
          '例：$f(x,y) = 6x$（$0 \\leq x \\leq y \\leq 1$），已知 $E[X]=1/2, E[Y]=3/4$',
          '$E[XY] = \\iint xy \\cdot 6x\\,dx\\,dy = \\int_0^1 \\int_0^y 6x^2 y\\,dx\\,dy = \\int_0^1 2y^4\\,dy = 2/5$',
          '$\\mathrm{Cov}(X,Y) = 2/5 - (1/2)(3/4) = 2/5 - 3/8 = 1/40$',
        ],
        tip: '若 $X, Y$ 独立，则 $E[XY] = E[X]E[Y]$，从而 $\\mathrm{Cov}(X,Y) = 0$。反之不成立。',
      },
      {
        title: '协方差的性质——线性运算规则',
        body: '协方差的重要性质（与线性代数中内积完全类比）：\n\n1. **对称性**：$\\mathrm{Cov}(X,Y) = \\mathrm{Cov}(Y,X)$\n2. **自协方差**：$\\mathrm{Cov}(X,X) = \\mathrm{Var}(X)$\n3. **线性性**：$\\mathrm{Cov}(aX+b, cY+d) = ac \\cdot \\mathrm{Cov}(X,Y)$（常数不影响）\n4. **双线性**：$\\mathrm{Cov}(X_1+X_2, Y) = \\mathrm{Cov}(X_1,Y) + \\mathrm{Cov}(X_2,Y)$\n5. **方差加法**：$\\mathrm{Var}(X+Y) = \\mathrm{Var}(X) + \\mathrm{Var}(Y) + 2\\mathrm{Cov}(X,Y)$\n\n**应用**：$Y = 2X+3$，则 $\\mathrm{Cov}(X,Y) = \\mathrm{Cov}(X, 2X+3) = 2\\mathrm{Cov}(X,X) = 2\\mathrm{Var}(X)$。',
        formula: '\\mathrm{Var}(X+Y) = \\mathrm{Var}(X) + \\mathrm{Var}(Y) + 2\\mathrm{Cov}(X,Y)',
        tip: '方差加法公式的一般形式：$\\mathrm{Var}(aX+bY) = a^2\\mathrm{Var}(X) + b^2\\mathrm{Var}(Y) + 2ab\\mathrm{Cov}(X,Y)$。独立时 $\\mathrm{Cov}=0$，退化为简单加法。',
      },
      {
        title: '相关系数——无量纲的协方差',
        body: '协方差受量纲影响（$X$ 改用"千克"而非"克"，协方差变 1000 倍），不便比较。**相关系数**（Pearson 相关系数）通过除以各自的标准差消除量纲：\n\n$\\rho_{XY} = \\dfrac{\\mathrm{Cov}(X,Y)}{\\sigma_X \\sigma_Y}$\n\n**性质**：\n1. $-1 \\leq \\rho_{XY} \\leq 1$（有界，可跨场景比较）\n2. $|\\rho_{XY}| = 1$ 当且仅当 $Y = aX + b$（严格线性关系）\n3. $\\rho_{XY} = 0$：线性不相关（但可能有非线性关系！）\n4. 无量纲，纯数',
        formula: '\\rho_{XY} = \\frac{\\mathrm{Cov}(X,Y)}{\\sigma_X \\sigma_Y} \\in [-1, 1]',
        steps: [
          '例：$\\mathrm{Cov}(X,Y) = 1/40$，$\\mathrm{Var}(X) = 1/20$，$\\mathrm{Var}(Y) = 3/80$',
          '$\\sigma_X = \\sqrt{1/20}$，$\\sigma_Y = \\sqrt{3/80}$',
          '$\\rho = \\frac{1/40}{\\sqrt{1/20 \\cdot 3/80}} = \\frac{1/40}{\\sqrt{3}/40} = \\frac{1}{\\sqrt{3}} \\approx 0.577$',
        ],
        tip: '相关系数接近 $\\pm 1$：强线性关系；接近 0：弱线性关系（不代表无关）。$\\rho$ 只度量线性相关，无法捕捉非线性关系。',
      },
      {
        title: '不相关 $\\neq$ 独立——经典反例',
        body: '**独立 $\\Rightarrow$ 不相关**（协方差为 0），但**不相关 $\\not\\Rightarrow$ 独立**！\n\n**经典反例**：$X \\sim U(-1,1)$，$Y = X^2$。\n\n$E[X] = 0$，$E[XY] = E[X^3] = \\int_{-1}^1 x^3 \\cdot \\frac{1}{2}\\,dx = 0$（奇函数积分为 0）\n\n$\\mathrm{Cov}(X,Y) = 0 - 0 \\cdot E[Y] = 0$，但 $Y$ 完全由 $X$ 决定，是最强的依赖！\n\n**正态分布是唯一例外**：对联合正态 $(X,Y)$，$\\mathrm{Cov}(X,Y) = 0 \\Leftrightarrow X, Y$ 独立。\n\n**深度学习警示**：相关系数为 0 不能说明两个特征无关（可能有非线性依赖）。互信息 $I(X;Y) = 0$ 才等价于独立。',
        formula: '\\text{独立} \\Rightarrow \\mathrm{Cov}(X,Y)=0, \\quad \\mathrm{Cov}(X,Y)=0 \\not\\Rightarrow \\text{独立}',
        tip: '口诀：独立比不相关强。独立是"没有任何关系"，不相关是"没有线性关系"——前者蕴含后者，但反之不成立（正态例外）。',
      },
      {
        title: '协方差矩阵——多维情形与 PCA',
        body: '对 $n$ 维随机向量 $\\mathbf{X} = (X_1, \\ldots, X_n)^T$，**协方差矩阵**：\n$\\boldsymbol{\\Sigma}_{ij} = \\mathrm{Cov}(X_i, X_j)$\n对角元 $\\Sigma_{ii} = \\mathrm{Var}(X_i)$，非对角元 $\\Sigma_{ij} = \\mathrm{Cov}(X_i, X_j)$。\n\n**性质**：对称正半定（所有特征值 $\\geq 0$）。\n\n**PCA 联系**：对 $\\boldsymbol{\\Sigma}$ 做特征分解 $\\boldsymbol{\\Sigma} = V\\Lambda V^T$，特征向量 $V$ 是数据方差最大的方向（主轴），特征值 $\\Lambda$ 是各主轴上的方差。\n\n**白化**：$\\mathbf{Z} = \\boldsymbol{\\Sigma}^{-1/2}(\\mathbf{X}-\\boldsymbol{\\mu})$，使 $\\mathbf{Z} \\sim N(\\mathbf{0}, I)$，消除特征间线性相关。',
        formula: '\\boldsymbol{\\Sigma}_{ij} = \\mathrm{Cov}(X_i, X_j), \\quad \\boldsymbol{\\Sigma} = \\boldsymbol{\\Sigma}^T \\text{，正半定}',
        reveal: {
          q: '$\\mathrm{Var}(X)=4, \\mathrm{Var}(Y)=9, \\mathrm{Cov}(X,Y)=3$。求 $\\mathrm{Var}(2X-Y+1)$ 和 $\\rho_{XY}$。',
          a: '$\\mathrm{Var}(2X-Y+1) = 4\\mathrm{Var}(X) + \\mathrm{Var}(Y) - 2\\cdot 2 \\cdot \\mathrm{Cov}(X,Y) = 16 + 9 - 12 = 13$（常数 $+1$ 不影响方差）。$\\rho = 3/(\\sqrt{4}\\cdot\\sqrt{9}) = 3/6 = 0.5$。',
        },
      },
    ],
    questions: [
      {
        type: 'choice',
        prompt: '设 $\\mathrm{Var}(X) = 4$，$\\mathrm{Var}(Y) = 9$，$\\mathrm{Cov}(X,Y) = 3$。求 $\\mathrm{Var}(X+Y)$。',
        options: ['$13$', '$19$', '$25$', '$10$'],
        answer: 1,
        explain: '$\\mathrm{Var}(X+Y) = \\mathrm{Var}(X) + \\mathrm{Var}(Y) + 2\\mathrm{Cov}(X,Y) = 4 + 9 + 6 = 19$。不能只加两个方差——还要加两倍协方差（若 $X,Y$ 有正相关，它们一起波动，总和方差比独立时更大）。',
      },
      {
        type: 'input',
        prompt: '$X \\sim N(0,1)$，$Y = 2X+3$，求 $\\rho_{XY}$（写整数或分数）。',
        accept: ['1'],
        explain: '$\\mathrm{Cov}(X,Y) = \\mathrm{Cov}(X,2X+3) = 2\\mathrm{Var}(X) = 2$；$\\mathrm{Var}(Y) = 4\\mathrm{Var}(X) = 4$；$\\rho = 2/(1 \\cdot 2) = 1$。$\\rho=1$ 表示完全正线性相关，与 $Y=2X+3$ 的严格线性关系完全吻合。',
      },
      {
        type: 'judge',
        prompt: '若 $\\mathrm{Cov}(X,Y) = 0$，则 $X$ 与 $Y$ 一定相互独立。',
        answer: false,
        explain: '错误。不相关（$\\mathrm{Cov}=0$）不蕴含独立。经典反例：$X \\sim U(-1,1)$，$Y = X^2$，则 $\\mathrm{Cov}(X,Y) = 0$，但 $Y$ 完全由 $X$ 决定，二者不独立。正态分布是唯一例外：联合正态时，不相关 $\\Leftrightarrow$ 独立。',
      },
      {
        type: 'choice',
        prompt: '以下哪种情形下，$X$ 与 $Y$ 的相关系数 $|\\rho_{XY}| = 1$？',
        options: [
          '$X$ 与 $Y$ 独立',
          '$Y = X^2$（$X > 0$）',
          '$Y = -3X + 5$（严格线性关系）',
          '$Y = e^X$（指数变换）',
        ],
        answer: 2,
        explain: '$|\\rho_{XY}| = 1$ 当且仅当 $Y = aX + b$（严格线性关系）。独立时 $\\rho = 0$；$Y=X^2$ 是非线性，$\\rho$ 不一定为 $\\pm 1$；$Y=e^X$ 是单调非线性，$\\rho < 1$（虽然完全由 $X$ 决定，但不是线性关系）。',
      },
      {
        type: 'match',
        prompt: '将协方差的性质与正确公式匹配。',
        left: ['$\\mathrm{Cov}(X,X)$', '$\\mathrm{Cov}(aX,bY)$', '$\\mathrm{Cov}(X_1+X_2, Y)$', '$\\mathrm{Var}(X+Y)$'],
        right: [
          '$\\mathrm{Cov}(X_1,Y) + \\mathrm{Cov}(X_2,Y)$（双线性）',
          '$\\mathrm{Var}(X) + \\mathrm{Var}(Y) + 2\\mathrm{Cov}(X,Y)$',
          '$\\mathrm{Var}(X)$（自协方差）',
          '$ab\\,\\mathrm{Cov}(X,Y)$（线性性）',
        ],
        explain: '$\\mathrm{Cov}(X,X)=\\mathrm{Var}(X)$；$\\mathrm{Cov}(aX,bY)=ab\\mathrm{Cov}(X,Y)$；双线性；方差加法公式。',
      },
      {
        type: 'input',
        prompt: '设 $X,Y$ 独立，$E[X]=2, E[Y]=3, \\mathrm{Var}(X)=1, \\mathrm{Var}(Y)=4$。求 $\\mathrm{Var}(3X-2Y+1)$。',
        accept: ['25'],
        explain: '独立时 $\\mathrm{Cov}(X,Y)=0$，故 $\\mathrm{Var}(3X-2Y+1) = 9\\mathrm{Var}(X) + 4\\mathrm{Var}(Y) = 9\\times1 + 4\\times4 = 9+16=25$（常数 $+1$ 不影响方差；系数为 $-2$ 时平方仍是 $4$）。',
      },
      {
        type: 'judge',
        prompt: '协方差矩阵 $\\boldsymbol{\\Sigma}$ 是对称正半定矩阵，其所有特征值 $\\geq 0$。',
        answer: true,
        explain: '正确。$\\boldsymbol{\\Sigma}_{ij} = \\mathrm{Cov}(X_i,X_j) = \\boldsymbol{\\Sigma}_{ji}$（对称性）；对任意向量 $\\mathbf{v}$，$\\mathbf{v}^T\\boldsymbol{\\Sigma}\\mathbf{v} = \\mathrm{Var}(\\mathbf{v}^T\\mathbf{X}) \\geq 0$（正半定）。因此所有特征值 $\\geq 0$。若计算出负特征值，一定有错误。',
      },
      {
        type: 'choice',
        prompt: '下列关于"不相关"与"独立"关系的叙述，哪项是正确的？',
        options: [
          '对任何分布，不相关等价于独立',
          '独立一定不相关，不相关不一定独立',
          '不相关一定独立，独立不一定不相关',
          '对联合正态分布，不相关不蕴含独立',
        ],
        answer: 1,
        explain: '正确答案是 B。独立 $\\Rightarrow$ 不相关（$\\mathrm{Cov}=0$），这是普遍成立的。但不相关 $\\not\\Rightarrow$ 独立（可有非线性依赖，如 $Y=X^2$）。对联合正态分布，不相关 $\\Leftrightarrow$ 独立（这是正态的特殊性）——故选项 D 错误。',
      },
    ],
  },
]
