import type { Unit } from '../../types'

// 第六部分（高阶应用）：第18–20章
// u18 指数核·拉普拉斯·傅里叶 / u19 凸性·熵·概率尾 / u20 高级综合与展望
// 数学已核对：反常积分收敛域、Laplace 变换对、MGF、Chernoff/Hoeffding 尾界。

export const PART6_UNITS: Unit[] = [
  // ===================== 第18章 =====================
  {
    id: 'u18',
    title: '指数核 · Laplace · Fourier',
    color: '#d63031',
    icon: '📡',
    blurb: '用 $e^{-st}$ 衰减扫描、用 $e^{i\\omega t}$ 频率扫描，把微分变成代数。',
    lessons: [
      {
        id: 'u18-l1',
        title: 'Laplace 核与收敛域',
        subtitle: '衰减因子 $e^{-st}$ 如何压住远处贡献',
        questions: [
          {
            id: 'u18-l1-q1',
            type: 'choice',
            prompt: '常数函数 $f(t)=1$ 的 Laplace 变换 $\\int_0^{\\infty}e^{-st}\\,dt$ 等于？',
            options: ['$\\dfrac{1}{s}$', '$\\dfrac{1}{s^2}$', '$s$', '$e^{-s}$'],
            answer: 0,
            explain: '$\\int_0^{T}e^{-st}\\,dt=\\tfrac1s(1-e^{-sT})\\to\\tfrac1s$（当 $s>0$），故 $\\mathcal{L}\\{1\\}=1/s$。',
          },
          {
            id: 'u18-l1-q2',
            type: 'input',
            prompt: '$\\int_0^{\\infty}e^{-st}\\,dt=\\dfrac{1}{s}$ 成立的收敛条件是 $s>\\,?$（填一个数）',
            accept: ['0'],
            explain: '只有 $s>0$ 时 $e^{-sT}\\to0$，积分才收敛；$s\\le0$ 时发散。收敛域是结论的一部分。',
          },
          {
            id: 'u18-l1-q3',
            type: 'judge',
            prompt: '判断：Laplace 核 $e^{-st}$ 的作用是把远处（大 $t$）的贡献压低，从而让积分收敛。',
            answer: true,
            explain: '正是衰减因子让“拖到无穷远”的常值贡献被压成有限量，这是 Laplace 变换的核心机制。',
          },
          {
            id: 'u18-l1-q4',
            type: 'choice',
            prompt: '$\\mathcal{L}\\{e^{at}\\}=\\dfrac{1}{s-a}$ 的收敛域是？',
            options: ['$s>0$', '$s>a$', '$s<a$', '所有 $s$'],
            answer: 1,
            explain: '$e^{-st}e^{at}=e^{-(s-a)t}$，需 $s-a>0$ 即 $s>a$ 才衰减收敛。原函数的增长率 $a$ 把门槛从 $0$ 抬到 $a$。',
          },
          {
            id: 'u18-l1-q5',
            type: 'match',
            prompt: '把每个时域函数与它的 Laplace 变换配对：',
            left: ['$1$', '$t$', '$e^{at}$', '$\\delta(t)$'],
            right: ['$\\dfrac{1}{s}$', '$\\dfrac{1}{s^2}$', '$\\dfrac{1}{s-a}$', '$1$'],
            explain: '$1\\mapsto1/s$、$t\\mapsto1/s^2$、$e^{at}\\mapsto1/(s-a)$、冲激 $\\delta\\mapsto1$。',
          },
        ],
      },
      {
        id: 'u18-l2',
        title: 'Fourier 视角下的复指数',
        subtitle: '$e^{i\\omega t}$ 编码节奏与相位',
        questions: [
          {
            id: 'u18-l2-q1',
            type: 'choice',
            prompt: '复指数 $e^{i\\omega t}$ 用 Euler 公式展开等于？',
            options: [
              '$\\cos(\\omega t)+i\\sin(\\omega t)$',
              '$\\cos(\\omega t)-i\\sin(\\omega t)$',
              '$\\sin(\\omega t)+i\\cos(\\omega t)$',
              '$e^{\\omega t}$',
            ],
            answer: 0,
            explain: '$e^{i\\omega t}=\\cos(\\omega t)+i\\sin(\\omega t)$，一个复指数同时打包同频率的余弦与正弦。',
          },
          {
            id: 'u18-l2-q2',
            type: 'input',
            prompt: '复指数 $e^{i\\omega t}$ 的模长 $|e^{i\\omega t}|$ 等于？（填一个数）',
            accept: ['1'],
            explain: '$|e^{i\\omega t}|=1$ 恒定，所以它只旋转不放大——负责编码频率与相位，而非增长。',
          },
          {
            id: 'u18-l2-q3',
            type: 'judge',
            prompt: '判断：$\\dfrac{d}{dt}e^{i\\omega t}=i\\omega\\,e^{i\\omega t}$，即求导只是把频率 $i\\omega$ 提到前面。',
            answer: true,
            explain: '对它求导不会跳出这类函数族，频率直接变成乘法因子——这正是 Fourier 语言稳定的原因。',
          },
          {
            id: 'u18-l2-q4',
            type: 'choice',
            prompt: '用频率为 $\\omega$ 的核去比较信号 $e^{i\\omega_0 t}$，乘积 $e^{-i\\omega t}e^{i\\omega_0 t}$ 等于？',
            options: ['$e^{i(\\omega_0-\\omega)t}$', '$e^{i(\\omega_0+\\omega)t}$', '$e^{-i\\omega_0 t}$', '$1$'],
            answer: 0,
            explain: 'Fourier 分析关心的是“信号频率与扫描频率之差”$\\omega_0-\\omega$；两者一致时结构最稳定。',
          },
          {
            id: 'u18-l2-q5',
            type: 'match',
            prompt: '把每个指数核与它的主要角色配对：',
            left: ['$e^{-st}$', '$e^{i\\omega t}$', '$e^{At}$', '$e^{kt}$'],
            right: ['衰减扫描（Laplace 核）', '频率旋转（Fourier 核）', '矩阵演化算子', '增长/衰减模型'],
            explain: '同样是指数，角色不同：衰减扫描、频率旋转、系统演化、按比例变化。',
          },
          {
            id: 'u18-l2-q6',
            type: 'judge',
            prompt: '判断：$|e^{-t}|$ 随 $t$ 增大而减小，而 $|e^{it}|$ 始终为 $1$。',
            answer: true,
            explain: '$e^{-t}$ 是实指数衰减（控制长期响应），$e^{it}$ 是复指数旋转（编码频率），承担两种不同分析任务。',
          },
        ],
      },
      {
        id: 'u18-l3',
        title: '把微分变成代数',
        subtitle: '微分性质、卷积定理与初值问题',
        questions: [
          {
            id: 'u18-l3-q1',
            type: 'choice',
            prompt: 'Laplace 微分性质 $\\mathcal{L}\\{f\'(t)\\}$ 等于？',
            options: ['$sF(s)-f(0)$', '$sF(s)$', '$F(s)/s$', '$F(s)-f(0)$'],
            answer: 0,
            explain: '$\\mathcal{L}\\{f\'\\}=sF(s)-f(0)$：求导在 $s$ 域变成乘 $s$，且初值 $f(0)$ 自动进入代数方程。',
          },
          {
            id: 'u18-l3-q2',
            type: 'choice',
            prompt: '卷积定理说：时域卷积 $(f*g)(t)$ 在 $s$ 域里对应？',
            options: ['$F(s)\\cdot G(s)$', '$F(s)+G(s)$', '$F(s)/G(s)$', '$F(s)-G(s)$'],
            answer: 0,
            explain: '$\\mathcal{L}\\{f*g\\}=F(s)G(s)$：时域里一个积分卷积，在 $s$ 域只是两个有理式相乘。',
          },
          {
            id: 'u18-l3-q3',
            type: 'input',
            prompt: '对 $y\'+3y=0,\\ y(0)=2$ 取 Laplace 变换得 $(s+3)Y=2$，解出时域 $y(t)=2e^{?\\,t}$，指数里填？',
            accept: ['-3', '−3'],
            explain: '$Y(s)=\\tfrac{2}{s+3}$，对照 $e^{at}\\mapsto1/(s-a)$ 得 $a=-3$，故 $y(t)=2e^{-3t}$。',
          },
          {
            id: 'u18-l3-q4',
            type: 'judge',
            prompt: '判断：因为指数求导后形式基本不变，所以线性微分方程经变换后常化为代数关系。',
            answer: true,
            explain: '导数在 Laplace 里对应乘 $s$、在 Fourier 里对应乘 $i\\omega$，于是微分方程变成代数方程。',
          },
          {
            id: 'u18-l3-q5',
            type: 'choice',
            prompt: '阻尼振动 $y\'\'+2y\'+5y=0$ 的解为 $y=e^{-t}\\cos2t+\\tfrac12 e^{-t}\\sin2t$。其中“衰减因子”$e^{-t}$ 来自？',
            options: [
              '分母配方 $(s+1)^2+2^2$ 的实部偏移 $s+1$',
              '分子里的常数项',
              '初值 $y(0)=1$',
              '虚部 $\\omega=2$',
            ],
            answer: 0,
            explain: '配方 $s^2+2s+5=(s+1)^2+2^2$：实部偏移 $s+1$（频移 $a=-1$）给出衰减 $e^{-t}$，虚部 $\\omega=2$ 给出振荡 $\\cos2t,\\sin2t$。',
          },
          {
            id: 'u18-l3-q6',
            type: 'match',
            prompt: '把每个 Laplace 运算性质与其 $s$ 域结果配对：',
            left: ['线性 $\\alpha f+\\beta g$', '微分 $f\'(t)$', '频移 $e^{at}f(t)$', '卷积 $f*g$'],
            right: ['$\\alpha F+\\beta G$', '$sF(s)-f(0)$', '$F(s-a)$', '$F(s)G(s)$'],
            explain: '微分→乘 $s$、卷积→乘积，是变换法简化微分方程的核心机制。',
          },
        ],
      },
    ],
  },

  // ===================== 第19章 =====================
  {
    id: 'u19',
    title: '凸性 · 熵 · 概率尾',
    color: '#fdcb6e',
    icon: '📊',
    blurb: '$e^x$ 凸 ⇒ 切线不等式 $e^x\\ge1+x$ ⇒ MGF、Chernoff 尾界、Jensen。',
    lessons: [
      {
        id: 'u19-l1',
        title: '凸性与切线不等式',
        subtitle: '$e^x\\ge1+x$ 是一切的源头',
        questions: [
          {
            id: 'u19-l1-q1',
            type: 'choice',
            prompt: '为什么 $e^x$ 是严格凸函数？',
            options: [
              '因为 $\\dfrac{d^2}{dx^2}e^x=e^x>0$',
              '因为 $e^x>0$',
              '因为 $e^x$ 递增',
              '因为 $e^0=1$',
            ],
            answer: 0,
            explain: '二阶导 $e^x>0$ 对一切 $x$ 成立，故 $e^x$ 严格凸：图像始终向上弯，任意切线都在图像下方。',
          },
          {
            id: 'u19-l1-q2',
            type: 'choice',
            prompt: '$e^x$ 在 $x=0$ 处的切线是？由凸性它给出哪条不等式？',
            options: [
              '切线 $y=1+x$，不等式 $e^x\\ge1+x$',
              '切线 $y=x$，不等式 $e^x\\ge x$',
              '切线 $y=1$，不等式 $e^x\\ge1$',
              '切线 $y=e^x$，无不等式',
            ],
            answer: 0,
            explain: '切线 $y=1+x$ 恒在曲线下方，仅在切点 $(0,1)$ 相切，故对一切实数 $e^x\\ge1+x$，等号仅 $x=0$。',
          },
          {
            id: 'u19-l1-q3',
            type: 'judge',
            prompt: '判断：不等式 $e^x\\ge1+x$ 只对 $x\\ge0$ 成立。',
            answer: false,
            explain: '对一切实数都成立。当 $x<-1$ 时 $1+x<0$ 而 $e^x>0$，差距反而更大。它是 Chernoff、Jensen 的基石。',
          },
          {
            id: 'u19-l1-q4',
            type: 'input',
            prompt: '用切线不等式估计 $e^{0.1}$ 的一个下界（即 $1+0.1$）：填这个下界。',
            accept: ['1.1', '1.10'],
            explain: '$e^{0.1}\\ge1+0.1=1.1$（真值约 $1.1052$，下界成立）。',
          },
          {
            id: 'u19-l1-q5',
            type: 'match',
            prompt: '把 $g(x)=e^x-(1+x)$ 的证明三步与其作用配对：',
            left: ['$g\'\'(x)=e^x>0$', '$g\'(x)=0\\Rightarrow x=0$', '$g(0)=0$'],
            right: ['确认严格凸', '定位唯一切点（极小点）', '代回得最小值为 $0$'],
            explain: '用二阶导确认凸、用一阶导定位切点、代回得最小值 $0$，于是 $g(x)\\ge0$。',
          },
        ],
      },
      {
        id: 'u19-l2',
        title: 'Jensen、MGF 与 log-sum-exp',
        subtitle: '指数放大波动，对数压缩尺度',
        questions: [
          {
            id: 'u19-l2-q1',
            type: 'choice',
            prompt: '$\\{0,0\\}$ 与 $\\{-1,1\\}$ 平均都为 $0$。先取指数再平均，哪组更大？',
            options: [
              '$\\{-1,1\\}$ 更大（约 $1.543>1$）',
              '$\\{0,0\\}$ 更大',
              '两组相等',
              '无法比较',
            ],
            answer: 0,
            explain: '$\\tfrac{e^{-1}+e^{1}}{2}\\approx1.543>1=\\tfrac{e^0+e^0}{2}$。更分散的一组指数平均更大——指数放大偏离。',
          },
          {
            id: 'u19-l2-q2',
            type: 'choice',
            prompt: 'Jensen 不等式对凸函数 $\\phi$（如 $e^x$）给出的方向是？',
            options: [
              '$\\mathbb{E}[\\phi(X)]\\ge\\phi(\\mathbb{E}[X])$',
              '$\\mathbb{E}[\\phi(X)]\\le\\phi(\\mathbb{E}[X])$',
              '$\\mathbb{E}[\\phi(X)]=\\phi(\\mathbb{E}[X])$',
              '方向不定',
            ],
            answer: 0,
            explain: '凸函数“先取指数再平均 ≥ 先平均再取指数”，与“指数放大波动”的直觉一致。',
          },
          {
            id: 'u19-l2-q3',
            type: 'input',
            prompt: 'Bernoulli 变量（$\\Pr(X{=}1)=p$）的 MGF $M(t)=\\mathbb{E}[e^{tX}]=(1-p)+p\\,e^{?}$，指数里填？',
            accept: ['t', 'T'],
            explain: '$M(t)=(1-p)e^{0}+p\\,e^{t}=(1-p)+pe^{t}$，是离散 MGF 的最简范例。',
          },
          {
            id: 'u19-l2-q4',
            type: 'judge',
            prompt: '判断：$\\operatorname{LSE}(x_1,\\dots,x_n)=\\log(e^{x_1}+\\cdots+e^{x_n})$ 可看作“最大值的平滑版本”，总不小于 $M=\\max_i x_i$。',
            answer: true,
            explain: '提出 $M$：$\\operatorname{LSE}=M+\\log\\!\\big(\\sum e^{x_i-M}\\big)\\ge M$（和式至少含等于 $1$ 的最大项），故 LSE 略大于但接近 $M$。',
          },
          {
            id: 'u19-l2-q5',
            type: 'choice',
            prompt: '$\\operatorname{LSE}(1,2,5)$ 约等于？（提示：提出 $M=5$）',
            options: ['约 $5.07$', '约 $5$', '约 $8$', '约 $2.67$'],
            answer: 0,
            explain: '$5+\\log(e^{-4}+e^{-3}+1)\\approx5+\\log(1.068)\\approx5.066$：最大项主导，其余项是平滑修正。',
          },
          {
            id: 'u19-l2-q6',
            type: 'match',
            prompt: '把对数与指数在信息里的分工配对：',
            left: ['对数', '指数'],
            right: ['压缩尺度、把乘法变加法', '还原尺度、放大差异'],
            explain: '对数负责压缩、线性化；指数负责还原、放大。两者组合即 log-sum-exp / softmax。',
          },
        ],
      },
      {
        id: 'u19-l3',
        title: '概率尾界：Chernoff 与 Hoeffding',
        subtitle: '先指数化，再取 $\\inf_t$',
        questions: [
          {
            id: 'u19-l3-q1',
            type: 'choice',
            prompt: '标准正态 $X\\sim N(0,1)$ 的矩母函数 $M(t)=\\mathbb{E}[e^{tX}]$ 等于？',
            options: ['$e^{t^2/2}$', '$e^{t}$', '$\\dfrac{1}{1-t}$', '$e^{-t^2/2}$'],
            answer: 0,
            explain: '对指数配方 $-\\tfrac{x^2}{2}+tx=-\\tfrac12(x-t)^2+\\tfrac{t^2}{2}$，剩余正态积分为 $1$，故 $M(t)=e^{t^2/2}$，对一切实 $t$ 收敛。',
          },
          {
            id: 'u19-l3-q2',
            type: 'choice',
            prompt: 'Chernoff 法第一步：对 $a>0$、$t>0$，由 Markov 不等式得 $\\Pr(X\\ge a)\\le$？',
            options: ['$e^{-ta}M(t)$', '$e^{ta}M(t)$', '$M(t)/a$', '$e^{-ta}$'],
            answer: 0,
            explain: '$\\Pr(X\\ge a)=\\Pr(e^{tX}\\ge e^{ta})\\le \\mathbb{E}[e^{tX}]/e^{ta}=e^{-ta}M(t)$。Markov 只对非负量成立，故先搬进 $e^{tX}$。',
          },
          {
            id: 'u19-l3-q3',
            type: 'input',
            prompt: '对 $N(0,1)$，$\\Pr(X\\ge a)\\le\\exp(\\tfrac{t^2}{2}-ta)$ 在 $t^*=?$ 取最优。填关于 $a$ 的表达式。',
            accept: ['a', 'A'],
            explain: '$\\varphi(t)=\\tfrac{t^2}{2}-ta$，$\\varphi\'(t)=t-a=0\\Rightarrow t^*=a$，代回得高斯尾界 $e^{-a^2/2}$。',
          },
          {
            id: 'u19-l3-q4',
            type: 'choice',
            prompt: '对 $t$ 取最优后，正态上尾界 $\\Pr(X\\ge a)\\le$？（$a>0$）',
            options: ['$e^{-a^2/2}$', '$e^{-a}$', '$e^{-a/2}$', '$\\dfrac12 e^{-a}$'],
            answer: 0,
            explain: '$\\varphi(a)=\\tfrac{a^2}{2}-a^2=-\\tfrac{a^2}{2}$，故 $\\Pr(X\\ge a)\\le e^{-a^2/2}$。不优化 $t$ 只能得更松的界。',
          },
          {
            id: 'u19-l3-q5',
            type: 'judge',
            prompt: '判断：对 $X_i\\in\\{0,1\\}$ 等概、$S_n=\\sum X_i$，Hoeffding 给出 $\\Pr(S_n\\ge\\tfrac n2+n\\varepsilon)\\le e^{-2n\\varepsilon^2}$，即偏离概率随 $n$ 指数下降。',
            answer: true,
            explain: '独立⇒MGF 相乘，有界变量 MGF 上界 $e^{t^2/8}$，Chernoff 取 $t^*=4\\varepsilon$ 得 $e^{-2n\\varepsilon^2}$。这是大数定律“收敛多快”的定量版。',
          },
          {
            id: 'u19-l3-q6',
            type: 'match',
            prompt: '把尾部类型与“当阈值变大时的直觉”配对：',
            left: ['指数尾 $e^{-ct}$', '多项式尾 $1/t$、$1/t^2$'],
            right: ['下降非常快，极端事件迅速变罕见', '也会下降，但尾巴更厚，极端事件更难压低'],
            explain: '“有指数尾界”是很强的结论：系统对大偏离的控制明显强于多项式级（厚尾）衰减。',
          },
        ],
      },
    ],
  },

  // ===================== 第20章 =====================
  {
    id: 'u20',
    title: '高级综合与展望',
    color: '#55a630',
    icon: '🏆',
    blurb: '$(1+x/n)^n\\to e^x$ 离散到连续，串联全书各条主线。',
    lessons: [
      {
        id: 'u20-l1',
        title: '先识别结构，再选语言',
        subtitle: '图像 / 导数 / 离散 / 复指数 / 矩阵 / 尾界',
        questions: [
          {
            id: 'u20-l1-q1',
            type: 'choice',
            prompt: '判断方程 $e^x=x+1$ 的实根个数，最省力的语言是？',
            options: [
              '令 $g=e^x-x-1$，用凸性（最小值恰为 $0$）',
              '两边取对数',
              '数值逐点试根',
              '画无穷多条切线',
            ],
            answer: 0,
            explain: '$g\'\'=e^x>0$ 凸，$g\'(0)=0$、$g(0)=0$ ⇒ 最小值 $0$ 在 $x=0$，故唯一根 $x=0$。结构识别比硬算更重要。',
          },
          {
            id: 'u20-l1-q2',
            type: 'choice',
            prompt: '方程 $e^x=2x+1$（斜率改成 $2$）的实根个数是？',
            options: ['$2$ 个', '$1$ 个', '$0$ 个', '无穷多个'],
            answer: 0,
            explain: '$h=e^x-2x-1$ 凸 ⇒ 至多两根；最小值 $h(\\ln2)=1-2\\ln2\\approx-0.386<0$，故恰好两根（含 $x=0$）。',
          },
          {
            id: 'u20-l1-q3',
            type: 'judge',
            prompt: '判断：高阶综合题最常见的失败不是“算不出来”，而是“一开始就选错了语言”。',
            answer: true,
            explain: '同一个指数表达式在不同章里身份不同；先判断核心结构属于哪种指数语言，后续步骤反而不复杂。',
          },
          {
            id: 'u20-l1-q4',
            type: 'match',
            prompt: '把题目线索与“优先想到的工具”配对：',
            left: ['比较谁在上面/先相交', '每步按比例更新', '变化率与自身成比例', '模长不变但方向在转'],
            right: ['图像、单调性、凸性', '数列、复利、离散模型', '导数、微分方程', '复指数、Euler 公式'],
            explain: '先选对语言，再决定细算步骤——这是 20.2 节通用观察框架的核心。',
          },
          {
            id: 'u20-l1-q5',
            type: 'input',
            prompt: '看到“极端事件越来越罕见、尾部衰减”这一信号，应调用第几章的语言（凸性、log-sum-exp 与尾界）？填章号数字。',
            accept: ['19', '第19章', '19章'],
            explain: '“尾部衰减、极端事件、平均放大”对应第19章的指数尾界与 Chernoff 方法。',
          },
        ],
      },
      {
        id: 'u20-l2',
        title: '离散到连续：$(1+x/n)^n\\to e^x$',
        subtitle: '复利加密的自然极限',
        questions: [
          {
            id: 'u20-l2-q1',
            type: 'choice',
            prompt: '离散复利 $A=P(1+\\tfrac rm)^{mt}$ 在 $m\\to\\infty$ 时走向？',
            options: ['$A=Pe^{rt}$', '$A=P(1+r)^t$', '$A=Pe^{r/t}$', '$A=Pr^{t}$'],
            answer: 0,
            explain: '把指数 $mt$ 拆成 $[(1+\\tfrac rm)^m]^t$，内层 $\\to e^r$，外层 $t$ 次方给出 $e^{rt}$。',
          },
          {
            id: 'u20-l2-q2',
            type: 'input',
            prompt: '取 $r=t=1$，连续复利极限 $(1+\\tfrac1m)^m$（$m\\to\\infty$）收敛到哪个常数？（填字母）',
            accept: ['e', 'E'],
            explain: '$\\lim_{m\\to\\infty}(1+\\tfrac1m)^m=e\\approx2.718$。$e$ 是“无限细分的离散更新”的极限。',
          },
          {
            id: 'u20-l2-q3',
            type: 'choice',
            prompt: '$m=1,2,12$ 时 $(1+\\tfrac1m)^m$ 的值依次约为？',
            options: ['$2,\\ 2.25,\\ 2.613$', '$1,\\ 2,\\ 3$', '$2,\\ 4,\\ 12$', '$e,\\ e,\\ e$'],
            answer: 0,
            explain: '$2<2.25<2.613<\\cdots<e$，单调上升逐步逼近极限 $e$。',
          },
          {
            id: 'u20-l2-q4',
            type: 'judge',
            prompt: '判断：第9章的离散复利与第10章的连续复利是两套彼此竞争、互相矛盾的公式。',
            answer: false,
            explain: '它们是同一条“按比例变化”主线的两种时间刻画——离散更新无限加密后自然得到 $e^{rt}$。',
          },
          {
            id: 'u20-l2-q5',
            type: 'choice',
            prompt: '把单步因子线性化：$n\\ln(1+\\tfrac xn)$ 在 $n\\to\\infty$ 时趋于？',
            options: ['$x$', '$0$', '$x^2$', '$\\ln x$'],
            answer: 0,
            explain: '$\\ln(1+\\tfrac xn)=\\tfrac xn-\\tfrac{x^2}{2n^2}+\\cdots$，乘 $n$ 得 $x-\\tfrac{x^2}{2n}+\\cdots\\to x$，故 $(1+\\tfrac xn)^n\\to e^x$。',
          },
          {
            id: 'u20-l2-q6',
            type: 'match',
            prompt: '把 $e^x$ 在不同章里的“身份”配对：',
            left: ['第10章', '第14章', '第12/13章', '第15章'],
            right: ['离散加密的极限', '对数线性化的主项', '自治方程 $y\'=y$ 的唯一解', '单位圆上的旋转 $e^{it}$'],
            explain: '同一个 $e^x$ 在不同章承担不同身份——综合能力是能说清“此刻用哪一章的语言、为什么最省力”。',
          },
        ],
      },
      {
        id: 'u20-l3',
        title: '主线综合：旋转、尾部与指数思维',
        subtitle: '复指数 ↔ 矩阵指数，近似 ↔ 尾界',
        questions: [
          {
            id: 'u20-l3-q1',
            type: 'choice',
            prompt: '对 $J=\\begin{pmatrix}0&-1\\\\1&0\\end{pmatrix}$（满足 $J^2=-I$），矩阵指数 $e^{Jt}$ 等于？',
            options: [
              '$\\cos t\\,I+\\sin t\\,J=\\begin{pmatrix}\\cos t&-\\sin t\\\\\\sin t&\\cos t\\end{pmatrix}$',
              '$e^t I$',
              '$\\begin{pmatrix}e^t&0\\\\0&e^{-t}\\end{pmatrix}$',
              '$tJ$',
            ],
            answer: 0,
            explain: '$J^2=-I$ 在矩阵世界扮演 $i^2=-1$；幂的 4-周期把级数劈成 $\\cos$ 与 $\\sin$，得旋转矩阵。',
          },
          {
            id: 'u20-l3-q2',
            type: 'judge',
            prompt: '判断：$e^{it}$ 的“旋转”与 $e^{Jt}$ 的“旋转矩阵”不是类比，而是同一代数结构（$i^2=-1$ 与 $J^2=-I$）的两种载体。',
            answer: true,
            explain: '正因为这个“虚单位结构”，两者都导向旋转而非增长——指数更深的角色是生成稳定的演化规则。',
          },
          {
            id: 'u20-l3-q3',
            type: 'input',
            prompt: '用 Laplace 解 $y\'=-y+e^{-2t},\\ y(0)=0$ 得 $Y(s)=\\tfrac{1}{(s+1)(s+2)}$，反变换 $y(t)=e^{-t}-e^{?\\,t}$，指数填？',
            accept: ['-2', '−2'],
            explain: '部分分式 $\\tfrac{1}{s+1}-\\tfrac{1}{s+2}$ ⇒ $y=e^{-t}-e^{-2t}$。',
          },
          {
            id: 'u20-l3-q4',
            type: 'choice',
            prompt: '上题中 $y=e^{-t}-e^{-2t}$ 的长期行为（$t$ 大）由哪一项主导？为什么？',
            options: [
              '$e^{-t}$ 主导，因其衰减最慢（极点 $s=-1$ 最靠近虚轴）',
              '$e^{-2t}$ 主导，因其衰减最快',
              '两项相互抵消',
              '由初值 $y(0)=0$ 决定',
            ],
            answer: 0,
            explain: '极点离虚轴越近衰减越慢、长期越主导——与第19章“衰减慢的厚尾主导极端行为”同源。',
          },
          {
            id: 'u20-l3-q5',
            type: 'judge',
            prompt: '判断：第14章“下一项很小所以误差不大”与第19章“指数尾衰减很快”，共享“指数型量进入尾部会迅速压小远处贡献”这一机制。',
            answer: true,
            explain: '阶乘分母让级数高次项迅速变小、指数衰减让尾部概率迅速变小——都在训练“尾部贡献是否足够小”的判断。',
          },
          {
            id: 'u20-l3-q6',
            type: 'match',
            prompt: '把“指数思维”在各领域的角色配对（全书主线总览）：',
            left: ['实数建模', '离散模型', '复数', '概率与信息'],
            right: ['增长与衰减', '等比更新与复利', '旋转与振荡', '放大偏离、控制尾部'],
            explain: '指数真正统一的是“按比例变化”与“对差异的系统放大”——这就是整本教程想留下的核心视角。',
          },
        ],
      },
    ],
  },
]
