import type { Unit } from '../../types'

// 第五部分：复数与结构（第15–17章）
// u15 复指数与欧拉公式 / u16 双曲函数 / u17 矩阵指数与线性系统
export const PART5_UNITS: Unit[] = [
  // ===================== 第15章：复指数与欧拉公式 =====================
  {
    id: 'u15',
    title: '复指数与欧拉公式',
    color: '#6c5ce7',
    icon: '🌐',
    blurb: '把指数函数推进复数世界：$e^{i\\theta}=\\cos\\theta+i\\sin\\theta$，旋转、振荡与单位圆。',
    lessons: [
      {
        id: 'u15-l1',
        title: '欧拉公式',
        subtitle: '从级数走到 $e^{i\\theta}=\\cos\\theta+i\\sin\\theta$',
        questions: [
          {
            id: 'u15-l1-q1',
            type: 'choice',
            prompt: '欧拉公式 $e^{i\\theta}$ 等于下列哪一个？',
            options: [
              '$\\cos\\theta+i\\sin\\theta$',
              '$\\sin\\theta+i\\cos\\theta$',
              '$\\cos\\theta-i\\sin\\theta$',
              '$\\cosh\\theta+i\\sinh\\theta$',
            ],
            answer: 0,
            explain: '欧拉公式：$e^{i\\theta}=\\cos\\theta+i\\sin\\theta$，实部为 $\\cos\\theta$，虚部为 $\\sin\\theta$。',
          },
          {
            id: 'u15-l1-q2',
            type: 'judge',
            prompt: '欧拉公式不是凭空假设的，而是把指数幂级数里的 $x$ 换成 $ix$ 后自然分出的实部和虚部。',
            answer: true,
            explain: '把 $e^{ix}$ 按幂级数展开并用 $i^2=-1$ 整理，偶次项凑成 $\\cos x$、奇次项凑成 $i\\sin x$。',
          },
          {
            id: 'u15-l1-q3',
            type: 'input',
            prompt: '欧拉公式中，$e^{i\\theta}$ 的实部是 $\\cos\\theta$，那么它的虚部是什么？（填三角函数）',
            accept: ['sin\\theta', '\\sin\\theta', 'sintheta', 'sin', '\\sin theta'],
            explain: '$e^{i\\theta}=\\cos\\theta+i\\sin\\theta$，所以虚部是 $\\sin\\theta$。',
          },
          {
            id: 'u15-l1-q4',
            type: 'choice',
            prompt: '把 $x$ 换成 $ix$ 后，幂级数里的偶次项重新组合成了哪个函数？',
            options: ['$\\sin x$', '$\\cos x$', '$e^x$', '$\\tan x$'],
            answer: 1,
            explain: '偶次项 $1-\\frac{x^2}{2!}+\\frac{x^4}{4!}-\\cdots$ 正是 $\\cos x$ 的级数；奇次项凑成 $i\\sin x$。',
          },
          {
            id: 'u15-l1-q5',
            type: 'match',
            prompt: '把每个角度与 $e^{i\\theta}$ 的值配对。',
            left: ['$\\theta=0$', '$\\theta=\\frac{\\pi}{2}$', '$\\theta=\\pi$', '$\\theta=\\frac{3\\pi}{2}$'],
            right: ['$1$', '$i$', '$-1$', '$-i$'],
            explain: '逐个代入 $e^{i\\theta}=\\cos\\theta+i\\sin\\theta$：得到 $1,\\,i,\\,-1,\\,-i$，恰为单位圆上右、上、左、下四点。',
          },
        ],
      },
      {
        id: 'u15-l2',
        title: '极形式与旋转',
        subtitle: '$z=re^{i\\theta}$：模长相乘、角度相加',
        questions: [
          {
            id: 'u15-l2-q1',
            type: 'choice',
            prompt: '为什么纯虚指数 $e^{i\\theta}$ 描述的是旋转而不是增长？',
            options: [
              '因为它的模长 $|e^{i\\theta}|=1$ 恒定，只有角度在变',
              '因为它的实部恒为 0',
              '因为 $\\theta$ 必须是整数',
              '因为 $e^{i\\theta}$ 总是大于 1',
            ],
            answer: 0,
            explain: '$|e^{i\\theta}|=\\sqrt{\\cos^2\\theta+\\sin^2\\theta}=1$，点始终在单位圆上，只随 $\\theta$ 旋转。',
          },
          {
            id: 'u15-l2-q2',
            type: 'input',
            prompt: '$|e^{i\\theta}|$ 的值等于多少？（填一个数）',
            accept: ['1', '一'],
            explain: '$|e^{i\\theta}|=\\sqrt{\\cos^2\\theta+\\sin^2\\theta}=1$，所以 $e^{i\\theta}$ 永远落在单位圆上。',
          },
          {
            id: 'u15-l2-q3',
            type: 'judge',
            prompt: '在极形式下，两个复数相乘 $z_1z_2$ 的结果是“模长相乘、角度相加”。',
            answer: true,
            explain: '$z_1z_2=r_1r_2\\,e^{i(\\theta_1+\\theta_2)}$：模长 $r_1r_2$，辐角 $\\theta_1+\\theta_2$。',
          },
          {
            id: 'u15-l2-q4',
            type: 'choice',
            prompt: '复数 $z=re^{i\\theta}$ 中，$r$ 和 $\\theta$ 分别负责什么？',
            options: [
              '$r$ 负责方向，$\\theta$ 负责长度',
              '$r$ 负责长度（模长），$\\theta$ 负责方向（辐角）',
              '两者都负责长度',
              '两者都负责方向',
            ],
            answer: 1,
            explain: '$r=|z|$ 是到原点的距离（有多长），$\\theta$ 是与正实轴的夹角（朝哪个方向）。',
          },
          {
            id: 'u15-l2-q5',
            type: 'input',
            prompt: '已知 $z_1=\\sqrt2\\,e^{i\\pi/4}$，$z_2=2e^{i\\pi/6}$，它们乘积的模长是多少？（填一个数或表达式）',
            accept: ['2sqrt2', '2\\sqrt2', '2\\sqrt{2}', '2根号2', '2*sqrt(2)', '2√2'],
            explain: '模长相乘：$\\sqrt2\\times 2=2\\sqrt2$；辐角相加：$\\frac{\\pi}{4}+\\frac{\\pi}{6}=\\frac{5\\pi}{12}$。',
          },
          {
            id: 'u15-l2-q6',
            type: 'judge',
            prompt: '“乘以 $e^{i\\theta}$”会改变复数的模长。',
            answer: false,
            explain: '$ze^{i\\theta}$ 保持模长不变，只把辐角整体增加 $\\theta$——这正是纯旋转。',
          },
        ],
      },
      {
        id: 'u15-l3',
        title: '单位根与著名恒等式',
        subtitle: '$z^n=1$ 的等角分布与 $e^{i\\pi}+1=0$',
        questions: [
          {
            id: 'u15-l3-q1',
            type: 'choice',
            prompt: '方程 $z^n=1$ 的 $n$ 个单位根在复平面上如何分布？',
            options: [
              '随机散布在平面上',
              '全部落在实轴上',
              '等角分布在单位圆上，构成正 $n$ 边形顶点',
              '全部重合在点 1 处',
            ],
            answer: 2,
            explain: '$z_k=e^{i\\frac{2k\\pi}{n}}$，相邻角度差恒为 $\\frac{2\\pi}{n}$，把单位圆均分成 $n$ 份。',
          },
          {
            id: 'u15-l3-q2',
            type: 'input',
            prompt: '欧拉恒等式 $e^{i\\pi}+1=0$ 中，$e^{i\\pi}$ 的值是多少？（填一个数）',
            accept: ['-1', '负1', '负一'],
            explain: '$e^{i\\pi}=\\cos\\pi+i\\sin\\pi=-1+0=-1$，故 $e^{i\\pi}+1=0$。',
          },
          {
            id: 'u15-l3-q3',
            type: 'judge',
            prompt: '$n$ 次单位根中相邻两根的辐角差恒等于 $\\frac{2\\pi}{n}$。',
            answer: true,
            explain: '$z_k=e^{i\\frac{2k\\pi}{n}}$，相邻 $k$ 差 1，对应辐角差 $\\frac{2\\pi}{n}$，故等角分布。',
          },
          {
            id: 'u15-l3-q4',
            type: 'choice',
            prompt: '方程 $z^4=1$ 的全部解是？',
            options: ['$1,\\,i,\\,-1,\\,-i$', '$1,\\,-1$', '$i,\\,-i$', '$1,\\,2,\\,3,\\,4$'],
            answer: 0,
            explain: '$z_k=e^{i\\frac{2k\\pi}{4}}\\ (k=0,1,2,3)$，得 $1,\\,i,\\,-1,\\,-i$，正方形四顶点。',
          },
          {
            id: 'u15-l3-q5',
            type: 'match',
            prompt: '把欧拉恒等式 $e^{i\\pi}+1=0$ 里的对象与它所代表的数学领域配对。',
            left: ['$e$', '$i$', '$\\pi$', '$0$ 与 $1$'],
            right: ['指数（自然底数）', '复数单位', '圆周率', '算术基本元'],
            explain: '一条恒等式同时压缩了指数、复数、圆周率和算术的核心常数，被誉为最美公式。',
          },
        ],
      },
    ],
  },

  // ===================== 第16章：双曲函数 =====================
  {
    id: 'u16',
    title: '双曲函数',
    color: '#0984e3',
    icon: '〽️',
    blurb: '$\\cosh,\\sinh,\\tanh$ 是指数的对称组合：$\\cosh^2-\\sinh^2=1$，悬链线与饱和响应。',
    lessons: [
      {
        id: 'u16-l1',
        title: '双曲函数的定义',
        subtitle: '$\\cosh x,\\sinh x$ 由 $e^x,e^{-x}$ 组合而来',
        questions: [
          {
            id: 'u16-l1-q1',
            type: 'choice',
            prompt: '双曲余弦 $\\cosh x$ 的定义是？',
            options: [
              '$\\frac{e^x-e^{-x}}{2}$',
              '$\\frac{e^x+e^{-x}}{2}$',
              '$\\frac{e^x+e^{-x}}{2i}$',
              '$\\frac{e^x}{e^{-x}}$',
            ],
            answer: 1,
            explain: '$\\cosh x=\\frac{e^x+e^{-x}}{2}$（对称平均），$\\sinh x=\\frac{e^x-e^{-x}}{2}$（反对称差值）。',
          },
          {
            id: 'u16-l1-q2',
            type: 'input',
            prompt: '双曲正弦的定义 $\\sinh x=\\frac{e^x-e^{-x}}{?}$，分母填什么？',
            accept: ['2', '二'],
            explain: '$\\sinh x=\\frac{e^x-e^{-x}}{2}$，与 $\\cosh$ 一样分母是 2，只是分子改成相减。',
          },
          {
            id: 'u16-l1-q3',
            type: 'judge',
            prompt: '$\\cosh x$ 是偶函数，$\\sinh x$ 是奇函数。',
            answer: true,
            explain: '$\\cosh(-x)=\\cosh x$（对称平均，偶），$\\sinh(-x)=-\\sinh x$（反对称差，奇）。',
          },
          {
            id: 'u16-l1-q4',
            type: 'choice',
            prompt: '把双曲函数反过来拆指数，$e^x$ 等于下列哪个组合？',
            options: [
              '$\\cosh x+\\sinh x$',
              '$\\cosh x-\\sinh x$',
              '$\\cosh x\\cdot\\sinh x$',
              '$2\\cosh x$',
            ],
            answer: 0,
            explain: '由定义直接相加：$\\cosh x+\\sinh x=\\frac{e^x+e^{-x}}{2}+\\frac{e^x-e^{-x}}{2}=e^x$。',
          },
          {
            id: 'u16-l1-q5',
            type: 'match',
            prompt: '把每个双曲函数与它的奇偶性／图像特征配对。',
            left: ['$\\cosh x$', '$\\sinh x$', '$\\tanh x$'],
            right: ['偶函数，恒 $\\ge 1$', '奇函数，过原点', '渐近 $y=\\pm 1$，呈饱和'],
            explain: '$\\cosh$ 是 U 形偶函数；$\\sinh$ 过原点的奇函数；$\\tanh$ 输出落在 $(-1,1)$，逐渐饱和。',
          },
        ],
      },
      {
        id: 'u16-l2',
        title: '恒等式与导数',
        subtitle: '$\\cosh^2-\\sinh^2=1$ 与整齐的导数',
        questions: [
          {
            id: 'u16-l2-q1',
            type: 'choice',
            prompt: '双曲函数的基本恒等式是？',
            options: [
              '$\\cosh^2 x+\\sinh^2 x=1$',
              '$\\cosh^2 x-\\sinh^2 x=1$',
              '$\\sinh^2 x-\\cosh^2 x=1$',
              '$\\cosh^2 x\\cdot\\sinh^2 x=1$',
            ],
            answer: 1,
            explain: '$\\cosh^2 x-\\sinh^2 x=1$，与三角的 $\\cos^2+\\sin^2=1$ 形式相似但符号是减号。',
          },
          {
            id: 'u16-l2-q2',
            type: 'input',
            prompt: '$(\\sinh x)\'=?$，请填它的导数（双曲函数名）。',
            accept: ['cosh x', '\\cosh x', 'coshx', 'cosh', '\\cosh', 'cosh(x)'],
            explain: '$(\\sinh x)\'=\\cosh x$，$(\\cosh x)\'=\\sinh x$——求导下两者彼此切换，且都不带负号。',
          },
          {
            id: 'u16-l2-q3',
            type: 'judge',
            prompt: '$(\\cosh x)\'=-\\sinh x$。',
            answer: false,
            explain: '错。双曲函数求导没有负号：$(\\cosh x)\'=\\sinh x$，$(\\sinh x)\'=\\cosh x$。',
          },
          {
            id: 'u16-l2-q4',
            type: 'choice',
            prompt: '$\\tanh x$ 的导数等于？',
            options: [
              '$\\frac{1}{\\cosh^2 x}$',
              '$\\cosh^2 x$',
              '$\\frac{1}{\\sinh^2 x}$',
              '$-\\tanh^2 x$',
            ],
            answer: 0,
            explain: '商法则给出 $(\\tanh x)\'=\\frac{\\cosh^2 x-\\sinh^2 x}{\\cosh^2 x}=\\frac{1}{\\cosh^2 x}=\\operatorname{sech}^2 x$。',
          },
          {
            id: 'u16-l2-q5',
            type: 'judge',
            prompt: '对任意实数 $x$，$\\cosh x$ 恒为正（恒 $\\ge 1$）。',
            answer: true,
            explain: '$\\cosh x=\\frac{e^x+e^{-x}}{2}$ 是两个正数的平均，故恒 $\\ge 1$，不必像三角函数那样讨论符号。',
          },
          {
            id: 'u16-l2-q6',
            type: 'choice',
            prompt: '微分方程 $y\'\'=y$ 的解会自然导向哪类函数？',
            options: ['三角函数 $\\cos,\\sin$', '双曲函数 $\\cosh,\\sinh$', '对数函数', '常值函数'],
            answer: 1,
            explain: '试探 $y=e^{rx}$ 得 $r^2=1$，两支解 $e^x,e^{-x}$ 重组即 $\\cosh,\\sinh$；而 $y\'\'=-y$ 才导向三角函数。',
          },
        ],
      },
      {
        id: 'u16-l3',
        title: '计算与应用',
        subtitle: '从定义算值、反函数与悬链线',
        questions: [
          {
            id: 'u16-l3-q1',
            type: 'input',
            prompt: '$\\cosh 0$ 的值是多少？（填一个数）',
            accept: ['1', '一'],
            explain: '$\\cosh 0=\\frac{e^0+e^{0}}{2}=\\frac{1+1}{2}=1$。',
          },
          {
            id: 'u16-l3-q2',
            type: 'input',
            prompt: '$\\sinh 0$ 的值是多少？（填一个数）',
            accept: ['0', '零'],
            explain: '$\\sinh 0=\\frac{e^0-e^{0}}{2}=\\frac{1-1}{2}=0$。',
          },
          {
            id: 'u16-l3-q3',
            type: 'choice',
            prompt: '已知 $\\sinh x=\\frac{3}{4}$，则 $\\cosh x$ 等于？',
            options: ['$\\frac{5}{4}$', '$\\frac{3}{5}$', '$\\frac{4}{3}$', '$-\\frac{5}{4}$'],
            answer: 0,
            explain: '$\\cosh^2 x=1+\\sinh^2 x=1+\\frac{9}{16}=\\frac{25}{16}$，取正根 $\\cosh x=\\frac{5}{4}$。',
          },
          {
            id: 'u16-l3-q4',
            type: 'judge',
            prompt: '$\\tanh x$ 的输出始终落在区间 $(-1,1)$ 内，因此常用作“压缩映射”。',
            answer: true,
            explain: '$\\tanh x$ 把任意实数压缩到 $(-1,1)$，在建模、神经网络中常见，渐近线为 $y=\\pm 1$。',
          },
          {
            id: 'u16-l3-q5',
            type: 'choice',
            prompt: '反双曲正弦可以用对数表示，$\\operatorname{arsinh} x=?$',
            options: [
              '$\\ln(x+\\sqrt{x^2+1})$',
              '$\\ln(x+\\sqrt{x^2-1})$',
              '$\\frac{1}{2}\\ln\\frac{1+x}{1-x}$',
              '$\\ln(x^2+1)$',
            ],
            answer: 0,
            explain: '解 $t^2-2xt-1=0$ 取正根 $t=x+\\sqrt{x^2+1}$，故 $\\operatorname{arsinh} x=\\ln(x+\\sqrt{x^2+1})$。',
          },
          {
            id: 'u16-l3-q6',
            type: 'match',
            prompt: '把每个双曲积分与它的结果配对。',
            left: ['$\\int\\sinh x\\,dx$', '$\\int\\cosh x\\,dx$', '$\\int\\tanh x\\,dx$'],
            right: ['$\\cosh x+C$', '$\\sinh x+C$', '$\\ln(\\cosh x)+C$'],
            explain: '与导数互逆：$\\int\\sinh=\\cosh$，$\\int\\cosh=\\sinh$，$\\int\\tanh=\\ln(\\cosh x)$。',
          },
        ],
      },
    ],
  },

  // ===================== 第17章：矩阵指数与线性系统 =====================
  {
    id: 'u17',
    title: '矩阵指数与线性系统',
    color: '#00cd9c',
    icon: '🔢',
    blurb: '$e^{At}$ 解 $\\mathbf x\'=A\\mathbf x$：对角化、相平面与特征值实部决定的稳定性。',
    lessons: [
      {
        id: 'u17-l1',
        title: '矩阵指数的定义',
        subtitle: '$e^A=I+A+\\frac{A^2}{2!}+\\cdots$',
        questions: [
          {
            id: 'u17-l1-q1',
            type: 'choice',
            prompt: '矩阵指数 $e^A$ 的定义是？',
            options: [
              '对矩阵每个元素分别取指数',
              '$I+A+\\frac{A^2}{2!}+\\frac{A^3}{3!}+\\cdots$',
              '$A\\cdot e$',
              '$\\det(A)$ 的指数',
            ],
            answer: 1,
            explain: '$e^A=I+A+\\frac{A^2}{2!}+\\cdots$，与标量幂级数同源，只是把数乘换成矩阵乘法。',
          },
          {
            id: 'u17-l1-q2',
            type: 'judge',
            prompt: '$e^A$ 就是把矩阵 $A$ 的每个元素分别取指数。',
            answer: false,
            explain: '错。$e^A$ 是幂级数 $I+A+\\frac{A^2}{2!}+\\cdots$，不是逐元素操作。例如 $A=\\begin{pmatrix}0&1\\\\0&0\\end{pmatrix}$ 时 $e^A=\\begin{pmatrix}1&1\\\\0&1\\end{pmatrix}$。',
          },
          {
            id: 'u17-l1-q3',
            type: 'input',
            prompt: '把 $t=0$ 代入，$e^{A\\cdot 0}$ 等于哪个矩阵？（填字母）',
            accept: ['I', '单位阵', '单位矩阵', '恒等矩阵', '单位矩阵I'],
            explain: '$e^{A\\cdot 0}=I$（单位矩阵），这正是初值 $\\mathbf x(0)=\\mathbf x_0$ 成立的原因。',
          },
          {
            id: 'u17-l1-q4',
            type: 'choice',
            prompt: '矩阵指数 $e^A$ 对什么样的矩阵才有意义？',
            options: ['任意矩形矩阵', '只对方阵', '只对对角矩阵', '只对可逆矩阵'],
            answer: 1,
            explain: '级数里要算 $A^2,A^3,\\dots$，需要矩阵能自乘，所以 $e^A$ 只对方阵有意义。',
          },
          {
            id: 'u17-l1-q5',
            type: 'judge',
            prompt: '幂零矩阵 $N=\\begin{pmatrix}0&1\\\\0&0\\end{pmatrix}$ 满足 $N^2=0$，所以 $e^{Nt}=I+Nt$。',
            answer: true,
            explain: '$N^2=0$ 使级数截断：$e^{Nt}=I+Nt=\\begin{pmatrix}1&t\\\\0&1\\end{pmatrix}$，这是一个剪切变换。',
          },
        ],
      },
      {
        id: 'u17-l2',
        title: '解线性系统与对角化',
        subtitle: '$\\mathbf x(t)=e^{At}\\mathbf x_0$ 与 $Pe^{Dt}P^{-1}$',
        questions: [
          {
            id: 'u17-l2-q1',
            type: 'choice',
            prompt: '线性系统 $\\mathbf x\'(t)=A\\mathbf x(t)$、$\\mathbf x(0)=\\mathbf x_0$ 的解是？',
            options: [
              '$\\mathbf x(t)=A^t\\mathbf x_0$',
              '$\\mathbf x(t)=e^{At}\\mathbf x_0$',
              '$\\mathbf x(t)=e^{A}t\\,\\mathbf x_0$',
              '$\\mathbf x(t)=\\mathbf x_0+At$',
            ],
            answer: 1,
            explain: '因为 $\\frac{d}{dt}e^{At}=Ae^{At}$ 且 $e^{A\\cdot0}=I$，故 $\\mathbf x(t)=e^{At}\\mathbf x_0$ 同时满足方程与初值。',
          },
          {
            id: 'u17-l2-q2',
            type: 'choice',
            prompt: '若 $A=PDP^{-1}$ 可对角化，则 $e^{At}=?$',
            options: ['$Pe^{Dt}P^{-1}$', '$P^{-1}e^{Dt}P$', '$e^{Pt}D$', '$PDP^{-1}t$'],
            answer: 0,
            explain: '$A^k=PD^kP^{-1}$ 代回级数得 $e^{At}=Pe^{Dt}P^{-1}$，把矩阵问题降成标量指数。',
          },
          {
            id: 'u17-l2-q3',
            type: 'input',
            prompt: '设 $A=\\begin{pmatrix}1&0\\\\0&-2\\end{pmatrix}$，则 $e^{At}$ 左上角元素是 $e^t$，右下角元素是什么？',
            accept: ['e^{-2t}', 'e^-2t', 'e^(-2t)', 'exp(-2t)', 'e^{-2 t}'],
            explain: '对角矩阵的指数逐个对角元取指数：$e^{At}=\\begin{pmatrix}e^t&0\\\\0&e^{-2t}\\end{pmatrix}$。',
          },
          {
            id: 'u17-l2-q4',
            type: 'judge',
            prompt: '对角矩阵 $D=\\operatorname{diag}(\\lambda_1,\\dots,\\lambda_n)$ 的指数就是 $\\operatorname{diag}(e^{\\lambda_1 t},\\dots,e^{\\lambda_n t})$。',
            answer: true,
            explain: '对角阵各方向互不耦合，逐个对角元取指数即可，这正是对角化求 $e^{At}$ 的核心便利。',
          },
          {
            id: 'u17-l2-q5',
            type: 'match',
            prompt: '把对角化求 $e^{At}$ 的步骤按顺序配对。',
            left: ['第 1 步', '第 2 步', '第 3 步', '第 4 步'],
            right: ['求特征值与特征向量', '写出 $A=PDP^{-1}$', '对角元取指数得 $e^{Dt}$', '乘回得 $Pe^{Dt}P^{-1}$'],
            explain: '先找系统最自然的坐标轴，再在各轴上做标量指数演化，最后变换回原坐标。',
          },
        ],
      },
      {
        id: 'u17-l3',
        title: '旋转、振荡与稳定性',
        subtitle: '从特征值实部读出系统命运',
        questions: [
          {
            id: 'u17-l3-q1',
            type: 'choice',
            prompt: '旋转矩阵 $J=\\begin{pmatrix}0&-1\\\\1&0\\end{pmatrix}$ 的指数 $e^{Jt}$ 等于？',
            options: [
              '$\\begin{pmatrix}\\cos t&-\\sin t\\\\\\sin t&\\cos t\\end{pmatrix}$',
              '$\\begin{pmatrix}e^t&0\\\\0&e^t\\end{pmatrix}$',
              '$\\begin{pmatrix}1&t\\\\0&1\\end{pmatrix}$',
              '$\\begin{pmatrix}\\cosh t&\\sinh t\\\\\\sinh t&\\cosh t\\end{pmatrix}$',
            ],
            answer: 0,
            explain: '$J^2=-I$ 使级数分出 $\\cos t\\,I+\\sin t\\,J$，即旋转矩阵；这把复指数旋转推广到了实平面。',
          },
          {
            id: 'u17-l3-q2',
            type: 'choice',
            prompt: '系统 $\\mathbf x\'=A\\mathbf x$ 的长期行为主要由什么决定？',
            options: [
              '矩阵元素之和',
              '特征值的实部',
              '矩阵的行列式符号',
              '矩阵的大小',
            ],
            answer: 1,
            explain: '某方向大致像 $e^{\\lambda t}$：$\\operatorname{Re}(\\lambda)>0$ 增长，$<0$ 衰减，$=0$ 常对应振荡。',
          },
          {
            id: 'u17-l3-q3',
            type: 'judge',
            prompt: '若矩阵 $A$ 全部特征值的实部都小于 0，则系统倾向于衰减到 0（稳定）。',
            answer: true,
            explain: '每个方向像 $e^{\\lambda t}$，实部全为负时各方向都衰减，状态向量整体趋于原点。',
          },
          {
            id: 'u17-l3-q4',
            type: 'judge',
            prompt: '对任意矩阵 $A,B$ 总有 $e^{A+B}=e^A e^B$。',
            answer: false,
            explain: '错。只有当 $AB=BA$（可交换）时才成立，因为矩阵乘法一般不可交换。',
          },
          {
            id: 'u17-l3-q5',
            type: 'choice',
            prompt: '纯虚特征值（如 $\\pm 2i$）常对应什么样的系统行为？',
            options: [
              '指数爆炸增长',
              '无衰减的振荡或旋转',
              '立即衰减到 0',
              '系统不动',
            ],
            answer: 1,
            explain: '纯虚特征值实部为 0，对应单位圆式旋转——如 $e^{At}$ 退化成旋转矩阵，轨迹是绕原点的圆。',
          },
          {
            id: 'u17-l3-q6',
            type: 'input',
            prompt: '若 $A=\\begin{pmatrix}3&0\\\\0&-1\\end{pmatrix}$，系统在第一分量方向按 $e^{3t}$ 演化，那第二分量方向按什么演化？',
            accept: ['e^{-t}', 'e^-t', 'e^(-t)', 'exp(-t)', 'e^{- t}'],
            explain: '$e^{At}=\\begin{pmatrix}e^{3t}&0\\\\0&e^{-t}\\end{pmatrix}$：第一方向增长、第二方向 $e^{-t}$ 衰减。',
          },
        ],
      },
    ],
  },
]
