import type { Unit } from '../../types'

// 第二部分：图像、变换与反函数（第 4–6 章）
export const PART2_UNITS: Unit[] = [
  // ===================== 单元 4：图像·变换·比较 =====================
  {
    id: 'u4',
    title: '图像·变换·比较',
    color: '#ff9600',
    icon: '🔀',
    blurb: '读懂 $y=a^x$ 的图像：平移翻折、增减陡缓与底数大小比较。',
    lessons: [
      {
        id: 'u4-l1',
        title: '基本图像与趋势',
        subtitle: '定点、渐近线、增减',
        questions: [
          {
            id: 'u4-l1-q1',
            type: 'choice',
            prompt: '所有形如 $y=a^x$（$a>0,a\\neq 1$）的图像都一定经过哪个定点？',
            options: ['$(1,0)$', '$(0,1)$', '$(0,0)$', '$(1,1)$'],
            answer: 1,
            explain: '因为 $a^0=1$，所以无论底数是多少，图像都过 $(0,1)$。',
          },
          {
            id: 'u4-l1-q2',
            type: 'judge',
            prompt: '判断：当 $0<a<1$ 时，$y=a^x$ 从左到右递减。',
            answer: true,
            explain: '$0<a<1$ 时函数递减，向右逐渐贴近 $0$；$a>1$ 时才递增。',
          },
          {
            id: 'u4-l1-q3',
            type: 'choice',
            prompt: '最基本的 $y=a^x$ 的水平渐近线是哪一条？',
            options: ['$x=0$', '$y=1$', '$y=0$', '$y=a$'],
            answer: 2,
            explain: '$a>1$ 时 $x\\to-\\infty$、$0<a<1$ 时 $x\\to+\\infty$，都有 $a^x\\to 0$，故渐近线为 $y=0$。',
          },
          {
            id: 'u4-l1-q4',
            type: 'input',
            prompt: '$y=a^x$ 的值域是 $($____$,+\\infty)$，请填入横线处的数。',
            accept: ['0', '0.0', '零'],
            explain: '指数输出永远为正，故值域为 $(0,+\\infty)$。',
          },
          {
            id: 'u4-l1-q5',
            type: 'choice',
            prompt: '底数越大（$a>1$），图像在 $x>0$ 一侧表现为？',
            options: ['越平缓', '越陡峭', '不变', '先陡后缓'],
            answer: 1,
            explain: '$a>1$ 时底数越大，右侧上升越快，曲线越陡。',
          },
          {
            id: 'u4-l1-q6',
            type: 'judge',
            prompt: '判断：$y=a^x$ 的图像会与 $x$ 轴相交。',
            answer: false,
            explain: '$a^x$ 永远取不到 $0$，图像始终在 $x$ 轴上方，不相交。',
          },
        ],
      },
      {
        id: 'u4-l2',
        title: '一般形式与变换',
        subtitle: '$y=Aa^{x-h}+k$',
        questions: [
          {
            id: 'u4-l2-q1',
            type: 'choice',
            prompt: '在 $y=Aa^{x-h}+k$ 中，谁决定水平渐近线的位置？',
            options: ['$A$', '$a$', '$h$', '$k$'],
            answer: 3,
            explain: '整体加 $k$ 把曲线上下平移，渐近线变成 $y=k$。',
          },
          {
            id: 'u4-l2-q2',
            type: 'judge',
            prompt: '判断：$y=a^{x-h}$（$h>0$）是把 $y=a^x$ 向右平移 $h$ 个单位。',
            answer: true,
            explain: '当 $x=h$ 时指数为 $0$、锚点跑到 $(h,1)$，说明向右平移 $h$。',
          },
          {
            id: 'u4-l2-q3',
            type: 'choice',
            prompt: '当 $A<0$ 时，$y=Aa^x$ 的图像相对基础图像发生了什么？',
            options: ['向右平移', '关于 $x$ 轴翻折', '向上平移', '没有变化'],
            answer: 1,
            explain: '负系数把图像翻到 $x$ 轴另一侧（关于 $x$ 轴翻折），并伴随竖直伸缩。',
          },
          {
            id: 'u4-l2-q4',
            type: 'input',
            prompt: '$y=3^{x+1}-2$ 的水平渐近线是 $y=$____。',
            accept: ['-2', '−2'],
            explain: '$k=-2$，故渐近线为 $y=-2$。',
          },
          {
            id: 'u4-l2-q5',
            type: 'choice',
            prompt: '对 $y=Aa^{x-h}+k$，当 $x=h$ 时图像经过的点是？',
            options: ['$(h,k)$', '$(h,A+k)$', '$(h,A)$', '$(0,A+k)$'],
            answer: 1,
            explain: '$x=h$ 时 $a^{x-h}=1$，于是 $y=A\\cdot 1+k=A+k$，过 $(h,A+k)$。',
          },
          {
            id: 'u4-l2-q6',
            type: 'match',
            prompt: '把 $y=Aa^{x-h}+k$ 中的参数与它控制的几何作用配对：',
            left: ['$h$', '$k$', '$A$', '$a$'],
            right: ['水平平移', '渐近线 / 竖直平移', '竖直伸缩与翻折', '原始增减与快慢'],
            explain: '$h$ 管左右、$k$ 管上下与渐近线、$A$ 管伸缩翻折、$a$ 管增减陡缓。',
          },
        ],
      },
      {
        id: 'u4-l3',
        title: '底数比较与反推',
        subtitle: '分区间比大小，由图猜式',
        questions: [
          {
            id: 'u4-l3-q1',
            type: 'choice',
            prompt: '在 $x>0$ 时，$2^x$ 与 $3^x$ 的大小关系是？',
            options: ['$2^x>3^x$', '$2^x<3^x$', '$2^x=3^x$', '无法确定'],
            answer: 1,
            explain: '$x>0$ 时底数越大幂越大，故 $3^x>2^x$。',
          },
          {
            id: 'u4-l3-q2',
            type: 'judge',
            prompt: '判断：在 $x<0$ 时仍有 $3^x>2^x$。',
            answer: false,
            explain: '负指数化为倒数，$3^{-1}=\\frac13<\\frac12=2^{-1}$，关系反转，此时 $3^x<2^x$。',
          },
          {
            id: 'u4-l3-q3',
            type: 'input',
            prompt: '比较 $2^{1.5}$ 与 $2^{1.7}$，较大者的指数是____（填 1.5 或 1.7）。',
            accept: ['1.7', '1.70'],
            explain: '底数 $2>1$ 函数递增，指数大者值大，故 $2^{1.7}$ 更大。',
          },
          {
            id: 'u4-l3-q4',
            type: 'choice',
            prompt: '某图像渐近线为 $y=1$ 且整体在其下方，反推 $A$ 的符号应为？',
            options: ['$A>0$', '$A=0$', '$A<0$', '与 $A$ 无关'],
            answer: 2,
            explain: '在渐近线下方说明 $A<0$（图像被翻到下侧）。',
          },
          {
            id: 'u4-l3-q5',
            type: 'judge',
            prompt: '判断：$y=-4^x$ 的图像始终在 $x$ 轴下方。',
            answer: true,
            explain: '$-4^x=-(4^x)$，$4^x>0$ 故整体为负，图像在 $x$ 轴下方。',
          },
          {
            id: 'u4-l3-q6',
            type: 'choice',
            prompt: '比较异底同指数 $3^{0.4}$ 与 $4^{0.4}$（指数 $0.4>0$）：',
            options: ['$3^{0.4}>4^{0.4}$', '$3^{0.4}<4^{0.4}$', '相等', '无法比较'],
            answer: 1,
            explain: '指数同为正，底数越大幂越大，故 $3^{0.4}<4^{0.4}$。',
          },
        ],
      },
    ],
  },

  // ===================== 单元 5：对数作为反函数 =====================
  {
    id: 'u5',
    title: '对数作为反函数',
    color: '#ff4b4b',
    icon: '🔄',
    blurb: '$a^x$ 与 $\\log_a x$ 互为反函数，关于 $y=x$ 对称。',
    lessons: [
      {
        id: 'u5-l1',
        title: '定义与反函数关系',
        subtitle: '$\\log_a x=y\\iff a^y=x$',
        questions: [
          {
            id: 'u5-l1-q1',
            type: 'input',
            prompt: '由定义求 $\\log_2 8=$____。',
            accept: ['3'],
            explain: '问“$2$ 的几次方等于 $8$”，$2^3=8$，故为 $3$。',
          },
          {
            id: 'u5-l1-q2',
            type: 'choice',
            prompt: '$\\log_a x=y$ 与下列哪个式子等价？',
            options: ['$x^y=a$', '$a^y=x$', '$y^a=x$', '$a^x=y$'],
            answer: 1,
            explain: '对数定义：$\\log_a x=y\\iff a^y=x$。',
          },
          {
            id: 'u5-l1-q3',
            type: 'judge',
            prompt: '判断：对任意合法底数都有 $\\log_a 1=0$。',
            answer: true,
            explain: '$a^0=1$，故 $\\log_a 1=0$，这是对数图像过 $(1,0)$ 的原因。',
          },
          {
            id: 'u5-l1-q4',
            type: 'choice',
            prompt: '下列哪个恒等式正确（$x>0$）？',
            options: ['$\\log_a(a^x)=a$', '$a^{\\log_a x}=x$', '$\\log_a x=a^x$', '$a^{\\log_a x}=a$'],
            answer: 1,
            explain: '互为反函数的两条核心恒等式：$\\log_a(a^x)=x$ 与 $a^{\\log_a x}=x$。',
          },
          {
            id: 'u5-l1-q5',
            type: 'input',
            prompt: '$\\log_5 5=$____。',
            accept: ['1'],
            explain: '$5^1=5$，故 $\\log_5 5=1$；一般地 $\\log_a a=1$。',
          },
          {
            id: 'u5-l1-q6',
            type: 'match',
            prompt: '把对数值与其等价的指数事实配对：',
            left: ['$\\log_2 8$', '$\\log_3 1$', '$\\log_5 5$', '$\\log_2 \\tfrac14$'],
            right: ['$2^3=8$', '$3^0=1$', '$5^1=5$', '$2^{-2}=\\tfrac14$'],
            explain: '每个对数值都对应一条“底数的几次方等于真数”的指数事实。',
          },
        ],
      },
      {
        id: 'u5-l2',
        title: '定义域、值域与对称',
        subtitle: '关于 $y=x$ 对称，真数 $x>0$',
        questions: [
          {
            id: 'u5-l2-q1',
            type: 'choice',
            prompt: '$y=\\log_a x$ 的定义域是？',
            options: ['$\\mathbb R$', '$(0,+\\infty)$', '$[0,+\\infty)$', '$(-\\infty,0)$'],
            answer: 1,
            explain: '指数函数输出恒为正，其反函数的输入（真数）只能取正，故定义域 $(0,+\\infty)$。',
          },
          {
            id: 'u5-l2-q2',
            type: 'judge',
            prompt: '判断：$y=a^x$ 与 $y=\\log_a x$ 的图像关于直线 $y=x$ 对称。',
            answer: true,
            explain: '互为反函数的图像必关于 $y=x$ 对称。',
          },
          {
            id: 'u5-l2-q3',
            type: 'choice',
            prompt: '指数函数的定点 $(0,1)$ 在对数图像上对应哪个点？',
            options: ['$(1,0)$', '$(0,1)$', '$(1,1)$', '$(0,0)$'],
            answer: 0,
            explain: '关于 $y=x$ 对称即交换横纵坐标，$(0,1)\\leftrightarrow(1,0)$。',
          },
          {
            id: 'u5-l2-q4',
            type: 'input',
            prompt: '$y=\\log_a x$ 的值域是全体实数，记作 ____（用一个符号填）。',
            accept: ['R', '\\mathbb R', 'ℝ', '实数', '全体实数'],
            explain: '指数函数自变量取遍 $\\mathbb R$，翻译过来对数值域为 $\\mathbb R$。',
          },
          {
            id: 'u5-l2-q5',
            type: 'choice',
            prompt: '$y=\\log_a x$ 的竖直渐近线是？',
            options: ['$y=0$', '$x=1$', '$x=0$', '$y=x$'],
            answer: 2,
            explain: '指数函数水平渐近线 $y=0$ 对称翻译为对数的竖直渐近线 $x=0$。',
          },
          {
            id: 'u5-l2-q6',
            type: 'judge',
            prompt: '判断：当 $a>1$ 时 $y=\\log_a x$ 递增。',
            answer: true,
            explain: '$a>1$ 时指数递增，其反函数也递增；$0<a<1$ 时则同为递减。',
          },
        ],
      },
      {
        id: 'u5-l3',
        title: '运算律与换底',
        subtitle: '乘变加、幂变乘、统一到 $\\ln$',
        questions: [
          {
            id: 'u5-l3-q1',
            type: 'choice',
            prompt: '$\\log_a(MN)$ 等于？',
            options: ['$\\log_a M\\cdot\\log_a N$', '$\\log_a M+\\log_a N$', '$\\log_a M-\\log_a N$', '$\\log_a(M+N)$'],
            answer: 1,
            explain: '乘法降维成加法：$\\log_a(MN)=\\log_a M+\\log_a N$。',
          },
          {
            id: 'u5-l3-q2',
            type: 'input',
            prompt: '化简 $\\log_2 24-\\log_2 3=$____。',
            accept: ['3'],
            explain: '$\\log_2\\frac{24}{3}=\\log_2 8=3$。',
          },
          {
            id: 'u5-l3-q3',
            type: 'judge',
            prompt: '判断：$\\log(a+b)=\\log a+\\log b$。',
            answer: false,
            explain: '这是典型错误！加法的对数没有这种拆分律，只有乘法 $\\log(ab)=\\log a+\\log b$。',
          },
          {
            id: 'u5-l3-q4',
            type: 'choice',
            prompt: '换底公式 $\\log_a x$ 等于下列哪一项？',
            options: ['$\\frac{\\ln a}{\\ln x}$', '$\\frac{\\ln x}{\\ln a}$', '$\\ln x\\cdot\\ln a$', '$\\ln(x-a)$'],
            answer: 1,
            explain: '换底到 $e$：$\\log_a x=\\frac{\\ln x}{\\ln a}$。',
          },
          {
            id: 'u5-l3-q5',
            type: 'input',
            prompt: '已知 $\\log_a 2=m,\\ \\log_a 3=n$，则 $\\log_a 12=$____（用 $m,n$ 表示，如 2m+n）。',
            accept: ['2m+n', 'n+2m', '2*m+n', 'n+2*m'],
            explain: '$12=2^2\\cdot 3$，故 $\\log_a 12=2\\log_a 2+\\log_a 3=2m+n$。',
          },
          {
            id: 'u5-l3-q6',
            type: 'choice',
            prompt: '桥梁公式 $a^x=e^{?}$，问号处应填？',
            options: ['$x\\ln a$', '$a\\ln x$', '$x+\\ln a$', '$\\frac{x}{\\ln a}$'],
            answer: 0,
            explain: '由 $a=e^{\\ln a}$ 得 $a^x=e^{x\\ln a}$，把一般底数统一到自然指数。',
          },
        ],
      },
    ],
  },

  // ===================== 单元 6：增长·衰减·翻倍时间 =====================
  {
    id: 'u6',
    title: '增长·衰减·翻倍时间',
    color: '#2bd4a6',
    icon: '⏳',
    blurb: '按比例变化：增长、衰减、倍增时间、半衰期与 70 法则。',
    lessons: [
      {
        id: 'u6-l1',
        title: '增长与衰减模型',
        subtitle: '$N_0e^{kt}$ 与按比例变化',
        questions: [
          {
            id: 'u6-l1-q1',
            type: 'choice',
            prompt: '指数变化与线性变化的根本区别是？',
            options: [
              '每步加固定量 vs 每步乘固定比例',
              '都加固定量',
              '都乘固定比例',
              '没有区别',
            ],
            answer: 0,
            explain: '线性=每步加固定量；指数=每步乘固定比例（变化率与当前规模挂钩）。',
          },
          {
            id: 'u6-l1-q2',
            type: 'choice',
            prompt: '在 $N(t)=N_0e^{kt}$ 中，$N_0$ 表示什么？',
            options: ['增长常数', '$t=0$ 时的初值', '半衰期', '渐近值'],
            answer: 1,
            explain: '$N_0$ 是 $t=0$ 时的数量，即初值。',
          },
          {
            id: 'u6-l1-q3',
            type: 'judge',
            prompt: '判断：连续衰减 $N(t)=N_0e^{-kt}$（$k>0$）会在有限时间内精确变成 $0$。',
            answer: false,
            explain: '$e^{-kt}$ 越来越小但恒为正，只趋近 $0$，不会在有限时间真正等于 $0$。',
          },
          {
            id: 'u6-l1-q4',
            type: 'choice',
            prompt: '$N(t)=N_0e^{kt}$ 表示衰减，应满足？',
            options: ['$k>0$', '$k<0$', '$N_0<0$', '$t<0$'],
            answer: 1,
            explain: '指数为正时是增长；若写成 $e^{kt}$ 且 $k<0$（即等价 $e^{-|k|t}$）才是衰减。',
          },
          {
            id: 'u6-l1-q5',
            type: 'judge',
            prompt: '判断：“某菌群越大，单位时间新增越多”体现了指数模型“变化率与当前规模挂钩”的特征。',
            answer: true,
            explain: '正是按比例变化：规模越大、同一比例下的增量越大。',
          },
          {
            id: 'u6-l1-q6',
            type: 'input',
            prompt: '若 $N(t)=100\\cdot 2^{t}$，则 $t=3$ 时 $N=$____。',
            accept: ['800'],
            explain: '$100\\cdot 2^3=100\\cdot 8=800$。',
          },
        ],
      },
      {
        id: 'u6-l2',
        title: '倍增时间与半衰期',
        subtitle: '都等于 $\\dfrac{\\ln 2}{k}$',
        questions: [
          {
            id: 'u6-l2-q1',
            type: 'choice',
            prompt: '增长模型 $N_0e^{kt}$ 的倍增时间 $T_d$ 等于？',
            options: ['$\\frac{k}{\\ln 2}$', '$\\frac{\\ln 2}{k}$', '$k\\ln 2$', '$\\frac{1}{k}$'],
            answer: 1,
            explain: '由 $e^{kT_d}=2$ 取对数得 $kT_d=\\ln 2$，故 $T_d=\\frac{\\ln 2}{k}$。',
          },
          {
            id: 'u6-l2-q2',
            type: 'judge',
            prompt: '判断：在统一约定下，倍增时间与半衰期都写成 $\\dfrac{\\ln 2}{k}$。',
            answer: true,
            explain: '增长用 $e^{kt}$、衰减用 $e^{-kt}$ 且都取 $k>0$，符号由前面承担，故两特征时间同形。',
          },
          {
            id: 'u6-l2-q3',
            type: 'input',
            prompt: '某物质每 $6$ 小时减半，初始 $80$g，则 $18$ 小时后剩____g。',
            accept: ['10'],
            explain: '$18$ 小时 $=3$ 个半衰期，$80\\times(\\tfrac12)^3=10$g。',
          },
          {
            id: 'u6-l2-q4',
            type: 'choice',
            prompt: '已知半衰期 $T_{1/2}$，则衰减常数 $k=$？',
            options: ['$\\frac{\\ln 2}{T_{1/2}}$', '$\\frac{T_{1/2}}{\\ln 2}$', '$T_{1/2}\\ln 2$', '$\\ln 2-T_{1/2}$'],
            answer: 0,
            explain: '由 $T_{1/2}=\\frac{\\ln 2}{k}$ 反解得 $k=\\frac{\\ln 2}{T_{1/2}}$。',
          },
          {
            id: 'u6-l2-q5',
            type: 'judge',
            prompt: '判断：特征时间（倍增时间/半衰期）越短，变化越快。',
            answer: true,
            explain: '$k=\\frac{\\ln 2}{T}$，$T$ 越小则 $k$ 越大，变化越快。',
          },
          {
            id: 'u6-l2-q6',
            type: 'input',
            prompt: '连续复利 $k=0.05$/年，用 $70$ 法则估倍增年数约为____年（填整数）。',
            accept: ['14'],
            explain: '$70/5=14$；精确为 $\\ln 2/0.05\\approx 13.86\\approx 14$ 年。',
          },
        ],
      },
      {
        id: 'u6-l3',
        title: '建模与反求参数',
        subtitle: '把文字题翻译成模型',
        questions: [
          {
            id: 'u6-l3-q1',
            type: 'choice',
            prompt: '“某药物变为原来的 $80\\%$”对应乘以多少？',
            options: ['乘 $0.2$', '乘 $0.8$', '乘 $1.8$', '乘 $0.08$'],
            answer: 1,
            explain: '“变为原来的 $80\\%$”=剩下 $0.8N_0$，即乘 $0.8$；“减少了 $80\\%$”才是乘 $0.2$。',
          },
          {
            id: 'u6-l3-q2',
            type: 'judge',
            prompt: '判断：“增加了 $80\\%$”表示变成原来的 $1.8$ 倍。',
            answer: true,
            explain: '增加了 $80\\%$ 即乘 $1+0.8=1.8$。注意与“变为原来的 $80\\%$”（乘 $0.8$）区分。',
          },
          {
            id: 'u6-l3-q3',
            type: 'choice',
            prompt: '已知初值 $N_0$ 与 $N(t_1)=N_1$，连续模型的 $k=$？',
            options: [
              '$\\frac{1}{t_1}\\ln\\frac{N_1}{N_0}$',
              '$t_1\\ln\\frac{N_0}{N_1}$',
              '$\\frac{N_1}{N_0 t_1}$',
              '$\\ln(N_1-N_0)$',
            ],
            answer: 0,
            explain: '由 $N_1=N_0e^{kt_1}$ 解得 $k=\\frac{1}{t_1}\\ln\\frac{N_1}{N_0}$。',
          },
          {
            id: 'u6-l3-q4',
            type: 'judge',
            prompt: '判断：若 $N_1>N_0$，则反求出的 $k>0$，说明是增长。',
            answer: true,
            explain: '$N_1/N_0>1$ 时 $\\ln$ 为正，故 $k>0$，方向写在比值里。',
          },
          {
            id: 'u6-l3-q5',
            type: 'input',
            prompt: '用户数 $2000$ 人，$3$ 个月后到 $2420$ 人，则 $e^{3k}=$____（小数）。',
            accept: ['1.21', '1.21,'],
            explain: '$\\frac{2420}{2000}=1.21$，即 $e^{3k}=1.21$，于是 $k=\\frac13\\ln 1.21$。',
          },
          {
            id: 'u6-l3-q6',
            type: 'choice',
            prompt: '题目给“每年增长 $4\\%$”，应优先想到哪类参数？',
            options: ['倍增时间', '半衰期', '速率参数 $k$', '初值'],
            answer: 2,
            explain: '给的是速率类信息，优先对应速率参数 $k$；“几年翻倍/几天减半”才对应特征时间。',
          },
        ],
      },
    ],
  },
]
