import type { Unit } from '../../types'

export const PART1_UNITS: Unit[] = [
  // ===================== 单元 1：重复乘法与幂 =====================
  {
    id: 'u1',
    title: '重复乘法与幂',
    color: '#58cc02',
    icon: '🌱',
    blurb: '从“同样的倍率不断重复”出发，掌握整数、零、负、分数指数，并感受指数爆炸。',
    lessons: [
      {
        id: 'u1-l1',
        title: '幂就是重复乘法',
        subtitle: '把 a 重复乘 n 次',
        questions: [
          {
            id: 'u1-l1-q1',
            type: 'choice',
            prompt: '$2^5$ 表示什么？',
            options: [
              '把 5 重复乘 2 次',
              '把 2 重复乘 5 次（5 个 2 相乘）',
              '2 乘以 5',
              '2 加 5 次',
            ],
            answer: 1,
            explain: '$2^5=2\\cdot2\\cdot2\\cdot2\\cdot2=32$，底数 2 被重复乘 5 次。',
          },
          {
            id: 'u1-l1-q2',
            type: 'input',
            prompt: '计算 $3^4$。',
            accept: ['81'],
            placeholder: '输入一个整数',
            explain: '$3^4=3\\cdot3\\cdot3\\cdot3=81$。',
          },
          {
            id: 'u1-l1-q3',
            type: 'judge',
            prompt: '判断：$2^3=2\\cdot3=6$。',
            answer: false,
            explain: '幂是重复乘法不是相乘。$2^3=2\\cdot2\\cdot2=8$，不是 $2\\cdot3$。',
          },
          {
            id: 'u1-l1-q4',
            type: 'choice',
            prompt: '比较 $2,4,6,8,\\dots$ 与 $2,4,8,16,\\dots$，后者每一步在做什么？',
            options: ['每次加 2', '每次乘 2', '每次加 4', '每次平方'],
            answer: 1,
            explain: '前者是线性（每次加 2，差值思维），后者是指数（每次乘 2，倍率思维）。',
          },
          {
            id: 'u1-l1-q5',
            type: 'input',
            prompt: '一个量初始为 1，连续翻倍 6 次后变为多少？（即求 $2^6$）',
            accept: ['64'],
            placeholder: '输入一个整数',
            explain: '翻倍 $n$ 次即乘 $2^n$，$2^6=64$。',
          },
          {
            id: 'u1-l1-q6',
            type: 'match',
            prompt: '把每个幂与它的值配对。',
            left: ['$2^3$', '$3^2$', '$5^2$', '$2^6$'],
            right: ['8', '9', '25', '64'],
            explain: '$2^3=8,\\ 3^2=9,\\ 5^2=25,\\ 2^6=64$。底数和指数都会影响结果。',
          },
        ],
      },
      {
        id: 'u1-l2',
        title: '零指数与负指数',
        subtitle: '为什么 $a^0=1$、$a^{-n}=1/a^n$',
        questions: [
          {
            id: 'u1-l2-q1',
            type: 'choice',
            prompt: '当 $a\\neq0$ 时，$a^0$ 等于多少？',
            options: ['0', '1', 'a', '没有意义'],
            answer: 1,
            explain: '由 $\\frac{a^m}{a^m}=a^{m-m}=a^0$，而 $\\frac{a^m}{a^m}=1$，故 $a^0=1$。',
          },
          {
            id: 'u1-l2-q2',
            type: 'judge',
            prompt: '判断：$2^{-3}=-8$。',
            answer: false,
            explain: '负指数表示倒数，不是相反数。$2^{-3}=\\dfrac{1}{2^3}=\\dfrac18$。',
          },
          {
            id: 'u1-l2-q3',
            type: 'input',
            prompt: '计算 $2^{-3}$（用分数表示，如 1/8）。',
            accept: ['1/8', '0.125'],
            placeholder: '例如 1/8',
            explain: '$2^{-3}=\\dfrac{1}{2^3}=\\dfrac18$。',
          },
          {
            id: 'u1-l2-q4',
            type: 'choice',
            prompt: '$\\left(\\tfrac12\\right)^2$ 等于？',
            options: ['$\\tfrac14$', '$\\tfrac12$', '1', '$\\tfrac11$'],
            answer: 0,
            explain: '$\\left(\\tfrac12\\right)^2=\\tfrac12\\cdot\\tfrac12=\\tfrac14$。',
          },
          {
            id: 'u1-l2-q5',
            type: 'input',
            prompt: '化简 $10^4\\cdot10^{-2}$。',
            accept: ['100', '10^2', '10²'],
            placeholder: '输入一个整数',
            explain: '同底相乘指数相加：$10^{4+(-2)}=10^2=100$。',
          },
          {
            id: 'u1-l2-q6',
            type: 'match',
            prompt: '把每个表达式与它的值配对。',
            left: ['$5^0$', '$3^{-1}$', '$2^{-2}$', '$10^{-1}$'],
            right: ['1', '$\\tfrac13$', '$\\tfrac14$', '$0.1$'],
            explain: '$5^0=1$（零指数）；$3^{-1}=\\tfrac13,\\ 2^{-2}=\\tfrac14,\\ 10^{-1}=0.1$（负指数取倒数）。',
          },
        ],
      },
      {
        id: 'u1-l3',
        title: '分数指数与科学记数法',
        subtitle: '开方与数量级',
        questions: [
          {
            id: 'u1-l3-q1',
            type: 'choice',
            prompt: '$16^{1/2}$ 等于多少？',
            options: ['8', '4', '32', '256'],
            answer: 1,
            explain: '分数指数 $\\tfrac12$ 表示开平方：$16^{1/2}=\\sqrt{16}=4$。',
          },
          {
            id: 'u1-l3-q2',
            type: 'input',
            prompt: '计算 $8^{2/3}$。',
            accept: ['4'],
            placeholder: '输入一个整数',
            explain: '先开三次方再平方：$8^{2/3}=(8^{1/3})^2=2^2=4$。',
          },
          {
            id: 'u1-l3-q3',
            type: 'judge',
            prompt: '判断：$a^{m/n}=\\sqrt[n]{a^m}$（$a>0$）。',
            answer: true,
            explain: '分母 $n$ 管开几次方，分子 $m$ 管乘方几次，二者可交换次序。',
          },
          {
            id: 'u1-l3-q4',
            type: 'input',
            prompt: '把 $53000$ 写成科学记数法 $a\\times10^n$，n 等于多少？',
            accept: ['4'],
            placeholder: '输入指数 n',
            explain: '$53000=5.3\\times10^4$，小数点左移 4 位，故 $n=4$。',
          },
          {
            id: 'u1-l3-q5',
            type: 'choice',
            prompt: '$0.00072$ 的科学记数法是？',
            options: [
              '$7.2\\times10^{4}$',
              '$7.2\\times10^{-4}$',
              '$72\\times10^{-5}$',
              '$0.72\\times10^{-3}$',
            ],
            answer: 1,
            explain: '小数对应负指数，小数点右移 4 位：$0.00072=7.2\\times10^{-4}$。',
          },
          {
            id: 'u1-l3-q6',
            type: 'choice',
            prompt: '不直接算大数，比较 $2^{30}$ 与 $10^9$。哪个大？',
            options: [
              '$10^9$ 大',
              '一样大',
              '$2^{30}$ 大',
              '无法比较',
            ],
            answer: 2,
            explain: '$2^{30}=(2^{10})^3=1024^3$，$10^9=1000^3$，底数 $1024>1000$，故 $2^{30}>10^9$。',
          },
        ],
      },
    ],
  },

  // ===================== 单元 2：定义·定义域·形状 =====================
  {
    id: 'u2',
    title: '定义·定义域·形状',
    color: '#1cb0f6',
    icon: '📈',
    blurb: '$y=a^x$ 的定义条件、过 (0,1)、恒正、x 轴渐近线，以及底数决定的增长或衰减。',
    lessons: [
      {
        id: 'u2-l1',
        title: '什么是指数函数',
        subtitle: '$y=a^x$ 的合法底数',
        questions: [
          {
            id: 'u2-l1-q1',
            type: 'choice',
            prompt: '指数函数 $y=a^x$ 对底数 $a$ 的要求是？',
            options: [
              '$a>0$ 即可',
              '$a>0$ 且 $a\\neq1$',
              '$a\\neq0$',
              '$a$ 为任意实数',
            ],
            answer: 1,
            explain: '$a\\le0$ 时 $a^x$ 在实数范围内对很多 $x$ 无意义；$a=1$ 时恒为 1，过于平凡。',
          },
          {
            id: 'u2-l1-q2',
            type: 'judge',
            prompt: '判断：$a=-3$ 可以作为指数函数 $y=a^x$ 的底数。',
            answer: false,
            explain: '$a$ 必须大于 0。例如 $(-3)^{1/2}$ 不是实数，所以负底数不行。',
          },
          {
            id: 'u2-l1-q3',
            type: 'judge',
            prompt: '判断：$y=1^x$ 是一个标准的指数函数。',
            answer: false,
            explain: '$1^x\\equiv1$ 是水平直线，没有增长或衰减信息，故排除 $a=1$。',
          },
          {
            id: 'u2-l1-q4',
            type: 'choice',
            prompt: '下列哪个是合法的指数函数底数？',
            options: ['$a=0$', '$a=1$', '$a=\\tfrac12$', '$a=-2$'],
            answer: 2,
            explain: '只有 $a=\\tfrac12$ 满足 $a>0$ 且 $a\\neq1$（属衰减型）。',
          },
          {
            id: 'u2-l1-q5',
            type: 'match',
            prompt: '判断每个底数是否合法，与结论配对。',
            left: ['$a=2$', '$a=1$', '$a=-3$', '$a=\\tfrac13$'],
            right: ['合法（增长型）', '不合法（恒为 1）', '不合法（负底数）', '合法（衰减型）'],
            explain: '$a>0$ 且 $a\\neq1$ 才合法；$a>1$ 增长、$0<a<1$ 衰减。',
          },
        ],
      },
      {
        id: 'u2-l2',
        title: '定义域、值域与三锚点',
        subtitle: '恒过 (0,1)、恒正、x 轴渐近',
        questions: [
          {
            id: 'u2-l2-q1',
            type: 'choice',
            prompt: '指数函数 $y=a^x$ 的定义域是？',
            options: ['$x>0$', '全体实数 $\\mathbb{R}$', '$x\\ge0$', '$x\\neq0$'],
            answer: 1,
            explain: '指数位置可取任意实数，定义域为 $\\mathbb{R}$；常见错误是误写成 $x>0$。',
          },
          {
            id: 'u2-l2-q2',
            type: 'choice',
            prompt: '指数函数 $y=a^x$ 的值域是？',
            options: ['$\\mathbb{R}$', '$[0,+\\infty)$', '$(0,+\\infty)$', '$(-\\infty,0)$'],
            answer: 2,
            explain: '只要 $a>0$ 就有 $a^x>0$，且能取到任意正数，但永远取不到 0。',
          },
          {
            id: 'u2-l2-q3',
            type: 'judge',
            prompt: '判断：任何指数函数 $y=a^x$ 的图像都经过点 $(0,1)$。',
            answer: true,
            explain: '因为 $a^0=1$，所以图像恒过 $(0,1)$。这是最稳的锚点之一。',
          },
          {
            id: 'u2-l2-q4',
            type: 'input',
            prompt: '对 $y=3^x$，求 $x=-1$ 时的函数值（用分数表示）。',
            accept: ['1/3', '0.333', '0.3333'],
            placeholder: '例如 1/3',
            explain: '$3^{-1}=\\tfrac13$，对应锚点 $(-1,\\tfrac1a)$。',
          },
          {
            id: 'u2-l2-q5',
            type: 'match',
            prompt: '把 $y=3^x$ 上的三个锚点横坐标与函数值配对。',
            left: ['$x=-1$', '$x=0$', '$x=1$', '$x=2$'],
            right: ['$\\tfrac13$', '1', '3', '9'],
            explain: '三锚点 $(-1,\\tfrac1a),(0,1),(1,a)$：$3^{-1}=\\tfrac13,\\ 3^0=1,\\ 3^1=3,\\ 3^2=9$。',
          },
          {
            id: 'u2-l2-q6',
            type: 'judge',
            prompt: '判断：当 $a>1$ 且 $x\\to-\\infty$ 时，$a^x$ 会无限贴近 0 但永不等于 0。',
            answer: true,
            explain: '$x$ 轴（$y=0$）是水平渐近线；$a^x>0$ 恒成立，故贴近但不触及。',
          },
        ],
      },
      {
        id: 'u2-l3',
        title: '底数决定增长还是衰减',
        subtitle: '$a>1$ 增、$0<a<1$ 减',
        questions: [
          {
            id: 'u2-l3-q1',
            type: 'choice',
            prompt: '当 $a>1$ 时，$y=a^x$ 的单调性是？',
            options: ['单调递增', '单调递减', '先增后减', '常值'],
            answer: 0,
            explain: '$a>1$ 时每向右一步都乘以大于 1 的因子，函数值放大，单调递增。',
          },
          {
            id: 'u2-l3-q2',
            type: 'choice',
            prompt: '当 $0<a<1$ 时，$y=a^x$ 的单调性是？',
            options: ['单调递增', '单调递减', '不单调', '常值'],
            answer: 1,
            explain: '$0<a<1$ 时每步乘以小于 1 的因子，函数值缩小，单调递减（衰减型）。',
          },
          {
            id: 'u2-l3-q3',
            type: 'judge',
            prompt: '判断：底数更大的指数函数在任意 $x$ 处函数值都更大。',
            answer: false,
            explain: '不对。如 $5^x$ 与 $2^x$：在 $x=2$ 时 $5^2>2^2$，但在 $x=-2$ 时 $5^{-2}<2^{-2}$。要结合区间。',
          },
          {
            id: 'u2-l3-q4',
            type: 'input',
            prompt: '指数函数 $y=a^x$ 的图像过点 $(2,9)$，求底数 $a$。',
            accept: ['3'],
            placeholder: '输入底数 a',
            explain: '$a^2=9$ 得 $a=3$ 或 $a=-3$，由 $a>0$ 舍去 $-3$，故 $a=3$。',
          },
          {
            id: 'u2-l3-q5',
            type: 'choice',
            prompt: '设 $a>0,a\\neq1$。不等式 $a^2<a^3$ 在什么时候成立？',
            options: [
              '$0<a<1$ 时',
              '$a>1$ 时',
              '所有 $a$ 都成立',
              '永不成立',
            ],
            answer: 1,
            explain: '$a^3-a^2=a^2(a-1)$，因 $a^2>0$，符号由 $a-1$ 决定，故 $a>1$ 时 $a^2<a^3$。',
          },
          {
            id: 'u2-l3-q6',
            type: 'choice',
            prompt: '$y=\\left(\\tfrac12\\right)^x$ 可以重写成下列哪个？',
            options: ['$2^x$', '$2^{-x}$', '$-2^x$', '$x^2$'],
            answer: 1,
            explain: '$\\left(\\tfrac12\\right)^x=(2^{-1})^x=2^{-x}$，把衰减写成熟悉的增长底数的镜像。',
          },
        ],
      },
    ],
  },

  // ===================== 单元 3：指数法则·易错 =====================
  {
    id: 'u3',
    title: '指数法则·易错',
    color: '#ce82ff',
    icon: '🧩',
    blurb: '积/商/幂法则、分数指数与根式互化、负指数对称，以及把加法和乘方混用等常见错误。',
    lessons: [
      {
        id: 'u3-l1',
        title: '四条基本运算律',
        subtitle: '乘、除、幂的乘方、积的乘方',
        questions: [
          {
            id: 'u3-l1-q1',
            type: 'choice',
            prompt: '$a^m\\cdot a^n$ 等于？',
            options: ['$a^{mn}$', '$a^{m+n}$', '$a^{m-n}$', '$2a^{m+n}$'],
            answer: 1,
            explain: '同底相乘指数相加：$m$ 个 $a$ 再接 $n$ 个 $a$，共 $m+n$ 个。',
          },
          {
            id: 'u3-l1-q2',
            type: 'input',
            prompt: '化简 $2^3\\cdot2^4$（用 2 的幂或数值）。',
            accept: ['128', '2^7', '2⁷'],
            placeholder: '例如 2^7 或 128',
            explain: '$2^3\\cdot2^4=2^{3+4}=2^7=128$。',
          },
          {
            id: 'u3-l1-q3',
            type: 'choice',
            prompt: '$(5^2)^3$ 等于？',
            options: ['$5^5$', '$5^6$', '$5^8$', '$25^3$'],
            answer: 1,
            explain: '幂的乘方指数相乘：$(5^2)^3=5^{2\\cdot3}=5^6$。',
          },
          {
            id: 'u3-l1-q4',
            type: 'input',
            prompt: '化简 $\\dfrac{3^6}{3^2}$（用 3 的幂或数值）。',
            accept: ['81', '3^4', '3⁴'],
            placeholder: '例如 3^4 或 81',
            explain: '同底相除指数相减：$\\dfrac{3^6}{3^2}=3^{6-2}=3^4=81$。',
          },
          {
            id: 'u3-l1-q5',
            type: 'match',
            prompt: '把每条运算律与它的结果配对。',
            left: ['$a^m\\cdot a^n$', '$\\dfrac{a^m}{a^n}$', '$(a^m)^n$', '$(ab)^n$'],
            right: ['$a^{m+n}$', '$a^{m-n}$', '$a^{mn}$', '$a^n b^n$'],
            explain: '四条核心律：相乘加、相除减、幂的乘方相乘、积的乘方各自乘方。',
          },
          {
            id: 'u3-l1-q6',
            type: 'choice',
            prompt: '化简 $\\dfrac{2^{x+1}\\cdot4^{x-1}}{8^x}$（统一为 2 的幂）。',
            options: ['$2^{-1}=\\tfrac12$', '$2$', '$2^x$', '$1$'],
            answer: 0,
            explain: '$4^{x-1}=2^{2x-2},8^x=2^{3x}$，指数 $(x+1)+(2x-2)-3x=-1$，结果 $2^{-1}=\\tfrac12$。',
          },
        ],
      },
      {
        id: 'u3-l2',
        title: '分数指数与根式互化',
        subtitle: '分母管开方、分子管乘方',
        questions: [
          {
            id: 'u3-l2-q1',
            type: 'choice',
            prompt: '$\\sqrt[3]{a^2}$（$a>0$）写成分数指数是？',
            options: ['$a^{3/2}$', '$a^{2/3}$', '$a^{6}$', '$a^{2}$'],
            answer: 1,
            explain: '根指数 3 作分母、被开方的指数 2 作分子：$\\sqrt[3]{a^2}=a^{2/3}$。',
          },
          {
            id: 'u3-l2-q2',
            type: 'input',
            prompt: '化简 $\\sqrt[3]{a^2}\\cdot\\sqrt{a}$（$a>0$），写成 $a$ 的分数指数幂。',
            accept: ['a^{7/6}', 'a^7/6', 'a^(7/6)', 'a^7/6'],
            placeholder: '例如 a^{7/6}',
            explain: '$a^{2/3}\\cdot a^{1/2}=a^{2/3+1/2}=a^{7/6}$（通分 $\\tfrac46+\\tfrac36$）。',
          },
          {
            id: 'u3-l2-q3',
            type: 'judge',
            prompt: '判断：$\\sqrt[3]{a^6}=a^2$（$a>0$）。',
            answer: true,
            explain: '$\\sqrt[3]{a^6}=a^{6/3}=a^2$。',
          },
          {
            id: 'u3-l2-q4',
            type: 'choice',
            prompt: '化简 $\\left(a^{1/2}b^{-1/3}\\right)^6$（$a,b>0$）。',
            options: ['$a^3 b^{-2}$', '$a^3 b^2$', '$a^{1/3}b^{-2}$', '$ab$'],
            answer: 0,
            explain: '括号外指数乘到每个因子：$a^{(1/2)\\cdot6}b^{(-1/3)\\cdot6}=a^3 b^{-2}=\\dfrac{a^3}{b^2}$。',
          },
          {
            id: 'u3-l2-q5',
            type: 'input',
            prompt: '把 $\\sqrt{2\\sqrt2}$ 写成 2 的分数指数幂。',
            accept: ['2^{3/4}', '2^3/4', '2^(3/4)', '2^3/4'],
            placeholder: '例如 2^{3/4}',
            explain: '$2\\sqrt2=2^{3/2}$，再开方乘 $\\tfrac12$：$(2^{3/2})^{1/2}=2^{3/4}$。',
          },
          {
            id: 'u3-l2-q6',
            type: 'judge',
            prompt: '判断：$(-1)^{1/2}$ 在实数范围内有意义。',
            answer: false,
            explain: '负数的偶次方根（如 $\\sqrt{-1}$）不在实数范围内，所以分数指数要求 $a>0$。',
          },
        ],
      },
      {
        id: 'u3-l3',
        title: '常见陷阱与负指数对称',
        subtitle: '别把加法和乘方混用',
        questions: [
          {
            id: 'u3-l3-q1',
            type: 'judge',
            prompt: '判断：$(a+b)^2=a^2+b^2$。',
            answer: false,
            explain: '乘方不能分配到加法上。$(a+b)^2=a^2+2ab+b^2$，少了 $2ab$。',
          },
          {
            id: 'u3-l3-q2',
            type: 'choice',
            prompt: '$(a+b)^2$ 正确展开是？',
            options: [
              '$a^2+b^2$',
              '$a^2+2ab+b^2$',
              '$a^2-b^2$',
              '$a^2+ab+b^2$',
            ],
            answer: 1,
            explain: '取 $a=1,b=2$ 验证：$(1+2)^2=9$，而 $a^2+b^2=5$，差的正是 $2ab=4$。',
          },
          {
            id: 'u3-l3-q3',
            type: 'choice',
            prompt: '$8^x$ 统一成 2 的底数是？',
            options: ['$2^{8x}$', '$2^{3x}$', '$2^{x+3}$', '$2^{x/3}$'],
            answer: 1,
            explain: '$8=2^3$，故 $8^x=(2^3)^x=2^{3x}$。统一底数是同底比较的关键。',
          },
          {
            id: 'u3-l3-q4',
            type: 'judge',
            prompt: '判断：$y=2^x$ 与 $y=2^{-x}$ 的图像关于 $y$ 轴对称。',
            answer: true,
            explain: '$2^{-x}=\\left(\\tfrac12\\right)^x$，把 $x$ 换成 $-x$ 即沿 $y$ 轴翻转，如 $(2,4)$ 与 $(-2,4)$ 互为镜像。',
          },
          {
            id: 'u3-l3-q5',
            type: 'input',
            prompt: '已知 $2^x=3$，求 $\\dfrac{8^x+2^{-x}}{4^x}$（结果用分数）。',
            accept: ['82/27'],
            placeholder: '例如 82/27',
            explain: '令 $t=2^x=3$：原式 $=\\dfrac{t^3+1/t}{t^2}=t+\\dfrac{1}{t^3}=3+\\dfrac{1}{27}=\\dfrac{82}{27}$。',
          },
          {
            id: 'u3-l3-q6',
            type: 'match',
            prompt: '把每个式子与正确结论配对。',
            left: ['$(a^m)^n$', '$(ab)^n$', '$(a+b)^2$', '$2^{-x}$'],
            right: ['$a^{mn}$', '$a^n b^n$', '$a^2+2ab+b^2$', '$\\left(\\tfrac12\\right)^x$'],
            explain: '前两条是合法运算律；第三条提醒乘方不分配到加法；第四条是负指数对称重写。',
          },
        ],
      },
    ],
  },
]
