import type { Lesson } from '../../src/types'

export const LESSONS: Lesson[] = [
  {
    id: 'c17-a',
    title: '广义积分：无穷限与瑕积分',
    subtitle: '把"无穷"纳入积分——极限定义、p/q-积分判别',
    intro: [
      {
        title: '为什么需要广义积分？',
        body: '普通定积分要求：区间 $[a,b]$ **有限**，被积函数在其上**有界**。\n\n现实中两种情形突破了这个限制：\n\n**①** 积分区间伸到无穷远，例如 $\\int_1^{+\\infty}\\frac{1}{x^2}\\,dx$——物理中计算引力场、概率中求正态分布归一化常数都会遇到。\n\n**②** 被积函数在端点处趋向无穷大，例如 $\\int_0^1\\frac{1}{\\sqrt{x}}\\,dx$（$x=0$ 处被积函数爆炸）。\n\n这两类积分统称**广义积分**（反常积分）。核心思想：用**极限**绕开"无穷"，先在有限范围内算，再取极限。',
        tip: '广义积分的结果可能存在（收敛）也可能爆到无穷（发散）——"写得出来"不代表"有意义"，必须验证极限存在。',
      },
      {
        title: '无穷上限积分——定义',
        body: '设 $f(x)$ 在 $[a,+\\infty)$ 上连续。先对有限区间 $[a,b]$ 积分，再令 $b\\to+\\infty$：',
        formula: '\\int_a^{+\\infty} f(x)\\,dx = \\lim_{b\\to+\\infty}\\int_a^b f(x)\\,dx',
        steps: [
          '若极限**存在且有限** → 广义积分**收敛**，该极限值即积分值',
          '若极限为 $\\pm\\infty$ 或不存在 → 广义积分**发散**',
          '类似地，$\\int_{-\\infty}^b f\\,dx = \\lim_{a\\to-\\infty}\\int_a^b f\\,dx$',
          '双无穷积分 $\\int_{-\\infty}^{+\\infty}f\\,dx$：**必须**拆成两段，两段都收敛才算收敛',
        ],
        tip: '双无穷积分不能写成 $\\lim_{R\\to+\\infty}\\int_{-R}^R f\\,dx$（那是 Cauchy 主值，与收敛是两回事！）',
      },
      {
        title: '具体计算：$\\int_1^{+\\infty}\\frac{1}{x^2}\\,dx$ 和 $\\int_1^{+\\infty}\\frac{1}{x}\\,dx$',
        body: '先算 $\\int_1^{+\\infty}\\frac{1}{x^2}\\,dx$：',
        steps: [
          '先算有限段：$\\int_1^b \\frac{1}{x^2}\\,dx = \\left[-\\frac{1}{x}\\right]_1^b = 1 - \\frac{1}{b}$',
          '令 $b\\to+\\infty$：$1-\\frac{1}{b}\\to 1$',
          '结论：$\\int_1^{+\\infty}\\frac{1}{x^2}\\,dx = 1$，**收敛**',
        ],
        reveal: {
          q: '那 $\\int_1^{+\\infty}\\frac{1}{x}\\,dx$ 呢？按同样步骤算一算。',
          a: '$\\int_1^b\\frac{1}{x}\\,dx = \\ln b\\to+\\infty$，故**发散**。两者差别仅在指数 1 vs 2——这引出了 p-积分判别准则。',
        },
      },
      {
        title: 'p-积分：无穷限的黄金参照',
        body: '$\\displaystyle\\int_1^{+\\infty}\\frac{1}{x^p}\\,dx$ 是所有收敛性比较的参照标准。当 $p\\neq 1$ 时，先算有限段：$\\int_1^b x^{-p}\\,dx = \\frac{x^{1-p}}{1-p}\\Big|_1^b = \\frac{b^{1-p}-1}{1-p}$。\n\n当 $p>1$：$1-p<0$，$b^{1-p}\\to 0$，极限存在，积分收敛于 $\\dfrac{1}{p-1}$。\n\n当 $p<1$：$1-p>0$，$b^{1-p}\\to+\\infty$，**发散**。\n\n当 $p=1$：化为 $\\ln b\\to+\\infty$，**发散**。',
        formula: '\\int_1^{+\\infty}\\frac{1}{x^p}\\,dx \\begin{cases} \\text{收敛} = \\dfrac{1}{p-1} & p>1 \\\\ \\text{发散} & p\\leq 1 \\end{cases}',
        tip: '记忆：无穷上限 p-积分，临界点 $p=1$，**大于 1 才收敛**。',
      },
      {
        title: '瑕积分——被积函数在端点无界',
        body: '**瑕点**：若 $f(x)$ 在某点附近无界（趋向 $\\pm\\infty$），该点称为瑕点。\n\n若 $x=a$ 是瑕点，$f$ 在 $(a,b]$ 上连续：',
        formula: '\\int_a^b f(x)\\,dx = \\lim_{\\varepsilon\\to 0^+}\\int_{a+\\varepsilon}^b f(x)\\,dx',
        steps: [
          '用 $\\varepsilon>0$ 避开奇点 $a$，先算 $[a+\\varepsilon,\\, b]$ 上的普通积分',
          '再令 $\\varepsilon\\to 0^+$：极限存在则收敛',
          '若瑕点在 $b$：$\\int_a^b f\\,dx = \\lim_{\\varepsilon\\to 0^+}\\int_a^{b-\\varepsilon}f\\,dx$',
          '若瑕点在**内部** $c\\in(a,b)$：必须拆成 $\\int_a^c + \\int_c^b$，两段独立判断',
        ],
        tip: '内部瑕点不可漏！直接算 $\\int_{-1}^1 \\frac{1}{x^2}\\,dx$ 得 $-2$ 是经典错误——$x=0$ 是瑕点，$\\int_0^1 \\frac{1}{x^2}\\,dx$ 其实发散，故整体发散。',
      },
      {
        title: 'q-积分：瑕积分的黄金参照',
        body: '与无穷限 p-积分相对，瑕积分有 q-积分作参照（瑕点在 $x=0$）：\n\n当 $q\\neq 1$：$\\int_\\varepsilon^1 x^{-q}\\,dx = \\dfrac{x^{1-q}}{1-q}\\Big|_\\varepsilon^1 = \\dfrac{1-\\varepsilon^{1-q}}{1-q}$\n\n当 $0<q<1$：$1-q>0$，$\\varepsilon^{1-q}\\to 0$，收敛于 $\\dfrac{1}{1-q}$。\n\n当 $q>1$：$1-q<0$，$\\varepsilon^{1-q}\\to+\\infty$，**发散**。\n\n当 $q=1$：$-\\ln\\varepsilon\\to+\\infty$，**发散**。',
        formula: '\\int_0^1\\frac{1}{x^q}\\,dx \\begin{cases} \\text{收敛} = \\dfrac{1}{1-q} & 0<q<1 \\\\ \\text{发散} & q\\geq 1 \\end{cases}',
        tip: '**临界值相反**：无穷限 p-积分 $p>1$ 收；瑕积分 q-积分 $q<1$ 收。两者恰好对称！',
      },
      {
        title: '瑕积分计算例：$\\int_0^1\\ln x\\,dx$',
        body: '$x=0$ 是瑕点（$\\ln x\\to-\\infty$）。用分部积分处理。',
        steps: [
          '令 $\\varepsilon\\to 0^+$，先算 $\\int_\\varepsilon^1 \\ln x\\,dx$',
          '分部积分：$u=\\ln x$，$dv=dx$，$v=x$',
          '$\\int_\\varepsilon^1\\ln x\\,dx = [x\\ln x]_\\varepsilon^1 - \\int_\\varepsilon^1 dx = (0 - \\varepsilon\\ln\\varepsilon) - (1-\\varepsilon)$',
          '关键极限：$\\lim_{\\varepsilon\\to 0^+}\\varepsilon\\ln\\varepsilon = 0$（用洛必达：$\\lim\\frac{\\ln\\varepsilon}{1/\\varepsilon} = \\lim(-\\varepsilon)=0$）',
          '令 $\\varepsilon\\to 0^+$：结果 $= 0 - 1 = -1$',
        ],
        reveal: {
          q: '为什么先分部再取极限，而不是先取极限再分部？',
          a: '取极限"之前"才是普通定积分，分部积分法只对普通定积分成立。若先令 $\\varepsilon\\to 0$，积分本身就已经是广义积分，没有定义可以直接分部。',
        },
      },
      {
        title: '易错点总结',
        body: '学完无穷限与瑕积分，以下四个坑最常见：',
        steps: [
          '**忘记验证收敛性**：写出 $F(b)-F(a)$ 就以为求出了广义积分，但若 $F(b)\\to\\infty$ 则发散，结论无效',
          '**p/q 临界值混淆**：无穷限 $p>1$ 收，瑕积分 $q<1$ 收——两者方向相反',
          '**内部瑕点遗漏**：$\\int_{-1}^1 f\\,dx$ 必须先检查区间内部是否有奇点',
          '**Cauchy 主值当收敛用**：$\\lim_{R\\to+\\infty}\\int_{-R}^R f\\,dx$ 存在 $\\neq$ 广义积分收敛',
        ],
        tip: '遇到广义积分，第一步：**识别所有奇点**（包括区间内部）；第二步：逐段判断；第三步：才能计算。',
      },
    ],
    questions: [
      {
        id: 'c17-a-q1',
        type: 'judge',
        prompt: '判断命题：$\\int_1^{+\\infty}\\frac{1}{x}\\,dx$ 收敛，其值为 $+\\infty$。',
        answer: false,
        explain: '错误。广义积分发散时不能说"值为 $+\\infty$"——"发散"意味着极限**不存在（或无穷）**，积分没有值可言。$\\int_1^{+\\infty}\\frac{1}{x}\\,dx$ 是发散的（p-积分 $p=1\\leq 1$）。',
      },
      {
        id: 'c17-a-q2',
        type: 'choice',
        prompt: '$\\int_1^{+\\infty}\\frac{1}{x^{3/2}}\\,dx$ 的值是多少？',
        options: ['$1$', '$2$', '$3$', '发散'],
        answer: 1,
        explain: 'p-积分，$p=\\frac{3}{2}>1$，收敛。$\\int_1^{+\\infty}x^{-3/2}\\,dx = \\left[-2x^{-1/2}\\right]_1^{+\\infty} = 0-(-2) = 2$。',
      },
      {
        id: 'c17-a-q3',
        type: 'choice',
        prompt: '下列哪个积分**发散**？',
        options: [
          '$\\int_1^{+\\infty}\\frac{1}{x^2}\\,dx$',
          '$\\int_1^{+\\infty}\\frac{1}{x^{1.001}}\\,dx$',
          '$\\int_1^{+\\infty}\\frac{1}{x}\\,dx$',
          '$\\int_1^{+\\infty}e^{-x}\\,dx$',
        ],
        answer: 2,
        explain: '前三个都是 p-积分或类似形式：$p=2>1$ 收，$p=1.001>1$ 收，$p=1$ **发散**。$e^{-x}$ 衰减极快，积分值为 $e^{-1}$，收敛。答案是选项 C（$p=1$）。',
      },
      {
        id: 'c17-a-q4',
        type: 'input',
        prompt: '计算 $\\int_0^{+\\infty} e^{-x}\\,dx$（填整数或分数）。',
        accept: ['1'],
        explain: '$\\int_0^b e^{-x}\\,dx = [-e^{-x}]_0^b = 1-e^{-b}\\to 1$（$b\\to+\\infty$）。',
      },
      {
        id: 'c17-a-q5',
        type: 'judge',
        prompt: '$\\int_{-1}^{1}\\frac{1}{x^2}\\,dx$ 收敛，因为 $\\left[-\\frac{1}{x}\\right]_{-1}^{1} = -1-1 = -2$ 存在。',
        answer: false,
        explain: '这是经典错误！$x=0$ 是内部瑕点，必须先拆：$\\int_{-1}^0+\\int_0^1$。$\\int_0^1 x^{-2}\\,dx = \\lim_{\\varepsilon\\to 0^+}[-x^{-1}]_\\varepsilon^1 = \\lim(-1+\\varepsilon^{-1}) = +\\infty$，**发散**，故整体发散。',
      },
      {
        id: 'c17-a-q6',
        type: 'choice',
        prompt: '$\\int_0^1\\frac{1}{x^{2/3}}\\,dx$ 的值是？',
        options: ['$1$', '$2$', '$3$', '发散'],
        answer: 2,
        explain: 'q-积分，$q=\\frac{2}{3}<1$，收敛。$\\int_\\varepsilon^1 x^{-2/3}\\,dx = \\left[3x^{1/3}\\right]_\\varepsilon^1 = 3-3\\varepsilon^{1/3}\\to 3$。',
      },
      {
        id: 'c17-a-q7',
        type: 'match',
        prompt: '将下列广义积分与其敛散结论配对（p/q-积分参照）：',
        left: [
          '$\\int_1^{+\\infty}x^{-0.9}\\,dx$',
          '$\\int_0^1 x^{-0.9}\\,dx$',
          '$\\int_1^{+\\infty}x^{-1.1}\\,dx$',
          '$\\int_0^1 x^{-1.1}\\,dx$',
        ],
        right: ['发散（$p=0.9\\leq1$）', '收敛（$q=0.9<1$）', '收敛（$p=1.1>1$）', '发散（$q=1.1\\geq1$）'],
        explain: '无穷限 p-积分：$p>1$ 收；瑕 q-积分：$q<1$ 收。临界方向恰好相反，这是本章最重要的记忆点。',
      },
      {
        id: 'c17-a-q8',
        type: 'input',
        prompt: '计算瑕积分 $\\int_0^4\\frac{1}{\\sqrt{4-x}}\\,dx$（填整数）。',
        accept: ['4'],
        explain: '$x=4$ 是瑕点。令 $u=4-x$，$du=-dx$：$\\int_0^{4-\\varepsilon}(4-x)^{-1/2}\\,dx = \\int_\\varepsilon^4 u^{-1/2}\\,du = [2\\sqrt{u}]_\\varepsilon^4 = 4-2\\sqrt{\\varepsilon}\\to 4$。',
      },
    ],
  },
  {
    id: 'c17-b',
    title: '收敛判别与 Gamma 函数',
    subtitle: '比较法+极限比较法判敛，Gamma 函数化简含参积分',
    intro: [
      {
        title: '为什么需要判别法？',
        body: '许多广义积分的被积函数没有初等原函数，无法直接算出数值——例如 $\\int_1^{+\\infty}e^{-x^2}\\,dx$，找不到 $e^{-x^2}$ 的原函数。\n\n但我们仍然需要知道它**收敛还是发散**。判别法的思路：**把陌生积分与已知敛散性的参照积分做比较**，从大小关系推出结论，无需求出具体值。\n\n最常用的参照就是 p-积分 $\\int_1^{+\\infty}\\frac{1}{x^p}\\,dx$。',
        tip: '判别法只判敛散，不求值。若需要数值，还得换元或数值积分。',
      },
      {
        title: '比较判别法',
        body: '设 $0\\leq f(x)\\leq g(x)$ 在 $[a,+\\infty)$ 上成立：',
        steps: [
          '若"大的"$\\int_a^{+\\infty}g\\,dx$ **收敛**，则"小的"$\\int_a^{+\\infty}f\\,dx$ 也收敛（**大收小收**）',
          '若"小的"$\\int_a^{+\\infty}f\\,dx$ **发散**，则"大的"$\\int_a^{+\\infty}g\\,dx$ 也发散（**小散大散**）',
          '**应用**：$e^{-x^2}\\leq e^{-x}$（$x\\geq 1$ 时），$\\int_1^{+\\infty}e^{-x}\\,dx = e^{-1}$ 收敛，故 $\\int_1^{+\\infty}e^{-x^2}\\,dx$ 也收敛',
        ],
        tip: '比较判别法要求被积函数非负，且不等式只需在 $[a,+\\infty)$ 的**尾部**成立即可（有限段不影响敛散）。',
      },
      {
        title: '极限比较判别法——更灵活的版本',
        body: '直接构造不等式有时很难。若能算出两个函数之比的极限，可直接判断：\n\n设 $f,g\\geq 0$，且 $\\lim_{x\\to+\\infty}\\dfrac{f(x)}{g(x)} = l$，则：',
        steps: [
          '若 $0<l<+\\infty$（正有限数）：$\\int f$ 与 $\\int g$ **同敛散**',
          '若 $l=0$ 且 $\\int g$ 收敛：则 $\\int f$ 也收敛',
          '若 $l=+\\infty$ 且 $\\int g$ 发散：则 $\\int f$ 也发散',
          '**实战技巧**：取 $g(x)=1/x^p$，求 $l=\\lim_{x\\to+\\infty}x^p f(x)$，找合适的 $p$ 使 $l$ 为正有限数',
        ],
        reveal: {
          q: '判断 $\\int_1^{+\\infty}\\frac{x}{x^3+1}\\,dx$ 的敛散性，该取 $g(x)=?$',
          a: '当 $x\\to+\\infty$，$\\frac{x}{x^3+1}\\sim\\frac{x}{x^3}=\\frac{1}{x^2}$，取 $g=1/x^2$，极限比 $=\\lim\\frac{x^3}{x^3+1}=1$（正有限数），故与 $\\int_1^{+\\infty}1/x^2\\,dx$（$p=2>1$，收敛）同敛散：**收敛**。',
        },
      },
      {
        title: '绝对收敛与条件收敛',
        body: '当被积函数变号（如含 $\\sin x$），不能直接用比较法。引入两个层次：\n\n**绝对收敛**：$\\int_a^{+\\infty}|f(x)|\\,dx$ 收敛 → 原积分必然也收敛（绝对收敛推条件收敛）。\n\n**条件收敛**：$\\int_a^{+\\infty}f(x)\\,dx$ 收敛，但 $\\int_a^{+\\infty}|f(x)|\\,dx$ 发散。\n\n**例**：$\\int_1^{+\\infty}\\frac{\\sin x}{x^2}\\,dx$：因为 $\\left|\\frac{\\sin x}{x^2}\\right|\\leq\\frac{1}{x^2}$，而 $\\int_1^{+\\infty}\\frac{1}{x^2}\\,dx$ 收敛，故**绝对收敛**。\n\n**例**：$\\int_1^{+\\infty}\\frac{\\sin x}{x}\\,dx$：收敛（Dirichlet 判别法），但 $\\int_1^{+\\infty}\\frac{|\\sin x|}{x}\\,dx$ 发散，故**条件收敛**。',
        tip: '绝对收敛一定条件收敛，条件收敛不一定绝对收敛——与交错级数完全类比。',
      },
      {
        title: 'Gamma 函数——阶乘的连续延拓',
        body: '普通积分能轻松处理 $\\int_0^{+\\infty}x^n e^{-x}\\,dx$（$n$ 为正整数），反复分部积分得 $n!$。\n\nGamma 函数将此推广到所有 $s>0$：',
        formula: '\\Gamma(s) = \\int_0^{+\\infty} x^{s-1}e^{-x}\\,dx, \\quad s>0',
        steps: [
          '**收敛性**：在 $x=0$ 附近，$x^{s-1}e^{-x}\\sim x^{s-1}$，q-积分 $q=1-s<1$ 当 $s>0$ 时成立，故收敛',
          '在 $x=+\\infty$ 附近，$e^{-x}$ 衰减速度压倒任意幂函数，故无穷端也收敛',
          '**结论**：$s>0$ 时 $\\Gamma(s)$ 收敛，$s\\leq 0$ 时发散',
        ],
      },
      {
        title: 'Gamma 函数的递推公式',
        body: '$\\Gamma(s)$ 最核心的性质：分部积分推导递推关系。',
        formula: '\\Gamma(s+1) = s\\,\\Gamma(s)',
        steps: [
          '$\\Gamma(s+1)=\\int_0^{+\\infty}x^s e^{-x}\\,dx$，令 $u=x^s$，$dv=e^{-x}dx$',
          '$= \\left[-x^s e^{-x}\\right]_0^{+\\infty} + s\\int_0^{+\\infty}x^{s-1}e^{-x}\\,dx$',
          '边界项 $[-x^s e^{-x}]_0^{+\\infty}=0$（$x^s$ 增长比 $e^x$ 慢得多，$x\\to+\\infty$ 时趋零；$x\\to 0^+$ 时也趋零）',
          '故 $\\Gamma(s+1) = s\\,\\Gamma(s)$',
          '又 $\\Gamma(1) = \\int_0^{+\\infty}e^{-x}\\,dx = 1$，因此 $\\Gamma(n+1)=n!$',
        ],
        tip: '递推公式是计算 Gamma 函数的主要工具：$\\Gamma(5/2) = \\frac{3}{2}\\cdot\\Gamma(3/2) = \\frac{3}{2}\\cdot\\frac{1}{2}\\cdot\\Gamma(1/2) = \\frac{3}{4}\\sqrt{\\pi}$。',
      },
      {
        title: 'Gamma 函数的重要特殊值',
        body: '除了正整数点 $\\Gamma(n+1)=n!$，最重要的半整数值是：',
        formula: '\\Gamma\\!\\left(\\tfrac{1}{2}\\right) = \\sqrt{\\pi}',
        steps: [
          '$\\Gamma(1/2)=\\int_0^{+\\infty}x^{-1/2}e^{-x}\\,dx$，令 $x=t^2$，$dx=2t\\,dt$',
          '$=\\int_0^{+\\infty}t^{-1}e^{-t^2}\\cdot 2t\\,dt = 2\\int_0^{+\\infty}e^{-t^2}\\,dt$',
          '高斯积分 $\\int_0^{+\\infty}e^{-t^2}\\,dt = \\frac{\\sqrt{\\pi}}{2}$（来自二重积分极坐标法）',
          '故 $\\Gamma(1/2) = \\sqrt{\\pi}$',
          '推论：$\\Gamma(3/2)=\\frac{1}{2}\\Gamma(1/2)=\\frac{\\sqrt{\\pi}}{2}$',
        ],
      },
      {
        title: 'Gamma 函数的应用：换元化简',
        body: '含 $e^{-ax}$ 或 $e^{-x^2}$ 的幂函数积分，可通过换元统一化为 Gamma 函数：\n\n**类型一**：$\\int_0^{+\\infty}x^n e^{-ax}\\,dx$，令 $t=ax$：\n\n$= \\int_0^{+\\infty}\\left(\\frac{t}{a}\\right)^n e^{-t}\\frac{dt}{a} = \\frac{1}{a^{n+1}}\\int_0^{+\\infty}t^n e^{-t}\\,dt = \\frac{\\Gamma(n+1)}{a^{n+1}} = \\frac{n!}{a^{n+1}}$\n\n**类型二**：$\\int_0^{+\\infty}x^{2k}e^{-x^2}\\,dx$，令 $t=x^2$，$x=\\sqrt{t}$，$dx=\\frac{1}{2}t^{-1/2}dt$：\n\n$= \\frac{1}{2}\\int_0^{+\\infty}t^{k-1/2}e^{-t}\\,dt = \\frac{1}{2}\\Gamma\\!\\left(k+\\frac{1}{2}\\right)$',
        reveal: {
          q: '用公式计算 $\\int_0^{+\\infty}x^3 e^{-2x}\\,dx$。',
          a: '$n=3$，$a=2$，套公式 $\\frac{n!}{a^{n+1}} = \\frac{3!}{2^4} = \\frac{6}{16} = \\frac{3}{8}$。',
        },
      },
    ],
    questions: [
      {
        id: 'c17-b-q1',
        type: 'judge',
        prompt: '极限比较判别法：若 $\\lim_{x\\to+\\infty}\\frac{f(x)}{g(x)}=0$ 且 $\\int_1^{+\\infty}g\\,dx$ **发散**，则 $\\int_1^{+\\infty}f\\,dx$ 也发散。',
        answer: false,
        explain: '错。$l=0$ 时只能推：若参照 $g$ 收敛则 $f$ 收敛。若 $g$ 发散，$l=0$ 说明 $f$ "比 $g$ 小得多"，无法得出 $f$ 发散的结论。反例：$f=1/x^2$，$g=1/x$，比值 $\\to 0$，$g$ 发散，但 $f$ 收敛。',
      },
      {
        id: 'c17-b-q2',
        type: 'choice',
        prompt: '$\\int_1^{+\\infty}\\frac{2x+3}{x^3+x+1}\\,dx$ 的敛散性？',
        options: ['收敛', '发散', '无法判断', '收敛于 $2$'],
        answer: 0,
        explain: '$x\\to+\\infty$ 时，$\\frac{2x+3}{x^3+x+1}\\sim\\frac{2x}{x^3}=\\frac{2}{x^2}$。取 $g=1/x^2$，极限比 $\\to 2$（正有限数），与 $\\int_1^{+\\infty}1/x^2\\,dx$（$p=2>1$，收敛）同敛散，故**收敛**。',
      },
      {
        id: 'c17-b-q3',
        type: 'choice',
        prompt: '$\\int_1^{+\\infty}\\frac{\\sin x}{x^2}\\,dx$ 是：',
        options: ['绝对收敛', '条件收敛但不绝对收敛', '发散', '无法判断'],
        answer: 0,
        explain: '$|\\sin x/x^2|\\leq 1/x^2$，且 $\\int_1^{+\\infty}1/x^2\\,dx$ 收敛，由比较判别法，$\\int_1^{+\\infty}|\\sin x/x^2|\\,dx$ 收敛，故原积分**绝对收敛**。',
      },
      {
        id: 'c17-b-q4',
        type: 'input',
        prompt: '计算 $\\Gamma(5)$（填整数）。',
        accept: ['24'],
        explain: '$\\Gamma(5) = \\Gamma(4+1) = 4! = 24$。递推：$\\Gamma(5)=4\\cdot\\Gamma(4)=4\\cdot 3\\cdot\\Gamma(3)=4\\cdot 3\\cdot 2\\cdot\\Gamma(2)=4\\cdot 3\\cdot 2\\cdot 1\\cdot\\Gamma(1)=24$。',
      },
      {
        id: 'c17-b-q5',
        type: 'choice',
        prompt: '$\\int_0^{+\\infty}x^3 e^{-2x}\\,dx$ 等于？',
        options: ['$\\dfrac{3}{8}$', '$\\dfrac{3}{16}$', '$\\dfrac{6}{16}$', '$\\dfrac{1}{8}$'],
        answer: 0,
        explain: '令 $t=2x$，$x=t/2$，$dx=dt/2$：$\\int_0^{+\\infty}(t/2)^3 e^{-t}\\frac{dt}{2} = \\frac{1}{16}\\int_0^{+\\infty}t^3 e^{-t}\\,dt = \\frac{\\Gamma(4)}{16} = \\frac{3!}{16} = \\frac{6}{16} = \\frac{3}{8}$。',
      },
      {
        id: 'c17-b-q6',
        type: 'input',
        prompt: '$\\Gamma\\!\\left(\\dfrac{3}{2}\\right) = \\dfrac{\\sqrt{\\pi}}{k}$，$k$ 等于几？（填整数）',
        accept: ['2'],
        explain: '$\\Gamma(3/2) = \\frac{1}{2}\\cdot\\Gamma(1/2) = \\frac{1}{2}\\cdot\\sqrt{\\pi} = \\frac{\\sqrt{\\pi}}{2}$，故 $k=2$。',
      },
      {
        id: 'c17-b-q7',
        type: 'match',
        prompt: '将积分与对应的收敛判断配对：',
        left: [
          '$\\int_1^{+\\infty}e^{-x^2}\\,dx$',
          '$\\int_1^{+\\infty}\\frac{\\ln x}{x}\\,dx$',
          '$\\int_1^{+\\infty}\\frac{1}{x^2+1}\\,dx$',
          '$\\int_1^{+\\infty}\\frac{\\sin x}{x}\\,dx$',
        ],
        right: [
          '收敛（比较法：$e^{-x^2}\\leq e^{-x}$）',
          '发散（$\\ln x/x\\geq 1/x$，大于发散的调和级数被积函数）',
          '收敛（$1/(x^2+1)<1/x^2$，$p=2>1$）',
          '条件收敛（Dirichlet 判别法）',
        ],
        explain: '四种典型情形：纯比较法、下界法（找发散的下界）、简单比较法、振荡型条件收敛。',
      },
      {
        id: 'c17-b-q8',
        type: 'choice',
        prompt: '$\\int_0^{+\\infty}\\sqrt{x}\\,e^{-x}\\,dx$ 用 Gamma 函数表示为？',
        options: [
          '$\\Gamma(1/2)=\\sqrt{\\pi}$',
          '$\\Gamma(3/2)=\\dfrac{\\sqrt{\\pi}}{2}$',
          '$\\Gamma(2)=1$',
          '$\\Gamma(5/2)=\\dfrac{3\\sqrt{\\pi}}{4}$',
        ],
        answer: 1,
        explain: '$\\int_0^{+\\infty}x^{1/2}e^{-x}\\,dx = \\Gamma(1/2+1) = \\Gamma(3/2) = \\frac{1}{2}\\Gamma(1/2) = \\frac{\\sqrt{\\pi}}{2}$。注意：$x^{s-1}$ 中 $s-1=1/2$ 故 $s=3/2$。',
      },
    ],
  },
  {
    id: 'c17-c',
    title: 'Beta 函数与综合判别',
    subtitle: 'Beta 函数定义、与 Gamma 的关系、综合收敛判断',
    intro: [
      {
        title: 'Beta 函数是什么？',
        body: 'Beta 函数（$B$ 函数）是另一个重要的特殊函数，它也是以广义积分为定义，在 $[0,1]$ 上积分而不是 $[0,+\\infty)$：',
        formula: 'B(p,q) = \\int_0^1 x^{p-1}(1-x)^{q-1}\\,dx, \\quad p>0,\\,q>0',
        steps: [
          '$x=0$ 处：$x^{p-1}$ 在 $p<1$ 时是瑕点，q-积分判别：$p-1<0$ 即 $p<1$ 时是瑕点，但 $q=1-p>0$ 时收敛，故 $p>0$ 时 $x=0$ 端收敛',
          '$x=1$ 处：$(1-x)^{q-1}$ 类似，$q>0$ 时收敛',
          '故只要 $p>0,q>0$，$B(p,q)$ 收敛',
        ],
        tip: '$B(p,q)$ 在机器学习中是 Beta 分布、Dirichlet 分布的归一化常数，在注意力机制分析中也有应用。',
      },
      {
        title: 'Beta 函数的对称性',
        body: '$B(p,q)=B(q,p)$——交换两个参数，积分值不变。\n\n**证明**：在 $B(p,q)=\\int_0^1 x^{p-1}(1-x)^{q-1}\\,dx$ 中令 $t=1-x$，$dt=-dx$：',
        steps: [
          '$B(p,q)=\\int_1^0(1-t)^{p-1}t^{q-1}(-dt)=\\int_0^1 t^{q-1}(1-t)^{p-1}\\,dt = B(q,p)$',
          '几何直觉：$[0,1]$ 上的积分关于 $x=1/2$ 对称，交换 $p,q$ 等价于把 $x$ 换成 $1-x$',
        ],
      },
      {
        title: 'Beta 与 Gamma 的关系——最重要的性质',
        body: 'Beta 函数可以完全用 Gamma 函数表示：',
        formula: 'B(p,q) = \\dfrac{\\Gamma(p)\\,\\Gamma(q)}{\\Gamma(p+q)}',
        steps: [
          '对正整数 $m,n$：$B(m,n) = \\frac{(m-1)!(n-1)!}{(m+n-1)!}$',
          '特殊值：$B(1,1) = \\int_0^1 1\\,dx = 1$（验证：$\\frac{\\Gamma(1)\\Gamma(1)}{\\Gamma(2)}=\\frac{1}{1}=1$）',
          '$B(1/2,1/2) = \\frac{\\Gamma(1/2)^2}{\\Gamma(1)} = \\frac{\\pi}{1} = \\pi$',
          '由此 $\\int_0^1\\frac{1}{\\sqrt{x(1-x)}}\\,dx = B(1/2,1/2) = \\pi$',
        ],
        tip: '利用 $B(p,q)=\\frac{\\Gamma(p)\\Gamma(q)}{\\Gamma(p+q)}$，可以把形如 $\\int_0^1 x^{a}(1-x)^{b}\\,dx$ 的积分立即化为 Gamma 函数相除，避免繁琐计算。',
      },
      {
        title: 'Beta 函数计算例',
        body: '计算 $\\int_0^1 x^3(1-x)^4\\,dx$：\n\n被积函数形如 $x^{p-1}(1-x)^{q-1}$，对比得 $p-1=3$，$q-1=4$，故 $p=4$，$q=5$。',
        steps: [
          '$\\int_0^1 x^3(1-x)^4\\,dx = B(4,5)$',
          '$= \\frac{\\Gamma(4)\\Gamma(5)}{\\Gamma(9)} = \\frac{3!\\cdot 4!}{8!} = \\frac{6\\times 24}{40320}$',
          '$= \\frac{144}{40320} = \\frac{1}{280}$',
        ],
        reveal: {
          q: '如果用 $B(m,n)=(m-1)!(n-1)!/(m+n-1)!$ 直接套，会得到同样结果吗？',
          a: '$\\frac{(4-1)!(5-1)!}{(4+5-1)!} = \\frac{3!\\cdot 4!}{8!} = \\frac{6\\cdot 24}{40320} = \\frac{1}{280}$。完全一样。',
        },
      },
      {
        title: '综合判别：多奇点情形',
        body: '当积分区间含多个奇点时，必须拆段逐一处理。以 $\\int_0^1\\frac{1}{\\sqrt{x(1-x)}}\\,dx$ 为例：\n\n$x=0$ 和 $x=1$ 都是瑕点。',
        steps: [
          '拆为 $\\int_0^{1/2}+\\int_{1/2}^1$ 两段',
          '$x\\to 0^+$ 时，$\\frac{1}{\\sqrt{x(1-x)}}\\sim\\frac{1}{\\sqrt{x}}=x^{-1/2}$，q-积分 $q=1/2<1$，收敛',
          '$x\\to 1^-$ 时，令 $u=1-x$，$\\frac{1}{\\sqrt{x(1-x)}}\\sim u^{-1/2}$，同理收敛',
          '两段均收敛，故整体收敛，且用 Beta 函数给出精确值 $B(1/2,1/2)=\\pi$',
        ],
      },
      {
        title: '对称性快速计算',
        body: '双无穷积分若被积函数是偶函数，可以简化：\n\n$f(-x)=f(x)$（偶函数）时：$\\int_{-\\infty}^{+\\infty}f(x)\\,dx = 2\\int_0^{+\\infty}f(x)\\,dx$\n\n例：$\\int_{-\\infty}^{+\\infty}\\frac{1}{1+x^2}\\,dx$，被积函数是偶函数，\n\n$= 2\\int_0^{+\\infty}\\frac{1}{1+x^2}\\,dx = 2[\\arctan x]_0^{+\\infty} = 2\\cdot\\frac{\\pi}{2} = \\pi$\n\n若 $f$ 是奇函数，$\\int_{-\\infty}^{+\\infty}f\\,dx=0$（但需要各段都收敛才能这样用！）',
        tip: '奇函数整体积分为 0 的结论，**前提是两段积分都收敛**。若各段发散，即使函数是奇函数，也不能说整体为 0（这是 Cauchy 主值，不是广义积分）。',
      },
      {
        title: '本章方法速查',
        body: '遇到广义积分，按以下 4 步操作：',
        steps: [
          '**识别类型**：无穷限（上下限含 $\\pm\\infty$）还是瑕积分（区间内有无界点）？',
          '**直接计算**（若能找到原函数）：取极限，验证收敛性',
          '**比较/极限比较**（若无原函数）：找参照 $1/x^p$，极限比较法',
          '**Gamma/Beta 化简**（含 $x^s e^{-x}$ 或 $x^{p-1}(1-x)^{q-1}$ 形式）：换元后套公式',
        ],
        tip: '判断绝对 vs 条件收敛：先判 $\\int|f|$——绝对收敛最强；条件收敛次之；发散最弱。',
      },
    ],
    questions: [
      {
        id: 'c17-c-q1',
        type: 'choice',
        prompt: '$B(3,3) = ?$',
        options: [
          '$\\dfrac{1}{15}$',
          '$\\dfrac{1}{30}$',
          '$\\dfrac{1}{10}$',
          '$\\dfrac{1}{60}$',
        ],
        answer: 1,
        explain: '$B(3,3)=\\frac{\\Gamma(3)\\Gamma(3)}{\\Gamma(6)}=\\frac{2!\\cdot 2!}{5!}=\\frac{4}{120}=\\frac{1}{30}$。或用公式 $\\frac{(m-1)!(n-1)!}{(m+n-1)!}=\\frac{2!\\cdot 2!}{5!}=\\frac{4}{120}=\\frac{1}{30}$。',
      },
      {
        id: 'c17-c-q2',
        type: 'judge',
        prompt: '$\\int_0^1\\frac{1}{\\sqrt{x(1-x)}}\\,dx$ 因为 $x=0$ 和 $x=1$ 都是瑕点，所以该积分发散。',
        answer: false,
        explain: '错。两端都是瑕点不代表发散。$x=0$ 处被积函数 $\\sim x^{-1/2}$（$q=1/2<1$，收敛），$x=1$ 处同理收敛。整体 $=B(1/2,1/2)=\\pi$，**收敛**。',
      },
      {
        id: 'c17-c-q3',
        type: 'input',
        prompt: '$\\int_{-\\infty}^{+\\infty}\\frac{1}{1+x^2}\\,dx = ?$（填 $\\pi$ 或数字，用 \\pi 表示 π）',
        accept: ['\\pi', 'π', 'pi', '3.14159'],
        explain: '$1/(1+x^2)$ 是偶函数，$\\int_{-\\infty}^{+\\infty} = 2\\int_0^{+\\infty} = 2[\\arctan x]_0^{+\\infty} = 2\\cdot\\frac{\\pi}{2} = \\pi$。',
      },
      {
        id: 'c17-c-q4',
        type: 'judge',
        prompt: '$\\int_0^{+\\infty}x^{-1/2}e^{-x}\\,dx = \\sqrt{\\pi}$。',
        answer: true,
        explain: '$\\int_0^{+\\infty}x^{-1/2}e^{-x}\\,dx = \\int_0^{+\\infty}x^{1/2-1}e^{-x}\\,dx = \\Gamma(1/2) = \\sqrt{\\pi}$。这也是高斯积分 $\\int_{-\\infty}^{+\\infty}e^{-t^2}\\,dt=\\sqrt{\\pi}$ 的来源（令 $x=t^2$）。',
      },
      {
        id: 'c17-c-q5',
        type: 'choice',
        prompt: '$\\int_0^1 x^2(1-x)^3\\,dx$ 的正确值是？',
        options: [
          '$\\dfrac{1}{60}$',
          '$\\dfrac{1}{30}$',
          '$\\dfrac{1}{20}$',
          '$\\dfrac{1}{12}$',
        ],
        answer: 0,
        explain: '$p-1=2 \\Rightarrow p=3$，$q-1=3 \\Rightarrow q=4$。$B(3,4)=\\frac{\\Gamma(3)\\Gamma(4)}{\\Gamma(7)}=\\frac{2!\\cdot 3!}{6!}=\\frac{2\\times 6}{720}=\\frac{12}{720}=\\dfrac{1}{60}$。',
      },
      {
        id: 'c17-c-q6',
        type: 'judge',
        prompt: '$B(p,q) = B(q,p)$ 对所有 $p>0,q>0$ 成立。',
        answer: true,
        explain: '正确。令 $t=1-x$ 换元即可证明：积分区间 $[0,1]$ 关于中点对称，$p$ 和 $q$ 的角色互换。',
      },
      {
        id: 'c17-c-q7',
        type: 'match',
        prompt: '将积分与 Gamma 函数值配对：',
        left: [
          '$\\int_0^{+\\infty}e^{-x}\\,dx$',
          '$\\int_0^{+\\infty}xe^{-x}\\,dx$',
          '$\\int_0^{+\\infty}\\sqrt{x}\\,e^{-x}\\,dx$',
          '$\\int_0^{+\\infty}x^4 e^{-x}\\,dx$',
        ],
        right: [
          '$\\Gamma(1)=1$',
          '$\\Gamma(2)=1$',
          '$\\Gamma(3/2)=\\sqrt{\\pi}/2$',
          '$\\Gamma(5)=24$',
        ],
        explain: '对应关系：$\\int_0^{+\\infty}x^{s-1}e^{-x}\\,dx=\\Gamma(s)$。$e^{-x}=x^0 e^{-x}$：$s=1$；$xe^{-x}=x^1 e^{-x}$：$s=2$；$x^{1/2}e^{-x}$：$s=3/2$；$x^4 e^{-x}$：$s=5$。',
      },
      {
        id: 'c17-c-q8',
        type: 'input',
        prompt: '$\\int_0^{+\\infty} x^4 e^{-x^2}\\,dx = \\dfrac{k\\sqrt{\\pi}}{8}$，$k$ 等于几？（填整数）',
        accept: ['3'],
        explain: '令 $t=x^2$，$x=\\sqrt{t}$，$dx=\\frac{1}{2}t^{-1/2}dt$：$\\int_0^{+\\infty}t^2 e^{-t}\\cdot\\frac{1}{2}t^{-1/2}\\,dt = \\frac{1}{2}\\int_0^{+\\infty}t^{3/2}e^{-t}\\,dt = \\frac{1}{2}\\Gamma(5/2)$。$\\Gamma(5/2)=\\frac{3}{2}\\cdot\\frac{1}{2}\\cdot\\Gamma(1/2)=\\frac{3}{4}\\sqrt{\\pi}$，故结果 $=\\frac{1}{2}\\cdot\\frac{3}{4}\\sqrt{\\pi}=\\frac{3\\sqrt{\\pi}}{8}$，$k=3$。',
      },
    ],
  },
]
