import type { Unit } from '../../types'

// 内容取自《三角函数教程》第 4–6 章：基本恒等式 / 和差·倍角·半角 / 积化和差·和差化积。
// 公式用 $...$（KaTeX）。输入题的 accept 提供多种等价写法，配合容错匹配。

export const PART2_UNITS: Unit[] = [
  // ============================== 单元 4 ==============================
  {
    id: 'u4',
    title: '基本恒等式',
    color: '#ff9600',
    icon: '🧩',
    blurb: '$\\sin^2\\theta+\\cos^2\\theta=1$ 是一切三角恒等式的根',
    lessons: [
      {
        id: 'u4-l1',
        title: '平方关系',
        subtitle: '来自单位圆的勾股恒等式',
        questions: [
          {
            id: 'u4-l1-q1',
            type: 'choice',
            prompt: '$\\sin^2\\theta+\\cos^2\\theta=?$',
            options: ['$0$', '$1$', '$2$', '$\\tan\\theta$'],
            answer: 1,
            explain: '单位圆上点 $(\\cos\\theta,\\sin\\theta)$ 满足 $x^2+y^2=1$。',
          },
          {
            id: 'u4-l1-q2',
            type: 'input',
            prompt: '已知 $\\sin\\theta=\\dfrac35$ 且 $\\theta$ 在第二象限，求 $\\cos\\theta$。',
            accept: ['-4/5', '-0.8'],
            placeholder: '如 -4/5',
            explain: '$\\cos^2\\theta=1-\\dfrac{9}{25}=\\dfrac{16}{25}$，第二象限余弦为负，故 $\\cos\\theta=-\\dfrac45$。',
          },
          {
            id: 'u4-l1-q3',
            type: 'judge',
            prompt: '由 $\\sin^2\\theta=\\dfrac14$ 一定能确定 $\\sin\\theta=\\dfrac12$。',
            answer: false,
            explain: '开平方只给绝对值，$\\sin\\theta$ 也可能是 $-\\dfrac12$，符号要由象限决定。',
          },
          {
            id: 'u4-l1-q4',
            type: 'input',
            prompt: '化简 $1-\\cos^2\\theta$，用 $\\sin$ 表示（可写 sin^2）。',
            accept: ['sin^2θ', 'sin^2', '\\sin^2\\theta', 'sin^2theta', 'sin²θ'],
            placeholder: '如 sin^2',
            explain: '由平方关系移项：$1-\\cos^2\\theta=\\sin^2\\theta$。',
          },
          {
            id: 'u4-l1-q5',
            type: 'choice',
            prompt: '已知 $\\cos\\theta=\\dfrac{12}{13}$ 且 $\\theta$ 为锐角，则 $\\sin\\theta=?$',
            options: ['$\\dfrac{5}{13}$', '$-\\dfrac{5}{13}$', '$\\dfrac{1}{13}$', '$\\dfrac{12}{13}$'],
            answer: 0,
            explain: '$\\sin^2\\theta=1-\\dfrac{144}{169}=\\dfrac{25}{169}$，锐角取正，$\\sin\\theta=\\dfrac{5}{13}$。',
          },
          {
            id: 'u4-l1-q6',
            type: 'judge',
            prompt: '$\\sin^2\\theta+\\cos^2\\theta=1$ 对所有实数 $\\theta$ 都成立。',
            answer: true,
            explain: '它是恒等式，源自单位圆方程，对任意 $\\theta$ 恒成立。',
          },
        ],
      },
      {
        id: 'u4-l2',
        title: '商数与倒数关系',
        subtitle: '六个函数连成一张网',
        questions: [
          {
            id: 'u4-l2-q1',
            type: 'judge',
            prompt: '$\\tan\\theta=\\dfrac{\\sin\\theta}{\\cos\\theta}$。',
            answer: true,
            explain: '商数关系：正切等于纵坐标除以横坐标。',
          },
          {
            id: 'u4-l2-q2',
            type: 'match',
            prompt: '把每个函数与其倒数配对。',
            left: ['$\\sec\\theta$', '$\\csc\\theta$', '$\\cot\\theta$'],
            right: ['$\\dfrac{1}{\\cos\\theta}$', '$\\dfrac{1}{\\sin\\theta}$', '$\\dfrac{1}{\\tan\\theta}$'],
            explain: '$\\sec\\leftrightarrow\\cos$、$\\csc\\leftrightarrow\\sin$、$\\cot\\leftrightarrow\\tan$。',
          },
          {
            id: 'u4-l2-q3',
            type: 'choice',
            prompt: '$\\cot\\theta$ 等于下列哪一个？',
            options: ['$\\dfrac{\\sin\\theta}{\\cos\\theta}$', '$\\dfrac{\\cos\\theta}{\\sin\\theta}$', '$\\dfrac{1}{\\cos\\theta}$', '$\\dfrac{1}{\\sin\\theta}$'],
            answer: 1,
            explain: '$\\cot\\theta=\\dfrac{\\cos\\theta}{\\sin\\theta}$，与 $\\tan$ 互为倒数。',
          },
          {
            id: 'u4-l2-q4',
            type: 'judge',
            prompt: '$\\tan\\theta$ 在 $\\cos\\theta=0$ 处也有定义。',
            answer: false,
            explain: '$\\tan\\theta=\\dfrac{\\sin\\theta}{\\cos\\theta}$，分母为 $0$ 时无定义。',
          },
          {
            id: 'u4-l2-q5',
            type: 'input',
            prompt: '已知 $\\tan\\theta=2$，求 $\\dfrac{\\sin\\theta+\\cos\\theta}{2\\sin\\theta-\\cos\\theta}$。',
            accept: ['1'],
            placeholder: '一个数',
            explain: '分子分母同除 $\\cos\\theta$：$\\dfrac{\\tan\\theta+1}{2\\tan\\theta-1}=\\dfrac{3}{3}=1$。',
          },
          {
            id: 'u4-l2-q6',
            type: 'choice',
            prompt: '为什么说六个三角函数“不是六套独立对象”？',
            options: [
              '因为它们图像都一样',
              '因为它们都等于 $1$',
              '因为靠商数、倒数关系彼此联系成一张网',
              '因为它们都只在锐角有定义',
            ],
            answer: 2,
            explain: '商数关系与倒数关系把六个函数统一回 $\\sin,\\cos$ 网络。',
          },
        ],
      },
      {
        id: 'u4-l3',
        title: '导出恒等式与化简',
        subtitle: '$1+\\tan^2=\\sec^2$ 等都是变形',
        questions: [
          {
            id: 'u4-l3-q1',
            type: 'choice',
            prompt: '$1+\\tan^2\\theta=?$',
            options: ['$\\sec^2\\theta$', '$\\csc^2\\theta$', '$\\cot^2\\theta$', '$1$'],
            answer: 0,
            explain: '平方关系两边除以 $\\cos^2\\theta$ 即得 $1+\\tan^2\\theta=\\sec^2\\theta$。',
          },
          {
            id: 'u4-l3-q2',
            type: 'choice',
            prompt: '$1+\\cot^2\\theta=?$',
            options: ['$\\sec^2\\theta$', '$\\csc^2\\theta$', '$\\tan^2\\theta$', '$0$'],
            answer: 1,
            explain: '平方关系两边除以 $\\sin^2\\theta$ 即得 $1+\\cot^2\\theta=\\csc^2\\theta$。',
          },
          {
            id: 'u4-l3-q3',
            type: 'match',
            prompt: '把表达式与它的化简结果配对。',
            left: ['$1-\\sin^2\\theta$', '$1+\\tan^2\\theta$', '$1+\\cot^2\\theta$'],
            right: ['$\\cos^2\\theta$', '$\\sec^2\\theta$', '$\\csc^2\\theta$'],
            explain: '都是平方关系的直接变形，看到即应“模式识别”。',
          },
          {
            id: 'u4-l3-q4',
            type: 'judge',
            prompt: '证明恒等式时，可以不管定义域随意约分。',
            answer: false,
            explain: '约分时若忽略分母为零，可能得到非法结论；必须守住定义域。',
          },
          {
            id: 'u4-l3-q5',
            type: 'input',
            prompt: '化简 $(\\tan\\theta+\\cot\\theta)\\,\\sin\\theta\\cos\\theta$。',
            accept: ['1'],
            placeholder: '一个数',
            explain: '$\\tan\\theta+\\cot\\theta=\\dfrac{\\sin^2\\theta+\\cos^2\\theta}{\\sin\\theta\\cos\\theta}=\\dfrac{1}{\\sin\\theta\\cos\\theta}$，乘 $\\sin\\theta\\cos\\theta$ 得 $1$。',
          },
          {
            id: 'u4-l3-q6',
            type: 'choice',
            prompt: '$\\sin^4\\theta+\\cos^4\\theta$ 等于下列哪一个？',
            options: [
              '$1$',
              '$1-2\\sin^2\\theta\\cos^2\\theta$',
              '$1+2\\sin^2\\theta\\cos^2\\theta$',
              '$2\\sin^2\\theta\\cos^2\\theta$',
            ],
            answer: 1,
            explain: '$\\sin^4\\theta+\\cos^4\\theta=(\\sin^2\\theta+\\cos^2\\theta)^2-2\\sin^2\\theta\\cos^2\\theta=1-2\\sin^2\\theta\\cos^2\\theta$。',
          },
        ],
      },
    ],
  },

  // ============================== 单元 5 ==============================
  {
    id: 'u5',
    title: '和差·倍角·半角',
    color: '#ff4b4b',
    icon: '➕',
    blurb: '和差公式是三角变换的发动机，倍角、半角都由它派生',
    lessons: [
      {
        id: 'u5-l1',
        title: '和差公式',
        subtitle: '两个旋转的叠加',
        questions: [
          {
            id: 'u5-l1-q1',
            type: 'choice',
            prompt: '$\\sin(\\alpha+\\beta)=?$',
            options: [
              '$\\sin\\alpha\\cos\\beta+\\cos\\alpha\\sin\\beta$',
              '$\\sin\\alpha\\cos\\beta-\\cos\\alpha\\sin\\beta$',
              '$\\cos\\alpha\\cos\\beta-\\sin\\alpha\\sin\\beta$',
              '$\\cos\\alpha\\cos\\beta+\\sin\\alpha\\sin\\beta$',
            ],
            answer: 0,
            explain: '正弦和角：符号“同号”，$\\sin\\alpha\\cos\\beta+\\cos\\alpha\\sin\\beta$。',
          },
          {
            id: 'u5-l1-q2',
            type: 'choice',
            prompt: '$\\cos(\\alpha+\\beta)=?$',
            options: [
              '$\\cos\\alpha\\cos\\beta+\\sin\\alpha\\sin\\beta$',
              '$\\cos\\alpha\\cos\\beta-\\sin\\alpha\\sin\\beta$',
              '$\\sin\\alpha\\cos\\beta+\\cos\\alpha\\sin\\beta$',
              '$\\sin\\alpha\\sin\\beta-\\cos\\alpha\\cos\\beta$',
            ],
            answer: 1,
            explain: '余弦和角：符号“相反”，$\\cos\\alpha\\cos\\beta-\\sin\\alpha\\sin\\beta$。',
          },
          {
            id: 'u5-l1-q3',
            type: 'judge',
            prompt: '$\\cos(\\alpha-\\beta)=\\cos\\alpha\\cos\\beta+\\sin\\alpha\\sin\\beta$。',
            answer: true,
            explain: '余弦差角公式，可由单位圆两点距离推出。',
          },
          {
            id: 'u5-l1-q4',
            type: 'match',
            prompt: '把和差表达式与其展开式配对。',
            left: ['$\\sin(\\alpha-\\beta)$', '$\\cos(\\alpha-\\beta)$', '$\\tan(\\alpha+\\beta)$'],
            right: [
              '$\\sin\\alpha\\cos\\beta-\\cos\\alpha\\sin\\beta$',
              '$\\cos\\alpha\\cos\\beta+\\sin\\alpha\\sin\\beta$',
              '$\\dfrac{\\tan\\alpha+\\tan\\beta}{1-\\tan\\alpha\\tan\\beta}$',
            ],
            explain: '正弦符号同号、余弦符号相反，正切分母符号与分子相反。',
          },
          {
            id: 'u5-l1-q5',
            type: 'input',
            prompt: '利用和角公式求 $\\cos 75^\\circ$（写成 $\\dfrac{\\sqrt6-\\sqrt2}{4}$ 形式）。',
            accept: ['(√6-√2)/4', '(sqrt6-sqrt2)/4', '(√6−√2)/4', '0.2588', '0.259'],
            placeholder: '如 (√6-√2)/4',
            explain: '$\\cos(45^\\circ+30^\\circ)=\\dfrac{\\sqrt2}{2}\\cdot\\dfrac{\\sqrt3}{2}-\\dfrac{\\sqrt2}{2}\\cdot\\dfrac12=\\dfrac{\\sqrt6-\\sqrt2}{4}$。',
          },
          {
            id: 'u5-l1-q6',
            type: 'choice',
            prompt: '$\\sin 15^\\circ$ 等于下列哪一个？',
            options: [
              '$\\dfrac{\\sqrt6+\\sqrt2}{4}$',
              '$\\dfrac{\\sqrt6-\\sqrt2}{4}$',
              '$\\dfrac{\\sqrt3-1}{2}$',
              '$\\dfrac{\\sqrt2}{2}$',
            ],
            answer: 1,
            explain: '$\\sin 15^\\circ=\\sin(45^\\circ-30^\\circ)=\\dfrac{\\sqrt6-\\sqrt2}{4}=\\cos 75^\\circ$。',
          },
        ],
      },
      {
        id: 'u5-l2',
        title: '倍角公式',
        subtitle: '令 $\\alpha=\\beta$ 的特例',
        questions: [
          {
            id: 'u5-l2-q1',
            type: 'choice',
            prompt: '$\\sin 2x=?$',
            options: ['$2\\sin x\\cos x$', '$\\sin^2x-\\cos^2x$', '$2\\sin x$', '$1-2\\sin^2x$'],
            answer: 0,
            explain: '令 $\\alpha=\\beta=x$ 于正弦和角公式得 $\\sin 2x=2\\sin x\\cos x$。',
          },
          {
            id: 'u5-l2-q2',
            type: 'match',
            prompt: '把 $\\cos 2x$ 的三种等价形式补全配对。',
            left: ['$\\cos 2x=\\cos^2x-?$', '$\\cos 2x=1-?$', '$\\cos 2x=?-1$'],
            right: ['$\\sin^2x$', '$2\\sin^2x$', '$2\\cos^2x$'],
            explain: '三式分别为 $\\cos^2x-\\sin^2x$、$1-2\\sin^2x$、$2\\cos^2x-1$。',
          },
          {
            id: 'u5-l2-q3',
            type: 'input',
            prompt: '已知 $\\sin x=\\dfrac35$ 且 $x$ 为锐角，求 $\\sin 2x$。',
            accept: ['24/25', '0.96'],
            placeholder: '如 24/25',
            explain: '$\\cos x=\\dfrac45$，$\\sin 2x=2\\cdot\\dfrac35\\cdot\\dfrac45=\\dfrac{24}{25}$。',
          },
          {
            id: 'u5-l2-q4',
            type: 'input',
            prompt: '同上，已知 $\\sin x=\\dfrac35$（$x$ 锐角），求 $\\cos 2x$。',
            accept: ['7/25', '0.28'],
            placeholder: '如 7/25',
            explain: '$\\cos 2x=1-2\\sin^2x=1-\\dfrac{18}{25}=\\dfrac{7}{25}$。',
          },
          {
            id: 'u5-l2-q5',
            type: 'judge',
            prompt: '$\\tan 2x=\\dfrac{2\\tan x}{1-\\tan^2x}$。',
            answer: true,
            explain: '正切倍角公式，由正切和角公式令两角相等得到。',
          },
          {
            id: 'u5-l2-q6',
            type: 'choice',
            prompt: '$\\sin 3x=?$（三倍角公式）',
            options: [
              '$3\\sin x-4\\sin^3x$',
              '$4\\sin^3x-3\\sin x$',
              '$4\\cos^3x-3\\cos x$',
              '$3\\sin x+4\\sin^3x$',
            ],
            answer: 0,
            explain: '正弦三倍角“3 减 4 立方”：$\\sin 3x=3\\sin x-4\\sin^3x$。',
          },
        ],
      },
      {
        id: 'u5-l3',
        title: '半角与万能代换',
        subtitle: '倍角的反向整理',
        questions: [
          {
            id: 'u5-l3-q1',
            type: 'choice',
            prompt: '$\\sin^2\\dfrac{x}{2}=?$',
            options: [
              '$\\dfrac{1-\\cos x}{2}$',
              '$\\dfrac{1+\\cos x}{2}$',
              '$\\dfrac{1-\\sin x}{2}$',
              '$1-\\cos x$',
            ],
            answer: 0,
            explain: '由 $\\cos x=1-2\\sin^2\\dfrac{x}{2}$ 反解得 $\\sin^2\\dfrac{x}{2}=\\dfrac{1-\\cos x}{2}$。',
          },
          {
            id: 'u5-l3-q2',
            type: 'choice',
            prompt: '$\\cos^2\\dfrac{x}{2}=?$',
            options: [
              '$\\dfrac{1-\\cos x}{2}$',
              '$\\dfrac{1+\\cos x}{2}$',
              '$\\dfrac{1+\\sin x}{2}$',
              '$\\dfrac{\\cos x}{2}$',
            ],
            answer: 1,
            explain: '由 $\\cos x=2\\cos^2\\dfrac{x}{2}-1$ 反解得 $\\cos^2\\dfrac{x}{2}=\\dfrac{1+\\cos x}{2}$。',
          },
          {
            id: 'u5-l3-q3',
            type: 'judge',
            prompt: '写 $\\sin\\dfrac{x}{2}=\\sqrt{\\dfrac{1-\\cos x}{2}}$ 时永远取正号即可。',
            answer: false,
            explain: '正负号取决于 $\\dfrac{x}{2}$ 所在象限，不能一律取正。',
          },
          {
            id: 'u5-l3-q4',
            type: 'input',
            prompt: '已知 $\\cos x=-\\dfrac35$ 且 $x\\in\\left(\\dfrac{\\pi}{2},\\pi\\right)$，求 $\\cos^2\\dfrac{x}{2}$。',
            accept: ['1/5', '0.2'],
            placeholder: '如 1/5',
            explain: '$\\cos^2\\dfrac{x}{2}=\\dfrac{1+\\cos x}{2}=\\dfrac{1-3/5}{2}=\\dfrac15$。',
          },
          {
            id: 'u5-l3-q5',
            type: 'match',
            prompt: '设 $t=\\tan\\dfrac{x}{2}$，把万能代换配对。',
            left: ['$\\sin x$', '$\\cos x$'],
            right: ['$\\dfrac{2t}{1+t^2}$', '$\\dfrac{1-t^2}{1+t^2}$'],
            explain: '万能代换把同时含 $\\sin x,\\cos x$ 的式子化为关于 $t$ 的有理式。',
          },
          {
            id: 'u5-l3-q6',
            type: 'input',
            prompt: '用万能代换化简 $\\dfrac{\\sin x}{1+\\cos x}$，结果用 $\\tan\\dfrac{x}{2}$ 表示（可写 tan(x/2)）。',
            accept: ['tan(x/2)', 'tanx/2', 't', '\\tan\\frac{x}{2}', 'tan x/2'],
            placeholder: '如 tan(x/2)',
            explain: '代入后约分得 $\\dfrac{\\sin x}{1+\\cos x}=t=\\tan\\dfrac{x}{2}$。',
          },
        ],
      },
    ],
  },

  // ============================== 单元 6 ==============================
  {
    id: 'u6',
    title: '积化和差·和差化积',
    color: '#2bd4a6',
    icon: '🔄',
    blurb: '在“乘积”与“频率叠加”两种表示之间自由切换',
    lessons: [
      {
        id: 'u6-l1',
        title: '积化和差',
        subtitle: '乘积变成频率和与差',
        questions: [
          {
            id: 'u6-l1-q1',
            type: 'choice',
            prompt: '$\\sin A\\cos B=?$',
            options: [
              '$\\dfrac12[\\sin(A+B)+\\sin(A-B)]$',
              '$\\dfrac12[\\cos(A+B)+\\cos(A-B)]$',
              '$\\dfrac12[\\sin(A+B)-\\sin(A-B)]$',
              '$2\\sin(A+B)\\cos(A-B)$',
            ],
            answer: 0,
            explain: '把 $\\sin(A+B)$ 与 $\\sin(A-B)$ 相加并除以 $2$ 即得。',
          },
          {
            id: 'u6-l1-q2',
            type: 'choice',
            prompt: '$\\cos A\\cos B=?$',
            options: [
              '$\\dfrac12[\\sin(A+B)+\\sin(A-B)]$',
              '$\\dfrac12[\\cos(A+B)+\\cos(A-B)]$',
              '$-\\dfrac12[\\cos(A+B)-\\cos(A-B)]$',
              '$\\dfrac12[\\cos(A-B)-\\cos(A+B)]$',
            ],
            answer: 1,
            explain: '$\\cos A\\cos B=\\dfrac12[\\cos(A+B)+\\cos(A-B)]$。',
          },
          {
            id: 'u6-l1-q3',
            type: 'judge',
            prompt: '$\\sin A\\sin B=-\\dfrac12[\\cos(A+B)-\\cos(A-B)]$。',
            answer: true,
            explain: '即 $\\sin A\\sin B=\\dfrac12[\\cos(A-B)-\\cos(A+B)]$，注意前面的负号。',
          },
          {
            id: 'u6-l1-q4',
            type: 'input',
            prompt: '用积化和差求 $\\cos 75^\\circ\\cos 15^\\circ$ 的精确值。',
            accept: ['1/4', '0.25'],
            placeholder: '如 1/4',
            explain: '$\\dfrac12[\\cos 90^\\circ+\\cos 60^\\circ]=\\dfrac12\\left[0+\\dfrac12\\right]=\\dfrac14$。',
          },
          {
            id: 'u6-l1-q5',
            type: 'choice',
            prompt: '化简 $\\cos 4x\\cos 2x$ 得到？',
            options: [
              '$\\dfrac12[\\cos 6x+\\cos 2x]$',
              '$\\dfrac12[\\cos 6x-\\cos 2x]$',
              '$\\dfrac12[\\sin 6x+\\sin 2x]$',
              '$2\\cos 6x\\cos 2x$',
            ],
            answer: 0,
            explain: '取 $A=4x,B=2x$：$\\cos A\\cos B=\\dfrac12[\\cos 6x+\\cos 2x]$。',
          },
          {
            id: 'u6-l1-q6',
            type: 'input',
            prompt: '求 $\\cos 20^\\circ\\cos 40^\\circ\\cos 80^\\circ$ 的值。',
            accept: ['1/8', '0.125'],
            placeholder: '如 1/8',
            explain: '逐层用积化和差展开，含 $\\cos 20^\\circ$ 的项两两抵消，只剩 $\\dfrac18$。',
          },
        ],
      },
      {
        id: 'u6-l2',
        title: '和差化积',
        subtitle: '叠加变成包络 × 波形',
        questions: [
          {
            id: 'u6-l2-q1',
            type: 'choice',
            prompt: '$\\sin A+\\sin B=?$',
            options: [
              '$2\\sin\\dfrac{A+B}{2}\\cos\\dfrac{A-B}{2}$',
              '$2\\cos\\dfrac{A+B}{2}\\sin\\dfrac{A-B}{2}$',
              '$2\\cos\\dfrac{A+B}{2}\\cos\\dfrac{A-B}{2}$',
              '$2\\sin\\dfrac{A+B}{2}\\sin\\dfrac{A-B}{2}$',
            ],
            answer: 0,
            explain: '$\\sin A+\\sin B=2\\sin\\dfrac{A+B}{2}\\cos\\dfrac{A-B}{2}$。',
          },
          {
            id: 'u6-l2-q2',
            type: 'match',
            prompt: '把和差化积公式配对（取 $\\dfrac{A+B}{2}=s,\\ \\dfrac{A-B}{2}=d$）。',
            left: ['$\\sin A+\\sin B$', '$\\cos A+\\cos B$', '$\\cos A-\\cos B$'],
            right: [
              '$2\\sin s\\cos d$',
              '$2\\cos s\\cos d$',
              '$-2\\sin s\\sin d$',
            ],
            explain: '注意 $\\cos A-\\cos B$ 前有负号，是最易记错符号的一组。',
          },
          {
            id: 'u6-l2-q3',
            type: 'input',
            prompt: '化简 $\\sin 5x+\\sin 3x$ 为乘积形式（可写 2sin4xcosx）。',
            accept: ['2sin4xcosx', '2sin(4x)cos(x)', '2\\sin4x\\cos x', '2 sin4x cosx'],
            placeholder: '如 2sin4xcosx',
            explain: '$A=5x,B=3x$：$2\\sin\\dfrac{8x}{2}\\cos\\dfrac{2x}{2}=2\\sin 4x\\cos x$。',
          },
          {
            id: 'u6-l2-q4',
            type: 'choice',
            prompt: '在拍频 $\\sin 101t+\\sin 99t=2\\sin 100t\\cos t$ 中，慢变包络是？',
            options: ['$\\sin 100t$', '$2\\cos t$', '$\\sin 99t$', '$2\\sin 100t$'],
            answer: 1,
            explain: '快速振荡是 $\\sin 100t$，慢变包络是 $2\\cos t$，这正是拍频结构。',
          },
          {
            id: 'u6-l2-q5',
            type: 'input',
            prompt: '化简 $\\dfrac{\\sin 5x+\\sin x}{\\cos 5x+\\cos x}$（可写 tan3x）。',
            accept: ['tan3x', 'tan(3x)', '\\tan 3x', 'tan 3x'],
            placeholder: '如 tan3x',
            explain: '分子 $2\\sin 3x\\cos 2x$，分母 $2\\cos 3x\\cos 2x$，约去得 $\\tan 3x$。',
          },
          {
            id: 'u6-l2-q6',
            type: 'input',
            prompt: '用和差化积把 $\\cos 50^\\circ+\\cos 10^\\circ$ 化简，结果是 $\\sqrt3\\cos 20^\\circ$ 吗？若是填 √3cos20。',
            accept: ['√3cos20', 'sqrt3cos20', '√3cos20°', '\\sqrt3\\cos 20^\\circ', 'sqrt3 cos20'],
            placeholder: '如 √3cos20',
            explain: '$2\\cos 30^\\circ\\cos 20^\\circ=2\\cdot\\dfrac{\\sqrt3}{2}\\cos 20^\\circ=\\sqrt3\\cos 20^\\circ$。',
          },
        ],
      },
      {
        id: 'u6-l3',
        title: '辅助角与综合',
        subtitle: '$a\\sin x+b\\cos x$ 合一',
        questions: [
          {
            id: 'u6-l3-q1',
            type: 'choice',
            prompt: '$\\sqrt3\\sin x+\\cos x$ 可化为？',
            options: [
              '$2\\sin\\left(x+\\dfrac{\\pi}{6}\\right)$',
              '$2\\sin\\left(x+\\dfrac{\\pi}{3}\\right)$',
              '$\\sqrt3\\sin\\left(x+\\dfrac{\\pi}{6}\\right)$',
              '$2\\cos\\left(x+\\dfrac{\\pi}{6}\\right)$',
            ],
            answer: 0,
            explain: '$R=\\sqrt{(\\sqrt3)^2+1^2}=2$，$\\tan\\varphi=\\dfrac{1}{\\sqrt3}$ 得 $\\varphi=\\dfrac{\\pi}{6}$。',
          },
          {
            id: 'u6-l3-q2',
            type: 'input',
            prompt: '求 $\\sin x+\\cos x$ 化为 $R\\sin(x+\\varphi)$ 中的 $R$。',
            accept: ['√2', 'sqrt2', '1.414', '1.41'],
            placeholder: '如 √2',
            explain: '$R=\\sqrt{1^2+1^2}=\\sqrt2$，且 $\\varphi=\\dfrac{\\pi}{4}$。',
          },
          {
            id: 'u6-l3-q3',
            type: 'judge',
            prompt: '$a\\sin x+b\\cos x$ 的最大值为 $\\sqrt{a^2+b^2}$。',
            answer: true,
            explain: '合一为 $\\sqrt{a^2+b^2}\\sin(x+\\varphi)$，正弦最大为 $1$，故最大值为 $\\sqrt{a^2+b^2}$。',
          },
          {
            id: 'u6-l3-q4',
            type: 'choice',
            prompt: '看到“两个相近频率正弦之和”，最该先想到哪类公式？',
            options: ['平方关系', '和差化积', '半角公式', '倒数关系'],
            answer: 1,
            explain: '和差化积把叠加拆成“包络 × 波形”，正适合分析拍频。',
          },
          {
            id: 'u6-l3-q5',
            type: 'judge',
            prompt: '“看到乘积先想积化和差，看到和差先想和差化积”是合理的选择策略。',
            answer: true,
            explain: '积化和差与和差化积本质是在两种表示系统间切换。',
          },
          {
            id: 'u6-l3-q6',
            type: 'input',
            prompt: '函数 $f(x)=3\\sin x+4\\cos x$ 的最大值是多少？',
            accept: ['5'],
            placeholder: '一个数',
            explain: '$R=\\sqrt{3^2+4^2}=5$，故最大值为 $5$。',
          },
        ],
      },
    ],
  },
]
