import type { Unit } from '../../types'

// 内容取自《三角函数教程》第 7 部分第 19–21 章：复平面与欧拉公式 / De Moivre 与单位根 / 傅里叶级数引论。
// 公式用 $...$（KaTeX）。注意：TS 字符串内所有 LaTeX 反斜杠均双写；虚数单位写作 i，复指数写作 e^{i\\theta}。

export const PART7_UNITS: Unit[] = [
  // ============================== 单元 19 ==============================
  {
    id: 'u19',
    title: '复平面与欧拉公式',
    color: '#d63031',
    icon: '🌀',
    blurb: '$e^{i\\theta}=\\cos\\theta+i\\sin\\theta$——把旋转、三角与指数统一',
    lessons: [
      {
        id: 'u19-l1',
        title: '欧拉公式',
        subtitle: '$e^{i\\theta}=\\cos\\theta+i\\sin\\theta$',
        questions: [
          {
            id: 'u19-l1-q1',
            type: 'choice',
            prompt: '欧拉公式 $e^{i\\theta}=?$',
            options: [
              '$\\cos\\theta-i\\sin\\theta$',
              '$\\cos\\theta+i\\sin\\theta$',
              '$\\sin\\theta+i\\cos\\theta$',
              '$1+i\\theta$',
            ],
            answer: 1,
            explain: '欧拉公式：$e^{i\\theta}=\\cos\\theta+i\\sin\\theta$。',
          },
          {
            id: 'u19-l1-q2',
            type: 'input',
            prompt: '欧拉恒等式：$e^{i\\pi}+1=?$',
            accept: ['0', '零'],
            placeholder: '填一个数',
            explain: '$e^{i\\pi}=-1$，故 $e^{i\\pi}+1=0$，这是“最美数学公式”。',
          },
          {
            id: 'u19-l1-q3',
            type: 'judge',
            prompt: '判断：$e^{i\\pi}=-1$。',
            answer: true,
            explain: '令 $\\theta=\\pi$：$e^{i\\pi}=\\cos\\pi+i\\sin\\pi=-1+0i=-1$。',
          },
          {
            id: 'u19-l1-q4',
            type: 'choice',
            prompt: '$e^{i\\theta}$ 的虚部是？',
            options: ['$\\cos\\theta$', '$\\sin\\theta$', '$-\\sin\\theta$', '$\\tan\\theta$'],
            answer: 1,
            explain: '$e^{i\\theta}=\\cos\\theta+i\\sin\\theta$，实部 $\\cos\\theta$，虚部 $\\sin\\theta$。',
          },
          {
            id: 'u19-l1-q5',
            type: 'input',
            prompt: '$e^{i\\cdot 0}=?$（填一个数）',
            accept: ['1', '一'],
            placeholder: '填一个数',
            explain: '$e^{i\\cdot 0}=\\cos 0+i\\sin 0=1$。',
          },
          {
            id: 'u19-l1-q6',
            type: 'choice',
            prompt: '欧拉公式可由哪一展开推得？',
            options: [
              '$e^x$ 的幂级数代入 $x=i\\theta$',
              '二项式定理',
              '洛必达法则',
              '余弦定理',
            ],
            answer: 0,
            explain: '把 $e^x$ 的 Taylor 级数代入 $x=i\\theta$，分离实虚部即得 $\\cos\\theta$ 与 $\\sin\\theta$ 的级数。',
          },
        ],
      },
      {
        id: 'u19-l2',
        title: '模、辐角与实虚部',
        subtitle: '$|e^{i\\theta}|=1$',
        questions: [
          {
            id: 'u19-l2-q1',
            type: 'input',
            prompt: '单位复数的模：$|e^{i\\theta}|=?$',
            accept: ['1', '一'],
            placeholder: '填一个数',
            explain: '$|e^{i\\theta}|=\\sqrt{\\cos^2\\theta+\\sin^2\\theta}=1$，故 $e^{i\\theta}$ 在单位圆上。',
          },
          {
            id: 'u19-l2-q2',
            type: 'choice',
            prompt: '复数极形式 $z=r(\\cos\\theta+i\\sin\\theta)$ 中 $r$ 表示？',
            options: ['辐角', '模长', '实部', '虚部'],
            answer: 1,
            explain: '$r$ 是模长（长度），$\\theta$ 是辐角（方向）。',
          },
          {
            id: 'u19-l2-q3',
            type: 'choice',
            prompt: '$z=1+\\sqrt{3}\\,i$ 的模 $|z|=?$',
            options: ['$2$', '$\\sqrt{3}$', '$4$', '$\\sqrt{2}$'],
            answer: 0,
            explain: '$|z|=\\sqrt{1^2+(\\sqrt{3})^2}=\\sqrt{4}=2$。',
          },
          {
            id: 'u19-l2-q4',
            type: 'input',
            prompt: '$z=1+\\sqrt{3}\\,i$ 的辐角 $\\theta=?$（用 $\\pi$ 表示，主值在第一象限）',
            accept: ['π/3', 'pi/3', '\\frac{\\pi}{3}', '60°', '60度'],
            placeholder: '例如 π/3',
            explain: '$\\cos\\theta=\\tfrac12,\\ \\sin\\theta=\\tfrac{\\sqrt3}{2}$，第一象限得 $\\theta=\\dfrac{\\pi}{3}$。',
          },
          {
            id: 'u19-l2-q5',
            type: 'judge',
            prompt: '判断：$e^{i\\theta}$ 始终落在单位圆上。',
            answer: true,
            explain: '因为 $|e^{i\\theta}|=1$ 对任意实数 $\\theta$ 成立。',
          },
          {
            id: 'u19-l2-q6',
            type: 'match',
            prompt: '把单位复数与其代数值配对：',
            left: ['$e^{i\\cdot 0}$', '$e^{i\\pi/2}$', '$e^{i\\pi}$', '$e^{i\\cdot 3\\pi/2}$'],
            right: ['$1$', '$i$', '$-1$', '$-i$'],
            explain: '辐角 $0,\\tfrac{\\pi}{2},\\pi,\\tfrac{3\\pi}{2}$ 分别对应 $1,i,-1,-i$。',
          },
        ],
      },
      {
        id: 'u19-l3',
        title: '复数乘法与旋转',
        subtitle: '模相乘、辐角相加',
        questions: [
          {
            id: 'u19-l3-q1',
            type: 'choice',
            prompt: '$e^{i\\alpha}\\cdot e^{i\\beta}=?$',
            options: [
              '$e^{i(\\alpha+\\beta)}$',
              '$e^{i\\alpha\\beta}$',
              '$e^{i(\\alpha-\\beta)}$',
              '$e^{i\\alpha}+e^{i\\beta}$',
            ],
            answer: 0,
            explain: '指数相加：$e^{i\\alpha}e^{i\\beta}=e^{i(\\alpha+\\beta)}$，几何上是两次旋转叠加。',
          },
          {
            id: 'u19-l3-q2',
            type: 'judge',
            prompt: '判断：两个复数相乘时，模长相乘、辐角相加。',
            answer: true,
            explain: '极形式下 $r_1e^{i\\theta_1}\\cdot r_2e^{i\\theta_2}=r_1r_2\\,e^{i(\\theta_1+\\theta_2)}$。',
          },
          {
            id: 'u19-l3-q3',
            type: 'choice',
            prompt: '$z_1=2e^{i\\pi/4}$，$z_2=3e^{i\\pi/6}$，则 $z_1z_2$ 的模为？',
            options: ['$5$', '$6$', '$\\dfrac{2}{3}$', '$1$'],
            answer: 1,
            explain: '模相乘：$2\\cdot 3=6$；辐角相加为 $\\tfrac{5\\pi}{12}$。',
          },
          {
            id: 'u19-l3-q4',
            type: 'input',
            prompt: '$z_1=2e^{i\\pi/4}$，$z_2=3e^{i\\pi/6}$，则 $\\dfrac{z_1}{z_2}$ 的辐角为？（用 $\\pi$ 表示）',
            accept: ['π/12', 'pi/12', '\\frac{\\pi}{12}'],
            placeholder: '例如 π/12',
            explain: '除法辐角相减：$\\tfrac{\\pi}{4}-\\tfrac{\\pi}{6}=\\tfrac{3\\pi-2\\pi}{12}=\\dfrac{\\pi}{12}$。',
          },
          {
            id: 'u19-l3-q5',
            type: 'choice',
            prompt: '用 $e^{i(\\alpha+\\beta)}=e^{i\\alpha}e^{i\\beta}$ 比较实部，可推得？',
            options: [
              '$\\cos(\\alpha+\\beta)=\\cos\\alpha\\cos\\beta-\\sin\\alpha\\sin\\beta$',
              '$\\cos(\\alpha+\\beta)=\\cos\\alpha\\cos\\beta+\\sin\\alpha\\sin\\beta$',
              '$\\sin(\\alpha+\\beta)=\\sin\\alpha\\sin\\beta$',
              '$\\cos(\\alpha+\\beta)=\\cos\\alpha+\\cos\\beta$',
            ],
            answer: 0,
            explain: '右边展开取实部即得余弦和角公式 $\\cos\\alpha\\cos\\beta-\\sin\\alpha\\sin\\beta$。',
          },
          {
            id: 'u19-l3-q6',
            type: 'input',
            prompt: '用 $\\cos\\theta=\\dfrac{e^{i\\theta}+e^{-i\\theta}}{2}$，则 $e^{i\\theta}+e^{-i\\theta}=?$',
            accept: ['2cosθ', '2\\cos\\theta', '2cos(θ)', '2cosθ ', '2\\cosθ'],
            placeholder: '用 cosθ 表示',
            explain: '由定义直接得 $e^{i\\theta}+e^{-i\\theta}=2\\cos\\theta$；类似 $e^{i\\theta}-e^{-i\\theta}=2i\\sin\\theta$。',
          },
        ],
      },
    ],
  },

  // ============================== 单元 20 ==============================
  {
    id: 'u20',
    title: '棣莫弗与单位根',
    color: '#fdcb6e',
    icon: '⭐',
    blurb: '幂运算把角度乘 $n$，单位根均分圆周',
    lessons: [
      {
        id: 'u20-l1',
        title: 'De Moivre 公式',
        subtitle: '$(\\cos\\theta+i\\sin\\theta)^n=\\cos n\\theta+i\\sin n\\theta$',
        questions: [
          {
            id: 'u20-l1-q1',
            type: 'choice',
            prompt: 'De Moivre 公式 $(\\cos\\theta+i\\sin\\theta)^n=?$',
            options: [
              '$\\cos n\\theta+i\\sin n\\theta$',
              '$n\\cos\\theta+in\\sin\\theta$',
              '$\\cos\\theta^n+i\\sin\\theta^n$',
              '$\\cos n\\theta-i\\sin n\\theta$',
            ],
            answer: 0,
            explain: '幂运算把角度乘以 $n$：$(\\cos\\theta+i\\sin\\theta)^n=\\cos n\\theta+i\\sin n\\theta$。',
          },
          {
            id: 'u20-l1-q2',
            type: 'input',
            prompt: '$\\left(\\cos\\dfrac{\\pi}{6}+i\\sin\\dfrac{\\pi}{6}\\right)^3=?$（用代数形式 $a+bi$）',
            accept: ['i', '0+i', '0+1i', '0 + i'],
            placeholder: '例如 i',
            explain: '角度乘 $3$：$\\cos\\tfrac{\\pi}{2}+i\\sin\\tfrac{\\pi}{2}=i$。',
          },
          {
            id: 'u20-l1-q3',
            type: 'judge',
            prompt: '判断：De Moivre 公式可看成“一次旋转重复 $n$ 次”。',
            answer: true,
            explain: '每乘一次角度多转 $\\theta$，$n$ 次后总角度为 $n\\theta$。',
          },
          {
            id: 'u20-l1-q4',
            type: 'choice',
            prompt: '把 $1+i$ 化为极形式，其模与辐角为？',
            options: [
              '$\\sqrt{2},\\ \\dfrac{\\pi}{4}$',
              '$2,\\ \\dfrac{\\pi}{4}$',
              '$\\sqrt{2},\\ \\dfrac{\\pi}{2}$',
              '$1,\\ \\dfrac{\\pi}{3}$',
            ],
            answer: 0,
            explain: '$|1+i|=\\sqrt{2}$，第一象限实虚部相等故辐角 $\\dfrac{\\pi}{4}$。',
          },
          {
            id: 'u20-l1-q5',
            type: 'input',
            prompt: '用 De Moivre 公式计算 $(1+i)^8=?$（填一个实数）',
            accept: ['16', '十六'],
            placeholder: '填一个数',
            explain: '$(\\sqrt2)^8=16$，角度 $8\\cdot\\tfrac{\\pi}{4}=2\\pi$ 转回正实轴，故 $(1+i)^8=16$。',
          },
          {
            id: 'u20-l1-q6',
            type: 'judge',
            prompt: '判断：对极形式 $r(\\cos\\theta+i\\sin\\theta)$，其 $n$ 次幂的模为 $r^n$。',
            answer: true,
            explain: '$[r(\\cos\\theta+i\\sin\\theta)]^n=r^n(\\cos n\\theta+i\\sin n\\theta)$，模取 $n$ 次方。',
          },
        ],
      },
      {
        id: 'u20-l2',
        title: '单位根',
        subtitle: '$z^n=1$ 有 $n$ 个根',
        questions: [
          {
            id: 'u20-l2-q1',
            type: 'input',
            prompt: '方程 $z^n=1$ 在复数范围内有几个根？',
            accept: ['n', 'N', 'n个', 'n 个'],
            placeholder: '用 n 表示',
            explain: '$n$ 次单位根共有 $n$ 个，辐角为 $\\dfrac{2\\pi k}{n}$（$k=0,\\dots,n-1$）。',
          },
          {
            id: 'u20-l2-q2',
            type: 'choice',
            prompt: '$n$ 次单位根的一般表达式为？',
            options: [
              '$e^{2\\pi i k/n},\\ k=0,1,\\dots,n-1$',
              '$e^{\\pi i k/n}$',
              '$e^{i k n}$',
              '$\\dfrac{1}{n}e^{ik}$',
            ],
            answer: 0,
            explain: '由 $e^{in\\theta}=e^{2k\\pi i}$ 得 $\\theta=\\dfrac{2k\\pi}{n}$，即 $z_k=e^{2\\pi i k/n}$。',
          },
          {
            id: 'u20-l2-q3',
            type: 'judge',
            prompt: '判断：$n$ 次单位根在单位圆上等分圆周，构成正 $n$ 边形。',
            answer: true,
            explain: '相邻根辐角间隔 $\\dfrac{2\\pi}{n}$，故等分圆周成正 $n$ 边形顶点。',
          },
          {
            id: 'u20-l2-q4',
            type: 'choice',
            prompt: '方程 $z^4=1$ 的全部根是？',
            options: [
              '$1,\\ i,\\ -1,\\ -i$',
              '$1,\\ -1$',
              '$1,\\ i,\\ -i$',
              '$i,\\ -i,\\ 2,\\ -2$',
            ],
            answer: 0,
            explain: '辐角 $0,\\tfrac{\\pi}{2},\\pi,\\tfrac{3\\pi}{2}$，对应 $1,i,-1,-i$，构成正方形顶点。',
          },
          {
            id: 'u20-l2-q5',
            type: 'match',
            prompt: '把三次单位根（$z^3=1$）与其辐角配对：',
            left: ['$1$', '$e^{2\\pi i/3}$', '$e^{4\\pi i/3}$'],
            right: ['$0$', '$\\dfrac{2\\pi}{3}$', '$\\dfrac{4\\pi}{3}$'],
            explain: '三次单位根 $1,e^{2\\pi i/3},e^{4\\pi i/3}$ 在复平面构成正三角形。',
          },
          {
            id: 'u20-l2-q6',
            type: 'input',
            prompt: '设 $\\omega=e^{2\\pi i/3}$，则 $1+\\omega+\\omega^2=?$',
            accept: ['0', '零'],
            placeholder: '填一个数',
            explain: '由 $\\omega^3-1=(\\omega-1)(\\omega^2+\\omega+1)=0$ 且 $\\omega\\neq1$，得 $1+\\omega+\\omega^2=0$。',
          },
        ],
      },
      {
        id: 'u20-l3',
        title: '复数开方',
        subtitle: '模长开方 + 角度等分',
        questions: [
          {
            id: 'u20-l3-q1',
            type: 'choice',
            prompt: '求 $w^n=z=re^{i\\theta}$，根的一般式为？',
            options: [
              '$\\sqrt[n]{r}\\,e^{i(\\theta+2k\\pi)/n},\\ k=0,\\dots,n-1$',
              '$\\sqrt[n]{r}\\,e^{i\\theta/n}$（只一个）',
              '$r^n e^{in\\theta}$',
              '$\\dfrac{r}{n}e^{i\\theta}$',
            ],
            answer: 0,
            explain: '模取 $n$ 次方根，角度加上整周期 $2k\\pi$ 再除以 $n$，共 $n$ 个根。',
          },
          {
            id: 'u20-l3-q2',
            type: 'judge',
            prompt: '判断：复数 $n$ 次开方一般得到 $n$ 个根，等角分布在同一圆上。',
            answer: true,
            explain: '$n$ 个根模长相同，辐角间隔 $\\dfrac{2\\pi}{n}$。',
          },
          {
            id: 'u20-l3-q3',
            type: 'input',
            prompt: '解 $w^3=-8$，其中的实根 $w=?$',
            accept: ['-2', '−2'],
            placeholder: '填一个数',
            explain: '$-8=8e^{i\\pi}$，$w_1=2e^{i\\pi}=-2$；另两根为 $1\\pm\\sqrt3\\,i$。',
          },
          {
            id: 'u20-l3-q4',
            type: 'choice',
            prompt: '$w^2=1+i$ 的两个根之间有何关系？',
            options: ['互为相反数', '互为共轭', '互为倒数', '相等'],
            answer: 0,
            explain: '开平方两根辐角相差 $\\dfrac{2\\pi}{2}=\\pi$，故 $w_1=-w_0$，互为相反数。',
          },
          {
            id: 'u20-l3-q5',
            type: 'judge',
            prompt: '判断：所有 $n$ 次单位根之和为 $0$（$n\\ge 2$）。',
            answer: true,
            explain: '等比和 $\\sum_{k=0}^{n-1}\\zeta^k=\\dfrac{\\zeta^n-1}{\\zeta-1}=0$；几何上对称向量相互抵消。',
          },
          {
            id: 'u20-l3-q6',
            type: 'input',
            prompt: '利用五次单位根之和为零，$\\cos\\dfrac{2\\pi}{5}+\\cos\\dfrac{4\\pi}{5}=?$',
            accept: ['-1/2', '−1/2', '-0.5', '−0.5', '-\\frac{1}{2}'],
            placeholder: '填一个数',
            explain: '五根之和实部 $1+2\\cos\\tfrac{2\\pi}{5}+2\\cos\\tfrac{4\\pi}{5}=0$，故和为 $-\\dfrac{1}{2}$。',
          },
        ],
      },
    ],
  },

  // ============================== 单元 21 ==============================
  {
    id: 'u21',
    title: '傅里叶级数引论',
    color: '#a29bfe',
    icon: '〰️',
    blurb: '周期函数 = 不同频率正弦余弦的叠加',
    lessons: [
      {
        id: 'u21-l1',
        title: '频率分解与正交性',
        subtitle: '三角函数作为频率基底',
        questions: [
          {
            id: 'u21-l1-q1',
            type: 'choice',
            prompt: '傅里叶级数的核心思想是？',
            options: [
              '把周期函数拆成不同频率正弦余弦的叠加',
              '把函数展成幂级数',
              '把函数化成多项式',
              '把角度化成弧度',
            ],
            answer: 0,
            explain: '三角函数在此充当“频率基底”，任意规整周期函数都可分解到各频率分量。',
          },
          {
            id: 'u21-l1-q2',
            type: 'judge',
            prompt: '判断：$\\sin nx$ 与 $\\cos mx$ 在对称区间上的正交性，是傅里叶级数能逐频率提取系数的根基。',
            answer: true,
            explain: '不同频率“互不干扰”，乘积在整周期上积分为零，故可投影出各系数。',
          },
          {
            id: 'u21-l1-q3',
            type: 'input',
            prompt: '$\\displaystyle\\int_{-\\pi}^{\\pi}\\cos x\\,\\cos 2x\\,dx=?$',
            accept: ['0', '零'],
            placeholder: '填一个数',
            explain: '积化和差为 $\\tfrac12(\\cos x+\\cos 3x)$，整周期上非零频率积分为零，故为 $0$。',
          },
          {
            id: 'u21-l1-q4',
            type: 'choice',
            prompt: '把两个频率乘积拆成单频率之和，傅里叶分析里用到的是？',
            options: ['积化和差', '二项式定理', '洛必达法则', '欧拉判别法'],
            answer: 0,
            explain: '$\\cos A\\cos B=\\tfrac12[\\cos(A-B)+\\cos(A+B)]$，正交性由此得到验证。',
          },
          {
            id: 'u21-l1-q5',
            type: 'judge',
            prompt: '判断：傅里叶系数代表某个频率分量在原函数中所占的权重。',
            answer: true,
            explain: '系数本质是“频率内容”的度量——哪些频率强、信号偏低频还是高频。',
          },
          {
            id: 'u21-l1-q6',
            type: 'choice',
            prompt: '周期为 $2\\pi$ 的函数，其傅里叶级数的标准形式为？',
            options: [
              '$\\dfrac{a_0}{2}+\\sum_{n=1}^{\\infty}(a_n\\cos nx+b_n\\sin nx)$',
              '$\\sum_{n=1}^{\\infty}a_n x^n$',
              '$\\sum_{n=0}^{\\infty}\\dfrac{x^n}{n!}$',
              '$a_0+\\sum a_n\\tan nx$',
            ],
            answer: 0,
            explain: '常数项 $\\dfrac{a_0}{2}$ 加上各次余弦、正弦谐波之和。',
          },
        ],
      },
      {
        id: 'u21-l2',
        title: '奇偶函数的简化',
        subtitle: '偶函数只含 cos，奇函数只含 sin',
        questions: [
          {
            id: 'u21-l2-q1',
            type: 'choice',
            prompt: '若 $f(x)$ 为偶函数，则其傅里叶级数？',
            options: [
              '只含余弦项（与常数项）',
              '只含正弦项',
              '既含正弦也含余弦',
              '为零',
            ],
            answer: 0,
            explain: '偶 × 奇（$\\sin$）= 奇，在对称区间积分为 $0$，故 $b_n=0$，只剩余弦项。',
          },
          {
            id: 'u21-l2-q2',
            type: 'choice',
            prompt: '若 $f(x)$ 为奇函数，则其傅里叶级数？',
            options: ['只含正弦项', '只含余弦项', '只有常数项', '发散'],
            answer: 0,
            explain: '奇 × 偶（$\\cos$）= 奇，积分为 $0$，故 $a_n=0$，只剩正弦项。',
          },
          {
            id: 'u21-l2-q3',
            type: 'judge',
            prompt: '判断：$f(x)=x^2$（周期 $2\\pi$）的傅里叶级数只含余弦项。',
            answer: true,
            explain: '$x^2$ 是偶函数，故 $b_n=0$，只含余弦项与常数项。',
          },
          {
            id: 'u21-l2-q4',
            type: 'judge',
            prompt: '判断：$f(x)=x^3$（周期 $2\\pi$）的傅里叶级数只含正弦项。',
            answer: true,
            explain: '$x^3$ 是奇函数，故 $a_n=0$，只含正弦项。',
          },
          {
            id: 'u21-l2-q5',
            type: 'match',
            prompt: '把函数与其傅里叶级数所含项配对（周期 $2\\pi$）：',
            left: ['$|x|$', '$x$', '$x\\cos x$'],
            right: ['只含余弦项', '只含正弦项', '只含正弦项'],
            explain: '$|x|$ 偶 → 余弦；$x$ 奇 → 正弦；$x\\cos x$ 奇×偶=奇 → 正弦。',
          },
          {
            id: 'u21-l2-q6',
            type: 'input',
            prompt: '$f(x)=x$（$-\\pi<x<\\pi$）为奇函数，其余弦系数 $a_n=?$',
            accept: ['0', '零'],
            placeholder: '填一个数',
            explain: '奇函数所有 $a_n=0$，仅正弦系数 $b_n=\\dfrac{2(-1)^{n+1}}{n}$ 非零。',
          },
        ],
      },
      {
        id: 'u21-l3',
        title: '方波与部分和',
        subtitle: '部分和逐步逼近方波',
        questions: [
          {
            id: 'u21-l3-q1',
            type: 'choice',
            prompt: '方波（$0<x<\\pi$ 取 $1$，$-\\pi<x<0$ 取 $-1$）的傅里叶展开为？',
            options: [
              '$\\dfrac{4}{\\pi}\\left(\\sin x+\\dfrac{\\sin 3x}{3}+\\dfrac{\\sin 5x}{5}+\\cdots\\right)$',
              '$\\dfrac{4}{\\pi}\\left(\\cos x+\\dfrac{\\cos 3x}{3}+\\cdots\\right)$',
              '$\\sin x+\\sin 2x+\\sin 3x+\\cdots$',
              '$\\dfrac{2}{\\pi}\\sum\\dfrac{\\cos nx}{n^2}$',
            ],
            answer: 0,
            explain: '方波为奇函数，只含奇次正弦谐波，系数 $b_n=\\dfrac{4}{n\\pi}$（$n$ 奇）。',
          },
          {
            id: 'u21-l3-q2',
            type: 'judge',
            prompt: '判断：方波的傅里叶级数只含奇次谐波（$\\sin x,\\sin 3x,\\sin 5x,\\dots$）。',
            answer: true,
            explain: '偶次项 $b_n=\\dfrac{2}{n\\pi}(1-\\cos n\\pi)=0$，故只剩奇次谐波。',
          },
          {
            id: 'u21-l3-q3',
            type: 'judge',
            prompt: '判断：随着取的谐波项数增加，部分和会逐步逼近方波。',
            answer: true,
            explain: '$N=1,3,5,\\dots$ 的部分和越来越接近方波，间断点附近的过冲即 Gibbs 现象。',
          },
          {
            id: 'u21-l3-q4',
            type: 'choice',
            prompt: '在间断点处，傅里叶级数收敛到？',
            options: [
              '左右极限的平均值 $\\dfrac{f(x^+)+f(x^-)}{2}$',
              '左极限 $f(x^-)$',
              '右极限 $f(x^+)$',
              '$0$（恒为零）',
            ],
            answer: 0,
            explain: 'Dirichlet 条件下，间断点收敛到左右极限的平均值。',
          },
          {
            id: 'u21-l3-q5',
            type: 'input',
            prompt: '方波展开取 $x=\\dfrac{\\pi}{2}$ 得 $1=\\dfrac{4}{\\pi}\\left(1-\\dfrac{1}{3}+\\dfrac{1}{5}-\\cdots\\right)$，由此 $1-\\dfrac{1}{3}+\\dfrac{1}{5}-\\cdots=?$（用 $\\pi$ 表示）',
            accept: ['π/4', 'pi/4', '\\frac{\\pi}{4}'],
            placeholder: '例如 π/4',
            explain: '这就是 Leibniz 公式：$\\dfrac{\\pi}{4}=1-\\dfrac{1}{3}+\\dfrac{1}{5}-\\dfrac{1}{7}+\\cdots$。',
          },
          {
            id: 'u21-l3-q6',
            type: 'choice',
            prompt: '间断点附近部分和出现的固定过冲现象称为？',
            options: ['Gibbs 现象', '多普勒效应', '共振', 'Aliasing 混叠'],
            answer: 0,
            explain: 'Gibbs 现象：无论取多少项，间断点附近总有约 9% 的过冲。',
          },
        ],
      },
    ],
  },
]
