import type { Unit } from '../../types'

// 内容取自《三角函数教程》第 10–12 章：三角方程 / 三角不等式 / 参数·最值·综合变形。
// 公式用 $...$（KaTeX）。输入题的 accept 提供多种等价写法，配合容错匹配。

export const PART4_UNITS: Unit[] = [
  // ============================== 单元 10 ==============================
  {
    id: 'u10',
    title: '三角方程',
    color: '#ffc800',
    icon: '🟰',
    blurb: '最简方程、通解、化同名/二次型、辅助角——先在一个周期里求解，再写完整解集',
    lessons: [
      {
        id: 'u10-l1',
        title: '最简方程与通解',
        subtitle: '主值解之外，别忘了 $+2k\\pi$',
        questions: [
          {
            id: 'u10-l1-q1',
            type: 'choice',
            prompt: '$\\sin x=\\dfrac12$ 在 $[0,2\\pi)$ 内的解集是？',
            options: [
              '$\\left\\{\\dfrac{\\pi}{6}\\right\\}$',
              '$\\left\\{\\dfrac{\\pi}{6},\\dfrac{5\\pi}{6}\\right\\}$',
              '$\\left\\{\\dfrac{\\pi}{6},\\dfrac{7\\pi}{6}\\right\\}$',
              '$\\left\\{\\dfrac{\\pi}{3},\\dfrac{2\\pi}{3}\\right\\}$',
            ],
            answer: 1,
            explain: '参考角 $\\dfrac{\\pi}{6}$，正弦为正在第一、二象限，得 $\\dfrac{\\pi}{6}$ 与 $\\pi-\\dfrac{\\pi}{6}=\\dfrac{5\\pi}{6}$。',
          },
          {
            id: 'u10-l1-q2',
            type: 'choice',
            prompt: '$\\sin x=\\dfrac12$ 在全体实数上的通解是？',
            options: [
              '$x=\\dfrac{\\pi}{6}+2k\\pi,\\ k\\in\\mathbb{Z}$',
              '$x=\\dfrac{\\pi}{6}+2k\\pi$ 或 $x=\\dfrac{5\\pi}{6}+2k\\pi,\\ k\\in\\mathbb{Z}$',
              '$x=\\dfrac{\\pi}{6}+k\\pi,\\ k\\in\\mathbb{Z}$',
              '$x=\\pm\\dfrac{\\pi}{6}+2k\\pi,\\ k\\in\\mathbb{Z}$',
            ],
            answer: 1,
            explain: '正弦方程有两族解，分别绕第一、二象限终边复制周期 $2\\pi$。',
          },
          {
            id: 'u10-l1-q3',
            type: 'judge',
            prompt: '正切方程 $\\tan x=a$ 的通解是 $x=\\alpha+k\\pi$，因为正切周期是 $\\pi$。',
            answer: true,
            explain: '正切周期为 $\\pi$，故只有一族解 $x=\\alpha+k\\pi$，$k\\in\\mathbb{Z}$。',
          },
          {
            id: 'u10-l1-q4',
            type: 'input',
            prompt: '解方程 $2\\sin x-1=0$，先写出它等价的最简方程 $\\sin x=?$（填一个数）。',
            accept: ['1/2', '0.5', '\\frac12', '\\frac{1}{2}', '½'],
            placeholder: '例如 1/2',
            explain: '$2\\sin x-1=0\\Rightarrow\\sin x=\\dfrac12$。',
          },
          {
            id: 'u10-l1-q5',
            type: 'choice',
            prompt: '$\\cos x=a$（主值角为 $\\alpha$）的通解形式是？',
            options: [
              '$x=\\alpha+2k\\pi$',
              '$x=\\pm\\alpha+2k\\pi$',
              '$x=\\alpha+k\\pi$',
              '$x=\\pi-\\alpha+2k\\pi$',
            ],
            answer: 1,
            explain: '余弦在上下对称两支取同值，故 $x=\\pm\\alpha+2k\\pi$，$k\\in\\mathbb{Z}$。',
          },
          {
            id: 'u10-l1-q6',
            type: 'judge',
            prompt: '若 $|a|>1$，则方程 $\\sin x=a$ 无解。',
            answer: true,
            explain: '正弦值域为 $[-1,1]$，水平线超出值域时与曲线无交点。',
          },
        ],
      },
      {
        id: 'u10-l2',
        title: '换元法与二次型',
        subtitle: '令 $t=\\sin x$，把方程压成代数方程',
        questions: [
          {
            id: 'u10-l2-q1',
            type: 'choice',
            prompt: '解 $2\\sin^2 x-3\\sin x+1=0$，令 $t=\\sin x$ 后得到哪个代数方程？',
            options: [
              '$2t^2-3t+1=0$',
              '$2t^2+3t-1=0$',
              '$t^2-3t+2=0$',
              '$2t^2-3t-1=0$',
            ],
            answer: 0,
            explain: '直接把 $\\sin x$ 整体换成 $t$ 即可。',
          },
          {
            id: 'u10-l2-q2',
            type: 'choice',
            prompt: '$2t^2-3t+1=0$ 的解是？',
            options: [
              '$t=1$ 或 $t=\\dfrac12$',
              '$t=-1$ 或 $t=\\dfrac12$',
              '$t=2$ 或 $t=\\dfrac12$',
              '$t=1$ 或 $t=-\\dfrac12$',
            ],
            answer: 0,
            explain: '$(2t-1)(t-1)=0\\Rightarrow t=\\dfrac12$ 或 $t=1$。',
          },
          {
            id: 'u10-l2-q3',
            type: 'judge',
            prompt: '换元 $t=\\sin x$ 后必须检查解是否落在 $[-1,1]$ 内，否则需舍去。',
            answer: true,
            explain: '$\\sin x\\in[-1,1]$，超出此范围的 $t$ 对应的三角方程无解。',
          },
          {
            id: 'u10-l2-q4',
            type: 'choice',
            prompt: '解 $2\\cos^2 x+\\sin x-1=0$ 时，先用哪个恒等式化成只含 $\\sin x$ 的二次型？',
            options: [
              '$\\cos^2 x=1-\\sin^2 x$',
              '$\\cos^2 x=1+\\sin^2 x$',
              '$\\sin^2 x=1+\\cos^2 x$',
              '$\\cos 2x=2\\cos^2 x-1$',
            ],
            answer: 0,
            explain: '用 $\\cos^2 x=1-\\sin^2 x$ 化同名，得 $2\\sin^2 x-\\sin x-1=0$。',
          },
          {
            id: 'u10-l2-q5',
            type: 'input',
            prompt: '$\\cos 2x+3\\sin x-2=0$ 中，用倍角把 $\\cos 2x$ 写成只含 $\\sin x$ 的式子：$\\cos 2x=1-?\\,\\sin^2 x$（填系数）。',
            accept: ['2', '２'],
            placeholder: '例如 2',
            explain: '$\\cos 2x=1-2\\sin^2 x$，这样可一步化成只含 $\\sin x$ 的二次型。',
          },
          {
            id: 'u10-l2-q6',
            type: 'choice',
            prompt: '$\\cos 2x+3\\sin x-2=0$ 在 $[0,2\\pi)$ 内的解集是？',
            options: [
              '$\\left\\{\\dfrac{\\pi}{6},\\dfrac{5\\pi}{6}\\right\\}$',
              '$\\left\\{\\dfrac{\\pi}{6},\\dfrac{\\pi}{2},\\dfrac{5\\pi}{6}\\right\\}$',
              '$\\left\\{\\dfrac{\\pi}{2}\\right\\}$',
              '$\\left\\{\\dfrac{\\pi}{3},\\dfrac{\\pi}{2},\\dfrac{2\\pi}{3}\\right\\}$',
            ],
            answer: 1,
            explain: '化为 $2\\sin^2 x-3\\sin x+1=0$，得 $\\sin x=\\dfrac12$（$\\dfrac{\\pi}{6},\\dfrac{5\\pi}{6}$）或 $\\sin x=1$（$\\dfrac{\\pi}{2}$）。',
          },
        ],
      },
      {
        id: 'u10-l3',
        title: '辅助角与结构变形',
        subtitle: '$a\\sin x+b\\cos x$ 压成单一正弦',
        questions: [
          {
            id: 'u10-l3-q1',
            type: 'input',
            prompt: '把 $\\sin x-\\sqrt3\\cos x$ 写成 $R\\sin(x+\\varphi)$，$R=?$（填一个数）。',
            accept: ['2', '２'],
            placeholder: '例如 2',
            explain: '$R=\\sqrt{1^2+(\\sqrt3)^2}=\\sqrt4=2$。',
          },
          {
            id: 'u10-l3-q2',
            type: 'choice',
            prompt: '$\\sin x-\\sqrt3\\cos x$ 可化为下列哪个形式？',
            options: [
              '$2\\sin\\!\\left(x-\\dfrac{\\pi}{3}\\right)$',
              '$2\\sin\\!\\left(x+\\dfrac{\\pi}{3}\\right)$',
              '$2\\cos\\!\\left(x-\\dfrac{\\pi}{6}\\right)$',
              '$\\sqrt3\\sin\\!\\left(x-\\dfrac{\\pi}{3}\\right)$',
            ],
            answer: 0,
            explain: '$2\\left(\\dfrac12\\sin x-\\dfrac{\\sqrt3}{2}\\cos x\\right)=2\\sin\\!\\left(x-\\dfrac{\\pi}{3}\\right)$。',
          },
          {
            id: 'u10-l3-q3',
            type: 'choice',
            prompt: '$\\sin x+\\cos x=1$ 用辅助角化简后得到？',
            options: [
              '$\\sqrt2\\sin\\!\\left(x+\\dfrac{\\pi}{4}\\right)=1$',
              '$2\\sin\\!\\left(x+\\dfrac{\\pi}{4}\\right)=1$',
              '$\\sqrt2\\cos\\!\\left(x+\\dfrac{\\pi}{4}\\right)=1$',
              '$\\sin\\!\\left(x+\\dfrac{\\pi}{4}\\right)=1$',
            ],
            answer: 0,
            explain: '$R=\\sqrt{1^2+1^2}=\\sqrt2$，故 $\\sqrt2\\sin\\!\\left(x+\\dfrac{\\pi}{4}\\right)=1$。',
          },
          {
            id: 'u10-l3-q4',
            type: 'judge',
            prompt: '解 $\\sin x=\\cos x$ 时两边同除以 $\\cos x$ 得 $\\tan x=1$，这一步默认了 $\\cos x\\ne0$。',
            answer: true,
            explain: '除以 $\\cos x$ 须保证它不为零；每次除法变形都要确认分母是否可能为零。',
          },
          {
            id: 'u10-l3-q5',
            type: 'judge',
            prompt: '两边平方是绝对安全的变形，永远不会引入增根。',
            answer: false,
            explain: '平方会引入增根，变形后必须代回原方程检验。',
          },
          {
            id: 'u10-l3-q6',
            type: 'match',
            prompt: '把方程结构与首选求解工具配对：',
            left: [
              '$\\sin x=a$ 型',
              '多项式型 $2\\sin^2 x-3\\sin x+1=0$',
              '线性组合 $a\\sin x+b\\cos x=c$',
              '正切方程 $\\tan x=a$',
            ],
            right: [
              '单位圆 / 图像',
              '换元法',
              '辅助角公式',
              '周期 $\\pi$ 的单族通解',
            ],
            explain: '识别结构、归约到对应标准类，是解三角方程的核心能力。',
          },
        ],
      },
    ],
  },

  // ============================== 单元 11 ==============================
  {
    id: 'u11',
    title: '三角不等式',
    color: '#ff86d0',
    icon: '⚖️',
    blurb: '读区间：先在一个周期里看图像或单位圆，按底/单调性定方向，再复制周期',
    lessons: [
      {
        id: 'u11-l1',
        title: '正弦·余弦不等式',
        subtitle: '先在一个周期定区间，再写 $+2k\\pi$',
        questions: [
          {
            id: 'u11-l1-q1',
            type: 'choice',
            prompt: '$\\sin x\\ge\\dfrac12$ 在一个周期 $[0,2\\pi)$ 内的解集是？',
            options: [
              '$\\left[\\dfrac{\\pi}{6},\\dfrac{5\\pi}{6}\\right]$',
              '$\\left(\\dfrac{\\pi}{6},\\dfrac{5\\pi}{6}\\right)$',
              '$\\left[\\dfrac{\\pi}{3},\\dfrac{2\\pi}{3}\\right]$',
              '$\\left[\\dfrac{5\\pi}{6},\\dfrac{13\\pi}{6}\\right]$',
            ],
            answer: 0,
            explain: '正弦曲线在 $\\dfrac{\\pi}{6}$ 到 $\\dfrac{5\\pi}{6}$ 之间不低于 $\\dfrac12$；含等号取闭区间。',
          },
          {
            id: 'u11-l1-q2',
            type: 'choice',
            prompt: '$\\sin x\\ge\\dfrac12$ 在全体实数上的解集是？',
            options: [
              '$\\left[\\dfrac{\\pi}{6}+2k\\pi,\\dfrac{5\\pi}{6}+2k\\pi\\right],\\ k\\in\\mathbb{Z}$',
              '$\\left[\\dfrac{\\pi}{6}+k\\pi,\\dfrac{5\\pi}{6}+k\\pi\\right],\\ k\\in\\mathbb{Z}$',
              '$\\left(\\dfrac{\\pi}{6}+2k\\pi,\\dfrac{5\\pi}{6}+2k\\pi\\right),\\ k\\in\\mathbb{Z}$',
              '$\\left[\\dfrac{\\pi}{6}+2k\\pi,\\dfrac{7\\pi}{6}+2k\\pi\\right],\\ k\\in\\mathbb{Z}$',
            ],
            answer: 0,
            explain: '把一个周期内的闭区间整体复制周期 $2\\pi$，$k\\in\\mathbb{Z}$ 不能省。',
          },
          {
            id: 'u11-l1-q3',
            type: 'choice',
            prompt: '$\\cos x<0$ 在一个周期 $[0,2\\pi)$ 内的解集是？',
            options: [
              '$\\left(\\dfrac{\\pi}{2},\\dfrac{3\\pi}{2}\\right)$',
              '$\\left[\\dfrac{\\pi}{2},\\dfrac{3\\pi}{2}\\right]$',
              '$\\left(0,\\pi\\right)$',
              '$\\left(\\dfrac{\\pi}{2},\\pi\\right)$',
            ],
            answer: 0,
            explain: '余弦在第二、三象限为负，对应开区间 $\\left(\\dfrac{\\pi}{2},\\dfrac{3\\pi}{2}\\right)$；严格不等号取开端点。',
          },
          {
            id: 'u11-l1-q4',
            type: 'judge',
            prompt: '不等式 $\\sin x>\\dfrac{\\sqrt3}{2}$ 的端点应取开区间，因为不等号是严格的。',
            answer: true,
            explain: '严格不等号 $>$ 端点不取，写开区间 $\\left(\\dfrac{\\pi}{3},\\dfrac{2\\pi}{3}\\right)$。',
          },
          {
            id: 'u11-l1-q5',
            type: 'input',
            prompt: '$2\\sin x-\\sqrt3>0$ 整理成最简不等式 $\\sin x>?$（填一个数，可用根号）。',
            accept: ['√3/2', 'sqrt3/2', '\\frac{\\sqrt3}{2}', '\\frac{\\sqrt{3}}{2}', 'sqrt(3)/2'],
            placeholder: '例如 √3/2',
            explain: '$2\\sin x-\\sqrt3>0\\Rightarrow\\sin x>\\dfrac{\\sqrt3}{2}$。',
          },
          {
            id: 'u11-l1-q6',
            type: 'judge',
            prompt: '$\\cos x\\le-\\dfrac12$ 在 $[0,2\\pi)$ 内的解集是 $\\left[\\dfrac{2\\pi}{3},\\dfrac{4\\pi}{3}\\right]$。',
            answer: true,
            explain: '交点为 $\\dfrac{2\\pi}{3},\\dfrac{4\\pi}{3}$，二者之间余弦更小（在水平线下方），含等号取闭区间。',
          },
        ],
      },
      {
        id: 'u11-l2',
        title: '正切不等式',
        subtitle: '周期 $\\pi$，守住渐近线',
        questions: [
          {
            id: 'u11-l2-q1',
            type: 'input',
            prompt: '正切函数的最小正周期是多少？（用 $\\pi$ 表示）',
            accept: ['π', 'pi', '\\pi', 'π rad'],
            placeholder: '例如 π',
            explain: '正切周期为 $\\pi$，比正弦、余弦的 $2\\pi$ 小一半。',
          },
          {
            id: 'u11-l2-q2',
            type: 'choice',
            prompt: '$\\tan x>1$ 在主值区间 $\\left(-\\dfrac{\\pi}{2},\\dfrac{\\pi}{2}\\right)$ 内的解是？',
            options: [
              '$\\left(\\dfrac{\\pi}{4},\\dfrac{\\pi}{2}\\right)$',
              '$\\left[\\dfrac{\\pi}{4},\\dfrac{\\pi}{2}\\right)$',
              '$\\left(-\\dfrac{\\pi}{2},\\dfrac{\\pi}{4}\\right)$',
              '$\\left(\\dfrac{\\pi}{4},\\pi\\right)$',
            ],
            answer: 0,
            explain: '主值区间内正切严格递增，$\\tan\\dfrac{\\pi}{4}=1$，故 $x>\\dfrac{\\pi}{4}$ 且 $x<\\dfrac{\\pi}{2}$。',
          },
          {
            id: 'u11-l2-q3',
            type: 'choice',
            prompt: '$\\tan x>1$ 在全体实数上的解集是？',
            options: [
              '$\\left(\\dfrac{\\pi}{4}+k\\pi,\\dfrac{\\pi}{2}+k\\pi\\right),\\ k\\in\\mathbb{Z}$',
              '$\\left(\\dfrac{\\pi}{4}+2k\\pi,\\dfrac{\\pi}{2}+2k\\pi\\right),\\ k\\in\\mathbb{Z}$',
              '$\\left[\\dfrac{\\pi}{4}+k\\pi,\\dfrac{\\pi}{2}+k\\pi\\right],\\ k\\in\\mathbb{Z}$',
              '$\\left(\\dfrac{\\pi}{4}+k\\pi,\\pi+k\\pi\\right),\\ k\\in\\mathbb{Z}$',
            ],
            answer: 0,
            explain: '正切周期为 $\\pi$，故复制周期 $\\pi$ 而非 $2\\pi$。',
          },
          {
            id: 'u11-l2-q4',
            type: 'judge',
            prompt: '解 $\\tan x\\le\\sqrt3$ 时，左端点 $-\\dfrac{\\pi}{2}+k\\pi$ 必须取开区间，因为那里正切无定义。',
            answer: true,
            explain: '$x=-\\dfrac{\\pi}{2}+k\\pi$ 是渐近线，正切无定义，永远取开端点。',
          },
          {
            id: 'u11-l2-q5',
            type: 'choice',
            prompt: '$\\tan x\\le\\sqrt3$ 在全体实数上的解集是？',
            options: [
              '$\\left(-\\dfrac{\\pi}{2}+k\\pi,\\dfrac{\\pi}{3}+k\\pi\\right],\\ k\\in\\mathbb{Z}$',
              '$\\left[-\\dfrac{\\pi}{2}+k\\pi,\\dfrac{\\pi}{3}+k\\pi\\right],\\ k\\in\\mathbb{Z}$',
              '$\\left(-\\dfrac{\\pi}{2}+k\\pi,\\dfrac{\\pi}{3}+k\\pi\\right),\\ k\\in\\mathbb{Z}$',
              '$\\left(-\\dfrac{\\pi}{2}+2k\\pi,\\dfrac{\\pi}{3}+2k\\pi\\right],\\ k\\in\\mathbb{Z}$',
            ],
            answer: 0,
            explain: '$\\tan\\dfrac{\\pi}{3}=\\sqrt3$，左端无定义取开、右端含 $\\le$ 取闭，周期为 $\\pi$。',
          },
          {
            id: 'u11-l2-q6',
            type: 'judge',
            prompt: '正切不等式可以直接照搬正弦余弦的“整周期图像块”思路，无需考虑定义域断点。',
            answer: false,
            explain: '正切有渐近线、周期为 $\\pi$，必须逐单调区间处理并守住无定义点。',
          },
        ],
      },
      {
        id: 'u11-l3',
        title: '参数·变形·单位圆',
        subtitle: '先看值域，再求交点',
        questions: [
          {
            id: 'u11-l3-q1',
            type: 'choice',
            prompt: '对参数不等式 $\\sin x\\ge a$，当 $a>1$ 时解集是？',
            options: [
              '全体实数',
              '空集（无解）',
              '$\\left[\\dfrac{\\pi}{6},\\dfrac{5\\pi}{6}\\right]$',
              '$\\{0\\}$',
            ],
            answer: 1,
            explain: '$\\sin x\\le1<a$，故不可能 $\\ge a$，无解。',
          },
          {
            id: 'u11-l3-q2',
            type: 'judge',
            prompt: '对 $\\sin x\\ge a$，当 $a<-1$ 时不等式恒成立。',
            answer: true,
            explain: '$\\sin x\\ge-1>a$，故对一切 $x$ 都成立。',
          },
          {
            id: 'u11-l3-q3',
            type: 'choice',
            prompt: '$2\\cos^2 x-1\\ge0$ 用二倍角化同名后等价于？',
            options: [
              '$\\cos 2x\\ge0$',
              '$\\sin 2x\\ge0$',
              '$\\cos 2x\\le0$',
              '$\\cos x\\ge0$',
            ],
            answer: 0,
            explain: '$2\\cos^2 x-1=\\cos 2x$，故等价于 $\\cos 2x\\ge0$。',
          },
          {
            id: 'u11-l3-q4',
            type: 'choice',
            prompt: '$2\\cos^2 x-1\\ge0$（即 $\\cos 2x\\ge0$）在全体实数上的解集是？',
            options: [
              '$\\left[-\\dfrac{\\pi}{4}+k\\pi,\\dfrac{\\pi}{4}+k\\pi\\right],\\ k\\in\\mathbb{Z}$',
              '$\\left[-\\dfrac{\\pi}{2}+k\\pi,\\dfrac{\\pi}{2}+k\\pi\\right],\\ k\\in\\mathbb{Z}$',
              '$\\left[-\\dfrac{\\pi}{4}+2k\\pi,\\dfrac{\\pi}{4}+2k\\pi\\right],\\ k\\in\\mathbb{Z}$',
              '$\\left(-\\dfrac{\\pi}{4}+k\\pi,\\dfrac{\\pi}{4}+k\\pi\\right),\\ k\\in\\mathbb{Z}$',
            ],
            answer: 0,
            explain: '$\\cos 2x\\ge0\\Rightarrow-\\dfrac{\\pi}{2}+2k\\pi\\le2x\\le\\dfrac{\\pi}{2}+2k\\pi$，整体除以 $2$ 得周期 $\\pi$、半长 $\\dfrac{\\pi}{4}$。',
          },
          {
            id: 'u11-l3-q5',
            type: 'match',
            prompt: '把符号条件与对应的单位圆区域配对：',
            left: [
              '$\\sin x\\ge0$',
              '$\\cos x<0$',
              '$\\tan x>0$',
              '$\\cos x>0$',
            ],
            right: [
              '上半圆',
              '左半圆',
              '第一、三象限',
              '右半圆',
            ],
            explain: '单位圆读符号最直接：正弦看上下、余弦看左右、正切看象限奇偶。',
          },
          {
            id: 'u11-l3-q6',
            type: 'judge',
            prompt: '处理参数不等式时，应先判断参数是否落在函数值域内，再去求交点。',
            answer: true,
            explain: '值域分析是参数不等式的第一步：先看有无交点，再求区间。',
          },
        ],
      },
    ],
  },

  // ============================== 单元 12 ==============================
  {
    id: 'u12',
    title: '参数·最值·综合变形',
    color: '#7c4dff',
    icon: '🎯',
    blurb: '$a\\sin x+b\\cos x$ 化 $R\\sin(x+\\varphi)$，$R=\\sqrt{a^2+b^2}$ 直接读最值；含参讨论',
    lessons: [
      {
        id: 'u12-l1',
        title: '辅助角与值域',
        subtitle: '$R=\\sqrt{a^2+b^2}$ 一锤定音',
        questions: [
          {
            id: 'u12-l1-q1',
            type: 'input',
            prompt: '$3\\sin x+4\\cos x$ 的最大值是？',
            accept: ['5', '５'],
            placeholder: '例如 5',
            explain: '$R=\\sqrt{3^2+4^2}=5$，故最大值为 $R=5$。',
          },
          {
            id: 'u12-l1-q2',
            type: 'choice',
            prompt: '$3\\sin x+4\\cos x$ 的值域是？',
            options: ['$[-3,3]$', '$[-4,4]$', '$[-5,5]$', '$[-7,7]$'],
            answer: 2,
            explain: '$R=5$，值域为 $[-R,R]=[-5,5]$。',
          },
          {
            id: 'u12-l1-q3',
            type: 'input',
            prompt: '$5\\sin x-12\\cos x$ 的值域为 $[-R,R]$，$R=?$（填一个数）。',
            accept: ['13', '１３'],
            placeholder: '例如 13',
            explain: '$R=\\sqrt{5^2+(-12)^2}=\\sqrt{169}=13$。',
          },
          {
            id: 'u12-l1-q4',
            type: 'judge',
            prompt: '$a\\sin x+b\\cos x$ 的值域由 $R=\\sqrt{a^2+b^2}$ 决定，与相位 $\\varphi$ 无关。',
            answer: true,
            explain: '只要算出 $R$ 即得值域 $[-R,R]$；$\\varphi$ 只影响取最值的具体 $x$。',
          },
          {
            id: 'u12-l1-q5',
            type: 'choice',
            prompt: '方程 $a\\sin x+b\\cos x=m$ 有解的充要条件是？',
            options: [
              '$|m|\\le\\sqrt{a^2+b^2}$',
              '$|m|\\ge\\sqrt{a^2+b^2}$',
              '$m\\le a+b$',
              '$m=\\sqrt{a^2+b^2}$',
            ],
            answer: 0,
            explain: '左边值域为 $[-\\sqrt{a^2+b^2},\\sqrt{a^2+b^2}]$，$m$ 落入其中才有解。',
          },
          {
            id: 'u12-l1-q6',
            type: 'judge',
            prompt: '$3\\sin x+4\\cos x$ 可看作向量 $(3,4)$ 的投影结构，向量长度 $5$ 限制了最大值不超过 $5$。',
            answer: true,
            explain: '辅助角公式背后有向量几何意义：模长 $\\sqrt{3^2+4^2}=5$ 即振幅 $R$。',
          },
        ],
      },
      {
        id: 'u12-l2',
        title: '降幂·综合变形',
        subtitle: '把“看似二次”压成 $A\\sin2x+B\\cos2x+C$',
        questions: [
          {
            id: 'u12-l2-q1',
            type: 'choice',
            prompt: '$(\\sin x+\\cos x)^2$ 展开并化简后等于？',
            options: [
              '$1+\\sin 2x$',
              '$1-\\sin 2x$',
              '$2+\\sin 2x$',
              '$\\sin 2x$',
            ],
            answer: 0,
            explain: '$\\sin^2x+\\cos^2x+2\\sin x\\cos x=1+\\sin 2x$。',
          },
          {
            id: 'u12-l2-q2',
            type: 'choice',
            prompt: '$(\\sin x+\\cos x)^2$ 的值域是？',
            options: ['$[0,2]$', '$[-1,1]$', '$[0,1]$', '$[-2,2]$'],
            answer: 0,
            explain: '等于 $1+\\sin 2x$，而 $\\sin 2x\\in[-1,1]$，故值域 $[0,2]$。',
          },
          {
            id: 'u12-l2-q3',
            type: 'input',
            prompt: '降幂公式：$\\sin^2 x=\\dfrac{1-\\cos 2x}{?}$（填分母）。',
            accept: ['2', '２'],
            placeholder: '例如 2',
            explain: '$\\sin^2 x=\\dfrac{1-\\cos 2x}{2}$。',
          },
          {
            id: 'u12-l2-q4',
            type: 'choice',
            prompt: '$f(x)=\\sin^2 x+\\sqrt3\\sin x\\cos x$ 化简后等于？',
            options: [
              '$\\dfrac12+\\sin\\!\\left(2x-\\dfrac{\\pi}{6}\\right)$',
              '$\\sin\\!\\left(2x-\\dfrac{\\pi}{6}\\right)$',
              '$\\dfrac12+\\sin\\!\\left(2x+\\dfrac{\\pi}{6}\\right)$',
              '$1+\\sin 2x$',
            ],
            answer: 0,
            explain: '降幂倍角得 $\\dfrac12+\\dfrac{\\sqrt3}{2}\\sin 2x-\\dfrac12\\cos 2x=\\dfrac12+\\sin\\!\\left(2x-\\dfrac{\\pi}{6}\\right)$。',
          },
          {
            id: 'u12-l2-q5',
            type: 'input',
            prompt: '上题 $f(x)=\\dfrac12+\\sin\\!\\left(2x-\\dfrac{\\pi}{6}\\right)$ 的最大值是？（填一个数，可用分数）',
            accept: ['3/2', '1.5', '\\frac32', '\\frac{3}{2}'],
            placeholder: '例如 3/2',
            explain: '$\\sin(\\cdot)$ 最大为 $1$，故 $f_{\\max}=\\dfrac12+1=\\dfrac32$。',
          },
          {
            id: 'u12-l2-q6',
            type: 'judge',
            prompt: '含 $\\sin^2 x$、$\\sin x\\cos x$ 的式子，应先降幂、倍角压成 $A\\sin2x+B\\cos2x+C$，再辅助角合并读值域。',
            answer: true,
            explain: '这是把“看似二次”的式子标准化的主线。',
          },
        ],
      },
      {
        id: 'u12-l3',
        title: '区间最值与含参讨论',
        subtitle: '先定内层角范围，再判单调',
        questions: [
          {
            id: 'u12-l3-q1',
            type: 'choice',
            prompt: '$f(x)=2\\sin\\!\\left(2x-\\dfrac{\\pi}{6}\\right)$ 在 $x\\in\\left[0,\\dfrac{\\pi}{2}\\right]$ 上的内层角 $u=2x-\\dfrac{\\pi}{6}$ 取值范围是？',
            options: [
              '$\\left[-\\dfrac{\\pi}{6},\\dfrac{5\\pi}{6}\\right]$',
              '$\\left[0,\\dfrac{\\pi}{2}\\right]$',
              '$\\left[-\\dfrac{\\pi}{6},\\dfrac{\\pi}{2}\\right]$',
              '$\\left[0,\\pi\\right]$',
            ],
            answer: 0,
            explain: '$x=0$ 时 $u=-\\dfrac{\\pi}{6}$，$x=\\dfrac{\\pi}{2}$ 时 $u=\\dfrac{5\\pi}{6}$。',
          },
          {
            id: 'u12-l3-q2',
            type: 'choice',
            prompt: '承上题，$f(x)=2\\sin u$ 在 $u\\in\\left[-\\dfrac{\\pi}{6},\\dfrac{5\\pi}{6}\\right]$ 上的最大值与最小值是？',
            options: [
              '最大 $2$，最小 $-1$',
              '最大 $2$，最小 $-2$',
              '最大 $1$，最小 $-1$',
              '最大 $2$，最小 $0$',
            ],
            answer: 0,
            explain: '$u=\\dfrac{\\pi}{2}$ 时 $\\sin u=1$（最大 $2$）；区间内 $\\sin u$ 最小为 $-\\dfrac12$（$u=-\\dfrac{\\pi}{6}$），故 $f_{\\min}=-1$。',
          },
          {
            id: 'u12-l3-q3',
            type: 'judge',
            prompt: '求 $2\\sin\\!\\left(2x-\\dfrac{\\pi}{6}\\right)$ 在限定区间上的最值，可以直接套用整体值域 $[-2,2]$，不必看内层角范围。',
            answer: false,
            explain: '限定区间时内层角未必取遍一个周期，必须先定 $u$ 的范围再判断能否到顶点/谷点。',
          },
          {
            id: 'u12-l3-q4',
            type: 'choice',
            prompt: '含参恒成立 $\\cos 2x+2a\\sin x+1\\ge0$ 化同名换元 $t=\\sin x\\in[-1,1]$ 后，转化为哪种问题？',
            options: [
              '闭区间 $[-1,1]$ 上二次函数恒成立',
              '一元一次不等式',
              '正切方程求解',
              '无解判定',
            ],
            answer: 0,
            explain: '化为 $t^2-at-1\\le0$ 对一切 $t\\in[-1,1]$ 恒成立，是闭区间上二次恒成立问题。',
          },
          {
            id: 'u12-l3-q5',
            type: 'input',
            prompt: '$\\cos 2x+2a\\sin x+1\\ge0$ 对一切实数 $x$ 恒成立，求出的参数 $a=?$（填一个数）。',
            accept: ['0', '０'],
            placeholder: '例如 0',
            explain: '$g(1)=-a\\le0$ 且 $g(-1)=a\\le0$ 夹逼出 $a=0$；代回得 $2\\cos^2 x\\ge0$ 成立。',
          },
          {
            id: 'u12-l3-q6',
            type: 'choice',
            prompt: '令 $u=\\sin x+\\cos x$，则 $u$ 的取值范围是？',
            options: [
              '$[-\\sqrt2,\\sqrt2]$',
              '$[-1,1]$',
              '$[-2,2]$',
              '$[0,\\sqrt2]$',
            ],
            answer: 0,
            explain: '$u=\\sqrt2\\sin\\!\\left(x+\\dfrac{\\pi}{4}\\right)$，故 $u\\in[-\\sqrt2,\\sqrt2]$，这是换元题的关键约束。',
          },
        ],
      },
    ],
  },
]
