import type { Unit } from '../../types'

// 内容取自《三角函数教程》第 8 部分（进阶）第 22–24 章：
// 信号·波与相量 / 旋转与向量 / 高级综合与展望。
// 公式用 $...$（KaTeX）。TS 字符串里所有 LaTeX 反斜杠均双写。

export const PART8_UNITS: Unit[] = [
  // ============================== 单元 22 ==============================
  {
    id: 'u22',
    title: '信号·波与相量',
    color: '#00cec9',
    icon: '📡',
    blurb: '正弦信号 $A\\cos(\\omega t+\\varphi)$、周期与相位、相量与同频叠加',
    lessons: [
      {
        id: 'u22-l1',
        title: '正弦信号的参数',
        subtitle: '振幅、角频率、周期、相位',
        questions: [
          {
            id: 'u22-l1-q1',
            type: 'choice',
            prompt: '在 $A\\cos(\\omega t+\\varphi)$ 中，$A$ 表示什么？',
            options: ['角频率', '振幅', '相位', '周期'],
            answer: 1,
            explain: '$A$ 是振幅，$\\omega$ 是角频率，$\\varphi$ 是初相位。',
          },
          {
            id: 'u22-l1-q2',
            type: 'input',
            prompt: '信号 $A\\cos(\\omega t+\\varphi)$ 中 $\\omega=2\\pi$，周期 $T=?$',
            accept: ['1', 'T=1', '1s', '1 秒'],
            placeholder: '填数字',
            explain: '$T=\\dfrac{2\\pi}{\\omega}=\\dfrac{2\\pi}{2\\pi}=1$。',
          },
          {
            id: 'u22-l1-q3',
            type: 'input',
            prompt: '某交流电压 $u(t)=12\\sin(100\\pi t+\\tfrac{\\pi}{6})$，它的振幅是多少？',
            accept: ['12', '12V', '12 伏', '12v'],
            placeholder: '填数字',
            explain: '对照 $A\\sin(\\omega t+\\phi)$，振幅 $A=12$ 伏。',
          },
          {
            id: 'u22-l1-q4',
            type: 'judge',
            prompt: '角频率 $\\omega$ 与频率 $f$ 满足 $\\omega=2\\pi f$。',
            answer: true,
            explain: '$\\omega$ 单位 rad/s，$f$ 单位 Hz，二者差一个 $2\\pi$：$\\omega=2\\pi f$。',
          },
          {
            id: 'u22-l1-q5',
            type: 'input',
            prompt: '$u(t)=12\\sin(100\\pi t+\\tfrac{\\pi}{6})$ 的频率 $f=?$（单位 Hz，填数字）',
            accept: ['50', '50Hz', '50 Hz', '50hz'],
            placeholder: '填数字',
            explain: '$f=\\dfrac{\\omega}{2\\pi}=\\dfrac{100\\pi}{2\\pi}=50$ Hz，正是我国工频。',
          },
          {
            id: 'u22-l1-q6',
            type: 'choice',
            prompt: '周期 $T$ 与角频率 $\\omega$ 的关系是？',
            options: [
              '$T=\\dfrac{\\omega}{2\\pi}$',
              '$T=2\\pi\\omega$',
              '$T=\\dfrac{2\\pi}{\\omega}$',
              '$T=\\dfrac{\\pi}{\\omega}$',
            ],
            answer: 2,
            explain: '$T=\\dfrac{2\\pi}{\\omega}$，周期与角频率成反比。',
          },
          {
            id: 'u22-l1-q7',
            type: 'judge',
            prompt: '相位 $\\varphi$ 只是无关紧要的小修正，对叠加结果没有影响。',
            answer: false,
            explain: '相位决定峰值出现时间，会显著影响叠加结果，甚至导致部分抵消。',
          },
        ],
      },
      {
        id: 'u22-l2',
        title: '拍频与同频叠加',
        subtitle: '和差化积看波的合成',
        questions: [
          {
            id: 'u22-l2-q1',
            type: 'choice',
            prompt: '$\\sin 101t+\\sin 99t$ 用和差化积等于？',
            options: [
              '$2\\sin 100t\\cos t$',
              '$2\\cos 100t\\sin t$',
              '$2\\sin 100t\\sin t$',
              '$\\sin 200t$',
            ],
            answer: 0,
            explain: '$\\sin\\alpha+\\sin\\beta=2\\sin\\tfrac{\\alpha+\\beta}{2}\\cos\\tfrac{\\alpha-\\beta}{2}=2\\sin 100t\\cos t$。',
          },
          {
            id: 'u22-l2-q2',
            type: 'judge',
            prompt: '拍频现象中，快速振荡被一个慢变化的包络调制。',
            answer: true,
            explain: '如 $2\\sin 100t\\cos t$：$\\sin 100t$ 快振荡，$2\\cos t$ 是慢包络。',
          },
          {
            id: 'u22-l2-q3',
            type: 'input',
            prompt: '两音 $440$ Hz 与 $444$ Hz 叠加，每秒听到几次强弱起伏（拍频，填数字）？',
            accept: ['4', '4Hz', '4 Hz', '4hz', '4次'],
            placeholder: '填数字',
            explain: '拍频 $=|f_1-f_2|=|444-440|=4$ Hz。',
          },
          {
            id: 'u22-l2-q4',
            type: 'choice',
            prompt: '把 $s(t)=3\\cos 2t+4\\sin 2t$ 化为 $A\\sin(2t+\\phi)$，振幅 $A=?$',
            options: ['$5$', '$7$', '$\\sqrt7$', '$25$'],
            answer: 0,
            explain: '$A=\\sqrt{3^2+4^2}=\\sqrt{25}=5$。',
          },
          {
            id: 'u22-l2-q5',
            type: 'input',
            prompt: '求 $\\cos t+\\cos(t+\\tfrac{\\pi}{3})$ 的合成振幅（精确值）。',
            accept: ['√3', 'sqrt3', 'sqrt(3)', '\\sqrt3', '\\sqrt{3}', '根号3'],
            placeholder: '例如 √2',
            explain: '$\\cos t+\\cos(t+\\tfrac{\\pi}{3})=2\\cos\\tfrac{\\pi}{6}\\cos(t+\\tfrac{\\pi}{6})=\\sqrt3\\cos(t+\\tfrac{\\pi}{6})$。',
          },
          {
            id: 'u22-l2-q6',
            type: 'judge',
            prompt: '三个等幅、相位互差 $120^\\circ$ 的同频波叠加，合成结果恒为零。',
            answer: true,
            explain: '三个等长向量首尾相接成正三角形，合矢量为零——这正是三相交流平衡的原理。',
          },
        ],
      },
      {
        id: 'u22-l3',
        title: '相量表示',
        subtitle: '把波冻结成复平面上的向量',
        questions: [
          {
            id: 'u22-l3-q1',
            type: 'choice',
            prompt: '相量法的核心思想是把正弦波看成？',
            options: [
              '复平面上的旋转向量',
              '一条直线',
              '一个实数',
              '抛物线',
            ],
            answer: 0,
            explain: '相量把正弦波表示为复平面上以 $\\omega$ 旋转的向量：模是振幅、辐角是初相。',
          },
          {
            id: 'u22-l3-q2',
            type: 'judge',
            prompt: '用相量法时，同频波的公共因子 $e^{i\\omega t}$ 可以约去，于是叠加变成向量相加。',
            answer: true,
            explain: '同频所有波都含 $e^{i\\omega t}$，约去后只剩不随时间变的复数（相量），叠加即向量加法。',
          },
          {
            id: 'u22-l3-q3',
            type: 'input',
            prompt: '把 $v(t)=6\\cos(\\omega t-\\tfrac{\\pi}{4})$ 写成相量 $A\\angle\\phi$，模 $A=?$',
            accept: ['6', 'A=6'],
            placeholder: '填数字',
            explain: '以 $\\cos(\\omega t+\\phi)\\leftrightarrow A\\angle\\phi$，模即振幅 $A=6$，辐角 $-\\tfrac{\\pi}{4}$。',
          },
          {
            id: 'u22-l3-q4',
            type: 'choice',
            prompt: '相量 $\\mathbf V=6\\angle(-\\tfrac{\\pi}{4})$ 位于复平面的哪个象限？',
            options: ['第一象限', '第二象限', '第三象限', '第四象限'],
            answer: 3,
            explain: '辐角 $-45^\\circ$，实部正、虚部负，位于第四象限：$3\\sqrt2-3\\sqrt2 i$。',
          },
          {
            id: 'u22-l3-q5',
            type: 'input',
            prompt: '用相量法求 $\\sin\\theta+\\sqrt3\\cos\\theta$ 的合成振幅。',
            accept: ['2', 'A=2'],
            placeholder: '填数字',
            explain: '相量 $1\\angle 0+\\sqrt3\\angle\\tfrac{\\pi}{2}=1+\\sqrt3 i$，振幅 $\\sqrt{1+3}=2$。',
          },
          {
            id: 'u22-l3-q6',
            type: 'match',
            prompt: '把正弦信号术语与含义配对。',
            left: ['$A$', '$\\omega$', '$T=\\tfrac{2\\pi}{\\omega}$', '相量的辐角'],
            right: ['振幅', '角频率', '周期', '初相位'],
            explain: '振幅—角频率—周期—初相位，是信号分析的四个基本参数。',
          },
        ],
      },
    ],
  },

  // ============================== 单元 23 ==============================
  {
    id: 'u23',
    title: '旋转与向量',
    color: '#fd79a8',
    icon: '🧭',
    blurb: '旋转矩阵 $R(\\theta)$、单位圆点坐标、复数乘 $e^{i\\theta}$ 即旋转',
    lessons: [
      {
        id: 'u23-l1',
        title: '二维旋转矩阵',
        subtitle: '基向量旋转后的坐标拼接',
        questions: [
          {
            id: 'u23-l1-q1',
            type: 'choice',
            prompt: '逆时针旋转 $\\theta$ 的二维旋转矩阵 $R(\\theta)=?$',
            options: [
              '$\\begin{pmatrix}\\cos\\theta&-\\sin\\theta\\\\\\sin\\theta&\\cos\\theta\\end{pmatrix}$',
              '$\\begin{pmatrix}\\cos\\theta&\\sin\\theta\\\\-\\sin\\theta&\\cos\\theta\\end{pmatrix}$',
              '$\\begin{pmatrix}\\sin\\theta&\\cos\\theta\\\\\\cos\\theta&-\\sin\\theta\\end{pmatrix}$',
              '$\\begin{pmatrix}1&0\\\\0&1\\end{pmatrix}$',
            ],
            answer: 0,
            explain: '$R(\\theta)=\\begin{pmatrix}\\cos\\theta&-\\sin\\theta\\\\\\sin\\theta&\\cos\\theta\\end{pmatrix}$，负号在右上角。',
          },
          {
            id: 'u23-l1-q2',
            type: 'choice',
            prompt: '把单位向量 $(1,0)$ 逆时针旋转 $\\theta$，得到的坐标是？',
            options: [
              '$(\\cos\\theta,\\sin\\theta)$',
              '$(-\\sin\\theta,\\cos\\theta)$',
              '$(\\sin\\theta,\\cos\\theta)$',
              '$(\\cos\\theta,-\\sin\\theta)$',
            ],
            answer: 0,
            explain: '$(1,0)$ 旋转 $\\theta$ 得 $(\\cos\\theta,\\sin\\theta)$，正是单位圆上的点。',
          },
          {
            id: 'u23-l1-q3',
            type: 'input',
            prompt: '把 $(1,0)$ 逆时针旋转 $90^\\circ$，得到的坐标是？',
            accept: ['(0,1)', '0,1', '(0, 1)'],
            placeholder: '例如 (0,1)',
            explain: '$R(90^\\circ)=\\begin{pmatrix}0&-1\\\\1&0\\end{pmatrix}$，$(1,0)\\to(0,1)$。',
          },
          {
            id: 'u23-l1-q4',
            type: 'input',
            prompt: '把向量 $(3,4)$ 绕原点逆时针旋转 $90^\\circ$，得到的坐标是？',
            accept: ['(-4,3)', '-4,3', '(-4, 3)'],
            placeholder: '例如 (-4,3)',
            explain: '逆时针 $90^\\circ$ 的效果是 $(x,y)\\mapsto(-y,x)$，故 $(3,4)\\to(-4,3)$。',
          },
          {
            id: 'u23-l1-q5',
            type: 'judge',
            prompt: '旋转不改变向量的模长。',
            answer: true,
            explain: '旋转是正交变换，$|R\\mathbf v|=|\\mathbf v|$。如 $(3,4)$ 与 $(-4,3)$ 模长都是 $5$。',
          },
          {
            id: 'u23-l1-q6',
            type: 'input',
            prompt: '把点 $(2,0)$ 绕原点逆时针旋转 $60^\\circ$，得到的坐标是？',
            accept: ['(1,√3)', '(1,sqrt3)', '1,√3', '(1, √3)', '(1,根号3)'],
            placeholder: '例如 (1,√3)',
            explain: '$2(\\cos 60^\\circ,\\sin 60^\\circ)=2(\\tfrac12,\\tfrac{\\sqrt3}{2})=(1,\\sqrt3)$。',
          },
        ],
      },
      {
        id: 'u23-l2',
        title: '点积、夹角与旋转性质',
        subtitle: '余弦衡量方向相似度',
        questions: [
          {
            id: 'u23-l2-q1',
            type: 'choice',
            prompt: '向量夹角公式 $\\mathbf a\\cdot\\mathbf b=?$',
            options: [
              '$|\\mathbf a||\\mathbf b|\\sin\\theta$',
              '$|\\mathbf a||\\mathbf b|\\cos\\theta$',
              '$|\\mathbf a|+|\\mathbf b|$',
              '$|\\mathbf a||\\mathbf b|\\tan\\theta$',
            ],
            answer: 1,
            explain: '$\\mathbf a\\cdot\\mathbf b=|\\mathbf a||\\mathbf b|\\cos\\theta$，余弦衡量方向相似程度。',
          },
          {
            id: 'u23-l2-q2',
            type: 'input',
            prompt: '$\\mathbf a=(1,\\sqrt3)$、$\\mathbf b=(\\sqrt3,1)$ 的夹角是多少度（填数字）？',
            accept: ['30', '30°', '30度'],
            placeholder: '填数字',
            explain: '$\\cos\\theta=\\dfrac{\\mathbf a\\cdot\\mathbf b}{|\\mathbf a||\\mathbf b|}=\\dfrac{2\\sqrt3}{2\\cdot 2}=\\dfrac{\\sqrt3}{2}$，故 $\\theta=30^\\circ$。',
          },
          {
            id: 'u23-l2-q3',
            type: 'judge',
            prompt: '二维旋转矩阵满足 $R_\\alpha R_\\beta=R_{\\alpha+\\beta}$。',
            answer: true,
            explain: '矩阵相乘后用和角公式可证 $R_\\alpha R_\\beta=R_{\\alpha+\\beta}$，把和角公式装进了矩阵里。',
          },
          {
            id: 'u23-l2-q4',
            type: 'choice',
            prompt: '旋转矩阵 $R_\\theta$ 的逆矩阵等于？',
            options: [
              '$R_{2\\theta}$',
              '$R_{-\\theta}=R_\\theta^{T}$',
              '$-R_\\theta$',
              '$R_\\theta$ 本身',
            ],
            answer: 1,
            explain: '旋转矩阵是正交矩阵，$R_\\theta^{-1}=R_{-\\theta}=R_\\theta^{T}$，几何上即反向旋转。',
          },
          {
            id: 'u23-l2-q5',
            type: 'input',
            prompt: '旋转矩阵 $R_\\theta$ 的行列式 $\\det R_\\theta=?$',
            accept: ['1', 'det=1'],
            placeholder: '填数字',
            explain: '$\\det R_\\theta=\\cos^2\\theta+\\sin^2\\theta=1$。',
          },
          {
            id: 'u23-l2-q6',
            type: 'judge',
            prompt: '三维空间中绕不同轴的旋转一般满足交换律。',
            answer: false,
            explain: '三维旋转一般不可交换：$R_x(\\alpha)R_z(\\beta)\\neq R_z(\\beta)R_x(\\alpha)$。仅二维旋转可交换。',
          },
        ],
      },
      {
        id: 'u23-l3',
        title: '复数乘法即旋转',
        subtitle: '$e^{i\\theta}$ 与旋转矩阵的统一',
        questions: [
          {
            id: 'u23-l3-q1',
            type: 'choice',
            prompt: '在复平面里，乘以 $e^{i\\theta}$ 对应什么几何动作？',
            options: [
              '逆时针旋转角度 $\\theta$',
              '平移 $\\theta$',
              '关于实轴反射',
              '放大 $\\theta$ 倍',
            ],
            answer: 0,
            explain: '单位模长的 $e^{i\\theta}$ 把复数逆时针旋转 $\\theta$，与旋转矩阵是同一现象。',
          },
          {
            id: 'u23-l3-q2',
            type: 'input',
            prompt: '欧拉公式 $e^{i\\theta}=?$（用 $\\cos\\theta$、$\\sin\\theta$ 表示）',
            accept: ['cosθ+isinθ', 'cos θ + i sin θ', '\\cos\\theta+i\\sin\\theta', 'cosθ+i sinθ'],
            placeholder: '例如 cosθ+isinθ',
            explain: '$e^{i\\theta}=\\cos\\theta+i\\sin\\theta$，这是连接旋转矩阵与复数的桥梁。',
          },
          {
            id: 'u23-l3-q3',
            type: 'input',
            prompt: '把 $z=1+i$ 乘以 $e^{i45^\\circ}$（旋转 $45^\\circ$），结果是？',
            accept: ['√2 i', 'sqrt2 i', '√2i', '\\sqrt2 i', '√2*i', '根号2 i'],
            placeholder: '例如 √2 i',
            explain: '$1+i$ 模长 $\\sqrt2$、辐角 $45^\\circ$，再转 $45^\\circ$ 得辐角 $90^\\circ$、模长 $\\sqrt2$，即 $\\sqrt2\\,i$。',
          },
          {
            id: 'u23-l3-q4',
            type: 'judge',
            prompt: '“旋转矩阵作用于向量”与“复数乘以 $e^{i\\theta}$”给出相同结果。',
            answer: true,
            explain: '$e^{i\\theta}(x+iy)$ 的实部、虚部恰是 $R_\\theta\\binom{x}{y}$ 的两个分量，二者等价。',
          },
          {
            id: 'u23-l3-q5',
            type: 'input',
            prompt: '把 $(1,0,0)$ 绕 $z$ 轴旋转 $90^\\circ$，得到的坐标是？',
            accept: ['(0,1,0)', '0,1,0', '(0, 1, 0)'],
            placeholder: '例如 (0,1,0)',
            explain: '$R_z(90^\\circ)$ 把 $x$ 轴上的点转到 $y$ 轴上：$(1,0,0)\\to(0,1,0)$。',
          },
          {
            id: 'u23-l3-q6',
            type: 'match',
            prompt: '把旋转/向量概念与其表述配对。',
            left: [
              '$R(\\theta)$ 第一列',
              '$\\mathbf a\\cdot\\mathbf b$',
              '乘 $e^{i\\theta}$',
              '$\\det R_\\theta$',
            ],
            right: [
              '$(\\cos\\theta,\\sin\\theta)$',
              '$|\\mathbf a||\\mathbf b|\\cos\\theta$',
              '逆时针旋转 $\\theta$',
              '$1$',
            ],
            explain: '旋转矩阵第一列是 $\\mathbf e_1$ 的去向；点积含余弦；复数乘法即旋转；旋转行列式为 $1$。',
          },
        ],
      },
    ],
  },

  // ============================== 单元 24 ==============================
  {
    id: 'u24',
    title: '高级综合与展望',
    color: '#55a630',
    icon: '🏆',
    blurb: '辅助角、正余弦定理、欧拉、相量、旋转的混合复习与方法选择',
    lessons: [
      {
        id: 'u24-l1',
        title: '选对表示系统',
        subtitle: '先判断方法，再动手计算',
        questions: [
          {
            id: 'u24-l1-q1',
            type: 'choice',
            prompt: '高阶三角题的第一步通常应该是？',
            options: [
              '立刻代入公式硬算',
              '先判断该用哪种表示系统',
              '直接求导',
              '画图量角',
            ],
            answer: 1,
            explain: '先判断表示系统（单位圆/图像/恒等式/几何/复数/信号），再计算，能避免硬算。',
          },
          {
            id: 'u24-l1-q2',
            type: 'input',
            prompt: '用辅助角公式求 $\\sin x+\\cos x$ 的最大值。',
            accept: ['√2', 'sqrt2', '\\sqrt2', '\\sqrt{2}', '根号2'],
            placeholder: '例如 √2',
            explain: '$\\sin x+\\cos x=\\sqrt2\\sin(x+\\tfrac{\\pi}{4})$，最大值 $\\sqrt2$。',
          },
          {
            id: 'u24-l1-q3',
            type: 'choice',
            prompt: '求 $f(x)=\\sin x+\\sqrt3\\cos x$ 的最大值是？',
            options: ['$1$', '$2$', '$\\sqrt3$', '$\\sqrt2$'],
            answer: 1,
            explain: '$f(x)=2\\sin(x+\\tfrac{\\pi}{3})$，最大值为 $2$。',
          },
          {
            id: 'u24-l1-q4',
            type: 'match',
            prompt: '把题型信号与优先方法配对。',
            left: ['角位置、象限', '周期、最值', '一般三角形', '旋转、单位根'],
            right: ['单位圆', '图像', '正弦/余弦定理', '复数/欧拉公式'],
            explain: '识别题型信号是高阶解题的关键：不同结构对应不同最优表示。',
          },
          {
            id: 'u24-l1-q5',
            type: 'judge',
            prompt: '正确选对方法常常能让题目直接变短，而错误方法会让题目显得很难。',
            answer: true,
            explain: '如求 $\\sin x+\\cos x$ 最值，辅助角一步出 $\\sqrt2$；平方展开则绕远路。',
          },
          {
            id: 'u24-l1-q6',
            type: 'input',
            prompt: '在 $\\triangle ABC$ 中 $b=7$，$c=5$，$A=120^\\circ$，求边 $a$（精确值）。',
            accept: ['√109', 'sqrt109', '\\sqrt{109}', '\\sqrt109', '根号109'],
            placeholder: '例如 √109',
            explain: '余弦定理：$a^2=49+25-2\\cdot7\\cdot5\\cos120^\\circ=74+35=109$，$a=\\sqrt{109}$。',
          },
        ],
      },
      {
        id: 'u24-l2',
        title: '复数与多倍角综合',
        subtitle: '棣莫弗、欧拉与值域',
        questions: [
          {
            id: 'u24-l2-q1',
            type: 'input',
            prompt: '不查表求 $\\cos 75^\\circ$ 的精确值。',
            accept: [
              '(√6-√2)/4',
              '(sqrt6-sqrt2)/4',
              '\\frac{\\sqrt6-\\sqrt2}{4}',
              '(√6−√2)/4',
              '(根号6-根号2)/4',
            ],
            placeholder: '例如 (√6-√2)/4',
            explain: '$\\cos 75^\\circ=\\cos(45^\\circ+30^\\circ)=\\dfrac{\\sqrt6-\\sqrt2}{4}\\approx0.2588$。',
          },
          {
            id: 'u24-l2-q2',
            type: 'choice',
            prompt: '用棣莫弗定理化简，$\\cos 3\\theta=?$',
            options: [
              '$3\\cos\\theta-4\\cos^3\\theta$',
              '$4\\cos^3\\theta-3\\cos\\theta$',
              '$2\\cos^2\\theta-1$',
              '$\\cos^3\\theta$',
            ],
            answer: 1,
            explain: '取 $(\\cos\\theta+i\\sin\\theta)^3$ 的实部并代 $\\sin^2=1-\\cos^2$，得 $\\cos 3\\theta=4\\cos^3\\theta-3\\cos\\theta$。',
          },
          {
            id: 'u24-l2-q3',
            type: 'judge',
            prompt: '$\\cos 3\\theta=4\\cos^3\\theta-3\\cos\\theta$ 正是切比雪夫多项式 $T_3$。',
            answer: true,
            explain: '它在数值分析与逼近论中反复出现，是 $T_3(\\cos\\theta)=\\cos 3\\theta$。',
          },
          {
            id: 'u24-l2-q4',
            type: 'choice',
            prompt: '求值域 $g(x)=\\dfrac{\\sin x}{2+\\cos x}$，其值域是？',
            options: [
              '$[-1,1]$',
              '$\\left[-\\tfrac{\\sqrt3}{3},\\tfrac{\\sqrt3}{3}\\right]$',
              '$[-\\sqrt3,\\sqrt3]$',
              '$\\mathbb R$',
            ],
            answer: 1,
            explain: '整理为 $\\sin x-y\\cos x=2y$，由 $|2y|\\le\\sqrt{1+y^2}$ 得 $3y^2\\le1$，值域 $\\left[-\\tfrac{\\sqrt3}{3},\\tfrac{\\sqrt3}{3}\\right]$。',
          },
          {
            id: 'u24-l2-q5',
            type: 'input',
            prompt: '欧拉公式 $e^{i\\pi}+1=?$',
            accept: ['0', '=0'],
            placeholder: '填数字',
            explain: '$e^{i\\pi}=-1$，故 $e^{i\\pi}+1=0$——欧拉恒等式。',
          },
          {
            id: 'u24-l2-q6',
            type: 'judge',
            prompt: '当题目涉及旋转、幂或单位根时，复数/欧拉公式往往比堆三角恒等式更高效。',
            answer: true,
            explain: '复数把旋转与多倍角统一为乘幂运算，常常一步到位。',
          },
        ],
      },
      {
        id: 'u24-l3',
        title: '混合复习与展望',
        subtitle: '相量、旋转、定理跨主题综合',
        questions: [
          {
            id: 'u24-l3-q1',
            type: 'judge',
            prompt: '（混合复习）信号 $\\cos\\omega t+\\cos(\\omega t+\\tfrac{2\\pi}{3})+\\cos(\\omega t+\\tfrac{4\\pi}{3})\\equiv 0$。',
            answer: true,
            explain: '三个等幅、互差 $120^\\circ$ 的相量和为零，对应单位根 $1+\\omega+\\omega^2=0$。',
          },
          {
            id: 'u24-l3-q2',
            type: 'input',
            prompt: '（混合复习·相量）信号 $A\\cos(\\omega t+\\varphi)$ 中 $\\omega=4\\pi$，周期 $T=?$',
            accept: ['0.5', '1/2', '½', '0.5s'],
            placeholder: '填数字',
            explain: '$T=\\dfrac{2\\pi}{\\omega}=\\dfrac{2\\pi}{4\\pi}=\\dfrac12$。',
          },
          {
            id: 'u24-l3-q3',
            type: 'input',
            prompt: '（混合复习·旋转）把 $(0,1)$ 绕原点逆时针旋转 $90^\\circ$，得到的坐标是？',
            accept: ['(-1,0)', '-1,0', '(-1, 0)'],
            placeholder: '例如 (-1,0)',
            explain: '$(x,y)\\mapsto(-y,x)$，故 $(0,1)\\to(-1,0)$。',
          },
          {
            id: 'u24-l3-q4',
            type: 'choice',
            prompt: '（混合复习·辅助角）$2\\sin x+2\\cos x$ 的振幅是？',
            options: ['$2$', '$2\\sqrt2$', '$4$', '$\\sqrt2$'],
            answer: 1,
            explain: '$A=\\sqrt{2^2+2^2}=\\sqrt8=2\\sqrt2$。',
          },
          {
            id: 'u24-l3-q5',
            type: 'choice',
            prompt: '（混合复习·定理）以下哪种情形最适合用余弦定理？',
            options: [
              '已知两角及一边',
              '已知两边及夹角求第三边',
              '已知周期求频率',
              '把波化为相量',
            ],
            answer: 1,
            explain: '“两边及夹角求第三边”直指余弦定理 $a^2=b^2+c^2-2bc\\cos A$。',
          },
          {
            id: 'u24-l3-q6',
            type: 'match',
            prompt: '（混合复习）把概念与所属主题配对。',
            left: [
              '$R(\\theta)=\\begin{pmatrix}\\cos\\theta&-\\sin\\theta\\\\\\sin\\theta&\\cos\\theta\\end{pmatrix}$',
              '$T=\\tfrac{2\\pi}{\\omega}$',
              '$e^{i\\theta}=\\cos\\theta+i\\sin\\theta$',
              '$a^2=b^2+c^2-2bc\\cos A$',
            ],
            right: ['旋转矩阵', '正弦信号周期', '欧拉公式', '余弦定理'],
            explain: '四条核心结果分别来自旋转、信号、复数与解三角形，是本教程的主线。',
          },
          {
            id: 'u24-l3-q7',
            type: 'judge',
            prompt: '学完三角函数后，微积分、线性代数/几何、信号处理是三条自然的延伸路线。',
            answer: true,
            explain: '分别对应导数与 Fourier、旋转与正交变换、拍频调制与相量——三角函数是它们共同的语言。',
          },
        ],
      },
    ],
  },
]
