import type { Unit } from '../../types'

// 内容取自《三角函数教程》第 13–15 章：直角三角形测量 / 正弦余弦定理 / 面积与几何恒等式。
// 公式用 $...$（KaTeX）。输入题的 accept 提供多种等价写法，配合容错匹配。

export const PART5_UNITS: Unit[] = [
  // ============================== 单元 13 ==============================
  {
    id: 'u13',
    title: '直角三角形与测量',
    color: '#ff9600',
    icon: '📐',
    blurb: 'SOH-CAH-TOA、仰角俯角、勾股——三角函数最稳固的应用入口',
    lessons: [
      {
        id: 'u13-l1',
        title: 'SOH-CAH-TOA',
        subtitle: '对边、邻边、斜边与三个比值',
        questions: [
          {
            id: 'u13-l1-q1',
            type: 'choice',
            prompt: '在直角三角形中，$\\sin\\theta$ 等于哪个比值？',
            options: ['对边 / 斜边', '邻边 / 斜边', '对边 / 邻边', '斜边 / 对边'],
            answer: 0,
            explain: 'SOH：$\\sin\\theta=\\dfrac{\\text{对边}}{\\text{斜边}}$。',
          },
          {
            id: 'u13-l1-q2',
            type: 'choice',
            prompt: '$\\cos\\theta$ 等于哪个比值？',
            options: ['对边 / 斜边', '邻边 / 斜边', '对边 / 邻边', '邻边 / 对边'],
            answer: 1,
            explain: 'CAH：$\\cos\\theta=\\dfrac{\\text{邻边}}{\\text{斜边}}$。',
          },
          {
            id: 'u13-l1-q3',
            type: 'judge',
            prompt: '$\\tan\\theta=\\dfrac{\\text{对边}}{\\text{邻边}}$。',
            answer: true,
            explain: 'TOA：正切等于对边比邻边，正确。',
          },
          {
            id: 'u13-l1-q4',
            type: 'input',
            prompt: '直角三角形中，$\\theta$ 的对边为 $3$，斜边为 $5$，求 $\\sin\\theta$（填小数或分数）。',
            accept: ['0.6', '3/5', '.6', '0.60'],
            placeholder: '例如 0.5',
            explain: '$\\sin\\theta=\\dfrac{\\text{对边}}{\\text{斜边}}=\\dfrac{3}{5}=0.6$。',
          },
          {
            id: 'u13-l1-q5',
            type: 'input',
            prompt: '同上三角形（对边 $3$、斜边 $5$、邻边 $4$），求 $\\tan\\theta$（填小数或分数）。',
            accept: ['0.75', '3/4', '.75'],
            placeholder: '例如 0.75',
            explain: '$\\tan\\theta=\\dfrac{\\text{对边}}{\\text{邻边}}=\\dfrac{3}{4}=0.75$。',
          },
          {
            id: 'u13-l1-q6',
            type: 'match',
            prompt: '把每个三角函数与它的边比对应起来。',
            left: ['$\\sin\\theta$', '$\\cos\\theta$', '$\\tan\\theta$'],
            right: ['对边 / 斜边', '邻边 / 斜边', '对边 / 邻边'],
            explain: 'SOH-CAH-TOA：正弦=对/斜，余弦=邻/斜，正切=对/邻。',
          },
        ],
      },
      {
        id: 'u13-l2',
        title: '勾股定理与求边',
        subtitle: '$a^2+b^2=c^2$ 与特殊勾股数',
        questions: [
          {
            id: 'u13-l2-q1',
            type: 'input',
            prompt: '直角三角形两条直角边为 $3$ 与 $4$，求斜边长。',
            accept: ['5', '5.0'],
            placeholder: '例如 5',
            explain: '$c=\\sqrt{3^2+4^2}=\\sqrt{25}=5$（$3\\text{-}4\\text{-}5$ 勾股数）。',
          },
          {
            id: 'u13-l2-q2',
            type: 'input',
            prompt: '直角三角形斜边为 $13$，一条直角边为 $5$，求另一条直角边长。',
            accept: ['12', '12.0'],
            placeholder: '例如 12',
            explain: '$b=\\sqrt{13^2-5^2}=\\sqrt{169-25}=\\sqrt{144}=12$（$5\\text{-}12\\text{-}13$ 勾股数）。',
          },
          {
            id: 'u13-l2-q3',
            type: 'choice',
            prompt: '上题中，直角边 $12$ 所对锐角 $\\theta$ 的正弦 $\\sin\\theta$ 为？',
            options: ['$\\dfrac{5}{13}$', '$\\dfrac{12}{13}$', '$\\dfrac{5}{12}$', '$\\dfrac{12}{5}$'],
            answer: 1,
            explain: '$12$ 是 $\\theta$ 的对边、$13$ 是斜边，$\\sin\\theta=\\dfrac{12}{13}$。',
          },
          {
            id: 'u13-l2-q4',
            type: 'judge',
            prompt: '三边为 $6,8,10$ 的三角形是直角三角形。',
            answer: true,
            explain: '$6^2+8^2=36+64=100=10^2$，满足勾股定理，是直角三角形。',
          },
          {
            id: 'u13-l2-q5',
            type: 'input',
            prompt: '坡道与水平面夹角 $\\theta$ 满足 $\\sin\\theta=\\dfrac35$，车沿坡行 $100$ 米，求上升的垂直高度（米）。',
            accept: ['60', '60.0', '60米'],
            placeholder: '例如 60',
            explain: '斜边 $100$，高为对边：$h=100\\sin\\theta=100\\times\\dfrac35=60$ 米。',
          },
          {
            id: 'u13-l2-q6',
            type: 'input',
            prompt: '同上坡道，求水平前进的距离（米）。已知 $\\cos\\theta=\\dfrac45$。',
            accept: ['80', '80.0', '80米'],
            placeholder: '例如 80',
            explain: '水平距离为邻边：$d=100\\cos\\theta=100\\times\\dfrac45=80$ 米（$3\\text{-}4\\text{-}5$）。',
          },
        ],
      },
      {
        id: 'u13-l3',
        title: '仰角、俯角与测距',
        subtitle: '$h=d\\tan\\alpha$ 与两观测点',
        questions: [
          {
            id: 'u13-l3-q1',
            type: 'choice',
            prompt: '从观察点向上看目标，视线与水平线的夹角叫做？',
            options: ['俯角', '仰角', '坡角', '视角'],
            answer: 1,
            explain: '向上看为仰角，向下看为俯角。',
          },
          {
            id: 'u13-l3-q2',
            type: 'judge',
            prompt: '水平距离 $d$、仰角 $\\alpha$ 时，目标高度差 $h=d\\tan\\alpha$。',
            answer: true,
            explain: '$\\tan\\alpha=\\dfrac{h}{d}$，故 $h=d\\tan\\alpha$，正确。',
          },
          {
            id: 'u13-l3-q3',
            type: 'input',
            prompt: '俯角为 $45^\\circ$，观测点到目标的水平距离为 $30$ 米，求高度差（米）。',
            accept: ['30', '30.0', '30米'],
            placeholder: '例如 30',
            explain: '俯角等于对应仰角，$h=30\\tan45^\\circ=30\\times1=30$ 米。',
          },
          {
            id: 'u13-l3-q4',
            type: 'input',
            prompt: '梯子与地面夹角 $60^\\circ$，底端离墙脚 $1.5$ 米。求梯子长度（米）。',
            accept: ['3', '3.0', '3米'],
            placeholder: '例如 3',
            explain: '水平距离是斜边的邻边：$\\cos60^\\circ=\\dfrac{1.5}{L}$，$L=\\dfrac{1.5}{1/2}=3$ 米。',
          },
          {
            id: 'u13-l3-q5',
            type: 'choice',
            prompt: '已知水平距离与仰角，要求目标的高度差，最适合用哪个函数？',
            options: ['$\\sin$', '$\\cos$', '$\\tan$', '$\\cot$'],
            answer: 2,
            explain: '高度差/水平距离=对边/邻边，用 $\\tan$ 最直接。',
          },
          {
            id: 'u13-l3-q6',
            type: 'match',
            prompt: '把测量目标与优先使用的函数对应起来。',
            left: ['求高度差（已知仰角与水平距离）', '求斜边/实际长度（已知邻边与角）', '求高（已知斜边与角）'],
            right: ['$\\tan$', '$\\cos$', '$\\sin$'],
            explain: '高差用 $\\tan$，斜边用 $\\cos$，已知斜边求高用 $\\sin$。',
          },
        ],
      },
    ],
  },

  // ============================== 单元 14 ==============================
  {
    id: 'u14',
    title: '正弦定理·余弦定理',
    color: '#00b894',
    icon: '🔺',
    blurb: '离开直角三角形，用两条定理重新联系边与角',
    lessons: [
      {
        id: 'u14-l1',
        title: '余弦定理',
        subtitle: '$c^2=a^2+b^2-2ab\\cos C$',
        questions: [
          {
            id: 'u14-l1-q1',
            type: 'input',
            prompt: '$\\triangle ABC$ 中 $a=2,b=2,C=60^\\circ$，求 $c$。',
            accept: ['2', '2.0'],
            placeholder: '例如 2',
            explain: '$c^2=4+4-2\\cdot2\\cdot2\\cos60^\\circ=8-8\\cdot\\dfrac12=4$，故 $c=2$（等边）。',
          },
          {
            id: 'u14-l1-q2',
            type: 'choice',
            prompt: '$\\triangle ABC$ 中 $a=5,b=7,C=60^\\circ$，求 $c$。',
            options: ['$\\sqrt{39}$', '$\\sqrt{74}$', '$\\sqrt{109}$', '$12$'],
            answer: 0,
            explain: '$c^2=25+49-2\\cdot5\\cdot7\\cdot\\dfrac12=74-35=39$，$c=\\sqrt{39}$。',
          },
          {
            id: 'u14-l1-q3',
            type: 'choice',
            prompt: '$\\triangle ABC$ 中 $a=8,b=6,C=120^\\circ$，求 $c$。（$\\cos120^\\circ=-\\dfrac12$）',
            options: ['$\\sqrt{52}$', '$2\\sqrt{37}$', '$10$', '$2\\sqrt{13}$'],
            answer: 1,
            explain: '$c^2=64+36-2\\cdot8\\cdot6\\cdot(-\\tfrac12)=100+48=148$，$c=\\sqrt{148}=2\\sqrt{37}$。',
          },
          {
            id: 'u14-l1-q4',
            type: 'judge',
            prompt: '当 $C=90^\\circ$ 时，余弦定理 $c^2=a^2+b^2-2ab\\cos C$ 退化为勾股定理。',
            answer: true,
            explain: '$\\cos90^\\circ=0$，故 $c^2=a^2+b^2$，正是勾股定理。',
          },
          {
            id: 'u14-l1-q5',
            type: 'input',
            prompt: '三边为 $3,4,5$，求最大边所对角的余弦 $\\cos C$（最大边 $c=5$）。',
            accept: ['0', '0.0'],
            placeholder: '例如 0',
            explain: '$\\cos C=\\dfrac{3^2+4^2-5^2}{2\\cdot3\\cdot4}=\\dfrac{0}{24}=0$，故 $C=90^\\circ$。',
          },
          {
            id: 'u14-l1-q6',
            type: 'match',
            prompt: '把已知条件与优先使用的定理对应起来。',
            left: ['两边及其夹角求第三边', '已知三边求角', '两角一边求边'],
            right: ['余弦定理', '余弦定理', '正弦定理'],
            explain: '两边夹角、三边求角用余弦定理；两角一边用正弦定理。',
          },
        ],
      },
      {
        id: 'u14-l2',
        title: '正弦定理',
        subtitle: '$\\dfrac{a}{\\sin A}=\\dfrac{b}{\\sin B}=2R$',
        questions: [
          {
            id: 'u14-l2-q1',
            type: 'choice',
            prompt: '正弦定理表述为？',
            options: [
              '$\\dfrac{a}{\\sin A}=\\dfrac{b}{\\sin B}=\\dfrac{c}{\\sin C}$',
              '$a^2=b^2+c^2-2bc\\cos A$',
              '$\\dfrac{\\sin A}{a}=\\dfrac{\\sin B}{b}=c$',
              '$a\\sin A=b\\sin B$',
            ],
            answer: 0,
            explain: '正弦定理：边与其对角正弦之比相等，且等于 $2R$。',
          },
          {
            id: 'u14-l2-q2',
            type: 'input',
            prompt: '直角三角形中 $30^\\circ$ 角的对边为 $4$，求斜边长（即 $90^\\circ$ 角对边）。',
            accept: ['8', '8.0'],
            placeholder: '例如 8',
            explain: '$\\sin30^\\circ=\\dfrac{4}{c}$，$c=\\dfrac{4}{1/2}=8$。',
          },
          {
            id: 'u14-l2-q3',
            type: 'input',
            prompt: '$\\triangle ABC$ 中 $A=45^\\circ,B=75^\\circ$，求 $C$（度）。',
            accept: ['60', '60°', '60度'],
            placeholder: '例如 60',
            explain: '$C=180^\\circ-45^\\circ-75^\\circ=60^\\circ$。',
          },
          {
            id: 'u14-l2-q4',
            type: 'choice',
            prompt: '$\\triangle ABC$ 中 $C=120^\\circ$，$a=8$，$c=2\\sqrt{37}$，用正弦定理求 $\\sin A$。',
            options: [
              '$\\dfrac{2\\sqrt3}{\\sqrt{37}}$',
              '$\\dfrac{\\sqrt3}{2}$',
              '$\\dfrac{4}{\\sqrt{37}}$',
              '$\\dfrac{8}{37}$',
            ],
            answer: 0,
            explain: '$\\sin A=\\dfrac{a\\sin C}{c}=\\dfrac{8\\cdot\\frac{\\sqrt3}{2}}{2\\sqrt{37}}=\\dfrac{4\\sqrt3}{2\\sqrt{37}}=\\dfrac{2\\sqrt3}{\\sqrt{37}}$。',
          },
          {
            id: 'u14-l2-q5',
            type: 'judge',
            prompt: '在正弦定理中，$\\dfrac{a}{\\sin A}$ 等于外接圆直径 $2R$。',
            answer: true,
            explain: '$\\dfrac{a}{\\sin A}=2R$，$R$ 为外接圆半径，正确。',
          },
          {
            id: 'u14-l2-q6',
            type: 'choice',
            prompt: '已知两角一边（AAS），求其余两边，最适合用？',
            options: ['余弦定理', '正弦定理', '勾股定理', '海伦公式'],
            answer: 1,
            explain: '补全第三角后，用正弦定理同一个公共比值一次性求出各边。',
          },
        ],
      },
      {
        id: 'u14-l3',
        title: 'SSA 双解与解三角形',
        subtitle: '同一正弦值可能对应两个角',
        questions: [
          {
            id: 'u14-l3-q1',
            type: 'choice',
            prompt: '$\\triangle ABC$ 中 $a=\\sqrt2,b=2,A=30^\\circ$，用正弦定理求得 $\\sin B$ 为？',
            options: ['$\\dfrac{\\sqrt2}{2}$', '$\\dfrac12$', '$\\dfrac{\\sqrt3}{2}$', '$1$'],
            answer: 0,
            explain: '$\\sin B=\\dfrac{b\\sin A}{a}=\\dfrac{2\\cdot\\frac12}{\\sqrt2}=\\dfrac{1}{\\sqrt2}=\\dfrac{\\sqrt2}{2}$。',
          },
          {
            id: 'u14-l3-q2',
            type: 'choice',
            prompt: '上题中 $\\sin B=\\dfrac{\\sqrt2}{2}$，$B$ 的可能取值为？',
            options: ['仅 $45^\\circ$', '仅 $135^\\circ$', '$45^\\circ$ 或 $135^\\circ$', '$30^\\circ$ 或 $60^\\circ$'],
            answer: 2,
            explain: '正弦在 $(0,\\pi)$ 对称，$B=45^\\circ$ 或 $135^\\circ$，且两者都满足角和 $<180^\\circ$，故双解。',
          },
          {
            id: 'u14-l3-q3',
            type: 'judge',
            prompt: 'SSA（两边及其中一边对角）情况一定只有一个三角形。',
            answer: false,
            explain: 'SSA 可能出现双解，因为同一正弦值对应两个角，需逐一验证。',
          },
          {
            id: 'u14-l3-q4',
            type: 'input',
            prompt: '$\\triangle ABC$ 中 $A=30^\\circ,B=45^\\circ$，求 $C$（度）。',
            accept: ['105', '105°', '105度'],
            placeholder: '例如 105',
            explain: '$C=180^\\circ-30^\\circ-45^\\circ=105^\\circ$，对应 $B=45^\\circ$ 的解。',
          },
          {
            id: 'u14-l3-q5',
            type: 'choice',
            prompt: 'SSA 双解出现的根本原因是？',
            options: [
              '余弦在 $(0,\\pi)$ 上单调',
              '正弦函数在 $(0,\\pi)$ 上关于 $\\dfrac\\pi2$ 对称',
              '三角形内角和不为 $180^\\circ$',
              '正弦定理本身错误',
            ],
            answer: 1,
            explain: '$\\sin$ 在 $(0,\\pi)$ 关于 $\\dfrac\\pi2$ 对称，同一正弦值对应两个角。',
          },
          {
            id: 'u14-l3-q6',
            type: 'judge',
            prompt: '当三角形已有一个钝角时，其余两角都是锐角，可直接排除正弦定理的钝角解。',
            answer: true,
            explain: '三角形最多一个钝角，故已知钝角时其余角必为锐角，正确。',
          },
        ],
      },
    ],
  },

  // ============================== 单元 15 ==============================
  {
    id: 'u15',
    title: '面积·几何恒等式',
    color: '#e84393',
    icon: '📏',
    blurb: '$S=\\tfrac12 ab\\sin C$、海伦公式与内外接圆——面积是几何的中心节点',
    lessons: [
      {
        id: 'u15-l1',
        title: '两边夹角面积公式',
        subtitle: '$S=\\dfrac12 ab\\sin C$',
        questions: [
          {
            id: 'u15-l1-q1',
            type: 'choice',
            prompt: '三角形两边为 $a,b$，夹角为 $C$，面积公式为？',
            options: ['$S=ab\\sin C$', '$S=\\dfrac12 ab\\sin C$', '$S=\\dfrac12 ab\\cos C$', '$S=\\dfrac12 ab$'],
            answer: 1,
            explain: '$S=\\dfrac12 ab\\sin C$，注意前面的 $\\dfrac12$ 不能漏。',
          },
          {
            id: 'u15-l1-q2',
            type: 'input',
            prompt: '$\\triangle ABC$ 中 $a=10,b=7,C=30^\\circ$，求面积 $S$。',
            accept: ['17.5', '35/2', '17.50'],
            placeholder: '例如 17.5',
            explain: '$S=\\dfrac12\\cdot10\\cdot7\\cdot\\sin30^\\circ=35\\cdot\\dfrac12=17.5$。',
          },
          {
            id: 'u15-l1-q3',
            type: 'input',
            prompt: '直角三角形两直角边为 $6,8$，求面积。',
            accept: ['24', '24.0'],
            placeholder: '例如 24',
            explain: '夹角 $90^\\circ$，$\\sin90^\\circ=1$，$S=\\dfrac12\\cdot6\\cdot8\\cdot1=24$。',
          },
          {
            id: 'u15-l1-q4',
            type: 'choice',
            prompt: '两边为 $6,8$，夹角 $45^\\circ$，面积为？',
            options: ['$24$', '$12\\sqrt2$', '$24\\sqrt2$', '$12$'],
            answer: 1,
            explain: '$S=\\dfrac12\\cdot6\\cdot8\\cdot\\sin45^\\circ=24\\cdot\\dfrac{\\sqrt2}{2}=12\\sqrt2$。',
          },
          {
            id: 'u15-l1-q5',
            type: 'judge',
            prompt: '面积公式 $S=\\dfrac12 ab\\sin C$ 中的 $C$ 必须是 $a,b$ 两边所夹的角。',
            answer: true,
            explain: '夹角放错位置是常见错误，$C$ 必须是 $a,b$ 的夹角。',
          },
          {
            id: 'u15-l1-q6',
            type: 'input',
            prompt: '等边三角形边长为 $4$，用 $S=\\dfrac12 ab\\sin C$ 求面积。',
            accept: ['4√3', '4\\sqrt3', '4sqrt3', '4√3', '6.93'],
            placeholder: '例如 4√3',
            explain: '$S=\\dfrac12\\cdot4\\cdot4\\cdot\\sin60^\\circ=8\\cdot\\dfrac{\\sqrt3}{2}=4\\sqrt3$。',
          },
        ],
      },
      {
        id: 'u15-l2',
        title: '海伦公式',
        subtitle: '$S=\\sqrt{p(p-a)(p-b)(p-c)}$',
        questions: [
          {
            id: 'u15-l2-q1',
            type: 'input',
            prompt: '三角形三边为 $5,6,7$，求半周长 $p$。',
            accept: ['9', '9.0'],
            placeholder: '例如 9',
            explain: '$p=\\dfrac{5+6+7}{2}=9$。',
          },
          {
            id: 'u15-l2-q2',
            type: 'choice',
            prompt: '三边为 $5,6,7$（$p=9$），用海伦公式求面积。',
            options: ['$6\\sqrt6$', '$\\sqrt{216}$ 与 $6\\sqrt6$ 都对', '$36$', '$18$'],
            answer: 1,
            explain: '$S=\\sqrt{9\\cdot4\\cdot3\\cdot2}=\\sqrt{216}=6\\sqrt6$，两种写法等价。',
          },
          {
            id: 'u15-l2-q3',
            type: 'judge',
            prompt: '只知道三角形三边长时，海伦公式比 $\\dfrac12 ab\\sin C$ 更直接。',
            answer: true,
            explain: '三边已知用海伦公式无需先求角，最直接。',
          },
          {
            id: 'u15-l2-q4',
            type: 'choice',
            prompt: '三边 $5,6,7$ 面积 $6\\sqrt6$，最长边 $7$ 上的高 $h$ 为？',
            options: ['$\\dfrac{12\\sqrt6}{7}$', '$\\dfrac{6\\sqrt6}{7}$', '$\\dfrac{7}{12\\sqrt6}$', '$6\\sqrt6$'],
            answer: 0,
            explain: '$S=\\dfrac12\\cdot7\\cdot h$，$h=\\dfrac{2S}{7}=\\dfrac{12\\sqrt6}{7}$。',
          },
          {
            id: 'u15-l2-q5',
            type: 'input',
            prompt: '海伦公式中半周长 $p$ 等于周长的几分之几？（填分数或小数）',
            accept: ['1/2', '0.5', '.5', '二分之一'],
            placeholder: '例如 1/2',
            explain: '$p=\\dfrac{a+b+c}{2}$，是周长的一半。',
          },
          {
            id: 'u15-l2-q6',
            type: 'match',
            prompt: '把已知条件与首选面积方法对应起来。',
            left: ['已知两边夹角', '已知三边', '已知底与高'],
            right: ['$\\dfrac12 ab\\sin C$', '海伦公式', '$\\dfrac12\\times$底$\\times$高'],
            explain: '两边夹角用 $\\frac12 ab\\sin C$，三边用海伦，底高用 $\\frac12$ 底乘高。',
          },
        ],
      },
      {
        id: 'u15-l3',
        title: '面积与内外接圆',
        subtitle: '$S=pr$、$S=\\dfrac{abc}{4R}$ 与几何恒等式',
        questions: [
          {
            id: 'u15-l3-q1',
            type: 'choice',
            prompt: '内切圆半径 $r$、半周长 $p$ 时，三角形面积为？',
            options: ['$S=pr$', '$S=\\dfrac{p}{r}$', '$S=2pr$', '$S=p+r$'],
            answer: 0,
            explain: '$S=pr$，面积等于半周长乘内切圆半径。',
          },
          {
            id: 'u15-l3-q2',
            type: 'input',
            prompt: '三边 $5,6,7$，面积 $S=6\\sqrt6$，半周长 $p=9$，求内切圆半径 $r$。',
            accept: ['2√6/3', '\\frac{2\\sqrt6}{3}', '2sqrt6/3', '1.63'],
            placeholder: '例如 2√6/3',
            explain: '$r=\\dfrac{S}{p}=\\dfrac{6\\sqrt6}{9}=\\dfrac{2\\sqrt6}{3}\\approx1.63$。',
          },
          {
            id: 'u15-l3-q3',
            type: 'choice',
            prompt: '用三边 $a,b,c$ 与面积 $S$ 表示外接圆半径 $R$ 的公式是？',
            options: ['$R=\\dfrac{abc}{4S}$', '$R=\\dfrac{4S}{abc}$', '$R=\\dfrac{abc}{S}$', '$R=\\dfrac{S}{abc}$'],
            answer: 0,
            explain: '$S=\\dfrac{abc}{4R}$，故 $R=\\dfrac{abc}{4S}$。',
          },
          {
            id: 'u15-l3-q4',
            type: 'judge',
            prompt: '由三种面积形式 $\\frac12bc\\sin A=\\frac12ca\\sin B=\\frac12ab\\sin C$ 可以推出正弦定理。',
            answer: true,
            explain: '三式相等，两两相除消去公共因子即得 $\\dfrac{a}{\\sin A}=\\dfrac{b}{\\sin B}=\\dfrac{c}{\\sin C}$。',
          },
          {
            id: 'u15-l3-q5',
            type: 'choice',
            prompt: '$\\triangle ABC$ 中 $A=60^\\circ$，对边 $a=\\sqrt3$，由 $b^2+c^2-bc=3$ 与 $bc\\le3$，面积最大值为？',
            options: ['$\\dfrac{3\\sqrt3}{4}$', '$\\dfrac{\\sqrt3}{4}$', '$\\sqrt3$', '$3\\sqrt3$'],
            answer: 0,
            explain: '$S=\\dfrac{\\sqrt3}{4}bc\\le\\dfrac{\\sqrt3}{4}\\cdot3=\\dfrac{3\\sqrt3}{4}$，$b=c$（等边）时取等。',
          },
          {
            id: 'u15-l3-q6',
            type: 'match',
            prompt: '把几何量与对应的面积关系对应起来。',
            left: ['内切圆半径 $r$', '外接圆半径 $R$', '两边夹角'],
            right: ['$S=pr$', '$S=\\dfrac{abc}{4R}$', '$S=\\dfrac12 ab\\sin C$'],
            explain: '面积串联内切圆、外接圆与边角，是几何的中心节点。',
          },
        ],
      },
    ],
  },
]
