import type { Unit } from '../../types'

export const PART3_UNITS: Unit[] = [
  {
    id: 'u7',
    title: '三角函数图象',
    color: '#1cb0f6',
    icon: '📈',
    blurb: 'sin、cos、tan 的图象：周期、值域、零点、单调区间与渐近线，统统从图里读出来。',
    lessons: [
      {
        id: 'u7-l1',
        title: '正弦与余弦图象',
        subtitle: '波形、周期 2π、值域 [-1,1]',
        questions: [
          {
            id: 'u7-l1-q1',
            type: 'choice',
            prompt: '$y=\\sin x$ 的最小正周期是？',
            options: ['$\\pi$', '$2\\pi$', '$\\dfrac{\\pi}{2}$', '$4\\pi$'],
            answer: 1,
            explain: '正弦图象每隔 $2\\pi$ 重复一次，最小正周期为 $2\\pi$。',
          },
          {
            id: 'u7-l1-q2',
            type: 'choice',
            prompt: '$y=\\sin x$ 与 $y=\\cos x$ 共同的值域是？',
            options: ['$[0,1]$', '$[-1,1]$', '$(-\\infty,+\\infty)$', '$[-2,2]$'],
            answer: 1,
            explain: '正弦、余弦都是单位圆上的投影，取值在 $[-1,1]$ 之间。',
          },
          {
            id: 'u7-l1-q3',
            type: 'judge',
            prompt: '判断：$\\cos x$ 的图象可以看成 $\\sin x$ 的图象向左平移 $\\dfrac{\\pi}{2}$。',
            answer: true,
            explain: '因为 $\\cos x=\\sin\\left(x+\\dfrac{\\pi}{2}\\right)$，即正弦图象左移 $\\dfrac{\\pi}{2}$。',
          },
          {
            id: 'u7-l1-q4',
            type: 'input',
            prompt: '$y=\\sin x$ 在区间 $[0,2\\pi]$ 上的最大值在 $x=$ ？处取得（用 $\\pi$ 表示）',
            accept: ['π/2', '\\pi/2', 'pi/2', '\\dfrac{\\pi}{2}', '\\frac{\\pi}{2}'],
            placeholder: '例如 π/2',
            explain: '正弦在 $x=\\dfrac{\\pi}{2}$ 处到达峰值 $1$。',
          },
          {
            id: 'u7-l1-q5',
            type: 'judge',
            prompt: '判断：$y=\\sin x$ 是奇函数，$y=\\cos x$ 是偶函数。',
            answer: true,
            explain: '$\\sin(-x)=-\\sin x$（奇），$\\cos(-x)=\\cos x$（偶），从图象的对称性也能看出。',
          },
          {
            id: 'u7-l1-q6',
            type: 'choice',
            prompt: '$y=\\sin x$ 在 $[0,2\\pi]$ 上与 $x$ 轴有几个交点（零点）？',
            options: ['$1$ 个', '$2$ 个', '$3$ 个', '$4$ 个'],
            answer: 2,
            explain: '零点为 $x=0,\\ \\pi,\\ 2\\pi$，闭区间端点都算，共 $3$ 个。',
          },
        ],
      },
      {
        id: 'u7-l2',
        title: '单调区间与对称',
        subtitle: '从图象读单调性、峰谷与对称轴',
        questions: [
          {
            id: 'u7-l2-q1',
            type: 'choice',
            prompt: '在一个周期内，$y=\\sin x$ 在下列哪个区间上单调递增？',
            options: [
              '$\\left[-\\dfrac{\\pi}{2},\\dfrac{\\pi}{2}\\right]$',
              '$\\left[\\dfrac{\\pi}{2},\\dfrac{3\\pi}{2}\\right]$',
              '$[0,\\pi]$',
              '$[\\pi,2\\pi]$',
            ],
            answer: 0,
            explain: '正弦在 $\\left[-\\dfrac{\\pi}{2},\\dfrac{\\pi}{2}\\right]$ 上从谷到峰单调递增。',
          },
          {
            id: 'u7-l2-q2',
            type: 'judge',
            prompt: '判断：$y=\\cos x$ 在 $[0,\\pi]$ 上单调递减。',
            answer: true,
            explain: '余弦从 $(0,1)$ 下降到 $(\\pi,-1)$，在 $[0,\\pi]$ 上整体递减。',
          },
          {
            id: 'u7-l2-q3',
            type: 'input',
            prompt: '$y=\\cos x$ 在 $[0,2\\pi]$ 上取得最小值 $-1$ 时，$x=$ ？（用 $\\pi$ 表示）',
            accept: ['π', 'pi', '\\pi'],
            placeholder: '例如 π',
            explain: '余弦在 $x=\\pi$ 处达到最小值 $-1$。',
          },
          {
            id: 'u7-l2-q4',
            type: 'choice',
            prompt: '一条周期曲线：过原点、最大值 $1$、最小值 $-1$、周期 $2\\pi$。它最可能是？',
            options: ['$y=\\cos x$', '$y=\\sin x$', '$y=\\tan x$', '$y=2\\sin x$'],
            answer: 1,
            explain: '过原点、有界于 $[-1,1]$、周期 $2\\pi$，正是 $y=\\sin x$。',
          },
          {
            id: 'u7-l2-q5',
            type: 'match',
            prompt: '把基本图象与其核心特征配对：',
            left: ['$\\sin x$', '$\\cos x$', '$\\tan x$'],
            right: ['过原点、周期 $2\\pi$、有界', '从 $(0,1)$ 出发、周期 $2\\pi$、有界', '有竖直渐近线、周期 $\\pi$、无界'],
            explain: '正弦过原点，余弦从最大值出发，正切有渐近线且周期为 $\\pi$。',
          },
          {
            id: 'u7-l2-q6',
            type: 'judge',
            prompt: '判断：$y=\\cos x$ 的图象关于 $y$ 轴对称。',
            answer: true,
            explain: '余弦是偶函数，图象关于 $y$ 轴对称。',
          },
        ],
      },
      {
        id: 'u7-l3',
        title: '正切图象与渐近线',
        subtitle: '周期 π、竖直渐近线、单调分支',
        questions: [
          {
            id: 'u7-l3-q1',
            type: 'choice',
            prompt: '$y=\\tan x$ 的最小正周期是？',
            options: ['$2\\pi$', '$\\pi$', '$\\dfrac{\\pi}{2}$', '$4\\pi$'],
            answer: 1,
            explain: '因为 $\\tan(x+\\pi)=\\tan x$（分子分母同时变号），周期为 $\\pi$。',
          },
          {
            id: 'u7-l3-q2',
            type: 'judge',
            prompt: '判断：$y=\\tan x$ 是有界函数。',
            answer: false,
            explain: '正切在渐近线附近趋于 $\\pm\\infty$，值域是全体实数，无界。',
          },
          {
            id: 'u7-l3-q3',
            type: 'choice',
            prompt: '$y=\\tan x$ 的竖直渐近线出现在哪里？',
            options: ['$x=k\\pi$', '$x=\\dfrac{\\pi}{2}+k\\pi$', '$x=2k\\pi$', '$x=\\dfrac{\\pi}{4}+k\\pi$'],
            answer: 1,
            explain: '当 $\\cos x=0$，即 $x=\\dfrac{\\pi}{2}+k\\pi$ 时正切无定义，那里是渐近线。',
          },
          {
            id: 'u7-l3-q4',
            type: 'judge',
            prompt: '判断：在区间 $\\left(-\\dfrac{\\pi}{2},\\dfrac{\\pi}{2}\\right)$ 上，$y=\\tan x$ 单调递增。',
            answer: true,
            explain: '在每个相邻渐近线之间，正切都从 $-\\infty$ 单调递增到 $+\\infty$。',
          },
          {
            id: 'u7-l3-q5',
            type: 'input',
            prompt: '正切函数无定义的原因是分母 $\\cos x=0$。$y=\\tan x$ 离原点最近的正渐近线是 $x=$ ？（用 $\\pi$ 表示）',
            accept: ['π/2', '\\pi/2', 'pi/2', '\\dfrac{\\pi}{2}', '\\frac{\\pi}{2}'],
            placeholder: '例如 π/2',
            explain: '$x=\\dfrac{\\pi}{2}$ 处 $\\cos x=0$，是离原点最近的正渐近线。',
          },
          {
            id: 'u7-l3-q6',
            type: 'choice',
            prompt: '为什么正切图象不是一条平滑连续的波，而是被切成一族分支？',
            options: [
              '因为它是奇函数',
              '因为在 $\\cos x=0$ 处无定义并发散',
              '因为它的周期是 $2\\pi$',
              '因为它有界',
            ],
            answer: 1,
            explain: '$\\tan x=\\dfrac{\\sin x}{\\cos x}$，分母为 $0$ 处无定义且发散，图象被渐近线切断。',
          },
        ],
      },
    ],
  },
  {
    id: 'u8',
    title: '平移·伸缩·相位',
    color: '#ce82ff',
    icon: '🎚️',
    blurb: '$y=A\\sin(\\omega x+\\varphi)+k$：振幅 A、周期 $\\dfrac{2\\pi}{\\omega}$、相位 φ、中线 k，并学会由图求式。',
    lessons: [
      {
        id: 'u8-l1',
        title: '振幅与周期',
        subtitle: '从 A 和 ω 读竖直拉伸与水平压缩',
        questions: [
          {
            id: 'u8-l1-q1',
            type: 'input',
            prompt: '函数 $y=3\\sin(2x+\\dfrac{\\pi}{3})$ 的最小正周期是？（用 $\\pi$ 表示）',
            accept: ['π', 'pi', '\\pi'],
            placeholder: '例如 π',
            explain: '$T=\\dfrac{2\\pi}{\\omega}=\\dfrac{2\\pi}{2}=\\pi$。',
          },
          {
            id: 'u8-l1-q2',
            type: 'choice',
            prompt: '$y=A\\sin(\\omega x+\\varphi)+b$ 中，决定振幅的参数是？',
            options: ['$\\omega$', '$A$', '$\\varphi$', '$b$'],
            answer: 1,
            explain: '$A$（的绝对值）就是振幅，决定上下摆动的幅度。',
          },
          {
            id: 'u8-l1-q3',
            type: 'judge',
            prompt: '判断：$|\\omega|$ 越大，图象在水平方向被压缩得越厉害。',
            answer: true,
            explain: '$T=\\dfrac{2\\pi}{|\\omega|}$，$|\\omega|$ 越大周期越小，单位横坐标内塞进更多周期。',
          },
          {
            id: 'u8-l1-q4',
            type: 'input',
            prompt: '若某正弦型函数最大值为 $M$、最小值为 $m$，其振幅 $A=$ ？（用 $M,m$ 表示）',
            accept: ['(M-m)/2', '(M - m)/2', '\\dfrac{M-m}{2}', '\\frac{M-m}{2}', '(M-m)÷2'],
            placeholder: '用 M、m 表示',
            explain: '振幅是中线到峰值的距离，$A=\\dfrac{M-m}{2}$。',
          },
          {
            id: 'u8-l1-q5',
            type: 'choice',
            prompt: '$y=4\\sin\\left(\\dfrac{1}{2}x\\right)-1$ 的周期是？',
            options: ['$2\\pi$', '$4\\pi$', '$\\pi$', '$\\dfrac{\\pi}{2}$'],
            answer: 1,
            explain: '$T=\\dfrac{2\\pi}{|\\omega|}=\\dfrac{2\\pi}{1/2}=4\\pi$。',
          },
          {
            id: 'u8-l1-q6',
            type: 'judge',
            prompt: '判断：$y=2\\sin x$ 与 $y=\\sin x$ 的周期相同，但振幅不同。',
            answer: true,
            explain: '系数 $2$ 只竖直拉伸（振幅 $1\\to2$），不改变周期，二者都是 $2\\pi$。',
          },
        ],
      },
      {
        id: 'u8-l2',
        title: '相位与平移',
        subtitle: '相位 φ、平移量 -φ/ω、中线 k',
        questions: [
          {
            id: 'u8-l2-q1',
            type: 'judge',
            prompt: '判断：$y=\\sin(2x-\\pi)$ 是把 $y=\\sin 2x$ 向右平移 $\\pi$ 得到的。',
            answer: false,
            explain: '要先提 $\\omega$：$2x-\\pi=2\\left(x-\\dfrac{\\pi}{2}\\right)$，真实平移量是 $\\dfrac{\\pi}{2}$ 而非 $\\pi$。',
          },
          {
            id: 'u8-l2-q2',
            type: 'choice',
            prompt: '对 $y=A\\sin(\\omega x+\\varphi)$，真正的水平平移量是？',
            options: ['$\\varphi$', '$-\\dfrac{\\varphi}{\\omega}$', '$\\omega\\varphi$', '$-\\varphi$'],
            answer: 1,
            explain: '改写为 $A\\sin\\left[\\omega\\left(x+\\dfrac{\\varphi}{\\omega}\\right)\\right]$，平移量为 $-\\dfrac{\\varphi}{\\omega}$，只有 $\\omega=1$ 时才等于 $\\varphi$。',
          },
          {
            id: 'u8-l2-q3',
            type: 'input',
            prompt: '$y=3\\sin(2x-\\pi)+1$ 的中线是 $y=$ ？',
            accept: ['1', 'y=1'],
            placeholder: '例如 1',
            explain: '竖直平移 $b=1$ 决定中线，即 $y=1$。',
          },
          {
            id: 'u8-l2-q4',
            type: 'choice',
            prompt: '$y=3\\sin(2x-\\pi)+1$ 的最大值是？',
            options: ['$3$', '$4$', '$2$', '$-2$'],
            answer: 1,
            explain: '最大值 = 中线 + 振幅 = $1+3=4$。',
          },
          {
            id: 'u8-l2-q5',
            type: 'judge',
            prompt: '判断：相位参数 $\\varphi$ 与水平平移量在 $\\omega=1$ 时才相等。',
            answer: true,
            explain: '平移量为 $-\\dfrac{\\varphi}{\\omega}$，仅当 $\\omega=1$ 时其绝对值与 $\\varphi$ 一致。',
          },
          {
            id: 'u8-l2-q6',
            type: 'match',
            prompt: '把 $y=A\\sin(\\omega x+\\varphi)+b$ 的参数与作用配对：',
            left: ['$A$', '$\\omega$', '$\\varphi$', '$b$'],
            right: ['振幅', '决定周期', '与 ω 一起决定相位平移', '决定中线'],
            explain: '$A$ 振幅、$\\omega$ 决定周期、$\\varphi$ 决定相位、$b$ 决定中线。',
          },
        ],
      },
      {
        id: 'u8-l3',
        title: '由图求式',
        subtitle: 'A 看高差、ω 看周期、φ 用特殊点',
        questions: [
          {
            id: 'u8-l3-q1',
            type: 'choice',
            prompt: '某 $y=A\\sin(\\omega x+\\varphi)$ 相邻最高点 $\\left(\\dfrac{\\pi}{6},3\\right)$、相邻最低点 $\\left(\\dfrac{2\\pi}{3},-3\\right)$，则周期 $T=$ ？',
            options: ['$\\dfrac{\\pi}{2}$', '$\\pi$', '$2\\pi$', '$\\dfrac{\\pi}{3}$'],
            answer: 1,
            explain: '相邻最高点与最低点相差半周期：$\\dfrac{T}{2}=\\dfrac{2\\pi}{3}-\\dfrac{\\pi}{6}=\\dfrac{\\pi}{2}$，故 $T=\\pi$。',
          },
          {
            id: 'u8-l3-q2',
            type: 'input',
            prompt: '承上题，由 $T=\\pi$ 得角频率 $\\omega=$ ？',
            accept: ['2'],
            placeholder: '例如 2',
            explain: '$\\omega=\\dfrac{2\\pi}{T}=\\dfrac{2\\pi}{\\pi}=2$。',
          },
          {
            id: 'u8-l3-q3',
            type: 'choice',
            prompt: '承上题（$A=3,\\omega=2$，$|\\varphi|<\\dfrac{\\pi}{2}$），由最高点 $\\left(\\dfrac{\\pi}{6},3\\right)$ 解得 $\\varphi=$ ？',
            options: ['$\\dfrac{\\pi}{3}$', '$\\dfrac{\\pi}{6}$', '$-\\dfrac{\\pi}{6}$', '$\\dfrac{\\pi}{2}$'],
            answer: 1,
            explain: '峰值处 $2\\cdot\\dfrac{\\pi}{6}+\\varphi=\\dfrac{\\pi}{2}$，得 $\\varphi=\\dfrac{\\pi}{6}$，满足 $|\\varphi|<\\dfrac{\\pi}{2}$。',
          },
          {
            id: 'u8-l3-q4',
            type: 'judge',
            prompt: '判断：由图求式时，相邻最高点与最低点的水平距离等于一个完整周期。',
            answer: false,
            explain: '相邻最高点与最低点相差的是半个周期，相邻两个最高点才相差一个周期。',
          },
          {
            id: 'u8-l3-q5',
            type: 'input',
            prompt: '把 $y=\\sin x$ 先右移 $\\dfrac{\\pi}{6}$，再把横坐标缩短为原来的 $\\dfrac{1}{2}$，所得解析式为 $y=\\sin(2x-\\dfrac{\\pi}{?})$，填 $?$。',
            accept: ['3'],
            placeholder: '填一个整数',
            explain: '右移得 $\\sin\\left(x-\\dfrac{\\pi}{6}\\right)$，再把 $x$ 换成 $2x$ 得 $\\sin\\left(2x-\\dfrac{\\pi}{3}\\right)$。',
          },
          {
            id: 'u8-l3-q6',
            type: 'choice',
            prompt: '$y=A\\cos(\\omega x+\\varphi)+b$ 中，若 $x=0$ 恰好取最大值，最方便的相位取值是？',
            options: ['$\\varphi=\\dfrac{\\pi}{2}$', '$\\varphi=0$', '$\\varphi=\\pi$', '$\\varphi=-\\dfrac{\\pi}{2}$'],
            answer: 1,
            explain: '余弦在自变量为 $0$ 时取最大值，故取 $\\varphi=0$ 最省事。',
          },
        ],
      },
    ],
  },
  {
    id: 'u9',
    title: '周期建模',
    color: '#58cc02',
    icon: '🌊',
    blurb: '潮汐、昼长、简谐振动：用中线、振幅、周期、相位把现实周期现象写成三角模型，并求关键时刻。',
    lessons: [
      {
        id: 'u9-l1',
        title: '中线与振幅',
        subtitle: '从最大最小值确定 b 和 A',
        questions: [
          {
            id: 'u9-l1-q1',
            type: 'input',
            prompt: '某地气温最高 $18^\\circ\\mathrm{C}$、最低 $6^\\circ\\mathrm{C}$，其模型中线（平均温度）是多少 $^\\circ\\mathrm{C}$？',
            accept: ['12', '12°C', '12摄氏度'],
            placeholder: '例如 12',
            explain: '中线 $b=\\dfrac{18+6}{2}=12$。',
          },
          {
            id: 'u9-l1-q2',
            type: 'input',
            prompt: '承上题，该气温模型的振幅是多少 $^\\circ\\mathrm{C}$？',
            accept: ['6', '6°C', '6摄氏度'],
            placeholder: '例如 6',
            explain: '振幅 $A=\\dfrac{18-6}{2}=6$。',
          },
          {
            id: 'u9-l1-q3',
            type: 'judge',
            prompt: '判断：中线与振幅只由最大值、最小值决定，与起始时刻无关。',
            answer: true,
            explain: '中线 $\\dfrac{M+m}{2}$、振幅 $\\dfrac{M-m}{2}$ 都只用到最值，与相位无关。',
          },
          {
            id: 'u9-l1-q4',
            type: 'choice',
            prompt: '潮汐最高 $8$ 米、最低 $2$ 米，则振幅 $A$ 与中线 $b$ 分别是？',
            options: ['$A=3,\\ b=5$', '$A=5,\\ b=3$', '$A=6,\\ b=4$', '$A=3,\\ b=4$'],
            answer: 0,
            explain: '$A=\\dfrac{8-2}{2}=3$，$b=\\dfrac{8+2}{2}=5$。',
          },
          {
            id: 'u9-l1-q5',
            type: 'choice',
            prompt: '什么样的现象最适合用单个三角函数建模？',
            options: [
              '一次性、不重复的事件',
              '有重复性、平滑变化、明显周期的现象',
              '完全随机的噪声',
              '单调上升的趋势',
            ],
            answer: 1,
            explain: '重复性、平滑、有明显周期三者齐备时，三角函数是第一选择。',
          },
          {
            id: 'u9-l1-q6',
            type: 'judge',
            prompt: '判断：温度同时受昼夜与季节两个周期影响时，单个三角函数只能抓住主周期。',
            answer: true,
            explain: '多周期叠加需要多个正弦项（傅里叶思想），单个三角函数只抓主结构。',
          },
        ],
      },
      {
        id: 'u9-l2',
        title: '潮汐与昼长模型',
        subtitle: '由周期定 ω、由起始状态选 sin/cos',
        questions: [
          {
            id: 'u9-l2-q1',
            type: 'input',
            prompt: '潮汐周期为 $12$ 小时，则角频率 $\\omega=\\dfrac{\\pi}{?}$，填 $?$。',
            accept: ['6'],
            placeholder: '填一个整数',
            explain: '$\\omega=\\dfrac{2\\pi}{T}=\\dfrac{2\\pi}{12}=\\dfrac{\\pi}{6}$。',
          },
          {
            id: 'u9-l2-q2',
            type: 'choice',
            prompt: '潮汐最高 $8$、最低 $2$、周期 $12$，且 $t=0$ 恰为最高水位。最省事的模型是？',
            options: [
              '$h(t)=3\\sin\\dfrac{\\pi}{6}t+5$',
              '$h(t)=3\\cos\\dfrac{\\pi}{6}t+5$',
              '$h(t)=5\\cos\\dfrac{\\pi}{6}t+3$',
              '$h(t)=3\\cos\\dfrac{\\pi}{12}t+5$',
            ],
            answer: 1,
            explain: '$t=0$ 取最大值时用余弦最省事：$A=3,b=5,\\omega=\\dfrac{\\pi}{6}$，得 $3\\cos\\dfrac{\\pi}{6}t+5$。',
          },
          {
            id: 'u9-l2-q3',
            type: 'judge',
            prompt: '判断：若 $t=0$ 时物理量从中线向上运动，用正弦模型（$\\varphi=0$）最自然。',
            answer: true,
            explain: '$\\sin$ 在自变量为 $0$ 时过中线且正在上升，正好对应这种起始状态。',
          },
          {
            id: 'u9-l2-q4',
            type: 'choice',
            prompt: '昼长在一年（$365$ 天）中变化，夏至（第 $172$ 天）最长 $14.5$ 时、冬至最短 $9.5$ 时。模型 $L(d)=2.5\\cos\\left[\\dfrac{2\\pi}{365}(d-172)\\right]+12$ 中的 $12$ 表示？',
            options: ['振幅', '中线（平均昼长）', '周期', '相位'],
            answer: 1,
            explain: '$b=\\dfrac{14.5+9.5}{2}=12$ 是中线，即平均昼长。',
          },
          {
            id: 'u9-l2-q5',
            type: 'input',
            prompt: '简谐振动 $y=4\\sin\\left(2\\pi t+\\dfrac{\\pi}{6}\\right)$，其周期 $T=$ ？秒',
            accept: ['1', '1秒', '1s'],
            placeholder: '例如 1',
            explain: '$T=\\dfrac{2\\pi}{\\omega}=\\dfrac{2\\pi}{2\\pi}=1$ 秒。',
          },
          {
            id: 'u9-l2-q6',
            type: 'judge',
            prompt: '判断：模型 $L(d)=2.5\\cos\\left[\\dfrac{2\\pi}{365}(d-172)\\right]+12$ 在 $d=172$ 时取最大值。',
            answer: true,
            explain: '$d=172$ 时括号内为 $0$，$\\cos 0=1$，$L=2.5+12=14.5$，正是最大值。',
          },
        ],
      },
      {
        id: 'u9-l3',
        title: '求时刻与时长',
        subtitle: '简谐、摩天轮、冲浪时长的综合应用',
        questions: [
          {
            id: 'u9-l3-q1',
            type: 'input',
            prompt: '简谐振动 $y=4\\sin\\left(2\\pi t+\\dfrac{\\pi}{6}\\right)$，$t=0$ 时位移 $y=$ ？厘米',
            accept: ['2', '2cm', '2厘米'],
            placeholder: '例如 2',
            explain: '$y=4\\sin\\dfrac{\\pi}{6}=4\\times\\dfrac{1}{2}=2$ 厘米。',
          },
          {
            id: 'u9-l3-q2',
            type: 'choice',
            prompt: '上题中位移首次到达最大值 $y=4$ 的时刻是？',
            options: ['$t=\\dfrac{1}{6}$ 秒', '$t=\\dfrac{1}{3}$ 秒', '$t=\\dfrac{1}{2}$ 秒', '$t=1$ 秒'],
            answer: 0,
            explain: '令 $2\\pi t+\\dfrac{\\pi}{6}=\\dfrac{\\pi}{2}$，得 $t=\\dfrac{1}{6}$ 秒（取首次）。',
          },
          {
            id: 'u9-l3-q3',
            type: 'choice',
            prompt: '摩天轮半径 $50$ 米、最低点离地 $2$ 米，从最低点登舱。高度模型应为？',
            options: [
              '$H(t)=50\\cos\\dfrac{\\pi}{10}t+52$',
              '$H(t)=-50\\cos\\dfrac{\\pi}{10}t+52$',
              '$H(t)=50\\sin\\dfrac{\\pi}{10}t+2$',
              '$H(t)=-50\\cos\\dfrac{\\pi}{10}t+50$',
            ],
            answer: 1,
            explain: '中线 $=2+50=52$，振幅 $50$，起点在谷值用 $-\\cos$：$H(t)=-50\\cos\\dfrac{\\pi}{10}t+52$（周期 $20$，$\\omega=\\dfrac{\\pi}{10}$）。',
          },
          {
            id: 'u9-l3-q4',
            type: 'judge',
            prompt: '判断：建模时若起点在最低点（谷值），用 $-\\cos$ 最契合；在最高点用 $+\\cos$。',
            answer: true,
            explain: '$-\\cos 0=-1$ 给最小值、$+\\cos 0=1$ 给最大值，按起始几何状态对号入座即可。',
          },
          {
            id: 'u9-l3-q5',
            type: 'choice',
            prompt: '水深 $y=3\\sin\\left(\\dfrac{\\pi}{6}t+\\dfrac{\\pi}{6}\\right)+10$，水深不低于 $11.5$ 米才可冲浪。先把条件化简为？',
            options: [
              '$\\sin\\left(\\dfrac{\\pi}{6}t+\\dfrac{\\pi}{6}\\right)\\ge \\dfrac{1}{2}$',
              '$\\sin\\left(\\dfrac{\\pi}{6}t+\\dfrac{\\pi}{6}\\right)\\ge 1.5$',
              '$\\sin\\left(\\dfrac{\\pi}{6}t+\\dfrac{\\pi}{6}\\right)\\le \\dfrac{1}{2}$',
              '$\\sin\\left(\\dfrac{\\pi}{6}t+\\dfrac{\\pi}{6}\\right)\\ge \\dfrac{1}{3}$',
            ],
            answer: 0,
            explain: '$3\\sin(\\cdots)+10\\ge 11.5\\Rightarrow\\sin(\\cdots)\\ge\\dfrac{1.5}{3}=\\dfrac{1}{2}$。',
          },
          {
            id: 'u9-l3-q6',
            type: 'input',
            prompt: '承上题，一天 $24$ 小时内允许冲浪的总时长是多少小时？',
            accept: ['8', '8小时', '8h'],
            placeholder: '例如 8',
            explain: '每个周期满足条件的时长为 $4$ 小时，$24$ 小时含 $2$ 个完整周期，共 $2\\times4=8$ 小时。',
          },
        ],
      },
    ],
  },
]
