import type { Unit } from '../../types'

// 内容取自《三角函数教程》第六部分（第 16–18 章）：
// 振幅·相位·谐波合成 / 三角换元 / 三角多项式与万能代换。
// 公式用 $...$（KaTeX）。TS 字符串内 LaTeX 反斜杠一律双写。

export const PART6_UNITS: Unit[] = [
  // ============================== 单元 16 ==============================
  {
    id: 'u16',
    title: '振幅·相位·谐波合成',
    color: '#6c5ce7',
    icon: '🎵',
    blurb: '把 $a\\sin x+b\\cos x$ 压成一个波——读出振幅与初相',
    lessons: [
      {
        id: 'u16-l1',
        title: '辅助角公式',
        subtitle: '$a\\sin x+b\\cos x=R\\sin(x+\\varphi)$',
        questions: [
          {
            id: 'u16-l1-q1',
            type: 'choice',
            prompt: '把 $a\\sin x+b\\cos x$ 化成 $R\\sin(x+\\varphi)$，振幅 $R$ 等于？',
            options: ['$a+b$', '$\\sqrt{a^2+b^2}$', '$a^2+b^2$', '$\\sqrt{a^2-b^2}$'],
            answer: 1,
            explain: '展开比较系数得 $R\\cos\\varphi=a,\\ R\\sin\\varphi=b$，两式平方相加得 $R=\\sqrt{a^2+b^2}$。',
          },
          {
            id: 'u16-l1-q2',
            type: 'input',
            prompt: '$3\\sin x+4\\cos x$ 的振幅 $R$ 是多少？（填数字）',
            accept: ['5', 'R=5', '5.0'],
            placeholder: '例如 2',
            explain: '$R=\\sqrt{3^2+4^2}=\\sqrt{25}=5$。',
          },
          {
            id: 'u16-l1-q3',
            type: 'judge',
            prompt: '合成式 $R\\sin(x+\\varphi)$ 的值域是 $[-R,\\,R]$。',
            answer: true,
            explain: '$\\sin(x+\\varphi)\\in[-1,1]$，乘以 $R$ 得值域 $[-R,R]$，这正是直接读出值域的好处。',
          },
          {
            id: 'u16-l1-q4',
            type: 'choice',
            prompt: '设 $a\\sin x+b\\cos x=R\\sin(x+\\varphi)$，下面哪组关系正确？',
            options: [
              '$R\\cos\\varphi=a,\\ R\\sin\\varphi=b$',
              '$R\\sin\\varphi=a,\\ R\\cos\\varphi=b$',
              '$R\\cos\\varphi=b,\\ R\\sin\\varphi=-a$',
              '$R\\tan\\varphi=a$',
            ],
            answer: 0,
            explain: '$R\\sin(x+\\varphi)=R\\cos\\varphi\\sin x+R\\sin\\varphi\\cos x$，对比 $a\\sin x+b\\cos x$ 即得 $R\\cos\\varphi=a,\\ R\\sin\\varphi=b$。',
          },
          {
            id: 'u16-l1-q5',
            type: 'input',
            prompt: '$5\\sin x-12\\cos x$ 的振幅 $R$ 是多少？（填数字）',
            accept: ['13', 'R=13', '13.0'],
            placeholder: '例如 5',
            explain: '$R=\\sqrt{5^2+(-12)^2}=\\sqrt{169}=13$。',
          },
          {
            id: 'u16-l1-q6',
            type: 'judge',
            prompt: '辅助角公式里，振幅 $R$ 就是把 $(a,b)$ 看成向量后的模长。',
            answer: true,
            explain: '$(a,b)$ 的模 $\\sqrt{a^2+b^2}=R$ 即振幅，辐角即初相 $\\varphi$，这是公式的几何解释。',
          },
        ],
      },
      {
        id: 'u16-l2',
        title: '求初相与具体合成',
        subtitle: '从 $\\cos\\varphi,\\sin\\varphi$ 的符号定象限',
        questions: [
          {
            id: 'u16-l2-q1',
            type: 'choice',
            prompt: '把 $\\sqrt3\\sin t+\\cos t$ 化成 $R\\sin(t+\\varphi)$，结果是？',
            options: [
              '$2\\sin\\left(t+\\dfrac{\\pi}{6}\\right)$',
              '$2\\sin\\left(t+\\dfrac{\\pi}{3}\\right)$',
              '$\\sqrt2\\sin\\left(t+\\dfrac{\\pi}{4}\\right)$',
              '$2\\sin\\left(t-\\dfrac{\\pi}{6}\\right)$',
            ],
            answer: 0,
            explain: '$R=\\sqrt{3+1}=2$，$\\cos\\varphi=\\dfrac{\\sqrt3}{2},\\ \\sin\\varphi=\\dfrac12$，故 $\\varphi=\\dfrac{\\pi}{6}$。',
          },
          {
            id: 'u16-l2-q2',
            type: 'choice',
            prompt: '若 $\\cos\\varphi=\\dfrac12$ 且 $\\sin\\varphi=-\\dfrac{\\sqrt3}{2}$，则可取 $\\varphi=$？',
            options: ['$\\dfrac{\\pi}{3}$', '$-\\dfrac{\\pi}{3}$', '$\\dfrac{2\\pi}{3}$', '$\\dfrac{\\pi}{6}$'],
            answer: 1,
            explain: '$\\cos\\varphi>0,\\ \\sin\\varphi<0$ 落在第四象限，取 $\\varphi=-\\dfrac{\\pi}{3}$ 最自然。',
          },
          {
            id: 'u16-l2-q3',
            type: 'input',
            prompt: '把 $\\sin x+\\cos x$ 写成 $\\sqrt2\\sin(x+\\varphi)$，初相 $\\varphi=$？（用 $\\pi$ 表示）',
            accept: ['π/4', 'pi/4', '\\frac{\\pi}{4}', '45°', '45度'],
            placeholder: '例如 π/6',
            explain: '$R=\\sqrt2$，$\\cos\\varphi=\\sin\\varphi=\\dfrac{\\sqrt2}{2}$，故 $\\varphi=\\dfrac{\\pi}{4}$。',
          },
          {
            id: 'u16-l2-q4',
            type: 'judge',
            prompt: '只用 $\\cos\\varphi$ 的值即可唯一确定 $\\varphi$ 所在象限。',
            answer: false,
            explain: '单看一个三角值会丢失象限信息，必须让 $\\cos\\varphi$ 与 $\\sin\\varphi$ 的符号同时满足。',
          },
          {
            id: 'u16-l2-q5',
            type: 'choice',
            prompt: '$f(x)=\\sin x-\\sqrt3\\cos x$ 化成 $R\\sin(x+\\varphi)$，下面正确的是？',
            options: [
              '$2\\sin\\left(x-\\dfrac{\\pi}{3}\\right)$',
              '$2\\sin\\left(x+\\dfrac{\\pi}{3}\\right)$',
              '$2\\sin\\left(x-\\dfrac{\\pi}{6}\\right)$',
              '$4\\sin\\left(x-\\dfrac{\\pi}{3}\\right)$',
            ],
            answer: 0,
            explain: '$R=\\sqrt{1+3}=2$，$\\cos\\varphi=\\dfrac12,\\ \\sin\\varphi=-\\dfrac{\\sqrt3}{2}$，取 $\\varphi=-\\dfrac{\\pi}{3}$。',
          },
          {
            id: 'u16-l2-q6',
            type: 'match',
            prompt: '把每个线性组合与它的振幅 $R$ 配对。',
            left: ['$\\sin x+\\cos x$', '$3\\sin x+4\\cos x$', '$\\sqrt3\\sin x+\\cos x$', '$\\sin x-\\sqrt3\\cos x$'],
            right: ['$\\sqrt2$', '$5$', '$2$', '$2$'],
            explain: '振幅都用 $R=\\sqrt{a^2+b^2}$：$\\sqrt2,\\ 5,\\ 2,\\ 2$。',
          },
        ],
      },
      {
        id: 'u16-l3',
        title: '最值·周期·简谐模型',
        subtitle: '从合成式读出最大值与周期',
        questions: [
          {
            id: 'u16-l3-q1',
            type: 'input',
            prompt: '$y=3\\sin x+4\\cos x$ 的最大值是多少？（填数字）',
            accept: ['5', '5.0', 'max=5'],
            placeholder: '例如 2',
            explain: '合成为 $5\\sin(x+\\varphi)$，最大值即振幅 $R=5$。',
          },
          {
            id: 'u16-l3-q2',
            type: 'choice',
            prompt: '$f(x)=2\\sin\\left(x-\\dfrac{\\pi}{3}\\right)$ 的最小正周期是？',
            options: ['$\\pi$', '$2\\pi$', '$\\dfrac{\\pi}{2}$', '$4\\pi$'],
            answer: 1,
            explain: '$x$ 的系数为 $1$，周期 $T=\\dfrac{2\\pi}{1}=2\\pi$。',
          },
          {
            id: 'u16-l3-q3',
            type: 'judge',
            prompt: '函数 $y=a\\sin\\omega x+b\\cos\\omega x$ 的最小值是 $-\\sqrt{a^2+b^2}$。',
            answer: true,
            explain: '合成为 $R\\sin(\\omega x+\\varphi)$，$R=\\sqrt{a^2+b^2}$，最小值为 $-R$。',
          },
          {
            id: 'u16-l3-q4',
            type: 'choice',
            prompt: '简谐运动 $x(t)=A\\sin(\\omega t+\\varphi)$ 中，$\\varphi$ 称为？',
            options: ['振幅', '角频率', '初相', '周期'],
            answer: 2,
            explain: '$A$ 是振幅，$\\omega$ 是角频率，$\\varphi$ 是初相——与辅助角公式同构。',
          },
          {
            id: 'u16-l3-q5',
            type: 'input',
            prompt: '两正交分量 $3\\sin\\omega t$ 与 $4\\cos\\omega t$ 叠加，合振动振幅是多少？（填数字）',
            accept: ['5', '5.0'],
            placeholder: '例如 5',
            explain: '相位差 $\\dfrac{\\pi}{2}$（正交），$R=\\sqrt{3^2+4^2}=5$。',
          },
          {
            id: 'u16-l3-q6',
            type: 'judge',
            prompt: '同频率的两个简谐振动叠加后，仍是同频率的简谐振动。',
            answer: true,
            explain: '$A_1\\sin(\\omega t+\\phi_1)+A_2\\sin(\\omega t+\\phi_2)$ 总可合成为 $R\\sin(\\omega t+\\varphi)$，频率不变，这正是辅助角公式的物理意义。',
          },
        ],
      },
    ],
  },

  // ============================== 单元 17 ==============================
  {
    id: 'u17',
    title: '三角换元',
    color: '#0984e3',
    icon: '🔁',
    blurb: '借单位圆恒等式，把根式交给三角函数吸收',
    lessons: [
      {
        id: 'u17-l1',
        title: '三类经典代换',
        subtitle: '$\\sqrt{a^2-x^2},\\ \\sqrt{a^2+x^2},\\ \\sqrt{x^2-a^2}$',
        questions: [
          {
            id: 'u17-l1-q1',
            type: 'choice',
            prompt: '用 $x=a\\sin\\theta$ 换元，$\\sqrt{a^2-x^2}$ 化为？',
            options: ['$a\\cos\\theta$', '$a\\sin\\theta$', '$a\\tan\\theta$', '$a$'],
            answer: 0,
            explain: '$\\sqrt{a^2-a^2\\sin^2\\theta}=a\\sqrt{1-\\sin^2\\theta}=a\\cos\\theta$（取 $\\cos\\theta\\ge0$）。',
          },
          {
            id: 'u17-l1-q2',
            type: 'choice',
            prompt: '含 $\\sqrt{a^2+x^2}$ 时，应采用哪种代换？',
            options: ['$x=a\\sin\\theta$', '$x=a\\tan\\theta$', '$x=a\\sec\\theta$', '$x=a\\cos\\theta$'],
            answer: 1,
            explain: '取 $x=a\\tan\\theta$，则 $a^2+x^2=a^2\\sec^2\\theta$，$\\sqrt{a^2+x^2}=a\\sec\\theta$。',
          },
          {
            id: 'u17-l1-q3',
            type: 'choice',
            prompt: '含 $\\sqrt{x^2-a^2}$ 时，应采用哪种代换？',
            options: ['$x=a\\sin\\theta$', '$x=a\\tan\\theta$', '$x=a\\sec\\theta$', '$x=a\\cot\\theta$'],
            answer: 2,
            explain: '取 $x=a\\sec\\theta$，则 $x^2-a^2=a^2\\tan^2\\theta$，$\\sqrt{x^2-a^2}=a\\tan\\theta$。',
          },
          {
            id: 'u17-l1-q4',
            type: 'judge',
            prompt: '三角代换之所以有效，是因为 $1-\\sin^2t=\\cos^2t$、$1+\\tan^2t=\\sec^2t$ 把根号「吸收」掉了。',
            answer: true,
            explain: '根式并非凭空消失，而是被这两条恒等式化成完全平方后开出。',
          },
          {
            id: 'u17-l1-q5',
            type: 'input',
            prompt: '设 $x=5\\tan\\theta$，则 $\\sqrt{25+x^2}=$？（用 $\\theta$ 表示，取正）',
            accept: ['5secθ', '5\\secθ', '5\\sec\\theta', '5 sec θ', '5sectheta', '5\\sec theta'],
            placeholder: '例如 a cosθ',
            explain: '$25+25\\tan^2\\theta=25\\sec^2\\theta$，开方得 $5\\sec\\theta$。',
          },
          {
            id: 'u17-l1-q6',
            type: 'match',
            prompt: '把根式结构与推荐代换配对。',
            left: ['$\\sqrt{a^2-x^2}$', '$\\sqrt{a^2+x^2}$', '$\\sqrt{x^2-a^2}$'],
            right: ['$x=a\\sin t$', '$x=a\\tan t$', '$x=a\\sec t$'],
            explain: '减号配 $\\sin$，加号配 $\\tan$，$x^2-a^2$ 配 $\\sec$——三类经典代换。',
          },
        ],
      },
      {
        id: 'u17-l2',
        title: '范围、符号与绝对值',
        subtitle: '$\\sqrt{\\cos^2t}=|\\cos t|$，再用范围定号',
        questions: [
          {
            id: 'u17-l2-q1',
            type: 'choice',
            prompt: '化简 $\\sqrt{\\cos^2 t}$ 的正确结果是？',
            options: ['$\\cos t$', '$|\\cos t|$', '$-\\cos t$', '$\\cos^2 t$'],
            answer: 1,
            explain: '开平方先得绝对值 $|\\cos t|$，再依参数范围去掉绝对值，这是避免符号错误的关键。',
          },
          {
            id: 'u17-l2-q2',
            type: 'judge',
            prompt: '当 $t\\in\\left[-\\dfrac{\\pi}{2},\\dfrac{\\pi}{2}\\right]$ 时，$|\\cos t|=\\cos t$。',
            answer: true,
            explain: '该区间上 $\\cos t\\ge0$，故可去掉绝对值，正是 $x=a\\sin t$ 常取此范围的原因。',
          },
          {
            id: 'u17-l2-q3',
            type: 'input',
            prompt: '设 $x=2\\sin t,\\ t\\in\\left[-\\dfrac{\\pi}{2},\\dfrac{\\pi}{2}\\right]$，则 $\\sqrt{4-x^2}=$？（用 $t$ 表示）',
            accept: ['2cost', '2\\cos t', '2\\cost', '2cos t', '2 cos t', '2\\cos\\,t'],
            placeholder: '例如 3 cos t',
            explain: '$\\sqrt{4-4\\sin^2t}=2|\\cos t|=2\\cos t$（该范围内 $\\cos t\\ge0$）。',
          },
          {
            id: 'u17-l2-q4',
            type: 'choice',
            prompt: '$x=3\\sin t$，当 $x=1$ 时（取 $t\\in\\left[-\\dfrac{\\pi}{2},\\dfrac{\\pi}{2}\\right]$ 之外不计），$\\sqrt{9-x^2}=$？',
            options: ['$2\\sqrt2$', '$3$', '$\\sqrt8$ 与 $2\\sqrt2$ 都对', '$\\sqrt{10}$'],
            answer: 2,
            explain: '$\\sqrt{9-1}=\\sqrt8=2\\sqrt2$，两种写法等价。',
          },
          {
            id: 'u17-l2-q5',
            type: 'judge',
            prompt: '若不限制参数 $t$ 的范围，也可以随意把 $|\\cos t|$ 写成 $\\cos t$。',
            answer: false,
            explain: '只有在 $\\cos t\\ge0$ 的范围内才成立，否则会出符号错误——这是三角代换最常被忽略的细节。',
          },
          {
            id: 'u17-l2-q6',
            type: 'choice',
            prompt: '已知 $x=\\sec t,\\ t\\in\\left[0,\\dfrac{\\pi}{2}\\right)$，化简 $\\dfrac{\\sqrt{x^2-1}}{x}$ 得？',
            options: ['$\\cos t$', '$\\sin t$', '$\\tan t$', '$\\sec t$'],
            answer: 1,
            explain: '$\\sqrt{\\sec^2t-1}=\\tan t$，故 $\\dfrac{\\tan t}{\\sec t}=\\dfrac{\\sin t/\\cos t}{1/\\cos t}=\\sin t$。',
          },
        ],
      },
      {
        id: 'u17-l3',
        title: '换元后的积分与几何',
        subtitle: '把根式问题化成三角恒等式问题',
        questions: [
          {
            id: 'u17-l3-q1',
            type: 'choice',
            prompt: '$\\displaystyle\\int\\frac{dx}{\\sqrt{9-x^2}}$ 用 $x=3\\sin t$ 后等于？',
            options: ['$t+C$', '$3t+C$', '$\\cos t+C$', '$\\dfrac{t}{3}+C$'],
            answer: 0,
            explain: '$dx=3\\cos t\\,dt$，被积式化为 $\\displaystyle\\int\\dfrac{3\\cos t}{3\\cos t}\\,dt=\\int dt=t+C$。',
          },
          {
            id: 'u17-l3-q2',
            type: 'input',
            prompt: '$\\displaystyle\\int\\frac{dx}{\\sqrt{9-x^2}}=$？回代后用 $x$ 表示（不写 $+C$）。',
            accept: ['arcsin(x/3)', 'arcsin x/3', '\\arcsin\\frac{x}{3}', 'arcsin(x/3)+C', '\\arcsin(x/3)'],
            placeholder: '例如 arcsin(x/2)',
            explain: '由 $x=3\\sin t$ 得 $t=\\arcsin\\dfrac{x}{3}$，故积分为 $\\arcsin\\dfrac{x}{3}+C$。',
          },
          {
            id: 'u17-l3-q3',
            type: 'choice',
            prompt: '$\\displaystyle\\int\\frac{dx}{x^2+4}$ 用 $x=2\\tan t$ 后，结果为？',
            options: [
              '$\\dfrac12\\arctan\\dfrac{x}{2}+C$',
              '$\\arctan\\dfrac{x}{2}+C$',
              '$2\\arctan\\dfrac{x}{2}+C$',
              '$\\arcsin\\dfrac{x}{2}+C$',
            ],
            answer: 0,
            explain: '$dx=2\\sec^2t\\,dt$，被积式化为 $\\dfrac12\\int dt=\\dfrac{t}{2}+C=\\dfrac12\\arctan\\dfrac{x}{2}+C$。',
          },
          {
            id: 'u17-l3-q4',
            type: 'judge',
            prompt: '$\\displaystyle\\int_0^a\\sqrt{a^2-x^2}\\,dx=\\dfrac{\\pi a^2}{4}$，等于半径为 $a$ 的四分之一圆面积。',
            answer: true,
            explain: '$y=\\sqrt{a^2-x^2}$ 是上半圆，第一象限部分面积为 $\\dfrac14\\pi a^2$，三角代换给出同一结果。',
          },
          {
            id: 'u17-l3-q5',
            type: 'choice',
            prompt: '$x=a\\sin\\theta$ 的几何意义中，把 $x$ 看成对边、$a$ 看成斜边，则邻边长是？',
            options: ['$a\\tan\\theta$', '$a\\sin\\theta$', '$\\sqrt{a^2-x^2}$', '$a\\sec\\theta$'],
            answer: 2,
            explain: '由勾股定理，邻边 $=\\sqrt{a^2-x^2}=a\\cos\\theta$，根式变成三角形的一条边。',
          },
          {
            id: 'u17-l3-q6',
            type: 'judge',
            prompt: '用三角代换算定积分时，换元的同时必须把积分上下限也一并换掉。',
            answer: true,
            explain: '换限后可省去最后回代原变量的步骤，更简洁，也避免回代出错。',
          },
        ],
      },
    ],
  },

  // ============================== 单元 18 ==============================
  {
    id: 'u18',
    title: '三角多项式与代换',
    color: '#00cd9c',
    icon: '🧮',
    blurb: '三倍角、降幂与万能代换 $t=\\tan\\dfrac{x}{2}$',
    lessons: [
      {
        id: 'u18-l1',
        title: '三倍角与三角多项式',
        subtitle: '$\\cos 3x=4\\cos^3 x-3\\cos x$',
        questions: [
          {
            id: 'u18-l1-q1',
            type: 'choice',
            prompt: '三倍角公式 $\\cos 3x=$？',
            options: [
              '$4\\cos^3 x-3\\cos x$',
              '$3\\cos x-4\\cos^3 x$',
              '$2\\cos^2 x-1$',
              '$4\\cos^3 x+3\\cos x$',
            ],
            answer: 0,
            explain: '由 $\\cos 3x=\\cos(2x+x)$ 展开并用 $\\sin^2x=1-\\cos^2x$ 化简，得 $4\\cos^3x-3\\cos x$。',
          },
          {
            id: 'u18-l1-q2',
            type: 'choice',
            prompt: '三倍角公式 $\\sin 3x=$？',
            options: [
              '$3\\sin x-4\\sin^3 x$',
              '$4\\sin^3 x-3\\sin x$',
              '$2\\sin x\\cos x$',
              '$3\\sin x+4\\sin^3 x$',
            ],
            answer: 0,
            explain: '$\\sin 3x=3\\sin x-4\\sin^3 x$，与 $\\cos 3x$ 形式对称（符号相反）。',
          },
          {
            id: 'u18-l1-q3',
            type: 'judge',
            prompt: '令 $u=\\cos x$，则 $\\cos 3x=4u^3-3u$ 是 $u$ 的三次多项式（Chebyshev 多项式 $T_3$）。',
            answer: true,
            explain: '$\\cos(nx)$ 总能写成 $\\cos x$ 的 $n$ 次多项式 $T_n(\\cos x)$，这里 $T_3(u)=4u^3-3u$。',
          },
          {
            id: 'u18-l1-q4',
            type: 'choice',
            prompt: '$8\\cos^3 x-6\\cos x$ 可以化简为？',
            options: ['$2\\cos 3x$', '$\\cos 3x$', '$\\cos 2x$', '$4\\cos 3x$'],
            answer: 0,
            explain: '$8\\cos^3x-6\\cos x=2(4\\cos^3x-3\\cos x)=2\\cos 3x$。',
          },
          {
            id: 'u18-l1-q5',
            type: 'input',
            prompt: '方程 $8\\cos^3 x-6\\cos x=1$ 等价于 $\\cos 3x=$？（填数值）',
            accept: ['1/2', '0.5', '\\frac{1}{2}', '½'],
            placeholder: '例如 1/2',
            explain: '左边 $=2\\cos 3x=1$，故 $\\cos 3x=\\dfrac12$。',
          },
          {
            id: 'u18-l1-q6',
            type: 'judge',
            prompt: '降幂公式 $\\cos^2 t=\\dfrac{1+\\cos 2t}{2}$ 能把 $\\cos^2$ 降成关于 $\\cos 2t$ 的一次式。',
            answer: true,
            explain: '由 $\\cos 2t=2\\cos^2t-1$ 反解即得，常用于把 $\\cos^2,\\sin^2$ 化为可直接积分的形式。',
          },
        ],
      },
      {
        id: 'u18-l2',
        title: '万能代换公式',
        subtitle: '$t=\\tan\\dfrac{x}{2}$ 把三角式变有理式',
        questions: [
          {
            id: 'u18-l2-q1',
            type: 'choice',
            prompt: '令 $t=\\tan\\dfrac{x}{2}$，则 $\\sin x=$？',
            options: [
              '$\\dfrac{2t}{1+t^2}$',
              '$\\dfrac{1-t^2}{1+t^2}$',
              '$\\dfrac{2t}{1-t^2}$',
              '$\\dfrac{1+t^2}{2t}$',
            ],
            answer: 0,
            explain: '万能代换核心公式之一：$\\sin x=\\dfrac{2t}{1+t^2}$。',
          },
          {
            id: 'u18-l2-q2',
            type: 'choice',
            prompt: '令 $t=\\tan\\dfrac{x}{2}$，则 $\\cos x=$？',
            options: [
              '$\\dfrac{2t}{1+t^2}$',
              '$\\dfrac{1-t^2}{1+t^2}$',
              '$\\dfrac{2t}{1-t^2}$',
              '$\\dfrac{1-t^2}{2t}$',
            ],
            answer: 1,
            explain: '$\\cos x=\\dfrac{1-t^2}{1+t^2}$。',
          },
          {
            id: 'u18-l2-q3',
            type: 'input',
            prompt: '令 $t=\\tan\\dfrac{x}{2}$，则 $\\tan x=$？（关于 $t$ 的有理式）',
            accept: ['2t/(1-t^2)', '2t/(1-t²)', '\\frac{2t}{1-t^2}', '2t/(1-t*t)'],
            placeholder: '例如 2t/(1+t^2)',
            explain: '$\\tan x=\\dfrac{\\sin x}{\\cos x}=\\dfrac{2t}{1-t^2}$。',
          },
          {
            id: 'u18-l2-q4',
            type: 'choice',
            prompt: '万能代换中，$dx$ 用 $t$ 表示为？',
            options: [
              '$\\dfrac{2}{1+t^2}\\,dt$',
              '$\\dfrac{1}{1+t^2}\\,dt$',
              '$(1+t^2)\\,dt$',
              '$2t\\,dt$',
            ],
            answer: 0,
            explain: '由 $t=\\tan\\dfrac{x}{2}$ 微分得 $dx=\\dfrac{2}{1+t^2}\\,dt$，用于把三角积分变成有理函数积分。',
          },
          {
            id: 'u18-l2-q5',
            type: 'judge',
            prompt: '万能代换 $t=\\tan\\dfrac{x}{2}$ 在 $x=\\pi$ 处无定义，解题后需单独验证 $x=\\pi$ 是否为解。',
            answer: true,
            explain: '$\\tan\\dfrac{\\pi}{2}$ 不存在，相当于预设 $x\\ne\\pi$，故须回头检查 $x=\\pi$ 以防漏解。',
          },
          {
            id: 'u18-l2-q6',
            type: 'match',
            prompt: '把每个三角函数与它的万能代换表达式配对（$t=\\tan\\dfrac{x}{2}$）。',
            left: ['$\\sin x$', '$\\cos x$', '$\\tan x$'],
            right: ['$\\dfrac{2t}{1+t^2}$', '$\\dfrac{1-t^2}{1+t^2}$', '$\\dfrac{2t}{1-t^2}$'],
            explain: '三条核心公式：$\\sin x=\\dfrac{2t}{1+t^2}$，$\\cos x=\\dfrac{1-t^2}{1+t^2}$，$\\tan x=\\dfrac{2t}{1-t^2}$。',
          },
        ],
      },
      {
        id: 'u18-l3',
        title: '万能代换解题',
        subtitle: '三角方程与有理积分的统一入口',
        questions: [
          {
            id: 'u18-l3-q1',
            type: 'choice',
            prompt: '用万能代换解 $\\sin x+\\cos x=1$，化简后得到关于 $t$ 的方程是？',
            options: [
              '$t(t-1)=0$',
              '$t^2+1=0$',
              '$t^2-2t=0$ 的另解',
              '$(t+1)^2=0$',
            ],
            answer: 0,
            explain: '代入化简得 $2t=2t^2$，即 $t(t-1)=0$，故 $t=0$ 或 $t=1$。',
          },
          {
            id: 'u18-l3-q2',
            type: 'choice',
            prompt: '上题中 $t=1$（即 $\\tan\\dfrac{x}{2}=1$）对应的解是？',
            options: [
              '$x=\\dfrac{\\pi}{2}+2k\\pi$',
              '$x=2k\\pi$',
              '$x=\\pi+2k\\pi$',
              '$x=\\dfrac{\\pi}{4}+2k\\pi$',
            ],
            answer: 0,
            explain: '$\\tan\\dfrac{x}{2}=1\\Rightarrow\\dfrac{x}{2}=\\dfrac{\\pi}{4}+k\\pi\\Rightarrow x=\\dfrac{\\pi}{2}+2k\\pi$。',
          },
          {
            id: 'u18-l3-q3',
            type: 'judge',
            prompt: '三角代换擅长根式结构，万能代换擅长同时含 $\\sin x,\\cos x$ 的有理式——二者服务对象不同。',
            answer: true,
            explain: '两者都叫代换但对象不同：三角代换处理 $\\sqrt{\\cdot}$，万能代换处理三角有理式。',
          },
          {
            id: 'u18-l3-q4',
            type: 'input',
            prompt: '$\\displaystyle\\int\\frac{dx}{2+\\cos x}$ 用 $t=\\tan\\dfrac{x}{2}$ 后，被积式化为 $\\dfrac{2}{?+t^2}\\,dt$，问号处填？',
            accept: ['3', 't^2+3', '+3'],
            placeholder: '例如 1',
            explain: '$2+\\cos x=\\dfrac{3+t^2}{1+t^2}$，结合 $dx=\\dfrac{2}{1+t^2}dt$ 得 $\\dfrac{2}{3+t^2}\\,dt$。',
          },
          {
            id: 'u18-l3-q5',
            type: 'choice',
            prompt: '$3\\sin x+4\\cos x=5$ 在 $[0,2\\pi)$ 上的解的个数是？',
            options: ['$0$ 个', '$1$ 个', '$2$ 个', '无穷多个'],
            answer: 1,
            explain: '右边 $5$ 恰为振幅 $\\sqrt{3^2+4^2}=5$，即最大值，故只有一个解（万能代换给出重根 $t=\\dfrac13$）。',
          },
          {
            id: 'u18-l3-q6',
            type: 'judge',
            prompt: '万能代换并不是所有三角题都应优先使用——有些题用图像或恒等式会更短。',
            answer: true,
            explain: '把万能代换当成「万灵药」是常见误区；它是统一入口，但不总是最短路径。',
          },
        ],
      },
    ],
  },
]
