import type { Unit } from '../../types'

// 内容取自《三角函数教程》第 1–3 章：单位圆 / 六个三角函数 / 特殊角与诱导。
// 公式用 $...$（KaTeX）。输入题的 accept 提供多种等价写法，配合容错匹配。

export const PART1_UNITS: Unit[] = [
  // ============================== 单元 1 ==============================
  {
    id: 'u1',
    title: '单位圆与弧度',
    color: '#58cc02',
    icon: '🧭',
    blurb: '角度、弧度、单位圆——三角函数的几何起点',
    lessons: [
      {
        id: 'u1-l1',
        title: '角度与弧度',
        subtitle: '把 $180^\\circ$ 当作 $\\pi$',
        questions: [
          {
            id: 'u1-l1-q1',
            type: 'choice',
            prompt: '$180^\\circ$ 等于多少弧度？',
            options: ['$\\dfrac{\\pi}{2}$', '$\\pi$', '$2\\pi$', '$\\dfrac{\\pi}{4}$'],
            answer: 1,
            explain: '半圈对应 $\\pi$ 弧度，整圈 $360^\\circ=2\\pi$。',
          },
          {
            id: 'u1-l1-q2',
            type: 'input',
            prompt: '把 $90^\\circ$ 化为弧度（用 $\\pi$ 表示）。',
            accept: ['π/2', 'pi/2', '\\frac{\\pi}{2}', '0.5π', 'π/2 rad'],
            placeholder: '例如 π/3',
            explain: '$90^\\circ=\\dfrac{90}{180}\\pi=\\dfrac{\\pi}{2}$。',
          },
          {
            id: 'u1-l1-q3',
            type: 'input',
            prompt: '把 $\\dfrac{\\pi}{6}$ 化为角度（填数字，单位度）。',
            accept: ['30', '30°', '30度'],
            placeholder: '例如 45',
            explain: '$\\dfrac{\\pi}{6}=\\dfrac16\\times180^\\circ=30^\\circ$。',
          },
          {
            id: 'u1-l1-q4',
            type: 'judge',
            prompt: '$60^\\circ=\\dfrac{\\pi}{3}$ 弧度。',
            answer: true,
            explain: '$60^\\circ=\\dfrac{60}{180}\\pi=\\dfrac{\\pi}{3}$，正确。',
          },
          {
            id: 'u1-l1-q5',
            type: 'choice',
            prompt: '$\\dfrac{3\\pi}{2}$ 对应的角度是？',
            options: ['$135^\\circ$', '$210^\\circ$', '$270^\\circ$', '$300^\\circ$'],
            answer: 2,
            explain: '$\\dfrac{3\\pi}{2}=\\dfrac32\\times180^\\circ=270^\\circ$。',
          },
          {
            id: 'u1-l1-q6',
            type: 'match',
            prompt: '把角度与弧度配对。',
            left: ['$45^\\circ$', '$120^\\circ$', '$180^\\circ$'],
            right: ['$\\dfrac{\\pi}{4}$', '$\\dfrac{2\\pi}{3}$', '$\\pi$'],
            explain: '记住 $180^\\circ=\\pi$，其余按比例缩放即可。',
          },
        ],
      },
      {
        id: 'u1-l2',
        title: '单位圆上的点',
        subtitle: '终边交点 $(\\cos\\theta,\\sin\\theta)$',
        questions: [
          {
            id: 'u1-l2-q1',
            type: 'choice',
            prompt: '单位圆上角 $\\theta$ 的终边与圆交于点 $P$，则 $P$ 的坐标是？',
            options: [
              '$(\\sin\\theta,\\cos\\theta)$',
              '$(\\cos\\theta,\\sin\\theta)$',
              '$(\\tan\\theta,1)$',
              '$(\\cos\\theta,\\tan\\theta)$',
            ],
            answer: 1,
            explain: '横坐标是 $\\cos\\theta$，纵坐标是 $\\sin\\theta$。',
          },
          {
            id: 'u1-l2-q2',
            type: 'input',
            prompt: '单位圆上 $\\theta=0$ 处点 $P$ 的横坐标是多少？',
            accept: ['1'],
            explain: '$\\cos 0=1$，点为 $(1,0)$。',
          },
          {
            id: 'u1-l2-q3',
            type: 'judge',
            prompt: '单位圆上任意点到原点的距离都是 $1$。',
            answer: true,
            explain: '“单位圆”即半径为 $1$ 的圆，故距离恒为 $1$。',
          },
          {
            id: 'u1-l2-q4',
            type: 'choice',
            prompt: '点 $\\left(0,1\\right)$ 对应单位圆上的角是？',
            options: ['$0$', '$\\dfrac{\\pi}{2}$', '$\\pi$', '$\\dfrac{3\\pi}{2}$'],
            answer: 1,
            explain: '$(\\cos\\tfrac{\\pi}{2},\\sin\\tfrac{\\pi}{2})=(0,1)$。',
          },
          {
            id: 'u1-l2-q5',
            type: 'input',
            prompt: '$\\theta=\\pi$ 处单位圆上点 $P$ 的横坐标是多少？',
            accept: ['-1'],
            explain: '$\\cos\\pi=-1$，点为 $(-1,0)$。',
          },
          {
            id: 'u1-l2-q6',
            type: 'judge',
            prompt: '由 $P=(\\cos\\theta,\\sin\\theta)$ 在单位圆上，可得 $\\sin^2\\theta+\\cos^2\\theta=1$。',
            answer: true,
            explain: '点在单位圆上 $\\Rightarrow x^2+y^2=1$，即勾股恒等式。',
          },
        ],
      },
      {
        id: 'u1-l3',
        title: '弧长与扇形',
        subtitle: '$l=r\\theta,\\ S=\\tfrac12 r^2\\theta$',
        questions: [
          {
            id: 'u1-l3-q1',
            type: 'choice',
            prompt: '弧度制下，半径 $r$、圆心角 $\\theta$ 的弧长公式是？',
            options: ['$l=r+\\theta$', '$l=r\\theta$', '$l=\\dfrac{r}{\\theta}$', '$l=r^2\\theta$'],
            answer: 1,
            explain: '由 $\\theta=\\dfrac{l}{r}$ 直接得 $l=r\\theta$。',
          },
          {
            id: 'u1-l3-q2',
            type: 'input',
            prompt: '半径 $2$、圆心角 $\\dfrac{\\pi}{2}$ 的弧长是多少？（用 $\\pi$ 表示）',
            accept: ['π', 'pi', '2·π/2', '2*π/2'],
            explain: '$l=r\\theta=2\\times\\dfrac{\\pi}{2}=\\pi$。',
          },
          {
            id: 'u1-l3-q3',
            type: 'input',
            prompt: '半径 $3$、圆心角 $2$ 弧度的扇形面积是多少？',
            accept: ['9', '9.0'],
            explain: '$S=\\dfrac12 r^2\\theta=\\dfrac12\\times9\\times2=9$。',
          },
          {
            id: 'u1-l3-q4',
            type: 'judge',
            prompt: '弧度制让 $l=r\\theta$ 不必额外乘比例因子 $\\dfrac{\\pi}{180}$。',
            answer: true,
            explain: '这正是高等数学偏爱弧度制的原因。',
          },
        ],
      },
    ],
  },

  // ============================== 单元 2 ==============================
  {
    id: 'u2',
    title: '六个三角函数',
    color: '#1cb0f6',
    icon: '📐',
    blurb: 'sin/cos/tan 与它们的倒数、商数关系',
    lessons: [
      {
        id: 'u2-l1',
        title: '三角函数的定义',
        subtitle: '从单位圆与直角三角形看',
        questions: [
          {
            id: 'u2-l1-q1',
            type: 'choice',
            prompt: '直角三角形中，$\\sin\\theta$ 等于？',
            options: ['邻边 / 斜边', '对边 / 斜边', '对边 / 邻边', '斜边 / 对边'],
            answer: 1,
            explain: '正弦 = 对边比斜边（SOH）。',
          },
          {
            id: 'u2-l1-q2',
            type: 'choice',
            prompt: '$\\tan\\theta$ 等于下列哪个？',
            options: [
              '$\\dfrac{\\cos\\theta}{\\sin\\theta}$',
              '$\\dfrac{\\sin\\theta}{\\cos\\theta}$',
              '$\\sin\\theta\\cos\\theta$',
              '$\\dfrac{1}{\\sin\\theta}$',
            ],
            answer: 1,
            explain: '$\\tan\\theta=\\dfrac{\\sin\\theta}{\\cos\\theta}$（商数关系）。',
          },
          {
            id: 'u2-l1-q3',
            type: 'input',
            prompt: '若 $\\sin\\theta=\\dfrac35$，$\\cos\\theta=\\dfrac45$，求 $\\tan\\theta$。',
            accept: ['3/4', '0.75'],
            explain: '$\\tan\\theta=\\dfrac{\\sin}{\\cos}=\\dfrac{3/5}{4/5}=\\dfrac34$。',
          },
          {
            id: 'u2-l1-q4',
            type: 'judge',
            prompt: '$\\sec\\theta=\\dfrac{1}{\\cos\\theta}$。',
            answer: true,
            explain: '正割是余弦的倒数。',
          },
          {
            id: 'u2-l1-q5',
            type: 'match',
            prompt: '把函数与其“身份”配对。',
            left: ['$\\sec\\theta$', '$\\csc\\theta$', '$\\cot\\theta$'],
            right: ['$\\dfrac{1}{\\cos\\theta}$', '$\\dfrac{1}{\\sin\\theta}$', '$\\dfrac{\\cos\\theta}{\\sin\\theta}$'],
            explain: 'sec↔cos、csc↔sin 互为倒数；cot 是 tan 的倒数。',
          },
        ],
      },
      {
        id: 'u2-l2',
        title: '各象限的符号',
        subtitle: '“全正、S、T、C”',
        questions: [
          {
            id: 'u2-l2-q1',
            type: 'choice',
            prompt: '第二象限（$90^\\circ<\\theta<180^\\circ$）中，下列哪个为正？',
            options: ['$\\cos\\theta$', '$\\sin\\theta$', '$\\tan\\theta$', '都为负'],
            answer: 1,
            explain: '第二象限只有 $\\sin$（及 $\\csc$）为正。',
          },
          {
            id: 'u2-l2-q2',
            type: 'judge',
            prompt: '第三象限中 $\\tan\\theta>0$。',
            answer: true,
            explain: '第三象限 $\\sin<0,\\cos<0$，故 $\\tan=\\sin/\\cos>0$。',
          },
          {
            id: 'u2-l2-q3',
            type: 'choice',
            prompt: '若 $\\theta$ 在第四象限，则？',
            options: [
              '$\\sin\\theta>0,\\ \\cos\\theta>0$',
              '$\\sin\\theta<0,\\ \\cos\\theta>0$',
              '$\\sin\\theta<0,\\ \\cos\\theta<0$',
              '$\\sin\\theta>0,\\ \\cos\\theta<0$',
            ],
            answer: 1,
            explain: '第四象限横正纵负：$\\cos>0,\\ \\sin<0$。',
          },
          {
            id: 'u2-l2-q4',
            type: 'judge',
            prompt: '在第一象限，六个三角函数全部为正。',
            answer: true,
            explain: '第一象限“全正”。',
          },
          {
            id: 'u2-l2-q5',
            type: 'choice',
            prompt: '$\\cos\\theta<0$ 且 $\\sin\\theta<0$，$\\theta$ 在第几象限？',
            options: ['一', '二', '三', '四'],
            answer: 2,
            explain: '横纵坐标都为负 → 第三象限。',
          },
        ],
      },
      {
        id: 'u2-l3',
        title: '已知一值求其余',
        subtitle: '平方关系 + 象限定号',
        questions: [
          {
            id: 'u2-l3-q1',
            type: 'input',
            prompt: '已知 $\\cos\\theta=\\dfrac45$ 且 $\\theta$ 在第一象限，求 $\\sin\\theta$。',
            accept: ['3/5', '0.6'],
            explain: '$\\sin\\theta=\\sqrt{1-\\cos^2\\theta}=\\sqrt{1-16/25}=\\dfrac35$（第一象限取正）。',
          },
          {
            id: 'u2-l3-q2',
            type: 'input',
            prompt: '已知 $\\sin\\theta=\\dfrac{5}{13}$，$\\theta$ 为锐角，求 $\\cos\\theta$。',
            accept: ['12/13', '0.923'],
            explain: '$\\cos\\theta=\\sqrt{1-25/169}=\\dfrac{12}{13}$。',
          },
          {
            id: 'u2-l3-q3',
            type: 'judge',
            prompt: '已知 $\\sin\\theta=\\dfrac35$ 而不知象限，就能唯一确定 $\\cos\\theta$。',
            answer: false,
            explain: '$\\cos\\theta=\\pm\\dfrac45$，需用象限定号才能确定。',
          },
          {
            id: 'u2-l3-q4',
            type: 'choice',
            prompt: '$\\cos\\theta=-\\dfrac{12}{13}$ 且 $\\theta$ 在第三象限，则 $\\sin\\theta=$？',
            options: ['$\\dfrac{5}{13}$', '$-\\dfrac{5}{13}$', '$\\dfrac{12}{13}$', '$-\\dfrac{12}{13}$'],
            answer: 1,
            explain: '第三象限 $\\sin<0$，$\\sin\\theta=-\\sqrt{1-144/169}=-\\dfrac{5}{13}$。',
          },
        ],
      },
    ],
  },

  // ============================== 单元 3 ==============================
  {
    id: 'u3',
    title: '特殊角与诱导',
    color: '#ce82ff',
    icon: '✨',
    blurb: '$30^\\circ/45^\\circ/60^\\circ$ 的值与诱导公式',
    lessons: [
      {
        id: 'u3-l1',
        title: '特殊锐角的值',
        subtitle: '$30^\\circ,45^\\circ,60^\\circ$',
        questions: [
          {
            id: 'u3-l1-q1',
            type: 'input',
            prompt: '$\\sin 30^\\circ=?$（填分数或小数）',
            accept: ['1/2', '0.5'],
            explain: '$\\sin 30^\\circ=\\dfrac12$。',
          },
          {
            id: 'u3-l1-q2',
            type: 'choice',
            prompt: '$\\cos 30^\\circ=?$',
            options: ['$\\dfrac12$', '$\\dfrac{\\sqrt2}{2}$', '$\\dfrac{\\sqrt3}{2}$', '$1$'],
            answer: 2,
            explain: '$\\cos 30^\\circ=\\dfrac{\\sqrt3}{2}$。',
          },
          {
            id: 'u3-l1-q3',
            type: 'input',
            prompt: '$\\tan 45^\\circ=?$',
            accept: ['1'],
            explain: '$\\tan 45^\\circ=\\dfrac{\\sin45^\\circ}{\\cos45^\\circ}=1$。',
          },
          {
            id: 'u3-l1-q4',
            type: 'input',
            prompt: '$\\sin 60^\\circ=?$（可写 √3/2 或 sqrt3/2）',
            accept: ['√3/2', 'sqrt3/2', '(√3)/2', '0.866', '\\frac{\\sqrt3}{2}'],
            explain: '$\\sin 60^\\circ=\\dfrac{\\sqrt3}{2}\\approx0.866$。',
          },
          {
            id: 'u3-l1-q5',
            type: 'match',
            prompt: '把角与它的正弦值配对。',
            left: ['$\\sin 30^\\circ$', '$\\sin 45^\\circ$', '$\\sin 60^\\circ$'],
            right: ['$\\dfrac12$', '$\\dfrac{\\sqrt2}{2}$', '$\\dfrac{\\sqrt3}{2}$'],
            explain: '$\\sin$ 在 $30/45/60$ 依次为 $\\tfrac12,\\tfrac{\\sqrt2}{2},\\tfrac{\\sqrt3}{2}$（递增）。',
          },
          {
            id: 'u3-l1-q6',
            type: 'judge',
            prompt: '$\\tan 60^\\circ=\\sqrt3$。',
            answer: true,
            explain: '$\\tan 60^\\circ=\\dfrac{\\sin60^\\circ}{\\cos60^\\circ}=\\dfrac{\\sqrt3/2}{1/2}=\\sqrt3$。',
          },
        ],
      },
      {
        id: 'u3-l2',
        title: '象限轴上的值',
        subtitle: '$0^\\circ,90^\\circ,180^\\circ,270^\\circ$',
        questions: [
          {
            id: 'u3-l2-q1',
            type: 'input',
            prompt: '$\\cos 0^\\circ=?$',
            accept: ['1'],
            explain: '$\\cos 0^\\circ=1$。',
          },
          {
            id: 'u3-l2-q2',
            type: 'input',
            prompt: '$\\sin 90^\\circ=?$',
            accept: ['1'],
            explain: '$\\sin 90^\\circ=1$（单位圆最高点）。',
          },
          {
            id: 'u3-l2-q3',
            type: 'choice',
            prompt: '$\\cos 90^\\circ=?$',
            options: ['$1$', '$0$', '$-1$', '不存在'],
            answer: 1,
            explain: '$\\cos 90^\\circ=0$，点为 $(0,1)$。',
          },
          {
            id: 'u3-l2-q4',
            type: 'judge',
            prompt: '$\\tan 90^\\circ$ 不存在（无定义）。',
            answer: true,
            explain: '$\\cos 90^\\circ=0$ 作分母，故 $\\tan 90^\\circ$ 无定义。',
          },
          {
            id: 'u3-l2-q5',
            type: 'input',
            prompt: '$\\sin 180^\\circ=?$',
            accept: ['0'],
            explain: '$\\sin 180^\\circ=0$，点为 $(-1,0)$。',
          },
        ],
      },
      {
        id: 'u3-l3',
        title: '参考角与诱导',
        subtitle: '把任意角“搬回”锐角',
        questions: [
          {
            id: 'u3-l3-q1',
            type: 'choice',
            prompt: '$\\sin(180^\\circ-\\theta)$ 等于？',
            options: ['$-\\sin\\theta$', '$\\sin\\theta$', '$\\cos\\theta$', '$-\\cos\\theta$'],
            answer: 1,
            explain: '$\\sin(180^\\circ-\\theta)=\\sin\\theta$（补角正弦相等）。',
          },
          {
            id: 'u3-l3-q2',
            type: 'input',
            prompt: '利用诱导公式求 $\\sin 150^\\circ$。',
            accept: ['1/2', '0.5'],
            explain: '$\\sin 150^\\circ=\\sin(180^\\circ-30^\\circ)=\\sin 30^\\circ=\\dfrac12$。',
          },
          {
            id: 'u3-l3-q3',
            type: 'choice',
            prompt: '$\\cos(-\\theta)$ 等于？',
            options: ['$-\\cos\\theta$', '$\\cos\\theta$', '$\\sin\\theta$', '$-\\sin\\theta$'],
            answer: 1,
            explain: '余弦是偶函数：$\\cos(-\\theta)=\\cos\\theta$。',
          },
          {
            id: 'u3-l3-q4',
            type: 'judge',
            prompt: '$\\sin(-\\theta)=-\\sin\\theta$（正弦是奇函数）。',
            answer: true,
            explain: '正弦关于原点对称，为奇函数。',
          },
          {
            id: 'u3-l3-q5',
            type: 'input',
            prompt: '求 $\\cos 120^\\circ$（填分数）。',
            accept: ['-1/2', '-0.5'],
            explain: '$\\cos 120^\\circ=\\cos(180^\\circ-60^\\circ)=-\\cos 60^\\circ=-\\dfrac12$。',
          },
          {
            id: 'u3-l3-q6',
            type: 'choice',
            prompt: '$\\tan 225^\\circ=?$',
            options: ['$-1$', '$1$', '$\\sqrt3$', '$0$'],
            answer: 1,
            explain: '$225^\\circ=180^\\circ+45^\\circ$，第三象限 $\\tan>0$，$\\tan225^\\circ=\\tan45^\\circ=1$。',
          },
        ],
      },
    ],
  },
]
