export const LESSONS = [
  {
    id: 'u14c3',
    title: '几何最值：将军饮马、胡不归、阿氏圆',
    subtitle: '对称换段、相似换段、共线最短——三把钥匙开三扇门',
    intro: [
      {
        title: '几何最值的核心思想',
        body: '求"动点 P 到两定点距离之和 PA + PB 的最小值"，关键词是"两点之间线段最短"。若 A、B 在直线 l 同侧，直接连 AB 并不过 l，无法利用；若先把 A 关于 l 作对称点 A\'，则对 l 上任意 P 都有 PA = PA\'，从而 PA + PB = PA\' + PB ≥ A\'B，当 A\'、P、B 共线时取等号。这就是将军饮马的全部奥秘。',
        image: 'model-junjun-yinma.svg',
        imageCaption: '将军饮马：A 关于直线 l 的对称点 A\'，连 A\'B 交 l 于 P，此时 PA + PB 最小，最小值 = |A\'B|',
        formula: 'PA + PB = PA\' + PB \\ge |A\'B|，\\text{等号在 }A\'、P、B\\text{ 共线时成立}',
        tip: '口诀：对称换段，共线最短。每次见到"两段距离和最小 + P 在直线上"，立刻想：把哪段换成对称？',
      },
      {
        title: '将军饮马：经典步骤',
        body: '步骤一：判断 A、B 是否在直线 l 的同侧。若同侧，进入对称流程；若异侧，直接连 AB 与 l 的交点就是答案。\n步骤二：作 A 关于 l 的对称点 A\'（可作垂线定位）。\n步骤三：连 A\'B，与 l 交于点 P。\n步骤四：PA + PB 的最小值 = |A\'B|（用坐标或勾股算出）。\n常见变形：P 在折线上（两段路程求最短）、三角形边上的 P 与两顶点的距离和。',
        formula: '|A\'B| = \\sqrt{(x_{A\'}-x_B)^2+(y_{A\'}-y_B)^2}',
        tip: '作对称点时，先过 A 向 l 作垂线，垂足为 H，则 A\' = 2H - A（H 是 A 与 A\' 的中点）。坐标系下可直接算。',
      },
      {
        title: '胡不归：带系数 k 的距离之和',
        body: '若目标是 PA + k·PB（0 < k < 1）最小，k·PB 不能直接当"第二段距离"。妙招：在 B 处作射线 l\'，使 l\' 与 l 的夹角 α 满足 sin α = k。过任意 P 作 l\' 的垂线 PH，则 PH = PB·sin α = k·PB。\n于是 PA + k·PB = PA + PH，这是"A 到 P 再到垂线 l\'"的折线，当 A 直接向 l\' 作垂线时折线最短。\n最小值 = 点 A 到射线 l\' 的距离。',
        image: 'model-hubugui.svg',
        imageCaption: '胡不归：在 B 处作与 BC 成角 α（sin α = k）的射线 l\'，过 P 作 l\' 的垂线 PH，则 k·PB = PH',
        formula: 'PA + k\\cdot PB = PA + PH \\ge \\text{点}A\\text{到}l\'\\text{的距离}，\\quad \\sin\\alpha = k',
        tip: '见到 (1/2)PB、(√3/2)PB、(√2/2)PB 等带系数的距离——先想"这个系数是哪个角的正弦"，sin 30° = 1/2，sin 60° = √3/2，sin 45° = √2/2。',
      },
      {
        title: '阿氏圆：P 在圆上的距离最值',
        body: '若 P 在圆 ⊙O（半径 r）上，要求 PA + k·PB 的最小值（B 在圆内、A 在圆外），用"反演"构造：在射线 OB 上取 B\'，使 OB·OB\' = r²（B\' 称为 B 关于 ⊙O 的反演点）。\n可以证明对圆上任意 P，△OPB\' ∼ △OBP（SAS 相似），相似比 r/OB，故 PB\'/PB = r/OB = k（若 k 恰为 r/OB）。\n于是 PA + k·PB = PA + PB\' ≥ |AB\'|，当 A、P、B\' 共线时取等。\n最小值 = |AB\'| = OA - OB\'（若 A、B\' 在同一射线上）。',
        image: 'model-aposhi-circle.svg',
        imageCaption: '阿氏圆：B\' 是 B 关于 ⊙O 的反演点（OB·OB\' = r²），PB\' = k·PB，原问题化为 PA + PB\' ≥ AB\'',
        formula: 'OB \\cdot OB\' = r^2 \\Rightarrow \\frac{PB\'}{PB} = \\frac{r}{OB} = k，\\quad PA + k\\cdot PB \\ge |AB\'|',
        tip: '反演点 B\' 的位置：B\' 在射线 OB 上，且 OB\' = r²/OB。若 OB = 4，r = 2，则 OB\' = 4/4 = 1（B\' 在圆内）。',
      },
      {
        title: '三大模型识别总览',
        body: '将军饮马：PA + PB 最小，P 在直线上，A、B 同侧 → 对称 A 得 A\'，最小值 = |A\'B|。\n胡不归：PA + k·PB 最小（0 < k < 1），P 在直线上 → 在 B 处作与直线成 arcsin(k) 角的射线，A 到射线的距离即最小值。\n阿氏圆：P 在圆上，PA + k·PB 或 PA/PB = k → 反演构造 B\'，最小值 = |AB\'|。\n通用口诀：对称换段、相似换段、共线最短。',
        formula: '\\text{将军饮马}\\colon |A\'B|；\\quad \\text{胡不归}\\colon d(A, l\')；\\quad \\text{阿氏圆}\\colon |AB\'|',
        tip: '做题时先判断"P 在直线上还是圆上""系数是 1 还是其他"，两问定模型，再套步骤。',
      },
      {
        title: '例题精析：正方形 + 将军饮马',
        body: '正方形 ABCD 边长 4，E 是 AB 中点，P 是对角线 BD 上的动点，求 PA + PE 的最小值。\n关键观察：在正方形中，A 关于对角线 BD 的对称点恰好是 C（BD 是 AC 的中垂线）。\n故 PA = PC，PA + PE = PC + PE ≥ CE，当 P、C、E 共线时取等。\n在直角三角形 CBE 中：CB = 4，BE = 2，CE = √(16 + 4) = 2√5。\n答：PA + PE 的最小值为 2√5。',
        image: 'ex-p10-03-1.svg',
        imageCaption: '正方形 ABCD 中 A 关于 BD 的对称点是 C，PA + PE = PC + PE 在 C、P、E 共线时取最小值 CE = 2√5',
        reveal: {
          q: '等边 △ABC 边长 6，D 是 AB 中点，P 是 BC 上的动点，求 PA + PD 的最小值。（提示：作 A 关于 BC 的对称点 A\'）',
          a: 'A 关于 BC 的对称点 A\'：在等边三角形中，A 到 BC 的距离 h = 3√3，A\' 在 BC 另一侧距 h = 3√3 处。BD = 3，D 在 AB 上。用坐标：B(0,0), C(6,0), A(3, 3√3)，A\'(3, -3√3)，D(3/2, 3√3/2)……此题实际最简做法：A\' 关于 BC 对称后，PA + PD = PA\' + PD ≥ A\'D，A\'D = √((3 - 3/2)² + (3√3 + 3√3/2)²) = √((3/2)² + (9√3/2)²) = √(9/4 + 243/4) = √(252/4) = 3√7。',
        },
      },
      {
        title: '例题精析：阿氏圆反演',
        body: '⊙O 半径 r = 2，A 在圆外 OA = 5，B 在线段 OA 上 OB = 4，P 在 ⊙O 上动。求 PA + (1/2)PB 的最小值。\n系数 k = 1/2，OB = 4，r = 2，k = r/OB = 2/4 = 1/2（正好匹配反演比）。\n取反演点 B\'：OB\' = r²/OB = 4/4 = 1（B\' 在圆内，距 O 为 1）。\n对任意 P ∈ ⊙O，△OB\'P ∼ △OPB，PB\'/PB = OB\'/OP = 1/2，即 PB\' = (1/2)PB。\nPA + (1/2)PB = PA + PB\' ≥ |AB\'| = OA - OB\' = 5 - 1 = 4。\n答：最小值 = 4。',
        image: 'ex-p10-03-3.svg',
        imageCaption: '阿氏圆：OB\' = r²/OB = 1，PB\' = (1/2)PB，PA + PB\' ≥ |AB\'| = 4',
        tip: '检查 k = r/OB 是否成立是反演法能否适用的前提。若 k ≠ r/OB，可能需要用 k 构造"另一侧的反演"（OB·OB\' = r² 但相似比换一种）。',
      },
    ],
    questions: [
      {
        type: 'choice',
        prompt: '直线 l 两侧各有定点 A、B，P 在 l 上动，则 PA + PB 最小值在哪一点 P 取得？',
        options: ['A 在 l 上的投影处', 'AB 与 l 的交点处', 'A 关于 l 的对称点 A\' 与 B 的连线和 l 的交点处', 'l 的中点处'],
        answer: 1,
        explain: '若 A、B 在 l 异侧，直接连 AB，交 l 于 P，即为最优点。此时 PA + PB = AB 为最小值。选项 B 就是这个答案（"AB 与 l 的交点处"）。',
      },
      {
        type: 'judge',
        prompt: '将军饮马中，若 A、B 在直线 l 同侧，则 PA + PB 的最小值等于 |AB|。',
        answer: false,
        explain: '若 A、B 同侧，最小值不是 |AB| 而是 |A\'B|（A 的对称点 A\' 到 B 的距离）。|A\'B| ≤ |AB| 不成立，实际上 |A\'B| 通常小于 |AB|（经过对称"拉直"路径）。',
      },
      {
        type: 'input',
        prompt: '正方形 ABCD 边长 4，E 是 AB 中点，P 在对角线 BD 上。PA + PE 的最小值是 2 乘以 √5。请填写 2√5 中的 5。（填整数）',
        accept: ['5'],
        explain: 'A 关于 BD 的对称点是 C（正方形对角线互相垂直平分且 BD 是 AC 的中垂线），PA = PC，最小值 = CE = √(CB² + BE²) = √(16+4) = 2√5，故括号内为 5。',
      },
      {
        type: 'choice',
        prompt: '目标 PA + (1/2)·PB 最小（P 在直线上），系数 1/2 对应的角度 α（满足 sin α = 1/2）是（  ）。',
        options: ['15°', '30°', '45°', '60°'],
        answer: 1,
        explain: 'sin 30° = 1/2，所以在 B 处作与 l 成 30° 角的射线 l\'，过 P 向 l\' 的垂线长 = (1/2)PB，从而转化为胡不归模型。',
      },
      {
        type: 'match',
        prompt: '将几何最值模型与其关键技巧配对。',
        left: ['将军饮马', '胡不归', '阿氏圆'],
        right: ['作 A 关于直线的对称点 A\'', '在 B 处作 sin α = k 的射线', '反演构造 B\'，使 PB\' = k·PB'],
        explain: '将军饮马 → 作 A 关于直线的对称点 A\'；胡不归 → 在 B 处作 sin α = k 的射线；阿氏圆 → 反演构造 B\'，使 PB\' = k·PB。',
      },
      {
        type: 'choice',
        prompt: '⊙O 半径 r = 3，B 在 O 到 A 的射线上且 OB = 1，P 在 ⊙O 上动，要把 3·PB 转化为 PB\'（反演），则 OB\' = ？',
        options: ['1', '3', '9', '1/3'],
        answer: 2,
        explain: 'OB·OB\' = r²，OB = 1，r = 3，故 OB\' = 9/1 = 9。B\' 在 O 的射线上距 O 为 9（在圆外）。相似比 OB\'/OP = 9/3 = 3，故 PB\' = 3·PB。',
      },
      {
        type: 'judge',
        prompt: '胡不归模型中，若系数 k = √3/2，则在 B 处作与 l 成 60° 角的射线（因为 sin 60° = √3/2），这个说法正确。',
        answer: true,
        explain: 'sin 60° = √3/2，与系数匹配，所以在 B 处作与直线 l 成 60° 角的射线 l\'，过 P 向 l\' 的垂线长 = (√3/2)·PB，将 k·PB 转化为点到直线的距离。',
      },
      {
        type: 'input',
        prompt: '△ABC 中 ∠B = 30°，AB = 6，P 在 BC 上，求 PA + (1/2)PB 的最小值。（提示：sin 30° = 1/2，射线 l\' 恰好平行于 BA 且过 B，A 到 l\' 的垂距 = AB·sin 60°）该最小值是多少？（填 3√3 中的 3，即填"3"）',
        accept: ['3'],
        explain: '系数 1/2 = sin 30°，在 B 处作射线 l\' 与 BC 成 30°（另一侧），过 A 向 l\' 作垂线，垂距 = AB·sin 60° = 6·(√3/2) = 3√3，故最小值 = 3√3，其中系数为 3。',
      },
    ],
  },
]
