export const LESSONS = [
  {
    id: 'u2c5',
    title: '平行线的性质',
    subtitle: '从两直线平行推出角的关系',
    intro: [
      {
        title: '性质与判定的方向相反',
        body: '上一章"判定"研究的是：角的关系 $\\Rightarrow$ 两直线平行（由数到形）。\n\n本章"性质"研究的是：**两直线平行 $\\Rightarrow$ 角的关系**（由形到数）。\n\n**口诀**：**判定是"造平行"，性质是"用平行"**。\n\n做题第一步：看清题目给的条件——若要**证两直线平行**，用判定；若题目**已经给出平行**，问角的大小，用性质。两者方向相反，绝不能混用。',
        image: 'thm-parallel-properties.svg',
        imageCaption: '三种平行性质：$a \\parallel b$ 推出同位角相等 / 内错角相等 / 同旁内角互补',
      },
      {
        title: '三大性质定理',
        body: '设直线 $l_1 \\parallel l_2$，被第三条直线 $l_3$ 所截，则：',
        steps: [
          '**性质 1（同位角）**：两直线平行，**同位角相等**',
          '**性质 2（内错角）**：两直线平行，**内错角相等**',
          '**性质 3（同旁内角）**：两直线平行，**同旁内角互补**（和为 $180^\\circ$）',
        ],
        formula: 'l_1 \\parallel l_2 \\;\\Rightarrow\\; \\angle 1 = \\angle 2 \\;\\text{（同位角）}',
        tip: '性质 3 的同旁内角是**互补**（$\\angle 1 + \\angle 2 = 180^\\circ$），不是相等！这是最容易混淆的地方。',
      },
      {
        title: '由性质 1 推出性质 2 和性质 3',
        body: '性质 1 在初中体系中作为基本事实直接由平行公理给出，性质 2、3 由性质 1 推出。\n\n**推出性质 2（内错角相等）**：\n取内错角 $\\angle 1$（在 $l_2$ 侧）与 $\\angle 2$（在 $l_1$ 侧）。$\\angle 1$ 的对顶角 $\\angle 3$ 与 $\\angle 2$ 是同位角，由性质 1 得 $\\angle 3 = \\angle 2$；又 $\\angle 1 = \\angle 3$（对顶角），故 $\\angle 1 = \\angle 2$。\n\n**推出性质 3（同旁内角互补）**：\n取同旁内角 $\\angle 1$（在 $l_2$ 侧）与 $\\angle 4$（在 $l_1$ 侧）。$\\angle 4$ 的邻补角 $\\angle 2$ 与 $\\angle 1$ 是同位角，由性质 1 得 $\\angle 1 = \\angle 2$；又 $\\angle 2 + \\angle 4 = 180^\\circ$（邻补角），代入得 $\\angle 1 + \\angle 4 = 180^\\circ$。',
        tip: '推理链：对顶角 + 性质 1 = 性质 2；邻补角 + 性质 1 = 性质 3。所有性质都建立在性质 1 之上。',
      },
      {
        title: '判定 vs 性质 对比表',
        body: '下面一张表把判定与性质的方向区别说清楚：\n\n| 名称 | 已知 | 结论 |\n|---|---|---|\n| **判定** | 角的关系（相等 / 互补） | 两直线平行 |\n| **性质** | 两直线平行 | 角的关系（相等 / 互补） |\n\n两者的逻辑箭头方向完全相反：\n- 判定："角 $\\Rightarrow$ 平行"\n- 性质："平行 $\\Rightarrow$ 角"',
        tip: '做题时，先看题目给了什么（条件），问的是什么（结论），再决定用判定还是性质。',
      },
      {
        title: '例 1：折线问题——过折点作平行辅助线',
        body: '已知 $AB \\parallel CD$，$P$ 是 $AB$ 与 $CD$ 之间的一点（折点），求证：\n$\\angle APC = \\angle BAP + \\angle DCP.$',
        image: 'ex-p2-05-1.svg',
        imageCaption: '例 1 折线问题：过 $P$ 作 $PE \\parallel AB$，把 $\\angle APC$ 拆成两个内错角之和',
        steps: [
          '过 $P$ 作辅助线 $PE \\parallel AB$（平行辅助线套路）',
          '因 $PE \\parallel AB$，由性质 2（内错角相等）：$\\angle BAP = \\angle APE$',
          '因 $AB \\parallel CD$ 且 $PE \\parallel AB$，由平行传递性：$PE \\parallel CD$',
          '因 $PE \\parallel CD$，由性质 2（内错角相等）：$\\angle DCP = \\angle CPE$',
          '两式相加：$\\angle BAP + \\angle DCP = \\angle APE + \\angle CPE = \\angle APC$。证毕。',
        ],
        tip: '"平行线之间有折点/拐角" → 第一反应：**过折点作平行辅助线**，把大角拆成两个内错角之和。这是平行线最经典的辅助线套路。',
      },
      {
        title: '例 2：平行线 + 角平分线',
        body: '已知 $AB \\parallel CD$，$AE$ 平分 $\\angle BAC$，$CE$ 平分 $\\angle ACD$，求证：$AE \\perp CE$。',
        steps: [
          '由 $AB \\parallel CD$，$AC$ 是截线，$\\angle BAC$ 与 $\\angle ACD$ 是同旁内角',
          '由性质 3（同旁内角互补）：$\\angle BAC + \\angle ACD = 180^\\circ$',
          '两边除以 2：$\\frac{1}{2}\\angle BAC + \\frac{1}{2}\\angle ACD = 90^\\circ$',
          '因 $AE$ 平分 $\\angle BAC$：$\\angle EAC = \\frac{1}{2}\\angle BAC$；$CE$ 平分 $\\angle ACD$：$\\angle ECA = \\frac{1}{2}\\angle ACD$',
          '故 $\\angle EAC + \\angle ECA = 90^\\circ$；在 $\\triangle AEC$ 中，$\\angle AEC = 180^\\circ - 90^\\circ = 90^\\circ$，故 $AE \\perp CE$。证毕。',
        ],
      },
      {
        title: '例 3：三角形内角和的平行线证明',
        body: '用平行线性质证明 $\\triangle ABC$ 三内角之和为 $180^\\circ$。',
        image: 'ex-p2-05-3.svg',
        imageCaption: '例 3 三角形内角和：过 $A$ 作 $BC$ 的平行线，三角拼成平角',
        steps: [
          '过顶点 $A$ 作直线 $l \\parallel BC$',
          '以 $AB$ 为截线，$l$ 与 $BC$ 平行，由内错角相等（性质 2）：$l$ 在 $A$ 左侧的角 $= \\angle B$',
          '以 $AC$ 为截线，$l$ 与 $BC$ 平行，由内错角相等（性质 2）：$l$ 在 $A$ 右侧的角 $= \\angle C$',
          '三角（$\\angle B$ 对应部分、$\\angle A$、$\\angle C$ 对应部分）恰好组成直线 $l$ 上的一个平角',
          '故 $\\angle A + \\angle B + \\angle C = 180^\\circ$。证毕。',
        ],
        tip: '"过三角形顶点作对边的平行线"是几何中最重要的辅助线之一，在三角形一章还会反复使用。',
      },
      {
        title: '易错点总结',
        body: '关于平行线性质，以下几点最高频：\n\n1. **方向不能反**：性质的前提是"两直线已经平行"，不能用性质去"证平行"——那是判定的事。\n2. **辅助线套路**："平行线之间的折点/拐角" → 过折点作平行辅助线，把折角拆成两个内错角之和。\n3. **同旁内角是互补不是相等**：性质 3 是 $\\angle 1 + \\angle 2 = 180^\\circ$，不是 $\\angle 1 = \\angle 2$！\n4. **两平行线间距离处处相等**：这一推论要求量的是**垂线段**的长度，斜线段不等。',
        reveal: {
          q: '已知 $AB \\parallel CD$，$\\angle BAP = 40^\\circ$，$\\angle DCP = 30^\\circ$，求 $\\angle APC$。',
          a: '过 $P$ 作 $PE \\parallel AB$，由内错角：$\\angle APE = \\angle BAP = 40^\\circ$；$PE \\parallel CD$，由内错角：$\\angle CPE = \\angle DCP = 30^\\circ$；故 $\\angle APC = \\angle APE + \\angle CPE = 40^\\circ + 30^\\circ = 70^\\circ$。',
        },
      },
    ],
    questions: [
      {
        id: 'u2c5q1',
        type: 'choice',
        prompt: '已知 $l_1 \\parallel l_2$，截线 $l_3$ 与它们所截得的内错角 $\\angle 1, \\angle 2$，则 $\\angle 1$ 与 $\\angle 2$ 的关系是？',
        options: ['$\\angle 1 + \\angle 2 = 180^\\circ$', '$\\angle 1 = \\angle 2$', '$\\angle 1 > \\angle 2$', '无法确定'],
        answer: 1,
        explain: '由性质 2（两直线平行，内错角相等）：$l_1 \\parallel l_2 \\Rightarrow \\angle 1 = \\angle 2$。',
      },
      {
        id: 'u2c5q2',
        type: 'judge',
        prompt: '已知 $AB \\parallel CD$，截线所截同旁内角 $\\angle 1 = \\angle 2$。',
        answer: false,
        explain: '由性质 3（两直线平行，同旁内角**互补**）：$AB \\parallel CD \\Rightarrow \\angle 1 + \\angle 2 = 180^\\circ$。同旁内角是互补（和为 $180^\\circ$）而不是相等（除非都是 $90^\\circ$）。',
      },
      {
        id: 'u2c5q3',
        type: 'input',
        prompt: '已知 $AB \\parallel CD$，截线 $EF$ 与 $AB$ 交于 $G$，与 $CD$ 交于 $H$，$\\angle AGE = 65^\\circ$。求同位角 $\\angle GHD$ 的度数（单位：度）。',
        accept: ['65', '65°', '65度'],
        explain: '$\\angle AGE$ 与 $\\angle GHD$ 是截线 $EF$ 所截 $AB \\parallel CD$ 形成的同位角（都在 $EF$ 右侧，分别在 $AB, CD$ 上方）。由性质 1（两直线平行，同位角相等）：$\\angle GHD = \\angle AGE = 65^\\circ$。',
      },
      {
        id: 'u2c5q4',
        type: 'input',
        prompt: '已知 $l_1 \\parallel l_2$，截线所截一对同旁内角之差为 $40^\\circ$，则这对同旁内角中较大的角是多少度？',
        accept: ['110', '110°', '110度'],
        explain: '设两角为 $x$ 和 $x - 40^\\circ$（$x$ 较大）。由性质 3（同旁内角互补）：$x + (x - 40^\\circ) = 180^\\circ$，解得 $2x = 220^\\circ$，$x = 110^\\circ$，较大角为 $110^\\circ$。',
      },
      {
        id: 'u2c5q5',
        type: 'choice',
        prompt: '已知 $AB \\parallel CD$，$P$ 在两线之间，$\\angle BAP = 40^\\circ$，$\\angle DCP = 30^\\circ$，则 $\\angle APC = $？',
        options: ['$60^\\circ$', '$70^\\circ$', '$80^\\circ$', '$110^\\circ$'],
        answer: 1,
        explain: '过 $P$ 作 $PE \\parallel AB$，则 $PE \\parallel CD$（平行传递）。\n由内错角（$PE \\parallel AB$）：$\\angle APE = \\angle BAP = 40^\\circ$。\n由内错角（$PE \\parallel CD$）：$\\angle CPE = \\angle DCP = 30^\\circ$。\n故 $\\angle APC = \\angle APE + \\angle CPE = 40^\\circ + 30^\\circ = 70^\\circ$。',
      },
      {
        id: 'u2c5q6',
        type: 'judge',
        prompt: '可以用"两直线平行，同位角相等"来证明两直线平行。',
        answer: false,
        explain: '性质的方向是"已知平行 $\\Rightarrow$ 角的关系"，而证两直线平行要用**判定**（"角的关系 $\\Rightarrow$ 平行"）。用性质去证平行是逻辑循环，是错误的。',
      },
      {
        id: 'u2c5q7',
        type: 'choice',
        prompt: '在 $\\triangle ABC$ 中，过 $A$ 作 $BC$ 的平行线 $l$，$\\angle B = 50^\\circ$，$\\angle C = 70^\\circ$，则 $\\angle BAC = $？',
        options: ['$50^\\circ$', '$60^\\circ$', '$70^\\circ$', '$120^\\circ$'],
        answer: 1,
        explain: '过 $A$ 作 $l \\parallel BC$。由内错角相等（$l \\parallel BC$，以 $AB$ 为截线）：$l$ 在 $A$ 左侧的角 $= \\angle B = 50^\\circ$；由内错角相等（以 $AC$ 为截线）：$l$ 在 $A$ 右侧的角 $= \\angle C = 70^\\circ$。三角拼成平角：$\\angle BAC = 180^\\circ - 50^\\circ - 70^\\circ = 60^\\circ$。',
      },
      {
        id: 'u2c5q8',
        type: 'match',
        prompt: '将平行线性质与对应的角关系配对。',
        left: ['性质 1（同位角）', '性质 2（内错角）', '性质 3（同旁内角）', '折线辅助线套路'],
        right: ['两角相等', '两角相等', '两角之和为 $180^\\circ$', '过折点作平行辅助线拆分折角'],
        explain: '性质 1（同位角相等）和性质 2（内错角相等）都是"两角相等"；性质 3（同旁内角互补）是"两角之和 $180^\\circ$"；处理折线夹在两平行线之间的典型辅助线是过折点作平行线，把折角拆成两个内错角之和。',
      },
    ],
  },
]
