export const LESSONS = [
  {
    id: 'u3c2',
    title: '三角形内角和与外角',
    subtitle: '内角和恒为 180°，外角等于不相邻两内角之和',
    intro: [
      {
        title: '从直觉到定理：内角和为什么是 180°？',
        body: '把一张纸剪成三角形，再把三个角撕下来拼在一起，你会发现它们恰好拼成一条直线——即 $180^\\circ$。\n\n**无论三角形的形状如何**（锐角、钝角、直角），这个结论始终成立。这不是巧合，而是一个可以严格证明的定理。',
        tip: '内角和 $= 180^\\circ$ 这个结论依赖于**平行公理**（过一点有且仅有一条直线与已知直线平行）；在非欧几何中，三角形内角和并不等于 $180^\\circ$。',
      },
      {
        title: '内角和定理的证明',
        body: '**证明思路**：在 $\\triangle ABC$ 中，过顶点 $A$ 作直线 $l \\parallel BC$。\n\n- 直线 $AB$ 截 $l$ 与 $BC$，由**内错角相等**得：$\\angle 1 = \\angle B$；\n- 直线 $AC$ 截 $l$ 与 $BC$，由**内错角相等**得：$\\angle 2 = \\angle C$；\n- $\\angle 1, \\angle BAC, \\angle 2$ 三角共顶点 $A$，恰好拼成直线 $l$ 上的平角：\n\n$\\angle 1 + \\angle BAC + \\angle 2 = 180^\\circ.$\n\n将 $\\angle 1 = \\angle B$、$\\angle 2 = \\angle C$ 代入，即得 $\\angle A + \\angle B + \\angle C = 180^\\circ$。',
        image: 'thm-angle-sum-proof.svg',
        imageCaption: '内角和定理证明：过 $A$ 作 $BC$ 的平行线 $l$，三个角拼成一个平角',
        formula: '\\angle A + \\angle B + \\angle C = 180^\\circ',
        steps: [
          '过 $A$ 作 $l \\parallel BC$',
          '$AB$ 为截线，内错角相等：$\\angle 1 = \\angle B$',
          '$AC$ 为截线，内错角相等：$\\angle 2 = \\angle C$',
          '$\\angle 1 + \\angle A + \\angle 2$ 拼成平角 $180^\\circ$',
          '代入得 $\\angle A + \\angle B + \\angle C = 180^\\circ$',
        ],
      },
      {
        title: '外角的定义',
        body: '把三角形的某一条边向**外延长**，延长线与相邻的另一边所组成的角，叫做这个三角形的**外角**。\n\n例如，在 $\\triangle ABC$ 中把 $BC$ 延长到 $D$，则 $\\angle ACD$ 是顶点 $C$ 处的一个外角。\n\n**注意**：\n- 每个顶点处各有**两个外角**（互为对顶角，度数相等），通常每顶点只算一个外角；\n- 外角必须由**延长一边**形成，不是任意从顶点往外作的角。',
        image: 'thm-exterior-angle.svg',
        imageCaption: '$BC$ 延长到 $D$，$\\angle ACD$ 是顶点 $C$ 处的外角',
      },
      {
        title: '外角定理及其推论',
        body: '**外角定理**：三角形的一个外角，等于与它**不相邻**的两个内角之和。\n\n即：$\\angle ACD = \\angle A + \\angle B$。\n\n**推论**：三角形的一个外角**大于**任意一个与它不相邻的内角：\n\n$\\angle ACD > \\angle A, \\qquad \\angle ACD > \\angle B.$\n\n**证明**：由"外角 + 相邻内角 = 平角"得 $\\angle ACD = 180^\\circ - \\angle C$；由内角和定理 $\\angle C = 180^\\circ - \\angle A - \\angle B$，代入得 $\\angle ACD = \\angle A + \\angle B$。由 $\\angle A, \\angle B > 0^\\circ$，推论立得。',
        formula: '\\angle ACD = \\angle A + \\angle B',
        tip: '**"不相邻"很关键**：外角等于与它**不相邻**的两个内角之和；相邻的那个内角与外角是互补关系（$180^\\circ$），不是相等关系。',
      },
      {
        title: '例 1：已知两角求其余各角',
        body: '在 $\\triangle ABC$ 中，$\\angle A = 40^\\circ$，$\\angle B = 70^\\circ$，求 $\\angle C$ 及三个顶点处各一个外角的度数。\n\n**解**：由内角和定理：\n$\\angle C = 180^\\circ - 40^\\circ - 70^\\circ = 70^\\circ.$\n\n由外角定理（外角 = 不相邻两内角之和）：\n- 顶点 $A$ 处外角 $= \\angle B + \\angle C = 70^\\circ + 70^\\circ = 140^\\circ$；\n- 顶点 $B$ 处外角 $= \\angle A + \\angle C = 40^\\circ + 70^\\circ = 110^\\circ$；\n- 顶点 $C$ 处外角 $= \\angle A + \\angle B = 40^\\circ + 70^\\circ = 110^\\circ$。',
        steps: [
          '用内角和定理先求出 $\\angle C$',
          '外角 = 不相邻两内角之和，逐顶点套用外角定理',
          '验证：三个外角之和 $= 140^\\circ + 110^\\circ + 110^\\circ = 360^\\circ$（多边形外角和）',
        ],
      },
      {
        title: '例 2：角平分线结论——内心角公式',
        body: '在 $\\triangle ABC$ 中，$BI, CI$ 分别平分 $\\angle ABC$ 和 $\\angle ACB$，交于点 $I$。\n\n求证：$\\angle BIC = 90^\\circ + \\dfrac{1}{2}\\angle A$。\n\n**证明**：在 $\\triangle BIC$ 中，由内角和定理：\n$\\angle BIC = 180^\\circ - \\angle IBC - \\angle ICB.$\n\n因 $BI$ 平分 $\\angle B$，$\\angle IBC = \\tfrac{1}{2}\\angle B$；同理 $\\angle ICB = \\tfrac{1}{2}\\angle C$。代入得\n$\\angle BIC = 180^\\circ - \\tfrac{1}{2}(\\angle B + \\angle C).$\n\n由 $\\angle B + \\angle C = 180^\\circ - \\angle A$，得\n$\\angle BIC = 180^\\circ - \\tfrac{1}{2}(180^\\circ - \\angle A) = 90^\\circ + \\tfrac{1}{2}\\angle A.$',
        image: 'ex-p3b-02-3.svg',
        imageCaption: '三角形内心：$BI, CI$ 是角平分线，$\\angle BIC = 90^\\circ + \\frac{1}{2}\\angle A$',
        formula: '\\angle BIC = 90^\\circ + \\dfrac{1}{2}\\angle A',
        reveal: {
          q: '若 $\\angle A = 60^\\circ$，利用内心角公式，$\\angle BIC$ 等于多少度？',
          a: '$\\angle BIC = 90^\\circ + \\tfrac{1}{2} \\times 60^\\circ = 90^\\circ + 30^\\circ = 120^\\circ$。',
        },
      },
      {
        title: '易错点总结',
        body: '内角和与外角相关的常见错误：\n\n1. **外角必须由"延长一边"形成**，不是从顶点任意画出去的角。\n2. **每个顶点有两个外角，但度数相同**（互为对顶角），通常每顶点只计一个。\n3. **外角定理要求"不相邻"**：外角 = 两个不相邻内角之和；与外角相邻的内角是互补关系，不是相等。\n4. **推论是"大于"不是"等于"**：外角 > 任一不相邻内角，切勿写成相等。\n5. **内角和定理的证明依赖作平行线这一步**，不可省略。',
      },
      {
        title: '五角星的五个尖角之和',
        body: '**例 3**：五角星的五个尖角之和等于多少度？\n\n**结论**：$\\angle A_1 + \\angle A_2 + \\angle A_3 + \\angle A_4 + \\angle A_5 = 180^\\circ$。\n\n**思路**：以每个尖角所在的小三角形为基础，对每个小三角形用内角和定理，再注意中央五边形五个顶点处的角正好被计入，利用"五边形内角和 $= (5-2) \\times 180^\\circ = 540^\\circ$"整体求和，扣除后恰好剩 $180^\\circ$。',
        image: 'ex-p3b-02-2.svg',
        imageCaption: '五角星：五个尖角 $\\angle A_1, \\ldots, \\angle A_5$ 之和为 $180^\\circ$',
        tip: '这道题常见于竞赛与中考压轴，关键是把外角定理或内角和定理在多个三角形上联合使用。',
      },
    ],
    questions: [
      {
        id: 'u3c2q1',
        type: 'choice',
        prompt: '$\\triangle ABC$ 中，$\\angle A : \\angle B : \\angle C = 2 : 3 : 4$，则 $\\angle B$ 等于多少度？',
        options: ['$40^\\circ$', '$60^\\circ$', '$70^\\circ$', '$80^\\circ$'],
        answer: 1,
        explain: '设 $\\angle A = 2k, \\angle B = 3k, \\angle C = 4k$。由内角和定理：\n$2k + 3k + 4k = 180^\\circ \\Rightarrow 9k = 180^\\circ \\Rightarrow k = 20^\\circ$。\n故 $\\angle B = 3k = 60^\\circ$。',
      },
      {
        id: 'u3c2q2',
        type: 'judge',
        prompt: '三角形的一个外角，一定大于三角形的任意一个内角。',
        answer: false,
        explain: '外角定理推论只说"外角大于**与它不相邻**的两个内角"，而与外角**相邻**的那个内角和外角是互补关系（外角 + 相邻内角 $= 180^\\circ$）。\n若相邻内角为 $10^\\circ$，外角为 $170^\\circ$，此时外角确实大于所有内角；但结论只严格保证大于**不相邻**的两个。\n此题说"任意一个内角"包含了相邻内角，若相邻内角接近 $180^\\circ$ 则外角接近 $0^\\circ$，反而更小，故说法不严谨，判**假**。',
      },
      {
        id: 'u3c2q3',
        type: 'input',
        prompt: '$\\triangle ABC$ 中，$\\angle A = 50^\\circ$，$\\angle B$ 的外角为 $130^\\circ$，求 $\\angle C$ 的度数（填数字）。',
        accept: ['80', '80°', '80度'],
        explain: '$\\angle B$ 处的外角与 $\\angle A, \\angle C$ 不相邻，由外角定理：\n$130^\\circ = \\angle A + \\angle C = 50^\\circ + \\angle C$，\n故 $\\angle C = 80^\\circ$。\n\n验证：$\\angle B = 180^\\circ - 130^\\circ = 50^\\circ$，$\\angle A + \\angle B + \\angle C = 50^\\circ + 50^\\circ + 80^\\circ = 180^\\circ$，正确。',
      },
      {
        id: 'u3c2q4',
        type: 'choice',
        prompt: '$\\triangle ABC$ 中，$\\angle A = 50^\\circ$，$\\angle B = 60^\\circ$，把 $BC$ 延长到 $D$，则 $\\angle ACD = ?$',
        options: ['$70^\\circ$', '$110^\\circ$', '$120^\\circ$', '$130^\\circ$'],
        answer: 1,
        explain: '方法一（外角定理）：$\\angle ACD = \\angle A + \\angle B = 50^\\circ + 60^\\circ = 110^\\circ$。\n方法二（内角和）：$\\angle C = 180^\\circ - 50^\\circ - 60^\\circ = 70^\\circ$，外角 $= 180^\\circ - 70^\\circ = 110^\\circ$。\n两种方法结果一致，选 $110^\\circ$。',
      },
      {
        id: 'u3c2q5',
        type: 'judge',
        prompt: '三角形任意一个外角都等于与它不相邻的两个内角之和。',
        answer: true,
        explain: '这正是**外角定理**的内容。设外角为 $\\angle ACD$，相邻内角为 $\\angle ACB$，则 $\\angle ACD + \\angle ACB = 180^\\circ$；由内角和定理 $\\angle A + \\angle B + \\angle C = 180^\\circ$，移项得 $\\angle A + \\angle B = 180^\\circ - \\angle C = \\angle ACD$。',
      },
      {
        id: 'u3c2q6',
        type: 'match',
        prompt: '将角度关系与对应的定理/推论配对。',
        left: [
          '$\\angle A + \\angle B + \\angle C = 180^\\circ$',
          '$\\angle ACD = \\angle A + \\angle B$',
          '$\\angle ACD > \\angle A$',
          '$\\angle BIC = 90^\\circ + \\tfrac{1}{2}\\angle A$',
        ],
        right: [
          '内角和定理',
          '外角定理',
          '外角推论',
          '角平分线交点（内心）角公式',
        ],
        explain: '① 内角和定理：三内角之和恒为 $180^\\circ$；② 外角定理：外角等于不相邻两内角之和；③ 外角推论：外角大于任一不相邻内角；④ 内心角公式：两条角平分线的交点处所成的角 $= 90^\\circ + \\tfrac{1}{2}\\angle A$。',
      },
      {
        id: 'u3c2q7',
        type: 'choice',
        prompt: '$\\triangle ABC$ 中，$AD$ 平分 $\\angle BAC$ 且交 $BC$ 于 $D$，$\\angle B = 70^\\circ$，$\\angle C = 30^\\circ$，则 $\\angle ADB = ?$',
        options: ['$70^\\circ$', '$80^\\circ$', '$100^\\circ$', '$110^\\circ$'],
        answer: 0,
        explain: '先求 $\\angle BAC = 180^\\circ - 70^\\circ - 30^\\circ = 80^\\circ$，故 $\\angle BAD = \\tfrac{1}{2} \\times 80^\\circ = 40^\\circ$。\n在 $\\triangle ABD$ 中，由内角和定理：$\\angle ADB = 180^\\circ - \\angle B - \\angle BAD = 180^\\circ - 70^\\circ - 40^\\circ = 70^\\circ$。\n\n也可用外角定理：$\\angle ADB$ 是 $\\triangle ACD$ 在 $D$ 处的外角，$\\angle ADB = \\angle C + \\angle DAC = 30^\\circ + 40^\\circ = 70^\\circ$。',
      },
      {
        id: 'u3c2q8',
        type: 'input',
        prompt: '$\\triangle ABC$ 中，$\\angle A = 60^\\circ$，$BI, CI$ 分别平分 $\\angle B$ 和 $\\angle C$，交于点 $I$。$\\angle BIC$ 等于多少度？',
        accept: ['120', '120°', '120度'],
        explain: '由内心角公式：$\\angle BIC = 90^\\circ + \\tfrac{1}{2}\\angle A = 90^\\circ + \\tfrac{1}{2} \\times 60^\\circ = 90^\\circ + 30^\\circ = 120^\\circ$。',
      },
    ],
  },
]
