export const LESSONS = [
  {
    id: 'u4c1',
    title: 'SSS、SAS、ASA、AAS 四大判定',
    subtitle: '三个恰当的元素，就能锁定两个三角形全等',
    intro: [
      {
        title: '全等三角形是什么？',
        body: '两个三角形如果能够**完全重合**——经过平移、旋转或翻折后可以一一叠合——就称它们**全等**。\n\n全等三角形有完全相同的形状和大小，记作\n$\\triangle ABC \\cong \\triangle DEF.$\n\n记号中**字母顺序非常关键**：它规定了对应关系 $A\\leftrightarrow D$、$B\\leftrightarrow E$、$C\\leftrightarrow F$。',
        formula: '\\triangle ABC \\cong \\triangle DEF',
        tip: '写全等记号时，对应顶点必须按顺序写，否则后续推导会完全错乱。',
      },
      {
        title: '全等的性质：对应边、对应角',
        body: '若 $\\triangle ABC \\cong \\triangle DEF$，则：\n\n- **对应边相等**：$AB = DE$，$BC = EF$，$AC = DF$；\n- **对应角相等**：$\\angle A = \\angle D$，$\\angle B = \\angle E$，$\\angle C = \\angle F$。\n\n这六个等量关系从全等记号中**直接读取**，无需额外证明——这是全等最强大的地方：一旦证得全等，六个量立刻到手。',
        tip: '"已知全等，就敢用对应边等、对应角等"——这是全等的核心用法，要形成条件反射。',
      },
      {
        title: '四大判定定理一览',
        body: '一个三角形有 6 个元素（3 条边、3 个角），判定全等只需其中**三个特定元素**对应相等。\n\n| 判定 | 内容 | 关键词 |\n|------|------|--------|\n| **SSS**（边边边）| 三边对应相等 | 三边 |\n| **SAS**（边角边）| 两边及其**夹角**对应相等 | 夹角在两边之间 |\n| **ASA**（角边角）| 两角及其**夹边**对应相等 | 夹边在两角之间 |\n| **AAS**（角角边）| 两角及其中一角的**对边**对应相等 | 边不在两角之间 |',
        image: 'thm-congruence-criteria.svg',
        imageCaption: '四大判定示意：SSS / SAS / ASA / AAS，已标记的元素是判定中相等的部分',
      },
      {
        title: 'SAS 的核心地位：夹角为什么重要？',
        body: 'SAS 通常作为公理出发点。两边及其**夹角**一旦确定，第三边就被余弦定理 $c^2 = a^2 + b^2 - 2ab\\cos C$ 唯一锁定，三角形被唯一确定。\n\n**ASA 由 SAS + 内角和定理推出**：两角相等，则第三角也相等（内角和为 $180^\\circ$），再配合夹边，形成 SAS 结构。\n\n**AAS 由 ASA + 内角和推出**：两角加对边，由内角和补出第三角，"对边"变成"另一角的夹边"，回到 ASA。\n\n**SSS 由 SAS 推出**：固定两边，夹角变化时第三边单调变化，故第三边一旦给定，夹角唯一，化归为 SAS。',
        formula: 'c^2 = a^2 + b^2 - 2ab\\cos C',
        tip: '四个判定不是独立公理，背后只有一条原则：**三个独立元素唯一确定一个三角形**。',
      },
      {
        title: 'SSA 陷阱：为什么"两边一对角"不行？',
        body: '**SSA 一般不能判定全等！**\n\n原因：已知两边 $AB = DE$、$BC = EF$ 以及 $\\angle A = \\angle D$（$\\angle A$ 是 $BC$ 的对角，不是夹角），从 $B$ 出发画半径 $BC$ 的弧，可能与 $A$ 处射线交于**两个不同的点**——一个锐角三角形和一个钝角三角形，它们都满足条件却不全等。\n\n**判断口诀**：看到"两边一角"，先判断那个角是不是两边的**夹角**。是夹角 → SAS；是对角 → 不能用 SSA，需另找条件。',
        tip: '直角三角形下的 SSA 是个例外：此时已知角恰好是 $90^\\circ$，歧义消失，升级为 HL（下一关讲）。',
      },
      {
        title: '例：等腰三角形中的全等（SAS）',
        body: '**题目**：$\\triangle ABC$ 中 $AB = AC$，$D, E$ 分别在 $AB, AC$ 上，且 $AD = AE$。连 $BE, CD$，交于 $P$。求证 $BE = CD$。\n\n**思路**：\n- 目标 $BE = CD$ → 找包含它们的两个三角形 → 选 $\\triangle ABE$ 与 $\\triangle ACD$；\n- 核对三组条件：$AB = AC$（等腰），$\\angle A = \\angle A$（**公共角**），$AE = AD$（题设）；\n- $\\angle A$ 恰好是 $AB$ 与 $AE$ 的夹角，也是 $AC$ 与 $AD$ 的夹角 → **SAS**；\n- $\\triangle ABE \\cong \\triangle ACD$ → 对应边 $BE = CD$。',
        steps: [
          '写出两组对应边：$AB = AC$（等腰），$AE = AD$（题设）',
          '写出夹角：$\\angle A = \\angle A$（公共角）',
          '验证夹角恰好在两组边之间',
          '套 SAS：$\\triangle ABE \\cong \\triangle ACD$',
          '由全等对应边：$BE = CD$',
        ],
        reveal: {
          q: '由 $\\triangle ABE \\cong \\triangle ACD$，除了 $BE = CD$，还能得到哪些等量关系？',
          a: '对应角相等：$\\angle ABE = \\angle ACD$，$\\angle AEB = \\angle ADC$；对应边：$BE = CD$。这些可以继续推出 $PB = PC$（$P$ 是 $BE$ 与 $CD$ 的交点）。',
        },
      },
      {
        title: '易错点总结',
        body: '1. **SSA 不能用**：看到"两边一角"，必须确认那个角是不是夹角。\n2. **对应顺序不能乱**：$\\triangle ABC \\cong \\triangle DEF$ 规定了 $A\\leftrightarrow D$、$B\\leftrightarrow E$、$C\\leftrightarrow F$；写反了后续推导全错。\n3. **SAS 中角必须是夹角**：$AB = A\'B\'$、$AC = A\'C\'$、$\\angle B = \\angle B\'$ 不是 SAS，因为 $\\angle B$ 不是 $AB$ 与 $AC$ 的夹角。\n4. **AAS 与 ASA 不要混**：AAS 的边是某一角的对边；ASA 的边是两角的夹边。\n5. **公共边、公共角、对顶角是"隐藏条件"**，写证明时不能省略，要明确写出来。',
        image: 'thm-congruence-criteria.svg',
        imageCaption: '对比四种判定：注意角的位置是"夹"还是"对"',
      },
    ],
    questions: [
      {
        id: 'u4c1q1',
        type: 'choice',
        prompt: '$\\triangle ABC$ 与 $\\triangle DEF$ 中，$AB = DE$，$\\angle A = \\angle D$，$AC = DF$。可以判定全等，用的是哪条定理？',
        options: ['SSS', 'SAS', 'ASA', 'AAS'],
        answer: 1,
        explain: '$\\angle A$ 是 $AB$ 与 $AC$ 的夹角，$\\angle D$ 是 $DE$ 与 $DF$ 的夹角。已知两边及其夹角对应相等，正是 **SAS**。',
      },
      {
        id: 'u4c1q2',
        type: 'judge',
        prompt: '在 $\\triangle ABC$ 与 $\\triangle DEF$ 中，若 $AB = DE$、$BC = EF$、$\\angle A = \\angle D$，则可以用 SAS 判定两三角形全等。',
        answer: false,
        explain: '这是 **SSA** 情形，不能用 SAS。SAS 要求那个角是**两边的夹角**，但 $\\angle A$ 是 $BC$ 的对角，不是 $AB$ 与 $BC$ 的夹角（夹角应是 $\\angle B$）。SSA 一般不能判定全等，存在"两解"的可能。',
      },
      {
        id: 'u4c1q3',
        type: 'choice',
        prompt: '已知 $\\triangle ABC \\cong \\triangle DEF$，$\\angle A = 40^\\circ$，$\\angle B = 70^\\circ$，$AC = 5$。则 $\\angle F$ 与 $DF$ 分别是？',
        options: [
          '$\\angle F = 70^\\circ$，$DF = 5$',
          '$\\angle F = 40^\\circ$，$DF = 5$',
          '$\\angle F = 70^\\circ$，$DF$ 未知',
          '$\\angle F = 40^\\circ$，$DF$ 未知',
        ],
        answer: 0,
        explain: '由 $\\triangle ABC \\cong \\triangle DEF$，对应关系 $A\\leftrightarrow D$、$B\\leftrightarrow E$、$C\\leftrightarrow F$。\n$\\angle C = 180^\\circ - 40^\\circ - 70^\\circ = 70^\\circ$，所以 $\\angle F = \\angle C = 70^\\circ$。\n$DF$ 对应 $AC$，故 $DF = AC = 5$。',
      },
      {
        id: 'u4c1q4',
        type: 'input',
        prompt: '四边形 $ABCD$ 中，$AB = CD$，$AD = CB$，连对角线 $AC$。利用 SSS 可以证明 $\\triangle ABC \\cong \\triangle CDA$。问 $\\angle BAC$ 与哪个角相等（填角的名称，如 $\\angle DCA$）？',
        accept: ['∠DCA', '角DCA', 'DCA', '∠ACD', '角ACD', 'ACD'],
        explain: '$\\triangle ABC \\cong \\triangle CDA$（SSS：$AB = CD$，$BC = DA$，$AC = CA$）。对应关系 $A\\leftrightarrow C$、$B\\leftrightarrow D$、$C\\leftrightarrow A$。所以 $\\angle BAC$（在 $\\triangle ABC$ 中，顶点 $A$ 处对应 $\\triangle CDA$ 中顶点 $C$ 处的角）$= \\angle DCA$。',
      },
      {
        id: 'u4c1q5',
        type: 'match',
        prompt: '将下列"已知条件"与对应的全等判定定理配对。',
        left: [
          '$AB=DE$，$BC=EF$，$CA=FD$',
          '$\\angle A=\\angle D$，$AB=DE$，$\\angle B=\\angle E$',
          '$\\angle A=\\angle D$，$\\angle B=\\angle E$，$BC=EF$',
          '$AB=DE$，$\\angle B=\\angle E$，$BC=EF$',
        ],
        right: [
          'SSS',
          'ASA（$AB$ 是两角夹边）',
          'AAS（$BC$ 是 $\\angle A$ 的对边）',
          'SAS（$\\angle B$ 是两边夹角）',
        ],
        explain: '① 三边相等 → SSS；② 两角及夹边 $AB$（在 $\\angle A$ 与 $\\angle B$ 之间）→ ASA；③ 两角及 $BC$（$BC$ 是 $\\angle A$ 的对边，不在两角之间）→ AAS；④ $\\angle B$ 在 $AB$ 与 $BC$ 之间 → SAS。',
      },
      {
        id: 'u4c1q6',
        type: 'judge',
        prompt: '两个三角形中，两角及其中一角的对边对应相等，可以用 ASA 判定全等。',
        answer: false,
        explain: '这是 **AAS** 的情形，不是 ASA。ASA 要求那条边是**两角的夹边**；AAS 的边是某一角的**对边**（不在两角之间）。两者都能判定全等，但名称和条件描述不同，不能混用。',
      },
      {
        id: 'u4c1q7',
        type: 'choice',
        prompt: '$\\triangle ABC$ 与 $\\triangle DEF$ 中，$\\angle A = \\angle D = 90^\\circ$，$\\angle B = \\angle E = 30^\\circ$，$AB = DE = 4$。用哪条定理判定全等？',
        options: ['SSS', 'SAS', 'ASA', 'AAS'],
        answer: 2,
        explain: '已知 $\\angle A = \\angle D$（两角之一），$\\angle B = \\angle E$（两角之二），$AB = DE$（$AB$ 是 $\\angle A$ 与 $\\angle B$ 的**夹边**）。两角及其夹边对应相等，用 **ASA**。',
      },
      {
        id: 'u4c1q8',
        type: 'input',
        prompt: '在 $\\triangle ABC$ 中，$\\angle A = \\angle B$，$CD$ 是 $AB$ 边上的中线（$D$ 是 $AB$ 中点）。问 $CA$ 与 $CB$ 的关系（填"相等"或"不相等"）？',
        accept: ['相等', '等', 'CA=CB', 'CA等于CB'],
        explain: '考虑 $\\triangle CAD$ 与 $\\triangle CBD$：$AD = BD$（中点），$\\angle A = \\angle B$（已知），$CD = CD$（公共边）。\n但 $\\angle A$ 是 $AD$ 与 $CA$ 的夹角，$CD$ 不是夹边……改用 AAS：$\\angle A = \\angle B$，$\\angle ADC = \\angle BDC = 90^\\circ$（不一定），换思路：\n直接在 $\\triangle CAD$ 与 $\\triangle CBD$ 中：$\\angle A = \\angle B$，$\\angle CDA = \\angle CDB$（同一个角的补角）不一定成立。\n最简洁：在 $\\triangle CAB$ 中，$\\angle A = \\angle B$ 说明 $\\triangle CAB$ 是等腰三角形，等角对等边，$CA = CB$。（不需要全等，直接用等腰三角形性质。）',
      },
      {
        id: 'u4c1q9',
        type: 'judge',
        prompt: '全等三角形的对应边相等、对应角相等，共有 6 个等量关系，其中对应角相等的 3 个关系可以直接从全等记号的顺序中读出。',
        answer: true,
        explain: '$\\triangle ABC \\cong \\triangle DEF$ 规定了 $A\\leftrightarrow D$、$B\\leftrightarrow E$、$C\\leftrightarrow F$，所以 $\\angle A = \\angle D$，$\\angle B = \\angle E$，$\\angle C = \\angle F$，确实可以直接从字母顺序读出，说法正确。',
      },
    ],
  },
]
