export const LESSONS = [
  {
    id: 'u4c2',
    title: 'HL：直角三角形专属判定',
    subtitle: '斜边 + 一条直角边，直角三角形的第五个判定',
    intro: [
      {
        title: '为什么直角三角形需要单独的判定？',
        body: '普通三角形的 SSA（两边及一非夹角）不能判定全等——从一个端点画固定长度的线段去交另一条射线，可能有**两个交点**，产生两个不同的三角形。\n\n但当已知角恰好是 $90^\\circ$ 时，情况**根本改变**：直角顶点必须垂直于另一边，方向被锁死，第三个顶点的位置由斜边长度**唯一决定**，歧义消失。\n\n这就是 **HL 判定**存在的意义：它是 SSA 在直角时的"特权版"。',
        tip: 'HL 只适用于直角三角形，绝对不能用于普通三角形。',
      },
      {
        title: 'HL 判定定理',
        body: '**HL（斜边-直角边）**：在两个直角三角形中，若**斜边**和**一条直角边**对应相等，则这两个直角三角形全等。\n\nHL 来自英文 **H**ypotenuse（斜边）和 **L**eg（直角边）。\n\n形式化：在 $\\triangle ABC$ 与 $\\triangle DEF$ 中，若\n$\\angle C = \\angle F = 90^\\circ,\\quad AB = DE\\ (\\text{斜边}),\\quad AC = DF\\ (\\text{直角边}),$\n则 $\\triangle ABC \\cong \\triangle DEF$（HL）。',
        image: 'thm-hl.svg',
        imageCaption: 'HL：两个直角三角形，斜边与一条直角边对应相等',
        formula: '\\angle C = \\angle F = 90^\\circ,\\; AB = DE,\\; AC = DF \\Rightarrow \\triangle ABC \\cong \\triangle DEF',
      },
      {
        title: 'HL 为什么成立？由勾股定理化归为 SSS',
        body: '**最清晰的证法**：用勾股定理把"缺少的"那条直角边算出来。\n\n设 $\\triangle ABC$（$\\angle C = 90^\\circ$）与 $\\triangle DEF$（$\\angle F = 90^\\circ$），已知 $AB = DE$（斜边）、$AC = DF$（一条直角边）。\n\n由勾股定理：\n$BC^2 = AB^2 - AC^2,\\qquad EF^2 = DE^2 - DF^2.$\n\n代入 $AB = DE$、$AC = DF$，得 $BC^2 = EF^2$，即 $BC = EF$（边长为正）。\n\n三边全部对应相等 → **SSS** → $\\triangle ABC \\cong \\triangle DEF$。\n\nHL 的本质：利用勾股定理自动补出第三条边，化归为 SSS。',
        formula: 'BC^2 = AB^2 - AC^2,\\quad EF^2 = DE^2 - DF^2',
        steps: [
          '已知：$\\angle C = \\angle F = 90^\\circ$，$AB = DE$（斜边），$AC = DF$（直角边）',
          '对 $\\triangle ABC$ 用勾股定理：$BC^2 = AB^2 - AC^2$',
          '对 $\\triangle DEF$ 用勾股定理：$EF^2 = DE^2 - DF^2$',
          '代入相等条件：$BC^2 = EF^2$，故 $BC = EF$',
          '三边对应相等，SSS → $\\triangle ABC \\cong \\triangle DEF$',
        ],
      },
      {
        title: '例 1：角平分线性质逆定理（HL 的经典应用）',
        body: '**题目**：$P$ 是 $\\angle AOB$ 内部一点，$PM \\perp OA$（垂足 $M$），$PN \\perp OB$（垂足 $N$），且 $PM = PN$。求证：$OP$ 平分 $\\angle AOB$。\n\n**思路**：\n- 由作图，$\\angle OMP = \\angle ONP = 90^\\circ$，两个三角形 $\\triangle OPM$ 与 $\\triangle OPN$ 都是直角三角形；\n- $OP$ 是**公共斜边**（$\\angle OMP, \\angle ONP$ 都是直角，斜边是直角的对边，即 $OP$），$OP = OP$；\n- $PM = PN$（题设，两直角边）；\n- 三项均满足 → **HL** → $\\triangle OPM \\cong \\triangle OPN$；\n- 对应角：$\\angle MOP = \\angle NOP$，即 $OP$ 平分 $\\angle AOB$。',
        image: 'thm-angle-bisector-converse.svg',
        imageCaption: '$PM \\perp OA$，$PN \\perp OB$，$PM = PN$，由 HL 得 $OP$ 平分 $\\angle AOB$',
        steps: [
          '指出 $\\angle OMP = \\angle ONP = 90^\\circ$（两三角形均为直角三角形）',
          '斜边：$OP = OP$（公共斜边）',
          '直角边：$PM = PN$（题设）',
          '套 HL：$\\triangle OPM \\cong \\triangle OPN$',
          '对应角：$\\angle MOP = \\angle NOP$，即 $OP$ 平分 $\\angle AOB$',
        ],
        reveal: {
          q: '若不用 HL，改用 SSS，需要额外求出哪条边？',
          a: '需要算 $OM$ 和 $ON$。由勾股定理 $OM = \\sqrt{OP^2 - PM^2}$，$ON = \\sqrt{OP^2 - PN^2}$，因 $PM = PN$，得 $OM = ON$。再加 $OP = OP$，三边对应相等，才能用 SSS。HL 省去了这一步计算，更简洁。',
        },
      },
      {
        title: '使用 HL 的三步核对清单',
        body: '每次使用 HL 之前，务必逐项核对：\n\n1. **两个都是直角三角形？** 必须先确认（通过垂直条件、$90^\\circ$ 角等），不能省略；\n2. **相等的那对边里，一条是斜边？** 两个三角形的斜边互相对应；\n3. **另一对相等的边是直角边？** 且两直角边互相对应。\n\n三项齐全，才能写"由 **HL** 得 $\\triangle\\cdots \\cong \\triangle\\cdots$"。缺一不可。',
        tip: '写证明格式：① 先写"$\\angle C = \\angle F = 90^\\circ$"（直角）；② 再写"$AB = DE$（斜边）"；③ 再写"$AC = DF$（直角边）"；④ 最后"由 HL，$\\triangle ABC \\cong \\triangle DEF$"。',
      },
      {
        title: '易错点总结',
        body: '1. **HL 仅限直角三角形**：没有 $90^\\circ$ 角就退化为普通 SSA，不能成立；\n2. **斜边必须对应斜边**：两对相等的边里，必须恰有一对是斜边；如果一条是斜边、另一条是直角边（"异位"），就不是 HL；\n3. **直角条件不能省**：写证明时先指明直角，再写边相等；\n4. **能用 ASA/AAS 时不必死守 HL**：若已知一条直角边和一个锐角，直接用 ASA 或 AAS 更自然；HL 的独特价值在于"只知两条边（其中一条是斜边）"；\n5. **"等腰三角形三线合一"的一种证法**：等腰三角形顶角上的中线，可证两半是全等的直角三角形，用 HL 或 SSS 均可。',
      },
    ],
    questions: [
      {
        id: 'u4c2q1',
        type: 'judge',
        prompt: '两个三角形中，若斜边和一条直角边对应相等，则可以用 HL 判定全等。',
        answer: false,
        explain: '必须先确认两个三角形**都是直角三角形**，才能使用 HL。如果没有确认直角条件，"斜边"这个说法本身就没有意义，强行使用 HL 等于用了普通的 SSA——而 SSA 一般不能判定全等。',
      },
      {
        id: 'u4c2q2',
        type: 'choice',
        prompt: '在 $\\text{Rt}\\triangle ABC$（$\\angle C = 90^\\circ$）与 $\\text{Rt}\\triangle DEF$（$\\angle F = 90^\\circ$）中，$AB = DE = 5$，$BC = EF = 3$。由 HL 可得两三角形全等，另一条直角边 $AC$ 的长度是？',
        options: ['$2$', '$3$', '$4$', '$\\sqrt{34}$'],
        answer: 2,
        explain: '由勾股定理：$AC = \\sqrt{AB^2 - BC^2} = \\sqrt{25 - 9} = \\sqrt{16} = 4$。\n（HL 告诉我们两三角形全等，由此 $DF = AC = 4$。）',
      },
      {
        id: 'u4c2q3',
        type: 'choice',
        prompt: '$AD$ 是 $\\triangle ABC$ 中 $BC$ 边上的高（$AD \\perp BC$，$D$ 在 $BC$ 上），且 $AB = AC$。用 HL 证明 $BD = DC$，那么两个候选直角三角形是？',
        options: [
          '$\\triangle ABD$ 与 $\\triangle ACD$，$AD$ 是公共直角边，斜边是 $AB = AC$',
          '$\\triangle ABD$ 与 $\\triangle ACD$，$BD$ 是公共直角边，斜边是 $AB = AC$',
          '$\\triangle ABD$ 与 $\\triangle ABC$，$AD$ 是公共直角边',
          '$\\triangle ABD$ 与 $\\triangle ACD$，$AB$ 是公共直角边',
        ],
        answer: 0,
        explain: '$\\triangle ABD$ 与 $\\triangle ACD$：两者都有直角（$\\angle ADB = \\angle ADC = 90^\\circ$，因 $AD \\perp BC$）；斜边 $AB = AC$（等腰条件）；公共直角边 $AD = AD$。三项满足，由 HL 得 $\\triangle ABD \\cong \\triangle ACD$，对应边 $BD = DC$。',
      },
      {
        id: 'u4c2q4',
        type: 'judge',
        prompt: '$P$ 是 $\\angle AOB$ 内部一点，$PM \\perp OA$，$PN \\perp OB$，$PM = PN$。由 HL 可以证明 $OP$ 平分 $\\angle AOB$。',
        answer: true,
        explain: '$\\triangle OPM$ 与 $\\triangle OPN$：$\\angle OMP = \\angle ONP = 90^\\circ$（直角三角形），公共斜边 $OP = OP$，直角边 $PM = PN$（题设）。HL 得全等，对应角 $\\angle MOP = \\angle NOP$，即 $OP$ 平分 $\\angle AOB$，说法正确。',
      },
      {
        id: 'u4c2q5',
        type: 'input',
        prompt: '在 $\\text{Rt}\\triangle ABC$（$\\angle C = 90^\\circ$）中，斜边 $AB = 10$，直角边 $AC = 6$，则直角边 $BC = $（填数字）？',
        accept: ['8', '8.0'],
        explain: '由勾股定理：$BC = \\sqrt{AB^2 - AC^2} = \\sqrt{100 - 36} = \\sqrt{64} = 8$。',
      },
      {
        id: 'u4c2q6',
        type: 'match',
        prompt: '将下列各情况与是否能用 HL 判定全等配对。',
        left: [
          '两个直角三角形，斜边相等，一条直角边相等',
          '两个锐角三角形，最长边相等，一边相等',
          '两个直角三角形，两条直角边分别相等',
          '两个直角三角形，斜边相等，一个锐角相等',
        ],
        right: [
          '可以用 HL',
          '不能用 HL（不是直角三角形）',
          '可以用 SSS（三边都知道了）',
          '可以用 AAS（两角一边）',
        ],
        explain: '① 直接满足 HL 条件；② 普通三角形无斜边概念，不能用 HL；③ 两条直角边已知，勾股定理可算出斜边，三边均已知，用 SSS；④ 已知直角 + 一个锐角 + 斜边（斜边对应 $90^\\circ$ 的对边），用 AAS 更直接。',
      },
      {
        id: 'u4c2q7',
        type: 'choice',
        prompt: '下列关于 HL 的说法中，正确的是？',
        options: [
          'HL 是一条独立的公理，不依赖 SSS/SAS/ASA/AAS',
          'HL 可以用勾股定理化归为 SSS',
          'HL 也可以用于钝角三角形',
          'HL 中斜边可以等于直角边，结论依然成立',
        ],
        answer: 1,
        explain: 'HL 不是独立公理，它可以用勾股定理将"缺少的直角边"算出来，从而化归为 **SSS**。钝角三角形没有"斜边"的概念，HL 仅限直角三角形。斜边必须等于斜边、直角边必须等于直角边，不能混位。',
      },
      {
        id: 'u4c2q8',
        type: 'judge',
        prompt: '两个直角三角形中，如果一条直角边和一个锐角对应相等，那么必须用 HL 才能判定全等。',
        answer: false,
        explain: '一条直角边 + 一个锐角，相当于"两角（直角 + 锐角）及对边"（直角边是锐角的对边）→ **AAS**；或者"两角（直角 + 锐角）及夹边"（直角边是直角与锐角的夹边）→ **ASA**，具体取决于边的位置。HL 的独特价值在于"只知两条边（斜边 + 直角边）"时，此题已有角度信息，用 AAS 或 ASA 更直接。',
      },
    ],
  },
]
