export const LESSONS = [
  {
    id: 'u4c3',
    title: '手拉手模型',
    subtitle: '两个等腰共顶点 + 顶角相等 → 腰端连线相等，夹角等于顶角',
    intro: [
      {
        title: '引入：一道让你卡住的题',
        body: '$\\triangle OAB$ 和 $\\triangle OCD$ 都是等腰三角形，$OA = OB$，$OC = OD$，$\\angle AOB = \\angle COD = 50^\\circ$，共顶点 $O$。求证：$AC = BD$。\n\n大多数人会卡在这里：条件给的是 $OA = OB$、$OC = OD$，要证的却是 $AC$ 和 $BD$——它们**"看起来"不在同一个明显的三角形里**，不知该选哪两个三角形。\n\n这一卡，正是手拉手模型存在的意义。',
        image: 'ex-p3c03-0.svg',
        imageCaption: '手拉手引入题：两个顶角 $50^\\circ$ 的等腰三角形共顶点 $O$，求证 $AC = BD$',
      },
      {
        title: '思维路径：怎么找那两个三角形？',
        body: '要证 $AC = BD$ → **找含 $AC$ 和 $BD$ 的三角形**，而不是死盯题目给的那两个等腰三角形。\n\n- $AC$ 最自然的三角形：$\\triangle AOC$；\n- $BD$ 最自然的三角形：$\\triangle BOD$。\n\n**目标锁定**：证 $\\triangle AOC \\cong \\triangle BOD$。\n\n现有条件：$OA = OB$，$OC = OD$，差一个角。差的是 $\\angle AOC$（夹 $OA, OC$）和 $\\angle BOD$（夹 $OB, OD$），它们相等吗？',
        tip: '遇到"两段相等"，第一步：把这两段所在的三角形画出来，再去凑条件——这是初中几何的标准条件反射。',
      },
      {
        title: '等量加同一项：凑出夹角相等',
        body: '直接看 $\\angle AOC$ 与 $\\angle BOD$ 是否相等，没有现成结论。**但可以拆**：\n\n$\\angle AOC = \\angle AOB + \\angle BOC,\\qquad \\angle BOD = \\angle BOC + \\angle COD.$\n\n两式右边都有 $\\angle BOC$（公共部分），且 $\\angle AOB = \\angle COD = 50^\\circ$（已知），所以\n\n$\\angle AOC = \\angle BOD.$\n\n这正是**等量加同一项**：两个相等的量（$\\angle AOB = \\angle COD$），各加上同一个量（$\\angle BOC$），结果仍相等。\n\n条件齐全：$OA = OB$，$\\angle AOC = \\angle BOD$，$OC = OD$ → **SAS** → $\\triangle AOC \\cong \\triangle BOD$ → $AC = BD$。',
        formula: '\\angle AOC = \\angle AOB + \\angle BOC = \\angle BOC + \\angle COD = \\angle BOD',
        steps: [
          '目标：证 $AC = BD$，找含 $AC, BD$ 的三角形：$\\triangle AOC$ 与 $\\triangle BOD$',
          '$OA = OB$（等腰 $\\triangle OAB$），$OC = OD$（等腰 $\\triangle OCD$），两组边到手',
          '拆角：$\\angle AOC = \\angle AOB + \\angle BOC$，$\\angle BOD = \\angle BOC + \\angle COD$',
          '等量加同一项：$\\angle AOB = \\angle COD \\Rightarrow \\angle AOC = \\angle BOD$',
          '套 SAS：$\\triangle AOC \\cong \\triangle BOD$，对应边 $AC = BD$',
        ],
      },
      {
        title: '模型提炼：三个识别条件 + 三个核心结论',
        body: '**识别条件**（三条全部满足才算手拉手）：\n1. 有两个等腰三角形：$\\triangle OAB$（$OA = OB$）和 $\\triangle OCD$（$OC = OD$）；\n2. 两个三角形**共顶点 $O$**（顶角顶点重合）；\n3. 两个**顶角相等**：$\\angle AOB = \\angle COD$。\n\n**核心结论**（见到上述特征立刻有）：\n- $\\triangle AOC \\cong \\triangle BOD$（SAS）；\n- $AC = BD$（对应边相等）；\n- $AC$ 与 $BD$ 的**夹角** $= \\angle AOB$（旋转角，等于两顶角）。',
        image: 'model-handshake-basic.svg',
        imageCaption: '手拉手模型：两个等腰三角形共顶点，顶角相等，腰端连线相等且夹角等于顶角',
      },
      {
        title: '模型变形：等边版与等腰直角版',
        body: '**变形 1（等边版）**：两个等边三角形，顶角自动 $= 60^\\circ$，旋转角 $= 60^\\circ$。\n\n**变形 2（等腰直角版）**：两个等腰直角三角形，顶角 $= 90^\\circ$，旋转角 $= 90^\\circ$。\n**重要副产品：$AC \\perp BD$**（$BD$ 是 $AC$ 绕 $O$ 转 $90^\\circ$ 得到的）。\n\n**变形 3（位置变化）**：$\\triangle OCD$ 可以在 $\\triangle OAB$ 外部、部分嵌入内部或翻转到另一侧——只要"共顶点 + 顶角相等"满足，证法**一字不变**。\n\n**变形 4（隐藏版）**：题目不明说"等腰"，但可以通过中点、角平分线等**推出** $OA = OB$、$OC = OD$。\n\n**本质**：手拉手 $=$ 旋转构造全等。$\\triangle OCD$ 是 $\\triangle OAB$ 绕 $O$ 旋转顶角所得，旋转保长度、保夹角。',
        image: 'model-handshake-equilateral.svg',
        imageCaption: '手拉手等边特例：两个等边三角形共顶点，旋转角 $60^\\circ$，腰端连线相等且夹角 $60^\\circ$',
      },
      {
        title: '思考路标（看到 X → 想到 Y）',
        body: '把下面每条内化为条件反射：\n\n- 看到**两个共顶点的等腰三角形（顶角相等）** → 手拉手，立刻去证 $\\triangle AOC \\cong \\triangle BOD$（SAS）；\n- 看到**等边三角形 + 共顶点** → 手拉手，旋转角 $60^\\circ$；\n- 看到**等腰直角 + 共顶点 + 要证垂直** → 手拉手，旋转角 $90^\\circ$，$AC \\perp BD$；\n- 要证**两段相等**，图中有**共顶点等腰结构** → 自己找含这两段的三角形，用 SAS；\n- 用 SAS 差一个角，两候选角都"夹着公共部分" → **等量加同一项**；\n- 看到"绕某点旋转"得新图形 → 原图与新图天然手拉手。',
        tip: '手拉手的核心动作只有一个："自己去找 $\\triangle AOC$ 与 $\\triangle BOD$"，而不是死盯题目给的那两个等腰三角形。',
      },
      {
        title: '例：等腰直角版 $AC = BD$ 且 $AC \\perp BD$',
        body: '**题目**：$\\triangle OAB$ 和 $\\triangle OCD$ 都是等腰直角三角形，$\\angle AOB = \\angle COD = 90^\\circ$，共顶点 $O$。求证：$AC = BD$ 且 $AC \\perp BD$。\n\n**$AC = BD$ 的证明**：同基础手拉手，SAS 得 $\\triangle AOC \\cong \\triangle BOD$，故 $AC = BD$。\n\n**$AC \\perp BD$ 的证明**：设 $AC$ 与 $BD$ 交于 $P$。由全等得 $\\angle OAC = \\angle OBD$。在 $\\triangle ABP$ 中，$\\angle APB = 180^\\circ - \\angle OAC - \\angle ABD$（其中 $\\angle ABD = \\angle OBA + \\angle OBD = 45^\\circ + \\angle OBD$）。利用 $\\angle OAB = 45^\\circ$（等腰直角）与 $\\angle OAC = \\angle OBD$，最终 $\\angle APB = 90^\\circ$，即 $AC \\perp BD$。',
        reveal: {
          q: '若两个等腰直角三角形共顶点，$AC$ 与 $BD$ 互相垂直且相等，这两段之间的关系相当于什么变换？',
          a: '$BD$ 是 $AC$ 绕 $O$ 顺时针（或逆时针）旋转 $90^\\circ$ 所得，$|AC| = |BD|$，且夹角 $90^\\circ$。这本质是以 $O$ 为中心的旋转变换。',
        },
      },
    ],
    questions: [
      {
        id: 'u4c3q1',
        type: 'choice',
        prompt: '$\\triangle OAB$ 和 $\\triangle OCD$ 均为等腰三角形，$OA = OB$，$OC = OD$，$\\angle AOB = \\angle COD = 70^\\circ$，共顶点 $O$。$B, C$ 在 $O$ 同侧，$\\angle BOC = 30^\\circ$。则 $\\angle AOC$ 等于多少度？',
        options: ['$30^\\circ$', '$70^\\circ$', '$100^\\circ$', '$140^\\circ$'],
        answer: 2,
        explain: '$\\angle AOC = \\angle AOB + \\angle BOC = 70^\\circ + 30^\\circ = 100^\\circ$。',
      },
      {
        id: 'u4c3q2',
        type: 'judge',
        prompt: '手拉手模型中，两腰端点连线 $AC$ 与 $BD$ 的夹角，等于两个等腰三角形的公共顶角。',
        answer: true,
        explain: '手拉手的核心结论之一：$AC$ 与 $BD$ 的夹角恰好等于顶角（旋转角）。这是因为 $\\triangle AOC \\cong \\triangle BOD$（SAS），$\\angle OAC = \\angle OBD$，从而交点处的角 $= \\angle AOB$。说法正确。',
      },
      {
        id: 'u4c3q3',
        type: 'choice',
        prompt: '$\\triangle OAB$ 和 $\\triangle OCD$ 都是等边三角形，共顶点 $O$，$AC$ 与 $BD$ 交于点 $P$，则 $\\angle APB$ 等于多少度？',
        options: ['$30^\\circ$', '$45^\\circ$', '$60^\\circ$', '$90^\\circ$'],
        answer: 2,
        explain: '等边三角形顶角 $= 60^\\circ$。手拉手结论：$AC$ 与 $BD$ 的夹角等于顶角 $= 60^\\circ$。$\\angle APB$ 是这两段在交点处的夹角（或其对顶角），故 $\\angle APB = 60^\\circ$。',
      },
      {
        id: 'u4c3q4',
        type: 'input',
        prompt: '手拉手证明中，要说明 $\\angle AOC = \\angle BOD$，用的是"等量____同一项"（填"加"或"减"）。',
        accept: ['加', '加上', '相加'],
        explain: '$\\angle AOC = \\angle AOB + \\angle BOC$，$\\angle BOD = \\angle COD + \\angle BOC$，两个相等的量（$\\angle AOB = \\angle COD$）各**加上**同一个量（$\\angle BOC$），结果相等。',
      },
      {
        id: 'u4c3q5',
        type: 'judge',
        prompt: '若 $\\triangle OAB$ 和 $\\triangle OCD$ 都是等腰直角三角形（顶角为 $90^\\circ$），共顶点 $O$，则 $AC \\perp BD$。',
        answer: true,
        explain: '等腰直角版手拉手，旋转角 $= 90^\\circ$，$BD$ 是 $AC$ 绕 $O$ 旋转 $90^\\circ$ 所得，故 $AC \\perp BD$。这是手拉手的重要副产品，说法正确。',
      },
      {
        id: 'u4c3q6',
        type: 'match',
        prompt: '将下列手拉手变形与对应的关键参数配对。',
        left: [
          '两个等边三角形共顶点',
          '两个等腰直角三角形共顶点',
          '两个顶角为 $40^\\circ$ 的等腰三角形共顶点',
          '两个顶角为 $\\ alpha$ 的等腰三角形共顶点',
        ],
        right: [
          '旋转角 $60^\\circ$，$AC = BD$，夹角 $60^\\circ$',
          '旋转角 $90^\\circ$，$AC = BD$，$AC \\perp BD$',
          '旋转角 $40^\\circ$，$AC = BD$，夹角 $40^\\circ$',
          '旋转角 $\\alpha$，$AC = BD$，夹角 $\\alpha$',
        ],
        explain: '手拉手中旋转角 $=$ 顶角，夹角 $=$ 旋转角 $=$ 顶角。等腰直角时夹角 $= 90^\\circ$，即 $AC \\perp BD$。',
      },
      {
        id: 'u4c3q7',
        type: 'choice',
        prompt: '证明 $\\triangle AOC \\cong \\triangle BOD$（手拉手）时，用的判定定理是？',
        options: ['SSS', 'SAS', 'ASA', 'AAS'],
        answer: 1,
        explain: '手拉手的标准证明：$OA = OB$（一组边），$\\angle AOC = \\angle BOD$（**夹角**，由等量加同一项得），$OC = OD$（另一组边）。两边及其夹角 → **SAS**。',
      },
      {
        id: 'u4c3q8',
        type: 'judge',
        prompt: '手拉手模型中，如果 $\\triangle OCD$ 在 $\\triangle OAB$ 的外部（而不是内部），证明 $AC = BD$ 的方法和步骤需要改变。',
        answer: false,
        explain: '只要"共顶点 + 两顶角相等"满足，$\\triangle OCD$ 在内部还是外部，只影响"公共角 $\\angle BOC$ 是加还是减"的拆解方式，但最终 $\\angle AOC = \\angle BOD$ 的结论仍然成立，SAS 证明的骨架**一字不变**。',
      },
    ],
  },
]
