export const LESSONS = [
  {
    id: 'u4c4',
    title: '半角模型',
    subtitle: '正方形 + 顶点处 45° 角 → 旋转拼合，两短段之和等于一长段',
    intro: [
      {
        title: '引入：让人卡住的正方形题',
        body: '正方形 $ABCD$ 中，$E$ 在 $BC$ 上，$F$ 在 $CD$ 上，$\\angle EAF = 45^\\circ$。求证：$EF = BE + DF$。\n\n卡点非常具体：$EF$ 是一段线段，$BE + DF$ 是分别长在不同边上的两段之和。死盯着图，怎么也找不出它们之间的显然等量关系。\n\n问题本质：**两段分散在不同位置，怎么"合"成一段？** 答案只有两个字：**旋转**。',
        image: 'ex-p3c04-0.svg',
        imageCaption: '半角引入：正方形 $ABCD$ + $\\angle EAF = 45^\\circ$，求证 $EF = BE + DF$',
      },
      {
        title: '核心信号：$45^\\circ$ 是 $90^\\circ$ 的一半',
        body: '$\\angle EAF = 45^\\circ$，而正方形顶角 $\\angle BAD = 90^\\circ$。\n\n$45^\\circ$ 恰好是 $90^\\circ$ 的**一半**——这是半角模型名字的来源，也是最强的触发信号。\n\n一旦看到"正方形 + 某顶点处 $45^\\circ$ 角"，立刻联想：**旋转一个三角形，把两段折合成一段**。\n\n旋转的基础是 $AB = AD$（正方形两邻边相等），旋转角度 $= 90^\\circ$（正方形的顶角）。',
        tip: '看到正方形里冒出 $45^\\circ$，先按半角模型试一遍——这是中考几何的高频套路。',
      },
      {
        title: '思维路径：旋转 $\\triangle ADF$ 到 $\\triangle ABF\'$',
        body: '**关键操作**：把 $\\triangle ADF$ 绕 $A$ 顺时针旋转 $90^\\circ$。\n\n- $AD$ 旋转到 $AB$ 的位置（$AD = AB$，$\\angle DAB = 90^\\circ$），所以 $D \\to B$；\n- $F$（在 $CD$ 上）旋转到 $BC$ 延长线上的某点 $F\'$；\n- 旋转后立刻有：$AF = AF\'$，$DF = BF\'$，$\\angle DAF = \\angle BAF\'$。\n\n**现在证 $\\triangle AEF \\cong \\triangle AEF\'$（SAS）**：\n- 公共边：$AE = AE$（✓）；\n- $AF = AF\'$（旋转得来，✓）；\n- 夹角：$\\angle EAF = 45^\\circ$（已知），$\\angle EAF\' = \\angle BAE + \\angle BAF\' = \\angle BAE + \\angle DAF = \\angle BAD - \\angle EAF = 90^\\circ - 45^\\circ = 45^\\circ$（✓）。\n\n**SAS** → $EF = EF\'$，而 $EF\' = BE + BF\' = BE + DF$，故 $EF = BE + DF$。',
        formula: '\\angle EAF = \\angle EAF\' = 45^\\circ,\\quad AF = AF\' \\Rightarrow \\triangle AEF \\cong \\triangle AEF\'',
        steps: [
          '识别信号：$\\angle EAF = 45^\\circ = \\frac{1}{2} \\times 90^\\circ$，正方形 $AB = AD$',
          '旋转 $\\triangle ADF$ 绕 $A$ 顺时针 $90^\\circ$，$D \\to B$，$F \\to F\'$（$F\'$ 在 $BC$ 的延长线上）',
          '旋转后：$AF = AF\'$，$DF = BF\'$',
          '计算 $\\angle EAF\' = \\angle BAE + \\angle BAF\' = \\angle BAE + \\angle DAF = 90^\\circ - 45^\\circ = 45^\\circ$',
          'SAS（$AE = AE$，$\\angle EAF = \\angle EAF\'$，$AF = AF\'$）：$\\triangle AEF \\cong \\triangle AEF\'$',
          '$EF = EF\' = BE + BF\' = BE + DF$',
        ],
        image: 'model-half-angle.svg',
        imageCaption: '半角模型：把 $\\triangle ADF$ 绕 $A$ 旋转 $90^\\circ$，$F$ 落到 $F\'$，两段拼合为一段',
      },
      {
        title: '模型提炼：三步记忆法',
        body: '**识别半角** → **旋转拼合** → **SAS 全等**\n\n- **识别半角**：正方形（或等腰直角三角形）顶点处出现等于**半顶角**（正方形为 $45^\\circ$）的角；\n- **旋转拼合**：把其中一个三角形绕顶点旋转顶角（$90^\\circ$）度，让两段首尾相接；\n- **SAS 全等**：旋转后配合公共边，凑出 SAS，完成等量关系的证明。\n\n核心等式：$EF = BE + DF$（"两短段之和 $=$ 一长段"）。',
        tip: '旋转哪个三角形？哪个三角形对应的"腰"（$AD$ 或 $AB$）能旋转到另一条腰上，就转哪个。正方形里 $AB = AD$，$\\triangle ADF$ 绕 $A$ 旋转 $90^\\circ$ 让 $AD \\to AB$。',
      },
      {
        title: '例 1：正方形 $+ 45^\\circ$，求 $\\triangle CEF$ 周长',
        body: '**题目**：正方形 $ABCD$ 边长为 $1$，$E$ 在 $BC$ 上，$F$ 在 $CD$ 上，$\\angle EAF = 45^\\circ$。求 $\\triangle CEF$ 的周长。\n\n**思路**：先由半角模型（同引入题）得 $EF = BE + DF$，则\n$L = CE + CF + EF = CE + CF + BE + DF = (CE + BE) + (CF + DF) = BC + CD = 1 + 1 = 2.$\n\n**周长恒为 $2$，与 $E, F$ 的具体位置无关！**',
        image: 'ex-p3c04-1.svg',
        imageCaption: '半角例 1：正方形边长 $1$，$\\triangle CEF$ 周长恒为 $2$',
        reveal: {
          q: '正方形 $ABCD$ 边长为 $6$，$E$ 在 $BC$ 上，$F$ 在 $CD$ 上，$\\angle EAF = 45^\\circ$，$BE = 2$。求 $DF$。',
          a: '设 $DF = x$。由半角模型 $EF = BE + DF = 2 + x$。$CE = 6 - 2 = 4$，$CF = 6 - x$。在 $\\text{Rt}\\triangle CEF$ 中：$(6 - x)^2 + 4^2 = (2 + x)^2$，展开得 $36 - 12x + x^2 + 16 = 4 + 4x + x^2$，化简 $48 = 16x$，$x = 3$。故 $DF = 3$。',
        },
      },
      {
        title: '模型变形与易错点',
        body: '**变形 1（等腰直角三角形版）**：等腰直角 $\\triangle ABC$（$\\angle BAC = 90^\\circ$，$AB = AC$）中，$D, E$ 在斜边上，$\\angle DAE = 45^\\circ$。结论变为 $DE^2 = BD^2 + EC^2$（用勾股而不是直接等量）。\n\n**变形 2（外部版）**：$E$ 在 $BC$ 延长线上，$F$ 在 $CD$ 上，$\\angle EAF = 45^\\circ$ → 结论变为 $EF = BE - DF$（$F\'$ 落在 $BE$ 内部，$EF\' = BE - BF\' = BE - DF$）。\n\n**易错点**：\n1. 混淆"旋转方向"（顺时针/逆时针）——只要最终让 $AD$ 旋转到 $AB$ 就行；\n2. 忘记验证 $\\angle EAF\' = 45^\\circ$（这一步不能省）；\n3. $E, F$ 位置互换时要重新检查 $F\'$ 的落点是在 $BC$ 内部还是外部。',
        image: 'model-half-angle-rotation.svg',
        imageCaption: '半角模型旋转过程：$\\triangle ADF$ 绕 $A$ 旋转 $90^\\circ$，$D$ 落到 $B$，$F$ 落到 $F\'$',
      },
    ],
    questions: [
      {
        id: 'u4c4q1',
        type: 'choice',
        prompt: '正方形 $ABCD$ 中，$E$ 在 $BC$ 上，$F$ 在 $CD$ 上，$\\angle EAF = 45^\\circ$。$BE = 3$，$DF = 2$，则 $EF = $？',
        options: ['$4$', '$5$', '$6$', '$\\sqrt{13}$'],
        answer: 1,
        explain: '直接套半角模型结论：$EF = BE + DF = 3 + 2 = 5$。',
      },
      {
        id: 'u4c4q2',
        type: 'judge',
        prompt: '半角模型中，旋转 $\\triangle ADF$ 绕 $A$ 旋转 $90^\\circ$ 后，$F$ 的像 $F\'$ 一定落在 $BC$ 上（不是延长线上）。',
        answer: false,
        explain: '$F\'$ 落在 $BC$ 上还是延长线上，取决于 $F$ 的位置（$DF$ 的长短与边长的关系）。若 $DF$ 较大，$F\'$ 可能超出 $B$ 落在 $BC$ 的延长线上；若 $E$ 在延长线上，则情况又不同。不能断定一定在 $BC$ 内部。',
      },
      {
        id: 'u4c4q3',
        type: 'choice',
        prompt: '正方形 $ABCD$ 边长为 $4$，$E$ 在 $BC$ 上，$F$ 在 $CD$ 上，$\\angle EAF = 45^\\circ$。$\\triangle CEF$ 的周长为？',
        options: ['$4$', '$6$', '$8$', '不能确定，依赖 $E, F$ 位置'],
        answer: 2,
        explain: '$\\triangle CEF$ 周长 $= CE + CF + EF = CE + CF + BE + DF = BC + CD = 4 + 4 = 8$，与 $E, F$ 的位置无关。',
      },
      {
        id: 'u4c4q4',
        type: 'input',
        prompt: '半角模型的证明中，把 $\\triangle ADF$ 绕 $A$ 旋转 $90^\\circ$ 后，利用的全等判定是（填判定名称，如 SSS）？',
        accept: ['SAS', 'sas'],
        explain: '旋转后证 $\\triangle AEF \\cong \\triangle AEF\'$，用到的是：$AE = AE$（公共边），$AF = AF\'$（旋转保距离），$\\angle EAF = \\angle EAF\' = 45^\\circ$（两边的夹角）。两边及其夹角相等 → **SAS**。',
      },
      {
        id: 'u4c4q5',
        type: 'judge',
        prompt: '等腰三角形（非直角）顶点处若出现等于半顶角的角，同样可以套用半角模型的旋转思路。',
        answer: true,
        explain: '半角模型的本质是：等腰两腰相等提供旋转基础，顶点处的"半顶角"保证旋转后夹角条件成立（SAS）。只要满足"等腰 + 半顶角"，无论是正方形（顶角 $90^\\circ$）、等腰直角（顶角 $90^\\circ$）还是一般等腰（顶角 $2\\alpha$），旋转思路都成立。',
      },
      {
        id: 'u4c4q6',
        type: 'match',
        prompt: '将下列图形特征与对应的结论配对。',
        left: [
          '正方形 + 顶点处 $45^\\circ$ 角，$E, F$ 在两邻边上',
          '正方形，$E$ 在 $BC$ 延长线上，$F$ 在 $CD$ 上，$\\angle EAF = 45^\\circ$',
          '等腰直角 $\\triangle ABC$（$\\angle A = 90^\\circ$），$D, E$ 在斜边上，$\\angle DAE = 45^\\circ$',
          '正方形边长 $s$，$\\triangle CEF$ 周长',
        ],
        right: [
          '$EF = BE + DF$',
          '$EF = BE - DF$',
          '$DE^2 = BD^2 + EC^2$',
          '恒为 $2s$',
        ],
        explain: '① 标准半角：$EF = BE + DF$；② 外部版：$F\'$ 在 $BE$ 内部，$EF = BE - DF$；③ 等腰直角斜边版：旋转后在直角处用勾股，得 $DE^2 = BD^2 + EC^2$；④ 周长 $= BC + CD = 2s$。',
      },
      {
        id: 'u4c4q7',
        type: 'choice',
        prompt: '半角模型的证明中，关键的一步是验证 $\\angle EAF\' = \\angle EAF$。请问 $\\angle EAF\'$ 由哪两个角相加得到？',
        options: [
          '$\\angle BAE + \\angle BAF\'$',
          '$\\angle DAF + \\angle BAF\'$',
          '$\\angle EAF + \\angle DAF$',
          '$\\angle BAD - \\angle EAF$',
        ],
        answer: 0,
        explain: '$F\'$ 在 $BC$ 一侧，$\\angle EAF\' = \\angle BAE + \\angle BAF\'$。由旋转，$\\angle BAF\' = \\angle DAF$，所以 $\\angle EAF\' = \\angle BAE + \\angle DAF = \\angle BAD - \\angle EAF = 90^\\circ - 45^\\circ = 45^\\circ = \\angle EAF$。',
      },
      {
        id: 'u4c4q8',
        type: 'input',
        prompt: '正方形 $ABCD$ 边长为 $6$，$E$ 在 $BC$ 上，$F$ 在 $CD$ 上，$\\angle EAF = 45^\\circ$，$BE = 2$。求 $EF$ 的长（填数字）。',
        accept: ['5', '5.0'],
        explain: '设 $DF = x$。由半角模型 $EF = BE + DF = 2 + x$。$CE = 4$，$CF = 6 - x$。在 $\\text{Rt}\\triangle CEF$ 中：$(6-x)^2 + 4^2 = (2+x)^2$，展开：$36 - 12x + x^2 + 16 = 4 + 4x + x^2$，得 $48 = 16x$，$x = 3$。故 $EF = 2 + 3 = 5$。',
      },
    ],
  },
]
