export const LESSONS = [
  {
    id: 'u4c5',
    title: '一线三等角（K 字模型）',
    subtitle: '一条直线上三个相等的角，两侧三角形相似；中点时升级为全等',
    intro: [
      {
        title: '引入：三个相等角贴在同一条直线上',
        body: '直线 $l$ 上顺次有三点 $A, P, B$，在 $l$ 的同侧作三个相等的角：$\\angle PAC = \\angle APD = \\angle PBD = \\alpha$（$C, D$ 在 $l$ 同侧）。求证：$\\triangle PAC \\sim \\triangle BPD$。\n\n看到"三点共线 + 同侧三个相等角"，先别急着列条件——**这种结构在大喊它的名字：K 字**。\n\n整体形状：把直线 $l$ 横着画，$AC$、$PD$、$BD$ 三段连起来，外形像把字母 **K** 平躺。',
        image: 'ex-p3c05-0.svg',
        imageCaption: 'K 字引入题：直线 $l$ 上三点 $A, P, B$，同侧三个相等角 $\\alpha$',
      },
      {
        title: '思维路径：两步到 AA 相似',
        body: '要证 $\\triangle PAC \\sim \\triangle BPD$，相似只需找**两对对应角相等**（AA）。\n\n**第一对**：$\\angle PAC = \\alpha = \\angle PBD$（已知的 $A$ 处和 $B$ 处角）。\n\n**第二对**：需要找 $\\triangle PAC$ 和 $\\triangle BPD$ 各自剩余的角。用**三角形外角定理**：\n- $\\triangle PAC$ 在 $P$ 处的外角 $\\angle CPB = \\angle PAC + \\angle ACP = \\alpha + \\angle ACP$；\n- 同时 $\\angle CPB = \\angle CPD + \\angle DPB = \\alpha + \\angle DPB$（中间角 $\\angle CPD = \\alpha$ 是已知的第三个等角）；\n- 两式相减：$\\angle ACP = \\angle DPB$。\n\n两对角相等（$\\angle A = \\angle B = \\alpha$，$\\angle ACP = \\angle DPB$）→ **AA** → $\\triangle PAC \\sim \\triangle BPD$。',
        formula: '\\angle CPB = \\alpha + \\angle ACP = \\alpha + \\angle DPB \\Rightarrow \\angle ACP = \\angle DPB',
        steps: [
          '第一对：$\\angle PAC = \\angle PBD = \\alpha$（已知）',
          '$\\triangle PAC$ 在 $P$ 处的外角 $\\angle CPB = \\angle PAC + \\angle ACP = \\alpha + \\angle ACP$',
          '平角分解：$\\angle CPB = \\angle CPD + \\angle DPB = \\alpha + \\angle DPB$',
          '两式相减：$\\angle ACP = \\angle DPB$（第二对）',
          'AA → $\\triangle PAC \\sim \\triangle BPD$',
        ],
        image: 'model-k-shape-basic.svg',
        imageCaption: 'K 字（一线三等角）：外角定理使第二对相等角直接弹出',
      },
      {
        title: '模型提炼：识别条件与核心结论',
        body: '**识别条件**（全部满足才算 K 字）：\n- 一条直线 $l$ 上**顺次有三点** $A, P, B$；\n- $l$ 的**同侧**有三条线段/射线，分别从 $A, P, B$ 出发；\n- 三个角 $\\angle PAC = \\angle APD = \\angle DBP = \\alpha$，**都贴在 $l$ 同侧**。\n\n**核心结论**：\n- $\\triangle PAC \\sim \\triangle BPD$（对应关系 $P\\leftrightarrow B$，$A\\leftrightarrow P$，$C\\leftrightarrow D$）；\n- 对应边成比例：$\\dfrac{PA}{BP} = \\dfrac{AC}{PD} = \\dfrac{PC}{BD}$；\n- 若 **$PA = BP$**（$P$ 是 $AB$ 中点），则相似比为 $1$，**升级为全等** $\\triangle PAC \\cong \\triangle BPD$。',
        tip: '**对应关系最易出错**：$\\triangle PAC \\sim \\triangle BPD$，$P$ 对 $B$、$A$ 对 $P$，不是 $A$ 对 $B$！写比例时一定先确认对应关系。',
      },
      {
        title: '最常考变形：一线三直角（$\\alpha = 90^\\circ$）',
        body: '当三个相等角全变成 $90^\\circ$ 时，称为**一线三直角**——K 字模型的最高频版本。\n\n**图形特征**：$l$ 上三点 $A, P, B$，$CA \\perp l$，$PD \\perp l$，$DB \\perp l$（或一段在 $P$ 处与直线垂直）。\n\n**变形嵌入场景**：\n- **正方形/矩形**：把一条边当作 $l$，边上一点向两邻边各引垂线（或 $90^\\circ$ 线段）→ 立刻形成一线三直角；\n- **坐标系**：动点在 $x$ 轴滑动，向轴上两定点作竖直线 → 一线三直角；\n- 此时外角定理那一步退化为"两锐角互余"，更简洁。',
        image: 'model-k-shape-right.svg',
        imageCaption: '一线三直角（K 字直角特例）：三个直角同侧贴在直线 $l$ 上',
      },
      {
        title: '例：正方形内的一线三直角',
        body: '**题目**：正方形 $ABCD$ 边长 $4$，$E$ 在 $AB$ 上，$AE = 1$，$F$ 在 $BC$ 上，使 $\\angle DEF = 90^\\circ$。求 $BF$。\n\n**识别**：直线 $AB$，三点 $A, E, B$，三个直角 $\\angle DAE = 90^\\circ$（正方形边），$\\angle DEF = 90^\\circ$（题设），$\\angle EBF = 90^\\circ$（正方形边）。一线三直角！\n\n**结论**：$\\triangle ADE \\sim \\triangle BEF$（对应 $A\\leftrightarrow B$，$D\\leftrightarrow E$，$E\\leftrightarrow F$）。\n\n列比例：$\\dfrac{AD}{BE} = \\dfrac{AE}{BF}$，即 $\\dfrac{4}{3} = \\dfrac{1}{BF}$，解得 $BF = \\dfrac{3}{4}$。',
        image: 'ex-p3c05-2.svg',
        imageCaption: 'K 字例 2：正方形内的一线三直角，$\\triangle ADE \\sim \\triangle BEF$',
        reveal: {
          q: '若 $PA = PB = 5$，$\\angle PAC = \\angle APD = \\angle PBD = \\alpha$，$AC = 3$，则 $BD$ 等于多少？',
          a: '$PA = PB$，相似升级为全等：$\\triangle PAC \\cong \\triangle BPD$，对应边 $BD = PC$。先在 $\\triangle PAC$ 里算 $PC$：$PC = \\sqrt{PA^2 + AC^2} = \\sqrt{25 + 9} = \\sqrt{34}$（当 $\\alpha = 90^\\circ$ 时）；故 $BD = \\sqrt{34}$。若 $\\alpha \\ne 90^\\circ$ 则需余弦定理。',
        },
      },
      {
        title: '思考路标（看到 X → 想到 Y）',
        body: '- 看到**一条直线上三个相等角（同侧）** → K 字相似，找两侧三角形；\n- 看到**一线三直角** → K 字直角特例，直接套相似；\n- 看到**正方形/矩形内"边上一点向两邻边各引 $90^\\circ$ 线段"** → 一线三直角立刻成立；\n- K 字结构 + **一段等条件**（如中点）→ 相似升级为**全等**；\n- K 字要算线段长度 → 写对应边比例 $\\dfrac{PA}{BP} = \\dfrac{AC}{PD}$，别写错对应关系；\n- 动点在轴上滑动 + 两侧直角 → 一线三直角，列比例方程；\n- 用 AA 证相似但少一个角，图中有"三角共线"结构 → 试**三角形外角定理**或"平角分三段"。',
        tip: '证明骨架（一句话版）：外角定理使 $\\angle ACP = \\angle DPB$，加上 $\\angle A = \\angle B = \\alpha$，AA 成立。',
      },
    ],
    questions: [
      {
        id: 'u4c5q1',
        type: 'judge',
        prompt: '一线三等角（K 字）模型中，直线两侧的两个三角形一定全等。',
        answer: false,
        explain: '一线三等角只能保证两侧三角形**相似**（AA），不一定全等。只有当 $P$ 恰好是 $AB$ 的中点（即 $PA = PB$）时，相似比为 $1$，才升级为全等。',
      },
      {
        id: 'u4c5q2',
        type: 'choice',
        prompt: 'K 字模型中，$\\triangle PAC \\sim \\triangle BPD$ 的对应关系是（$P \\leftrightarrow ?$，$A \\leftrightarrow ?$）？',
        options: [
          '$P\\leftrightarrow A$，$A\\leftrightarrow B$',
          '$P\\leftrightarrow B$，$A\\leftrightarrow P$',
          '$P\\leftrightarrow D$，$A\\leftrightarrow C$',
          '$P\\leftrightarrow P$，$A\\leftrightarrow B$',
        ],
        answer: 1,
        explain: '由 AA 推导，$\\angle PAC = \\angle BPD = \\alpha$，$\\angle ACP = \\angle DPB$，所以 $\\angle APC = \\angle BDP$，对应关系是 $P\\leftrightarrow B$，$A\\leftrightarrow P$，$C\\leftrightarrow D$。',
      },
      {
        id: 'u4c5q3',
        type: 'input',
        prompt: 'K 字模型中，$PA = 3$，$BP = 4$，$AC = 2$。由 $\\dfrac{PA}{BP} = \\dfrac{AC}{PD}$，求 $PD$ 的值（保留分数形式）。',
        accept: ['8/3', '8／3', '8÷3'],
        explain: '$\\dfrac{PA}{BP} = \\dfrac{AC}{PD}$，即 $\\dfrac{3}{4} = \\dfrac{2}{PD}$，解得 $PD = \\dfrac{4 \\times 2}{3} = \\dfrac{8}{3}$。',
      },
      {
        id: 'u4c5q4',
        type: 'choice',
        prompt: '正方形 $ABCD$ 边长 $4$，$E$ 在 $AB$ 上，$AE = 1$，$F$ 在 $BC$ 上，$\\angle DEF = 90^\\circ$。则 $BF = $？',
        options: ['$\\dfrac{1}{4}$', '$\\dfrac{3}{4}$', '$1$', '$\\dfrac{4}{3}$'],
        answer: 1,
        explain: '识别一线三直角（直线 $AB$，三直角 $\\angle A, \\angle DEF, \\angle B$），$\\triangle ADE \\sim \\triangle BEF$。$BE = AB - AE = 3$，由 $\\dfrac{AD}{BE} = \\dfrac{AE}{BF}$，即 $\\dfrac{4}{3} = \\dfrac{1}{BF}$，解得 $BF = \\dfrac{3}{4}$。',
      },
      {
        id: 'u4c5q5',
        type: 'judge',
        prompt: 'K 字模型中，证明第二对对应角相等时，用到的关键定理是三角形外角定理。',
        answer: true,
        explain: '证明 $\\angle ACP = \\angle DPB$ 的关键步骤：$\\triangle PAC$ 在 $P$ 处的外角 $\\angle CPB$，一方面等于 $\\alpha + \\angle ACP$，另一方面等于 $\\alpha + \\angle DPB$（因 $\\angle CPD = \\alpha$）；两者相等推出 $\\angle ACP = \\angle DPB$。用的正是**三角形外角定理**（外角等于不相邻两内角之和）。',
      },
      {
        id: 'u4c5q6',
        type: 'match',
        prompt: '将下列场景与对应的 K 字判断配对。',
        left: [
          '$\\alpha = 90^\\circ$，$PA = PB$',
          '$\\alpha = 90^\\circ$，$PA \\ne PB$',
          '$\\alpha = 60^\\circ$，$PA = PB$',
          '正方形内，边上一点向两邻边各引 $90^\\circ$ 线段',
        ],
        right: [
          '一线三直角，升级为全等（$\\triangle PAC \\cong \\triangle BPD$）',
          '一线三直角，仅相似（$\\triangle PAC \\sim \\triangle BPD$）',
          '$\\alpha = 60^\\circ$ 的 K 字，升级为全等',
          '一线三直角（嵌入正方形的典型配置）',
        ],
        explain: '① $\\alpha = 90^\\circ + PA = PB$ → 全等；② $\\alpha = 90^\\circ + PA \\ne PB$ → 相似；③ $\\alpha = 60^\\circ + PA = PB$ → 全等；④ 正方形边作 $l$，顶点与边上点各 $90^\\circ$ → 一线三直角。',
      },
      {
        id: 'u4c5q7',
        type: 'choice',
        prompt: '矩形 $ABCD$ 中，$AB = 6$，$BC = 8$，动点 $P$ 在 $BC$ 上。过 $P$ 作 $\\angle APQ = 90^\\circ$，$Q$ 在 $CD$ 上。当 $BP = 2$ 时，$CQ$ 等于多少？',
        options: ['$2$', '$3$', '$4$', '$6$'],
        answer: 0,
        explain: '识别一线三直角（直线 $BC$，$\\angle B = 90^\\circ$，$\\angle APQ = 90^\\circ$，$\\angle C = 90^\\circ$），$\\triangle ABP \\sim \\triangle PCQ$（对应 $A\\leftrightarrow P$，$B\\leftrightarrow C$，$P\\leftrightarrow Q$）。比例：$\\dfrac{AB}{PC} = \\dfrac{BP}{CQ}$，$PC = BC - BP = 6$，$\\dfrac{6}{6} = \\dfrac{2}{CQ}$，故 $CQ = 2$。',
      },
      {
        id: 'u4c5q8',
        type: 'judge',
        prompt: '在 K 字模型中，若 $\\alpha = 90^\\circ$ 且 $PA = PB$，则两侧三角形面积相等。',
        answer: true,
        explain: '$PA = PB$ 时 $\\triangle PAC \\cong \\triangle BPD$（全等），全等三角形面积相等。',
      },
    ],
  },
]
