export const LESSONS = [
  {
    id: 'u4c6',
    title: '倍长中线模型',
    subtitle: '见中线就延长一倍，把散落的条件集中到一个三角形里',
    intro: [
      {
        title: '引入：散落的三段，定理用不上',
        body: '在 $\\triangle ABC$ 中，$D$ 是 $BC$ 的中点，$AB = 5$，$AC = 7$。求中线 $AD$ 的取值范围。\n\n大多数人会卡在这里：$AD$ 不是 $\\triangle ABC$ 的边，三角形三边关系 $|a-b| < c < a+b$ 用不上。$AB, AC, AD$ 三段**散在不同位置**，没有一个已知三角形同时包含这三段。\n\n这一卡，正是倍长中线模型存在的意义：**把散落的边"搬"进同一个三角形**。',
        image: 'ex-p3c06-0.svg',
        imageCaption: '倍长中线引入：延长 $AD$ 到 $E$，$DE = AD$，连 $CE$，三段进入 $\\triangle ACE$',
      },
      {
        title: '操作：延长中线，找对顶角，套 SAS',
        body: '**一个动作**：延长 $AD$ 到 $E$，使 $DE = AD$，连 $CE$。\n\n现在比较 $\\triangle ABD$ 与 $\\triangle ECD$：\n- $BD = CD$（$D$ 是 $BC$ 中点，题设）；\n- $\\angle ADB = \\angle EDC$（**对顶角**，自动相等）；\n- $AD = ED$（构造时规定的）。\n\n两边及夹角 → **SAS** → $\\triangle ABD \\cong \\triangle ECD$。\n\n全等立刻给出：$CE = AB = 5$。\n\n**三段进了同一个三角形** $\\triangle ACE$：$AC = 7$，$CE = 5$，$AE = 2AD$。\n\n用三边关系：$|AC - CE| < AE < AC + CE$，即 $2 < 2AD < 12$，故 $1 < AD < 6$。',
        formula: '|AB - AC| < 2 \\cdot AD < AB + AC',
        steps: [
          '延长 $AD$ 到 $E$，$DE = AD$，连 $CE$',
          '$BD = CD$（中点），$\\angle ADB = \\angle EDC$（对顶角），$AD = ED$（构造）',
          'SAS → $\\triangle ABD \\cong \\triangle ECD$，故 $CE = AB = 5$',
          '$\\triangle ACE$：$AC = 7$，$CE = AB = 5$，$AE = 2AD$',
          '三边关系：$|7 - 5| < 2AD < 7 + 5$，得 $1 < AD < 6$',
        ],
      },
      {
        title: '模型提炼：三个视角',
        body: '**倍长中线 $=$ 中心对称构造全等 $=$ 构造平行四边形**，三种视角等价：\n\n- **中心对称视角**：$\\triangle ABD$ 绕 $D$ 旋转 $180^\\circ$ 重合到 $\\triangle ECD$，保长度、保夹角，全等自动成立；\n- **平行四边形视角**：倍长后 $D$ 同时是 $AE$ 的中点和 $BC$ 的中点，四边形 $ABEC$ 的两条对角线互相平分，是**平行四边形**；由此 $AB \\parallel CE$（$\\Rightarrow\\angle B = \\angle DCE$，内错角）；\n- **模型视角**：见中点 → 立刻反射出"倍长"这个动作；夹角永远是**对顶角**，自动相等，不用证。',
        image: 'model-double-median.svg',
        imageCaption: '倍长中线模型：$ABEC$ 是平行四边形，$D$ 为对角线交点，$AB \\parallel CE$，$CE = AB$',
        tip: '倍长哪个端点？从**中点 $D$ 出发**，延长**中线 $AD$** 经过 $D$ 到对侧——别搞反了。方向：$A \\to D \\to E$，$DE = AD$。',
      },
      {
        title: '三大用途',
        body: '倍长中线在中考里有三种典型用法：\n\n**用途 1：求中线长度范围**（引入题）：倍长后用三边关系。\n\n**用途 2：证两段线段相等**：两段散在不同位置 → 倍长中线制造全等 → 对应边相等 → 两段进入同一个三角形。\n\n**用途 3：集中条件，再用勾股**：\n例：$D$ 是 $BC$ 中点，$AD \\perp AB$，$AD = 4$，$AB = 6$，求 $AC$。\n倍长 $AD$ 至 $E$，$DE = AD = 4$，SAS 得 $\\triangle ABD \\cong \\triangle ECD$，$CE = AB = 6$，$\\angle E = \\angle BAD = 90^\\circ$。\n$\\triangle AEC$ 中：$AE = 8$，$CE = 6$，$AC = \\sqrt{AE^2 + CE^2} = \\sqrt{64 + 36} = 10$。',
        image: 'ex-p3c06-3.svg',
        imageCaption: '用途 3：$AD \\perp AB$，$AD = 4$，$AB = 6$，倍长后 $\\triangle AEC$ 是直角三角形，$AC = 10$',
      },
      {
        title: '例：已知中线长求 $AC$（综合应用）',
        body: '**题目**：$\\triangle ABC$ 中 $D$ 是 $BC$ 中点，$AB = 13$，$AC = 5$，$BC = 12$。求中线 $AD$ 的长度。\n\n**思路**：先判断 $\\triangle ABC$ 的形状：$AB^2 = 169$，$AC^2 + BC^2 = 25 + 144 = 169$，$AC^2 + BC^2 = AB^2$，所以 $\\angle ACB = 90^\\circ$（勾股逆定理）。\n\n倍长 $AD$ 到 $E$，$DE = AD$，$CE = AB = 13$，$ABEC$ 是平行四边形。\n\n$AE = 2AD$，在 $\\triangle ACE$ 中用余弦定理（或构造辅助直角）计算 $AD$。\n\n由中线长公式（从倍长中线导出）：\n$AD^2 = \\frac{2AB^2 + 2AC^2 - BC^2}{4} = \\frac{2 \\times 169 + 2 \\times 25 - 144}{4} = \\frac{338 + 50 - 144}{4} = \\frac{244}{4} = 61,$\n故 $AD = \\sqrt{61}$。',
        formula: 'AD^2 = \\frac{2AB^2 + 2AC^2 - BC^2}{4}',
        reveal: {
          q: '$\\triangle ABC$ 中 $D$ 是 $BC$ 中点，$AB = 8$，$AC = 6$，求中线 $AD$ 的取值范围。',
          a: '倍长 $AD$ 到 $E$，$CE = AB = 8$，$\\triangle ACE$：$AC = 6$，$CE = 8$，$AE = 2AD$。三边关系：$|8 - 6| < 2AD < 8 + 6$，即 $2 < 2AD < 14$，故 $1 < AD < 7$。',
        },
      },
      {
        title: '思考路标与易错点',
        body: '**路标（看到 X → 想到 Y）**：\n- 见到**中点 + 题目涉及中线** → 倍长中线；\n- 见到**中点 + 两边 + 中线**，求范围 → 倍长 + 三边关系；\n- 见到**中点 + 两段不在同一三角形且要证相等** → 倍长中线制造全等，把两段"挪近"；\n- 倍长后夹角永远是**对顶角**（自动相等），不用证。\n\n**易错点**：\n1. **延长方向搞反**：是从 $A$ 经 $D$ 到 $E$（$DE = AD$），不是从 $D$ 经 $A$ 到外侧；\n2. **全等结论只用对应边，忘掉对应角**：$\\triangle ABD \\cong \\triangle ECD$ 还给出 $\\angle B = \\angle DCE$，可用来证明 $AB \\parallel CE$；\n3. **倍长不只用于严格中线**：任何"经过中点的连线"都可以倍长；\n4. **混淆倍长中线与中位线**：中位线是连两边**中点**，倍长中线是延长**一条中线**；两者本质相同，但触发时机不同。',
      },
    ],
    questions: [
      {
        id: 'u4c6q1',
        type: 'choice',
        prompt: '$\\triangle ABC$ 中，$D$ 是 $BC$ 的中点，$AB = 5$，$AC = 7$。倍长 $AD$ 到 $E$（$DE = AD$），连 $CE$。由 SAS，$\\triangle ABD \\cong \\triangle ECD$，则 $CE$ 等于？',
        options: ['$5$', '$7$', '$10$', '$12$'],
        answer: 0,
        explain: '$\\triangle ABD \\cong \\triangle ECD$，对应边 $AB = EC$，故 $CE = AB = 5$。',
      },
      {
        id: 'u4c6q2',
        type: 'judge',
        prompt: '倍长中线的证明中，$\\triangle ABD \\cong \\triangle ECD$ 用的是 SAS，其中夹角是"对顶角 $\\angle ADB = \\angle EDC$"。',
        answer: true,
        explain: '三组条件：$BD = CD$（中点），$\\angle ADB = \\angle EDC$（**对顶角**，自动相等），$AD = ED$（构造）。夹角恰好是对顶角，SAS 成立。',
      },
      {
        id: 'u4c6q3',
        type: 'choice',
        prompt: '$\\triangle ABC$ 中，$D$ 是 $BC$ 中点，$AB = 8$，$AC = 6$，中线 $AD = x$。$x$ 的取值范围是？',
        options: [
          '$1 < x < 7$',
          '$2 < x < 14$',
          '$1 < x < 14$',
          '$2 < x < 7$',
        ],
        answer: 0,
        explain: '倍长 $AD$ 到 $E$，$CE = AB = 8$，$\\triangle ACE$：$AC = 6$，$CE = 8$，$AE = 2x$。三边关系：$|8 - 6| < 2x < 8 + 6$，即 $2 < 2x < 14$，故 $1 < x < 7$。',
      },
      {
        id: 'u4c6q4',
        type: 'input',
        prompt: '倍长中线后，$ABEC$ 是平行四边形。这是因为两条对角线 $AE$ 和 $BC$ 在 $D$ 处____（填"互相平分"或"互相垂直"）。',
        accept: ['互相平分', '平分', '互相平分。'],
        explain: '$D$ 是 $BC$ 的中点，$DE = DA$ 使 $D$ 也是 $AE$ 的中点，两条对角线在 $D$ 处**互相平分**，这正是平行四边形的充要条件。',
      },
      {
        id: 'u4c6q5',
        type: 'judge',
        prompt: '若 $\\triangle ABC$ 中 $AD$ 是中线且 $AD \\perp BC$，则可由倍长中线直接推出 $AB = AC$。',
        answer: true,
        explain: '倍长 $AD$ 到 $E$，SAS 得 $\\triangle ABD \\cong \\triangle ECD$，$CE = AB$。同时由全等 $\\angle DCE = \\angle B$，且 $AB \\parallel CE$；又 $AD \\perp BC$ 推出 $AE \\perp BC$，即 $AE \\perp CE$……实际上更直接：$\\triangle ABD$ 与 $\\triangle ACD$ 中，$BD = CD$，$AD = AD$（公共），$\\angle ADB = \\angle ADC = 90^\\circ$（中线 $\\perp$ $BC$），SAS 得 $\\triangle ABD \\cong \\triangle ACD$，对应边 $AB = AC$。',
      },
      {
        id: 'u4c6q6',
        type: 'match',
        prompt: '将下列中点/中线相关场景与最合适的处理方法配对。',
        left: [
          '只有一个中点，题目涉及含该中点的中线长度',
          '有两个中点，分别在三角形两边上',
          '中点 + 要证两段线段相等，两段不在同一三角形',
          '中点 + 已知中线长 + 两边，求另一边',
        ],
        right: [
          '倍长中线，用三边关系',
          '中位线定理（连两边中点，长度为第三边一半）',
          '倍长中线，制造全等后把两段"挪进"同一三角形',
          '倍长中线 + SAS 全等 + 勾股/余弦定理',
        ],
        explain: '① 一个中点 + 中线 → 倍长中线 + 三边关系；② 两个中点 → 中位线；③ 中点 + 两段相等 → 倍长后全等；④ 中点 + 中线长 + 两边 → 倍长后 SSS/SAS + 勾股。',
      },
      {
        id: 'u4c6q7',
        type: 'choice',
        prompt: '$\\triangle ABC$ 中，$D$ 是 $BC$ 中点，$AD = 4$，$AB = 6$，$AD \\perp AB$。由倍长中线求 $AC$ 的值是？',
        options: ['$8$', '$10$', '$\\sqrt{52}$', '$\\sqrt{28}$'],
        answer: 1,
        explain: '倍长 $AD$ 到 $E$，$DE = 4$，$\\triangle ABD \\cong \\triangle ECD$（SAS），$CE = AB = 6$，$\\angle AEC = \\angle BAD = 90^\\circ$（对应角）。$\\triangle AEC$：$AE = 2AD = 8$，$CE = 6$，$\\angle AEC = 90^\\circ$，$AC = \\sqrt{AE^2 + CE^2} = \\sqrt{64 + 36} = \\sqrt{100} = 10$。',
      },
      {
        id: 'u4c6q8',
        type: 'judge',
        prompt: '倍长中线模型的本质是以中点 $D$ 为旋转中心，把 $\\triangle ABD$ 旋转 $180^\\circ$ 得到 $\\triangle ECD$，因此是中心对称构造全等。',
        answer: true,
        explain: '$\\triangle ABD$ 绕 $D$ 旋转 $180^\\circ$：$A \\to E$，$B \\to C$（因为 $BD = CD$，$D$ 是 $BC$ 中点），旋转保距离和夹角，$\\triangle ABD$ 与 $\\triangle ECD$ 全等。这正是**中心对称**（以 $D$ 为对称中心）的几何本质，说法正确。',
      },
    ],
  },
]
