export const LESSONS = [
  {
    id: 'u13c5',
    title: '三角函数综合应用',
    subtitle: '降幂合并 · 辅助角 · 解三角形 · 综合最值',
    intro: [
      {
        title: '三角综合的核心流程',
        body: '高考三角综合几乎都是同一套路：化简 → 合并 → 读性质。先把复杂表达式化为 A sin(ωx+φ)+B 的标准形，再从标准形直接读出最值、单调区间、周期、对称轴。',
        tip: '目标形式：A sin(ωx+φ)+B。一旦到达此形，所有性质显式可读，不再需要额外计算。',
      },
      {
        title: '第一招：降幂（二次变一次）',
        body: '看到 sin²x、cos²x、sin x cos x，立刻降幂：利用半角公式把二次变成含 2x 的一次式，是化简的核心动作。',
        formula: '\\sin^{2}x = \\frac{1-\\cos 2x}{2},\\quad \\cos^{2}x = \\frac{1+\\cos 2x}{2},\\quad 2\\sin x\\cos x = \\sin 2x',
        tip: '通用模板：a sin²x + b sin x cos x + c cos²x = (a+c)/2 + (c−a)/2·cos 2x + b/2·sin 2x，化为 2x 的一次组合+常数。',
      },
      {
        title: '第二招：辅助角（两项合一项）',
        body: '降幂后出现 A sin 2x + B cos 2x 形式，用辅助角公式合并为单个正弦。R 是振幅，φ 由 sin φ = B/R、cos φ = A/R 确定（看系数对应哪个函数）。',
        formula: 'a\\sin\\theta + b\\cos\\theta = \\sqrt{a^{2}+b^{2}}\\sin\\!\\left(\\theta+\\varphi\\right),\\quad \\tan\\varphi = \\frac{b}{a}',
        steps: [
          '必背六个特例：sin x+cos x=√2 sin(x+π/4)；√3 sin x+cos x=2 sin(x+π/6)；',
          'sin x−cos x=√2 sin(x−π/4)；sin x+√3 cos x=2 sin(x+π/3)；',
          '√3 sin x−cos x=2 sin(x−π/6)；sin x−√3 cos x=2 sin(x−π/3)。',
        ],
        tip: '推导口诀：振幅 R=√(a²+b²)，相位 φ 由 sinφ/cosφ=b/a 确定，结合象限选正确区间。',
      },
      {
        title: '从标准形读出所有性质',
        body: '化为 A sin(ωx+φ)+B 后，所有问题都是机械操作：最值用 sin∈[−1,1]；单调区间令内部角在 [−π/2+2kπ, π/2+2kπ] 解 x；对称轴令内部角=π/2+kπ；周期 T=2π/|ω|。',
        steps: [
          '最值：f_max=|A|+B（sin 取+1 时），f_min=−|A|+B（sin 取−1 时）。',
          '单调递增区间：令 −π/2+2kπ ≤ ωx+φ ≤ π/2+2kπ，解出 x 的范围。',
          '对称轴：令 ωx+φ=π/2+kπ，解出 x=（π/2+kπ−φ）/ω。',
        ],
        tip: '解单调区间时，先解内部角的不等式，再除以 ω（注意 ω<0 时不等号方向改变）。',
      },
      {
        title: '解三角形：四大定理的选用',
        body: '解三角形的核心是"已知条件类型决定用哪个公式"。记住四种已知类型与对应工具，选错工具会让计算极其复杂。',
        steps: [
          '两角一边（AAS/ASA）→ 正弦定理：a/sin A = b/sin B = c/sin C = 2R。',
          '两边一夹角（SAS）→ 余弦定理：c²=a²+b²−2ab cos C。',
          '三边（SSS）→ 余弦定理求角，或海伦公式求面积。',
          '两边一对角（SSA）→ 正弦定理，注意可能多解（钝角情形）。',
        ],
        tip: '投影定理（射影定理）：c=a cos B+b cos A，常在条件中隐含，识别出来可大幅简化。',
      },
      {
        title: '三角形中的隐含条件 A+B+C=π',
        body: '凡是三角形问题，A+B+C=π 是永远成立的隐藏条件。由此派生出 sin(A+B)=sin C、cos(A+B)=−cos C 等等式，在化简中频繁出现。',
        formula: 'A+B+C=\\pi \\Rightarrow \\sin(A+B)=\\sin C,\\quad \\cos(A+B)=-\\cos C',
        tip: '看到 sin C 时，想"能否用 sin(A+B) 替代"；看到 cos C 时，想"能否用 −cos(A+B) 替代"。',
      },
      {
        title: '换元法与三角+不等式综合',
        body: '当 sin x 和 cos x 同时出现且乘积关系复杂时，令 t=sin x+cos x=√2 sin(x+π/4)，则 sin x cos x=(t²−1)/2，将两变量问题降为单变量关于 t 的多项式。',
        reveal: {
          q: '求 f(x)=sin x+cos x+sin x cos x 的最大值，应该怎么换元？',
          a: '令 t=sin x+cos x∈[−√2, √2]，则 sin x cos x=(t²−1)/2，f=t+(t²−1)/2=(1/2)(t+1)²−1。t=√2 时取最大值 (1/2)(√2+1)²−1=(1+2√2)/2=1/2+√2。',
        },
      },
      {
        title: '综合压轴：三角+约束最值',
        body: '三角 + 余弦定理 + 基本不等式是高频组合。如"A=π/3，b+c=4，求 a 的最小值"：用余弦定理表达 a²，再用 b+c=4 代入，基本不等式得 bc≤(b+c)²/4=4，从而 a² 最小值可求。',
        tip: '约束最值套路：余弦定理→用已知和/差代换→基本不等式（或配方）求极值。等号取得条件务必写出。',
      },
    ],
    questions: [
      {
        id: 'u13c5q1',
        type: 'choice',
        stem: '已知 $f(x)=\\sin^{2}x+2\\sin x\\cos x+3\\cos^{2}x$，降幂化简后 $f(x)$ 等于',
        options: [
          '$2+\\sqrt{2}\\sin\\!\\left(2x+\\dfrac{\\pi}{4}\\right)$',
          '$2+\\cos 2x+\\sin 2x$',
          '$2+\\sqrt{2}\\sin\\!\\left(2x-\\dfrac{\\pi}{4}\\right)$',
          '$1+\\sin 2x+\\cos 2x$',
        ],
        answer: 0,
        explanation: '降幂：sin²x=(1−cos 2x)/2，cos²x=(1+cos 2x)/2，2sin x cos x=sin 2x。代入：(1−cos 2x)/2+sin 2x+3(1+cos 2x)/2=2+cos 2x+sin 2x。辅助角：sin 2x+cos 2x=√2 sin(2x+π/4)。故 f(x)=2+√2 sin(2x+π/4)。',
      },
      {
        id: 'u13c5q2',
        type: 'choice',
        stem: '已知 $f(x)=2\\sin^{2}\\!\\left(\\dfrac{\\pi}{4}+x\\right)-\\sqrt{3}\\cos 2x$，则 $f(x)$ 化简为',
        options: [
          '$1+2\\sin\\!\\left(2x+\\dfrac{\\pi}{3}\\right)$',
          '$1+\\sin 2x-\\sqrt{3}\\cos 2x$',
          '$1+2\\sin\\!\\left(2x-\\dfrac{\\pi}{3}\\right)$',
          '$2+2\\sin\\!\\left(2x+\\dfrac{\\pi}{6}\\right)$',
        ],
        answer: 2,
        explanation: '2sin²(π/4+x)=1−cos(π/2+2x)=1+sin 2x（因 cos(π/2+2x)=−sin 2x）。故 f=1+sin 2x−√3 cos 2x。辅助角：a=1，b=−√3，R=√(1+3)=2，φ 满足 cosφ=1/2、sinφ=−√3/2，φ=−π/3。故 sin 2x−√3 cos 2x=2sin(2x−π/3)，f=1+2sin(2x−π/3)，选 C。',
      },
      {
        id: 'u13c5q3',
        type: 'judge',
        stem: '六个必背辅助角特例中，$\\sqrt{3}\\sin x+\\cos x=2\\sin\\!\\left(x+\\dfrac{\\pi}{6}\\right)$ 是正确的。',
        answer: true,
        explanation: 'a=√3，b=1，R=√(3+1)=2。tan φ=b/a=1/√3，cos φ=√3/2，sin φ=1/2，φ=π/6。故 √3 sin x+cos x=2sin(x+π/6)。',
      },
      {
        id: 'u13c5q4',
        type: 'choice',
        stem: '已知 $f(x)=\\sqrt{3}\\sin(\\omega x+\\pi/6)+\\cos(\\omega x+\\pi/6)$（$\\omega>0$）最小正周期为 $\\pi$，则 $\\omega=$',
        options: ['$1$', '$2$', '$\\pi$', '$1/2$'],
        answer: 1,
        explanation: '辅助角合并：√3 sinθ+cosθ=2sin(θ+π/6)（θ=ωx+π/6）。故 f(x)=2sin(ωx+π/6+π/6)=2sin(ωx+π/3)。周期 T=2π/ω=π，ω=2。',
      },
      {
        id: 'u13c5q5',
        type: 'choice',
        stem: '在 $\\triangle ABC$ 中，$a=2$，$b\\cos A-a\\cos B=c$，$\\cos C=\\dfrac{1}{3}$，则 $\\triangle ABC$ 的面积为',
        options: [
          '$2\\sqrt{2}$',
          '$4\\sqrt{2}$',
          '$2\\sqrt{3}$',
          '$4$',
        ],
        answer: 1,
        explanation: '投影定理：c=a cosB+b cosA。条件 b cosA−a cosB=c=a cosB+b cosA，化简得 a cosB=0。a=2≠0，故 cosB=0，B=π/2。sin C=√(1−1/9)=2√2/3，sin A=cos C=1/3（A=π/2−C）。由正弦定理：a/sin A=2/(1/3)=6，c=6 sin C=6·2√2/3=4√2。面积=（1/2）·a·c=（1/2）·2·4√2=4√2。',
      },
      {
        id: 'u13c5q6',
        type: 'input',
        stem: '在 $\\triangle ABC$ 中，$A=\\dfrac{\\pi}{3}$，$b+c=4$。由余弦定理 $a^{2}=b^{2}+c^{2}-bc=16-3bc$，再由均值不等式 $bc\\leq 4$，则 $a$ 的最小值为',
        answer: '2',
        explanation: 'a²=b²+c²−2bc cos(π/3)=b²+c²−bc=(b+c)²−3bc=16−3bc。bc≤(b+c)²/4=4，等号 b=c=2。a²_min=16−12=4，a_min=2（等边三角形）。',
      },
      {
        id: 'u13c5q7',
        type: 'match',
        stem: '将下列三角化简问题与对应的"关键第一步"配对。',
        left: [
          '$f(x)=\\sin^{2}x-\\cos^{2}x$',
          '$f(x)=\\sin x+\\cos x+\\sin x\\cos x$',
          '$f(x)=2\\cos^{2}(x/2)-1$',
        ],
        right: [
          '令 $t=\\sin x+\\cos x$，则 $\\sin x\\cos x=(t^{2}-1)/2$',
          '利用二倍角：$2\\cos^{2}(x/2)-1=\\cos x$',
          '利用降幂：$\\sin^{2}x-\\cos^{2}x=-\\cos 2x$',
        ],
        answer: [2, 0, 1],
        explanation: 'sin²x−cos²x=−(cos²x−sin²x)=−cos 2x（降幂/倍角）；sin x+cos x+sin x cos x 令 t 换元；2cos²(x/2)−1=cos x 是倍角公式反向。',
      },
      {
        id: 'u13c5q8',
        type: 'choice',
        stem: '在 $\\triangle ABC$ 中，$2\\cos C(a\\cos B+b\\cos A)=c$，则角 $C=$',
        options: [
          '$\\dfrac{\\pi}{6}$',
          '$\\dfrac{\\pi}{3}$',
          '$\\dfrac{\\pi}{2}$',
          '$\\dfrac{2\\pi}{3}$',
        ],
        answer: 1,
        explanation: '由投影定理 a cosB+b cosA=c，代入得 2c cosC=c，故 cosC=1/2，C=π/3。',
      },
      {
        id: 'u13c5q9',
        type: 'judge',
        stem: '已知 $A+B+C=\\pi$，则 $\\sin(A+B)=\\sin C$，$\\cos(A+B)=-\\cos C$，这两个等式都正确。',
        answer: true,
        explanation: 'A+B=π−C，故 sin(A+B)=sin(π−C)=sin C；cos(A+B)=cos(π−C)=−cos C。两式均由补角公式直接得出，是解三角形化简中的常用隐含条件。',
      },
    ],
  },
]
