export const LESSONS = [
  {
    id: 'u13c2',
    title: '存在性与任意性：语义转化压轴',
    subtitle: '存在↔最值反向 · 任意↔最值同向 · 双变量嵌套',
    intro: [
      {
        title: '核心口诀：存在与任意的方向',
        body: '含参不等式中最容易混淆的是量词的翻译。记住：存在→最值反方向；任意→最值同方向。方向搞反，答案必错。',
        tip: '"存在 x 使 f(x)≥M" → max f≥M（找最大）；"任意 x 都有 f(x)≥M" → min f≥M（找最小）。',
      },
      {
        title: '四种基本组合的完整对照表',
        body: '将原问题与等价最值条件一一对应，是解题的第一步。先把语言翻译准确，后续的求最值过程才不会方向错误。',
        steps: [
          '存在 x 使 f(x)≥M ⟺ max f(x)≥M',
          '存在 x 使 f(x)≤M ⟺ min f(x)≤M',
          '任意 x 都有 f(x)≥M ⟺ min f(x)≥M',
          '任意 x 都有 f(x)≤M ⟺ max f(x)≤M',
        ],
        tip: '记忆口诀：存在→反方向（≥M 看 max；≤M 看 min）；任意→同方向（≥M 看 min；≤M 看 max）。',
      },
      {
        title: '参数分离降维：把含参变为无参',
        body: '当不等式可以改写为"a≥g(x)"或"a≤g(x)"形式时，参数 a 孤立到一侧，g(x) 不含参，其极值可以直接用导数求。进一步利用量词对应关系确定 a 的范围。',
        formula: 'f(x) \\geq M \\xrightarrow{\\text{变形}} a \\geq h(x) \\xrightarrow{\\text{任意 }x} a \\geq \\max h(x)',
        tip: '参数分离的前提：a 在不等式中线性出现（只出现一次）且容易孤立。',
      },
      {
        title: '含参讨论求最值的三步流程',
        body: '参数分离不可行时，直接对含参函数 f(x;a) 求最值。步骤：① 求 f\'(x)，分类讨论 a 的范围；② 求各情形下的极值或端点值；③ 代入量词不等式得到 a 的范围。',
        steps: [
          '情形 A：a≤临界值，f 单调，最值在端点取得。',
          '情形 B：a>临界值，f 有内部极值点，最值在极值点处取得。',
          '合并两情形的结论。',
        ],
        tip: '两种方法（参数分离 vs 含参讨论）殊途同归，能用参数分离优先用，更简洁。',
      },
      {
        title: '端点极限必须检查',
        body: '开区间或无界区间上，最值未必存在，要用上确界/下确界。函数趋向端点时若趋于±∞，说明 sup=+∞ 或 inf=−∞，需据此判断"存在性"是否自动满足。',
        formula: '\\lim_{x \\to 0^{+}} (-\\ln x) = +\\infty \\Rightarrow \\sup_{x>0} f(x) = +\\infty',
        tip: '验证"存在 x 使 f(x)≥M"时，若 sup f=+∞，任意 M 都满足，答案为所有 a。',
      },
      {
        title: '双变量嵌套：任意-存在的值域翻译',
        body: '"对任意 x₁，存在 x₂ 使 f(x₁)=g(x₂)"等价于 f 的值域 ⊆ g 的值域。这是双变量嵌套问题的核心翻译，把两个量词问题变成集合包含问题。',
        steps: [
          '∀x₁ ∃x₂ 使 f(x₁)=g(x₂) ⟺ 值域(f) ⊆ 值域(g)。',
          '∀x₁ ∃x₂ 使 f(x₁)≤g(x₂) ⟺ max f ≤ max g。',
          '∃x₁ ∀x₂ 都有 f(x₁)≤g(x₂) ⟺ min f ≤ min g。',
        ],
        tip: '两个量词都是"存在"时，只需 f 和 g 的值域有交集即可。',
      },
      {
        title: '易错点与验算策略',
        body: '① 量词翻译反方向（最常见）；② 开区间端点漏判；③ 参数分离时乘以 x（正负号变化）需先确认 x 的符号；④ 双变量嵌套忘记先求各函数值域。写完后，代一个临界值的 a 验算，能快速发现方向错误。',
        reveal: {
          q: '已知 f(x)=x+a/x（x>0），"存在 x∈[1,4] 使 f(x)≤5"等价于什么最值条件？',
          a: '等价于 min_{x∈[1,4]} f(x)≤5。再用参数分离：f(x)≤5 ⟺ a≤5x−x²，存在 x 成立 ⟺ a≤max_{[1,4]}(5x−x²)=25/4。故 a≤25/4。',
        },
      },
    ],
    questions: [
      {
        id: 'u13c2q1',
        type: 'choice',
        stem: '"存在 $x>0$ 使 $f(x)\\leq 0$"等价于',
        options: [
          '$\\max_{x>0} f(x) \\leq 0$',
          '$\\min_{x>0} f(x) \\leq 0$',
          '$\\max_{x>0} f(x) \\geq 0$',
          '$\\min_{x>0} f(x) \\geq 0$',
        ],
        answer: 1,
        explanation: '"存在 x 使 f(x)≤0" ⟺ f 的最小值≤0（取最容易满足"≤0"的那个 x，即取 min）。存在 + ≤0 → min f≤0。',
      },
      {
        id: 'u13c2q2',
        type: 'choice',
        stem: '已知 $f(x) = \\ln x + \\dfrac{a}{x}$（$x\\geq 1$，$a\\in\\mathbb{R}$）。若对任意 $x\\geq 1$ 都有 $f(x)\\geq 1$，则 $a$ 的取值范围是',
        options: [
          '$a \\leq 1$',
          '$a = 1$',
          '$a \\geq 1$',
          '$a > 0$',
        ],
        answer: 2,
        explanation: '翻译：min_{x≥1} f(x)≥1。参数分离：a≥x(1−ln x)=h(x)；∀x≥1 成立 ⟺ a≥max_{x≥1} h(x)。h\'(x)=−ln x≤0（x≥1），h 递减，max h=h(1)=1。故 a≥1。',
      },
      {
        id: 'u13c2q3',
        type: 'judge',
        stem: '"对任意 $x\\in\\mathbb{R}$ 都有 $f(x)\\geq M$"等价于"$f(x)$ 的最大值 $\\geq M$"。',
        answer: false,
        explanation: '"任意 x 都有 f(x)≥M" ⟺ min f(x)≥M，而非最大值≥M。任意→同方向：f(x)≥M 看 min，需最小值也≥M。',
      },
      {
        id: 'u13c2q4',
        type: 'choice',
        stem: '已知 $f(x) = x^{2} - 2ax + 1$（$x\\in[1,3]$）。若对任意 $x\\in[1,3]$ 都有 $f(x)\\geq 0$，则 $a$ 的范围是',
        options: [
          '$a \\leq 1$',
          '$a \\leq \\sqrt{2}$',
          '$a \\leq 2\\sqrt{2}$',
          '$a \\leq 1$ 或 $a \\geq 3$',
        ],
        answer: 0,
        explanation: '参数分离：f(x)≥0 ⟺ 2ax≤x²+1 ⟺ a≤(x²+1)/(2x)=x/2+1/(2x)=h(x)。∀x∈[1,3] 成立 ⟺ a≤min_{[1,3]} h(x)。h\'(x)=(x²−1)/(2x²)≥0（x≥1），h 递增，min h=h(1)=1。故 a≤1。',
      },
      {
        id: 'u13c2q5',
        type: 'choice',
        stem: '已知 $f(x) = e^{x} - ax$（$x\\geq 0$）。若对任意 $x\\geq 0$ 都有 $f(x)\\geq 1$，则 $a$ 的范围是',
        options: [
          '$a < 0$',
          '$0 < a \\leq 1$',
          '$a \\leq 1$',
          '$a \\geq 1$',
        ],
        answer: 2,
        explanation: 'f(0)=1 自动满足。f\'(x)=eˣ−a。若 a≤1：f\'(x)≥eˣ−1≥0（x≥0），f 递增，min f=f(0)=1，满足。若 a>1：f\'(x₀)=0 ⟹ x₀=ln a>0，f(ln a)=a−a ln a=a(1−ln a)。a>e 时<0，a∈(1,e) 时>0 需验证：实际 a(1−ln a)<1（因为 a>1 时…）。精确验证 a=e：f(1)=e−e=0<1，不满足。故 a≤1。',
      },
      {
        id: 'u13c2q6',
        type: 'judge',
        stem: '"存在 $x\\in I$ 使 $a\\leq g(x)$"等价于"$a\\leq\\max_{x\\in I} g(x)$"。',
        answer: true,
        explanation: '存在某个 x 使 a≤g(x) 成立，只需找一个 g(x) 足够大的点即可，即 a 不超过 g 的最大值。存在 + a≤g(x) → a≤max g(x)。',
      },
      {
        id: 'u13c2q7',
        type: 'match',
        stem: '将下列"量词+不等式"翻译为对应的最值条件。',
        left: [
          '存在 $x$ 使 $f(x)\\geq M$',
          '任意 $x$ 都有 $f(x)\\leq M$',
          '存在 $x$ 使 $f(x)\\leq M$',
        ],
        right: [
          '$\\min f(x) \\leq M$',
          '$\\max f(x) \\leq M$',
          '$\\max f(x) \\geq M$',
        ],
        answer: [2, 1, 0],
        explanation: '存在+≥M → max≥M；任意+≤M → max≤M；存在+≤M → min≤M。口诀：存在反方向，任意同方向。',
      },
      {
        id: 'u13c2q8',
        type: 'choice',
        stem: '已知 $f(x)=x^{2}+1$（$x\\in[0,2]$），$g(x)=ax-1$（$x\\in[0,1]$）。若对任意 $x_{1}\\in[0,2]$，存在 $x_{2}\\in[0,1]$ 使 $g(x_{2})\\geq f(x_{1})$，则 $a$ 的取值范围是',
        options: [
          '$a \\geq 4$',
          '$a \\geq 6$',
          '$a \\geq 5$',
          '$a \\geq 3$',
        ],
        answer: 1,
        explanation: '翻译：∀x₁ ∃x₂ 使 g(x₂)≥f(x₁) ⟺ max g(x₂)≥max f(x₁)。max f=f(2)=5。a>0 时 max g=g(1)=a−1；a−1≥5 ⟹ a≥6。a≤0 时 max g=−1<5，不满足。故 a≥6。',
      },
      {
        id: 'u13c2q9',
        type: 'input',
        stem: '已知 $f(x)=\\dfrac{x^{2}+a}{x+1}$（$x>-1$）。若存在 $x>-1$ 使 $f(x)<0$，则 $a<$ ______（填写数值）。',
        answer: '0',
        explanation: 'x+1>0，f(x)<0 ⟺ x²+a<0 ⟺ a<−x²。存在 x>−1 使成立 ⟺ a<max_{x>−1}(−x²)。−x² 在 x=0 处最大，max=0。故 a<0。',
      },
    ],
  },
]
