import type { Unit } from '../../types'

export const PART2_UNITS: Unit[] = [
  // ===================== 单元 4：图像·定义域·单调性 =====================
  {
    id: 'u4',
    title: '图像·定义域·单调性',
    color: '#ff9600',
    icon: '📉',
    blurb: '对数图像是指数图像关于 y=x 的镜像：定义域 x>0、值域 R、过 (1,0)、以 y 轴为渐近线，单调性看底数。',
    lessons: [
      {
        id: 'u4-l1',
        title: '从指数图像得到对数图像',
        subtitle: '互为反函数、关于 $y=x$ 对称',
        questions: [
          {
            id: 'u4-l1-q1',
            type: 'choice',
            prompt: '$y=a^x$ 与 $y=\\log_a x$ 的图像关于哪条直线对称？',
            options: ['$x$ 轴', '$y$ 轴', '直线 $y=x$', '原点'],
            answer: 2,
            explain: '两者互为反函数，反函数图像关于直线 $y=x$ 对称——本质是把横纵坐标对调。',
          },
          {
            id: 'u4-l1-q2',
            type: 'choice',
            prompt: '指数函数过点 $(0,1)$，那么对数函数 $y=\\log_a x$ 一定过哪个点？',
            options: ['$(1,0)$', '$(0,1)$', '$(0,0)$', '$(a,1)$'],
            answer: 0,
            explain: '把 $(0,1)$ 的横纵坐标对调得 $(1,0)$。所以任何 $y=\\log_a x$ 都过 $(1,0)$，即 $\\log_a 1=0$。',
          },
          {
            id: 'u4-l1-q3',
            type: 'judge',
            prompt: '判断：若指数图像经过 $(u,a^u)$，则对数图像经过 $(a^u,u)$。',
            answer: true,
            explain: '反函数把每个点 $(x,y)$ 换成 $(y,x)$。$(u,a^u)\\to(a^u,u)$，正是横纵坐标交换。',
          },
          {
            id: 'u4-l1-q4',
            type: 'input',
            prompt: '$y=\\log_5 x$ 一定过点 $(\\,?\\,,1)$，横坐标是多少？',
            accept: ['5'],
            placeholder: '输入一个数',
            explain: '$\\log_5 5=1$，所以过 $(5,1)$。一般地 $y=\\log_a x$ 过 $(a,1)$。',
          },
          {
            id: 'u4-l1-q5',
            type: 'match',
            prompt: '把指数图像上的点与对应的对数图像上的点配对（互换坐标）。',
            left: ['$(0,1)$', '$(1,2)$', '$(2,4)$', '$(-1,\\tfrac12)$'],
            right: ['$(1,0)$', '$(2,1)$', '$(4,2)$', '$(\\tfrac12,-1)$'],
            explain: '反函数就是把每个 $(x,y)$ 变成 $(y,x)$，所以一一对应地交换坐标即可。',
          },
        ],
      },
      {
        id: 'u4-l2',
        title: '定义域、值域与渐近线',
        subtitle: '为什么真数必须 $>0$',
        questions: [
          {
            id: 'u4-l2-q1',
            type: 'choice',
            prompt: '$y=\\log_a x$ 的定义域是什么？',
            options: ['$\\mathbb R$', '$(0,+\\infty)$', '$[0,+\\infty)$', '$(-\\infty,0)$'],
            answer: 1,
            explain: '因为 $a^x>0$ 恒成立，反函数的输入（即真数）必须为正：定义域 $(0,+\\infty)$。',
          },
          {
            id: 'u4-l2-q2',
            type: 'choice',
            prompt: '$y=\\log_a x$ 的值域是什么？',
            options: ['$(0,+\\infty)$', '$[0,+\\infty)$', '$\\mathbb R$', '$(1,+\\infty)$'],
            answer: 2,
            explain: '指数函数的输入可取任意实数，对调后对数函数的输出也覆盖整个 $\\mathbb R$。',
          },
          {
            id: 'u4-l2-q3',
            type: 'judge',
            prompt: '判断：$x=0$ 是 $y=\\log_a x$ 可以取到的一个点。',
            answer: false,
            explain: '$x=0$ 不在定义域内，它是竖直渐近线 $x=0$，函数无限靠近但取不到。',
          },
          {
            id: 'u4-l2-q4',
            type: 'input',
            prompt: '求 $y=\\log_2(x-3)$ 的定义域用区间表示，下界端点是多少？',
            accept: ['3'],
            placeholder: '输入一个数',
            explain: '真数 $x-3>0\\Rightarrow x>3$，定义域 $(3,+\\infty)$，竖直渐近线 $x=3$。',
          },
          {
            id: 'u4-l2-q5',
            type: 'choice',
            prompt: '求 $y=\\ln\\dfrac{1}{x^2-1}$ 的定义域。',
            options: [
              '$(-1,1)$',
              '$(-\\infty,-1)\\cup(1,+\\infty)$',
              '$\\mathbb R$',
              '$(1,+\\infty)$',
            ],
            answer: 1,
            explain: '真数 $\\dfrac{1}{x^2-1}>0\\Rightarrow x^2-1>0\\Rightarrow |x|>1$，即 $(-\\infty,-1)\\cup(1,+\\infty)$。',
          },
          {
            id: 'u4-l2-q6',
            type: 'match',
            prompt: '把每个函数与它的定义域配对（先令真数 $>0$）。',
            left: ['$\\log_2 x$', '$\\log_2(x-3)$', '$\\log_2(x+2)$', '$\\ln\\dfrac{1}{x^2-1}$'],
            right: ['$(0,+\\infty)$', '$(3,+\\infty)$', '$(-2,+\\infty)$', '$(-\\infty,-1)\\cup(1,+\\infty)$'],
            explain: '定义域永远由“真数 $>0$”决定，水平平移会平移定义域，复合式要逐层检查。',
          },
        ],
      },
      {
        id: 'u4-l3',
        title: '单调性与符号',
        subtitle: '$a>1$ 增 / $0<a<1$ 减',
        questions: [
          {
            id: 'u4-l3-q1',
            type: 'choice',
            prompt: '当 $a>1$ 时，$y=\\log_a x$ 在定义域上是？',
            options: ['递增', '递减', '先增后减', '不单调'],
            answer: 0,
            explain: '反函数保留单调方向。$a>1$ 时 $a^x$ 递增，故 $\\log_a x$ 也递增。',
          },
          {
            id: 'u4-l3-q2',
            type: 'judge',
            prompt: '判断：因为 $0<\\tfrac12<1$，所以 $y=\\log_{1/2}x$ 递减。',
            answer: true,
            explain: '底数在 $0$ 与 $1$ 之间时对数函数递减：$x$ 越大，$\\log_{1/2}x$ 越小。',
          },
          {
            id: 'u4-l3-q3',
            type: 'choice',
            prompt: '比较 $\\log_{1/3}2$ 与 $\\log_{1/3}5$ 的大小。',
            options: [
              '$\\log_{1/3}2<\\log_{1/3}5$',
              '$\\log_{1/3}2>\\log_{1/3}5$',
              '两者相等',
              '无法比较',
            ],
            answer: 1,
            explain: '底数 $\\tfrac13$ 在 $(0,1)$，函数递减；$2<5$ 时函数值反过来，故 $\\log_{1/3}2>\\log_{1/3}5$。',
          },
          {
            id: 'u4-l3-q4',
            type: 'choice',
            prompt: '当 $a>1$ 且 $0<x<1$ 时，$\\log_a x$ 的符号是？',
            options: ['正', '负', '零', '不确定'],
            answer: 1,
            explain: '$a>1$ 时函数递增、在 $x=1$ 取零；$x<1$ 落在零点左侧，故 $\\log_a x<0$。',
          },
          {
            id: 'u4-l3-q5',
            type: 'input',
            prompt: '$y=\\log_{1/2}(x^2-2x-3)$ 的单调递增区间是 $(-\\infty,?)$，问号处填什么？',
            accept: ['-1'],
            placeholder: '输入一个整数',
            explain: '定义域 $x<-1$ 或 $x>3$。内层在 $(-\\infty,-1)$ 上递减，外层 $\\log_{1/2}$ 递减，异减得增，故递增区间 $(-\\infty,-1)$。',
          },
          {
            id: 'u4-l3-q6',
            type: 'match',
            prompt: '把每个对数值与它的符号配对（注意底数与真数同 1 比较）。',
            left: ['$\\log_2 3$', '$\\log_2 \\tfrac12$', '$\\log_{1/2}3$', '$\\log_{1/2}\\tfrac12$'],
            right: ['正', '负', '负', '正'],
            explain: '$a>1$：真数 $>1$ 为正、$<1$ 为负；$0<a<1$ 时正好相反。',
          },
        ],
      },
    ],
  },

  // ===================== 单元 5：变换·比较 =====================
  {
    id: 'u5',
    title: '变换·比较',
    color: '#ff4b4b',
    icon: '🔄',
    blurb: '平移、翻折与反函数关系，再到不同底对数大小的比较；先抓真数为零的位置，是分析变换的稳定起点。',
    lessons: [
      {
        id: 'u5-l1',
        title: '反函数与对称',
        subtitle: '$a^x$ 与 $\\log_a x$ 关于 $y=x$ 互逆',
        questions: [
          {
            id: 'u5-l1-q1',
            type: 'choice',
            prompt: '下列哪个函数是 $y=2^x$ 的反函数？',
            options: ['$y=2^{-x}$', '$y=\\log_2 x$', '$y=\\log_{1/2}x$', '$y=x^2$'],
            answer: 1,
            explain: '同底指数与对数互为反函数，所以 $y=2^x$ 的反函数是 $y=\\log_2 x$。',
          },
          {
            id: 'u5-l1-q2',
            type: 'judge',
            prompt: '判断：$y=2^x$ 上的点 $(1,2)$ 在 $y=\\log_2 x$ 上对应点 $(2,1)$。',
            answer: true,
            explain: '反函数把每对点的横纵坐标互换，$(1,2)\\leftrightarrow(2,1)$，且都被 $y=x$ 垂直平分。',
          },
          {
            id: 'u5-l1-q3',
            type: 'choice',
            prompt: '$y=-\\log_3 x$ 与 $y=\\log_3 x$ 的图像是什么关系？',
            options: ['关于 $y$ 轴对称', '关于 $x$ 轴对称', '关于 $y=x$ 对称', '完全重合'],
            answer: 1,
            explain: '给整个 $y$ 取相反数就是关于 $x$ 轴翻折。$\\log_3 x$ 递增，$-\\log_3 x$ 则递减。',
          },
          {
            id: 'u5-l1-q4',
            type: 'input',
            prompt: '$y=2^x$ 与 $y=\\log_2 x$ 的图像关于直线 $y=?\\,x$ 对称，系数填多少？',
            accept: ['1'],
            placeholder: '输入一个数',
            explain: '互为反函数的图像关于 $y=x$ 对称，即系数为 1。',
          },
          {
            id: 'u5-l1-q5',
            type: 'match',
            prompt: '把 $y=3^x$ 上的点与 $y=\\log_3 x$ 上对应的点配对。',
            left: ['$(0,1)$', '$(1,3)$', '$(2,9)$', '$(-1,\\tfrac13)$'],
            right: ['$(1,0)$', '$(3,1)$', '$(9,2)$', '$(\\tfrac13,-1)$'],
            explain: '反函数互换坐标，每对点都关于 $y=x$ 对称。',
          },
        ],
      },
      {
        id: 'u5-l2',
        title: '平移、伸缩与翻折',
        subtitle: '先找真数为零的位置',
        questions: [
          {
            id: 'u5-l2-q1',
            type: 'choice',
            prompt: '$y=\\log_2(x+4)-1$ 是由 $y=\\log_2 x$ 怎样平移得到的？',
            options: [
              '右移 4、上移 1',
              '左移 4、下移 1',
              '左移 4、上移 1',
              '右移 4、下移 1',
            ],
            answer: 1,
            explain: '$x\\to x+4$ 是左移 4，外层 $-1$ 是下移 1。渐近线随之从 $x=0$ 移到 $x=-4$。',
          },
          {
            id: 'u5-l2-q2',
            type: 'input',
            prompt: '$y=\\log_3(x+2)-4$ 的竖直渐近线是 $x=?$，填多少？',
            accept: ['-2'],
            placeholder: '输入一个整数',
            explain: '先令真数为 0：$x+2=0\\Rightarrow x=-2$。这就是渐近线，也是定义域下界。',
          },
          {
            id: 'u5-l2-q3',
            type: 'judge',
            prompt: '判断：分析 $y=\\log_a(x-h)+k$ 时，先找真数为 0 的位置最有效。',
            answer: true,
            explain: '真数为 0 的位置直接给出竖直渐近线和定义域边界，是后续平移分析的稳定起点。',
          },
          {
            id: 'u5-l2-q4',
            type: 'choice',
            prompt: '$y=\\log_a(bx)$（$b>0$）利用运算律可写成什么？',
            options: [
              '$\\log_a b\\cdot\\log_a x$',
              '$\\log_a b+\\log_a x$',
              '$\\log_a(b+x)$',
              '$b\\log_a x$',
            ],
            answer: 1,
            explain: '$\\log_a(bx)=\\log_a b+\\log_a x$，所以真数里乘常数本质是**纵向平移**，而非横向缩放。',
          },
          {
            id: 'u5-l2-q5',
            type: 'input',
            prompt: '$y=\\log_2(8x)$ 相当于把 $y=\\log_2 x$ 上移多少个单位？',
            accept: ['3'],
            placeholder: '输入一个整数',
            explain: '$\\log_2(8x)=\\log_2 8+\\log_2 x=3+\\log_2 x$，故上移 3 个单位。',
          },
          {
            id: 'u5-l2-q6',
            type: 'match',
            prompt: '把每个变换与它对解析式的作用配对（基准 $y=\\log_a x$）。',
            left: ['右移 $h$', '上移 $k$', '关于 $x$ 轴翻折', '真数乘 $b>0$'],
            right: ['$x\\to x-h$', '$+k$', '整个 $y$ 取相反数', '等价上移 $\\log_a b$'],
            explain: '水平变换作用在 $x$ 上、竖直平移加常数、翻折给 $y$ 取相反数；真数乘常数靠运算律变成纵向平移。',
          },
        ],
      },
      {
        id: 'u5-l3',
        title: '不同底数的比较',
        subtitle: '换底公式与中间值法',
        questions: [
          {
            id: 'u5-l3-q1',
            type: 'input',
            prompt: '换底公式：$\\log_a x=\\dfrac{\\ln x}{\\ln\\,?}$，问号处填什么？',
            accept: ['a'],
            placeholder: '填底数',
            explain: '$\\log_a x=\\dfrac{\\ln x}{\\ln a}$。任意底都能用自然对数（或任一公共底）统一表达。',
          },
          {
            id: 'u5-l3-q2',
            type: 'choice',
            prompt: '比较 $\\log_2 8$ 与 $\\log_4 8$ 的大小。',
            options: [
              '$\\log_2 8<\\log_4 8$',
              '$\\log_2 8>\\log_4 8$',
              '两者相等',
              '无法比较',
            ],
            answer: 1,
            explain: '$\\log_2 8=3$，$\\log_4 8=\\tfrac32$。同一真数（$>1$）下底数越大对数越小，故 $\\log_2 8>\\log_4 8$。',
          },
          {
            id: 'u5-l3-q3',
            type: 'choice',
            prompt: '比较 $\\log_2 \\tfrac18$ 与 $\\log_4 \\tfrac18$（注意都是负数）。',
            options: [
              '$\\log_2 \\tfrac18<\\log_4 \\tfrac18$',
              '$\\log_2 \\tfrac18>\\log_4 \\tfrac18$',
              '两者相等',
              '无法比较',
            ],
            answer: 0,
            explain: '$\\log_2 \\tfrac18=-3$，$\\log_4 \\tfrac18=-\\tfrac32$。$-3<-\\tfrac32$，故 $\\log_2 \\tfrac18<\\log_4 \\tfrac18$。',
          },
          {
            id: 'u5-l3-q4',
            type: 'judge',
            prompt: '判断：$\\log_2 3\\cdot\\log_3 2=1$。',
            answer: true,
            explain: '$\\log_a b$ 与 $\\log_b a$ 互为倒数：$\\dfrac{\\ln 3}{\\ln 2}\\cdot\\dfrac{\\ln 2}{\\ln 3}=1$。',
          },
          {
            id: 'u5-l3-q5',
            type: 'choice',
            prompt: '不用计算器，比较 $A=\\log_2 3$ 与 $B=\\log_3 5$，借助中间值 $\\tfrac32$。',
            options: [
              '$A<B$',
              '$A>B$',
              '$A=B$',
              '都等于 $\\tfrac32$',
            ],
            answer: 1,
            explain: '$\\log_2 3>\\tfrac32\\iff 3>2\\sqrt2$（即 $9>8$）成立；$\\log_3 5<\\tfrac32\\iff 5<3\\sqrt3$（即 $25<27$）成立。故 $B<\\tfrac32<A$。',
          },
          {
            id: 'u5-l3-q6',
            type: 'match',
            prompt: '把每个对数值与它的结果配对。',
            left: ['$\\log_2 8$', '$\\log_4 8$', '$\\log_2 \\tfrac18$', '$\\log_4 \\tfrac18$'],
            right: ['$3$', '$\\tfrac32$', '$-3$', '$-\\tfrac32$'],
            explain: '同一真数下底数越大对数越小；$0<x<1$ 时对数为负，比较时务必核对符号。增长层级 $\\ln x\\ll x^\\alpha\\ll a^x$ 也提醒：慢不等于停。',
          },
        ],
      },
    ],
  },

  // ===================== 单元 6：常用对数·自然对数·标度 =====================
  {
    id: 'u6',
    title: '常用对数·自然对数·标度',
    color: '#2bd4a6',
    icon: '📏',
    blurb: '$\\lg$ 看十进制数量级，$\\ln$ 连接连续变化；对数标度把 pH、分贝、震级等巨大跨度压成等距刻度。',
    lessons: [
      {
        id: 'u6-l1',
        title: '常用对数与自然对数',
        subtitle: '$\\lg=\\log_{10}$、$\\ln=\\log_e$',
        questions: [
          {
            id: 'u6-l1-q1',
            type: 'input',
            prompt: '计算 $\\lg 1000$。',
            accept: ['3'],
            placeholder: '输入一个整数',
            explain: '$\\lg 1000=\\lg 10^3=3$。常用对数 $\\lg 10^n=n$，直接读出数量级。',
          },
          {
            id: 'u6-l1-q2',
            type: 'input',
            prompt: '计算 $\\lg 100+\\lg 0.001+\\ln e^4$。',
            accept: ['3'],
            placeholder: '输入一个整数',
            explain: '$\\lg 100=2$，$\\lg 0.001=-3$，$\\ln e^4=4$，合计 $2-3+4=3$。',
          },
          {
            id: 'u6-l1-q3',
            type: 'choice',
            prompt: '自然对数为什么在微积分中特别自然？',
            options: [
              '因为 $\\dfrac{d}{dx}\\ln x=\\dfrac1x$，且 $a^x=e^{x\\ln a}$',
              '因为 $e=3$',
              '因为它比 $\\lg$ 好写',
              '因为底数是整数',
            ],
            answer: 0,
            explain: '$\\ln$ 的导数最简洁，且任意指数都能统一写成 $a^x=e^{x\\ln a}$，是连接连续变化的自然坐标。',
          },
          {
            id: 'u6-l1-q4',
            type: 'judge',
            prompt: '判断：$\\ln x$ 只是 $\\lg x$ 的另一种记号，二者没有本质区别。',
            answer: false,
            explain: '它们只差常数倍 $\\ln x=\\lg x\\cdot\\ln 10$，但 $\\ln$ 在导数 $(\\ln x)^{\\prime}=\\tfrac1x$ 上有特殊地位，不只是换记号。',
          },
          {
            id: 'u6-l1-q5',
            type: 'match',
            prompt: '把每个对数表达式与它的值（或等价形式）配对。',
            left: ['$\\lg 10^6$', '$\\ln e^4$', '$\\lg 0.001$', '$\\log_2 x$'],
            right: ['$6$', '$4$', '$-3$', '$\\dfrac{\\ln x}{\\ln 2}$'],
            explain: '$\\lg 10^n=n$、$\\ln e^n=n$；换底 $\\log_2 x=\\dfrac{\\ln x}{\\ln 2}$，不同底只差固定比例。',
          },
        ],
      },
      {
        id: 'u6-l2',
        title: '对数尺度：pH 与分贝',
        subtitle: '刻度差 1 = 原始量乘固定倍率',
        questions: [
          {
            id: 'u6-l2-q1',
            type: 'choice',
            prompt: 'pH 的定义是？',
            options: [
              '$\\mathrm{pH}=\\lg[\\mathrm H^+]$',
              '$\\mathrm{pH}=-\\lg[\\mathrm H^+]$',
              '$\\mathrm{pH}=-\\ln[\\mathrm H^+]$',
              '$\\mathrm{pH}=[\\mathrm H^+]$',
            ],
            answer: 1,
            explain: '$\\mathrm{pH}=-\\lg[\\mathrm H^+]$：氢离子浓度的负常用对数，把跨数量级的浓度压成 0–14 的标尺。',
          },
          {
            id: 'u6-l2-q2',
            type: 'input',
            prompt: 'pH 从 5 变为 3，氢离子浓度变成原来的多少倍？',
            accept: ['100'],
            placeholder: '输入一个整数',
            explain: '$\\Delta\\mathrm{pH}=-2$，浓度比 $10^{2}=100$。pH 每减 1，浓度增大 10 倍。',
          },
          {
            id: 'u6-l2-q3',
            type: 'choice',
            prompt: '声强级 $L=10\\lg\\dfrac{P}{P_0}$。功率翻倍，分贝大约增加多少？',
            options: ['增加 1 倍（翻倍）', '增加约 3 dB', '增加 10 dB', '不变'],
            answer: 1,
            explain: '$10\\lg 2\\approx3$，所以功率翻倍只增加约 3 dB，体现对数尺度的压缩作用。',
          },
          {
            id: 'u6-l2-q4',
            type: 'input',
            prompt: '声功率 $10^{-4}$ W、参考功率 $10^{-12}$ W，求分贝数（单位 dB）。',
            accept: ['80'],
            placeholder: '输入一个整数',
            explain: '$L=10\\lg\\dfrac{10^{-4}}{10^{-12}}=10\\lg 10^{8}=80$ dB。',
          },
          {
            id: 'u6-l2-q5',
            type: 'judge',
            prompt: '判断：在对数标度数轴上，$1,10,10^2,\\dots,10^{14}$ 被压成等距刻度，相邻刻度恒为 10 倍。',
            answer: true,
            explain: '对数标度把“乘固定倍率”变成“加固定间距”，所以 10 的各次幂等距排列。',
          },
          {
            id: 'u6-l2-q6',
            type: 'match',
            prompt: '把每个对数尺度与它度量的量配对。',
            left: ['pH', '分贝', '里氏震级', '星等'],
            right: ['氢离子浓度', '声强（功率）比值', '地震波振幅', '天体亮度'],
            explain: '它们都遵循“刻度差 1 个固定量 = 原始量乘一个固定倍率”的对数思想。',
          },
        ],
      },
      {
        id: 'u6-l3',
        title: '震级、星等与跨数量级',
        subtitle: '把刻度差还原成 10 的幂之比',
        questions: [
          {
            id: 'u6-l3-q1',
            type: 'input',
            prompt: '里氏震级 $M=\\lg\\dfrac{A}{A_0}$。7.0 级与 5.0 级地震的振幅之比是多少？',
            accept: ['100'],
            placeholder: '输入一个整数',
            explain: '$\\dfrac{A_7}{A_5}=\\dfrac{10^{7.0}}{10^{5.0}}=10^{2}=100$。震级每增 1，振幅放大 10 倍。',
          },
          {
            id: 'u6-l3-q2',
            type: 'choice',
            prompt: '在简化模型 $E\\propto A^{3/2}$ 下，振幅相差 100 倍时能量之比约为？',
            options: ['$100$', '$1000$', '$10$', '$10^6$'],
            answer: 1,
            explain: '$\\left(\\dfrac{A_7}{A_5}\\right)^{3/2}=100^{3/2}=(10^2)^{3/2}=10^{3}=1000$。',
          },
          {
            id: 'u6-l3-q3',
            type: 'choice',
            prompt: '视星等 $m_1-m_2=-2.5\\lg\\dfrac{F_1}{F_2}$。星等差 5（如 0 等比 5 等），亮度差多少倍？',
            options: ['$5$ 倍', '$10$ 倍', '$100$ 倍', '$251$ 倍'],
            answer: 2,
            explain: '$\\lg\\dfrac{F_1}{F_2}=\\dfrac{5}{2.5}=2$，亮度比 $10^{2}=100$ 倍。星等是“越亮数值越小”的反向尺度。',
          },
          {
            id: 'u6-l3-q4',
            type: 'judge',
            prompt: '判断：求 $2^n>10^{12}$ 何时成立，可两边取 $\\lg$ 得 $n\\lg 2>12$。',
            answer: true,
            explain: '$\\lg$ 递增，不等号方向不变。取对数把指数 $n$ 从指数位置“放下来”，是跨数量级比较的标准手法。',
          },
          {
            id: 'u6-l3-q5',
            type: 'input',
            prompt: '细菌每 20 分钟翻倍，从 1 个开始，约需多少“次分裂”才超过 $10^{12}$？（$\\lg 2\\approx0.301$，填整数）',
            accept: ['40'],
            placeholder: '输入一个整数',
            explain: '$n>\\dfrac{12}{\\lg 2}\\approx\\dfrac{12}{0.301}\\approx39.9$，向上取整得 $n=40$ 次。',
          },
          {
            id: 'u6-l3-q6',
            type: 'match',
            prompt: '把每个“刻度差”与对应的“原始量之比”配对。',
            left: ['震级差 1', '震级差 2', 'pH 差 3', '星等差 5'],
            right: ['振幅 $\\times10$', '振幅 $\\times100$', '浓度 $\\times1000$', '亮度 $\\times100$'],
            explain: '把刻度差还原成 10 的幂之比：$M$ 系数 1、pH 系数 1、星等系数 2.5。对数差等于真数比的对数，直接反映倍率。',
          },
        ],
      },
    ],
  },
]
