import type { Unit } from '../../types'

// 第四部分（第 11–14 章）：微积分与分析。
// 四个单元：自然对数与 e、极限·增长比较、求导、积分·级数·近似。
export const PART4_UNITS: Unit[] = [
  // ===================== u11 自然对数与 e =====================
  {
    id: 'u11',
    title: '自然对数与 e',
    color: '#ff86d0',
    icon: '🌿',
    blurb: '$\\ln=\\log_e$，常数 $e=\\lim(1+1/n)^n\\approx2.718$，连续增长的自然底数。',
    lessons: [
      {
        id: 'u11-l1',
        title: '什么是自然对数',
        subtitle: '$\\ln x=\\log_e x$',
        questions: [
          {
            id: 'u11-l1-q1',
            type: 'choice',
            prompt: '自然对数 $\\ln x$ 的底数是什么？',
            options: ['$10$', '$2$', '$e$', '$1$'],
            answer: 2,
            explain: '自然对数即以 $e$ 为底的对数：$\\ln x=\\log_e x$。',
          },
          {
            id: 'u11-l1-q2',
            type: 'choice',
            prompt: '$e$ 的近似值最接近下面哪一个？',
            options: ['$2.718$', '$3.142$', '$1.414$', '$1.618$'],
            answer: 0,
            explain: '$e\\approx2.71828$，是无理数也是超越数。',
          },
          {
            id: 'u11-l1-q3',
            type: 'input',
            prompt: '$\\ln e$ 的值是多少？（填数字）',
            accept: ['1', '1.0'],
            explain: '$\\ln e=\\log_e e=1$，因为 $e^1=e$。',
          },
          {
            id: 'u11-l1-q4',
            type: 'input',
            prompt: '$\\ln 1$ 的值是多少？（填数字）',
            accept: ['0', '0.0'],
            explain: '任何底数的对数在 $1$ 处都是 $0$：$e^0=1$，故 $\\ln 1=0$。',
          },
          {
            id: 'u11-l1-q5',
            type: 'judge',
            prompt: '判断：自然对数与常用对数只是记号不同，本质完全一样。',
            answer: false,
            explain: '底数不同（$e$ 与 $10$）。$e$ 会在连续增长、极限和微积分中自然出现，地位特殊。',
          },
          {
            id: 'u11-l1-q6',
            type: 'input',
            prompt: '$\\ln e^3$ 的值是多少？（填数字）',
            accept: ['3', '3.0'],
            explain: '$\\ln e^3=3\\ln e=3$。',
          },
        ],
      },
      {
        id: 'u11-l2',
        title: 'e 的经典来源',
        subtitle: '$e=\\lim_{n\\to\\infty}(1+1/n)^n$',
        questions: [
          {
            id: 'u11-l2-q1',
            type: 'choice',
            prompt: '下面哪个极限给出常数 $e$？',
            options: [
              '$\\lim_{n\\to\\infty}\\left(1+\\frac1n\\right)^n$',
              '$\\lim_{n\\to\\infty}\\left(1+n\\right)^{1/n}$',
              '$\\lim_{n\\to\\infty}\\frac1n$',
              '$\\lim_{n\\to\\infty}\\left(1-\\frac1n\\right)^n$',
            ],
            answer: 0,
            explain: '$e=\\lim_{n\\to\\infty}\\left(1+\\frac1n\\right)^n$，是单位增长率连续累积的自然基准。',
          },
          {
            id: 'u11-l2-q2',
            type: 'judge',
            prompt: '判断：以年利率 100% 连续复利，一年后本金的倍率会逼近 $e$。',
            answer: true,
            explain: '复利次数 $n\\to\\infty$ 时 $\\left(1+\\frac1n\\right)^n\\to e$，所以连续复利倍率趋于 $e$。',
          },
          {
            id: 'u11-l2-q3',
            type: 'choice',
            prompt: '$e$ 的级数定义是哪一个？',
            options: [
              '$\\sum_{n=0}^{\\infty}\\frac1{n!}$',
              '$\\sum_{n=1}^{\\infty}\\frac1n$',
              '$\\sum_{n=0}^{\\infty}\\frac1{2^n}$',
              '$\\sum_{n=1}^{\\infty}\\frac{(-1)^{n-1}}{n}$',
            ],
            answer: 0,
            explain: '$e=\\sum_{n=0}^{\\infty}\\frac1{n!}=1+1+\\frac12+\\frac16+\\cdots$。',
          },
          {
            id: 'u11-l2-q4',
            type: 'input',
            prompt: '求 $\\lim_{n\\to\\infty}\\left(1+\\frac1n\\right)^{3n}$，结果用 e 表示（如 e^3）。',
            accept: ['e^3', 'e^{3}', 'e**3'],
            explain: '$\\left(1+\\frac1n\\right)^{3n}=\\left[\\left(1+\\frac1n\\right)^{n}\\right]^3\\to e^3$。',
          },
          {
            id: 'u11-l2-q5',
            type: 'judge',
            prompt: '判断：$e$ 是无理数。',
            answer: true,
            explain: '$e\\approx2.71828\\ldots$ 是无理数，且是超越数。',
          },
          {
            id: 'u11-l2-q6',
            type: 'match',
            prompt: '把 $e$ 的每种等价定义与它的视角配对。',
            left: ['$\\lim(1+1/n)^n$', '$\\sum 1/n!$', '$\\ln x=\\int_1^x\\frac{dt}{t}$'],
            right: ['复利极限', '级数求和', '面积阈值（$\\ln e=1$）'],
            explain: '三种定义都指向同一核心：$e^x$ 是满足 $f^{\\prime}=f$、$f(0)=1$ 的唯一函数。',
          },
        ],
      },
      {
        id: 'u11-l3',
        title: '桥梁公式与时间尺度',
        subtitle: '$a^x=e^{x\\ln a}$',
        questions: [
          {
            id: 'u11-l3-q1',
            type: 'choice',
            prompt: '把一般指数 $a^x$ 写成以 $e$ 为底的形式，结果是？',
            options: ['$e^{x\\ln a}$', '$e^{a\\ln x}$', '$e^{x/a}$', '$e^{ax}$'],
            answer: 0,
            explain: '桥梁公式 $a^x=e^{x\\ln a}$ 把任意底数指数统一成自然指数。',
          },
          {
            id: 'u11-l3-q2',
            type: 'input',
            prompt: '把 $5^x$ 改写成以 $e$ 为底的指数形式（填指数部分，如 x\\ln 5）。',
            accept: ['x\\ln5', 'x\\ln 5', 'x ln5', 'x ln 5', '(\\ln5)x'],
            explain: '$5^x=e^{x\\ln 5}$。',
          },
          {
            id: 'u11-l3-q3',
            type: 'choice',
            prompt: '模型 $y=y_0 e^{kt}$ 达到目标 $Y$ 所需时间是？',
            options: [
              '$t=\\frac1k\\ln\\frac{Y}{y_0}$',
              '$t=k\\ln\\frac{Y}{y_0}$',
              '$t=\\frac{1}{k}\\frac{Y}{y_0}$',
              '$t=\\frac{y_0}{kY}$',
            ],
            answer: 0,
            explain: '由 $Y=y_0e^{kt}$ 两边取对数得 $kt=\\ln\\frac{Y}{y_0}$，故 $t=\\frac1k\\ln\\frac{Y}{y_0}$。',
          },
          {
            id: 'u11-l3-q4',
            type: 'choice',
            prompt: '连续增长模型中，倍增时间 $T_d$（数量翻倍所需时间）等于？',
            options: ['$\\frac{\\ln 2}{k}$', '$\\frac{2}{k}$', '$\\frac{k}{\\ln 2}$', '$2k$'],
            answer: 0,
            explain: '翻倍即 $e^{kT_d}=2$，取对数得 $kT_d=\\ln 2$，故 $T_d=\\frac{\\ln 2}{k}$。',
          },
          {
            id: 'u11-l3-q5',
            type: 'judge',
            prompt: '判断：放射性衰减 $N=N_0 e^{-\\lambda t}$ 的半衰期 $T_{1/2}=\\frac{\\ln 2}{\\lambda}$ 与初始量 $N_0$ 有关。',
            answer: false,
            explain: '两边约去 $N_0$ 后 $e^{-\\lambda T_{1/2}}=\\frac12$，故 $T_{1/2}=\\frac{\\ln 2}{\\lambda}$，与 $N_0$ 无关。',
          },
          {
            id: 'u11-l3-q6',
            type: 'input',
            prompt: '若 $y=4e^{0.2t}$，求达到 $y=20$ 的时间 $t$（用 ln 表示，如 5\\ln5）。',
            accept: ['5\\ln5', '5\\ln 5', '5 ln5', '5 ln 5', '\\ln5/0.2', '\\frac{\\ln5}{0.2}'],
            explain: '$20=4e^{0.2t}\\Rightarrow e^{0.2t}=5\\Rightarrow 0.2t=\\ln5\\Rightarrow t=\\frac{\\ln5}{0.2}=5\\ln5$。',
          },
        ],
      },
    ],
  },

  // ===================== u12 极限·增长比较 =====================
  {
    id: 'u12',
    title: '极限·增长比较',
    color: '#7c4dff',
    icon: '🐢',
    blurb: '$\\ln x\\ll x^a\\ll a^x$，$\\lim\\frac{\\ln x}{x}=0$，对数增长最慢。',
    lessons: [
      {
        id: 'u12-l1',
        title: '两端的行为',
        subtitle: '$x\\to0^+$ 与 $x\\to+\\infty$',
        questions: [
          {
            id: 'u12-l1-q1',
            type: 'choice',
            prompt: '当 $x\\to 0^+$ 时，$\\ln x$ 趋于？',
            options: ['$-\\infty$', '$+\\infty$', '$0$', '$1$'],
            answer: 0,
            explain: '$x\\to0^+$ 时 $\\ln x\\to-\\infty$，对应 $x=0$ 处的竖直渐近线。',
          },
          {
            id: 'u12-l1-q2',
            type: 'choice',
            prompt: '当 $x\\to+\\infty$ 时，$\\ln x$ 趋于？',
            options: ['$+\\infty$', '$-\\infty$', '$0$', '某个有限上界'],
            answer: 0,
            explain: '$\\ln x\\to+\\infty$，但增长非常慢，没有上界。',
          },
          {
            id: 'u12-l1-q3',
            type: 'judge',
            prompt: '判断：可以讨论 $x\\to 0^-$ 时 $\\ln x$ 的极限。',
            answer: false,
            explain: '实数范围内 $\\ln x$ 只对 $x>0$ 有定义，只能写 $x\\to0^+$。',
          },
          {
            id: 'u12-l1-q4',
            type: 'judge',
            prompt: '判断：$\\ln x\\to+\\infty$ 说明它增长得很快。',
            answer: false,
            explain: '“趋于无穷”只表示无上界；$\\ln x$ 的增长其实非常慢（如 $\\ln 10^6\\approx13.8$）。',
          },
          {
            id: 'u12-l1-q5',
            type: 'choice',
            prompt: '$\\ln x$ 在哪个区间上连续？',
            options: ['$(0,+\\infty)$', '$(-\\infty,+\\infty)$', '$[0,+\\infty)$', '$[1,+\\infty)$'],
            answer: 0,
            explain: '$\\ln x$ 的定义域是 $(0,+\\infty)$，并在该区间上连续。',
          },
          {
            id: 'u12-l1-q6',
            type: 'match',
            prompt: '把每种情形与 $\\ln x$ 的行为配对。',
            left: ['$x\\to 0^+$', '$x\\to+\\infty$', '定义域'],
            right: ['$\\ln x\\to-\\infty$（剧烈下落）', '$\\ln x\\to+\\infty$（缓慢上升）', '$(0,+\\infty)$ 上连续'],
            explain: '$\\ln x$ 在 $x=0$ 处无定义，只能从右侧讨论；它在 $(0,+\\infty)$ 上连续。',
          },
        ],
      },
      {
        id: 'u12-l2',
        title: '两个基本极限',
        subtitle: '$\\frac{\\ln(1+x)}{x}\\to1$，$\\frac{\\ln x}{x}\\to0$',
        questions: [
          {
            id: 'u12-l2-q1',
            type: 'input',
            prompt: '求 $\\lim_{x\\to 0}\\frac{\\ln(1+x)}{x}$。（填数字）',
            accept: ['1', '1.0'],
            explain: '$\\frac{\\ln(1+x)}{x}=\\ln(1+x)^{1/x}\\to\\ln e=1$。',
          },
          {
            id: 'u12-l2-q2',
            type: 'input',
            prompt: '求 $\\lim_{x\\to +\\infty}\\frac{\\ln x}{x}$。（填数字）',
            accept: ['0', '0.0'],
            explain: '对数增长比任何正幂都慢，故 $\\frac{\\ln x}{x}\\to0$。',
          },
          {
            id: 'u12-l2-q3',
            type: 'choice',
            prompt: '当 $x$ 很小时，$\\ln(1+x)$ 近似等于？',
            options: ['$x$', '$1+x$', '$x^2$', '$\\frac1x$'],
            answer: 0,
            explain: '由 $\\frac{\\ln(1+x)}{x}\\to1$ 知 $\\ln(1+x)\\approx x$——对数变化近似等于相对变化。',
          },
          {
            id: 'u12-l2-q4',
            type: 'input',
            prompt: '用基本极限求 $\\lim_{x\\to 0}\\frac{\\ln(1+5x)}{x}$。（填数字）',
            accept: ['5', '5.0'],
            explain: '$\\frac{\\ln(1+5x)}{x}=5\\cdot\\frac{\\ln(1+5x)}{5x}\\to5\\cdot1=5$。',
          },
          {
            id: 'u12-l2-q5',
            type: 'input',
            prompt: '求 $\\lim_{x\\to 0^+}x\\ln x$。（填数字）',
            accept: ['0', '0.0'],
            explain: '令 $x=1/t$，$x\\ln x=-\\frac{\\ln t}{t}\\to0$（$x$ 趋零快过 $\\ln x$ 趋负无穷）。',
          },
          {
            id: 'u12-l2-q6',
            type: 'judge',
            prompt: '判断：使用洛必达法则前，必须先确认是 $\\frac00$ 或 $\\frac{\\infty}{\\infty}$ 型未定式。',
            answer: true,
            explain: '洛必达法则只适用于 $\\frac00$ 或 $\\frac{\\infty}{\\infty}$ 未定式，否则可能出错。',
          },
        ],
      },
      {
        id: 'u12-l3',
        title: '增长层级',
        subtitle: '$\\ln x\\ll x^a\\ll a^x$',
        questions: [
          {
            id: 'u12-l3-q1',
            type: 'choice',
            prompt: '下面哪个增长层级是正确的（从慢到快）？',
            options: [
              '$\\ln x\\ll x^\\alpha\\ll a^x$',
              '$x^\\alpha\\ll \\ln x\\ll a^x$',
              '$a^x\\ll x^\\alpha\\ll \\ln x$',
              '$\\ln x\\ll a^x\\ll x^\\alpha$',
            ],
            answer: 0,
            explain: '对数 < 幂 < 指数：$\\ln x\\ll x^\\alpha\\ll a^x$（$\\alpha>0,a>1$）。',
          },
          {
            id: 'u12-l3-q2',
            type: 'input',
            prompt: '对 $\\alpha>0$，求 $\\lim_{x\\to+\\infty}\\frac{\\ln x}{x^\\alpha}$。（填数字）',
            accept: ['0', '0.0'],
            explain: '$\\ln x$ 增长慢于任意正幂函数，故极限为 $0$。',
          },
          {
            id: 'u12-l3-q3',
            type: 'input',
            prompt: '求 $\\lim_{x\\to+\\infty}\\frac{\\ln x}{\\sqrt{x}}$。（填数字）',
            accept: ['0', '0.0'],
            explain: '$\\sqrt x=x^{1/2}$，$\\alpha=\\frac12>0$，由增长比较得极限为 $0$。',
          },
          {
            id: 'u12-l3-q4',
            type: 'input',
            prompt: '用两次洛必达求 $\\lim_{x\\to+\\infty}\\frac{x^2}{e^x}$。（填数字）',
            accept: ['0', '0.0'],
            explain: '$\\frac{x^2}{e^x}\\to\\frac{2x}{e^x}\\to\\frac{2}{e^x}\\to0$，体现 $x^\\alpha\\ll a^x$。',
          },
          {
            id: 'u12-l3-q5',
            type: 'judge',
            prompt: '判断：因为 $\\sqrt x$ 增长“也很慢”，所以它和 $\\ln x$ 难分胜负。',
            answer: false,
            explain: '只要幂指数 $\\alpha>0$（哪怕 $\\frac12$），幂函数终将彻底压过对数。',
          },
          {
            id: 'u12-l3-q6',
            type: 'match',
            prompt: '把每个极限与其值配对。',
            left: [
              '$\\lim_{x\\to+\\infty}\\frac{\\ln x}{x}$',
              '$\\lim_{x\\to 0}\\frac{\\ln(1+x)}{x}$',
              '$\\lim_{x\\to+\\infty}\\frac{x^2}{e^x}$',
            ],
            right: ['$0$', '$1$', '$0$'],
            explain: '对数比幂、幂比指数都趋于 $0$；唯有 $\\frac{\\ln(1+x)}{x}\\to1$。',
          },
        ],
      },
    ],
  },

  // ===================== u13 求导 =====================
  {
    id: 'u13',
    title: '求导',
    color: '#00b894',
    icon: '✏️',
    blurb: '$(\\ln x)^{\\prime}=\\frac1x$，$(\\log_a x)^{\\prime}=\\frac1{x\\ln a}$，链式法则与对数求导法。',
    lessons: [
      {
        id: 'u13-l1',
        title: '基本导数公式',
        subtitle: '$(\\ln x)^{\\prime}=\\frac1x$',
        questions: [
          {
            id: 'u13-l1-q1',
            type: 'choice',
            prompt: '$\\frac{d}{dx}\\ln x$ 等于？',
            options: ['$\\frac1x$', '$\\ln x$', '$x$', '$\\frac{1}{x^2}$'],
            answer: 0,
            explain: '$(\\ln x)^{\\prime}=\\frac1x$（$x>0$），这是本章最核心的公式。',
          },
          {
            id: 'u13-l1-q2',
            type: 'choice',
            prompt: '$\\frac{d}{dx}\\log_a x$ 等于？',
            options: ['$\\frac{1}{x\\ln a}$', '$\\frac1x$', '$\\frac{\\ln a}{x}$', '$\\frac{1}{x\\ln x}$'],
            answer: 0,
            explain: '由换底 $\\log_a x=\\frac{\\ln x}{\\ln a}$，求导得 $\\frac{1}{x\\ln a}$。',
          },
          {
            id: 'u13-l1-q3',
            type: 'judge',
            prompt: '判断：$(\\log_2 x)^{\\prime}=\\frac1x$。',
            answer: false,
            explain: '一般底数多一个因子：$(\\log_2 x)^{\\prime}=\\frac{1}{x\\ln 2}$，不是 $\\frac1x$。',
          },
          {
            id: 'u13-l1-q4',
            type: 'choice',
            prompt: '导数 $1/x$ 的结构意义是什么？',
            options: [
              '体现相对变化率：$x$ 越大，单位增量对 $\\ln x$ 影响越小',
              '说明 $\\ln x$ 增长很快',
              '说明 $\\ln x$ 是常数',
              '说明 $\\ln x$ 没有定义',
            ],
            answer: 0,
            explain: '$1/x$ 表示在不同尺度下的相对敏感度，正是“压缩尺度”的微积分表达。',
          },
          {
            id: 'u13-l1-q5',
            type: 'input',
            prompt: '$y=\\ln x$ 在点 $x_0=2$ 处的切线斜率是多少？（填数字或分数，如 1/2）',
            accept: ['1/2', '0.5', '\\frac{1}{2}'],
            explain: '斜率 $=(\\ln x)^{\\prime}|_{x=2}=\\frac1{x_0}=\\frac12$。',
          },
          {
            id: 'u13-l1-q6',
            type: 'match',
            prompt: '把每个函数与它的导数配对。',
            left: ['$\\ln x$', '$\\log_a x$', '$\\log_2 x$'],
            right: ['$\\frac1x$', '$\\frac{1}{x\\ln a}$', '$\\frac{1}{x\\ln 2}$'],
            explain: '只有自然对数导数是干净的 $\\frac1x$；一般底数都多一个因子 $\\frac1{\\ln a}$。',
          },
        ],
      },
      {
        id: 'u13-l2',
        title: '链式法则',
        subtitle: '$(\\ln u)^{\\prime}=\\frac{u^{\\prime}}{u}$',
        questions: [
          {
            id: 'u13-l2-q1',
            type: 'choice',
            prompt: '若 $u=u(x)>0$，$\\frac{d}{dx}\\ln u$ 等于？',
            options: ['$\\frac{u^{\\prime}}{u}$', '$\\frac1u$', '$u^{\\prime}\\ln u$', '$\\frac{1}{u^{\\prime}}$'],
            answer: 0,
            explain: '链式法则：$(\\ln u)^{\\prime}=\\frac{u^{\\prime}}{u}$——分母抄原式，分子放内导。',
          },
          {
            id: 'u13-l2-q2',
            type: 'input',
            prompt: '求导 $y=\\ln(x^2+1)$，写出 $y^{\\prime}$（如 2x/(x^2+1)）。',
            accept: ['2x/(x^2+1)', '\\frac{2x}{x^2+1}', '2x/(x^{2}+1)', '(2x)/(x^2+1)'],
            explain: '$u=x^2+1$，$u^{\\prime}=2x$，故 $y^{\\prime}=\\frac{2x}{x^2+1}$。',
          },
          {
            id: 'u13-l2-q3',
            type: 'input',
            prompt: '求导 $y=\\ln(3x+1)$，写出 $y^{\\prime}$（如 3/(3x+1)）。',
            accept: ['3/(3x+1)', '\\frac{3}{3x+1}', '3/(3x + 1)'],
            explain: '内层导数为 $3$，故 $y^{\\prime}=\\frac{3}{3x+1}$。',
          },
          {
            id: 'u13-l2-q4',
            type: 'choice',
            prompt: '$y=\\ln(x^2-4)$ 的定义域是？',
            options: ['$|x|>2$', '$x>0$', '全体实数', '$-2<x<2$'],
            answer: 0,
            explain: '真数 $x^2-4>0$ 即 $|x|>2$；导数 $y^{\\prime}=\\frac{2x}{x^2-4}$ 也只在该区间有意义。',
          },
          {
            id: 'u13-l2-q5',
            type: 'judge',
            prompt: '判断：求复合对数函数的导数时，可以忽略真数为正的定义域要求。',
            answer: false,
            explain: '必须先求定义域（真数 $>0$），导数表达式只在该区间才有意义。',
          },
          {
            id: 'u13-l2-q6',
            type: 'input',
            prompt: '用化商为差求导 $y=\\ln\\frac{x+1}{x-1}$（$|x|>1$），写出 $y^{\\prime}$（如 -2/(x^2-1)）。',
            accept: ['-2/(x^2-1)', '\\frac{-2}{x^2-1}', '-2/(x^{2}-1)', '-\\frac{2}{x^2-1}'],
            explain: '$y=\\ln(x+1)-\\ln(x-1)$，$y^{\\prime}=\\frac1{x+1}-\\frac1{x-1}=\\frac{-2}{x^2-1}$。',
          },
        ],
      },
      {
        id: 'u13-l3',
        title: '对数求导法',
        subtitle: '先取对数，再求导，再还原',
        questions: [
          {
            id: 'u13-l3-q1',
            type: 'choice',
            prompt: '对 $y=x^x$（$x>0$）取自然对数后得到？',
            options: ['$\\ln y=x\\ln x$', '$\\ln y=x^2$', '$\\ln y=\\ln x$', '$\\ln y=x+\\ln x$'],
            answer: 0,
            explain: '$\\ln y=\\ln(x^x)=x\\ln x$，这把幂指函数化成乘积，便于求导。',
          },
          {
            id: 'u13-l3-q2',
            type: 'input',
            prompt: '求导 $y=x^x$（$x>0$），写出 $y^{\\prime}$（如 x^x(\\ln x+1)）。',
            accept: ['x^x(\\ln x+1)', 'x^x(\\ln x + 1)', 'x^{x}(\\ln x+1)', 'x^x(1+\\ln x)'],
            explain: '$\\frac{y^{\\prime}}{y}=\\ln x+1$，乘回 $y=x^x$ 得 $y^{\\prime}=x^x(\\ln x+1)$。',
          },
          {
            id: 'u13-l3-q3',
            type: 'choice',
            prompt: '对数求导法为什么适合处理幂指函数 $f(x)^{g(x)}$？',
            options: [
              '取对数后指数落下来变乘积 $g(x)\\ln f(x)$，便于求导',
              '它能消去所有变量',
              '它把函数变成常数',
              '它不需要链式法则',
            ],
            answer: 0,
            explain: '幂指函数无法直接套幂法则或指数法则，取对数后指数落下变乘积即可常规求导。',
          },
          {
            id: 'u13-l3-q4',
            type: 'input',
            prompt: '用对数求导法求 $y=x^{\\sin x}$（$x>0$），写出 $y^{\\prime}$。',
            accept: [
              'x^{\\sin x}(\\cos x\\ln x+\\sin x/x)',
              'x^{\\sin x}(\\cos x\\ln x+\\frac{\\sin x}{x})',
              'x^{\\sin x}(\\cos x \\ln x + \\sin x/x)',
            ],
            explain: '$\\ln y=\\sin x\\ln x$，$\\frac{y^{\\prime}}{y}=\\cos x\\ln x+\\frac{\\sin x}{x}$，乘回得结果。',
          },
          {
            id: 'u13-l3-q5',
            type: 'judge',
            prompt: '判断：用对数求导法后，必须把 $y$ 还原成原式才算完成。',
            answer: true,
            explain: '$\\frac{y^{\\prime}}{y}$ 求出后要乘回 $y$（即原函数表达式）才得到 $y^{\\prime}$。',
          },
          {
            id: 'u13-l3-q6',
            type: 'input',
            prompt: '$y=x^x$（$x>0$）的极小值点 $x=?$（填数字或表达式，如 1/e）。',
            accept: ['1/e', 'e^{-1}', 'e^-1', '\\frac{1}{e}'],
            explain: '$y^{\\prime}=x^x(\\ln x+1)=0\\Rightarrow\\ln x=-1\\Rightarrow x=\\frac1e$，此处取极小值。',
          },
        ],
      },
    ],
  },

  // ===================== u14 积分·级数·近似 =====================
  {
    id: 'u14',
    title: '积分·级数·近似',
    color: '#e84393',
    icon: '∫',
    blurb: '$\\int\\frac1x dx=\\ln|x|+C$，$\\ln x=\\int_1^x\\frac{dt}{t}$，$\\ln(1+x)$ 级数与交错和 $\\ln 2$。',
    lessons: [
      {
        id: 'u14-l1',
        title: '对数与积分',
        subtitle: '$\\int\\frac1x dx=\\ln|x|+C$',
        questions: [
          {
            id: 'u14-l1-q1',
            type: 'choice',
            prompt: '$\\int\\frac1x\\,dx$ 等于？',
            options: ['$\\ln|x|+C$', '$\\ln x+C$', '$\\frac{1}{x^2}+C$', '$x\\ln x+C$'],
            answer: 0,
            explain: '$\\int\\frac1x\\,dx=\\ln|x|+C$，绝对值同时覆盖 $x>0$ 与 $x<0$。',
          },
          {
            id: 'u14-l1-q2',
            type: 'judge',
            prompt: '判断：$\\int\\frac1x\\,dx$ 只写成 $\\ln x+C$ 就足够了。',
            answer: false,
            explain: '$\\ln x$ 只对 $x>0$ 有定义；积分变量可能在负半轴，须写 $\\ln|x|+C$。',
          },
          {
            id: 'u14-l1-q3',
            type: 'choice',
            prompt: '自然对数的面积定义是？',
            options: [
              '$\\ln x=\\int_1^x\\frac{dt}{t}$',
              '$\\ln x=\\int_0^x t\\,dt$',
              '$\\ln x=\\int_1^x t\\,dt$',
              '$\\ln x=\\int_0^x\\frac{dt}{t}$',
            ],
            answer: 0,
            explain: '$\\ln x=\\int_1^x\\frac1t\\,dt$ 表示 $y=1/t$ 下方从 $1$ 到 $x$ 的面积。',
          },
          {
            id: 'u14-l1-q4',
            type: 'choice',
            prompt: '识别 $u^{\\prime}/u$ 结构，$\\int\\frac{2x}{x^2+1}\\,dx$ 等于？',
            options: ['$\\ln(x^2+1)+C$', '$\\frac{1}{x^2+1}+C$', '$2\\ln x+C$', '$\\arctan x+C$'],
            answer: 0,
            explain: '分子是分母导数：$\\int\\frac{f^{\\prime}}{f}\\,dx=\\ln|f|+C$；这里 $x^2+1>0$ 可去绝对值。',
          },
          {
            id: 'u14-l1-q5',
            type: 'input',
            prompt: '计算 $\\int\\frac{3}{3x+1}\\,dx$（写含绝对值的结果，如 \\ln|3x+1|+C）。',
            accept: ['\\ln|3x+1|+C', '\\ln |3x+1|+C', 'ln|3x+1|+C', '\\ln|3x+1| + C'],
            explain: '$u=3x+1$，$u^{\\prime}=3$，故 $\\int\\frac{3}{3x+1}\\,dx=\\ln|3x+1|+C$。',
          },
          {
            id: 'u14-l1-q6',
            type: 'input',
            prompt: '计算 $\\int\\frac{1}{2x-5}\\,dx$（如 \\frac12\\ln|2x-5|+C）。',
            accept: [
              '\\frac12\\ln|2x-5|+C',
              '\\frac{1}{2}\\ln|2x-5|+C',
              '1/2\\ln|2x-5|+C',
              '0.5\\ln|2x-5|+C',
            ],
            explain: '分母导数为 $2$，凑因子：$\\frac12\\int\\frac{2}{2x-5}\\,dx=\\frac12\\ln|2x-5|+C$。',
          },
        ],
      },
      {
        id: 'u14-l2',
        title: 'ln x 的积分与级数',
        subtitle: '$\\int\\ln x\\,dx=x\\ln x-x+C$',
        questions: [
          {
            id: 'u14-l2-q1',
            type: 'choice',
            prompt: '$\\int\\ln x\\,dx$ 等于？',
            options: ['$x\\ln x-x+C$', '$\\frac1x+C$', '$x\\ln x+C$', '$\\frac{(\\ln x)^2}{2}+C$'],
            answer: 0,
            explain: '分部积分（$u=\\ln x,\\,dv=dx$）：$\\int\\ln x\\,dx=x\\ln x-x+C$。',
          },
          {
            id: 'u14-l2-q2',
            type: 'choice',
            prompt: '$\\ln(1+x)$ 的级数展开是？',
            options: [
              '$x-\\frac{x^2}{2}+\\frac{x^3}{3}-\\cdots$',
              '$1+x+\\frac{x^2}{2}+\\cdots$',
              '$x+\\frac{x^2}{2}+\\frac{x^3}{3}+\\cdots$',
              '$1-x+x^2-\\cdots$',
            ],
            answer: 0,
            explain: '$\\ln(1+x)=\\sum_{n=1}^{\\infty}\\frac{(-1)^{n-1}}{n}x^n=x-\\frac{x^2}{2}+\\frac{x^3}{3}-\\cdots$。',
          },
          {
            id: 'u14-l2-q3',
            type: 'choice',
            prompt: '$\\ln(1+x)$ 级数的收敛域是？',
            options: ['$-1<x\\le 1$', '$-1\\le x\\le 1$', '$|x|<\\infty$', '$0<x<1$'],
            answer: 0,
            explain: '收敛域 $-1<x\\le1$：右端 $x=1$ 收敛（交错级数），左端 $x=-1$ 发散（调和级数）。',
          },
          {
            id: 'u14-l2-q4',
            type: 'input',
            prompt: '交错和 $1-\\frac12+\\frac13-\\frac14+\\cdots$ 收敛到什么？（用 ln 表示，如 \\ln2）',
            accept: ['\\ln2', '\\ln 2', 'ln2', 'ln 2'],
            explain: '在级数中取 $x=1$：$1-\\frac12+\\frac13-\\cdots=\\ln(1+1)=\\ln 2\\approx0.693$。',
          },
          {
            id: 'u14-l2-q5',
            type: 'input',
            prompt: '计算定积分 $\\int_1^e\\ln x\\,dx$。（填数字）',
            accept: ['1', '1.0'],
            explain: '$[x\\ln x-x]_1^e=(e-e)-(0-1)=1$。',
          },
          {
            id: 'u14-l2-q6',
            type: 'match',
            prompt: '把每个积分与其结果配对。',
            left: ['$\\int\\ln x\\,dx$', '$\\int_1^e\\ln x\\,dx$', '$\\int_0^1\\ln x\\,dx$'],
            right: ['$x\\ln x-x+C$', '$1$', '$-1$'],
            explain: '原函数都是 $x\\ln x-x$；定积分代入对应上下限即可，反常积分靠 $\\lim_{a\\to0^+}a\\ln a=0$ 收敛。',
          },
        ],
      },
      {
        id: 'u14-l3',
        title: '小量近似',
        subtitle: '$\\ln(1+x)\\approx x$',
        questions: [
          {
            id: 'u14-l3-q1',
            type: 'choice',
            prompt: '当 $x$ 很小时，$\\ln(1+x)$ 的一阶近似是？',
            options: ['$x$', '$1+x$', '$\\frac x2$', '$x^2$'],
            answer: 0,
            explain: '$\\ln(1+x)\\approx x$，相对变化很小时对数变化与线性变化几乎一致。',
          },
          {
            id: 'u14-l3-q2',
            type: 'input',
            prompt: '用一阶近似估算 $\\ln(1.02)$。（填数字）',
            accept: ['0.02', '.02'],
            explain: '$\\ln(1.02)=\\ln(1+0.02)\\approx0.02$。',
          },
          {
            id: 'u14-l3-q3',
            type: 'judge',
            prompt: '判断：$\\ln(1.5)\\approx0.5$ 是一个可靠的近似。',
            answer: false,
            explain: '真值约 $0.405$，误差约 $0.095$（约 23%）——$x=0.5$ 不够小。',
          },
          {
            id: 'u14-l3-q4',
            type: 'judge',
            prompt: '判断：$\\ln(1+x)\\approx x$ 是恒等式，对任意 $x$ 都精确成立。',
            answer: false,
            explain: '这只是 $x$ 很小时的近似，不是恒等式；$x$ 不小时误差不可忽视。',
          },
          {
            id: 'u14-l3-q5',
            type: 'choice',
            prompt: '保留到二次项，$\\ln(1+x)$ 的更精细近似是？',
            options: [
              '$x-\\frac{x^2}{2}$',
              '$x+\\frac{x^2}{2}$',
              '$x-x^2$',
              '$\\frac{x^2}{2}$',
            ],
            answer: 0,
            explain: '由级数 $\\ln(1+x)=x-\\frac{x^2}{2}+\\cdots$，二阶近似为 $x-\\frac{x^2}{2}$。',
          },
          {
            id: 'u14-l3-q6',
            type: 'choice',
            prompt: '调和级数 $H_n=1+\\frac12+\\cdots+\\frac1n$ 的渐近行为是？',
            options: [
              '$H_n\\approx\\ln n+\\gamma$，缓慢发散',
              '$H_n$ 收敛到 $\\ln 2$',
              '$H_n$ 收敛到 $e$',
              '$H_n$ 有上界',
            ],
            answer: 0,
            explain: '$H_n=\\ln n+\\gamma+O(1/n)$，$\\gamma\\approx0.5772$；调和级数发散但增长极慢。',
          },
        ],
      },
    ],
  },
]
