import type { Unit } from '../../types'

// 第六部分（复数与综合）：第18–20章
// u18 复对数与分支 / u19 高级问题·结构联系 / u20 综合与展望
// 数学已核对：主辐角 Arg∈(-π,π]、ln(-1)=iπ、i^i=e^{-π/2}（主值）、相差 2πi；
// ln 凹性方向、Jensen φ(E[X])≥E[φX]（φ 凹）、Stirling、排序下界 n log n；指数↔对数反函数全景。

export const PART6_UNITS: Unit[] = [
  // ===================== 第18章 =====================
  {
    id: 'u18',
    title: '复对数与分支',
    color: '#d63031',
    icon: '🌀',
    blurb: '进入复数后对数变成多值：$\\operatorname{Log} z=\\ln|z|+i\\arg z$，主值、分支与 $i^i$。',
    lessons: [
      {
        id: 'u18-l1',
        title: '复对数为什么多值',
        subtitle: '复指数有周期 $2\\pi$，反函数不再单值',
        questions: [
          {
            id: 'u18-l1-q1',
            type: 'choice',
            prompt: '实对数 $\\log_a x$（$a>0,a\\neq1$）是单值函数，根本原因是？',
            options: [
              '实指数函数在实数上一一对应（单调可逆）',
              '对数本身规定只能取一个值',
              '真数必须为正',
              '底数必须大于 1',
            ],
            answer: 0,
            explain: '单值性来自指数函数在实数范围内的一一对应。一旦这个可逆性丢失（如进入复数），对数就不再单值。',
          },
          {
            id: 'u18-l1-q2',
            type: 'judge',
            prompt: '判断：由欧拉公式 $e^{i\\theta}=\\cos\\theta+i\\sin\\theta$ 可知 $e^{i(\\theta+2k\\pi)}=e^{i\\theta}$，即复指数有周期 $2\\pi$。',
            answer: true,
            explain: '角度相差 $2k\\pi$ 表示同一个复数，所以复指数是周期函数，不再一一对应——这正是复对数多值的源头。',
          },
          {
            id: 'u18-l1-q3',
            type: 'choice',
            prompt: '设 $z=re^{i\\theta}$（$r>0$），则它的全部复对数为？',
            options: [
              '$\\ln r$',
              '$\\ln r+i\\theta$',
              '$\\ln r+i(\\theta+2k\\pi),\\ k\\in\\mathbb{Z}$',
              '$\\ln(r+\\theta)$',
            ],
            answer: 2,
            explain: '实部 $\\ln r$ 唯一锁定；虚部是一族相差 $2k\\pi$ 的辐角，故 $\\log z=\\ln r+i(\\theta+2k\\pi)$。',
          },
          {
            id: 'u18-l1-q4',
            type: 'input',
            prompt: '复对数的多值性体现在哪一部分？相邻两值的虚部相差多少（填形如 $2\\pi$ 的数）？',
            accept: ['2\\pi', '2π', '2pi'],
            explain: '实部 $\\ln|z|$ 唯一，多值全在虚部：相邻分支的虚部相差一个完整辐角周期 $2\\pi$。',
          },
          {
            id: 'u18-l1-q5',
            type: 'match',
            prompt: '把“实对数”与“复对数”的对应特征配对：',
            left: ['底层映射', '一个真数/复数的对数', '多值来源', '虚部'],
            right: ['指数一一对应 vs 周期不可逆', '唯一一个 vs 无穷多个', '无 vs 辐角不唯一', '为 0 vs 跳 $2k\\pi$'],
            explain: '实对数单值（指数可逆、值唯一、虚部为 0）；复对数多值（指数有周期、值无穷、虚部相差 $2k\\pi$）。',
          },
        ],
      },
      {
        id: 'u18-l2',
        title: '主值与 $\\operatorname{Log}(-1)$',
        subtitle: '取定主辐角 $\\operatorname{Arg}\\in(-\\pi,\\pi]$ 选一个分支',
        questions: [
          {
            id: 'u18-l2-q1',
            type: 'choice',
            prompt: '常用的主辐角区间 $\\operatorname{Arg}(z)$ 是？',
            options: ['$[0,2\\pi)$', '$(-\\pi,\\pi]$', '$[-\\pi,\\pi)$', '$(0,2\\pi]$'],
            answer: 1,
            explain: '主值对数取主辐角 $\\operatorname{Arg}(z)\\in(-\\pi,\\pi]$，于是 $\\operatorname{Log} z=\\ln|z|+i\\operatorname{Arg}(z)$ 单值。',
          },
          {
            id: 'u18-l2-q2',
            type: 'input',
            prompt: '已知 $\\operatorname{Arg}(-1)=\\pi$，写出主值 $\\operatorname{Log}(-1)$（用 $i\\pi$ 形式作答）。',
            accept: ['i\\pi', 'iπ', 'ipi', '\\pi i', 'πi', '0+i\\pi'],
            explain: '$|-1|=1$ 故实部 $\\ln 1=0$；主辐角 $\\pi$ 给出虚部，于是 $\\operatorname{Log}(-1)=\\ln 1+i\\pi=i\\pi$。',
          },
          {
            id: 'u18-l2-q3',
            type: 'judge',
            prompt: '判断：$\\operatorname{Log}(-1)=i\\pi$ 是从多值集合 $\\log(-1)=i(\\pi+2k\\pi)$ 中选定的一个分支（$k=0$），并不代表其他值不存在。',
            answer: true,
            explain: '主值只是“选定分支后的单值代表”。其余分支 $i(\\pi\\pm2\\pi),\\dots$ 依然成立，只是没被选中。',
          },
          {
            id: 'u18-l2-q4',
            type: 'choice',
            prompt: '一般复对数 $\\log(-1)$ 的全部取值为？',
            options: [
              '$i\\pi$',
              '$i(\\pi+2k\\pi),\\ k\\in\\mathbb{Z}$',
              '$\\pi+2k\\pi,\\ k\\in\\mathbb{Z}$',
              '$0$',
            ],
            answer: 1,
            explain: '$-1=e^{i(\\pi+2k\\pi)}$，故 $\\log(-1)=i(\\pi+2k\\pi)$；主值 $i\\pi$ 只是其中 $k=0$ 的那一支。',
          },
          {
            id: 'u18-l2-q5',
            type: 'match',
            prompt: '这些复数的模都是 1，故主值是纯虚数。把每个复数与它的主值对数配对：',
            left: ['$\\operatorname{Log}(1)$', '$\\operatorname{Log}\\,i$', '$\\operatorname{Log}(-1)$', '$\\operatorname{Log}(-i)$'],
            right: ['$0$', '$\\tfrac{\\pi}{2}i$', '$\\pi i$', '$-\\tfrac{\\pi}{2}i$'],
            explain: '模为 1 时实部 $\\ln1=0$，主值就是主辐角乘 $i$：$\\operatorname{Arg}(1)=0$、$\\operatorname{Arg}(i)=\\tfrac{\\pi}{2}$、$\\operatorname{Arg}(-1)=\\pi$、$\\operatorname{Arg}(-i)=-\\tfrac{\\pi}{2}$。',
          },
          {
            id: 'u18-l2-q6',
            type: 'judge',
            prompt: '判断：取 $z=w=-1$，主值满足 $\\operatorname{Log}(zw)=\\operatorname{Log}(-1)+\\operatorname{Log}(-1)$。',
            answer: false,
            explain: '$zw=1$ 故 $\\operatorname{Log}(zw)=0$，而 $\\operatorname{Log}(-1)+\\operatorname{Log}(-1)=2\\pi i\\neq0$。对数法则在复数里整族成立、主值未必，差额恒为 $2k\\pi i$。',
          },
        ],
      },
      {
        id: 'u18-l3',
        title: '分支切割与 $i^i$',
        subtitle: '负实轴切一刀换单值；复幂 $z^w=e^{w\\operatorname{Log}z}$',
        questions: [
          {
            id: 'u18-l3-q1',
            type: 'choice',
            prompt: '在复对数中做“分支切割”（如切掉负实轴）的目的是？',
            options: [
              '让对数变成多值',
              '让主值在某区域内保持单值且连续',
              '扩大定义域到全平面',
              '消去虚部',
            ],
            answer: 1,
            explain: '穿过负实轴时主辐角会从 $\\pi$ 跳到 $-\\pi$（虚部跳 $-2\\pi$）。切一刀禁止穿越，主值才能局部单值连续。',
          },
          {
            id: 'u18-l3-q2',
            type: 'judge',
            prompt: '判断：当 $z$ 沿单位圆连续穿过负实轴时，主值 $\\operatorname{Log} z$ 的虚部会发生一个 $2\\pi$ 的跳变，即主值在此处不连续。',
            answer: true,
            explain: '越过前虚部趋于 $\\pi$，越过后主辐角落回 $(-\\pi,\\pi]$ 变为 $-\\pi$，跳变 $-2\\pi$——这正是必须设支割线的原因。',
          },
          {
            id: 'u18-l3-q3',
            type: 'input',
            prompt: '由 $i^i=e^{i\\log i}$ 与 $\\log i=i(\\tfrac{\\pi}{2}+2k\\pi)$，写出 $i^i$ 的主值（$k=0$）的精确表达式。',
            accept: ['e^{-\\pi/2}', 'e^{-π/2}', 'e^(-pi/2)', 'e^{-\\frac{\\pi}{2}}', 'e^-pi/2'],
            explain: '$i\\cdot i(\\tfrac{\\pi}{2})=i^2\\tfrac{\\pi}{2}=-\\tfrac{\\pi}{2}$，故主值 $i^i=e^{-\\pi/2}\\approx0.208$——虚数的虚次幂却是正实数。',
          },
          {
            id: 'u18-l3-q4',
            type: 'choice',
            prompt: '$i^i$ 的全部取值为？',
            options: [
              '$e^{-\\pi/2}$（只有一个）',
              '$e^{-\\pi/2-2k\\pi},\\ k\\in\\mathbb{Z}$（全是正实数）',
              '$e^{i\\pi/2+2k\\pi i}$',
              '纯虚数族',
            ],
            answer: 1,
            explain: '$i^i=\\exp\\!\\big(i\\cdot i(\\tfrac{\\pi}{2}+2k\\pi)\\big)=e^{-\\pi/2-2k\\pi}$，全部是正实数，主值最大，相邻之比恒为 $e^{-2\\pi}$。',
          },
          {
            id: 'u18-l3-q5',
            type: 'choice',
            prompt: '用主值幂 $z^w=e^{w\\operatorname{Log}z}$ 求 $(-1)^{1/2}$ 的主值，结果是？',
            options: ['$-i$', '$i$', '$1$', '$-1$'],
            answer: 1,
            explain: '$\\operatorname{Log}(-1)=i\\pi$，故 $(-1)^{1/2}=e^{\\frac12 i\\pi}=e^{i\\pi/2}=i$。取另一支辐角 $-\\pi$ 才得 $-i$。',
          },
          {
            id: 'u18-l3-q6',
            type: 'match',
            prompt: '把复对数/复幂的对象与其主值配对：',
            left: ['$\\operatorname{Log}(-1)$', '$\\operatorname{Log}\\,i$', '$i^i$', '$(-1)^{1/2}$'],
            right: ['$i\\pi$', '$\\tfrac{\\pi}{2}i$', '$e^{-\\pi/2}$', '$i$'],
            explain: '主值四例：$\\operatorname{Log}(-1)=i\\pi$、$\\operatorname{Log}\\,i=\\tfrac{\\pi}{2}i$、$i^i=e^{-\\pi/2}$、$(-1)^{1/2}=i$。',
          },
        ],
      },
    ],
  },
  // ===================== 第19章 =====================
  {
    id: 'u19',
    title: '高级问题 · 结构联系',
    color: '#fdcb6e',
    icon: '🧠',
    blurb: '$\\ln$ 是凹函数 → Jensen / AM-GM；Stirling 把 $\\ln n!$ 算出来；对数把难度降维。',
    lessons: [
      {
        id: 'u19-l1',
        title: '凹性 · Jensen · AM-GM',
        subtitle: '$\\ln x$ 向下弯，先平均再取对数更大',
        questions: [
          {
            id: 'u19-l1-q1',
            type: 'choice',
            prompt: '$\\ln x$ 在 $(0,+\\infty)$ 上是？',
            options: ['凸函数（向上弯）', '凹函数（向下弯）', '线性函数', '周期函数'],
            answer: 1,
            explain: '$\\ln x$ 是凹函数，图像向下弯。由此“先平均再取对数”往往大于“先取对数再平均”。',
          },
          {
            id: 'u19-l1-q2',
            type: 'judge',
            prompt: '判断：对凹函数 $\\phi$，Jensen 不等式为 $\\phi(\\mathbb{E}[X])\\ge\\mathbb{E}[\\phi(X)]$。',
            answer: true,
            explain: '凹函数 Jensen 取 $\\ge$：$\\phi(\\mathbb{E}[X])\\ge\\mathbb{E}[\\phi(X)]$。代入 $\\phi=\\ln$ 得 $\\ln\\mathbb{E}[X]\\ge\\mathbb{E}[\\ln X]$。',
          },
          {
            id: 'u19-l1-q3',
            type: 'choice',
            prompt: '由 $\\ln$ 凹性 $\\ln\\tfrac{a+b}{2}\\ge\\tfrac{\\ln a+\\ln b}{2}$，去掉对数可得？',
            options: [
              '$\\dfrac{a+b}{2}\\ge\\sqrt{ab}$（AM-GM）',
              '$\\dfrac{a+b}{2}\\le\\sqrt{ab}$',
              '$a+b\\ge ab$',
              '$\\sqrt{ab}\\ge a+b$',
            ],
            answer: 0,
            explain: '右边 $=\\ln\\sqrt{ab}$，由 $\\ln$ 单调递增去对数得 $\\tfrac{a+b}{2}\\ge\\sqrt{ab}$——即二元 AM-GM。',
          },
          {
            id: 'u19-l1-q4',
            type: 'input',
            prompt: '$X$ 取 $1$ 与 $100$ 各以概率 $\\tfrac12$。其几何平均 $\\exp(\\mathbb{E}[\\ln X])=\\sqrt{1\\times100}=\\,?$（填数字）',
            accept: ['10'],
            explain: '$\\mathbb{E}[\\ln X]=\\tfrac12\\ln1+\\tfrac12\\ln100=\\ln10$，故 $\\exp$ 后为 $10$，远小于算术平均 $50.5$——差距来自凹性。',
          },
          {
            id: 'u19-l1-q5',
            type: 'match',
            prompt: '把概念与其内容配对：',
            left: ['凹性', 'Jensen（凹）', 'AM-GM', '对数凹分布'],
            right: ['图像向下弯', '$\\phi(\\mathbb{E}X)\\ge\\mathbb{E}\\phi(X)$', '$\\tfrac{a+b}{2}\\ge\\sqrt{ab}$', '$\\ln f$ 是凹函数'],
            explain: '凹性是源头；Jensen 是其不等式表述；AM-GM 是 $\\phi=\\ln$ 的特例；对数凹分布要求 $\\ln f$ 凹（如正态）。',
          },
        ],
      },
      {
        id: 'u19-l2',
        title: 'Stirling 与排序下界',
        subtitle: '$\\ln n!\\approx n\\ln n-n$，比较排序至少 $n\\log n$',
        questions: [
          {
            id: 'u19-l2-q1',
            type: 'choice',
            prompt: 'Stirling 近似（简化式）给出 $\\ln n!\\approx$？',
            options: ['$n\\ln n$', '$n\\ln n-n$', '$n!$', '$\\ln n$'],
            answer: 1,
            explain: '简化式 $\\ln n!\\approx n\\ln n-n$；更精确为 $n\\ln n-n+\\tfrac12\\ln(2\\pi n)$。它把不可手算的连乘变成几次对数运算。',
          },
          {
            id: 'u19-l2-q2',
            type: 'input',
            prompt: '用简化式 $\\ln n!\\approx n\\ln n-n$ 估计 $\\ln(20!)$。取 $\\ln20\\approx2.996$，结果约为多少？（填一位小数，如 $39.9$）',
            accept: ['39.9', '39.92', '39.915'],
            explain: '$20\\times2.996-20\\approx59.9-20=39.9$。加修正项 $\\tfrac12\\ln(2\\pi\\cdot20)\\approx2.42$ 后得 $42.3$，接近精确值 $42.336$。',
          },
          {
            id: 'u19-l2-q3',
            type: 'choice',
            prompt: '基于比较的排序，其判定树要区分 $n!$ 种排列，故最坏比较次数下界为？',
            options: ['$O(n)$', '$O(\\log n)$', '$\\Omega(n\\log n)$', '$O(n^2)$'],
            answer: 2,
            explain: '高度 $\\ge\\log_2(n!)\\approx n\\log_2 n-n\\log_2 e$，主项 $n\\log_2 n$，故下界 $\\Omega(n\\log n)$，主阶系数为 1。',
          },
          {
            id: 'u19-l2-q4',
            type: 'judge',
            prompt: '判断：$\\log_2(n!)=\\dfrac{\\ln n!}{\\ln 2}$ 这一步用到了换底公式。',
            answer: true,
            explain: '换底 $\\log_2 x=\\dfrac{\\ln x}{\\ln 2}$ 把自然对数换成以 2 为底；再配 Stirling 展开 $\\ln n!$，得到 $n\\log_2 n$ 的下界。',
          },
          {
            id: 'u19-l2-q5',
            type: 'choice',
            prompt: '为什么二分查找的复杂度是 $O(\\log n)$？',
            options: [
              '每步把候选范围按比例减半，问“减半几次到 1”即 $2^k\\approx n$',
              '因为数组必须有序',
              '因为对数公式恰好如此',
              '因为每步遍历全部元素',
            ],
            answer: 0,
            explain: '$\\tfrac{n}{2^k}\\approx1\\Rightarrow k\\approx\\log_2 n$。这是“重复按比例缩小”的反向提问——又回到第 1 章的反向问题。',
          },
          {
            id: 'u19-l2-q6',
            type: 'match',
            prompt: '“对数把难度降维”——把每个对象与取对数后的近似/结果配对：',
            left: ['$\\ln n!$', '$\\log_2(n!)$', '二分查找步数', '$\\ln\\binom{n}{k}$'],
            right: ['$n\\ln n-n$', '$n\\log_2 n$（主项）', '$\\log_2 n$', '$\\ln n!-\\ln k!-\\ln(n-k)!$'],
            explain: 'Stirling 给 $\\ln n!\\approx n\\ln n-n$；换底后 $\\log_2(n!)$ 主项 $n\\log_2 n$；按比例减半给 $\\log_2 n$ 步；组合数取对数化为阶乘对数之差。',
          },
        ],
      },
      {
        id: 'u19-l3',
        title: '四条主线与离散对数',
        subtitle: '反函数 · 可加化 · 尺度 · 多值，外加密码学护城河',
        questions: [
          {
            id: 'u19-l3-q1',
            type: 'match',
            prompt: '把对数的四条结构线与其含义配对：',
            left: ['反函数线', '可加化线', '尺度线', '多值线'],
            right: ['解指数位置的未知数', '乘法/连乘变加法/求和', '巨大跨度压成层级', '复数中反函数失去全局单值'],
            explain: '四线贯穿全书：反函数、可加化、尺度压缩、多值延伸——同一结构在不同章节反复展开。',
          },
          {
            id: 'u19-l3-q2',
            type: 'choice',
            prompt: '离散对数问题“已知 $a,b,p$ 求 $x$ 使 $a^x\\equiv b\\pmod p$”的难度特征是？',
            options: [
              '正向、反向都容易',
              '正向容易（快速幂 $O(\\log x)$）、反向困难（无已知多项式算法）',
              '正向困难、反向容易',
              '两向都不可计算',
            ],
            answer: 1,
            explain: '正向 $a^x\\bmod p$ 用快速幂很快；反向求 $x$ 没有已知多项式时间算法。这种不对称是 Diffie-Hellman、ElGamal 的根基。',
          },
          {
            id: 'u19-l3-q3',
            type: 'input',
            prompt: '在模 7 下解 $3^x\\equiv5\\pmod 7$。逐次算 $3^1=3,3^2\\equiv2,3^3\\equiv6,3^4\\equiv4,3^5\\equiv?$，求 $x$。',
            accept: ['5'],
            explain: '$3^5=243\\equiv5\\pmod7$，故离散对数 $x=5$。（$3^6\\equiv1$，说明 3 是模 7 的原根，阶为 6。）',
          },
          {
            id: 'u19-l3-q4',
            type: 'judge',
            prompt: '判断：对数螺旋 $r=ae^{b\\theta}$ 的自相似性，本质是“半径乘常数 $\\leftrightarrow$ 角度加常数”，即 $\\ln$ 把乘法变加法。',
            answer: true,
            explain: '由 $\\theta=\\tfrac1b\\ln\\tfrac{r}{a}$，半径乘 $\\lambda$ 对应角度加 $\\tfrac{\\ln\\lambda}{b}$——径向几何级数被 $\\ln$ 翻成角向算术级数。',
          },
          {
            id: 'u19-l3-q5',
            type: 'choice',
            prompt: '“对数在概率、信息论、算法、复分析里反复出现”最准确的解释是？',
            options: [
              '巧合，大家爱用这个符号',
              '这些问题都含相同结构：比例、连乘、倍率、层级、反向恢复指数位置',
              '因为对数公式最简单',
              '因为历史习惯',
            ],
            answer: 1,
            explain: '不是巧合：凡涉及比例/连乘/倍率/层级/反向指数的问题，对数都是自然语言——这正是“结构连接”的核心论点。',
          },
        ],
      },
    ],
  },
  // ===================== 第20章 =====================
  {
    id: 'u20',
    title: '综合与展望',
    color: '#55a630',
    icon: '🏆',
    blurb: '指数↔对数反函数全景；$e$、换底、对数标度、熵、复对数串成一条复盘线。',
    lessons: [
      {
        id: 'u20-l1',
        title: '五条主线全景',
        subtitle: '$a^x$ 与 $\\log_a x$ 关于 $y=x$ 互为镜像',
        questions: [
          {
            id: 'u20-l1-q1',
            type: 'match',
            prompt: '把全书五条主线与其含义配对：',
            left: ['反函数', '可加化', '尺度化', '分析化', '拓展化'],
            right: ['从指数回到指数位置', '乘法/概率/似然转和', '处理巨大跨度', '自然对数连接微积分', '信息/计算/复分析延展'],
            explain: '五线把 20 章压成一张图：对数来自指数逆问题，并在可加化、尺度、微积分、拓展四个方向反复现身。',
          },
          {
            id: 'u20-l1-q2',
            type: 'judge',
            prompt: '判断：指数函数 $a^x$ 与对数函数 $\\log_a x$ 关于直线 $y=x$ 互为镜像（反函数）。',
            answer: true,
            explain: '互为反函数 ⇔ 图像关于 $y=x$ 对称。自然底 $e$ 让两曲线分别过 $(1,e)$ 与 $(e,1)$ 并接通微积分。',
          },
          {
            id: 'u20-l1-q3',
            type: 'choice',
            prompt: '下列哪种情形“不必”切换到对数视角？',
            options: [
              '比较 $2^{40}$ 与 $10^{12}$ 的大小',
              '求两个相隔 30 元的价格的绝对差',
              '比较震级 6 与震级 4 的地震能量',
              '把许多很小的概率连乘',
            ],
            answer: 1,
            explain: '纯粹的绝对差值（线性差）没有倍率或巨大跨度结构，直接相减即可；其余三项都有比例/数量级，宜用对数。',
          },
          {
            id: 'u20-l1-q4',
            type: 'choice',
            prompt: '面对新问题判断“该不该用对数”，下列哪个自检问题最贴切？',
            options: [
              '这里是否有重复乘法/按比例变化/巨大跨度/层级比较？',
              '题目里有没有出现 log 这个字？',
              '数字是不是很大？',
              '是不是考试题？',
            ],
            answer: 0,
            explain: '关键不是符号或数字大小，而是结构：有比例、连乘、巨大跨度、层级或复指数反问题时，对数就是自然语言。',
          },
          {
            id: 'u20-l1-q5',
            type: 'input',
            prompt: '比较 $2^{40}$ 与 $10^{12}$：取 $\\log_{10}$，$\\log_{10}2^{40}=40\\times0.301\\approx?$（填两位小数，如 $12.04$）',
            accept: ['12.04', '12.0', '12'],
            explain: '$40\\times0.301=12.04>12=\\log_{10}10^{12}$，故 $2^{40}>10^{12}$（仅多约 10%）。换底+对数标度让数量级一目了然。',
          },
        ],
      },
      {
        id: 'u20-l2',
        title: '综合题：增长 · 似然 · 稳定',
        subtitle: '线性化、对数似然与 log-sum-exp 串成一条链',
        questions: [
          {
            id: 'u20-l2-q1',
            type: 'choice',
            prompt: '线性化模型 $\\ln N(t)=2+0.4t$ 还原成原模型为？',
            options: ['$N(t)=2e^{0.4t}$', '$N(t)=e^2e^{0.4t}$', '$N(t)=e^{0.4}t$', '$N(t)=0.4e^{2t}$'],
            answer: 1,
            explain: '对两边取指数：$N(t)=e^{2+0.4t}=e^2e^{0.4t}$。截距 $=\\ln$（初值）、斜率 $=$ 增长率。',
          },
          {
            id: 'u20-l2-q2',
            type: 'input',
            prompt: '上题模型的倍增时间满足 $e^{0.4T}=2$。求 $T=\\dfrac{\\ln 2}{0.4}\\approx?$（填两位小数，$\\ln2\\approx0.693$）',
            accept: ['1.73', '1.7', '1.733'],
            explain: '$T=\\dfrac{\\ln2}{0.4}=\\dfrac{0.693}{0.4}\\approx1.73$。“取对数解指数方程”是反函数主线的标准用法。',
          },
          {
            id: 'u20-l2-q3',
            type: 'judge',
            prompt: '判断：把概率连乘 $\\prod p_i$ 改写成对数似然 $\\sum\\ln p_i$，既能避免下溢，又把连乘变成便于求导优化的求和。',
            answer: true,
            explain: '$n$ 大且 $p_i$ 小时 $\\prod p_i$ 会下溢到 0；取对数后 $\\ln\\prod p_i=\\sum\\ln p_i$，安全相加又利于优化。',
          },
          {
            id: 'u20-l2-q4',
            type: 'choice',
            prompt: 'log-sum-exp 稳定形式 $\\ln\\sum_j e^{s_j}=m+\\ln\\sum_j e^{s_j-m}$ 中的 $m$ 取什么？',
            options: ['$\\min_j s_j$', '$\\max_j s_j$', '$0$', '平均值'],
            answer: 1,
            explain: '取 $m=\\max_j s_j$，则每个 $e^{s_j-m}\\in(0,1]$ 不再下溢/上溢。这是 softmax、交叉熵实现的关键稳定技巧。',
          },
          {
            id: 'u20-l2-q5',
            type: 'input',
            prompt: '用 log-sum-exp 算 $\\log(e^{-1000}+e^{-1002})$：取 $m=-1000$，结果约为？（填两位小数，$\\ln(1+e^{-2})\\approx0.13$）',
            accept: ['-999.87', '-999.9', '-999.88'],
            explain: '$-1000+\\ln(e^0+e^{-2})=-1000+\\ln(1.135)\\approx-1000+0.13=-999.87$，避免了直接对 $e^{-1000}$ 取指数下溢。',
          },
          {
            id: 'u20-l2-q6',
            type: 'match',
            prompt: '把这条“增长—似然—稳定”链上的每一步与其对数操作配对：',
            left: ['指数增长建模', '概率连乘', '对数和换回比较', '解倍增时间'],
            right: ['线性化 $\\ln N=\\ln N_0+kt$', '对数似然 $\\sum\\ln p_i$', 'log-sum-exp 提 $\\max$', '取对数 $T=\\tfrac{\\ln2}{k}$'],
            explain: '线性化把指数变直线、连乘取对数变求和、换回时用 log-sum-exp 提最大值稳定、倍增时间靠取对数解指数方程——同一条对数链的四步。',
          },
        ],
      },
      {
        id: 'u20-l3',
        title: '复对数收束与欧拉恒等式',
        subtitle: '$e^{i\\pi}+1=0$ 是五条主线的交汇点',
        questions: [
          {
            id: 'u20-l3-q1',
            type: 'choice',
            prompt: '为什么实对数单值、复对数多值？最根本的原因是？',
            options: [
              '复数没有大小',
              '实指数一一对应、复指数因周期性失去一一性',
              '复对数定义不完善',
              '虚数不能取对数',
            ],
            answer: 1,
            explain: '实数上指数可逆 → 反函数单值；复数上指数有周期 → 不再一一对应 → 复对数只能靠主值与分支局部单值。',
          },
          {
            id: 'u20-l3-q2',
            type: 'input',
            prompt: '综合复对数与复幂，求 $(1+i)^i$ 主值时第一步：$\\operatorname{Log}(1+i)=\\tfrac12\\ln2+i\\tfrac{\\pi}{4}$。其主辐角 $\\operatorname{Arg}(1+i)=?$（填 $\\tfrac{\\pi}{4}$ 形式）',
            accept: ['\\pi/4', '\\frac{\\pi}{4}', 'π/4', 'pi/4'],
            explain: '$|1+i|=\\sqrt2,\\ \\operatorname{Arg}(1+i)=\\tfrac{\\pi}{4}$，故 $\\operatorname{Log}(1+i)=\\ln\\sqrt2+i\\tfrac{\\pi}{4}=\\tfrac12\\ln2+i\\tfrac{\\pi}{4}$。',
          },
          {
            id: 'u20-l3-q3',
            type: 'choice',
            prompt: '欧拉恒等式 $e^{i\\pi}+1=0$ 取主值对数得到？',
            options: ['$\\operatorname{Log}(-1)=i\\pi$', '$\\operatorname{Log}(1)=i\\pi$', '$\\operatorname{Log}(0)=\\pi$', '$\\ln\\pi=i$'],
            answer: 0,
            explain: '$e^{i\\pi}=-1$ 的对数面孔正是 $\\operatorname{Log}(-1)=i\\pi$。恒等式与主值对数互为指数/对数。',
          },
          {
            id: 'u20-l3-q4',
            type: 'judge',
            prompt: '判断：$e^{i\\pi}+1=0$ 同时触及反函数、可加化、自然底数、复对数多值性这几条主线，是整套教程的交汇点。',
            answer: true,
            explain: '反函数（$\\operatorname{Log}(-1)=i\\pi$）、可加化（$e^{i\\theta_1}e^{i\\theta_2}=e^{i(\\theta_1+\\theta_2)}$）、自然底 $e$、多值性（$\\log(-1)=i(\\pi+2k\\pi)$ 选主支）四线在此交汇。',
          },
          {
            id: 'u20-l3-q5',
            type: 'match',
            prompt: '把同一个“反向问题”的三种形态与其难度配对：',
            left: ['$e^{kt}=2$ 求 $t$', '二分查找 $O(\\log n)$', '$g^x\\equiv b\\pmod p$'],
            right: ['连续可逆：一行闭式解 $t=\\tfrac{\\ln2}{k}$', '离散单调：给复杂度 $\\log_2 n$', '模运算不可逆：无多项式算法'],
            explain: '同一“反向恢复指数位置”的问题，随定义域从连续实数→离散整数→模 $p$ 剩余系，难度从闭式解跃到密码学护城河。',
          },
          {
            id: 'u20-l3-q6',
            type: 'choice',
            prompt: '学完整套教程，对数最本质的升级是？',
            options: [
              '记住了更多公式',
              '从“题型”升级为“工具”：会判断何时切换到对数视角看结构',
              '只会做复对数题',
              '背下了所有换底公式',
            ],
            answer: 1,
            explain: '目标不是装满公式，而是形成判断：遇到比例、连乘、巨大跨度或复指数反问题，就切换到对数视角——用结构看对数。',
          },
        ],
      },
    ],
  },
]
