import type { Unit } from '../../types'

// 第五部分：信息与计算（第15–17章）。每章 → 一个单元，每单元 3 课。
// 内容取自《从零到高阶的对数函数教程》part5（概率与信息、对数似然·熵·交叉熵、log-sum-exp 与数值稳定）。
export const PART5_UNITS: Unit[] = [
  // ===================== u15 概率与信息 =====================
  {
    id: 'u15',
    title: '概率与信息',
    color: '#6c5ce7',
    icon: '🎲',
    blurb: '为什么概率连乘要取对数？自信息 $-\\log_2 p$ 又是怎么来的？',
    lessons: [
      {
        id: 'u15-l1',
        title: '概率连乘与对数',
        subtitle: '把连乘压成连加',
        questions: [
          {
            id: 'u15-l1-q1',
            type: 'choice',
            prompt: '$n$ 个独立事件同时发生的概率是 $\\prod_{i=1}^n P(A_i)$。取对数后它变成什么？',
            options: [
              '$\\sum_{i=1}^n \\log P(A_i)$',
              '$\\prod_{i=1}^n \\log P(A_i)$',
              '$\\log\\left(\\sum_{i=1}^n P(A_i)\\right)$',
              '$n\\log P(A_1)$',
            ],
            answer: 0,
            explain: '$\\log$ 把乘积变成求和：$\\log\\prod_i P(A_i)=\\sum_i \\log P(A_i)$。这正是对数在概率里无处不在的根本原因。',
          },
          {
            id: 'u15-l1-q2',
            type: 'judge',
            prompt: '判断：把许多很小的概率直接连乘，在计算机里容易因数值过小而下溢，而取对数后改成连加就能缓解。',
            answer: true,
            explain: '正确。$0.001^{100}$ 这类乘积会下溢成 0；改成 $\\sum \\log p_i$（大量负数相加）则数值稳定得多。',
          },
          {
            id: 'u15-l1-q3',
            type: 'input',
            prompt: '已知 $\\log(ab)=\\log a+\\log b$。那么 $\\log\\left(\\tfrac12\\cdot\\tfrac14\\cdot\\tfrac18\\right)$ 应写成 $\\log\\tfrac12+\\log\\tfrac14+\\,?$。请填入缺失的那一项（形如 \\log\\frac18）。',
            accept: ['\\log\\frac18', '\\log\\frac{1}{8}', 'log(1/8)', '\\log_2\\frac18', 'log 1/8'],
            explain: '连乘取对数后逐项相加：$\\log\\tfrac12+\\log\\tfrac14+\\log\\tfrac18$。',
          },
          {
            id: 'u15-l1-q4',
            type: 'choice',
            prompt: '“对数把乘法变成加法”这条主线，最早在本教程哪一处出现过？',
            options: [
              '第3章（运算法则）',
              '复对数那一章',
              '从来没出现过，是本章独有',
              '只在导数那一章',
            ],
            answer: 0,
            explain: '第3章的运算法则 $\\log(ab)=\\log a+\\log b$ 就是源头；概率连乘只是它的又一次自然应用。',
          },
          {
            id: 'u15-l1-q5',
            type: 'match',
            prompt: '把乘法世界与加法世界里的对应概念连起来。',
            left: ['概率连乘 $\\prod p_i$', '小概率下溢', '联合概率', '$\\log$ 变换'],
            right: ['对数求和 $\\sum\\log p_i$', '负数相加更稳定', '各事件信息量之和', '乘法 → 加法的桥梁'],
            explain: '对数把“乘法世界”整体翻译到“加法世界”，连乘、下溢、联合概率都因此变得好处理。',
          },
        ],
      },
      {
        id: 'u15-l2',
        title: '自信息 $-\\log p$',
        subtitle: '越罕见，信息越多',
        questions: [
          {
            id: 'u15-l2-q1',
            type: 'input',
            prompt: '某事件概率为 $1/8$。以 2 为底的自信息 $I=-\\log_2 p$ 等于多少 bit？（填数字）',
            accept: ['3', '3 bit', '3bit', '3.0'],
            explain: '$-\\log_2\\tfrac18=-(-3)=3$ bit。',
          },
          {
            id: 'u15-l2-q2',
            type: 'choice',
            prompt: '随着 $p\\to 0^+$，自信息 $I(A)=-\\log_2 p$ 的变化趋势是？',
            options: [
              '趋于 $+\\infty$（越罕见，信息越大）',
              '趋于 $0$',
              '趋于 $1$ bit',
              '趋于 $-\\infty$',
            ],
            answer: 0,
            explain: '$p\\to 0$ 时 $-\\log_2 p\\to+\\infty$：极罕见事件一旦发生会带来巨大的认知冲击。',
          },
          {
            id: 'u15-l2-q3',
            type: 'judge',
            prompt: '判断：概率为 1 的确定事件，其自信息为 0 bit。',
            answer: true,
            explain: '正确。$-\\log_2 1=0$：必然发生的事不带来任何新消息。',
          },
          {
            id: 'u15-l2-q4',
            type: 'choice',
            prompt: '两个独立事件概率为 $\\tfrac12$ 和 $\\tfrac14$，联合发生的自信息是多少 bit？',
            options: ['3', '2', '8', '1.5'],
            answer: 0,
            explain: '联合概率 $\\tfrac12\\cdot\\tfrac14=\\tfrac18$，$-\\log_2\\tfrac18=3$。它恰等于 $1+2$，即各自信息量之和。',
          },
          {
            id: 'u15-l2-q5',
            type: 'judge',
            prompt: '判断：概率越大，自信息越大。',
            answer: false,
            explain: '错误。恰好相反——概率越大越“不稀奇”，自信息越小；$-\\log p$ 随 $p$ 增大而减小。',
          },
          {
            id: 'u15-l2-q6',
            type: 'match',
            prompt: '把概率与对应的以 2 为底自信息（bit）配对。',
            left: ['$p=1$', '$p=1/2$', '$p=1/4$', '$p=1/1024$'],
            right: ['$0$ bit', '$1$ bit', '$2$ bit', '$10$ bit'],
            explain: '$-\\log_2 p$：$1\\to0$，$\\tfrac12\\to1$，$\\tfrac14\\to2$，$\\tfrac1{1024}=2^{-10}\\to10$。',
          },
        ],
      },
      {
        id: 'u15-l3',
        title: '底数与信息单位',
        subtitle: 'bit、nat、hartley',
        questions: [
          {
            id: 'u15-l3-q1',
            type: 'match',
            prompt: '把对数底数与对应的信息单位配对。',
            left: ['底数 2', '底数 $e$', '底数 10'],
            right: ['bit', 'nat', 'hartley'],
            explain: '底数 2 → bit，底数 $e$ → nat，底数 10 → hartley。不同底数只是换刻度。',
          },
          {
            id: 'u15-l3-q2',
            type: 'judge',
            prompt: '判断：换用不同底数会改变“概率越小，信息越大”这一核心结构。',
            answer: false,
            explain: '错误。由换底公式，不同底数只是乘以一个正常数，单位变了但单调结构不变。',
          },
          {
            id: 'u15-l3-q3',
            type: 'choice',
            prompt: '$1$ nat 约等于多少 bit？（换算因子为 $1/\\ln 2$）',
            options: ['约 $1.4427$ bit', '约 $0.6931$ bit', '恰好 $1$ bit', '约 $2.3026$ bit'],
            answer: 0,
            explain: '$\\log_2 x=\\ln x/\\ln 2$，故 $1$ nat $=1/\\ln 2\\approx1.4427$ bit。',
          },
          {
            id: 'u15-l3-q4',
            type: 'input',
            prompt: '一个公平四面骰子每面概率 $1/4$，其熵 $H=-\\sum p_i\\log_2 p_i$ 等于多少 bit？（填数字）',
            accept: ['2', '2 bit', '2bit', '2.0'],
            explain: '$H=-4\\cdot\\tfrac14\\log_2\\tfrac14=-4\\cdot\\tfrac14\\cdot(-2)=2$ bit，即 $\\log_2 4$。',
          },
          {
            id: 'u15-l3-q5',
            type: 'choice',
            prompt: '把公平四面骰子改成有偏分布 $p=(\\tfrac12,\\tfrac14,\\tfrac18,\\tfrac18)$，熵会怎样变化？',
            options: [
              '变小（从 $2$ 降到 $1.75$ bit）',
              '变大',
              '不变，仍是 $2$ bit',
              '变成 $0$',
            ],
            answer: 0,
            explain: '有偏分布更“可预测”，熵更小：$H=\\tfrac12+\\tfrac12+\\tfrac38+\\tfrac38=1.75<2$。均匀分布熵最大。',
          },
        ],
      },
    ],
  },

  // ============= u16 对数似然·熵·交叉熵 =============
  {
    id: 'u16',
    title: '对数似然·熵·交叉熵',
    color: '#0984e3',
    icon: '🔥',
    blurb: '熵、交叉熵、KL 散度，以及机器学习为什么爱优化对数损失。',
    lessons: [
      {
        id: 'u16-l1',
        title: '对数似然',
        subtitle: '把样本概率乘积变成求和',
        questions: [
          {
            id: 'u16-l1-q1',
            type: 'choice',
            prompt: '独立样本似然 $L(\\theta)=\\prod_{i=1}^n p(x_i\\mid\\theta)$。对数似然 $\\ell(\\theta)$ 等于？',
            options: [
              '$\\sum_{i=1}^n \\log p(x_i\\mid\\theta)$',
              '$\\prod_{i=1}^n \\log p(x_i\\mid\\theta)$',
              '$n\\log p(x_1\\mid\\theta)$',
              '$\\log n$',
            ],
            answer: 0,
            explain: '$\\ell(\\theta)=\\log L(\\theta)=\\sum_i\\log p(x_i\\mid\\theta)$：连乘变连加，便于求导与计算。',
          },
          {
            id: 'u16-l1-q2',
            type: 'judge',
            prompt: '判断：因为 $\\log$ 在合法范围内严格单调递增，使 $L(\\theta)$ 最大的参数也使 $\\ell(\\theta)=\\log L(\\theta)$ 最大。',
            answer: true,
            explain: '正确。单调变换不改变最大值点，所以最大化似然 ⇔ 最大化对数似然，但后者更好算。',
          },
          {
            id: 'u16-l1-q3',
            type: 'input',
            prompt: '抛硬币 5 次得“正正反正反”（3 正 2 反），正面概率为 $\\theta$。对数似然 $\\ell(\\theta)=3\\log\\theta+?\\,\\log(1-\\theta)$，缺失的系数是多少？（填数字）',
            accept: ['2'],
            explain: '$L=\\theta^3(1-\\theta)^2$，取对数得 $\\ell=3\\log\\theta+2\\log(1-\\theta)$。',
          },
          {
            id: 'u16-l1-q4',
            type: 'choice',
            prompt: '对上一题数据，伯努利 MLE $\\hat\\theta=k/n$ 给出正面概率的估计是？',
            options: ['$0.6$', '$0.5$', '$0.4$', '$0.3$'],
            answer: 0,
            explain: '$\\hat\\theta=k/n=3/5=0.6$，即“频率即最大似然估计”。',
          },
          {
            id: 'u16-l1-q5',
            type: 'judge',
            prompt: '判断：取对数似然的一个实际好处是避免大量小概率连乘导致的数值下溢。',
            answer: true,
            explain: '正确。这正好把第17章的数值稳定性主题预先牵了出来。',
          },
        ],
      },
      {
        id: 'u16-l2',
        title: '熵与交叉熵',
        subtitle: '平均信息量与编码代价',
        questions: [
          {
            id: 'u16-l2-q1',
            type: 'choice',
            prompt: '离散随机变量的熵定义为？',
            options: [
              '$H(X)=-\\sum_i p_i\\log p_i$',
              '$H(X)=\\sum_i p_i\\log p_i$',
              '$H(X)=-\\sum_i \\log p_i$',
              '$H(X)=\\prod_i p_i$',
            ],
            answer: 0,
            explain: '熵是“按真实概率加权的平均自信息”：$H=\\sum_i p_i\\cdot(-\\log p_i)=-\\sum_i p_i\\log p_i$。',
          },
          {
            id: 'u16-l2-q2',
            type: 'choice',
            prompt: '二元熵 $H(p)=-p\\log_2 p-(1-p)\\log_2(1-p)$ 在何处取得最大值？最大值是多少？',
            options: [
              '$p=\\tfrac12$，最大值 $1$ bit',
              '$p=0$，最大值 $0$',
              '$p=1$，最大值 $1$ bit',
              '$p=\\tfrac14$，最大值 $2$ bit',
            ],
            answer: 0,
            explain: '钟形曲线在最公平、最不确定的 $p=\\tfrac12$ 取峰值 $1$ bit；两端 $p=0,1$（完全确定）为 0。',
          },
          {
            id: 'u16-l2-q3',
            type: 'choice',
            prompt: '真实分布 $p$、模型分布 $q$ 的交叉熵定义为？',
            options: [
              '$H(p,q)=-\\sum_i p_i\\log q_i$',
              '$H(p,q)=-\\sum_i q_i\\log p_i$',
              '$H(p,q)=-\\sum_i p_i\\log p_i$',
              '$H(p,q)=\\sum_i p_i q_i$',
            ],
            answer: 0,
            explain: '交叉熵 $H(p,q)=-\\sum_i p_i\\log q_i$：用模型 $q$ 编码真实分布 $p$ 的平均代价。注意是 $\\log q_i$。',
          },
          {
            id: 'u16-l2-q4',
            type: 'judge',
            prompt: '判断：对二分类真实标签 $(1,0)$，预测 $(0.1,0.9)$ 的交叉熵比预测 $(0.9,0.1)$ 更大。',
            answer: true,
            explain: '正确。前者 $-\\log 0.1$ 远大于后者 $-\\log 0.9$：模型把概率压错到真实类别之外，惩罚更重。',
          },
          {
            id: 'u16-l2-q5',
            type: 'input',
            prompt: '二分类真实标签 $y=1$，损失 $\\ell=-\\log\\hat y$。当 $\\hat y=1$（完美预测）时损失等于多少？（填数字）',
            accept: ['0', '0.0'],
            explain: '$-\\log 1=0$：预测正确且满置信，损失为 0。',
          },
          {
            id: 'u16-l2-q6',
            type: 'match',
            prompt: '把三个量与其含义配对。',
            left: ['熵 $H(p)$', '交叉熵 $H(p,q)$', '自信息 $-\\log p_i$'],
            right: ['真实分布自身的平均信息量', '用 $q$ 编码 $p$ 的平均代价', '单个事件的信息量'],
            explain: '结构链：单个事件信息量 → 按真实概率平均得熵 → 换成模型分布编码得交叉熵。',
          },
        ],
      },
      {
        id: 'u16-l3',
        title: 'KL 散度与 log-loss',
        subtitle: '为什么交叉熵是好的损失',
        questions: [
          {
            id: 'u16-l3-q1',
            type: 'choice',
            prompt: 'KL 散度与交叉熵、熵的关系是？',
            options: [
              '$D_{\\mathrm{KL}}(p\\|q)=H(p,q)-H(p)$',
              '$D_{\\mathrm{KL}}(p\\|q)=H(p)-H(p,q)$',
              '$D_{\\mathrm{KL}}(p\\|q)=H(p,q)+H(p)$',
              '$D_{\\mathrm{KL}}(p\\|q)=H(p)\\cdot H(p,q)$',
            ],
            answer: 0,
            explain: '$D_{\\mathrm{KL}}(p\\|q)=\\sum_i p_i\\log\\tfrac{p_i}{q_i}=H(p,q)-H(p)$：交叉熵比熵多出来的那部分。',
          },
          {
            id: 'u16-l3-q2',
            type: 'judge',
            prompt: '判断：KL 散度满足 $D_{\\mathrm{KL}}(p\\|q)\\ge 0$，且等号当且仅当 $p=q$。',
            answer: true,
            explain: '正确，这是 Gibbs 不等式，用切线不等式 $\\ln x\\le x-1$ 即可证明。',
          },
          {
            id: 'u16-l3-q3',
            type: 'judge',
            prompt: '判断：KL 散度是对称的，即 $D_{\\mathrm{KL}}(p\\|q)=D_{\\mathrm{KL}}(q\\|p)$，所以它是一种距离。',
            answer: false,
            explain: '错误。KL 散度一般不对称，也不满足三角不等式，因此不是严格意义上的“距离”。',
          },
          {
            id: 'u16-l3-q4',
            type: 'choice',
            prompt: '当真实分布 $p$ 固定时，为什么“最小化交叉熵 $H(p,q)$”等价于“最小化 $D_{\\mathrm{KL}}(p\\|q)$”？',
            options: [
              '因为 $H(p,q)=H(p)+D_{\\mathrm{KL}}(p\\|q)$，而 $H(p)$ 是常数',
              '因为交叉熵恒等于 KL 散度',
              '因为 $H(p)=0$ 总成立',
              '因为 $q$ 不影响交叉熵',
            ],
            answer: 0,
            explain: '$p$ 固定时 $H(p)$ 是常数，所以对 $q$ 优化时两者只差一个常数，最优解相同（都在 $q=p$）。',
          },
          {
            id: 'u16-l3-q5',
            type: 'input',
            prompt: '多分类中 softmax 接交叉熵，损失对 logit $z_k$ 的梯度有极简形式 $\\partial\\ell/\\partial z_k=q_k-\\,?$。缺失的项是什么？（填 p_k 或 q_k 之一）',
            accept: ['p_k', 'p', 'pk', 'p_{k}'],
            explain: '$\\partial\\ell/\\partial z_k=q_k-p_k$，即“预测减真实”。这把交叉熵与下一章的 log-sum-exp 直接缝合。',
          },
          {
            id: 'u16-l3-q6',
            type: 'judge',
            prompt: '判断：log-loss 会对“高置信但错误”的预测施加非常大的惩罚，因为 $q$ 很小时 $-\\log q$ 迅速增大。',
            answer: true,
            explain: '正确。这正是“自信但错误要重罚”的合理误差尺度，使对数成为分类损失的天然选择。',
          },
        ],
      },
    ],
  },

  // ============= u17 log-sum-exp·数值稳定 =============
  {
    id: 'u17',
    title: 'log-sum-exp·数值稳定',
    color: '#00cd9c',
    icon: '🛡️',
    blurb: '当对数目标真正落进计算机：如何防溢出、稳定 softmax 与 log-softmax。',
    lessons: [
      {
        id: 'u17-l1',
        title: 'log-sum-exp 与溢出',
        subtitle: '数学正确 ≠ 数值可算',
        questions: [
          {
            id: 'u17-l1-q1',
            type: 'choice',
            prompt: '直接计算 $\\log\\!\\left(e^{1000}+e^{999}\\right)$ 时，主要风险是什么？',
            options: [
              '$e^{1000}$ 在浮点里上溢成 $+\\infty$',
              '结果一定为负数',
              '$\\log$ 没有定义',
              '完全没有问题',
            ],
            answer: 0,
            explain: '双精度最大约 $1.8\\times10^{308}$，而 $e^{1000}$ 远超此值，会上溢成 $\\infty$，整个结果失效。',
          },
          {
            id: 'u17-l1-q2',
            type: 'judge',
            prompt: '判断：上溢会让结果变成无穷大，而下溢会让某些项被错误地当成完全不存在（变成 0）。',
            answer: true,
            explain: '正确。两种情形都会破坏后续计算，这正是需要稳定技巧的原因。',
          },
          {
            id: 'u17-l1-q3',
            type: 'choice',
            prompt: '$\\mathrm{LSE}(x,0)=\\ln(e^x+1)$（即 softplus）在几何上是什么的光滑近似？',
            options: [
              '$\\max(x,0)$（ReLU 折线）',
              '$|x|$',
              '常函数 $1$',
              '$\\sin x$',
            ],
            answer: 0,
            explain: 'log-sum-exp 是 $\\max$ 的光滑近似：softplus 把 ReLU 的尖角磨圆，两端又紧贴折线。',
          },
          {
            id: 'u17-l1-q4',
            type: 'input',
            prompt: 'log-sum-exp 的稳定形式：先取 $m=\\max_i x_i$，则 $\\log\\sum_i e^{x_i}=m+\\log\\sum_i e^{x_i-\\,?}$。缺失处填什么？（填一个字母）',
            accept: ['m'],
            explain: '$\\log\\sum_i e^{x_i}=m+\\log\\sum_i e^{x_i-m}$：减去最大值后所有指数项 $\\le 1$，不会爆炸。',
          },
          {
            id: 'u17-l1-q5',
            type: 'judge',
            prompt: '判断：稳定形式 $m+\\log\\sum_i e^{x_i-m}$ 只是一个近似公式，会引入误差。',
            answer: false,
            explain: '错误。它来自 $\\sum_i e^{x_i}=e^m\\sum_i e^{x_i-m}$，是严格恒等变形，不是近似。',
          },
        ],
      },
      {
        id: 'u17-l2',
        title: '减最大值的恒等性',
        subtitle: '为什么这样做合法',
        questions: [
          {
            id: 'u17-l2-q1',
            type: 'choice',
            prompt: '稳定技巧的代数依据是哪个恒等式？',
            options: [
              '$\\sum_i e^{x_i}=e^{m}\\sum_i e^{x_i-m}$',
              '$\\sum_i e^{x_i}=e^{m}+\\sum_i e^{x_i-m}$',
              '$\\sum_i e^{x_i}=m\\sum_i e^{x_i}$',
              '$\\sum_i e^{x_i}=\\sum_i (e^{x_i}-m)$',
            ],
            answer: 0,
            explain: '提取公共因子 $e^m$：$\\sum_i e^{x_i}=\\sum_i e^m e^{x_i-m}=e^m\\sum_i e^{x_i-m}$，再取对数即得稳定式。',
          },
          {
            id: 'u17-l2-q2',
            type: 'input',
            prompt: '用稳定公式计算 $\\mathrm{LSE}(100,98,95)$，取整数 $m=100$。结果约为 $100+\\ln(1+e^{-2}+e^{-5})\\approx100.?$，小数部分约为 $0.133$。请填 $m$ 的值。（填数字）',
            accept: ['100'],
            explain: '$m=\\max(100,98,95)=100$，$\\mathrm{LSE}=100+\\ln(1+0.1353+0.0067)\\approx100.133$，全程只处理 $\\le1$ 的数。',
          },
          {
            id: 'u17-l2-q3',
            type: 'judge',
            prompt: '判断：把所有 logits 同时加上或减去同一个常数 $c$，softmax 的输出保持不变。',
            answer: true,
            explain: '正确。$\\mathrm{softmax}(x_i)=\\mathrm{softmax}(x_i-c)$，分子分母同乘 $e^{-c}$ 即可验证。取 $c=m$ 只是为了数值安全。',
          },
          {
            id: 'u17-l2-q4',
            type: 'choice',
            prompt: '设 $f(x)=\\ln\\sum_j e^{x_j}$（即 LSE）。它对 $x_k$ 的偏导 $\\partial f/\\partial x_k$ 等于什么？',
            options: [
              '$\\mathrm{softmax}(x_k)$',
              '$e^{x_k}$',
              '$x_k$',
              '$1$',
            ],
            answer: 0,
            explain: '$\\partial f/\\partial x_k=\\dfrac{e^{x_k}}{\\sum_j e^{x_j}}=\\mathrm{softmax}(x_k)$：LSE 是 softmax 的“原函数”。',
          },
          {
            id: 'u17-l2-q5',
            type: 'judge',
            prompt: '判断：LSE 的梯度向量各分量都为正且总和为 1。',
            answer: true,
            explain: '正确。梯度就是 softmax 概率向量，自然非负且和为 1——这也解释了 LSE 为何被称为“光滑的 max”。',
          },
        ],
      },
      {
        id: 'u17-l3',
        title: 'softmax 与 log-softmax',
        subtitle: '深度学习里的稳定实现',
        questions: [
          {
            id: 'u17-l3-q1',
            type: 'choice',
            prompt: 'softmax 的稳定计算式是？',
            options: [
              '$\\dfrac{e^{x_i-m}}{\\sum_j e^{x_j-m}}$',
              '$\\dfrac{e^{x_i+m}}{\\sum_j e^{x_j+m}}$',
              '$\\dfrac{e^{x_i}}{\\sum_j e^{x_j}+m}$',
              '$\\dfrac{e^{x_i}}{m}$',
            ],
            answer: 0,
            explain: '分子分母同减最大值 $m$：$\\dfrac{e^{x_i-m}}{\\sum_j e^{x_j-m}}$，结果不变但能防大数溢出。',
          },
          {
            id: 'u17-l3-q2',
            type: 'input',
            prompt: '计算 $\\mathrm{softmax}(3,1,-2)$ 的第一个分量，用减最大值形式：$\\dfrac{1}{1+e^{-2}+e^{-5}}\\approx0.??$（保留两位，约 0.88）。请填 $m=\\max(3,1,-2)$ 的值。（填数字）',
            accept: ['3'],
            explain: '$m=3$，第一分量 $=\\dfrac{e^0}{e^0+e^{-2}+e^{-5}}=\\dfrac{1}{1.1421}\\approx0.8756$。',
          },
          {
            id: 'u17-l3-q3',
            type: 'choice',
            prompt: '稳定的 log-softmax 应写成下面哪种形式（$m=\\max_j x_j$）？',
            options: [
              '$(x_k-m)-\\ln\\sum_j e^{x_j-m}$',
              '$\\ln\\left(\\dfrac{e^{x_k}}{\\sum_j e^{x_j}}\\right)$ 先算 softmax 再取对数',
              '$x_k-\\sum_j e^{x_j}$',
              '$\\ln x_k-\\ln m$',
            ],
            answer: 0,
            explain: '$\\log\\mathrm{softmax}(x_k)=x_k-\\mathrm{LSE}(x)=(x_k-m)-\\ln\\sum_j e^{x_j-m}$，全程不溢出、不丢精度。',
          },
          {
            id: 'u17-l3-q4',
            type: 'judge',
            prompt: '判断：“先算 softmax 再取对数”是稳健做法，不会损失精度。',
            answer: false,
            explain: '错误。当某 $x_k$ 远小于 $m$ 时 $\\mathrm{softmax}(x_k)$ 会下溢为 0，再 $\\ln 0=-\\infty$，精度彻底丢失。应直接用稳定 log-softmax 式。',
          },
          {
            id: 'u17-l3-q5',
            type: 'judge',
            prompt: '判断：softmax → 交叉熵这条链条，正是 log-sum-exp 数值稳定性在机器学习里被真实需要的地方。',
            answer: true,
            explain: '正确。分类模型用 softmax，其输出进入交叉熵，所以稳定 LSE / log-softmax 是几乎所有框架交叉熵损失的底层实现。',
          },
          {
            id: 'u17-l3-q6',
            type: 'match',
            prompt: '把概念与其稳定/正确表达式配对。',
            left: ['log-sum-exp（稳定）', 'softmax（稳定）', 'log-softmax（稳定）', 'softmax 梯度的来源'],
            right: [
              '$m+\\ln\\sum_i e^{x_i-m}$',
              '$\\dfrac{e^{x_i-m}}{\\sum_j e^{x_j-m}}$',
              '$(x_k-m)-\\ln\\sum_j e^{x_j-m}$',
              'LSE 的梯度 $\\partial f/\\partial x_k$',
            ],
            explain: '四者环环相扣：LSE 给出归一化常数，其梯度即 softmax，log-softmax 则是交叉熵损失的稳定底座。',
          },
        ],
      },
    ],
  },
]
