import type { Unit } from '../../types'

// Part 1 · 对数基础（第 1–3 章）：为什么需要对数 / 定义·记号·底 / 运算法则·换底
export const PART1_UNITS: Unit[] = [
  // ===================== 单元 1：为什么需要对数 =====================
  {
    id: 'u1',
    title: '为什么需要对数',
    color: '#58cc02',
    icon: '🔑',
    blurb: '从「指数的反向问题」出发，理解对数如何把乘法变加法、把数量级压缩成一个小数字。',
    lessons: [
      {
        id: 'u1-l1',
        title: '指数的反向问题',
        subtitle: '已知结果，反求指数',
        questions: [
          {
            id: 'u1-l1-q1',
            type: 'choice',
            prompt: '由 $2^3=8$ 反向提问「以 2 为底，要得到 8，指数是多少」，这个未知指数记作什么？',
            options: ['$\\log_2 8$', '$\\log_8 2$', '$2^8$', '$8^2$'],
            answer: 0,
            explain: '对数就是「指数位置上的未知数」：$\\log_2 8=3$。底数仍是 2，真数是 8。',
          },
          {
            id: 'u1-l1-q2',
            type: 'input',
            prompt: '求 $\\log_2 8$ 的值。',
            accept: ['3'],
            explain: '因为 $2^3=8$，所以 $\\log_2 8=3$。',
          },
          {
            id: 'u1-l1-q3',
            type: 'judge',
            prompt: '判断：对数 $\\log_a x$ 的值，就是「$a$ 的多少次幂等于 $x$」中的那个指数。',
            answer: true,
            explain: '正确。对数的值是一个**指数**，不是真数 $x$ 本身。这是理解对数的关键。',
          },
          {
            id: 'u1-l1-q4',
            type: 'choice',
            prompt: '反向关系 $a^y=x$ 等价于下面哪一个？',
            options: ['$\\log_a x=y$', '$\\log_x a=y$', '$\\log_y a=x$', '$\\log_a y=x$'],
            answer: 0,
            explain: '$a^y=x \\iff \\log_a x=y$。底数 $a$ 不变，结果 $x$ 成为真数，指数 $y$ 成为对数的值。',
          },
          {
            id: 'u1-l1-q5',
            type: 'input',
            prompt: '已知 $3^4=81$，求 $\\log_3 81$。',
            accept: ['4'],
            explain: '$\\log_3 81$ 问「3 的几次方等于 81」，答案是 4。',
          },
          {
            id: 'u1-l1-q6',
            type: 'match',
            prompt: '把每个对数与它的值配对。',
            left: ['$\\log_2 8$', '$\\log_3 81$', '$\\log_5 25$', '$\\log_{10}1000$'],
            right: ['3', '4', '2', '3'],
            explain: '$2^3=8,\\ 3^4=81,\\ 5^2=25,\\ 10^3=1000$，依次读出指数即可。',
          },
        ],
      },
      {
        id: 'u1-l2',
        title: '数量级与尺度压缩',
        subtitle: '对数关心的是层级，不是数值',
        questions: [
          {
            id: 'u1-l2-q1',
            type: 'input',
            prompt: '求 $\\log_{10}1000000$（一百万）。',
            accept: ['6'],
            explain: '$10^6=1000000$，所以常用对数直接读出「有 6 个数量级」，巨大的数被压缩成 6。',
          },
          {
            id: 'u1-l2-q2',
            type: 'choice',
            prompt: '把 $10,\\ 1000,\\ 1000000$ 取常用对数后，依次得到？',
            options: ['$1,\\ 3,\\ 6$', '$1,\\ 2,\\ 3$', '$10,\\ 100,\\ 1000$', '$0,\\ 3,\\ 6$'],
            answer: 0,
            explain: '$\\lg 10=1,\\ \\lg 1000=3,\\ \\lg 1000000=6$。跨度巨大的数变成了可直接比较的层级。',
          },
          {
            id: 'u1-l2-q3',
            type: 'judge',
            prompt: '判断：取对数会改变这几个数的大小顺序。',
            answer: false,
            explain: '错误。对数保持大小顺序不变，只是把「绝对大小」换成了「指数层级」，便于比较。',
          },
          {
            id: 'u1-l2-q4',
            type: 'choice',
            prompt: '某地震 A 的振幅是 B 的 $10000$ 倍。若「振幅放大 10 倍对应震级差 1」，A 比 B 的震级约高多少？',
            options: ['4 级', '3 级', '10 级', '$10000$ 级'],
            answer: 0,
            explain: '振幅比 $10^d=10000$，故 $d=\\lg 10000=4$。震级本身就是一种对数尺度。',
          },
          {
            id: 'u1-l2-q5',
            type: 'input',
            prompt: '求 $\\log_{10}10^7$。',
            accept: ['7'],
            explain: '$10^7$ 表示从 1 出发连乘 7 次 10，所以「需要 7 个 10 的倍率」，答案是 7。',
          },
          {
            id: 'u1-l2-q6',
            type: 'judge',
            prompt: '判断：$\\log_{10}1000=3$ 的意思是「1000 除以 10 得 3」。',
            answer: false,
            explain: '错误。它的意思是「10 的 3 次方等于 1000」，即需要 3 个数量级，而不是做除法。',
          },
        ],
      },
      {
        id: 'u1-l3',
        title: '乘法变加法',
        subtitle: '对数最核心的结构价值',
        questions: [
          {
            id: 'u1-l3-q1',
            type: 'choice',
            prompt: '一个信号先放大 $1000$ 倍再放大 $100$ 倍。用常用对数，总放大的层级数等于？',
            options: ['$3+2=5$', '$3\\times2=6$', '$1000+100$', '$3-2=1$'],
            answer: 0,
            explain: '$\\lg(1000\\times100)=\\lg 1000+\\lg 100=3+2=5$。乘法关系变成了加法关系。',
          },
          {
            id: 'u1-l3-q2',
            type: 'input',
            prompt: '求 $\\log_{10}(100\\times1000)$。',
            accept: ['5'],
            explain: '$100\\times1000=100000=10^5$，所以等于 5，也等于 $\\lg 100+\\lg 1000=2+3$。',
          },
          {
            id: 'u1-l3-q3',
            type: 'judge',
            prompt: '判断：计算尺能用「长度相加」完成乘法，正是因为 $\\lg(ab)=\\lg a+\\lg b$。',
            answer: true,
            explain: '正确。两段对数刻度首尾拼接（物理加法）就完成了乘法，这是计算尺的原理。',
          },
          {
            id: 'u1-l3-q4',
            type: 'choice',
            prompt: '不计算具体值，$\\log_2 50$ 落在哪两个相邻整数之间？',
            options: ['5 和 6', '4 和 5', '6 和 7', '49 和 51'],
            answer: 0,
            explain: '用最近的 2 的幂夹逼：$2^5=32<50<64=2^6$，所以 $5<\\log_2 50<6$。',
          },
          {
            id: 'u1-l3-q5',
            type: 'judge',
            prompt: '判断：因为 $\\log_2 8+\\log_2 4=5$，所以 $\\log_2(8+4)=5$。',
            answer: false,
            explain: '错误。对数的加法对应真数的**乘法**而非加法。$\\log_2(8+4)=\\log_2 12\\neq5$。',
          },
          {
            id: 'u1-l3-q6',
            type: 'match',
            prompt: '把每个表达式与它的值配对。',
            left: ['$\\lg 100$', '$\\lg 1000$', '$\\lg(100\\times1000)$', '$\\lg 100+\\lg 1000$'],
            right: ['2', '3', '5', '5'],
            explain: '$\\lg(100\\times1000)=\\lg 100000=5$，恰等于 $\\lg 100+\\lg 1000=2+3=5$。',
          },
        ],
      },
    ],
  },

  // ===================== 单元 2：定义·记号·底 =====================
  {
    id: 'u2',
    title: '定义·记号·底',
    color: '#1cb0f6',
    icon: '📖',
    blurb: '把直觉写成正式定义：指对互化、底数与真数的合法条件，以及 $\\lg$、$\\ln$ 等记号。',
    lessons: [
      {
        id: 'u2-l1',
        title: '指对互化',
        subtitle: '$a^x=N\\Leftrightarrow\\log_a N=x$',
        questions: [
          {
            id: 'u2-l1-q1',
            type: 'choice',
            prompt: '把指数式 $5^3=125$ 改写成对数式，结果是？',
            options: ['$\\log_5 125=3$', '$\\log_3 125=5$', '$\\log_{125}5=3$', '$\\log_5 3=125$'],
            answer: 0,
            explain: '底数 5 不变，结果 125 是真数，指数 3 是对数的值：$\\log_5 125=3$。',
          },
          {
            id: 'u2-l1-q2',
            type: 'input',
            prompt: '把 $2^{-3}=\\dfrac18$ 改写成对数式 $\\log_2\\dfrac18=?$，填这个值。',
            accept: ['-3'],
            explain: '负指数照样适用定义：$\\log_2\\dfrac18=-3$。真数 $\\dfrac18>0$ 合法，对数的值可为负。',
          },
          {
            id: 'u2-l1-q3',
            type: 'judge',
            prompt: '判断：$\\log_5 125=3$ 与 $5^3=125$ 表达的是同一件事。',
            answer: true,
            explain: '正确。指对互化只是同一关系的两种写法：$a^y=x\\iff\\log_a x=y$。',
          },
          {
            id: 'u2-l1-q4',
            type: 'choice',
            prompt: '已知 $\\log_a 16=4$（$a>0,\\ a\\neq1$），底数 $a=?$',
            options: ['2', '4', '$-2$', '8'],
            answer: 0,
            explain: '指数化得 $a^4=16$。因 $a>0$ 舍去 $-2$，所以 $a=2$（且满足 $a\\neq1$）。',
          },
          {
            id: 'u2-l1-q5',
            type: 'input',
            prompt: '把 $4^{-2}=\\dfrac1{16}$ 改写成对数式 $\\log_4\\dfrac1{16}=?$，填这个值。',
            accept: ['-2'],
            explain: '$\\log_4\\dfrac1{16}=-2$，因为 $4^{-2}=\\dfrac1{16}$。',
          },
          {
            id: 'u2-l1-q6',
            type: 'match',
            prompt: '把每个指数式与对应的对数式配对。',
            left: ['$3^3=27$', '$5^2=25$', '$2^{-1}=\\frac12$', '$10^0=1$'],
            right: ['$\\log_3 27=3$', '$\\log_5 25=2$', '$\\log_2 \\frac12=-1$', '$\\log_{10}1=0$'],
            explain: '每条都把「底数不变、指数→对数值、结果→真数」执行一遍即可。',
          },
        ],
      },
      {
        id: 'u2-l2',
        title: '底数与真数的合法条件',
        subtitle: '$a>0,\\ a\\neq1$ 且真数 $>0$',
        questions: [
          {
            id: 'u2-l2-q1',
            type: 'choice',
            prompt: '下列对数中，在实数范围内**有意义**的是？',
            options: ['$\\log_{0.5}9$', '$\\log_1 7$', '$\\log_{-3}9$', '$\\log_4(-2)$'],
            answer: 0,
            explain: '$\\log_{0.5}9$ 底数 $0.5>0$ 且 $\\neq1$、真数 $9>0$，合法。其余分别违反底数或真数条件。',
          },
          {
            id: 'u2-l2-q2',
            type: 'judge',
            prompt: '判断：$\\log_1 5$ 没有定义，因为 $1^y$ 恒等于 1，永远到不了 5。',
            answer: true,
            explain: '正确。$a=1$ 时函数不是一一对应，反向问题没有唯一答案，所以要求 $a\\neq1$。',
          },
          {
            id: 'u2-l2-q3',
            type: 'choice',
            prompt: '使 $\\log_2(x-3)$ 在实数范围内有意义的 $x$ 取值范围是？',
            options: ['$x>3$', '$x\\geq3$', '$x<3$', '全体实数'],
            answer: 0,
            explain: '底数已合法，只需真数为正：$x-3>0\\Rightarrow x>3$，即 $(3,+\\infty)$。',
          },
          {
            id: 'u2-l2-q4',
            type: 'judge',
            prompt: '判断：$\\log_2(-8)$ 在实数范围内有意义。',
            answer: false,
            explain: '错误。$2^y>0$ 恒成立，不可能等于 $-8$，所以真数为负时无意义。',
          },
          {
            id: 'u2-l2-q5',
            type: 'choice',
            prompt: '底数必须满足 $a>0$ 的根本原因是？',
            options: [
              '否则指数函数无法在全体实数指数上稳定、连续地定义',
              '否则对数算出来太大',
              '负底数会让真数变负',
              '这只是约定俗成，没有原因',
            ],
            answer: 0,
            explain: '如 $(-2)^{1/2}$ 在实数内无意义，无理指数也无法稳定处理；需 $a>0$ 才有良好可逆的指数函数。',
          },
          {
            id: 'u2-l2-q6',
            type: 'match',
            prompt: '判断每个对数是否合法，与结论配对。',
            left: ['$\\log_2 7$', '$\\log_0 5$', '$\\log_{-2}4$', '$\\log_3 0$'],
            right: ['合法', '不合法（底数为 0）', '不合法（底数为负）', '不合法（真数为 0）'],
            explain: '走两道关：底数关 $a>0,\\ a\\neq1$ 与真数关 $x>0$。只有 $\\log_2 7$ 全部通过。',
          },
        ],
      },
      {
        id: 'u2-l3',
        title: '特殊值与常用记号',
        subtitle: '$\\log_a 1=0$、$\\log_a a=1$、$\\lg$ 与 $\\ln$',
        questions: [
          {
            id: 'u2-l3-q1',
            type: 'input',
            prompt: '求 $\\log_a 1$（$a>0,\\ a\\neq1$）。',
            accept: ['0'],
            explain: '因为 $a^0=1$，所以 $\\log_a 1=0$。所有底数的对数曲线都过点 $(1,0)$。',
          },
          {
            id: 'u2-l3-q2',
            type: 'input',
            prompt: '求 $\\log_a a$（$a>0,\\ a\\neq1$）。',
            accept: ['1'],
            explain: '因为 $a^1=a$，所以 $\\log_a a=1$。',
          },
          {
            id: 'u2-l3-q3',
            type: 'choice',
            prompt: '记号 $\\ln x$ 表示？',
            options: ['$\\log_e x$（自然对数）', '$\\log_{10}x$', '$\\log_2 x$', '$\\log_1 x$'],
            answer: 0,
            explain: '$\\ln x=\\log_e x$ 是自然对数；$\\lg x=\\log_{10}x$ 是常用对数，两者不要混淆。',
          },
          {
            id: 'u2-l3-q4',
            type: 'input',
            prompt: '求 $\\ln e^4$。',
            accept: ['4'],
            explain: '$\\ln$ 与 $e^{(\\cdot)}$ 互为反函数，所以 $\\ln e^t=t$，故 $\\ln e^4=4$。',
          },
          {
            id: 'u2-l3-q5',
            type: 'judge',
            prompt: '判断：$\\lg x$ 表示自然对数 $\\log_e x$。',
            answer: false,
            explain: '错误。$\\lg x=\\log_{10}x$ 是常用对数；自然对数才是 $\\ln x=\\log_e x$。',
          },
          {
            id: 'u2-l3-q6',
            type: 'input',
            prompt: '求 $\\log_{10}\\sqrt{1000}$（可填 3/2 或 1.5）。',
            accept: ['3/2', '1.5'],
            explain: '$\\sqrt{1000}=(10^3)^{1/2}=10^{3/2}$，故 $\\lg\\sqrt{1000}=\\dfrac32$。',
          },
        ],
      },
    ],
  },

  // ===================== 单元 3：运算法则·换底 =====================
  {
    id: 'u3',
    title: '运算法则·换底',
    color: '#ce82ff',
    icon: '🧩',
    blurb: '积、商、幂三条运算律与换底公式，全部来自指数运算律的反向翻译。',
    lessons: [
      {
        id: 'u3-l1',
        title: '积·商·幂运算律',
        subtitle: '乘法转加法、除法转减法、幂转乘法',
        questions: [
          {
            id: 'u3-l1-q1',
            type: 'choice',
            prompt: '$\\log_a(MN)$ 等于（$M,N>0$）？',
            options: [
              '$\\log_a M+\\log_a N$',
              '$\\log_a M\\cdot\\log_a N$',
              '$\\log_a M-\\log_a N$',
              '$\\log_a(M+N)$',
            ],
            answer: 0,
            explain: '积的对数 = 对数之和。来自 $a^u a^v=a^{u+v}$ 的反向翻译。',
          },
          {
            id: 'u3-l1-q2',
            type: 'input',
            prompt: '用运算律求 $\\log_2(4\\times8)$。',
            accept: ['5'],
            explain: '$\\log_2 4+\\log_2 8=2+3=5$；也可先乘得 $32=2^5$，结果一致。',
          },
          {
            id: 'u3-l1-q3',
            type: 'input',
            prompt: '化简并求值：$\\log_2 12-\\log_2 3$。',
            accept: ['2'],
            explain: '商律：$\\log_2\\dfrac{12}{3}=\\log_2 4=2$。',
          },
          {
            id: 'u3-l1-q4',
            type: 'input',
            prompt: '用幂的对数律求 $\\log_5 125$。',
            accept: ['3'],
            explain: '$125=5^3$，故 $\\log_5 5^3=3\\log_5 5=3\\times1=3$。',
          },
          {
            id: 'u3-l1-q5',
            type: 'judge',
            prompt: '判断：在实数范围内使用 $\\log_a(M^r)=r\\log_a M$ 时，通常要求 $M>0$。',
            answer: true,
            explain: '正确。负真数会破坏定义，所以使用幂的对数律前要先确认真数为正。',
          },
          {
            id: 'u3-l1-q6',
            type: 'input',
            prompt: '化简并求值：$\\log_3 18+\\log_3 6-\\log_3 4$。',
            accept: ['3'],
            explain: '合并为 $\\log_3\\dfrac{18\\times6}{4}=\\log_3 27=3$。',
          },
        ],
      },
      {
        id: 'u3-l2',
        title: '换底公式',
        subtitle: '$\\log_a b=\\dfrac{\\log_c b}{\\log_c a}$',
        questions: [
          {
            id: 'u3-l2-q1',
            type: 'choice',
            prompt: '换底公式 $\\log_a x=\\dfrac{\\log_c x}{\\log_c a}$ 中，对新底数 $c$ 的要求是？',
            options: ['$c>0$ 且 $c\\neq1$', '$c>0$ 即可', '$c$ 为任意实数', '$c=10$'],
            answer: 0,
            explain: '新底 $c$ 也是对数的底数，必须 $c>0,\\ c\\neq1$；同时分母 $\\log_c a\\neq0$ 才合法。',
          },
          {
            id: 'u3-l2-q2',
            type: 'choice',
            prompt: '用自然对数表示 $\\log_2 7$，正确的是？',
            options: [
              '$\\dfrac{\\ln 7}{\\ln 2}$',
              '$\\dfrac{\\ln 2}{\\ln 7}$',
              '$\\ln 7-\\ln 2$',
              '$\\ln 7\\cdot\\ln 2$',
            ],
            answer: 0,
            explain: '换底到自然对数：$\\log_2 7=\\dfrac{\\ln 7}{\\ln 2}$（也可用 $\\dfrac{\\lg 7}{\\lg 2}$）。',
          },
          {
            id: 'u3-l2-q3',
            type: 'input',
            prompt: '用换底化简求值：$\\log_2 3\\cdot\\log_3 8$。',
            accept: ['3'],
            explain: '$\\dfrac{\\ln 3}{\\ln 2}\\cdot\\dfrac{\\ln 8}{\\ln 3}=\\dfrac{\\ln 8}{\\ln 2}=\\log_2 8=3$，中间量相消。',
          },
          {
            id: 'u3-l2-q4',
            type: 'judge',
            prompt: '判断：换底改变了对数问题的本质，会得到不同的答案。',
            answer: false,
            explain: '错误。换底像单位转换，只改变表示方式，不改变问题本质；不同底只差一个常数比例。',
          },
          {
            id: 'u3-l2-q5',
            type: 'choice',
            prompt: '链式恒等式 $\\log_a b\\cdot\\log_b c$ 等于？',
            options: ['$\\log_a c$', '$\\log_c a$', '$\\log_b(ac)$', '$1$'],
            answer: 0,
            explain: '统一换底后中间量相消：$\\dfrac{\\ln b}{\\ln a}\\cdot\\dfrac{\\ln c}{\\ln b}=\\dfrac{\\ln c}{\\ln a}=\\log_a c$。',
          },
          {
            id: 'u3-l2-q6',
            type: 'input',
            prompt: '求 $\\log_a b\\cdot\\log_b c\\cdot\\log_c a$（$a,b,c>0$ 且均 $\\neq1$）。',
            accept: ['1'],
            explain: '三因子统一换底后 $\\ln a,\\ln b,\\ln c$ 两两相消，结果为 1。',
          },
        ],
      },
      {
        id: 'u3-l3',
        title: '恒等式与常见错误',
        subtitle: '$a^{\\log_a N}=N$ 与「和差不能拆」',
        questions: [
          {
            id: 'u3-l3-q1',
            type: 'input',
            prompt: '求 $7^{\\log_7 12}$。',
            accept: ['12'],
            explain: '$a^{\\log_a N}=N$ 是定义的另一种写法：$\\log_a N$ 正是让 $a$ 的几次幂等于 $N$ 的那个指数。',
          },
          {
            id: 'u3-l3-q2',
            type: 'judge',
            prompt: '判断：$\\log_a(M+N)=\\log_a M+\\log_a N$ 对一般的 $M,N$ 成立。',
            answer: false,
            explain: '错误。指数里没有 $a^{u+v}=a^u+a^v$ 的规律，所以和差不能直接拆。',
          },
          {
            id: 'u3-l3-q3',
            type: 'choice',
            prompt: '为什么 $\\log_a(MN)=\\log_a M+\\log_a N$ 成立，而 $\\log_a(M+N)$ 不能拆？',
            options: [
              '因为运算律对应指数中的乘除幂，而非加减',
              '因为加法太难计算',
              '因为 $M+N$ 一定为负',
              '因为底数必须是 10',
            ],
            answer: 0,
            explain: '判断变形是否可行，要看它是否来自指数运算律的反向翻译。加减没有对应规律，故不能拆。',
          },
          {
            id: 'u3-l3-q4',
            type: 'choice',
            prompt: '已知 $\\log_a 2=m,\\ \\log_a 3=n$，则 $\\log_a 12=?$',
            options: ['$2m+n$', '$m+2n$', '$mn$', '$m+n$'],
            answer: 0,
            explain: '$12=2^2\\times3$，故 $\\log_a 12=2\\log_a 2+\\log_a 3=2m+n$。先质因数分解再套运算律。',
          },
          {
            id: 'u3-l3-q5',
            type: 'judge',
            prompt: '判断：化简 $\\log_4(xy)$ 为 $\\log_4 x+\\log_4 y$ 之前，需要先要求 $x>0,\\ y>0$。',
            answer: true,
            explain: '正确。否则 $\\log_4 x$ 或 $\\log_4 y$ 无定义，运算律不成立。',
          },
          {
            id: 'u3-l3-q6',
            type: 'match',
            prompt: '判断每个变形是否正确，与结论配对。',
            left: [
              '$\\log_a(MN)=\\log_a M+\\log_a N$',
              '$\\log_a(M+N)=\\log_a M+\\log_a N$',
              '$\\log_a(M^r)=r\\log_a M$',
              '$a^{\\log_a N}=N$',
            ],
            right: ['正确（$M,N>0$）', '错误', '正确（$M>0$）', '正确'],
            explain: '只有积、幂、还原恒等式成立；和差形式没有对应的指数规律，错误。',
          },
        ],
      },
    ],
  },
]
