import type { Unit } from '../../types'

export const PART3_UNITS: Unit[] = [
  // ===================== u7 对数化简 =====================
  {
    id: 'u7',
    title: '对数化简',
    color: '#1cb0f6',
    icon: '✂️',
    blurb: '先看定义域，再把结构整理成积、商、幂；当心 $\\log_a x^2$ 的绝对值陷阱。',
    lessons: [
      {
        id: 'u7-l1',
        title: '化简前先写定义域',
        subtitle: '约分能成立，不代表条件能丢',
        questions: [
          {
            id: 'u7-l1-q1',
            type: 'judge',
            prompt: '化简 $\\log_2\\dfrac{x^2-1}{x-1}$ 时，可以先约分再考虑定义域。',
            answer: false,
            explain: '必须先写真数为正的条件（且 $x\\neq1$）。约分会把原本不合法的值偷偷带进来，所以条件要先行。',
          },
          {
            id: 'u7-l1-q2',
            type: 'choice',
            prompt: '化简 $\\log_3(27x^2)$ 为 $3+2\\log_3 x$ 时，必须附加的条件是？',
            options: ['$x\\neq0$', '$x>0$', '$x\\ge0$', '无需任何条件'],
            answer: 1,
            explain: '虽然 $x^2$ 对任意实数非负，但写成 $2\\log_3 x$ 后已要求 $x>0$。改写形式会收紧定义域，条件必须一并写出。',
          },
          {
            id: 'u7-l1-q3',
            type: 'input',
            prompt: '化简 $\\log_2(8x)-\\log_2 x$（$x>0$），结果是一个整数，填这个数。',
            accept: ['3'],
            placeholder: '一个整数',
            explain: '$\\log_2\\dfrac{8x}{x}=\\log_2 8=3$。差对应商，约掉 $x$ 后真数恒为正常数。',
          },
          {
            id: 'u7-l1-q4',
            type: 'input',
            prompt: '化简 $\\log_a\\dfrac{x^2-4}{x+2}$ 后最简结果为 $\\log_a(x-2)$，其定义域为 $x>$ 几？填这个数。',
            accept: ['2'],
            placeholder: '一个整数',
            explain: '约分得 $x-2$，要求 $x-2>0$ 且 $x\\neq-2$，故 $x>2$。$x=-2$ 处原式无定义，靠定义域挡住。',
          },
          {
            id: 'u7-l1-q5',
            type: 'choice',
            prompt: '写出 $\\log\\dfrac{x-1}{x+2}$ 的定义域条件，正确的是？',
            options: ['$x>1$', '$x>-2$', '$x<-2$ 或 $x>1$', '$-2<x<1$'],
            answer: 0,
            explain: '需 $x-1>0$ 且 $x+2>0$，取交集得 $x>1$。两个因子同正才使真数为正。',
          },
        ],
      },
      {
        id: 'u7-l2',
        title: '可化简的结构与绝对值陷阱',
        subtitle: '积商幂能拆，和差不能拆；$x^2$ 要带 $|x|$',
        questions: [
          {
            id: 'u7-l2-q1',
            type: 'judge',
            prompt: '对任意 $a>0,a\\neq1$，恒有 $\\log_a x^2=2\\log_a x$。',
            answer: false,
            explain: '当 $x<0$ 时 $\\log_a x$ 无意义而 $\\log_a x^2$ 有意义。通用恒等写法是 $\\log_a x^2=2\\log_a|x|$（$x\\neq0$）。',
          },
          {
            id: 'u7-l2-q2',
            type: 'choice',
            prompt: '$\\log_a x^2$（$x\\neq0$）通用且恒成立的化简结果是？',
            options: ['$2\\log_a x$', '$2\\log_a|x|$', '$(\\log_a x)^2$', '$\\log_a(2x)$'],
            answer: 1,
            explain: '幂指数下放前要检查底数变量是否可能为负。$x<0$ 也合法，故须写 $2\\log_a|x|$。',
          },
          {
            id: 'u7-l2-q3',
            type: 'judge',
            prompt: '$\\log_a(M+N)=\\log_a M+\\log_a N$ 是一个恒等式。',
            answer: false,
            explain: '对数只把乘除转成加减，不会把括号里的加减直接拆开。$\\log_a M+\\log_a N=\\log_a(MN)$，而不是 $\\log_a(M+N)$。',
          },
          {
            id: 'u7-l2-q4',
            type: 'choice',
            prompt: '$\\log(x+2)-\\log x$ 正确的合并结果是？',
            options: ['$\\log 2$', '$\\log\\dfrac{x+2}{x}$', '$\\log(2)$ 的相反数', '$\\log(x+2-x)$'],
            answer: 1,
            explain: '差对应商：$\\log\\dfrac{x+2}{x}$。只有当 $\\dfrac{x+2}{x}=2$（即 $x=2$）时才偶然等于 $\\log 2$，这不是恒等变形。',
          },
          {
            id: 'u7-l2-q5',
            type: 'match',
            prompt: '把下列对数表达式与正确的化简结果配对。',
            left: ['$\\log_a(MN)$', '$\\log_a\\dfrac{M}{N}$', '$\\log_a(M^r)$', '$\\log_a(M+N)$'],
            right: ['$\\log_a M+\\log_a N$', '$\\log_a M-\\log_a N$', '$r\\log_a M$', '不能再拆'],
            explain: '积→和、商→差、幂→系数；和差无法拆。判断能否拆，就看它是否对应指数运算里的乘、除、幂。',
          },
        ],
      },
      {
        id: 'u7-l3',
        title: '换底约分与 $\\lg 2+\\lg 5=1$',
        subtitle: '对数之商即换底；常用对数靠 10 的幂当锚点',
        questions: [
          {
            id: 'u7-l3-q1',
            type: 'input',
            prompt: '化简 $\\dfrac{\\log_4 9}{\\log_4 3}$，结果是一个整数，填这个数。',
            accept: ['2'],
            placeholder: '一个整数',
            explain: '$\\dfrac{\\log_a M}{\\log_a N}=\\log_N M$，故 $\\dfrac{\\log_4 9}{\\log_4 3}=\\log_3 9=2$。对数之商本质是一次换底。',
          },
          {
            id: 'u7-l3-q2',
            type: 'input',
            prompt: '化简链式相乘 $\\dfrac{\\log_2 3\\cdot\\log_3 5}{\\log_2 5}$，结果填这个整数。',
            accept: ['1'],
            placeholder: '一个整数',
            explain: '$\\log_2 3\\cdot\\log_3 5=\\dfrac{\\ln 3}{\\ln 2}\\cdot\\dfrac{\\ln 5}{\\ln 3}=\\dfrac{\\ln 5}{\\ln 2}=\\log_2 5$，与分母约掉得 $1$。',
          },
          {
            id: 'u7-l3-q3',
            type: 'choice',
            prompt: '$\\lg 2+\\lg 5$ 等于？',
            options: ['$\\lg 7$', '$1$', '$\\lg 10$ 的相反数', '$0$'],
            answer: 1,
            explain: '$\\lg 2+\\lg 5=\\lg(2\\times5)=\\lg 10=1$。这是常用对数化简最常用的锚点关系。',
          },
          {
            id: 'u7-l3-q4',
            type: 'input',
            prompt: '已知 $\\lg 2\\approx0.301$，求 $\\lg 5$（保留三位小数）。',
            accept: ['0.699', '.699'],
            placeholder: '形如 0.699',
            explain: '$\\lg 5=\\lg\\dfrac{10}{2}=\\lg 10-\\lg 2=1-0.301=0.699$。把真数拆成 $10$ 的幂与 $2$ 的组合。',
          },
          {
            id: 'u7-l3-q5',
            type: 'choice',
            prompt: '化简 $\\log_3 18-\\log_3 2+\\log_3\\dfrac{1}{3}$ 的结果是？',
            options: ['$0$', '$1$', '$2$', '$3$'],
            answer: 1,
            explain: '$\\log_3\\dfrac{18}{2}=\\log_3 9=2$，$\\log_3\\dfrac13=-1$，合计 $2+(-1)=1$。先把能凑整的项合并最省力。',
          },
          {
            id: 'u7-l3-q6',
            type: 'judge',
            prompt: '看到对数之商 $\\dfrac{\\log_a M}{\\log_a N}$ 时，应优先识别为 $\\log_N M$。',
            answer: true,
            explain: '对数的商在本质上是一次换底操作，识别成 $\\log_N M$ 往往能整段约简。',
          },
        ],
      },
    ],
  },

  // ===================== u8 指对方程 =====================
  {
    id: 'u8',
    title: '指对方程',
    color: '#ce82ff',
    icon: '🟰',
    blurb: '同底转化、两边取对数、换元；对数方程务必检验定义域、剔除增根。',
    lessons: [
      {
        id: 'u8-l1',
        title: '同底转化与两边取对数',
        subtitle: '能同底先同底，不能同底就取对数',
        questions: [
          {
            id: 'u8-l1-q1',
            type: 'input',
            prompt: '解方程 $2^{x+1}=8$，填 $x$ 的值。',
            accept: ['2'],
            placeholder: '一个整数',
            explain: '$8=2^3$，同底得 $x+1=3$，故 $x=2$。能写成同底数幂时这是最直接的解法。',
          },
          {
            id: 'u8-l1-q2',
            type: 'choice',
            prompt: '解方程 $3^x=10$，下列哪个是正确的解？',
            options: ['$x=\\log_{10}3$', '$x=\\log_3 10$', '$x=\\dfrac{\\ln 3}{\\ln 10}$', '$x=3^{10}$'],
            answer: 1,
            explain: '两边取对数：$x\\ln 3=\\ln 10$，故 $x=\\dfrac{\\ln 10}{\\ln 3}=\\log_3 10$。取对数把指数位置的未知数放到乘法位置。',
          },
          {
            id: 'u8-l1-q3',
            type: 'choice',
            prompt: '解 $3^{2x-1}=5$ 时，对 $2x-1$ 的正确处理是？',
            options: [
              '只对 $x$ 取对数，得 $x\\ln 3=\\ln 5$',
              '把整个指数 $2x-1$ 作为整体，得 $(2x-1)\\ln 3=\\ln 5$',
              '直接令 $2x-1=5$',
              '两边平方',
            ],
            answer: 1,
            explain: '整个指数 $2x-1$ 是一个整体，取对数后 $2x-1=\\log_3 5$，解得 $x=\\dfrac{1+\\log_3 5}{2}$。',
          },
          {
            id: 'u8-l1-q4',
            type: 'judge',
            prompt: '“两边取对数”是把指数位置上的未知数还原出来，因为指数函数与对数函数互为反函数。',
            answer: true,
            explain: '$y=2^x$ 与 $y=\\log_2 x$ 关于 $y=x$ 对称、互为反函数。解 $2^x=b$ 取 $\\log_2$ 正是用这条对称关系还原指数。',
          },
          {
            id: 'u8-l1-q5',
            type: 'input',
            prompt: '把方程 $7^x=20$ 的解写成以 7 为底的对数形式，填 $x=\\log_7$ 几？',
            accept: ['20'],
            placeholder: '一个整数',
            explain: '$x=\\log_7 20=\\dfrac{\\ln 20}{\\ln 7}$。无法同底时，取对数得到的就是这个对数值。',
          },
        ],
      },
      {
        id: 'u8-l2',
        title: '换元与因式分解',
        subtitle: '$(\\log x)^2$ 与 $4^x=(2^x)^2$ 都靠代换',
        questions: [
          {
            id: 'u8-l2-q1',
            type: 'choice',
            prompt: '解 $(\\log_2 x)^2-3\\log_2 x+2=0$，设 $t=\\log_2 x$，化成的方程是？',
            options: ['$t^2-3t+2=0$', '$t^2+3t+2=0$', '$2t^2-3t=0$', '$t^2-3t-2=0$'],
            answer: 0,
            explain: '令 $t=\\log_2 x$ 直接得 $t^2-3t+2=0$。看到 $(\\log x)^2$ 的二次结构，换元是标准策略。',
          },
          {
            id: 'u8-l2-q2',
            type: 'choice',
            prompt: '承上，$(\\log_2 x)^2-3\\log_2 x+2=0$ 的解集是？',
            options: ['$\\{1,2\\}$', '$\\{2,4\\}$', '$\\{0,1\\}$', '$\\{2,8\\}$'],
            answer: 1,
            explain: '$(t-1)(t-2)=0$ 得 $t=1,2$；回代 $\\log_2 x=1\\Rightarrow x=2$，$\\log_2 x=2\\Rightarrow x=4$。都满足 $x>0$。',
          },
          {
            id: 'u8-l2-q3',
            type: 'input',
            prompt: '解 $\\lg^2 x-\\lg x-2=0$（$\\lg^2 x$ 指 $(\\lg x)^2$）中较大的根，填这个整数。',
            accept: ['100'],
            placeholder: '一个整数',
            explain: '令 $t=\\lg x$，$(t-2)(t+1)=0$，$t=2$ 或 $-1$。$t=2\\Rightarrow x=100$，$t=-1\\Rightarrow x=\\tfrac{1}{10}$。较大根为 $100$。',
          },
          {
            id: 'u8-l2-q4',
            type: 'judge',
            prompt: '解 $4^x-3\\cdot2^x+2=0$ 时，令 $t=2^x$ 可化为 $t^2-3t+2=0$，且 $t>0$ 自动满足。',
            answer: true,
            explain: '$4^x=(2^x)^2$，令 $t=2^x>0$ 得 $t^2-3t+2=0$，解 $t=1,2$ 均正，回代得 $x=0,1$。无需额外筛选。',
          },
          {
            id: 'u8-l2-q5',
            type: 'input',
            prompt: '解 $2^{x+1}+2^x=12$，填 $x$ 的值。',
            accept: ['2'],
            placeholder: '一个整数',
            explain: '提公因式 $2^x(2+1)=12$，即 $3\\cdot2^x=12$，$2^x=4=2^2$，故 $x=2$。提公因式避免盲目取对数。',
          },
        ],
      },
      {
        id: 'u8-l3',
        title: '对数方程与验根剔除增根',
        subtitle: '代数正确 ≠ 对数合法：每个根都要回代定义域',
        questions: [
          {
            id: 'u8-l3-q1',
            type: 'input',
            prompt: '解 $\\log_2(x-1)=3$，填 $x$ 的值。',
            accept: ['9'],
            placeholder: '一个整数',
            explain: '按定义 $x-1=2^3=8$，$x=9$，满足 $x-1>0$。最简对数方程先改写成指数式，再回头检验真数。',
          },
          {
            id: 'u8-l3-q2',
            type: 'choice',
            prompt: '解 $\\log_3(x-2)+\\log_3(x-4)=1$，先定义域 $x>4$，解得 $x=1$ 或 $x=5$。最终答案是？',
            options: ['$x=1$ 或 $x=5$', '只有 $x=5$', '只有 $x=1$', '无解'],
            answer: 1,
            explain: '合并得 $(x-2)(x-4)=3$，$x^2-6x+5=0$，$x=1,5$。$x=1$ 使真数为负，是增根舍去；只有 $x=5$ 满足 $x>4$。',
          },
          {
            id: 'u8-l3-q3',
            type: 'judge',
            prompt: '对数方程合并或变形后，代数解出的每个根都一定是原方程的解。',
            answer: false,
            explain: '合并对数会引入不满足真数条件的增根。必须把每个根逐一回代定义域检验，例如 $\\log(x-1)+\\log(x-3)=\\log 4$ 中 $2-\\sqrt5<3$ 应舍去。',
          },
          {
            id: 'u8-l3-q4',
            type: 'choice',
            prompt: '解 $\\log_2(x+3)+\\log_2(x-1)=3$（定义域 $x>1$），解得 $x=-1\\pm2\\sqrt3$。合法解是？',
            options: [
              '$x=-1+2\\sqrt3$',
              '$x=-1-2\\sqrt3$',
              '两个都合法',
              '两个都是增根',
            ],
            answer: 0,
            explain: '$-1+2\\sqrt3\\approx2.46>1$ 合法；$-1-2\\sqrt3\\approx-4.46<1$ 是增根。只取 $x=-1+2\\sqrt3$。',
          },
          {
            id: 'u8-l3-q5',
            type: 'input',
            prompt: '解 $\\lg(x-1)+\\lg(x+2)=\\lg(3x)$（定义域 $x>1$）的唯一解为 $x=1+\\sqrt{k}$，填 $k$。',
            accept: ['3'],
            placeholder: '一个整数',
            explain: '由 $\\lg A=\\lg B\\Rightarrow A=B$ 得 $(x-1)(x+2)=3x$，$x^2-2x-2=0$，$x=1\\pm\\sqrt3$。$1-\\sqrt3<1$ 是增根，唯一解 $x=1+\\sqrt3$，故 $k=3$。',
          },
          {
            id: 'u8-l3-q6',
            type: 'match',
            prompt: '把解对数方程的各步骤与其作用配对。',
            left: ['先写定义域', '合并/改写', '解代数方程', '逐根回代'],
            right: ['锁定哪些 $x$ 合法', '把对数式转成代数式', '求出候选根', '剔除增根'],
            explain: '标准流程：定义域 → 合并 → 解代数 → 验根。代数有根不等于对数有解，最后一步剔除增根不可省。',
          },
        ],
      },
    ],
  },

  // ===================== u9 对数不等式·参数 =====================
  {
    id: 'u9',
    title: '对数不等式·参数',
    color: '#58cc02',
    icon: '⚖️',
    blurb: '真数先>0，再按底数 $a>1$ / $0<a<1$ 定方向；含参题逆推底数。',
    lessons: [
      {
        id: 'u9-l1',
        title: '底数决定不等号方向',
        subtitle: '$a>1$ 保持，$0<a<1$ 反转',
        questions: [
          {
            id: 'u9-l1-q1',
            type: 'choice',
            prompt: '当 $a>1$ 时，$\\log_a M>\\log_a N$（$M,N>0$）等价于？',
            options: ['$M<N$', '$M>N$', '$M=N$', '无法比较'],
            answer: 1,
            explain: '$a>1$ 时 $\\log_a x$ 递增，比较对数等于比较真数，不等号方向保持，故 $M>N$。',
          },
          {
            id: 'u9-l1-q2',
            type: 'choice',
            prompt: '当 $0<a<1$ 时，$\\log_a M>\\log_a N$（$M,N>0$）等价于？',
            options: ['$M>N$', '$M<N$', '$M=N$', '$M+N>0$'],
            answer: 1,
            explain: '$0<a<1$ 时 $\\log_a x$ 递减，比较真数时不等号方向反转，故 $M<N$。这是最易出错处。',
          },
          {
            id: 'u9-l1-q3',
            type: 'judge',
            prompt: '解对数不等式只要看“对数”二字，方向总与真数比较一致。',
            answer: false,
            explain: '方向取决于底数：先看底数把函数变成递增（$a>1$）还是递减（$0<a<1$），再决定真数比较是否反转。',
          },
          {
            id: 'u9-l1-q4',
            type: 'input',
            prompt: '解 $\\log_2(x+1)\\le3$，结果为 $-1<x\\le k$，填 $k$。',
            accept: ['7'],
            placeholder: '一个整数',
            explain: '定义域 $x>-1$；底数 $2>1$ 递增得 $x+1\\le8$，即 $x\\le7$。联立得 $-1<x\\le7$，$k=7$。',
          },
          {
            id: 'u9-l1-q5',
            type: 'choice',
            prompt: '解 $\\log_{1/2}(x-1)>1$ 的解集是？',
            options: ['$x>1$', '$1<x<\\dfrac32$', '$x>\\dfrac32$', '$x<\\dfrac32$'],
            answer: 1,
            explain: '定义域 $x>1$；底数 $\\tfrac12\\in(0,1)$ 递减，方向反转得 $x-1<\\tfrac12$，即 $x<\\tfrac32$。联立得 $1<x<\\tfrac32$。',
          },
        ],
      },
      {
        id: 'u9-l2',
        title: '真数>0 与定义域联立',
        subtitle: '真数为二次式时，定义域本身就是不等式',
        questions: [
          {
            id: 'u9-l2-q1',
            type: 'judge',
            prompt: '解对数不等式时，可以先去对数比较真数，最后再补真数为正的条件。',
            answer: false,
            explain: '真数为正是“哪些 $x$ 合法”的前提，必须先写。否则去对数后得到的范围可能含非法值，导致多解。',
          },
          {
            id: 'u9-l2-q2',
            type: 'input',
            prompt: '解 $\\log_2 x<3$，结果为 $0<x<k$，填 $k$。',
            accept: ['8'],
            placeholder: '一个整数',
            explain: '定义域 $x>0$；底数 $2>1$ 递增得 $x<2^3=8$。联立得 $0<x<8$，左端 $x>0$ 不能漏。',
          },
          {
            id: 'u9-l2-q3',
            type: 'choice',
            prompt: '解 $\\log_{1/3}(2x-1)\\ge-1$ 的解集是？',
            options: ['$\\dfrac12<x\\le2$', '$x\\le2$', '$x\\ge2$', '$\\dfrac12<x\\le3$'],
            answer: 0,
            explain: '定义域 $x>\\tfrac12$；底数 $\\tfrac13$ 递减反转得 $2x-1\\le(\\tfrac13)^{-1}=3$，即 $x\\le2$。联立得 $\\tfrac12<x\\le2$。',
          },
          {
            id: 'u9-l2-q4',
            type: 'choice',
            prompt: '解 $\\log_2(x-1)+\\log_2(x+1)<3$ 的解集是？',
            options: ['$-3<x<3$', '$1<x<3$', '$x<3$', '$x>1$'],
            answer: 1,
            explain: '定义域 $x>1$；合并得 $(x-1)(x+1)<8$，即 $x^2<9$，$-3<x<3$。定义域砍掉左半段，得 $1<x<3$。',
          },
          {
            id: 'u9-l2-q5',
            type: 'choice',
            prompt: '解 $\\log_3(x^2-x)\\le\\log_3(2x+4)$ 的解集是？',
            options: ['$[-1,4]$', '$[-1,0)\\cup(1,4]$', '$(1,4]$', '$[-1,0)$'],
            answer: 1,
            explain: '定义域 $-2<x<0$ 或 $x>1$；去对数得 $(x-4)(x+1)\\le0$ 即 $-1\\le x\\le4$。两段取交集得 $[-1,0)\\cup(1,4]$，易漏其中一段。',
          },
        ],
      },
      {
        id: 'u9-l3',
        title: '含参逆推底数',
        subtitle: '$a>1$ 与 $0<a<1$ 都要解，再对照题给解集',
        questions: [
          {
            id: 'u9-l3-q1',
            type: 'choice',
            prompt: '解含参不等式 $\\log_a(2x-1)>\\log_a(x+2)$（$a>0,a\\neq1$，定义域 $x>\\tfrac12$）。当 $a>1$ 时解集是？',
            options: ['$x>3$', '$\\tfrac12<x<3$', '$x<3$', '$x>2$'],
            answer: 0,
            explain: '$a>1$ 递增，方向保持：$2x-1>x+2\\Rightarrow x>3$。与定义域联立仍是 $x>3$。',
          },
          {
            id: 'u9-l3-q2',
            type: 'choice',
            prompt: '承上，当 $0<a<1$ 时 $\\log_a(2x-1)>\\log_a(x+2)$ 的解集是？',
            options: ['$x>3$', '$\\tfrac12<x<3$', '$x<3$', '$\\tfrac12<x<2$'],
            answer: 1,
            explain: '$0<a<1$ 递减，方向反转：$2x-1<x+2\\Rightarrow x<3$。与定义域 $x>\\tfrac12$ 联立得 $\\tfrac12<x<3$。',
          },
          {
            id: 'u9-l3-q3',
            type: 'choice',
            prompt: '已知 $\\log_a 3<\\log_a 5$（$a>0,a\\neq1$），则底数 $a$ 满足？',
            options: ['$a>1$', '$0<a<1$', '$a>0$', '无法确定'],
            answer: 0,
            explain: '$3<5$ 且对数值随之增大，说明函数递增，故 $a>1$。这是由不等关系反推底数的题型。',
          },
          {
            id: 'u9-l3-q4',
            type: 'choice',
            prompt: '已知 $\\log_a(x+1)>\\log_a(3-x)$ 的解集恰为 $(1,3)$，则底数 $a$ 满足？',
            options: ['$a>1$', '$0<a<1$', '$a=2$', '$a>0$'],
            answer: 0,
            explain: '$a>1$ 给解集 $(1,3)$，$0<a<1$ 给 $(-1,1)$。题给 $(1,3)$ 与 $a>1$ 吻合。逆问题须把两种底数都解出再比对。',
          },
          {
            id: 'u9-l3-q5',
            type: 'judge',
            prompt: '在含参对数不等式中，只要写出 $a>1$ 一种情况的解集就够了。',
            answer: false,
            explain: '$a>1$ 与 $0<a<1$ 给出方向相反的两个解集，缺一就会漏解或在逆问题中无法锁定底数。两种情况都考虑是解题命脉。',
          },
          {
            id: 'u9-l3-q6',
            type: 'match',
            prompt: '把底数范围与对应的单调性、方向配对。',
            left: ['$a>1$', '$0<a<1$'],
            right: ['递增，不等号方向保持', '递减，不等号方向反转'],
            explain: '底数 $>1$ 递增、方向保持；底数在 0 与 1 之间递减、方向反转。这是对数不等式的总开关。',
          },
        ],
      },
    ],
  },

  // ===================== u10 建模·线性化 =====================
  {
    id: 'u10',
    title: '建模·线性化',
    color: '#ffc800',
    icon: '📊',
    blurb: '半对数把指数拉直、双对数把幂律拉直；$\\lg$ 求位数，读斜率得参数。',
    lessons: [
      {
        id: 'u10-l1',
        title: '指数模型与半对数线性化',
        subtitle: '$\\ln y=\\ln C+kx$：斜率读增长率',
        questions: [
          {
            id: 'u10-l1-q1',
            type: 'choice',
            prompt: '对 $y=Ce^{kx}$ 两边取自然对数，结果是？',
            options: ['$\\ln y=\\ln C\\cdot kx$', '$\\ln y=\\ln C+kx$', '$\\ln y=C+kx$', '$y=\\ln C+kx$'],
            answer: 1,
            explain: '$\\ln y=\\ln C+kx$。对数把乘法型增长改写成加法型直线结构，斜率 $k$、截距 $\\ln C$。',
          },
          {
            id: 'u10-l1-q2',
            type: 'choice',
            prompt: '半对数图（横轴线性、纵轴取对数）上数据近似为直线，往往说明原关系是？',
            options: ['幂律 $y=Cx^\\alpha$', '指数 $y=Ce^{kx}$', '线性 $y=kx+b$', '对数 $y=\\ln x$'],
            answer: 1,
            explain: '半对数直线 ↔ 指数律。$\\ln y$ 对 $x$ 成直线正对应 $y=Ce^{kx}$。',
          },
          {
            id: 'u10-l1-q3',
            type: 'input',
            prompt: '将 $y=8e^{0.5x}$ 线性化为 $\\ln y=\\ln 8+kx$，填斜率 $k$（小数）。',
            accept: ['0.5', '.5'],
            placeholder: '一个小数',
            explain: '$\\ln y=\\ln 8+0.5x$，斜率即增长率 $k=0.5$，截距 $\\ln 8\\approx2.079$。',
          },
          {
            id: 'u10-l1-q4',
            type: 'choice',
            prompt: '线性化后得 $\\ln y=1.2+0.5x$，写回原模型 $y=Ce^{kx}$，则？',
            options: ['$C=1.2,\\ k=0.5$', '$C=e^{1.2},\\ k=0.5$', '$C=e^{0.5},\\ k=1.2$', '$C=1.2,\\ k=e^{0.5}$'],
            answer: 1,
            explain: '$y=e^{1.2}e^{0.5x}$，故 $C=e^{1.2}$、$k=0.5$。截距是初始规模的对数，须指数还原成 $C$。',
          },
          {
            id: 'u10-l1-q5',
            type: 'judge',
            prompt: '只要要对某个轴的数据取对数，就必须保证该数据为正。',
            answer: true,
            explain: '$\\ln 0$ 无定义、负数更不行。半对数图要求取对数那个轴的数据为正，双对数图要求两轴数据都为正。',
          },
        ],
      },
      {
        id: 'u10-l2',
        title: '幂律的双对数线性化与求位数',
        subtitle: '$\\ln y=\\ln C+\\alpha\\ln x$；$\\lfloor\\lg N\\rfloor+1$ 是位数',
        questions: [
          {
            id: 'u10-l2-q1',
            type: 'choice',
            prompt: '对幂律 $y=Cx^\\alpha$ 两边取对数，结果是？',
            options: ['$\\ln y=\\ln C+\\alpha x$', '$\\ln y=\\ln C+\\alpha\\ln x$', '$\\ln y=\\alpha\\ln C+\\ln x$', '$\\ln y=C\\ln x^\\alpha$'],
            answer: 1,
            explain: '$\\ln y=\\ln C+\\alpha\\ln x$，故在 $(\\ln x,\\ln y)$ 坐标下成直线，斜率 $\\alpha$、截距 $\\ln C$。',
          },
          {
            id: 'u10-l2-q2',
            type: 'choice',
            prompt: '双对数拟合得 $\\ln y=0.7+2\\ln x$，对应的原模型是？',
            options: ['$y=2x^{0.7}$', '$y=e^{0.7}x^2$', '$y=0.7x^2$', '$y=e^2 x^{0.7}$'],
            answer: 1,
            explain: '对照 $\\ln y=\\ln C+\\alpha\\ln x$：$\\alpha=2$，$\\ln C=0.7\\Rightarrow C=e^{0.7}\\approx2.01$。故 $y\\approx2.01x^2$。',
          },
          {
            id: 'u10-l2-q3',
            type: 'input',
            prompt: '已知 $\\lg 2\\approx0.3010$，求 $N=2^{60}$ 的位数，填这个整数。',
            accept: ['19'],
            placeholder: '一个整数',
            explain: '$\\lg N=60\\lg 2\\approx18.06\\in[18,19)$，位数 $=\\lfloor\\lg N\\rfloor+1=18+1=19$。',
          },
          {
            id: 'u10-l2-q4',
            type: 'choice',
            prompt: '数据中每当 $x$ 翻倍，$y$ 就变为原来的 $4$ 倍。这组数据最可能符合？',
            options: ['指数律 $y\\propto e^{kx}$', '幂律 $y\\propto x^2$', '线性 $y\\propto x$', '常值'],
            answer: 1,
            explain: '$x$ 乘 $2$、$y$ 乘 $4=2^2$，符合幂律 $y\\propto x^2$（$\\alpha=2$）。判别捷径：$x$ 乘倍数时 $y$ 乘的倍数是否为该倍数的固定次幂。',
          },
          {
            id: 'u10-l2-q5',
            type: 'judge',
            prompt: '若 $x$ 每增加固定量、$y$ 就乘固定倍，则该关系是指数律，应用半对数图识别。',
            answer: true,
            explain: '等差的 $x$ 对应等比的 $y$ 正是指数特征，$\\ln y$ 对 $x$ 成直线，故用半对数图。幂律则是 $x$ 乘倍数时 $y$ 乘固定次幂。',
          },
        ],
      },
      {
        id: 'u10-l3',
        title: '倍增时间、半衰期与判别',
        subtitle: '$T=\\dfrac{\\ln 2}{k}$；看哪种图变直线定模型',
        questions: [
          {
            id: 'u10-l3-q1',
            type: 'choice',
            prompt: '模型 $y=Ce^{kx}$（$k>0$）的倍增时间 $T$ 满足 $e^{kT}=2$，故 $T=$？',
            options: ['$\\dfrac{\\ln 2}{k}$', '$k\\ln 2$', '$\\dfrac{2}{k}$', '$\\dfrac{k}{\\ln 2}$'],
            answer: 0,
            explain: '由 $e^{kT}=2$ 取对数得 $kT=\\ln 2$，故 $T=\\dfrac{\\ln 2}{k}$。半衰期同理为 $-\\dfrac{\\ln 2}{k}$（$k<0$）。',
          },
          {
            id: 'u10-l3-q2',
            type: 'input',
            prompt: '某物质满足 $N(t)\\approx100e^{-0.02t}$，求半衰期（年），保留一位小数。提示 $\\ln 2\\approx0.693$。',
            accept: ['34.7', '34.65'],
            placeholder: '形如 34.7',
            explain: '$T_{1/2}=\\dfrac{\\ln 2}{0.02}\\approx\\dfrac{0.693}{0.02}\\approx34.7$ 年。半衰期把“达到一半所需时间”直接写出。',
          },
          {
            id: 'u10-l3-q3',
            type: 'choice',
            prompt: '人口 $P(t)=P_0e^{kt}$，10 年从 50 万增至 80 万。求 $k$ 用到的关键一步是？',
            options: [
              '直接令 $P_0=50$',
              '取两时刻之比 $\\dfrac{P(10)}{P_0}=1.6=e^{10k}$ 消去 $P_0$',
              '两边平方',
              '把 80 减 50',
            ],
            answer: 1,
            explain: '取比值 $\\dfrac{80}{50}=1.6=e^{10k}$ 消去 $P_0$，再取对数 $10k=\\ln 1.6$ 解出 $k\\approx0.047$。比值技巧避开对初值的依赖。',
          },
          {
            id: 'u10-l3-q4',
            type: 'choice',
            prompt: '一组数据在半对数图上明显弯曲、在双对数图上接近直线（斜率 1.5）。模型类型是？',
            options: [
              '指数模型 $y=Ce^{kx}$',
              '幂律模型 $y=Cx^{1.5}$',
              '线性模型',
              '无法判断',
            ],
            answer: 1,
            explain: '半对数弯曲否定指数模型；双对数成直线对应幂律。斜率即幂指数 $\\alpha=1.5$，故 $y=Cx^{1.5}$。',
          },
          {
            id: 'u10-l3-q5',
            type: 'input',
            prompt: '已知 $\\ln y=2-0.4x$，写回原模型 $y=Ce^{kx}$，填 $k$（小数，含负号）。',
            accept: ['-0.4'],
            placeholder: '形如 -0.4',
            explain: '$y=e^2e^{-0.4x}$，故 $C=e^2\\approx7.389$，$k=-0.4$（衰减模型）。负斜率对应衰减。',
          },
          {
            id: 'u10-l3-q6',
            type: 'match',
            prompt: '把图类型与它最适合识别的模型配对。',
            left: ['半对数图（纵轴对数、横轴线性）', '双对数图（两轴都取对数）'],
            right: ['指数增长 / 衰减', '幂律关系'],
            explain: '半对数直线 ↔ 指数律，双对数直线 ↔ 幂律。给定“哪种图成直线”即可反推模型类型。',
          },
        ],
      },
    ],
  },
]
